### ISSUE TITLE
Label expressions do not load when loading a style

### ISSUE THREAD

**Issue by AgAssist** [qgis/QGIS-Documentation#1001]
When I load a style the style expressions and setting load OK but the label expression do not load - it just stays the same as what was there prior to loading a style.

**Comment by DelazJ** [comment]
According to http://qgis.org/en/site/getinvolved/development/bugreporting.html, this kind of issue report is invalid in this repository and should be reported at hub.qgis.org
You can see that your report is already there at http://hub.qgis.org/issues/14224 and https://github.com/qgis/QGIS/pull/2929.
Closing it.
