### ISSUE TITLE
[feature] New configuration options for attribute table

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1003]
Original commit: https://github.com/qgis/QGIS/commit/dd88fa99f39ee039f0e6a387eeba5b5be62bb045 by m-kuhn
- Allow reordering the attribute table columns
- Allow adding a new column to trigger an action to the attribute table

**Comment by m-kuhn** [comment]
For reference: https://github.com/qgis/QGIS/pull/3010

**Comment by DelazJ** [comment]
should this one be closed?
