### ISSUE TITLE
QGIS does not re-install completely

### ISSUE THREAD

**Issue by lappinski** [qgis/QGIS-Documentation#1005]
Hello everyone,

I am trying to re-install QGIS Lyon on my Windows7-based CPU. The installation seems to run correctly. There are no error messages. However, in the Start Menu under QGIS Lyon the QGIS Desktop link is missing to run the software. 

![unbenannt](https://cloud.githubusercontent.com/assets/19164278/14977444/35aa3100-1114-11e6-8c60-ab69d0395ce1.JPG)

Only MSYS Shell, QSGeo4W and the GRASS GIS 6.4.4 folder appears.

Does anyone had the same problem or a sparking idea?
Thanx a lot and greetings from Berlin!

Martin

**Comment by yjacolin** [comment]
Martin,

Could you contact the QGIS Mailinglist or create a ticket in hub.qgis.org as this tickets tracking is for QGIS documentation which is not linked to you problem.

Thanks,

Y.

**Comment by lappinski** [comment]
Hello Y.,

thanks for your advice!

Martin
