### ISSUE TITLE
[FEATURE] New class QgsJSONUtils with utilities for converting
features to and from GeoJSON strings

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1012]
Original commit: https://github.com/qgis/QGIS/commit/24309dfb3a6971fd7425a1392d338d7eb9a2df87 by nyalldawson

Sponsored by Kanton of Zug, Switzerland

**Comment by yjacolin** [comment]
This is for python cookbook manual, isn't @nyalldawson

**Comment by nyalldawson** [comment]
Yes, there's no user relevant changes here.

**Comment by ThomasG77** [comment]
I've made a full sample but I need some feedback to submit a PR.
https://gist.github.com/ThomasG77/3fb933ca7de993e4a9c653b78b8a7169
Where do you think we should insert this documentation class in the current cookbook content?

**Comment by DelazJ** [comment]
@ThomasG77 though your question needs an answer, note that this feature is a 2.16 one (it doesn't mean that you shouldn't address them however)

**Comment by nyalldawson** [comment]
I'm not sure it's needed in the cookbook - the API docs are likely enough.

**Comment by havatv** [comment]
OK. Closing.
