### ISSUE TITLE
[FEATURE] Allow copying features from QGIS in GeoJSON format

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1013]
Original commit: https://github.com/qgis/QGIS/commit/c3d6c796f401ca3ed65b16511e03587cb2280d51 by nyalldawson

The previous setting for include WKT when copying features has been
replaced with a choice of copying features as "Plain text, attributes
only", "Plain text, WKT geometry" and a new "GeoJSON" option.

When set to "GeoJSON", copying features in QGIS will place a GeoJSON
text representation of the features on the clipboard for easy
pasting into other applications/javascript code.

Sponsored by North Road

**Comment by DelazJ** [comment]
Fixed in #1576
