### ISSUE TITLE
[FEATURE] Embed atlas feature into composer HTML source as GeoJSON

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1014]
Original commit: https://github.com/qgis/QGIS/commit/794ab065dc7ada524ee9b284f90ea70c8e4c75c8 by nyalldawson

This change makes the current atlas feature (and additionally all
attributes of related child features) available to the source of
a composer HTML item, allowing the item to dynamically adjust
its rendered HTML in response to the feature's properties. An
example use case is dynamically populating a HTML table with
all the attributes of related child features for the atlas
feature.

To use this, the HTML source must implement a "setFeature(feature)"
JavaScript function. This function is called whenever the atlas
feature changes, and is passed the atlas feature (+related attributes)
as a GeoJSON Feature.

Sponsored by Kanton of Zug, Switzerland

**Comment by lajunek** [comment]
@SrNetoChan Hi Alex, what does self-assigned mean,  do you work on this issue?

**Comment by SrNetoChan** [comment]
wow, I self-assigned that issue to me, in the hope of getting some time to work on it, but I never did...  Better to remove me from it

**Comment by lajunek** [comment]
@DelazJ @nyalldawson @SrNetoChan @havatv @rosaguilar @andreasneumann  Hello folks, there is the possibility to mention a code sample (placed in the HTML item source window) either in the user guide: Laying out the maps-->Layout Items-->The HTML frame item   **or**    in the training manual: 5.Module: Creating maps --> 5.3. Creating an atlas using project relations. The first alternative would only include a reduced code sample and the second would be a detailed description of an advanced way to create an atlas. What do you think?

**Comment by DelazJ** [comment]
How about both? 😈 
I'd go with the User manual first. I think this is where people may look at first. And we need to show people how concretely that works and code sample is a good way.
For the training manual it has a double interest: add an atlas oriented lesson in which we can have different levels of complexity, including using relations data (but that means people have previously been taught "relations" and I'm not sure there's such a lesson, yet.)

**Comment by SrNetoChan** [comment]
Hi, I agree with @DelazJ. I believe that features must always be described in the user manual. An example or exercise in the training manual would be great, but IMHO it is secondary.

**Comment by DelazJ** [comment]
Fixed in #4222 
Closing the issue: we don't have manpower to handle the suggestions above and i want to reduce the number of reports ;)
