### ISSUE TITLE
[FEATURE] New "Filled marker" symbol layer type

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1015]
Original commit: https://github.com/qgis/QGIS/commit/ea2014923914d21e5414b33461c8b40fe39f92dd by nyalldawson

A "filled marker" is similar to the simple marker symbol layer, except
that it uses a fill sub symbol to render the marker. This allows use
of all the existing QGIS fill (and outline) styles for rendering
markers, eg gradient or shapeburst fills.

A new abstract class QgsSimpleMarkerSymbolLayerBase has been created
from which both QgsSimpleMarkerSymbolLayerV2 and
QgsFilledMarkerSymbolLayer derive. All common code has been moved to
this base class, allowing for easy addition of new shapes or features
to both simple markers and filled markers without duplication.

Also, adds a lot of missing docs to marker symbol layers.

**Comment by havatv** [comment]
Perhaps something could be added to the "Appearance (Symbology) of Vector Layers" part of vector.rst ("Using Vector Layers")?  Would be great if someone who has experience with this could handle it.  I don't know if that part of the cookbook has been updated to QGIS 3.

**Comment by DelazJ** [comment]
>  I don't know if that part of the cookbook has been updated to QGIS 3.

Glad to see that [adding mention](https://github.com/qgis/QGIS-Documentation/commit/4353a0f8e04ead5f953af9537a17652cf594640e) in the source for writers can quickly help to answer. Changes in the symbology section stopped just before symbol layers description.

**Comment by havatv** [comment]
Mentioned in docs/user_manual/style_library/symbol_selector.rst.
If that is not enough, please reopen.
