### ISSUE TITLE
[FEATURE][cad] Implement "repeating" locking mode for constraints

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1016]
Original commit: https://github.com/qgis/QGIS/commit/e53cb6ef3c9f6fca9c7414ffd83f5927e24bea95 by nyalldawson

When enabled, repeating locks are not automatically cleared when
a new point is added. They are handy when the same constraint
must be repeated for multiple points (eg adding vertices
which are always 50 meters apart)

(fix #12605)

**Comment by SrNetoChan** [comment]
Part of this might be done in https://github.com/qgis/QGIS-Documentation/commit/cf7b76b5a1e6ed630ab23272b4cbafe6f9e7b621. I will investigate.
