### ISSUE TITLE
[FEATURE] Add style/history tab to style dock

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1017]
Original commit: https://github.com/qgis/QGIS/commit/ca914f118e070edda47af6a231c1d496e795ac43 by NathanW2

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment]
Trying to tackle this, I still wonder why there are Undo/Redo buttons within the History tab. Another pair is just at the bottom of the widget and afaics they all do the same things. Any reasons? An issue report had been filled at http://hub.qgis.org/issues/14897.
@NathanW2 ?

**Comment by NathanW2** [comment]
Mainly because there are on the QgsUndoWidget by default. It will just need
a switch to hide them if required.

**Comment by DelazJ** [comment]
Hmmmm. Maybe should we hide them. I personally find it weird to have those four buttons when the history panel is active. And this could avoid users being puzzled by "why are there 2 buttons of each?".

**Comment by NathanW2** [comment]
Go for it ;)

**Comment by DelazJ** [comment]
Thanks,
I'd love to, now that I have your consent but after I gave a quick look to the code it seems that it'll be cpp matters, something not obvious to me. Having tried fixes like that in the past, I'm afraid I'll spend more time to understand things inside the code and propose a clean PR than I'd need to fix many issues in doc repo.
So, if someone else wants to pick that issue and fix it, thanks to him/her ...

**Comment by NathanW2** [comment]
I'll see if I can fix it for the next release.
