### ISSUE TITLE
[FEATURE] [WFS provider] Add support for WFS 2.0 joins and other improvements

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1022]
Original commit: https://github.com/qgis/QGIS/commit/84a797ea86392ce5f42675f8e4b9ec52cd3e5700 by rouault

Second part of qgis/QGIS-Enhancement-Proposals#53
(QEP 35: WFS provider enhancements)
- [ ] URI parameter with sql with SELECT / FROM / JOIN / WHERE / ORDER BY clauses
- [ ] handle WFS 2.0 joins
- [ ] handle DateTime fields
~~- [ ] enable "Only request features overlapping the view extent" by default (and memorize the settings)~~
~~- [ ] rework DescribeFeatureType parsing to handle responses with several documents, and some support for attribute types being complexType~~
~~- [ ]  rework feature transfer between downloader and iterator so as to avoid uncontrolled RAM usage when the iterator cannot keep up with the downloader~~
~~- [ ] turn on WAL journaling for better reader / writer concurrency~~
~~- [ ] add retry logic based on the 'Max retry in case of tile request errors' setting (renamed 'Max retry in case of tile or feature request errors')~~
~~- [ ] error to MessageBar in case of failed download~~
~~- [ ]  in progress dialog, add a "Hide" button to mask the dialog~~
~~- [ ] improve automated testing~~
~~- [ ]  add testing of the GUI of QgsWFSSourceSelect~~

**Comment by yjacolin** [comment]
`add retry logic based on the 'Max retry in case of tile request errors' setting (renamed 'Max retry in case of tile or feature request errors')`: see in options > Network > General

**Comment by havatv** [comment]
Could this be split into more manageable issues?

**Comment by DelazJ** [comment]
It could, if that sounds better. An alternative is to use numbered list, ref the issue in commits and check each item if documented. I did it but should not prevent from split if you want. I guess some of the points are not to document and can either be checked now or struck out.

**Comment by SrNetoChan** [comment]
+1 for splitting

**Comment by lajunek** [comment]
@DelazJ @SrNetoChan @havatv In order to close all 2.x issues I will work on this issue!

**Comment by lajunek** [comment]
@DelazJ @SrNetoChan @havatv to show the join feature: can I describe this without using a PostgreSQL layer? Is this technically possible?
Following the discussions about the user manual I think we should just use shapefiles for the WFS-Layer and the join-layer

**Comment by lajunek** [comment]
@DelazJ @SrNetoChan @havatv to show the join feature: can I describe this without using a PostgreSQL layer? Is this technically possible?
Following the discussions about the user manual I think we should just use shapefiles for the WFS-Layer and the join-layer

**Comment by lajunek** [comment]
@DelazJ @SrNetoChan @havatv Hello guys, is Ives a specialist for these features so that I can get support for writing the docs for it?

**Comment by DelazJ** [comment]
Hi @lajunek 
I am reopening the feature (no idea why it was closed) and have cleaned a bit the initial report. Many items were internal, API related and not worth mentioning in the user manual or were already documented, eg [Only request .. extent](https://docs.qgis.org/testing/en/docs/user_manual/working_with_ogc/ogc_client_support.html#wfs-and-wfs-t-client) and [max retry....](https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html#network-settings)
About Yves, I can't tell. What I can suggest is to read the QEP mentioned in the initial message. While  a bit technical, it gives some ideas on what is proposed here. From my understanding:
> - [ ] URI parameter with sql with SELECT / FROM / JOIN / WHERE / ORDER BY clauses
>- [ ] handle WFS 2.0 joins

Double-click a layer in Data source manager > WFS and you get a SQL dialog shown in the QEP. I don't think we'd need to go very deep in that description and maybe we can reuse the provided screenshot if you don't find any.
>- [ ] handle DateTime fields

No idea how it's or could be exposed to users. Maybe somewhere in https://docs.qgis.org/3.4/en/docs/user_manual/working_with_ogc/ogc_client_support.html#wfs-and-wfs-t-client or https://docs.qgis.org/testing/en/docs/user_manual/managing_data_source/supported_data.html?

if really you find nobody to help you document it, if I may, don't waste your time with that. Take another ticket. and when/if we do the spring cleanup, we'll close it, documented or not.

**Comment by lajunek** [comment]
@DelazJ  ok, let's close that in the spring cleanup

**Comment by havatv** [comment]
This is covered by the statement in 18.1.3 WFS and WFS-T Client (user manual):
"In QGIS, a WFS layer behaves pretty much like any other vector layer."
