### ISSUE TITLE
[FEATURE] [WFS provider] Add support for WFS 2.0 joins and other improvements

### ISSUE THREAD

**Issue by qgis-feature-tracker** [qgis/QGIS-Documentation#1023]
Original commit: https://github.com/qgis/QGIS/commit/d4d13a4a0a2b9b4b30a4ddaf876fa610d2b063ab by rouault
Merge pull request #3018 from rouault/wfs_sql

 [FEATURE] [WFS provider] Add support for WFS 2.0 joins and other improvements

**Comment by yjacolin** [comment]
duplicate of #1022
