### ISSUE TITLE
[FEATURE] new method QgsVectorLayer::selectByExpression(...)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1028]
Original commit: https://github.com/qgis/QGIS/commit/b951d5a54d52833f4150350c15e1b7d9bef3c43b by nyalldawson

Makes it simple for scripts to select by expression. The method
also accepts a parameter which dictates whether matching features
are added to an existing selection, removed from the selection
or intersected with the current selection.

The existing code from the select by expression dialog has been
moved to QgsVectorLayer, and optimised for maximum possible speed.

Also added unit tests.

**Comment by yjacolin** [comment]
@nyalldawson could you confirm that this is for python cookbook manual?

**Comment by nyalldawson** [comment]
Yes, that would be the best place. Something like:

```
layer = QgsVectorLayer('points.shp'), 'Points', 'ogr')
layer.selectByExpression('"Class"=\'B52\' and "Heading" > 10 and "Heading" <70', QgsVectorLayer.SetSelection)
```

Might be a good example (using the points.shp file from the QGIS test suite)

**Comment by havatv** [comment]
Forgot to close this one.
