### ISSUE TITLE
[FEATURE]: possibility to set the segmentation tolerance (maximum angle or maximum difference)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1033]
Original commit: https://github.com/qgis/QGIS/commit/c0d12dcdeb87a2639479eb99c002aec877c4ec01 by mhugent

Unfortunately this naughty coder did not write a description... :-(

**Comment by yjacolin** [comment]
Text to add later (around line  235):

```
.. tip:: **Tolerance for circular string**
   Tolerance for circular string can be changed in the 
   :menuselection:`Options -> Rendering`
```

**Comment by DelazJ** [comment]
wouldn't qgis configuration more appropriate? rendering tab is "somehow" described there. and then, simply mention in the editing chapter that curve geometries can be simplified (actually, all geometries can be simplified).
If addig such information in Editing chapter, it may be useful to know the impact of simplification on feature edits

**Comment by DelazJ** [comment]
Description of this setting is available in #1491. Do we still add a schema and what would that look like?

**Comment by DelazJ** [comment]
--- Cleaning the repo---
@yjacolin what kind of image were you expecting for this issue?

**Comment by yjacolin** [comment]
To discribe this in a more visual way: `the angle in degree between the two vertex and the
   curve center or the distance in map unit between the
   segment between the two vertex and the curve line. `

**Comment by SrNetoChan** [comment]
Looking into this more carefully, I'm not sure if an image is not a bit overkill for such specific setting. But 
I can do it if necessary. I will consider this an improvement.

**Comment by yjacolin** [comment]
Could we close this ticket if schema is not needed?
