### ISSUE TITLE
[FEATURE] Add search widget wrapper for check box widget

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1040]
Original commit: https://github.com/qgis/QGIS/commit/195b4dee5ac534962fdf020baee856e9fb5b88fd by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by yjacolin** [comment]
@nyalldawson do you have any (even quick) screenshot or more information about this feature?

**Comment by nyalldawson** [comment]
I don't think this needs any documenation - I'd suggest just closing this.

**Comment by yjacolin** [comment]
neither for python cookbook?
