### ISSUE TITLE
Add description for geometry checker plugin

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#1063]

**Comment by yjacolin** [comment]
@DelazJ you tell me that this feature should be described in plugins chapter. But I think that something should be added in editing_geometry_attributes.rst file. Some though?

**Comment by DelazJ** [comment]
@yjacolin yes I think the right place to expose the whole dialog behavior is in the plugin chapter https://github.com/qgis/QGIS-Documentation/blob/master/source/docs/user_manual/plugins/plugins_geometry_checker.rst
But your remark is fair enough. We can add a note(s) or a tip(s) about the use of this plugin (and maybe about geometry snapper or topology checker) under Advanced Digitizing section or in the Configuration section. The point would be to point that there are tools to fix geometries or topology issues for a nice digitization.
Yes. Good idea to mention those tools in Editing section.

**Comment by DelazJ** [comment]
Sorry I didn't see your link earlier. Nice!

**Comment by yjacolin** [comment]
ok thank, I keep going the direction.
