### ISSUE TITLE
'Save As' and 'DXF export' feature are not documented

### ISSUE THREAD

**Issue by yjacolin** [qgis/QGIS-Documentation#1066]
I am not sure about this but can't find them in the current doc.

**Comment by DelazJ** [comment]
I'm neither aware of a dedicated chapter, though there are a lot to write about "save as"

**Comment by yjacolin** [comment]
*Save AS* is now documented in 2.14 See #1143

**Comment by yjacolin** [comment]
Same for DXF Export. Closing the issue.
