### ISSUE TITLE
Layer visibility preset and layer tree panel

### ISSUE THREAD

**Issue by yjacolin** [qgis/QGIS-Documentation#1067]
one can define several layer visibility preset to switch between one preset to another preset to modify enabled layer.

It seems that the layer tree panel is not documented at all.

**Comment by DelazJ** [comment]
something like this http://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_gui.html#map-legend ?

**Comment by yjacolin** [comment]
exactly :( do you think that Map Legend is a good name for this section? It is not only about legend. @SrNetoChan

**Comment by DelazJ** [comment]
According to the figure at the top of the GUI chapter, the layer tree (what we are actually talking about) is called map legend so I suppose this is why this term is used below

**Comment by yjacolin** [comment]
You are right but this is not true anymore, the screenshot shows something else: 'Layers Panel' which is much better than 'Map Legend'.

**Comment by SrNetoChan** [comment]
+1 for Layer Panel
