### ISSUE TITLE
[FEATURE][expressions] If a feature is passed to a function
expecting geometry inputs, then use that feature's geometry
instead of throwing an error

### ISSUE THREAD

**Issue by qgis-feature-tracker** [qgis/QGIS-Documentation#1077]
Original commit: https://github.com/qgis/QGIS/commit/7cab60bc4328e6cb4c57f8320c2d85d9383a2424 by nyalldawson

eg

buffer(@atlas_feature,100)

or

buffer(get_feature('my_layer','id=54'))

**Comment by yjacolin** [comment]
Reverted see  #1131
