### ISSUE TITLE
[needs-docs] Reword "delete" option in db connection dialog

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1080]
Original commit: https://github.com/qgis/QGIS/commit/c7a4e5a065bdf1c606e5f24d728978f0789cff17 by nyalldawson

Button has been changed to "remove", to make it clear that
the button just removes the connection, it does not delete
the database! (It was confusing for spatialite dbs)

Also add tooltips to buttons for extra clarification.

**Comment by yjacolin** [comment]
https://github.com/qgis/QGIS/pull/3420 is a similar changes for WMS and WFS (not yet backporting)
