### ISSUE TITLE
[FEATURE] Plugins can add pages to vector layer properties*

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1092]
Original commit: https://github.com/qgis/QGIS/commit/71f8e3e4bb85db27818467f4f8af761d0b267257 by nyalldawson
- This is actually a followup to 87121d, which fixes leaks
  & clarifies some docs. But I figured the ability to add
  custom pages to the properties is worth highlighting as a
  feature on it's own, or it may go unnoticed in the other
  globe related changes!

**Comment by havatv** [comment]
Is the merged pull request of @DelazJ that references this issue enough to close this one?

**Comment by DelazJ** [comment]
I'm not sure it's enough! My PR simply mentions that so users won't be surprised to have undocumented panels in the GUI but this feature is for plugin developers so its place is in the cookbook. For reference, there was recently [a discussion](http://osgeo-org.1560.x6.nabble.com/QGIS-Developer-Adding-a-panel-to-layer-properties-dialog-from-a-python-plugin-td5382217.html#a5382266) on the dev-list regarding this feature, though I wonder if it really works as i think i see related issue reports.

**Comment by tilmanb** [comment]
Can anyone point me to a plugin that does that, so I could have a look at its code and maybe write some docs for it?

**Comment by Gustry** [comment]
> Can anyone point me to a plugin that does that, so I could have a look at its code and maybe write some docs for it?

QField Sync does it FYI.

![Screenshot from 2020-09-29 11-00-37](https://user-images.githubusercontent.com/1609292/94536729-0da65100-0243-11eb-9d1a-c13d8e2efba2.png)

**Comment by DelazJ** [comment]
Anybody (@tilmanb) planning to work on this one? I realized that it's the same issue as #2071 and a similar fix (for Options dialog) was provided in #5973 with a tip for vector layer. Do we need to repeat the examples or should we consider to definitely close this with #6436

**Comment by tilmanb** [comment]
I don't plan to work on it - no time. I see no need to repeat the examples in #5973 .
