### ISSUE TITLE
[FEATURE] [mssql] Save styles to the database in MSSQL

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1098]
Original commit: https://github.com/qgis/QGIS/commit/36714d5b38858108414e1bcfef61e541e0622eed by NathanW2

Adding the functions to save styles in an mssql database.
Creates tables, etc to support default and listing styles.

**Comment by yjacolin** [comment]
@SrNetoChan For screenshot, see http://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/vector_properties.html#managing-custom-styles
