### ISSUE TITLE
[FEATURE] widgets constraints

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1101]
Original commit: https://github.com/qgis/QGIS/commit/2b1560c5be3e6c0ff5045ffdff0fd6eec0f24a94 by m-kuhn

[FEATURE] widgets constraints

**Comment by yjacolin** [comment]
See #1115

**Comment by DelazJ** [comment]
@yjacolin I'm not sure they are related issues. While this one refers to https://github.com/qgis/QGIS/pull/3079, the other one refers to `Layer Properties > Legend` new tab

**Comment by yjacolin** [comment]
indeed. I was too fast.
