### ISSUE TITLE
[FEATURE] Move QgsShortcutsManager, QgsConfigureShortcutsDialog to gui

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1103]
Original commit: https://github.com/qgis/QGIS/commit/e0c87ffe6b82bf6694d8cd13afe530c43db6d696 by nyalldawson

This allows plugins to reuse the shortcuts manager if they
want to add the ability for users to customise their shortcut
key sequences.

The shortcut manager has been extended to also handle customisation
of QShortcut objects as well as QActions.

**Comment by havatv** [comment]
And where in the cookbook could this be included?
