### ISSUE TITLE
[FEATURE] Add support for attribute renaming to QgsVectorDataProvider

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1107]
Original commit: https://github.com/qgis/QGIS/commit/58cc89019c878646e9bf010eb00d77f2865af464 by nyalldawson

Implemented in memory layer provider only, not yet supported
in edit buffer or configurable in GUI

**Comment by yjacolin** [comment]
See #1108 for complete feature.
