### ISSUE TITLE
[FEATURE] Allow renaming fields by double clicking name
in layer properties window

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1108]
Original commit: https://github.com/qgis/QGIS/commit/831f4c12b780b965e4bf2bb3286df7ef46ab1b61 by nyalldawson

Available for supported data providers only (postgres,
memory layers and OGR layers, dependant on OGR data format
and version)

**Comment by yjacolin** [comment]
See also #1109 for Oracle
