### ISSUE TITLE
[FEATURE] QgsTooltip support full HTML
This is useful for example to add URL links that
allow being clicked on.

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1113]
Original commit: https://github.com/qgis/QGIS/commit/45227e51d88a822409ef04e3c932fb10d4fc2a85 by m-kuhn

Unfortunately this naughty coder did not write a description... :-(

**Comment by yjacolin** [comment]
Nothing to add as before this commit, maptips was not full web but it was not indicated as such in the doc.
