### ISSUE TITLE
[feature] Add runtime profiler class to profile code

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1114]
Original commit: https://github.com/qgis/QGIS/commit/f8715444fb7ea299c3a9caafdecea4643b3db7e9 by NathanW2

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment]
@NathanW2 Do we have to document this?

**Comment by NathanW2** [comment]
I wouldn't at the moment.  It's a lower level API thing and not really used
at the moment.
