### ISSUE TITLE
[FEATURE] Layer tree embedded widgets

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1115]
Original commit: https://github.com/qgis/QGIS/commit/9c7dbb9e0931af6231b0a0314b60ce59decd93e0 by wonder-sk

This allows definition of widgets embedded into layer tree for individual layers in the layer properties dialog (in new Legend tab). The idea is to have a way to quickly access to some actions that are often used with a layer.

The implementation comes with transparency widget, in the future there may be more standard widgets coming, e.g. to setup filtering, selection, style or other stuff. The API allows plugins to register their own widgets, which will be useful for various domain specific plugins to assign custom widgets to layers they manage.

**Comment by havatv** [comment]
Is there a natural place for this in the cookbook?

**Comment by ghtmtt** [comment]
I would say no.
