### ISSUE TITLE
Tables are truncated and unreadable in the PDF version 

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#1135]
In the PDF version of the user manual many tables in the Expression Chapter are wrongly rendered ( table truncated at the end of page, column truncated, mixed texts of different columns..) Just unusable I'm afraid.

**Comment by DelazJ** [comment]
Actually, it's not only tables (see `Expression` chapter) that are truncated in the pdf doc. Code samples or links are also affected.
Some examples in the `QGIS as OGC Data Server` chapter, leading to incomplete and thus meaningless commands

**Comment by DelazJ** [comment]
I think i'm about to give up :'(
One of the above commits has fixed the big table of geometry functions wider than the page (with a lot of truncated description). And it's (obviously )very nice. But at the same time it fails to fix the same issue on variable table (less dramatic - though it's dramatic I can't find what is missing there).

But the remaining bad thing is how LateX (?) distribute the width of the columns. Sometimes, the first column, which ideally should be display in one line, is larger than needed (blank space) or too small (so that words are split on many lines or, --worse-- overlap words of the other column).

Unless someone has hints to propose, I think i'm done for now with this issue.

**Comment by yjacolin** [comment]
:( thanks to have tried !

**Comment by ghtmtt** [comment]
@DelazJ even if for another project I had the same problem: the only way I was able to fix that was to create some Latex style file and using the `.. row:` directive. So no easy fix found..

**Comment by DelazJ** [comment]
Could you point to that or an example? I didn't check recent pdf docs to see how table and code samples are rendered but some were unusable in older docs so if there's a way to improve this...
