### ISSUE TITLE
Add description for "Variables" option

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#1145]
"Variables" seem to be one amazing capability people should know about

**Comment by SrNetoChan** [comment]
Is this something for general tools?

Great starting point for this:
http://nyalldawson.net/2015/12/exploring-variables-in-qgis-2-12-part-1/
http://nyalldawson.net/2015/12/exploring-variables-in-qgis-pt-2-project-management/
http://nyalldawson.net/2015/12/exploring-variables-in-qgis-pt-3-layer-level-variables/

**Comment by yjacolin** [comment]
Thanks @SrNetoChan we are just discussing where to integrate them in the PR :)
