### ISSUE TITLE
Show local TOC in GitHub file preview

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#1155]
A followup to #1152 fix that ends up with the removal of per file TOC from pdf doc but also from GitHub preview. Might be nice to find a way to get back the local contents in GitHub.

**Comment by ghtmtt** [comment]
ping @DelazJ do you think this is still an issue?

**Comment by DelazJ** [comment]
yes please! it's my "Moby Dick"! Not seeing by default the file structure when writing some big texts annoys me. From time to time, I test if it works but no success yet.

**Comment by havatv** [comment]
Time to give up this one, @DelazJ?

**Comment by DelazJ** [comment]
Yeah. Time to give up, Håvard.
