### ISSUE TITLE
Chapter loaded but not visible in the index

### ISSUE THREAD

**Issue by ghtmtt** [qgis/QGIS-Documentation#1158]
Hi..
in the past days I've added 2 R chapter in the training manual and they have been merged into the master branch.. 

The chapter have been added in the Training Manual index and they are loaded in the server:

http://docs.qgis.org/testing/en/docs/training_manual/processing/r_syntax.html
http://docs.qgis.org/testing/en/docs/training_manual/processing/r_syntax-table.html

but they are not visible in the main index..

http://docs.qgis.org/testing/en/docs/training_manual/processing/index.html

is this a normal behavior or something is missing? 

Thanks

**Comment by yjacolin** [comment]
Probably not, but the 2 first links you gave are in the table of content of the third. It shows chapter 17.32 and 17.33 with their subsection (only the first level under the chapter).

![contents or R scripts1](https://cloud.githubusercontent.com/assets/660191/16409366/6dc56c1e-3d1d-11e6-8e4b-73d7e1123323.png)

**Comment by ghtmtt** [comment]
mmm that's weird.. I mean in the main index of the training manual (so the third link) there are not the 2 additional chapters.. or do you see them?

**Comment by yjacolin** [comment]
Yes, the screenshot I made is from: http://docs.qgis.org/testing/en/docs/training_manual/processing/index.html

Could be a cache issue?

**Comment by ghtmtt** [comment]
super weird.. I see it now.. maybe I had the cache full.. sorry for the noise.. and thanks for the support!
