### ISSUE TITLE
Add Vertex Editor panel to Digitizing existing layer

### ISSUE THREAD

**Issue by SrNetoChan** [qgis/QGIS-Documentation#1159]
There is now a vertex editor panel, that is opened once you click the node tool. The tool is useful to select the nodes (and works together with the node tool), edit vertex coordinates, but also Z and M coordinates if the layer have them.

**Comment by DelazJ** [comment]
I'm currently rewriting the Editing chapter so took this into charge (see https://github.com/qgis/QGIS-Documentation/compare/master...DelazJ:edittools?expand=1#diff-2c43ad55938d7361885be1e947c728b1R369). Thanks for the precision about M handling

**Comment by SrNetoChan** [comment]
@DelazJ Let me know when you need screenshots. And what you need.

**Comment by DelazJ** [comment]
It could be a vertex Editor dialog showing x,y,r (and maybe z or m) values filled and some rows selected. And in the canvas, showing the feature nodes (and the selected ones)
Does it sound good? we show a feature being edited with node tool and behavior of node selection in both canvas and panel.

**Comment by SrNetoChan** [comment]
Sounds good, I will try to push it to your branch
