### ISSUE TITLE
Adapt the screenshot in PanelToolbar section

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#1173]
The screenshot in [PanelToolbar section](http://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html#panels-and-toolbars) shows a list of toolbars while the section is all about panels.
Could be nice to replace it with one showing panels and move the existing one under [Toolbar](http://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_gui.html#toolbar) section

Another queston: the text states that "These menus are in  Settings (for Linux) or View (Windows)" . Is really Settings the right menu (under KDE I assume, given that the screenshot is from Linux)?

**Comment by SrNetoChan** [comment]
Good catch! On ubuntu it's still in the view menu. @yjacolin confirms that it's in a different place in KDE.

I like the idea of having information under the configuration chapter about how to turn on and off both  toolbars and the panels. But maybe panels explanation is the one that is not suited to be here... if this is configuration, why are we explaining here what each panel is useful for? 

Also, we only explain 3 panels, when we have a lot more (they are probably explained else where).

Maybe move everything to the GUI part?

**Comment by DelazJ** [comment]
I think you are right!

**Comment by DelazJ** [comment]
Fixed
