### ISSUE TITLE
Explain the "Rotate Point Symbols" advanced digitizing tool

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#1178]
Unable to use that tool following description in http://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/editing_geometry_attributes.html#rotate-point-symbols. I think the process has evolved meanwhile --> Update the description.

**Comment by yjacolin** [comment]
Milestone 2.16 to focus only on new feature for 2.14 if you don't mind.
