### ISSUE TITLE
Orienteering map symbols (IOF ISOM)

### ISSUE THREAD

**Issue by Symbian9** [qgis/QGIS-Documentation#1179]
Is O-maps symbol set availiable in QGIS now?
http://lists.osgeo.org/pipermail/qgis-developer/2007-January/001475.html

**Comment by DelazJ** [comment]
Please ask this question in qgis-developer or qgis-user mailing list. You'll find information on QGIS support channels at http://www.qgis.org/en/site/forusers/support.html
This repository is for issues related to QGIS Documentation. Closing...
