### ISSUE TITLE
Add Nyall content into documentation

### ISSUE THREAD

**Issue by yjacolin** [qgis/QGIS-Documentation#1187]
See comments in https://github.com/qgis/QGIS-Documentation/pull/1164. Nyall wrote a nice article in 3 parts about the use of variable. We currently add three links into the documentation but Nyall kindly propose to change the licence to include the text directly inside the documentation. It could be done:
- either directly in the chapter
- in appendix
- somewhere else

**Comment by SrNetoChan** [comment]
We need to add information about variables in the Vector Layer Properties.

**Comment by DelazJ** [comment]
Something like http://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html#variables-tab?

**Comment by SrNetoChan** [comment]
@DelazJ Yes, something similar to that. Besides, in the following section, we should mention that it's possible to set and use variables at Layer and composition level.
 http://docs.qgis.org/testing/en/docs/user_manual/introduction/general_tools.html#use-of-variables-for-dynamic-content

I will give it a try and create a PR for that.

**Comment by DelazJ** [comment]
Then a similar section might be needed under http://docs.qgis.org/testing/en/docs/user_manual/print_composer/composer_items/composer_items_options.html for composer stuffs

**Comment by SrNetoChan** [comment]
@DelazJ Indeed, I'm working on it.

**Comment by SrNetoChan** [comment]
After all the description about variables added in several places, can we close this? @DelazJ @yjacolin ?

**Comment by SrNetoChan** [comment]
After #1704, can we close this one? Nyall content is linked, and I don't think we will ever be able to add them to the Docs itself.

**Comment by DelazJ** [comment]
Agreed
