### ISSUE TITLE
[FEATURE] Mouse wheel over sliders in color dialog to change value by
increments

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1204]
Original commit: https://github.com/qgis/QGIS/commit/c63f9c9e8b97884b63e4a779bc207aeb3cbcac95 by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment]
Cherry-picked from #1181

**Comment by DelazJ** [comment]
I'm not sure this is worth documenting. See it in action at http://qgis.org/fr/site/forusers/visualchangelog218/index.html#feature-add-custom-color-schemes-to-color-button-drop-down-menu. Opinions?
