### ISSUE TITLE
Fix Me link at the bottom of 2.14 doc

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#1205]
There's a `fix me` link at the bottom of 2.14 doc pages to reach the github repo. There wasn't such a link for 2.8 doc: only the one to reach transifex.
I think it's good to have that link to directly fix issues in the released doc (some minor issues may need fixes in the future). but currently that link points to `master` branch instead of `manual_en_v2.14`.
Others, what do you think: should we keep the link for textual fixes and link it to `manual_en_v2.14` branch or remove it?
@rduivenvoorde @yjacolin @SrNetoChan

**Comment by rduivenvoorde** [comment]
@DelazJ mmm, I think I forgot to hide the fixme link in 2.14 after branching. Because the idea is that people should go to 'testing' to see the lastest version of a document page. And only fix THAT version.

We did not fix pages of older versions anymore.

For translating: only(!) latest stable (currently 2.14) is translated. So to be sure, I actually have to rebuild 2.8 docs again and remove the fixme link there from the template...

Problem with fixing (little) things in older versions then testing (even 2.14) is that fixing breaks the translation strings. Though not sure if it is worth NOT fixing errors in it..

Please let me know. At least the two different versions then should link to the two different branches!

**Comment by DelazJ** [comment]
@rduivenvoorde : 
> Problem with fixing (little) things in older versions then testing (even 2.14) is that fixing breaks the translation strings. Though not sure if it is worth NOT fixing errors in it.. 

Yes, you point the underlying question:  is 2.14 supposed to be pushed to transifex once for all? Looking at [2.8 history](https://github.com/qgis/QGIS-Documentation/commits/manual_en_v2.8), it appears that 2.8 has got commits after release and I wonder if it hasn't been updated in transifex.
One thing that I think might need improvement is the training manual which might be deprecated for 2.14; we barely worked on it.

Moreover I'd be interested to see statistics of testing pages consultation. Are there so many people other than writers using testing ? Until today, I personally often send released version link to people on forums (from now it's 2.14). And I only came to use testing when 2.8 doc became really deprecated and that I become documenter.

**Comment by yjacolin** [comment]
I think we can make some update and push the new translation string to transifex some time before the new release.

Testing Doc can be found by google (I remember found it the last week if I am not wrong).

**Comment by DelazJ** [comment]
@yjacolin:
> I think we can make some update and push the new translation string to transifex some time before the new release.

Which release do u mean? 2.18?

**Comment by yjacolin** [comment]
I meant "in general". I think the final process should be: before the finale release, push to transifex to update translation at the best we can. After the finale release, push again to transifex to update the last string.

For langage with not enought people, that doesn't change anything, for bigger translation team, like fr, we have a documentation almost ready.

For 2.18 vs 3.0 documentation, I am +1 for working only for 3.0 release. I am not sure that the 2.16 will be so much different than 2.18. We can push some update in 2.16 branch for "2.18" and just say that this is only for 2.18 (there is a rst tag for such thing, used a lot in mapserver documentation for example). If we do so, these updates will be lost for 3.0 documentation and the work done once again.

**Comment by rduivenvoorde** [comment]
@yjacolin, @DelazJ  just to be sure: do you think there will be a true translated build of either 2.16 OR 2.18?    2.14(!) is current latest translated build.

My idea would be (but fine to discuss this) is to let 2.14 be the latest 2.x version of the docs. My argument would be: it is the latest LTR...

IF 3.0 takes longer, we could maybe(!) decide to make a 2.18 (translated) version, and drop 2.14 translation at that time.. BUT we really have to be carefull then to NOT include 3.0 fixes/changes then into the master/testing documentation....

Also: I'm just not in favour of doing to much on 2.x. I hope to fully concentrate on 3.x version of QGIS...

**Comment by DelazJ** [comment]
@rduivenvoorde said:

> @yjacolin, @DelazJ just to be sure: do you think there will be a true translated build of either 2.16 OR 2.18? 2.14(!) is current latest translated build.

Translated build? I'd say no; imho there's no need to have translators doing such a job for a non-ltr version and I think this is something we've talked about few months ago. Couldn't find the thread.
Will there be a doc released for these versions? I remembered we talked about releasing (not always translated) doc for each release from 2.14. But this is somehow the question I'm asking myself as the thread [Managing a future 2.18 or 3.0 documentation?](http://osgeo-org.1560.x6.nabble.com/Managing-a-future-2-18-or-3-0-documentation-td5277232.html) goes on. Actually, given the experience of 2.14 (and previous releases) and assuming the team doesn't really grow, I'm not sure we'll have all 2.16 issues fixed when 2.18 is released. 

> My idea would be (but fine to discuss this) is to let 2.14 be the latest 2.x version of the docs. My argument would be: it is the latest LTR...
IF 3.0 takes longer, we could maybe(!) decide to make a 2.18 (translated) version, and drop 2.14 translation at that time.. BUT we really have to be carefull then to NOT include 3.0 fixes/changes then into the master/testing documentation....

Sounds reasonable. But that means 2.18 issues should be clearly identified with the convenient milestone tag (--> create a 2.18 milestone). In the thread linked above, some argue for a 2.18 doc as it'll be the last 2.x version.

> Also: I'm just not in favour of doing to much on 2.x. I hope to fully concentrate on 3.x version of QGIS...

I do not really understand this part of the comment. working on 2.x doc isn't like preparing work on 3.x? Will there be so many differences between the two? While PYQGIS doc may be more impacted due to API Break, I suppose that most of the features in 2.x will stay in 3x. So unless i miss something, working hard on 2.x doc sounds good for 3.x

**Comment by DelazJ** [comment]
@rduivenvoorde Thanks for fixing the `Fix Me` link at the bottom of 2.14 doc pages.
Can we close this report (are all subjects treated)?

**Comment by rduivenvoorde** [comment]
@DelazJ  yes, but not sure what is decided now about the 2.16/2.18 branches. Are we creating working branches for those? Or do we start first only doing 2.16 issues in master, then 2.18 in master etc, so we can branch when we want from master?

**Comment by DelazJ** [comment]
I'd be in favor of the second scenario: keep working in master branch with 2.16 issues first and branch when we want. It's more easier to maintain (and follow) I think. Note that there are currently only [3 issues reported for 2.18](https://github.com/qgis/QGIS-Documentation/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22QGIS+2.18%22)

**Comment by yjacolin** [comment]
Let's go to this scenario if everybody are ok with this.
