### ISSUE TITLE
Can`t find neither r_intro.qps nor sample_points.shp in training_manual_exercise_data.zip

### ISSUE THREAD

**Issue by evgeniusb** [qgis/QGIS-Documentation#1206]
There is a sentence: "Open the :file:`r_intro.qps` QGIS project" here:
 QGIS-Documentation/source/docs/training_manual/processing/r_intro.rst
Creating plots.
But neither r_intro.qps nor sample_points.shp were found.
Could you explain or fix it, please.

Evgeny.

**Comment by ghtmtt** [comment]
you are right.. it seems that if you download the zip of the training manual data as described here

http://docs.qgis.org/testing/en/docs/training_manual/foreword/preparing_data.html#preparing-exercise-data

some dataset are missing.. I'll try to investigate it!

**Comment by DelazJ** [comment]
data available in https://github.com/qgis/QGIS-Training-Data/tree/master/training_manual_data/processing/r_intro
