### ISSUE TITLE
[FEATURE] Add an option to show user color schemes menus

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1208]
Original commit: https://github.com/qgis/QGIS/commit/693d45a99916bb5bb20f84b6a2d2fbd7b04a1ca4 by nyalldawson

This adds the ability for users to set whether a user created
color scheme should show up in the color button drop-down menus.

It's accessed through the color picker dialog, on the lists tab.
Just add a new color scheme, then from the scheme menu tick the
new "show in buttons" option.

Handy if you have sets of common palettes and want them to be
instantly available through the color menu.

(cherry-picked from 12a21474276322084e9c67ad46dd68aa486c34f1)

**Comment by DelazJ** [comment]
cherry-picked from #1207
