### ISSUE TITLE
[FEATURE] Label polygons using curved labels along perimeter

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1210]
Original commit: https://github.com/qgis/QGIS/commit/5f33991e7bcd95069ba88e01cafa7078bbad5f24 by nyalldawson

This adds a new mode for labeling polygons, where the perimeter
of the polygon is labeled using curved labeling.

**Comment by DelazJ** [comment]
duplicate of #1273
