### ISSUE TITLE
[FEATURE] Expression function for calculating geometry boundary

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1213]
Original commit: https://github.com/qgis/QGIS/commit/1a4ceb1680e9adb4dd78c1bc11887c5a05ba0d19 by nyalldawson

The new 'boundary(...)' function returns a geometry's topological
boundary, ie for polygons this is a multilinestring representing
the polygons rings

**Comment by DelazJ** [comment]
duplicate of #1272
