### ISSUE TITLE
Add explanation of CSVT files

### ISSUE THREAD

**Issue by nickbearman** [qgis/QGIS-Documentation#1214]
I think it would be useful to add a note about reading CSV files and how to create and include CSVT files so that numbers are read as numbers rather than strings (as per https://anitagraser.com/2011/03/07/how-to-specify-data-types-of-csv-columns-for-use-in-qgis/). 

Is this section (http://docs.qgis.org/2.14/en/docs/user_manual/working_with_vector/supported_data.html#loading-a-delimited-text-file) a suitable place to do this or if someone knows the manual better than I do, is there a better please? I couldn't find any reference to CSVT anywhere in the documentation. 

If so, I will do a suitable PR when I get a moment. 
Best wishes,
Nick.

**Comment by yjacolin** [comment]
feel free to send a PR :)

**Comment by nickbearman** [comment]
Thanks, done #1226
