### ISSUE TITLE
[FEATURE] API + expression function for merging linestrings

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1219]
Original commit: https://github.com/qgis/QGIS/commit/10c92394e7ccacb7dacef163f04ae7bdc0d910b1 by nyalldawson

Adds a new method to QgsGeometry for merging linestrings.
By passing a multilinestring, any connected lines will
be joined into single linestrings. Behind the scenes this
uses GEOS' line merge.

A corresponding expression function "line_merge" has also
been added.

**Comment by DelazJ** [comment]
duplicate of #1271
