### ISSUE TITLE
Rename visibility presets to map themes

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1229]
Original commit: https://github.com/qgis/QGIS/commit/3e33e686c14dc863e55c923f748add4a6d19b6c0 by m-kuhn

Because it is not only more descriptive for what it does but also
sounds more interesting.

[needs-docs]

**Comment by anitagraser** [comment]
@m-kuhn Has the Command line option –dxf-preset been renamed? If yes, what's its new name? See:
https://docs.qgis.org/testing/en/docs/user_manual/introduction/getting_started.html?highlight=visibility%20presets

**Comment by m-kuhn** [comment]
I don't think so because I can see it here https://github.com/qgis/QGIS/blob/master/src/app/main.cpp . I've never used this option.

**Comment by anitagraser** [comment]
Ok, then I think all necessary doc updates are done.

**Comment by m-kuhn** [comment]
Oh, great news. Thank you @anitagraser !

**Comment by andreasneumann** [comment]
hm - I am not so sure it is a good idea. Have you discussed this with some native speakers?

Visibility presets are combinations of layer visibilities and styles. Not sure if map theme is the best term to describe this combination.

Besides, visibility presets have been around for some time now (in fact for several versions already). We should not arbitrarily rename terms without discussing it first.

**Comment by andreasneumann** [comment]
To me, the "theme" of a map is the subject or content of the map - not the style or the layer visibility.

**Comment by anitagraser** [comment]
@andreasneumann there was already some discussion on the commit: https://github.com/qgis/QGIS/commit/3e33e686c14dc863e55c923f748add4a6d19b6c0.

> To me, the "theme" of a map is the subject or content of the map - not the style or the layer visibility.

In my understanding "layer visibility" is "content of the map", so I don't see a contradiction here.

**Comment by DelazJ** [comment]
@anitagraser I think that  the description of the dxf-preset (@m-kuhn should we keep  this name (for consistency)?) option would still need an update
@andreasneumann I'm also bugged by this expression (although the new name could more suggest why people would use this option than "preset visibility" did) but no proposal in mind...

**Comment by andreasneumann** [comment]
It's not so easy to find the correct term that is both meaningful (describing what it actually does) and easy for the users. I am fine with "map theme" - just wanted to know if it was discussed (also with native speakers).

In this particular example what annoys me most, is that for 1.5 year I've taught users of our QGIS courses about "visibility presets" and then several releases later, it is renamed to "map themes". Perhaps for the future it would be best to discuss terms early on to get it right already in the first release and not rename three versions later ...

But as I said, if there are good reasons for the renaming I am ok with it. Sorry for the fuss.

**Comment by m-kuhn** [comment]
The term *visibility preset* originally was on point because it only controlled "a combination of visible layers". Then the scope changed and styles for the layers were added, that's why the original name no longer was consistent with the functionality itself. I think the release 3.0 is a good point in time to adjust this and I hope the new term is accurate for the functionality itself.

On the dxf preset side, I've got no idea, since I've never used it myself.

**Comment by andreasneumann** [comment]
The DXF export uses the exact map themes (both with layer visibilities and styles), alias visibility presets then QGIS itself. So it should be changed there as well.

**Comment by m-kuhn** [comment]
What should it be? `--dxf-map-theme`?

**Comment by andreasneumann** [comment]
yes - unless @jef-n thinks different .

**Comment by DelazJ** [comment]
closed in #2278
