### ISSUE TITLE
[FEATURE] Ability to cancel rendering of rasters + WMS/WCS support

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1233]
Original commit: https://github.com/qgis/QGIS/commit/b6b5afd8859e28f3be76c81129a12015c1e17825 by wonder-sk

The improvement allows immediate cancellation of raster rendering
in progress. Until now, even when map rendering got cancelled
(e.g. by zooming of panning canvas), the GUI got blocked while waiting
for raster layers to finish their rendering (only vector layers have
had support for cancellation). This should allow for much smoother
user experience while browsing maps including rasters.

The cancellation is supported currently by WMS/WMTS and WCS providers.
GDAL provider may also get support thanks to improvements in GDAL 2.

Funded by Land Information New Zealand.

**Comment by havatv** [comment]
I don't think this needs to be documented.

**Comment by havatv** [comment]
> two ideas:
> 
>     1. for the pyqgis thread chapter [qgis/QGIS@b6b5afd#diff-2137c5ebefd06b15a5ccd273faf92573R21](https://github.com/qgis/QGIS/commit/b6b5afd8859e28f3be76c81129a12015c1e17825#diff-2137c5ebefd06b15a5ccd273faf92573R21)

That is good idea for an enhancement, but it is not directly connected to this.
So if someone would like to have more about the use of feedback, a new
issue should be created.

>     2. as a tip in map canvas description: eg `if map canvas takes time to update due to different reasons (...) you can cancel it pressing...` (_i don't know how the cancelation is done by the user_)

This is about support for cancellation, not about the ability to utilise it in the GUI.
