### ISSUE TITLE
[FEATURE][processing] add search to Get Scripts and Models dialog (fix #12067)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1235]
Original commit: https://github.com/qgis/QGIS/commit/592c33f41ee51d5782dd6d032317ece231651db1 by alexbruy

Unfortunately this naughty coder did not write a description... :-(

**Comment by ghtmtt** [comment]
Get Script and Model is not in Processing anymore. Closing this outdated issue
