### ISSUE TITLE
Keeping OpenLayers Plugin presentation in Training manual?

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#1239]
Given the recent discussion on OpenLayers plugin in dev mailing list, do we keep it in the training manual (see https://docs.qgis.org/testing/en/docs/training_manual/qgis_plugins/plugin_examples.html#basic-fa-the-openlayers-plugin)?

**Comment by yjacolin** [comment]
I think we should keep it as:
* there is a new version (still maintained)
* it still well known
* it doesn't break any licence right

**Comment by DelazJ** [comment]
ok!
