### ISSUE TITLE
Processing no longer have simplified and advanced view

### ISSUE THREAD

**Issue by SrNetoChan** [qgis/QGIS-Documentation#1247]
Processing no longer have simplified and advanced view. (Since 2.14 I think)

It's still mention in trainning

http://docs.qgis.org/testing/en/docs/training_manual/processing/set_up.html

**Comment by DelazJ** [comment]
@volaya @alexbruy  any reference/idea of what's the rule now? Which providers fill the default view (speaking of QGIS 2.x series)? I recall discussion about the changes but couldn't find it. Thanks

**Comment by volaya** [comment]
All providers without 3rd party dependencies are enabled by default

Notice that in 3.0, some providers have been removed, like LiDAR tools, OTB, etc. The idea is to have only GDAL, SAGA and the native ones, if possible
