### ISSUE TITLE
Remove training manual exercise data from http://qgis.org/downloads/data/

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#1248]
These data are no longer up to date
And what's the future of that page?

**Comment by yjacolin** [comment]
I discussed with @rduivenvoorde about this page and data. We are going to use only tar.gz for sample data and we can remove the training data.

- @rduivenvoorde could you remove the training data from this?
- Any idea where are the custom data for the training manual? The introduction said that this is OSM data and that some chapter can have specific/custom data.

**Comment by rduivenvoorde** [comment]
@DelazJ why is the data no longer uptodate? Not working? Or not working with the excersises?
For what I know the data is still used? I even updated a gml file today (both in zip and tar.gz).

The custom data for the training manual... if I'm sure we already found these @timlinux did you not let one of your guys search for it? That data is actually in github: https://github.com/qgis/QGIS-Training-Data and should be kept uptodate there.

For the Sample data, we SHOULD put it in github (I will do that), and be exported periodically exported both as zip and tar.gz. While .zip is easier for most users, the tar.gz version is easier to incorporate in the nsis installer (in the windows installer you can tick a checkbox to grab and untar it to a folder). So we will provide both. I will put the data in Github plus a shell script to create and download the data to the right folder (to be run as a cronjob on the qgis server).

Or is the data really so old that it is not to be used anymore...

**Comment by DelazJ** [comment]
> @DelazJ why is the data no longer uptodate? Not working? Or not working with the excersises?
For what I know the data is still used?

Good question. I have no sure idea (reason why an issue report should be as clear and referenced as possible). For what i can remember, there were issues with sample data provided for the training manual. Those have been updated in the training manual data repo (but only there) and all the links in the training manual doc point to the data repository now. 
Also, I think we should keep a single place to maintain and download files.

I do not understand the rest of your message (I guess a part of the discussion was held face to face during the hackfest).

**Comment by pcav** [comment]
Sorry, I did not follow the discussion closely: where are updated data?
Thanks.

**Comment by DelazJ** [comment]
Give a look to https://github.com/qgis/QGIS-Training-Data/pull/5 and specifically https://github.com/qgis/QGIS-Training-Data/pull/3

**Comment by DelazJ** [comment]
What's the status of this issue? It seems that http://qgis.org/downloads/data/ has been updated (but not the training_manual_exercise_data). And If training data are available there, what is the purpose of the training-data repository (and its versionning zip link mentionned in the training manual)?

I think we should not present different links (with different data?) to the end users.

**Comment by ghtmtt** [comment]
ping @DelazJ @rduivenvoorde 

The link in the Training Manual that points to the data in the github repo (I'm updating the repo periodically when new exercises are added):

https://docs.qgis.org/testing/en/docs/training_manual/foreword/foreword.html#data

while the main manual https://docs.qgis.org/testing/en/docs/user_manual/introduction/getting_started.html?highlight=sample#downloading-sample-data points to qgis.org

datasets are different and the gihub repository contains just the data of the training manual. I don't have strong opinion on that and since people are not complaining for this it could be overkilling to have 2 different repositories or the data.

**Comment by yjacolin** [comment]
@ghtmtt or two branches? Much more useful as branch are already used for the different release for the training manual.

**Comment by ghtmtt** [comment]
@yjacolin yes also.. no problem with different branches ;)

**Comment by madanksuwal** [comment]
I am trying find data for **9.4. Lesson: Supplementary Exercise**. 
The give link of dropbox is no more working. 
https://www.dropbox.com/s/q5evvkizuunrcs0/more_analysis.zip?dl=0

May I request for the data here. 
thanks.

**Comment by havatv** [comment]
> I am trying find data for **9.4. Lesson: Supplementary Exercise**.
> The give link of dropbox is no more working.
> https://www.dropbox.com/s/q5evvkizuunrcs0/more_analysis.zip?dl=0
> 
> May I request for the data here.
> thanks.

This has been fixed (dropbox link removed - data available elsewhere).

**Comment by havatv** [comment]
I think most of this has been fixed, or is covered by other issues.
