### ISSUE TITLE
Automatic R-Packages Installation Processing

### ISSUE THREAD

**Issue by ghtmtt** [qgis/QGIS-Documentation#1254]
Hey,

[here](https://github.com/qgis/QGIS-Documentation/blob/master/source/docs/user_manual/processing/3rdParty.rst#r-creating-r-scripts) just above the GRASS section, it seems that Processing will **not** take care of additional R packages installation. 

That means that th R Package should be install through the R GUI itself. I ran some random test (Ubuntu 16.04 and QGIS 2.16) but it seems that just by adding `library(packageName)` if the package is not present in the system, Processing will install it.

If somebody can confirm, I think we have to change the docs.

**Comment by DelazJ** [comment]
fixed in #1255
