### ISSUE TITLE
[FEATURE] API to allow drag'n'drop of custom browser items

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1268]
Original commit: https://github.com/qgis/QGIS/commit/b4fe9002d8a4c48bd629468d023863fb84ca2060 by web-flow

QgsDataItem implementations may provide hasDragEnabled(), mimeUri()
and QgsCustomDropHandler implementation to deal with drop of custom items.

**Comment by DelazJ** [comment]
@web-flow is this a PyQGIS issue or is it something that may interest user guide (drag-and-drop any type of layer within browser?) ? In the latter case, please add description in non dev language :) so that anyone can document it later.

**Comment by DelazJ** [comment]
I'm not sure this one particularly needs docs; there are other (more practical) reports imo
