### ISSUE TITLE
Improving the step-by-step guidelines with a git FAQ

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#1270]
Some how-to to help people handle frequent errors they may encounter when using git:
- fix "corrupted" branch (`master` case)
- squash commits to clean the branch history
- how to fix conflicts when master has changed since you pushed your PR
- what to do When Travis CI shows red cross
- ... others?

Could be exposed like a FAQ. However we should be careful to not overload the guidelines with git matters that can easily be found with any web search. Discussion began in #1258

**Comment by ghtmtt** [comment]
I totally agree to not overload the documentation. So what do you think if we add a new subchapter (same level of A Step By Step Contribution) and we call it e.g. `git FAQ`. We can so easy reference to it in some other parts and *A Step By Step Contribution* would not become long and unreadable.

**Comment by DelazJ** [comment]
I think it depends on how long is the FAQ section, how many questions we want to expose. If we have a lot, it could worth its own page otherwise, let's put it at the end of step-by-step. It's all about the same thing (git). And comparing to some pages in the user guide, step-by-step is really really short :). My fear is to have a hidden (and surely not really consulted) page like http://qgis.org/en/site/getinvolved/faq/index.html
No strong opinion for the moment.

**Comment by ghtmtt** [comment]
Agreed. But maybe (just maybe) if we add a good section (just like the step by step is) also for git management maybe it  would be simpler to contribute also for other people
