### ISSUE TITLE
[FEATURE] Label polygons using curved labels along perimeter

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1273]
Original commit: https://github.com/qgis/QGIS/commit/5ab62a91d3a821ffec5f088c33e2347c3d65cbae by nyalldawson

This adds a new mode for labeling polygons, where the perimeter
of the polygon is labeled using curved labeling.

(cherry-picked from 5f33991e7bcd95069ba88e01cafa7078bbad5f24)

**Comment by DelazJ** [comment]
@SrNetoChan could you please update the schema in http://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/vector_properties.html#placement-for-polygon-layers with the curved perimeter? Thanks

**Comment by DelazJ** [comment]
@nyalldawson what do the `inside` and `outside` parameters of `Maximum angle between curved characters` stand for? What kind of changes do they provide or how are they supposed to be used? see #1519 
Thanks

**Comment by SrNetoChan** [comment]
@DelazJ check if the new screenshot is ok.

**Comment by DelazJ** [comment]
👍 thanks
