### ISSUE TITLE
[FEATURE][processing] New algorithm for offsetting lines

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1285]
Original commit: https://github.com/qgis/QGIS/commit/82f4a82c66865e3d0b4af6c9410821c740eb3232 by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by ghtmtt** [comment]
closed by 3b4c1a97e84950db62bfdb8c8a755cb6edcd7f0f
