### ISSUE TITLE
[FEATURE] Color dialog can be embedded in layer style panel

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1300]
Original commit: https://github.com/qgis/QGIS/commit/5407ae8a6ad2a3599081588d1b3f04bbe4c6fe4b by nyalldawson

Now clicking color buttons inside the layer style panel causes
the color picker dialog to be opened inside the style panel itself
rather than as a separate dialog

**Comment by DelazJ** [comment]
Duplicate of #1306
