### ISSUE TITLE
cp doesn't copy only new pictures but all files for each build

### ISSUE THREAD

**Issue by yjacolin** [qgis/QGIS-Documentation#1301]
In the makfile, cp command line are used to copy pictures file into the right directory. Doing so, even when there is no new files, all files are copied and the make command run the build from scratch.

@tudorbarascu write some tips to speed up the build process, but I think we can help using rsync instead of cp as command line.
- Tudor Barascu PR: https://github.com/qgis/QGIS-Documentation/pull/1291
- An example where the cp command could be removed: https://github.com/qgis/QGIS-Documentation/blob/master/Makefile#L75

ping @rduivenvoorde , any though about this?

**Comment by ghtmtt** [comment]
`make fasthtml` is working well to build fast documentation using `rsync`. Closing this issue
