### ISSUE TITLE
[FEATURE] Expose GEOS single sided buffer through QgsGeometry

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1303]
Original commit: https://github.com/qgis/QGIS/commit/e3f0d3d88fc7fa70f3829cb40b77c6e9f9fc724c by nyalldawson

Makes it easy for PyQGIS code to perform a single sided buffer
operation

**Comment by havatv** [comment]
Geometry functions are documented in the QGIS Python API, not in the Cookbook.
