### ISSUE TITLE
[feature] Allow controlling labels for individual edit widgets

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1314]
Original commit: https://github.com/qgis/QGIS/commit/1bd26f75a5cf5772ad6421d9eec0abd3d2c649e5 by m-kuhn

In the drag and drop designer, a double click on an item will allow
controlling if the label should be shown for each item individually.

Fix #15450

**Comment by DelazJ** [comment]
duplicate of #1313
