### ISSUE TITLE
[FEATURE] Expose GEOS linear referencing function to QgsGeometry

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1323]
Original commit: https://github.com/qgis/QGIS/commit/409dfdf5395c9136090f28a58678b1d0c66b7543 by nyalldawson

Adds a new QgsGeometry::lineLocatePoint() function for
retrieving the distance along a linestring to the nearest
position on the linestring to a given point.

**Comment by yjacolin** [comment]
See also #1303

**Comment by havatv** [comment]
The methods of QgsGeometry are not documented in the Cookbook - the user should consult the Python API documentation.
