### ISSUE TITLE
[FEATURE] Add linear referencing functions to expression engine

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1324]
Original commit: https://github.com/qgis/QGIS/commit/e110ba7d54b0ac7d3f63e8ed7eaebb2845f9f38c by nyalldawson

Adds new functions
- line_interpolate_point: interpolates a point by a given distance
  along a linestring geometry
- line_locate_point: returns the distance along a linestring to
  the closest position on the linestring to a given point

**Comment by DelazJ** [comment]
fixed in https://github.com/qgis/QGIS-Documentation/commit/0dcce7fcdaf80e9acd2908feb3c5d794212d0101
