### ISSUE TITLE
Orbit Plugin problem

### ISSUE THREAD

**Issue by Binoasir** [qgis/QGIS-Documentation#1331]
Hi,

Now we are start to work on Mobile mapping in Orbit Plugin using QGIS .We have used QGIS 2.16 nodebo,Adobe Flash player  22 active X and 22 npapi. We have the activation Key ,user name and password for the trial version which is provided by the client. After installing this we have an error message like in attached screen.How to solve this and continue in QGIS.

![capture](https://cloud.githubusercontent.com/assets/21171309/17851221/84b59b6a-687e-11e6-9101-96a081281337.JPG)

**Comment by DelazJ** [comment]
hi @Binoasir 
Though I'm not sure your issue is due to QGIS, please ask for help in qgis-user list (see [support channels](http://qgis.org/en/site/forusers/support.html)).
This repository is actually dedicated to issues related to the main documentation of QGIS project.
