### ISSUE TITLE
Anyone know what's the use of the :file:`....` tag?

### ISSUE THREAD

**Issue by tudorbarascu** [qgis/QGIS-Documentation#1333]
In the generated HTML I haven't found any difference between ``code`` format and :file:`path_file`.
If there's no difference, can we switch to the `` ..`` as it makes documentation writing faster?

**Comment by yjacolin** [comment]
We can also change the rendering style (just another option to take account, I have no strong opinion on this).

**Comment by SrNetoChan** [comment]
Even that there are no rendering style differences for now. I think we should still use sphinx roles as much as we can. This way, if we decide to change the style in the future, or simply build it with another style for some purpose, the roles will be rendered correctly.
