### ISSUE TITLE
[FEATURE] Make map unit scaling dialog show inline in style dock

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1346]
Original commit: https://github.com/qgis/QGIS/commit/5735be131fcde2ad841824a44843b6a34571023d by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment]
Not sure it's worth documenting

**Comment by yjacolin** [comment]
ping @nyalldawson is it something we should document? Thanks.

**Comment by nyalldawson** [comment]
Nor this one either
