### ISSUE TITLE
[FEATURE] Make color brewer and limited random ramp editors show
inline in style panel

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1349]
Original commit: https://github.com/qgis/QGIS/commit/b225a82b3e425a93ab114c8c828d1ea9903b4682 by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment]
Not worth documenting imho

**Comment by yjacolin** [comment]
ping @nyalldawson is it something we should document? Thanks.

**Comment by nyalldawson** [comment]
Yeah I'd say not worth documenting

**Comment by yjacolin** [comment]
Thanks @nyalldawson
