### ISSUE TITLE
missing continuation between Lesson 12.1.3 and  12.2.1 and later 

### ISSUE THREAD

**Issue by ittala** [qgis/QGIS-Documentation#1350]
**Wrong saved example file name ?**
In Lesson 12.1.3 a raster map file is loaded into GRASS, named and saved with the term "g_dem".
In Lesson 12.2.1 the input - obviously referring to the same raster map generated in 12.1.2  is now suddenly "g_dem**w**" - and the result of running the Lesson is an error.
Same for 12.2.2.   If the user is changing the input of Lesson 12.1.3 so that the saved filename is "g_dem**w**"  (according to 12.2.1 or 12.2.2) - there is no error message then, but also no result: The map is not changed after running the module r.colors.table. 

**More trouble:**
Additionally the Module NVIZ used in 12.2.2 doesn't shoes up anymore in QGIS 2.16.1, right?

**Comment by havatv** [comment]
I can't find g_demw in the training manual anymore.  So I guess this has been fixed.  Please reopen if this is not the case.
