### ISSUE TITLE
[FEATURE]: possibility to segmentize feature info geometry in server

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1353]
Original commit: https://github.com/qgis/QGIS/commit/6f7b93343aece7b83f64469d50b7967cd9ae268d by mhugent

Unfortunately this naughty coder did not write a description... :-(

**Comment by yjacolin** [comment]
@tudorbarascu I kindly assigned this ticket to you as you already worked on the QGIS Server

**Comment by yjacolin** [comment]
![spectacle b31693](https://cloud.githubusercontent.com/assets/660191/25558200/fb567b0a-2d21-11e7-8d89-19e0dc33571f.png)
