### ISSUE TITLE
[FEATURE][processing] Optimised points along geometry algorithm

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1354]
Original commit: https://github.com/qgis/QGIS/commit/8db9284cb304618c91c22c380711a0d4dd02f707 by nyalldawson

Supports also polygon geometries, handles null geometries,
and records the original line angle along with the distance
for each point.

**Comment by ghtmtt** [comment]
closed by 3b4c1a97e84950db62bfdb8c8a755cb6edcd7f0f
