### ISSUE TITLE
[FEATURE][processing] Extract nodes algorithm now saves node
index, distance along line and angle at node

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1355]
Original commit: https://github.com/qgis/QGIS/commit/9fa4e776dbf2ba5004583be1bcb0e8eb8c343301 by nyalldawson

Also correctly handles null geometries

**Comment by ghtmtt** [comment]
closed by 3b4c1a97e84950db62bfdb8c8a755cb6edcd7f0f
