### ISSUE TITLE
[FEATURE] New expression functions for angle/distance interpolation

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1356]
Original commit: https://github.com/qgis/QGIS/commit/da78ddeb7cb79eabccb48d9707ea15d9e9b16d50 by nyalldawson

angle_at_vertex: returns average (bisector) angle to a geometry
at a specified vertex index
distance_to_vertex: returns distance along geometry to a specified
vertex index
line_interpolate_angle: calculates the angle parallel to a geometry
at the specified distance along the geometry

Sponsored by Andreas Neumann

**Comment by DelazJ** [comment]
duplicate of #1358
