### ISSUE TITLE
[FEATURE] Expose GEOS linear referencing function to QgsGeometry

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1357]
Original commit: https://github.com/qgis/QGIS/commit/193e9e746f84b1fe2db8574d991fbe7d94b1f6a3 by nyalldawson

Adds a new QgsGeometry::lineLocatePoint() function for
retrieving the distance along a linestring to the nearest
position on the linestring to a given point.

(cherry-picked from 409dfdf5395c9136090f28a58678b1d0c66b7543)

**Comment by havatv** [comment]
No need to document this, in my opinion.  It is just a method of QgsGeometry, and it is well documented there (in the API docs).
