### ISSUE TITLE
In QGIS 2.16.1 and 2.16.2 no Raster Calculator - even when GdalTools are active?

### ISSUE THREAD

**Issue by ittala** [qgis/QGIS-Documentation#1372]
in all my older versions the Raster calculator is easy to find in the raster menu - however in the 2.16. Versions not visible anymore. Even if I switch on and off the GdalTools in Plugins.

Is that a bug or a new feature ? ( like the same functions moved somewhere else ? )

**Comment by DelazJ** [comment]
I still have Raster calculator in 2.16.2 and without having GdalTools plugin (or Processing) enabled. They are not dependent. And as far as I remember, no move has been done for raster functions in 2.16 to Processing (as done for vector). So might be a bug in your side.

Please do not report application issues in this repository. This one is dedicated to [QGIS documentation](docs.qgis.org) matters. Report either in the [application issue report](hub.qgis.org) or in the user/developer mailing list. More information at http://qgis.org/fr/site/getinvolved/mailinglists.html#qgis-mailinglists or http://qgis.org/fr/site/forusers/support.html
Thanks

**Comment by ittala** [comment]
Ok. Thanks for your feedback
