### ISSUE TITLE
[FEATURE][processing] Add choice of simplification method to simplify

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1374]
Original commit: https://github.com/qgis/QGIS/commit/56b77db88c4b617f254a7fa1309f86ee7d3cedfa by nyalldawson

This change allows users to choose which method to use when running
the simplify geometries algorithm, with choices of the existing
distance based (Douglas Peucker) algorithm, area based (Visvalingam)
algorithm and snap-to-grid.

Visvaligam in particular usually results in more cartographically
pleasing simplification over the standard distance based methods.

**Comment by ghtmtt** [comment]
closed by 3b4c1a97e84950db62bfdb8c8a755cb6edcd7f0f
