### ISSUE TITLE
[FEATURE] Extra control when smoothing geometries

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1376]
Original commit: https://github.com/qgis/QGIS/commit/4d60d0cdb54cc75f15c4e841aa87a3fd6994c918 by nyalldawson

Add option to QgsGeometry::smooth to not smooth segments shorter than a certain threshold or sharp corners with an angle exceeding a threshold

Expose the angle threshold to processing smooth algorithm

Also:
- optimise QgsGeometry::smooth for new geometry classes
- Fix smooth does not work with geometries containing Z/M

**Comment by ghtmtt** [comment]
closed by 3b4c1a97e84950db62bfdb8c8a755cb6edcd7f0f
