### ISSUE TITLE
Merge pull request #3451 from nyalldawson/smoooooth

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1380]
Original commit: https://github.com/qgis/QGIS/commit/95c4fa13409060d5780b6590bdfa3225753f4e70 by web-flow

[FEATURE] New simplify + smoothing expression functions

**Comment by SrNetoChan** [comment]
This is a duplication of https://github.com/qgis/QGIS-Documentation/issues/1379.

Can we close it?
