### ISSUE TITLE
Command line options needs to be updated

### ISSUE THREAD

**Issue by SrNetoChan** [qgis/QGIS-Documentation#1383]
The command line options section needs to be updated.

http://docs.qgis.org/2.14/en/docs/user_manual/introduction/getting_started.html#command-line-options

The expected result is outdated, and `gui --help` does not work on Windows.

**Comment by DelazJ** [comment]
@SrNetoChan I think it has been (see #1070 or #1069). Any missing option?
> The expected result is outdated

What do you mean?  Update in the result 2.6 into 2.14? Is that worth the effort (from release to release)? 

For qgis --help, see also http://hub.qgis.org/issues/15024

**Comment by SrNetoChan** [comment]
We should say in docs that this does not work in windows. So that users don't stress about it. Once it's fixed, we remove the warning.
