### ISSUE TITLE
Qgis version has wrong name after windows installation

### ISSUE THREAD

**Issue by dmitrykinakh** [qgis/QGIS-Documentation#1386]
See screenshot:  http://screencast.com/t/jmFY5PUbVi3

**Comment by DelazJ** [comment]
@dmitrykinakh, this is an application issue that might be reported at either [issue report website](hub.qgis.org) or developer [mailing list](http://qgis.org/fr/site/getinvolved/mailinglists.html#qgis-mailinglists). See http://qgis.org/en/site/getinvolved/development/bugreporting.html.
This repository is dedicated to [QGIS documentation](docs.qgis.org) matters.
Thanks for contributing.
