### ISSUE TITLE
[Processing]Any reason to have separated mergedatasourcesinvrt from vector tools?

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#1390]
Is there any reason to have this file http://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/vector_general_tools/mergedatasourcesinvrt.html not under http://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/vector_general_tools.html (given the url)? If not compatible, any other group of tools that can inherits mergedatasourceinvrt?
@volaya @alexbruy ?

**Comment by alexbruy** [comment]
There are no reason for this. I think it is in the separate file because it was added together with code manually, not by running helper script. Feel free to move it into "Vector general tools" group

**Comment by DelazJ** [comment]
Ok, thanks @alexbruy
