### ISSUE TITLE
any automatic process to address processing doc?

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#1403]
I note that there are some processing tools that have help in doc but not in desktop:
- `Point Displacement`, `Execute SQL`...
- `symmetrical difference` has help when opened from vector menu but not from toolbox (need an issue report?)

Is there any process to automatically fill help (or list of algs) between doc and app or is that done manually?
@volaya  @alexbruy ?

**Comment by alexbruy** [comment]
Are you talking about "quick help" panel in this algorithm dialog? Content for this panel added manually by editing file in the QGIS source tree. Personally I don't think that we should add it for all algs, as this simply means moving docs into QGIS source tree. IMHO ideally we should have all algs documented in the documentation and drop "quick help" panel.

On latest master "symmetrical difference" always has "quick help".

**Comment by DelazJ** [comment]
yes Alex I meant the panel that appears at the right of the alg parameters.
> Personally I don't think that we should add it for all algs, as this simply means moving docs into QGIS source tree. IMHO ideally we should have all algs documented in the documentation and drop "quick help" panel.

I do not agree with you, because currently, this panel only shows what the algorithm does, which is very helpful for users, I think. One should not have to browse the documentation (not a simple task) to just ensure that the alg he wants to use really does what he expects. I am only refering to description of the algorithm itself, not to its parameters description (which can stay in docs). So unless there's a link to the right place in the docs to the alg descrition, I'm not fan of removing this description.
I may be wrong but there was a processing release which picked description from documentation in the past, wasn't it?

> On latest master "symmetrical difference" always has "quick help".

Seems to not be the case in master_2 (qgis/QGIS@f7a1dcd, the latest in osgeo4w)

**Comment by alexbruy** [comment]
> I may be wrong but there was a processing release which picked description from documentation in the past, wasn't it?

No. We added ability to load online documentation into the "Help" tab.

**Comment by DelazJ** [comment]
No there's no automatic process to fill algorithm helps...
