### ISSUE TITLE
[FEATURE] Preview for WMTS + added XYZ tile layers

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1408]
Original commit: https://github.com/qgis/QGIS/commit/f5b657db19eda7e72e6ed34eb7fe333c156acad0 by web-flow

This is a port of the functionality from master (to be QGIS 3.0) to 2.x that keeps backward API compatibility.
- added support for XYZ tile layers to WMS provider
- rendering of raster layers can be interrupted, support in WMS provider
- temporary preview of tiled layers (WMTS / XYZ) in WMS provider

WMTS improvements funded by Land Information New Zealand.

XYZ tile layer funded by Lutra Consulting.

**Comment by DelazJ** [comment]
more details in #1398

**Comment by DelazJ** [comment]
@yjacolin I think we should document this in the User Manual, don't you? It's available through the browser panel...

**Comment by havatv** [comment]
Should be fixed with #4800.
