### ISSUE TITLE
[FEATURE] Enable tabbed floating docks for Qt >= 5.6

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1413]
Original commit: https://github.com/qgis/QGIS/commit/b45a6b42298f36e00ceaabcf49c8384378b1e58b by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment]
Not worth documenting imho

**Comment by nyalldawson** [comment]
Me either
