### ISSUE TITLE
[Feature] Allow configuring link/unlink feature buttons on relation editor widget

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1415]
Original commit: https://github.com/qgis/QGIS/commit/5f0ade83f3ae989abb607f7f185ca0849b5b11dd by m-kuhn

Unfortunately this naughty coder did not write a description... :-(

**Comment by m-kuhn** [comment]
In the drag and drop designer, doubleclick a relation item and make use of the two new checkboxes.
