### ISSUE TITLE
[Feature] Allow configuring link/unlink feature buttons on relation editor widget

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1416]
Original commit: https://github.com/qgis/QGIS/commit/8069154aadd76aa0fd48d4fb3126109728f26963 by m-kuhn

Unfortunately this naughty coder did not write a description... :-(

**Comment by m-kuhn** [comment]
In the drag and drop designer, doubleclick a relation item and make use of the two new checkboxes.

**Comment by m-kuhn** [comment]
Duplicate of #1415
