### ISSUE TITLE
Build QGIS from source with Windows7

### ISSUE THREAD

**Issue by icetorm** [qgis/QGIS-Documentation#1426]
Hi everyone,
I'm a student of architecture and i'm trying to learn how to build QGIS from source with windows 7 x64 to adapt QGIS for a urban planing. However even if i work with python plugins and QT , i never learn to build a software from source. 

I'm trying to build QGIS 2.16.3
-I install these dependencies from cygwin(x64): Perl,wget,unzip,tar,bzip2
-I unzip the source QGIS 2.16.3 from this link: https://github.com/qgis/QGIS/releases
-I enter cmd from batch file with this configuration when i tried to build with visual studio:

@echo off
  set VS90COMNTOOLS=%PROGRAMFILES(x86)%\Microsoft Visual Studio 10.0\Common7\Tools\
  call "%PROGRAMFILES(x86)%\Microsoft Visual Studio 10.0\VC\vcvarsall.bat" x86
  
  set INCLUDE=%INCLUDE%;%PROGRAMFILES%\Microsoft SDKs\Windows\v7.1\Include
  set LIB=%LIB%;%PROGRAMFILES%\Microsoft SDKs\Windows\v7.1\Lib
  
  set OSGEO4W_ROOT=C:\OSGeo4W
  call "%OSGEO4W_ROOT%\bin\o4w_env.bat"
  path %PATH%;%PROGRAMFILES(x86)%\CMake\bin;c:\cygwin\bin;%PROGRAMFILES(x86)%\Microsoft Visual Studio 10.0\Common7\IDE
  
  @set GRASS_PREFIX=c:/OSGeo4W/apps/grass/grass-6.4.3
  @set SPATIALINDEX_LIBRARY=C:/OSGeo4W/lib/spatialindex-64.lib
  @set INCLUDE=%INCLUDE%;%OSGEO4W_ROOT%\include
  @set LIB=%LIB%;%OSGEO4W_ROOT%\lib;%OSGEO4W_ROOT%\apps\gdal-dev\lib
  
  @cmd

-I go to C:/QGIS/ms-windows/osgeo4w/
-I run: creatensis.pl
-I got this error looping (+100 times):
out of gid_t 
out of uid_t 
and then: ... unpacking grass-7.0.4-1.tar.bz2+failed

Can someone help me, i have been 7 days trying solving this, i tried with master branch, with 2.16.2 and now with 2.16.3 but with the same result each time. I only want to know how to get a installation binary from source for windows so i can later put my custom templates and plugins in source and then build it again so i can give to my schoolmates a custom QGIS specially design for architects.

**Comment by icetorm** [comment]
this is a screenshot  of the error:
![image](https://cloud.githubusercontent.com/assets/21952818/18810720/9dfa58ca-829d-11e6-9d6f-1ca5d9e741f0.png)

**Comment by DelazJ** [comment]
Please ask for help in qgis-user or qgis-developer list (see [support channels](http://qgis.org/en/site/forusers/support.html)).
This repository is actually dedicated to issues related to the [main documentation](docs.qgis.org) of QGIS.
Thanks
