### ISSUE TITLE
Show a more complete/detailed table of contents in PDF doc

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#1432]
It would be nice if the PDF doc could show more than 2 levels of TOC as the [global index](http://docs.qgis.org/testing/en/docs/user_manual/index.html) is the single place where one can see the architecture of the user guide in pdf doc.

Is that possible to have a 2-level toc in html and let's say a 3-level one in pdf? maybe with the `.. only::` tag?

**Comment by havatv** [comment]
Our options (I think):
* We now have one level (LaTeX tocdepth 1 - chapter + section) and spend three pages for the TOC.
* With one more level (tocdepth 2) we go to nine pages for the TOC.
* With two more levels (tocdepth 3) we got to 22 pages for the TOC.

Which one should we go for, @DelazJ, @ghtmtt, @SrNetoChan?

**Comment by SrNetoChan** [comment]
Uff hard call. 22 pages seems too much!

**Comment by havatv** [comment]
> Uff hard call. 22 pages seems too much!

Agreed.
So I support @DelazJ's suggestion - two levels (nine pages for the TOC).

**Comment by havatv** [comment]
> Is that possible to have a 2-level toc in html and let's say a 3-level one in pdf? maybe with the `.. only::` tag?

The settings for the number of TOC levels for the main PDF TOC seem to be unrelated to HTML TOC level settings, so this should be possible.

PR #5845 fixes a three level TOC (nine pages) for the PDFs by setting tocdepth to `2` in the latex preamble (conf.py). HTML TOCs are not affected.

The number of HTML TOC levels:
* The `:maxdepth:` parameter of `toctree` sets the number of TOC levels for that entry. We use 2.
* `navigation_depth` in conf.py sets the number of TOC levels in the TOC in the left (navigation) bar of the documentation page (it is currently 4)
