### ISSUE TITLE
Advanced Digitizing - Closing last point orthogonally, based on first point

### ISSUE THREAD

**Issue by geofuture** [qgis/QGIS-Documentation#1436]
Hi,
I have been working with CAD softwares for a long time, and I know a GIS software will not focus only on tools for accurate digitizing.

Advanced Digitzing is a great tool that has been implemented in the newest versions, but it still have a big problem. The last point will never be accurated, unless you type its angle and distance.  We need a tool to close the last point based on the first alignment's perpendicular line. 

Thank you,
Felipe Souza

**Comment by DelazJ** [comment]
Hi,
@geofuture Please do not report application issues in this repository. This one is dedicated to [QGIS documentation ](http://www.docs.qgis.org) matters. Rather report in the application issue report (http://hub.qgis.org) as mentioned in http://qgis.org/en/site/getinvolved/development/bugreporting.html
Thanks
