### ISSUE TITLE
[FEATURE] support for 2.5D geometries in memory provider

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1437]
Original commit: https://github.com/qgis/QGIS/commit/b9ca91a55a981ddf6d99e0e5b9e4ecc9f6425e88 by alexbruy

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment]
If it is said in the documentation that 2.5D is not supported by memory provider, this should not be documented, in my opinion.
