### ISSUE TITLE
[FEATURE] Port composer config widgets to QgsPanelWidgets

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1438]
Original commit: https://github.com/qgis/QGIS/commit/028db7e54182a82c4e64e955dfe4971210b21f5b by nyalldawson

Brings the inline (ie, no modal dialogs!) color modification
and symbol editing from the layer styling panel to
composer item configuration.

**Comment by DelazJ** [comment]
No need to document imho
