### ISSUE TITLE
QGIS not loading georeferenced Tiff files - invalid data source

### ISSUE THREAD

**Issue by PipMess** [qgis/QGIS-Documentation#1442]
When loading georeferenced image files, no matter the format, the data source (.tif, .jpeg, etc) is not recognised.  
"Invalid Data Source: <FILE LOCATION\>tq35sw.tif is not a valid or recognized data source", georeference files are saved in the same location.  This a recent issue, as these types of files have previously worked, until this week.  (Please not  <FILE LOCATION\> represents the location of the file on the computer)
In addition, if i want to georeference an image file, using the GDAL plugin "Georeferencer", this gives the same issue when trying to load the image file to georeference.

**Comment by DelazJ** [comment]
Hi,
Please report this in the [issue tracker] (hub.qgis.org) or ask for help in one of qgis [support channels](http://qgis.org/en/site/forusers/support.html).
This repository is dedicated to [QGIS Website](qgis.org) issues.

In order to improve communication about this repository, could you please explain why you end up reporting this issue here and not in another repo or mailing list? Thanks

**Comment by PipMess** [comment]
Sorry,  I think I got redirected to the wrong page and just assumed that it was the right place to report the issue.

**Comment by DelazJ** [comment]
@PipMess:
> Sorry, I think I got redirected to the wrong page and just assumed that it was the right place to report the issue.

May I ask "from where?"? Sorry if I bother you but we have more and more issue reports in website and doc repos and I'm wondering why this occurs and where might be the information that leads people to the wrong repo.

**Comment by PipMess** [comment]
From: https://qgis.org/en/site/getinvolved/development/bugreporting.html
Then Reporting an Issue (at the bottom of the page): There are two options.  This now (in hindsight) is obviously for the website and documentation, but the initial how to report a bug is not clear, as you have to create several accounts to be able to report a bug, which is confusing..

**Comment by DelazJ** [comment]
Thanks, I was suspecting things might not be clear in this page. I try to simplify the description and emphasize on what looks important. Hope that people will no longer mix up the steps.
A PR is available at https://github.com/qgis/QGIS-Website/pull/383 and if you want to read the new description, it can simply be found at https://github.com/DelazJ/QGIS-Website/blob/issuereport/source/site/getinvolved/development/bugreporting.rst
