### ISSUE TITLE
Remove old and useless pdf files in http://docs.qgis.org/testing/pdf/en/ folder

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#1445]
It'll free around 160Mo

**Comment by DelazJ** [comment]
Also in http://docs.qgis.org/2.8/pdf/en/ there are some odd files (testing branch related)

**Comment by rduivenvoorde** [comment]
Ok, cleaned. 
For the record: testing is on qgis, 2.8 is on qgis2
