### ISSUE TITLE
Document the temporary storage mechanism for PostgreSQL credentials

### ISSUE THREAD

**Issue by pcav** [qgis/QGIS-Documentation#1458]
See this thread for details:
https://lists.osgeo.org/pipermail/qgis-developer/2016-October/045344.html

**Comment by jef-n** [comment]
QgsCredentials is also used in db_manager for postgis and oracle connection, in processing and in the postgresql, oracle and db2 providers.  It allows to prompt for a password for any connection, stores it in an temporary internal cache and returns the stored password, when a password is requested again for the same connection.
