### ISSUE TITLE
[FEATURE] QgsTextRenderer class for rich text rendering

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1461]
Original commit: https://github.com/qgis/QGIS/commit/08143475edb5a920523fb0f56ca7ffbb1870d45e by nyalldawson

Moves all the drawing code out of labeling into a new class
which just handles rendering text. This allows other parts
of the code to utilise all the advanced formatting options
that labeling supports, eg rendering text with shadows,
buffers and backgrounds.

**Comment by DelazJ** [comment]
I don't think there's anything for us to document here.

**Comment by DelazJ** [comment]
I think main elements visible to the end user are in describing the label/text setting tabs. Closing then.
