### ISSUE TITLE
[FEATURE] Allow label font size in mm/pixels

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1462]
Original commit: https://github.com/qgis/QGIS/commit/169b367c5b5ed5997052e8fa536f1bf8adef4386 by nyalldawson

And all other label sizes (eg buffer size) now accept sizes in
pixels too

**Comment by yjacolin** [comment]
Do we need to add this information in the documentation? I don't think so. Opinions? @ghtmtt @DelazJ  @SrNetoChan

**Comment by yjacolin** [comment]
Here an example in QGIS 3:

![spectacle x27834](https://user-images.githubusercontent.com/660191/43903415-b010f1b2-9bec-11e8-938e-ff8028e3ac12.png)

**Comment by SrNetoChan** [comment]
@yjacolin I kind of Agree, unless we get a place to describe/explain the options units. Meters at scale, and Map Units may deserve some explanation, but not especific to labels, as they apply elsewhere.

**Comment by yjacolin** [comment]
I agree with @SrNetoChan but I can't find a good location. Any idea?

**Comment by yjacolin** [comment]
Some proposition:
* https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_gui.html#layer
* https://docs.qgis.org/testing/en/docs/user_manual/introduction/general_tools.html

**Comment by DelazJ** [comment]
I think https://docs.qgis.org/testing/en/docs/user_manual/introduction/general_tools.html#common-widgets could be a good candidate
