### ISSUE TITLE
Snapping config changes

### ISSUE THREAD

**Issue by m-kuhn** [qgis/QGIS-Documentation#1468]
Sorry, I pressed the wrong button, so the doc request was not opened automatically.

Details here:

https://github.com/qgis/QGIS/pull/3617

**Comment by havatv** [comment]
Has this update to the QGIS snapping config happened (qgis/QGIS#3617 does not seem to have been merged)?

**Comment by m-kuhn** [comment]
I think this is in there, at least the screenshots look very familiar to me. It has probably been manually merged (in these days we didn't like the github merge button too much because of merge commits in the commit history).

**Comment by yjacolin** [comment]
@m-kuhn in this case, if I am not wrong, use the dropdown list:
![spectacle xf7124](https://user-images.githubusercontent.com/660191/46998309-7b264900-d122-11e8-9da6-2958ec833ea4.png)

**Comment by m-kuhn** [comment]
That wasn't in place back in 2016 ;
