### ISSUE TITLE
[FEATURE] save and restore color ramp used for singleband pseudocolor rendering

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1497]
Original commit: https://github.com/qgis/QGIS/commit/2497375ee95c5eb3046a8316793adf75c4ef1768 by alexbruy

Unfortunately this naughty coder did not write a description... :-(

**Comment by alexbruy** [comment]
See qgis/QGIS-Enhancement-Proposals#71 for more details
