### ISSUE TITLE
[FEATURE] [processing] New algorithm to compute geometry by expression 

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#1498]
This algorithm updates existing geometries (or creates new geometries) for input features by use of a QGIS expression. This allows complex geometry modifications which can utilise all the
flexibility of the QGIS expression engine to manipulate and create geometries for output features.

see https://github.com/qgis/QGIS/pull/3692/commits/12ab6c6f6f77aea5cf5e31e9af81723d35a263cb

**Comment by ghtmtt** [comment]
closed by 3b4c1a97e84950db62bfdb8c8a755cb6edcd7f0f
