### ISSUE TITLE
[FEATURE][processing] Snap geometries to layer algorithm

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1505]
Original commit: https://github.com/qgis/QGIS/commit/c3a978b9da33f69c6c5440e1166c78c89946dde4 by nyalldawson

Port the Geometry Snapper plugin across to the analysis lib, and
expose to python bindings

Add a new algorithm which performs the snapping to layers

**Comment by ghtmtt** [comment]
closed by 3b4c1a97e84950db62bfdb8c8a755cb6edcd7f0f
