### ISSUE TITLE
[FEATURE][processing] Snap geometries algorithm allows snapping
to other layer types, supports point/line layers

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1506]
Original commit: https://github.com/qgis/QGIS/commit/dae0a017617d3082b6e89f8a3e75c2c9bcd0ebf5 by nyalldawson

Fix #14791, #15313

**Comment by ghtmtt** [comment]
closed by 3b4c1a97e84950db62bfdb8c8a755cb6edcd7f0f
