### ISSUE TITLE
[FEATURE] upgrade the substr() function

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1513]
Original commit: https://github.com/qgis/QGIS/commit/0fbcc4b95d310e2223a805fac4e10d726ea8f9eb by nyalldawson

- support negative start value (e.g. substr('hello',-2) returns 'lo')
- support negative length value (e.g. substr('hello',3,-1) returns 'll')
- length parameter now optional, defaults to end of string  (e.g. substr('hello world',7) returns 'world')

**Comment by DelazJ** [comment]
We do not describe such details in doc
