### ISSUE TITLE
[FEATURE][processing] New input type for expressions

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1518]
Original commit: https://github.com/qgis/QGIS/commit/132e76a596c71e3d559deef19c36b414c01630ec by nyalldawson

This adds a new input type for expression inputs. Expression
inputs can be linked to a parent layer so that the builder
shows the correct fields and layer variables.

It's designed for two use cases:

1. to be used when an algorithm specifically requires an expression,
eg Select by Expression and Extract by Expression.

2. to be potentially used as a replacement input instead of string
or number literals in algorithms. Eg - if the simplify algorithm
tolerance parameter was replaced with an expression paremeter, then
this expression would be evaluated for every feature before
simplifying that feature. It would allow parameters to be calculated
per feature, as opposed to the current approach of calculating
a parameter once before running the algorithm. It would also
mean algorithms like "variable distance buffer" would no longer
be needed, as a single "buffer" algorithm could then be used
for either a fixed distance, field based, or expression based
distance.

**Comment by havatv** [comment]
The only documentation of processing parameter types is a list in using processing algorithms from the console section.  ParameterExpression is included.  I am therefore closing this one.  If this needs more documentation, a new issue should be filed.
