### ISSUE TITLE
[FEATURE] Add method to calculate pole of inaccessibility for polygons

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1520]
Original commit: https://github.com/qgis/QGIS/commit/d6f09c012e71cb827c2e4408783f724638094cec by nyalldawson

Implements a method in QgsGeometry and a processing algorithm to
calculate the pole of inaccessibility for a surface, which is the
most distant internal point from the boundary of the surface. This function
uses the 'polylabel' algorithm (Vladimir Agafonkin, 2016), which is an iterative
approach guaranteed to find the true pole of inaccessibility within a specified
tolerance. More precise tolerances require more iterations and will take longer
to calculate.

**Comment by stonetip** [comment]
For reference, the PolyLabel algorithm in JS: https://github.com/mapbox/polylabel

This would be a welcome feature.

**Comment by DelazJ** [comment]
@stonetip FYI it's already implemented in upcoming QGIS 3 so if you want, you can give it a try in [QGIS nightlies](http://www.qgis.org/en/site/forusers/alldownloads.html)

**Comment by ghtmtt** [comment]
closed by 3b4c1a97e84950db62bfdb8c8a755cb6edcd7f0f
