### ISSUE TITLE
[feature] Add layer scoped actions

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1523]
Original commit: https://github.com/qgis/QGIS/commit/5b4a88f8e07e8ee1f9bfc0570f76f68717688cf2 by m-kuhn

Within the attribute table, there is a new button to trigger actions
which are not based on individual features but instead on the whole layer.
Normally they will perform actions based on all features or the selection.

In addition to this, a lot of cleanup has been done.

**Comment by yjacolin** [comment]
Some screenhots to help:

![spectacle juo497](https://user-images.githubusercontent.com/660191/43907542-fb403aea-9bf5-11e8-82fa-f93befeae05d.png)


![spectacle csa497](https://user-images.githubusercontent.com/660191/43907519-e429f620-9bf5-11e8-8ae0-b5d156d85502.png)
