### ISSUE TITLE
[FEATURE] Add method to get list of unique strings matching
a substring from a vector data provider

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1524]
Original commit: https://github.com/qgis/QGIS/commit/3242321aa9a3bc81d3db369edeadea4922ea861d by m-kuhn

Base implementation iterates through all features, but
providers can override with optimised versions. Native
implementations for postgres, spatialite and OGR included.

**Comment by DelazJ** [comment]
@m-kuhn  to doc? In which case, any explanation please? Thanks

**Comment by m-kuhn** [comment]
Doesn't look like something for the user docs, I would close this issue.

**Comment by DelazJ** [comment]
Thanks
