### ISSUE TITLE
Incremental compiling of documentation?

### ISSUE THREAD

**Issue by gravitystorm** [qgis/QGIS-Documentation#153]
The instructions in the README suggest the following workflow:

* run ``./scripts/post_translate.sh en`` locally to build the english docs
* edit/update the rst files with the english documentation from ``./source/docs/user_manual/``
* run ``./scripts/post_translate.sh en`` locally again to check your changes

However, the third step recompiles the entire documentation from scratch, not just the file that has been changed. This takes over 2 minutes on my laptop and makes it hard to check as I'm working.

Is there a way to do incremental updates when recompiling?

**Comment by rduivenvoorde** [comment]
These are old issues. We cannot do incremental builds because we change images/languages between builds. 
The post_translate.sh scripts are not used anymore either.
Closing this one.
