### ISSUE TITLE
Cleaning the list of tags in the repository?

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#1530]
Looking at the stats of the tags defined in the current repo, I wonder if there aren't some we could remove:

- [x] `Answers`, `Appendix`, `invalid`, `ready`: 0 issue reported
- [x] `wontfix`: issues(1); actually most of the times we simply close them (with explanation) without tagging
- [x] `duplicate`: surprisingly, only one issue (same reason as above)
- [x] `Doc`: many issues but we are in the documentation repository so I assume everything is related to doc, and when it's not the case, see above.

I however wonder if we should not add:
- [x]  `Processing` and/or `Server` tags (though they are chapters of the user manual, but with something particular imo); e.g; some of the recent issues would need to be addressed in both Expression(/Vector) and Processing chapter; having a processing tag could ensure that the issue is not closed by simply filling the expression part -- no strong opinion
- [x] a `Doc Guidelines` tag (to cover all the five docs maintained)
- ~~[x] automatically add the `Text` tag to the automated issues (most of the times, it's about text or text+screenshot; so if text is removed (hence fixed) we know that only screenshot is missing).~~

Any opinion?

**Comment by DelazJ** [comment]
Seems there's no objection...

**Comment by yjacolin** [comment]
* Appendix: if we used this only for licence, yes it is not useful. -0
* Answer: to be removed, +1
* Invalid: +1
* wontfix: +1
* duplicate: +1
* doc: +1, we should use usermanual, trainings, etc.

**Comment by yjacolin** [comment]
* ready: +1 ;)
