### ISSUE TITLE
[FEATURE][processing] Create attribute index algorithm

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1531]
Original commit: https://github.com/qgis/QGIS/commit/5e1a69fc88e6ac97675ed178bcb8f0d8e32da3c1 by nyalldawson

Allows creation of an index on an attribute in a layer for faster
attribute based filtering

Support depends on the underlying data provider for the layer

**Comment by DelazJ** [comment]
Fixed in #2334
