### ISSUE TITLE
[FEATURE][processing] Remove duplicate create points along lines script

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1549]
Original commit: https://github.com/qgis/QGIS/commit/6bb4934907ea26bcff802bb4ae9abbb47eae7d5f by nyalldawson

This functionality is duplicated by the PointsAlongGeometry algorithm

Keep the algorithm version, since it has unit tests and supports things
like progress reports.

(marked as feature for inclusion in release notes)

**Comment by ghtmtt** [comment]
closed by 3b4c1a97e84950db62bfdb8c8a755cb6edcd7f0f
