### ISSUE TITLE
[FEATURE][processing] New universal 'basic stats for field' algorithm

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1552]
Original commit: https://github.com/qgis/QGIS/commit/b30a1ff65df284b9112198b384ed3e09a4768fef by nyalldawson

Replaces the existing 'Basic Stats for Numeric Fields' and
'Basic Stats for String Fields' algorithms and adds support
for date/time/datetime fields.

Having a single unified algorithm allows more flexible models
where a field type may not be known in advance.

Deprecate existing basic stats algorithms

**Comment by DelazJ** [comment]
I can't check because of a broken Processing but doesn't https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/vectoranalysis.html#basic-statistics-for-numeric-fields describe this alg? In which case *a minima* it should be renamed in docs and this issue closed.
