### ISSUE TITLE
[FEATURE] Create attribute index support for spatialite provider

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1560]
Original commit: https://github.com/qgis/QGIS/commit/bd8d2121dccdeea61fe9ada620c84b311d3deb25 by nyalldawson

Allows creation of attribute indexes for spatialite layers

**Comment by havatv** [comment]
I don't think this should be documented - it is not exposed to the users, is it?

**Comment by m-kuhn** [comment]
Check if the existing doc for attribute index creation mentions specific providers. If yes, add spatialite. If not, nothing changed and it's just magically supported from now on.
