### ISSUE TITLE
[FEATURE] Add a Task manager

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1562]
Original commit: https://github.com/qgis/QGIS/commit/b1b647349ac5d43a6f0b1a308dd7480f11dded63 by web-flow

[FEATURE] Task manager

**Comment by havatv** [comment]
@nyalldawson, in which parts (and (new) chapters) of the documentation would you suggest that we start documenting the task manager and the use of tasks (in processing scripts / processing plugins I guess).
Is the use of tasks in non-processing plugins supported?

**Comment by nyalldawson** [comment]
I think this should go into the cookbook. It's automatically handled for processing (so nothing to include there), but can be manually used by other areas of QGIS outside of processing.

If you can get permission to reproduce http://www.opengis.ch/2018/06/22/threads-in-pyqgis3/ , I'd say that's a great starting point (or maybe it's everything needed!)

**Comment by havatv** [comment]
#3095 #3129 address this issue.  Can it be closed?

**Comment by DelazJ** [comment]
Yes and thanks for having handled this.
