### ISSUE TITLE
[FEATURE][processing] New algorithm to orthagonalize geometries

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1568]
Original commit: https://github.com/qgis/QGIS/commit/4b6f3a3ee5a55b23dc3226f4b6bfa2eae8fee8da by nyalldawson

Adds a new QgsGeometry::orthagonalize method which tries to make
angles in geometries either right angles or straight lines

Also adds a processing algorithm exposing this feature.

**Comment by DelazJ** [comment]
@nyalldawson is it orth**a**gonalize or orth**o**gonalize? Couldn't find any reference to the first one on the web.

**Comment by nyalldawson** [comment]
Think it's the second... I suck at spelling

**Comment by DelazJ** [comment]
Fixed in #2255
