### ISSUE TITLE
[FEATURE] Toggle visibility of opened panels in main window

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1581]
Original commit: https://github.com/qgis/QGIS/commit/398249806f9cc87d935c5cd8a76c7dee3816d45b by nirvn

Accessible via:
- View menu > Toggle Panels Visibility
- Ctrl+Tab keyboard shortcut

**Comment by rduivenvoorde** [comment]
Related to #2507 should be written together with.
