### ISSUE TITLE
[FEATURE] Implement raster auto-stretching when updating canvas

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1583]
Original commit: https://github.com/qgis/QGIS/commit/532eb58d1f4003a9bcb77ad2119ab8d1255ff7b6 by rouault

This commit implements the improvements described at:
https://lists.osgeo.org/pipermail/qgis-developer/2016-September/044393.html

The QgsRasterMinMaxWidget now offers a seetting to specify that the statistics
should be computed each time the canvas extent changes.

Other changes:
- the content of the QgsRasterMinMaxWidget is now persistant.
- there is no longer any Load button. The global Apply / OK button of the raster
  properties dialog has this effect.
- the default "limits" for single band raster is now MinMax and not CumulativeCut
- the default "limits" can be configured for single band, multi band single byte and
  multi band multi byte
- "Strech using current extent" honours the "limits" instead of forcing min/max.

**Comment by havatv** [comment]
The setting is documented ("Statistics extent" has the "Updated canvas" option). But it can be given an explanation.  I will try.
