### ISSUE TITLE
[FEATURE] remove Raster terrain analysis plugin

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1587]
Original commit: https://github.com/qgis/QGIS/commit/c3e3ba6b49dc223d226034f78de06c5bf5c864dc by alexbruy

tagged as feature to not forget mention this in docs and changelog

**Comment by havatv** [comment]
The user manual seems to be fixed by #1806.  In the training manual, "Lesson: Supplementary Exercise" is affected (from step 11). I have tried to address that in #3075.
