### ISSUE TITLE
[FEATURE] Raster stretch toolbar actions support for pseudocolor renderer

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1595]
Original commit: https://github.com/qgis/QGIS/commit/239b342a3f0bb8d7a13c4b73bc2dc12be4b2b47d by nirvn

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment]
The screenshot in "Fig. 15.5: Raster Symbology - Singleband pseudocolor rendering" shows the min/max value settings element, and there is a *:ref:values range <minmaxvalues>* reference to  so this should be OK.
