### ISSUE TITLE
[FEATURE] Add QgsVectorDataProvider::truncate for clearing layers

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1596]
Original commit: https://github.com/qgis/QGIS/commit/bc98a326c0b08a9b2c66576517062fb6e003aab1 by nyalldawson

Adds a new method to QgsVectorDataProvider to truncate the layer.
The base implementation requires DeleteFeatures capability and
is not optimised. Providers can return the FastTruncate capability
and override the base implementation with a provider specific
optimised version. This is done in this commit for the Postgres
and Spatialite providers.

**Comment by havatv** [comment]
This is documented in QgsVectorDataProvider in the QGIS API docs.
