### ISSUE TITLE
[FEATURE] Export processing models as PDF/SVG

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1603]
Original commit: https://github.com/qgis/QGIS/commit/f54476cddaf70096c585c984c5963fdaf5530931 by nirvn

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment]
PDF, SVG and image export has now been mentioned in the user manual, and the image of the processing modeller canvas has been updated.
