### ISSUE TITLE
[Feature][PostgreSQL] Compile expression functions

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1605]
Original commit: https://github.com/qgis/QGIS/commit/735b1c359a4b3941aa84b9b7f051352c9c714648 by rldhont

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment]
I don't think this needs to be documented.

**Comment by m-kuhn** [comment]
There is an option in the QGIS properties -> Data Sources "Execute expressions on server-side if possible". A short discussion of the effect of this setting should be enough.

Something like

> When requesting features from a datasource, QGIS will try to optimize requests by sending filter criteria directly to the server and only download the features which match the criteria. For example, if for a list on the user interface only the farmers which live in Bern should be listed, QGIS will send a `WHERE "hometown" = 'Bern'` to the database. In some cases, filter criteria are too complex to be translated from QGIS Expressions to database compatible SQL in those cases, QGIS will download the whole data and filter locally to be on the safe side, which is much less performant.
> By disabling "Execute expressions on server-side if possible" QGIS can be forced to always download the whole data and filter locally, at the expense of a performance penalty. This option is meant as a safety break and should only be deactivated if you identify a misbehavior of the QGIS expression translation engine.

This is pretty much the only way a user can influence this behavior.

**Comment by havatv** [comment]
Thanks. That is a good start.
I can't see "Execute expressions on server-side if possible" in 3.4.2 (Project properties-> Data sources).  Will it be in 3.6?

**Comment by DelazJ** [comment]
It's instead in Settings --> Options --> Data sources

**Comment by havatv** [comment]
Found it!  So it can be documented now.
