### ISSUE TITLE
[FEATURE] Change of ergonomy of the visibility of layers inside groups

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1611]
Original commit: https://github.com/qgis/QGIS/commit/60a17013770a16b35fec3cd83a85bca9ced5e6ce by rouault

See https://github.com/qgis/QGIS-Enhancement-Proposals/issues/86

- Checking/unchecking a group doesn't change the check state of its children.
A node is visible if and only if it is checked and all its parents too.
- There is no more a semi-checked state for a group
- Ctrl-clic on a unchecked group will check the group and all its descendants.
- Ctrl-clic on a unchecked layer will check the lager and all its parents.
- Ctrl-clic on a checked group will uncheck the group and all its descendants.
- Ctrl-clic on a checked layer will uncheck the layer and all its parents.
- Those actions are available in contextual menu items in the tree view.
- Invisible layers because they or their parent(s) is unchecked are greyed out.

**Comment by havatv** [comment]
I can't find the old behaviour documented in the user manual, and I guess this is intuitive and does not need documentation.

**Comment by DelazJ** [comment]
The old behavior was not documented because it was not... well, not sure someone was able to explain easily and clearly how it worked.
And I think that the "new" ctrl-click behaviour is worth mentioning. Not sure how people could find it, otherwise.

**Comment by havatv** [comment]
> And I think that the "new" ctrl-click behaviour is worth mentioning. Not sure how people could find it, otherwise.

OK. But where in the documentation does this belong?

**Comment by DelazJ** [comment]
https://docs.qgis.org/testing/en/docs/user_manual/introduction/general_tools.html#interact-with-groups-and-layers

**Comment by havatv** [comment]
> https://docs.qgis.org/testing/en/docs/user_manual/introduction/general_tools.html#interact-with-groups-and-layers

Thanks. I have included a mention of the ctrl + check there.
