### ISSUE TITLE
[FEATURE][processing] remove TauDEM provider from core Processing

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1619]
Original commit: https://github.com/qgis/QGIS/commit/80d0d05b18410c3cee830916a984daa4b20eb260 by alexbruy

TauDEM is quite specific set of tools and it requires installation of
some additional tools. So we decide to turn it into separate provider,
reducing core codebase size and maintenance efforts.

Tagged as feature to not forget mention in changelog and documentation

**Comment by havatv** [comment]
Currently only seems to be mentioned in the processing guide (other programs, others) in the training manual.
