### ISSUE TITLE
[composer][needs-docs] Rename "world file map" option to "reference map"

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1622]
Original commit: https://github.com/qgis/QGIS/commit/e0934d7766f626731b3a8e3c436727ffa1700e7c by nyalldawson

This option will be used for more than just world file generation,
and instead will indicate which map should be considered the master
map for the composition from which any composer properties
calculating map units will derive the scale from.

**Comment by DelazJ** [comment]
Fixed in #1775
