### ISSUE TITLE
[FEATURE] API to enable/disable editing of raster data

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1632]
Original commit: https://github.com/qgis/QGIS/commit/f6f6ebdb441d45b750090801f5a7c671d563f5f8 by wonder-sk

To create a 2x2 raster block with one byte per pixel:

```
block = QgsRasterBlock(Qgis.Byte, 2, 2)
block.setData(b'\xaa\xbb\xcc\xdd')
```

To overwrite existing raster data at position 0,0 by the 2x2 block:

```
provider.setEditable(True)
provider.writeBlock(block, band, 0, 0)
provider.setEditable(False)
```

**Comment by havatv** [comment]
If this is to be documented, it goes in the cookbook (not exposed through the GUI).
