### ISSUE TITLE
 [FEATURE] symbol level drawing in group layers

### ISSUE THREAD

**Issue by Laiv-mv** [qgis/QGIS-Documentation#1639]
QGIS needs a "symbol level drawing" in group layers like ArcGIS. 
Currently there is only a "symbol level drawing" in each single layer.

**Comment by DelazJ** [comment]
Hi,
Please do not report application issues in this repository. This one is dedicated to [QGIS documentation](http://www.qgis.org/en/docs/index.html) matters. Better report issues or ask for new features in the application at http://hub.qgis.org or, if need be, discuss them in the [user/developer](http://qgis.org/en/site/getinvolved/mailinglists.html) mailing list. More information at http://qgis.org/en/site/getinvolved/development/bugreporting.html
Thanks
