### ISSUE TITLE
[FEATURE] API call to make geometries valid (port of ST_MakeValid)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1651]
Original commit: https://github.com/qgis/QGIS/commit/b245ccc105ff8456c39444b9cbe6bcbed0ce44b3 by wonder-sk

This introduces QgsGeometry::makeValid() which will try to make a valid
geometry out of invalid one. This is more complicated method than just
doing a buffer with zero width, but it should not loose any vertices.

Finally we should have a reliable way in QGIS to fix bad geometries!

Ported the C code from lwgeom library to QGIS.

**Comment by havatv** [comment]
Geometry functions are documented in the QGIS Python API, not in the Cookbook.
