### ISSUE TITLE
[FEATURE][processing] removed otb and lidartools providers

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1669]
Original commit: https://github.com/qgis/QGIS/commit/5939ae23e7906a542222d1be060216a2de5b2639 by web-flow

[FEATURE][processing] removed otb and lidartools providers

Tagged as feature to not forget mention this in changelog and docs

**Comment by havatv** [comment]
I can't find OTB or lidartools mentioned in the docs now.  Closing.
