### ISSUE TITLE
[FEATURE][processing] algorithm to fix invalid geometries using native
makeValid() implementation

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1674]
Original commit: https://github.com/qgis/QGIS/commit/0293bc76a0bb6e7ec55df59b8bb2764204552247 by alexbruy

Unfortunately this naughty coder did not write a description... :-(

**Comment by ghtmtt** [comment]
closed by 3b4c1a97e84950db62bfdb8c8a755cb6edcd7f0f
