### ISSUE TITLE
Using a double slash in a page link breaks its formatting

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#1675]
With the new generic help system landed in master, users can reach online documentation from within the application. Thanks to @alexbruy and the others.
If instead of http://docs.qgis.org/2.14/en/docs/user_manual, the users write http://docs.qgis.org/2.14/en/docs/user_manual/ (note the slash at the end) for the documentation path to use, the hyperlink created when hitting the help button is like http://docs.qgis.org/2.14/en/docs/user_manual//introduction/qgis_configuration.html#options which returns a kind of plain text of the real page (no images rendered e.g.). 
This was reported at http://hub.qgis.org/issues/16156 but @alexbruy suggested me to also report it at the server side in order to have double slash behaviour tackled there as well (given that this can occur while typing the link in the browser too). Here it's.

@rduivenvoorde ?

**Comment by havatv** [comment]
2.14 behaviour is still the same, and the same behaviour is observed for 3.4.

**Comment by havatv** [comment]
Sems to work for testing and 3.10. Closing.

**Comment by DelazJ** [comment]
I can not confirm. I still get plain text, not the usual rendering of the pages. Mind sharing what you get?

**Comment by havatv** [comment]
From "Assign projection", when I click the "Help" button, the link that is opened is:
* 3.12.3: https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/vectorgeneral.html#qgisassignprojection.
* 3:10.3: https://docs.qgis.org/3.10/en/docs/user_manual/processing_algs/qgis/vectorgeneral.html#qgisassignprojection

**Comment by rduivenvoorde** [comment]
@havatv @DelazJ maybe we have to look how Apache is handling this (leading slashes is a common issue with webserver configuration in combi with mod_rewrite...)

**Comment by DelazJ** [comment]
From the software, people shouldn't get a broken link so let's not fill issues queue with nitpicking issues we won't work on soon...
