### ISSUE TITLE
Documentation calls "Menu" to the Vector/Raster Properties tabs

### ISSUE THREAD

**Issue by SrNetoChan** [qgis/QGIS-Documentation#1678]
Both the vector and raster properties description, we are calling "Menus" (e.g. "General menu"), to the properties dialog tabs (e.g. "General tab").

https://github.com/qgis/QGIS-Documentation/blame/master/source/docs/user_manual/working_with_vector/vector_properties.rst#L38

This is probably old stuff. But not sure if it was a conscient decision.

**Comment by DelazJ** [comment]
Yes, I've been puzzled by this at the beginning and opted to follow what was done. But I think that using tab would be more appropriate. Also note that in the Labels tab, both menu and tab are used for its tabs (it would worth a fix, also).

**Comment by DelazJ** [comment]
Or maybe, we should simply remove mention of "menu" or "tab" in the title

**Comment by SrNetoChan** [comment]
Or, in the titles, we can use "settings" or "properties" ?

General properties
==============

General settings
============

**Comment by DelazJ** [comment]
I'd vote for "properties"

**Comment by SrNetoChan** [comment]
I will make a PR with this. Thanks for the input.
