### ISSUE TITLE
[FEATURE] Background saving of vector layers

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1686]
Original commit: https://github.com/qgis/QGIS/commit/95d000f66233ab6cb62051872962d0f9c12d7706 by nyalldawson

Switches the vector layer save operation to a background task
using the task manager framework. Allows layers to saved without
blocking the interface.

**Comment by DelazJ** [comment]
I think this does not need to be documented.

**Comment by havatv** [comment]
Agreed.
