### ISSUE TITLE
[FEATURE] allow to configure maximum request size for WMS requests (fixes #16182)
Hardwired setting was 2000, which is still default.

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1703]
Original commit: https://github.com/qgis/QGIS/commit/baa5d90ddc58e469b5bdbb602793f00ec74bcb91 by jef-n

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment]
Seems to be documented in the user guide (18.2. QGIS as OGC Data Server):
> Furthermore, you can restrict the maximum size of the maps returned by the GetMap request by entering the maximum width and height into the respective fields under Maximums for GetMap request.

**Comment by agiudiceandrea** [comment]
@havatv @DelazJ It seems to me the feature introduced with https://github.com/qgis/QGIS/commit/baa5d90ddc58e469b5bdbb602793f00ec74bcb91 is not documented in the user guide: the feature is about the client, not the server.

As you can see, in the doc the current image for the Add WMS/WMTS Layer Window is:
![image](https://user-images.githubusercontent.com/16253859/90528865-64643980-e173-11ea-9220-6e679d0ab6a8.png)

But, actually the Add WMS/WMTS Layer Window in 3.10 has one more option: "**Request step size**" (in red) which was introduced right with https://github.com/qgis/QGIS/commit/baa5d90ddc58e469b5bdbb602793f00ec74bcb91 

![image](https://user-images.githubusercontent.com/16253859/90529726-54008e80-e174-11ea-9594-1ca623704850.png)

**Comment by agiudiceandrea** [comment]
I can't figure out what exactly "Request step size" option is for and how it differs from "Tile size" option...

**Comment by havatv** [comment]
> I can't figure out what exactly "Request step size" option is for and how it differs from "Tile size" option...

I have checked qgis/QGIS@baa5d90, and they both seem to "map" to `mTileWidth` (```<widget class="QLineEdit" name="mTileWidth"/>```). Confusing. I think we need input from a developer on this.

**Comment by agiudiceandrea** [comment]
It seems to me that the "Request step size" parameters map to mStepWidth and mStepHeight, while the "Tile size" ones to mTileWidth and mTileHeight

**Comment by anitagraser** [comment]
Based on https://github.com/qgis/QGIS/issues/24092, it sound like these options are meant to deal with the issue of tiled WMS cutting off labels. I think the implemented solution is to request larger tiles where only the central part is displayed in QGIS so that the label placements are not affected by the tile borders. Therefore the requested larger tiles need to be overlapping. The amount of overlap is defined by the request step size. Based on this logic, request step size should always be smaller than tile size.

**Comment by nirvn** [comment]
It also can reduce the number of queries sent to the server by having a larger request size (say you are requested a map rendering of 4000 x 4000 pixels, increasing the request size to 4000 x 4000 would lead to one request to the server instead of four)

**Comment by agiudiceandrea** [comment]
Thanks @nirvn. The issue is about the missing description of the "Request step size" option in the docs, as you can see at https://docs.qgis.org/3.22/en/docs/user_manual/working_with_ogc/ogc_client_support.html#loading-wms-wmts-layers

> The Options area of the dialog provides means to configure the WMS requests. You can define:
> 
> - Tile size    if you want to set tile sizes (e.g., 256x256) to split up the WMS request into multiple requests.
> 
> - The Request step size
>
> - The Maximum number of GetFeatureInfo results from the server

**Comment by nirvn** [comment]
Yeah, so request step size -> internal, vs. tile size being a size sent to the server I'd assume.

**Comment by anitagraser** [comment]
Thank you, @nirvn. Does that mean that my "overlap" interpretation/explanation from 13 days ago is correct?
