### ISSUE TITLE
[FEATURE][processing] New algorithm for topological coloring of polygons

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1709]
Original commit: https://github.com/qgis/QGIS/commit/1cf0a20267de67d225061a351276e90b5c886fc8 by nyalldawson

This ports to old (pre 2.0!!) topocolor plugin to processing. It's based
off my beta 2.x fork (never publicly released) which implemented
a bunch of improvements to the algorithm allowing for minimal number
of required colors and also balanced counts of features assigned
each individual color.

** Pretty sure this plugin was highlighted in Victor's presentation
about plugins-which-shouldn't-be-plugins-and-should-be-processing-algs
instead. It's a prime example of a plugin where the amount of code
required for gui+setup exceeded the actual "guts" of the plugin by
a huge factor, and which is much more useful when it can be
integrated into a larger processing model.

**Comment by DelazJ** [comment]
Fixed in #2156
