### ISSUE TITLE
[Foreword] QT link is dead

### ISSUE THREAD

**Issue by ponceta** [qgis/QGIS-Documentation#1717]
Hi,

On the foreword page. QT link is dead :
https://docs.qgis.org/2.14/en/docs/user_manual/preamble/foreword.html

Actually:

`QGIS is developed using the Qt toolkit (http://qt.digia.com)`

Proposed:

`QGIS is developed using the Qt toolkit (https://www.qt.io)`

**Comment by DelazJ** [comment]
fixed in a1c8e16
