### ISSUE TITLE
[FEATURE] Allow setting project CRS to "no projection"

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1724]
Original commit: https://github.com/qgis/QGIS/commit/899888d1c533df37b8c60a1cc9532d2055710652 by nyalldawson

This replaces the older "OTF off" setting. If a project has
no projection set, then the following things happen:

- no reprojection is done while rendering - features are just
drawn using their raw coordinates
- ellipsoid, distance and area units, and coordinate display
are locked out.
- all measurements are done in unknown map units, and no conversion
is possible.

As well as addressing the use cases in which users disabled
OTF reprojection, this setting may also be useful for users
who use QGIS to create "non-earth" maps, such as RPG or fantasy
maps, or for microscopic analysis, or some other local reference
system not related to earth based projections.

**Comment by cvvergara** [comment]
I am trying to use
> QGIS to create "non-earth" maps
I read the #2812 
I still cant figure how to do it
My data comes from postgres and the srid defined is 0

This what I am using

QGIS version | 3.4.2-Madeira | QGIS code revision | 5645791
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
PostgreSQL Client Version | 10.3 (Ubuntu 10.3-1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493

**Comment by havatv** [comment]
@cvvergara, this not really the place for these kinds of questions.  You could try the qgis-user email list.
But I think you can set "no projection" in the project properties dialogue by checking "No projection (or unknown/non-Earth projection" under the CRS "tab" -see the included screen shot.
![image](https://user-images.githubusercontent.com/1598812/50046923-2a908500-00ac-11e9-8bf0-754b0505afaf.png)

**Comment by cvvergara** [comment]
Thanks
