### ISSUE TITLE
[WIP] Add documentation for Advanced Digitizing panel

### ISSUE THREAD

**Issue by yjacolin** [qgis/QGIS-Documentation#1727]
# This text is currently a really draft description of the feature, contributions are welcome as comments

The Advanced Digitizing panel can be open either with a right-clic on the toolbar and choose Advanded Digitizing panel or in :menu:Preference -> Panel -> Advanced Digitizing Panel.

To start it, enable the panel from the Advanced Digitizing toolbar (the first icon).

## Concepts
You can digitize feature or create some intermediate point in order to locate a feature in regards of the position of other features.

You can also create constraints with relative or absolute reference. Relative reference means that the next vertex constraint will be relative to the previous vertex or segment.

## Parallel line or Perpendicular line

Enable the editing mode then start to create your feature, in order to create a parallel or a perpendicular line, click on the desired shortcut in the Advanced Digitizing panel then select an existing line (the line become highlighted with dark orange color) somewhere in the canvas as reference of the line you want to create and add the line.

**Comment by yjacolin** [comment]
@pcav short description for the parallel and perpendicular mode. Do you think that the different steps are  clear enought? Need screenshot though.

**Comment by pcav** [comment]
IMHO the steps could be detailed. @ghtmtt could you please add content?

**Comment by ghtmtt** [comment]
@yjacolin I'll step in to help to improve the documentation. Should I write the content in this issue or directly in the section (http://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/editing_geometry_attributes.html#the-advanced-digitizing-panel)?

**Comment by yjacolin** [comment]
Matteo,

You can do as you want. If you work on the rst file, could you manage it
completely?

Y.

**Comment by ghtmtt** [comment]
yes no problem to manage directly rst files. I wrote some pieces of the QGIS documentation (I should also have commit rights ;) ).
Ok, so I will write on my fork and then create a PR (the target branch is release_2_18 right?)

Thanks @yjacolin

**Comment by yjacolin** [comment]
It should be master f I am not wrong.

**Comment by SrNetoChan** [comment]
@yjacolin  can we close this one? #1742 seems to solve it, right?
