### ISSUE TITLE
[FEATURE] Add system tray notifcation for finished tasks.

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1728]
Original commit: https://github.com/qgis/QGIS/commit/c2b365c70e88c59a7873d657a1a6db465dee57fe by NathanW2

Should work on all platforms and only shows when application is hidden.

**Comment by DelazJ** [comment]
Not worth documentation?

**Comment by havatv** [comment]
Not important enough, I think. Could of course be mentioned, but not necessary.
