### ISSUE TITLE
[Feature] Conditional styles for relation reference widget

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1730]
Original commit: https://github.com/qgis/QGIS/commit/ac53a3d56932123aaaaed44d05cb2d48fb890c57 by m-kuhn

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment]
If this is to be documented, I think we need some input on where and how. With no input, I suggest we close.

**Comment by DelazJ** [comment]
> If this is to be documented, I think we need some input on where and how. With no input, I suggest we close.

*nine hours later (in the night) havatv closed this*

@havatv general comment if I may: If you do not give time nor ping the original author, there's indeed less chance to have any information. Also note that the url in the issue message brings you to the implementation pull request, where you can sometimes find more details.

**Comment by havatv** [comment]
> @havatv general comment if I may: If you do not give time nor ping the original author, there's indeed less chance to have any information. Also note that the url in the issue message brings you to the implementation pull request, where you can sometimes find more details.

I should have mentioned that re-opening is welcome, but apart from that I see no problems with closing issues in this way.
