### ISSUE TITLE
[Feature] Path prefix for attachment widget can be defined by expression

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1731]
Original commit: https://github.com/qgis/QGIS/commit/c1ede008ea083addbb6dbdfee568a26f1b4fb26a by m-kuhn

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment]
Difficult to see where this should be documented, so closing. If documentation is required, please re-open with more information about where and how.
