### ISSUE TITLE
[feature] Add support for square centimeters / square millimeter units

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1741]
Original commit: https://github.com/qgis/QGIS/commit/91da1f5817d0df049fdcaf71e7ec976152104c0a by m-kuhn

Note for documentation writers, centimers / millimeters support has been
added as well in a previous commit.

**Comment by DelazJ** [comment]
@m-kuhn what does this refer to? I can't find any place where these units appear. Thanks

**Comment by m-kuhn** [comment]
It was mainly a core addition and every item that would be dynamic enough to work with this would be automatically adjusted...
Turns out, most parts just hardcode lists of available unit types.
... I added it to the measure dialog now so it can be documented ;) ...
