### ISSUE TITLE
[NEEDS-DOCS][processing] Move configuration to qgis options dialog

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1744]
Original commit: https://github.com/qgis/QGIS/commit/9f23dd24142dfd4d7775602f2b876a5d03c2124c by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment]
Closing. There's now much to write on Processing configs so no need to hold this report (which is actually fixed in #1795 )
