### ISSUE TITLE
MetaSearch: update images to reflect UI changes

### ISSUE THREAD

**Issue by tomkralidis** [qgis/QGIS-Documentation#1750]
As per https://github.com/qgis/QGIS/commit/4d77431b98533aaf268b41ddc11ccee1ce45c9e2

Milestone should be 3.0. Putting as placeholder for now given UI will likely change between now and then.

**Comment by havatv** [comment]
I think this one is too broad to be useful. Should we close it @DelazJ?

**Comment by DelazJ** [comment]
The single place Metasearch is documented is at https://docs.qgis.org/testing/en/docs/user_manual/plugins/core_plugins/plugins_metasearch.html so it's a matter whether the screenshots there are uptodate

**Comment by havatv** [comment]
I don't think Metasearch is that relevant here.  The question is if this issue is useful for improving the QGIS documentation. Since I am the only one who has used it (and have used it only once), I doubt that it will help us much.

**Comment by DelazJ** [comment]
> I don't think Metasearch is that relevant here

The issue title states: "MetaSearch: update images to reflect UI changes". So I fail to understand the irrelevance of Metasearch here.
I don't understand what you are referring to by being the only one to use in the rest of the message

**Comment by havatv** [comment]
Sorry, somehow, I must have missed the title...
We should keep this one open, then.

**Comment by havatv** [comment]
The only file that seems to be affected: source/docs/user_manual/plugins/core_plugins/plugins_metasearch.rst
