### ISSUE TITLE
[FEATURE][needs-docs] new custom widget: password edit with built-in show/hide
password button.

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1760]
Original commit: https://github.com/qgis/QGIS/commit/1ef68358cb321926e660318200fd9b90beeab1a5 by alexbruy

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment]
This should not need documentation, or? Might be relevant for developers.
