### ISSUE TITLE
Revert "[FEATURE] Allow using secondary zoom wheel on mouse to magnify canvas"

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1770]
Original commit: https://github.com/qgis/QGIS/commit/0d3cf5748304988374b93324ee7ada67202336f4 by nyalldawson

This reverts commit ecc49256a37d4333d9cefdeefff1f3fd7a38d893.

Works very badly for touchpads, where horizontal movement is interpreted
as a magnify request

**Comment by DelazJ** [comment]
Closed because of #1769
