### ISSUE TITLE
[FEATURE] Add a secondary stroke color to QgsRubberBand (#4301)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1776]
Original commit: https://github.com/qgis/QGIS/commit/9c5abc958798416da93f2f657c8db90e3ecd53e0 by web-flow

This comes in handy when in need of insure visibility of a
marker/line/polygon overlay over both light and dark areas.
This also updates the map view's extent to make use of a
secondary stroke color instead of a semi-transparent fill.

**Comment by havatv** [comment]
Belongs in the API docs.
