### ISSUE TITLE
Building QGIS 3 Wiki: `./configure` ... `-qt-xcb`  for Ubuntu 17.04

### ISSUE THREAD

**Issue by sildeag** [qgis/QGIS-Documentation#1778]
Which dependency is needed or is adding `-qt-xcb` the correct approach?

**Comment by DelazJ** [comment]
@rduivenvoorde what is the status of the Build chapter in the wiki and @sildeag reports?

**Comment by rduivenvoorde** [comment]
@DelazJ @sildeag we have asked to move this content to his own fork, see:

https://lists.osgeo.org/pipermail/qgis-psc/2017-March/005136.html

He did:

https://github.com/mj10777/QGIS/wiki

and I promissed to write a blogpost or tweet about it (which I forgot). But I will at least answer in that PSC thread now.

So @sildeag can you please move your issues from the QGIS-Documentation tracker to mark's issues? Or at least close them here?

Thanks for monitoring this Harrissou

**Comment by sildeag** [comment]
I noticed that the wiki was moved.

**Comment by sildeag** [comment]
I closed my issues.

 

Note:  the exercise did allow me to resolve the problem I had with PyQt5 resulting in a dependency on Qt5.8, it now uses Qt5.7.1.

**Comment by DelazJ** [comment]
Thanks @sildeag
