### ISSUE TITLE
[FEATURE] New API QgsGeometry::densifyByCount

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1779]
Original commit: https://github.com/qgis/QGIS/commit/5360b79174866c48d61387b673bb1dcc15d9886a by nyalldawson

Densifies a geometry by adding a specified number of vertices
to each segment

**Comment by havatv** [comment]
API only?

**Comment by DelazJ** [comment]
Yes. The application was porting the eponym alg to C++, hence transparent for doc.
