### ISSUE TITLE
[processing][needs-docs] Processing API improvements

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1784]
Original commit: https://github.com/qgis/QGIS/commit/b8cb196322d829982fbca9be6b938c3a69c6a60d by web-flow

[processing][needs-docs] Processing API improvements

**Comment by havatv** [comment]
Changes (in processing/tools/general.py):
algoption -> algorithmOptions
alglist ->algorithmsList
runalg -> run
runandload -> runAndLoadResults
alghelp -> algorithmHelp

and (in AlgorithmExecutor.py)
runalgIterating -> executeIterating
runalg -> execute

**Comment by havatv** [comment]
There may still be some issues left, but I close it now.  Please report remaining issues.
