### ISSUE TITLE
[FEATURE] New class QgsInternalGeometrySnapper

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1785]
Original commit: https://github.com/qgis/QGIS/commit/ece3991dbee3931cc478ec342644dcaa22844df3 by nyalldawson

Used for snapping geometries within a set of features to other
features from that same set.

Just like QgsGeometrySnapper, except that where QgsGeometrySnapper
requires a separate reference layer to snap to
QgsInternalGeometrySnapper snaps *within* a single layer. E.g.
allows you to close gaps within that layer.

**Comment by havatv** [comment]
API only?

**Comment by DelazJ** [comment]
Yes, the application is in #1786
