### ISSUE TITLE
[FEATURE] Add geometry snapper modes to only snap end points of lines

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1787]
Original commit: https://github.com/qgis/QGIS/commit/636e9c5ea3c5a2656867159c35d0d801c96664fd by nyalldawson

Allows snapping of end points only, or end point to end point only

Also update processing algorithm to match

**Comment by DelazJ** [comment]
I don't know if there's another place (digitizing chapter?) this report will be treated but for reference, it's already done in "Snap to geometry" alg description (#2255)
