### ISSUE TITLE
GPG error NO_PUBKEY 089EBE08314DF160

### ISSUE THREAD

**Issue by justinnoor** [qgis/QGIS-Documentation#1790]
Hi. If you have time, please review the QGIS Installers Documentation for Ubuntu Xenial 16.04.

I installed Las Palmas 2.18.5 on Ubuntu Xenial 16.04 LTS, following the instructions at:
http://www.qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu

The following error was generated:
W: GPG error: http://ppa.launchpad.net/ubuntugis/ubuntugis-unstable/ubuntu xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 089EBE08314DF160

I resolved it with:
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key 089EBE08314DF160

This key is not referred to in the documentation. Sorry in advance if I've missed anything.

**Comment by DelazJ** [comment]
@justinmnoor According to http://qgis.org/en/site/getinvolved/development/bugreporting.html the best place for this kind of issues is https://github.com/qgis/QGIS-Website/issues/

**Comment by TeAmigo** [comment]
Thanks for the tip. Haven't delved into apt enough to even try what you mention, but it worked! Had to change the key to the error value on my machine.

**Comment by DelazJ** [comment]
key has been updated meanwhile so closing
