### ISSUE TITLE
[FEATURE] Implement saving paletted raster renderer color tables

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1799]
Original commit: https://github.com/qgis/QGIS/commit/7eb63d99dceddbe7ea10a51149800d0e0326c19a by nyalldawson

Use the .clr/gdal file format, but add the labels on the ends of
the lines. Seems other importers like ArcMap just ignore these.

**Comment by havatv** [comment]
Saving styles is documented in "11.6 Save and Share Layer Properties", both with text and a screen shot. It is available for all layers, so no need to mention it specifically for paletted rasters.

**Comment by DelazJ** [comment]
This is not about saving the raster style but storing/loading a paletted classification, ie the following this `...` drop-down menu
![image](https://user-images.githubusercontent.com/7983394/73350894-30d0c900-428e-11ea-9f44-cf31fe13b2a2.png)
Follow the link for the original commit/PR

**Comment by havatv** [comment]
Fine. I have tried to update the documentation (text only).

**Comment by havatv** [comment]
Should be fixed now.
