### ISSUE TITLE
[FEATURE] [needs-docs] MetaSearch: add support for ESRI MapServer/FeatureServer layer integration (fixes #16320)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1807]
Original commit: https://github.com/qgis/QGIS/commit/c403994d02ef26e7e508f777f22d58013c129683 by tomkralidis

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment]
Fixed in #3435
