### ISSUE TITLE
[FEATURE] new custom widget — combobox with checkable items

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1815]
Original commit: https://github.com/qgis/QGIS/commit/638dbcad1c3e203c887a68fa1c94dc7f0875cbba by alexbruy

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment]
If this should be documented, please re-open and provide information about what / how to document and where in the documentation this belongs. (I guess this might be relevant for developers, but can't find any of the other widgets documented)
