### ISSUE TITLE
[feature][needs-docs] Master Password integration with OS password manager

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1820]
Original commit: https://github.com/qgis/QGIS/commit/090d5305e5134b99fcccce2d4602bbe1478d6d8f by elpaso

This PR adds (optional) synchronization of the master password
with the OS password manager (AKA wallet/keychain).

A set of new menu items has been added in the options ->
authentication -> utilities to manage the new behavior.

Notifications are handled by the message bar unless the
password r/w operation is triggered from a modal dialog,
in this case the notifications will be routed through
the recently exposed QgisApp::showSystemNotification
that uses the OS tray notifications.

This new feature requires libqt5keychain, and was tested
with v. 0.5+

**Comment by havatv** [comment]
Additions to the "Utilities" pull-down in *Options-> Authentication* (compared to current master documentation - user manual, 20.1. Authentication System Overview):

![image](https://user-images.githubusercontent.com/1598812/82767084-04d0e900-9e25-11ea-95e6-b4a4d939e26b.png)
