### ISSUE TITLE
[needs-docs] use QgsPasswordLineEdit in the master password dialog

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1826]
Original commit: https://github.com/qgis/QGIS/commit/c749057f0270fa437acd96b08d7bb3c4dc0f1634 by web-flow

[needs-docs] use QgsPasswordLineEdit in the master password dialog

**Comment by havatv** [comment]
In what way is this relevant/interesting for the user?

**Comment by ghtmtt** [comment]
I don't think this is worth a specific documentation. I see this improvement as an API one and it is well documented in the pyqgis and C++ API. If somebody will add a section with some code that involves password typing then we can suggest to use `QgsPasswordLineEdit`.

Closing the issue, please reopen if necessary.
