### ISSUE TITLE
Better connections between QGIS 3 and documentation releases

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#1834]
From https://github.com/qgis/QGIS/commit/09d126325cc033cf6e23ef8bd9ce8fa5780a3f18 (Add online QGIS User Guide as default help source)

NOTE: to use online QGIS user Guide as help source in QGIS application we still need some server-side tweaks: 
- redirection to the testing docs for non-LTR QGIS versions 
- and redirection to english docs for not supported locales

**Comment by DelazJ** [comment]
More insight (also reported at https://issues.qgis.org/issues/17486):
With the Help button (being) added to dialogs, user should directly be able to find the appropriate web page of the dialog he's using. It's a nice way to teach him the dialog features but also, and we could expect, for those who know, incitate them to directly fix issues in documentation.
However, in its default implementation, it does not work.
Afaict, in QGIS, a URL to user manual is built based on the current language and version used. Problem is that languages (or the code of languages) used in the application do not match what is provided in documentation, leading to a Not Found page.
What is needed in the QGIS repository is:
- to match the languages that are provided in both places (for example, en_US <--> en, fr_FR <--> fr, ca <--> ca....)
- to return the english version when there's no correspondance (there are many more languages in application than in doc).
- Also note that for dev version, only english is provided so maybe always fallback to english when the provided link will likely return a not found page, eg, test catalan if requested and if not found test english. (don't quite know!)

Set as Blocker because not fixing this is like providing a broken feature by default and would not help for its adoption.

**Comment by ghtmtt** [comment]
I think we have to tweak something here:

https://github.com/qgis/QGIS/blob/master/python/plugins/processing/gui/AlgorithmDialogBase.py#L262

@alexbruy is that right?

**Comment by DelazJ** [comment]
@ghmtt i think this issue is more about how requested languages are handled by QGIS-Documentation server than the way Processing help buttons construct them.

**Comment by DelazJ** [comment]
Fixed weeks ago
