### ISSUE TITLE
Rephrasing Actions section in vector_properties.rst

### ISSUE THREAD

**Issue by yjacolin** [qgis/QGIS-Documentation#1835]
From line 2048 to 2059: https://github.com/qgis/QGIS-Documentation/blame/master/source/docs/user_manual/working_with_vector/vector_properties.rst#L2048-L2058

**Comment by DelazJ** [comment]
@yjacolin I think the link provided is no longer referring to the text you wish to fix: line numbers have changeed due to new texts inserted.

**Comment by yjacolin** [comment]
Here a new link to a specific commit: https://github.com/qgis/QGIS-Documentation/blame/293e7c87ae47e0a8fee6a705ca2993617bae2a43/source/docs/user_manual/working_with_vector/vector_properties.rst#L2048-L2058
