### ISSUE TITLE
Add code-block in guideline

### ISSUE THREAD

**Issue by yjacolin** [qgis/QGIS-Documentation#1838]
Guidelines should explain how to use code-block.

**Comment by yjacolin** [comment]
See pygments list here: http://pygments.org/docs/lexers/ and info on rst here: http://www.sphinx-doc.org/en/stable/markup/code.html

**Comment by DelazJ** [comment]
Isn't this a duplicate of #1722 ?
FYI I've been working on it at https://github.com/qgis/QGIS-Documentation/compare/release_2.18...DelazJ:code-block I don't know if it's enough though I can't see what other worthy information I could add; Indeed I think that we should be careful to not overload our guidelines with things a writer could find elsewhere (we do not have to teach him sphinx but let him know about choices we made for our documentation among all the rules and techniques provided by this language)

**Comment by yjacolin** [comment]
I propose to merge it as it is. You can probably add a link to pygments list, probably also on the sphinx doc as you did it for index.

For me such addition is enought, specially with link to look further.
