### ISSUE TITLE
[FEATURE] customizable output width and height in save as image dialog

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1875]
Original commit: https://github.com/qgis/QGIS/commit/fa7a3e7aff07b03d2ac2a0e48af974c7661cabf5 by nirvn

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment]
Width and height of image in pixels.

**Comment by DelazJ** [comment]
@havatv Actually, this relates to "Project --> Export --> Save Map as Image" which does not have a dedicated section (despite an _another broken_ help button)
