### ISSUE TITLE
Link to JTS homepage is broken

### ISSUE THREAD

**Issue by JakobMiksch** [qgis/QGIS-Documentation#1881]
This link  is broken: http://www.vividsolutions.com/jts/discussion.htm#spatialDataModel

The docs refer to the link here:  http://docs.qgis.org/2.18/en/docs/pyqgis_developer_cookbook/geometry.html#geometry-handling

Here the source:
https://github.com/qgis/QGIS-Documentation/blame/master/source/docs/pyqgis_developer_cookbook/geometry.rst#L15

**Comment by SrNetoChan** [comment]
Seems that their site link is borken as well:

http://www.vividsolutions.com/products.asp?catg=spaapp&code=jts

**Comment by DelazJ** [comment]
Would that make sense to replace this link by http://www.opengeospatial.org/standards/sfa?

**Comment by SrNetoChan** [comment]
@DelazJ  that sounds like a good idea. We might have to change the text a bit, as the OGC document is not really easy to consult.

**Comment by DelazJ** [comment]
Oh, sure it's not readable 😃 
See #2671
