### ISSUE TITLE
Link broken: "remote debugging QGIS Python plugins with pyDev" 

### ISSUE THREAD

**Issue by bufferclip** [qgis/QGIS-Documentation#1884]
This link is broken:
http://linfiniti.com/2011/12/remote-debugging-qgis-python-plugins-with-pydev

It is referenced here: 
https://github.com/qgis/QGIS-Documentation/blame/release_2.18/source/docs/pyqgis_developer_cookbook/ide_debugging.rst#L216

EDIT:
here the link to the actual documentation http://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/ide_debugging.html#id7

**Comment by DelazJ** [comment]
Thanks @bufferclip If you find other broken links, could you also add the online doc link to your report, please? Would help to read the context. Thanks

@timlinux can you help on this, please?

**Comment by bufferclip** [comment]
@DelazJ I added the link to the online documentation above. 

Is raising an issue actually the right way to notify about a broken link?

**Comment by DelazJ** [comment]
Yes, it's a first and necessary step.
Next steps could be to look for the new/fixed link and either report it or propose a patch (a pull request) to have it fixed in the doc.
