### ISSUE TITLE
[needs-docs] Add a "shuffle random" option to color ramp button

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1896]
Original commit: https://github.com/qgis/QGIS/commit/927faf70370b0d196d6c8580f72dc3c4ce29d9df by nyalldawson

Allows quick regeneration of a new set of random colors if the
current color ramp is a random color ramp.

**Comment by havatv** [comment]
This is documented (14.1.3 Symbology Properties):
"You can click the Shuffle Random Colors entry to regenerate a new set of random colors if you
are not satisfied."
