### ISSUE TITLE
[FEATURE] Import layers to data providers in background

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1907]
Original commit: https://github.com/qgis/QGIS/commit/64b612f2a880a047cb7f89e8219e81a8ceaf3894 by nyalldawson

Flips the drag and drop import of layers to browser data sources
to use task manager, allowing these slow imports to occur
in the background.

**Comment by DelazJ** [comment]
Btw this one too @havatv. Closing?
