### ISSUE TITLE
[FEATURE] add clone() methods for layers

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1916]
Original commit: https://github.com/qgis/QGIS/commit/7b20c2e8b3892ff2a2960552299f9ba9d1327242 by pblottiere

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment]
This is documented in the QGIS API docs.  If someone would like to include this in cookbook examples, I suggest that they file a separate issue for that.
