### ISSUE TITLE
[processing][needs-docs] always use SAGA shipped with QGIS (refs #16422)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1917]
Original commit: https://github.com/qgis/QGIS/commit/b9929d4c2a8b68721542f7ff594a958051428dd8 by alexbruy

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment]
Does this belong in "Configuring external applications" (3rdParty.rst) in the QGIS processing framework part of the user manual?
