### ISSUE TITLE
[FEATURE] Add option to take extent from project map layer
to QgsExtentGroupBox

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1928]
Original commit: https://github.com/qgis/QGIS/commit/4e4f232ad49c0600c8b05747e51cbc9f47c01607 by nyalldawson

This allows matching another layer's extent in the save vector/
raster layer dialog, among others

Fix #16357

**Comment by havatv** [comment]
The "extent selector" is is documented for spatial bookmarks and for processing algorithms, and the "Calculate from Layer"/"Use layer extent" option is included.
The screenshot for processing could be updated.

**Comment by DelazJ** [comment]
>  The screenshot for processing could be updated.

Any particular processing screenshot concerned?

**Comment by havatv** [comment]
> Any particular processing screenshot concerned?

The one that I just updated :-)

**Comment by DelazJ** [comment]
👍
