### ISSUE TITLE
Broken links in "QGIS as OGC Data Server" chapter

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#1935]
The introduction of http://docs.qgis.org/2.18/en/docs/user_manual/working_with_ogc/ogc_server_support.html ends with three hyperlinks for more information. Two of those links are borken:
* http://hub.qgis.org/projects/quantum-gis/wiki/QGIS_Server_Tutorial (our closed redmine wiki!)
* and http://linfiniti.com/2010/08/qgis-mapserver-a-wms-server-for-the-masses/: @timlinux any idea where we could find replacements for linfiniti.com broken links? see also #1884 . Thanks

**Comment by elpaso** [comment]
I believe you can safely delete the tutorial link, the information on the official manual are much more reliable and up to date now.

**Comment by DelazJ** [comment]
@elpaso yes, I'll do.
And what about the third link about plugins in server(http://www.itopen.it/qgis-server-python-plugins-ubuntu-setup/)? Are these information available in any QGIS official doc (user manual or Pycookbook)?
Thanks

**Comment by elpaso** [comment]
The third link (that I authored) has been the most complete guide for a couple of years, but now I believe that @tudorbarascu ported all its content to the main manual and the cookbook. 
I think that it must also be removed (I'm not maintaining it anymore).
