### ISSUE TITLE
[FEATURE][processing] Add checkbox for each vector input layer
to control whether selected features only are to be used

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1939]
Original commit: https://github.com/qgis/QGIS/commit/7f687345f8544af22b4f688223713aeb98af027e by nyalldawson

Replaces the old global setting and makes it immediately obvious
to users when the selection will be respected

**Comment by havatv** [comment]
I guess this is scattered all over the place, so I close it. If someone has input on specific places in the documentation that should be updates, please reopen and specify.
