### ISSUE TITLE
Improve DB Manager description

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#1949]
it might be nice to complete a bit the [DB Manager page](http://docs.qgis.org/2.18/en/docs/user_manual/plugins/plugins_db_manager.html) in Plugins chapter. DB Manager can do more than what's described (e.g., gui to build sql queries, table versioning...)

**Comment by timlinux** [comment]
@DelazJ I am closing this since DB Manager should be avoided in favour of browser workflows now right?
