### ISSUE TITLE
[FEATURE] Subdivide algorithm for QgsGeometry

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1953]
Original commit: https://github.com/qgis/QGIS/commit/e74395d95bd326788ce55f2a7caa31435fed9ea9 by nyalldawson

Subdivides the geometry. The returned geometry will be a collection
containing subdivided parts from the original geometry, where no
part has more then the specified maximum number of nodes.

**Comment by ghtmtt** [comment]
closed by 3b4c1a97e84950db62bfdb8c8a755cb6edcd7f0f
