### ISSUE TITLE
[FEATURE][processing] New algorithm for subdividing geometries

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1954]
Original commit: https://github.com/qgis/QGIS/commit/4dcf8d8d10249971f5ec1358a172078e11e6bad8 by nyalldawson

The returned geometry will be a collection containing subdivided parts
from the original geometry, where no part has more then the specified
maximum number of nodes.

This is useful for dividing a complex geometry into less complex parts,
which are better able to be spatially indexed and faster to perform
further operations such as intersects on. The returned geometry parts may
not be valid and may contain self-intersections.

**Comment by ghtmtt** [comment]
closed by 3b4c1a97e84950db62bfdb8c8a755cb6edcd7f0f
