### ISSUE TITLE
Structure the "Server configuration and supported parameters" chapter

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#1965]
Looking to the [QGIS Server doc in user manual](http://docs.qgis.org/2.18/en/docs/user_manual/working_with_ogc/ogc_server_support.html) and particularly the TOC below, it's not really easy (especially for beginners) to identify what are the default provided variables and specific ones, which variable is linked to which parameter...  

![capture d ecran 2017-06-26 a 12 46 05](https://user-images.githubusercontent.com/7983394/27536012-771f3da8-5a6d-11e7-888b-6ca54c48060d.png)

It'd be nice to have all this reorganized. Some points:

- [ ] describe first what is provided in all installation (and move the environment variables section at the top?)
- [ ] list the custom "extra parameters ..." variables together instead of have them interrupted by different global (?) parameters
- [ ] Any reason to have "Redlining" in upper case?

@tudorbarascu any chance you handle this, please? Among current active contributor, you are the one more involved in Server doc. Thanks.

**Comment by tudorbarascu** [comment]
Sure. I'll assign it to myself. It will have to wait a while though.

**Comment by DelazJ** [comment]
Fixed in #2017
