### ISSUE TITLE
[needs-docs] Mouse wheeling over font buttons can change font size

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1974]
Original commit: https://github.com/qgis/QGIS/commit/e95b65ef48b6778f08a18a4ed0fd87d54ad2e965 by nyalldawson

With ctrl+mouse wheel changing in smaller size increments

**Comment by havatv** [comment]
I don't think this needs to be documented.

**Comment by havatv** [comment]
If this is to be documented, please re-open and provide information about what and where.
