### ISSUE TITLE
Data to test N-m relations and associated widgets

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#1978]
Following #1905 I found data at https://openflights.org/data.html (their license seems compatible) but it would require a certain amount of work I can't afford to limit data to the single Alaska. It'd be nice to have them in order to:
- test the N-M relation for a doc writer perspective,
- produce screenshots (there isn't currently)
- and later use them to create a n-m chapter in the training manual (?).

**Comment by ghtmtt** [comment]
I'd say #3516 closes this. We don't have something in the training manual, but the addition to the user manual is more than complete

**Comment by DelazJ** [comment]
> I'd say #3516 closes this.

I don't know... The idea here is to provide data we can use to maintain this feature. If new options/features arise and we need to document them (I personally tend to test a feature before writing about) and add screenshot, we already have the compatible data, and we  have the relation set in a project, instead of individually look for data, and have to recreate the relation from scratch.
Also if we want to explore the numerous options in the vector layer properties --> Attribute forms tab, we need more complete/complex and "linkable" dataset.

**Comment by ghtmtt** [comment]
yep, but IMHO the code snippet for the geopackage provided is fully working. Moreover in the example a lot of screenshot and widgets are described. 

But of course, feel free to reopen this if necessary!
