### ISSUE TITLE
[FEATURE] New unit type for rendering in map unit meters sizes

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1983]
Original commit: https://github.com/qgis/QGIS/commit/172e80918131bb8414c753a463a9b7abc069e0bf by nyalldawson

Allows setting symbols other map item sizes to Map Units in Meters. This allows setting the size always in meters, regardless of what the underlying map units are (e.g. they can be it geographic degrees). The size in meters is calculated based on the current project ellipsoid setting and a projection of the distances in meters at the center of the current map extent.

**Comment by havatv** [comment]
Related to #2314? Could it be closed?
