### ISSUE TITLE
[needs-docs] Add optional weight field to Points In Polygon algorithm

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1985]
Original commit: https://github.com/qgis/QGIS/commit/b67e525f295394826a2af652505744e64515d63e by nyalldawson

Instead of a separate Points In Polygon algorithm just for this
extra option, add it to the original Points In Polygon algorithm
as a non-default option.

**Comment by DelazJ** [comment]
Fixed in #2239
