### ISSUE TITLE
Creating new Oracle connection: document "Options" parameter

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#1987]
all is in the title

**Comment by TomGeoDK** [comment]
I second the request. It is not clear what options can be used there or what syntax to use.

**Comment by havatv** [comment]
In 13.1.3 Provider-based loading tools we have:
```
The spatial features in Oracle Spatial aid users in managing geographic and location data in a native type within an Oracle database. In addition to some of the options in Creating a stored Connection, the connection dialog proposes:
• Database: SID or SERVICE_NAME of the Oracle instance;
• Port: Port number the Oracle database server listens on. The default port is 1521;
• Workspace: Workspace to switch to.
Optionally, you can activate the following checkboxes:
...
```
and a number of options are listed.

Does this mean that some options are missing, or is there a separate options part that is missing?
I don't have Oracle support, so I can't check.

**Comment by DelazJ** [comment]
There's an `Options` entry
![addOracle](https://user-images.githubusercontent.com/7983394/81681864-cc103780-9454-11ea-9ff2-8dc055070362.PNG)

**Comment by havatv** [comment]
I have looked at the code, and "Options" seems to be QT related (QSqlDatabase). For possible options, see https://doc.qt.io/qt-5/qsqldatabase.html#setConnectOptions. Perhaps we could include that link in the documentation?
Is relevant at least for MSSQL, Oracle and DB2.

**Comment by DelazJ** [comment]
@troopa could you please help us understand what the "Options" entry is supposed to address? The section in doc is at https://docs.qgis.org/testing/en/docs/user_manual/managing_data_source/opening_data.html#connecting-to-oracle-spatial

**Comment by DelazJ** [comment]
Oups I hit the wrong troopa!
> It is not clear what options can be used there or what syntax to use.

@troopa81 Could you help us document what the "Options" textbox in the Oracle Connection dialog is about? Thanks

**Comment by troopa81** [comment]
Options are given to [setConnectOptions](https://doc.qt.io/qt-5/qsqldatabase.html#setConnectOptions) methods.

According to the documentation

> The format of the options string is a semicolon separated list of option names or option=value pairs.

And the possible Oracle (OCI) options are the following

>  OCI_ATTR_PREFETCH_ROWS
>  OCI_ATTR_PREFETCH_MEMORY

But it's unclear to me if it's possible to deal with other Oracle specific connection option.

I would say for documentation

> Options : Oracle connection specific options. The format of the options string is a semicolon separated list of option names or option=value pairs.

**Comment by DelazJ** [comment]
Thanks @troopa81
