### ISSUE TITLE
Explain columns in the "Add PostGIS table(s)" dialog

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#1988]
It could be nice to address:
- ~~what the "select at id" column means~~
- complaints from people who have the same layer shown multiple times in the table list with missing value in geometry or primary id columns

**Comment by lajunek** [comment]
@DelazJ I will implement this

**Comment by havatv** [comment]
In 3.12, the dialogue has the title "Data Source Manager | PostgreSQL", but is still opened with "Add PostGIS Layer..." (in *Layer-> Add Layer* or the "Manage Layers Toolbar").

![image](https://user-images.githubusercontent.com/1598812/82766565-78bcc280-9e20-11ea-95ad-f34903bc7fed.png)

**Comment by havatv** [comment]
> @DelazJ I will implement this

@lajunek, has this been implemented?

**Comment by anitagraser** [comment]
For reference, this explanation should go into: https://docs.qgis.org/testing/en/docs/user_manual/managing_data_source/opening_data.html#loading-a-database-layer

**Comment by anitagraser** [comment]
> complaints from people who have the same layer shown multiple times in the table list with missing value in geometry or primary id columns 

Is this still happening? I think this issue may have been solved.

**Comment by timlinux** [comment]
@DelazJ I think we can close this right? Please reopen if you disagree and I will assign it to @selmaVH1
