### ISSUE TITLE
Document creating new MSSQL connection dialog

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#1989]
All is in the title (the dialog is currently different from other providers - I suppose it might be for a good reason, e.g. how is the database list filled)

**Comment by havatv** [comment]
There is a separate section on this already: "Connecting to MSSQL Spatial". The contents is:

> In addition to some of the options in Creating a stored Connection, creating a new MSSQL connection dialog proposes you to fill a Provider/DSN name. You can also display available databases.

If this is not enough, please re-open this issue with some more information on what to include.
