### ISSUE TITLE
[FEATURE] Give access to geometry errors

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1990]
Original commit: https://github.com/qgis/QGIS/commit/2b2d5e3637949b0059004392ab57c6eeee865039 by m-kuhn

When methods are called that use GEOS to create new geometries, the
result geometries now contain information about what has gone wrong in
case of an error.

In practice, this means it's possible to give more detailed information
in place (and not only in the message log) when things like processing
algorithms fail.

**Comment by nyalldawson** [comment]
Doesn't need documenting
