### ISSUE TITLE
[FEATURE] New algorithms to add Z/M values to existing geometries

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1992]
Original commit: https://github.com/qgis/QGIS/commit/340cf93f93fb28e1aa9e23b2d80a7c38e6a89d6c by nyalldawson

Allows upgrading geometries to include these dimensions, or
overwriting any existing Z/M values with a new value.

Intended mostly as a test run for QgsProcessingFeatureBasedAlgorithm

**Comment by ghtmtt** [comment]
closed by 3b4c1a97e84950db62bfdb8c8a755cb6edcd7f0f
