### ISSUE TITLE
[FEATURE] First experiment with preloading

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1994]
Original commit: https://github.com/qgis/QGIS/commit/2d531e5814c1b43a23c36d09ace9a5f5729e5bb4 by nyalldawson

After main map canvas render is complete, render a separate image
for each adjacent map "tile" (in the background). These are shown
when panning the map to display a preview of what will be visible
when the panning operation ends.

**Comment by DelazJ** [comment]
As far as I remember, this has been reverted, right? @nyalldawson

**Comment by nyalldawson** [comment]
No, not reverted. Just much much refined, so now it only prerenders "fast" layers

**Comment by DelazJ** [comment]
Not sure this needs a mention in docs. Should be transparent to the user.

**Comment by nyalldawson** [comment]
I'd close, I don't think it's needed
