### ISSUE TITLE
Making dialog titles use Book Style Capitalization [needs-docs]

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2009]
Original commit: https://github.com/qgis/QGIS/commit/8d4dec5c3f2ca6169a0f0b65413687a4625c2b44 by SrNetoChan

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment]
Although it may lead to some needed replacemnt of :guilabel:`...`, this is not a user manual issue and has been already documented in the developer's guide
