### ISSUE TITLE
Add precision on .GPX layers particularities

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#2014]
When creating a new GPX file, it adds three layers to layers panel. It could be nice to precise relationship among these three layers, particularly when it's about editing: role of each layer, constraints on each file if ever, could they be edited separately and keep a valid file...?

**Comment by havatv** [comment]
In the User manual (the GPS plugin section), it is documented that three layers can be created from a GPX file. The documentation of the semantics of these and the relationships between these can be found elsewhere, so therefore does not need to be included in the QGIS documentations.
