### ISSUE TITLE
Merge pull request #4942 from gacarrillor/relation_reference_widget_fixes

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2016]
Original commit: https://github.com/qgis/QGIS/commit/cf753e9ff4778d62b632b88f203b8e3285b06677 by web-flow

[needs-docs] Relation Reference Widget: Add option to show/hide Open Form Button

**Comment by DelazJ** [comment]
Duplicate of #2015
