### ISSUE TITLE
[FEATURE][needs-docs][processing] add parameter representing raster band

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2022]
Original commit: https://github.com/qgis/QGIS/commit/f96442884b248694b36405f6909bcb1740baed27 by web-flow

[FEATURE][needs-docs][processing] add parameter representing raster band

**Comment by havatv** [comment]
The only documentation of processing parameter types is a list in using processing algorithms from the console section. ParameterBand is included. I am therefore closing this one. If this needs more documentation, a new issue should be filed.
