### ISSUE TITLE
MS Visual C++ 5.0 needed for XP SP3 and QGIS 32-bit 2.18.11

### ISSUE THREAD

**Issue by ab1vl** [qgis/QGIS-Documentation#2046]
## Description

Install of 32-bit LA Palmas goes without incident on win XP SP3 but launching some main program items via created shortcuts fails with error 0xc0xc0150002, which decodes to VC80.crt not installed.  Note I had several later versions of VC++ installed but not VC++ 5.0.  Installing this enabled launching of QGIS Desktop 2.8.11 but then load throws a "saga_cmd.exe is not a valid win32 application" error.  <CR> continues program load.  Evidently functions requiring saga_cmd.exe are not supported in 32 bit QGIS versions running on 32-bit windows systems.  Limitations should be pointed out in a System Requirements note in the installation section of the documentation AND a note on the downloads page.   

From SourceForge:

"SAGA CMD is a command line interface to execute SAGA modules. Other than SAGA GUI, it provides no functionality for data management and data visualization. It's purpose is to automate tasks by writing scripts or to execute SAGA modules from within an other application like a web server. This section will describe the necessary setup of your system to use SAGA CMD and execute modules."

## Checklist
> This is the issue/bug trackers for [QGIS Documentation](https://docs.qgis.org).
Cleaning the queue is a process done by project maintainers, mostly on a volunteer basis.
We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items.

- [x] I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage.

**Comment by nyalldawson** [comment]
Not a documentation issue
