### ISSUE TITLE
EPSG instead of EPGS in documentation

### ISSUE THREAD

**Issue by danceb** [qgis/QGIS-Documentation#2047]
At the page "17.33. R Syntax Summary table for Processing" within the table "17.33.1. Input parameters" the 
returning object for the parameter "crs" is mentioned as "string of the resulting CRS chosen, in the format: "EPGS:4326"". I think it should be "EPSG" instead of "EPGS".
 
https://docs.qgis.org/2.14/en/docs/training_manual/processing/r_syntax-table.html#input-parameters

Greatings, Dan.

**Comment by DelazJ** [comment]
Fixed in #2212
