### ISSUE TITLE
[needs-docs] Refactoring of all help calls, deprecating QgsContextHelp+Helpviewer

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2051]
Original commit: https://github.com/qgis/QGIS/commit/55cdc89a11b010b8c548f24298d285b449cd9fa4 by web-flow

[needs-docs] Refactoring of all help calls, deprecating QgsContextHelp+Helpviewer

**Comment by DelazJ** [comment]
Documented in #2520 (even if many dialogs still do not have the help button connected - but that this the application issue)
