### ISSUE TITLE
[feature][needs-docs] Adds delete layer context action to ogr and geopackage items

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2052]
Original commit: https://github.com/qgis/QGIS/commit/11fb601a9810fb584f8cc02ef37cdc3c9db55cff by web-flow

[feature][needs-docs] Adds delete layer context action to ogr and geopackage items

**Comment by havatv** [comment]
This should be sufficiently documented.
