### ISSUE TITLE
[feature] Geopackage handle drops in the browser

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2053]
Original commit: https://github.com/qgis/QGIS/commit/e6814bca2c9a21df814e30b78ecfa4af42539246 by elpaso

It is now possible to drag and drop from any vector
layer onto a gpkg node layer and import a layer.

Overwrites are protected by a confirmation dialog.

**Comment by havatv** [comment]
This is (and was?) documented in chapter 13.1.1 (Managing Data -> Opening Data -> The Browser Panel), as a general feature that includes databases:

```
To add a layer into a project, using the Browser interface:
1. Enable the Browser as described above. A browser tree with your file system, databases and web services is
displayed. You may need to connect databases and web services before they appear (see dedicated sections).
2. Find the layer in the list.
3. Double-click its name or drag-and-drop it into the map canvas. Your layer is now added to the Layers panel
and can be viewed in the map canvas.
```
