### ISSUE TITLE
Search doesn't work in Testing documentation

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#2059]
## Description
Let's do a search in the QGIS Doc search bar, using "Offline" word.
In 2.18: the link is http://docs.qgis.org/2.18/en/search.html?q=offline&check_keywords=yes&area=default which returns a result
In Testing: the link is http://docs.qgis.org/testing/en/search.html?q=offline&check_keywords=yes&area=default endlessly searches --> No result is returned

This had been reported in irc few weeks ago but not here... And still present!

@rduivenvoorde any idea?
## Checklist
> This is the issue/bug trackers for [QGIS Documentation](https://docs.qgis.org).
Cleaning the queue is a process done by project maintainers, mostly on a volunteer basis.
We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items.

- [x] I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage.
If it's related to QGIS application or website, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html for the right issue tracker or to the [support channels](http://qgis.org/en/site/forusers/support.html)
- [x] I have added a link to the page concerned by the issue

**Comment by rduivenvoorde** [comment]
Ok, crux is that newer sphinx themes added some more configurations, and our QGIS theme is based on older Sphinx themes... 
Have to dig a little deeper to get results PLUS context but for now we at least have some results back:
http://docs.qgis.org/testing/en/search.html?q=offline&check_keywords=yes&area=default 
problem though is that with frequently used words like 'calculator' you really need the context:
http://docs.qgis.org/testing/en/search.html?q=calculator

Logic to retrieve the context is that an ajax request retrieves the source (.rst) file from the server and that part is shown then. That is why in the 2.18 results you do not actually see the html/output text in the result context, but the (rst) source from which this output is created.

Anyway: will look later into resurrecting that....

**Comment by DelazJ** [comment]
still better to have results than an unfinished work. Thanks!

**Comment by havatv** [comment]
Search works now. So I am closing this one. @DelazJ, please feel free to reopen if you disagree.
