### ISSUE TITLE
Export/Add Geometry Columns

### ISSUE THREAD

**Issue by AStefanski89** [qgis/QGIS-Documentation#2063]
I have to say - this feature is absolutely TERRIBLE in 2.18. It was easy to use and simple in 2.14 - just the way I need it when calculating areas for multiple layers in our project GIS (archaeological project - basically taking GPS points of sites).

Please return this feature to how it was in 2.14, it is just abysmal in 2.18 - confusing, time consuming to use.

**Comment by DelazJ** [comment]
@AStefanski89 Please take the time to read the issue report template. You'd have understood that this repository is not the place to report such issues (only documentation issues are allowed here). See http://qgis.org/en/site/getinvolved/development/bugreporting.html for other places.
Thanks.
