### ISSUE TITLE
[FEATURE] New algorithm for creating vector layer from raster layer's extent

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2064]
Original commit: https://github.com/qgis/QGIS/commit/44e7f3371e9d131e5c6799634f89451dbbaefadf by nyalldawson

Allows creation of a new vector layer with a single feature containing
a raster layer's extent. Previously this was only possible for
vector layers.

**Comment by DelazJ** [comment]
This alg was later merged in the Extract layer extent alg described in #2130
