### ISSUE TITLE
[FEATURE][Processing] Minimal enclosing circle

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2069]
Original commit: https://github.com/qgis/QGIS/commit/e30f7044c9af22096dda8722d188d452228d420c by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by ghtmtt** [comment]
closed by 3b4c1a97e84950db62bfdb8c8a755cb6edcd7f0f
