### ISSUE TITLE
Document the layer styling customization in Cookbook

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#2071]
Using Python, user can add new custom tabs to the Layer Styling Panel. Could be nice to document an example in the PyQGIS CookBook.
There's one at https://nathanw.net/2016/06/29/qgis-style-dock-part-2-plugin-panels/ but in the long run, better have an integrated one if possible...

**Comment by havatv** [comment]
Could this one be closed, @DelazJ ?

**Comment by DelazJ** [comment]
Is it covered or is it not worth documentation?

**Comment by havatv** [comment]
I just noticed that you referenced it from a merged pull request.

**Comment by DelazJ** [comment]
The PR simply mentions this report creation and covers the issue from an end user point of view (like layer properties dialog extension).

**Comment by ghtmtt** [comment]
@DelazJ @havatv the updated link is https://woostuff.wordpress.com/2016/06/29/qgis-style-dock-part-2-plugin-panels/ but even with the API correction it is not working anymore:


```python
class CustomPanel(QgsMapLayerConfigWidget):
    def __init__(self, layer, canvas, parent):
        super(CustomPanel, self).__init__(layer, canvas, parent)
        self.layer = layer
 
    def apply(self):
        pass

class PanelFactory(QgsMapLayerConfigWidgetFactory):
    def icon(self):
        return QIcon('/home/matteo/icon.svg')
 
    def title(self):
        return 'matteo'
 
    def supportsLayer( self, layer):
        return layer.type() == QgsMapLayer.VectorLayer
 
    def createPanel(self, layer, canvas, parent):
        return CustomPanel(layer, canvas, parent)
 
# Also make a instance and tell the style dock about it
# make sure you keep a instance of the the factory around
factory = PanelFactory()
iface.registerMapLayerConfigWidgetFactory(factory)
```

**Comment by ghtmtt** [comment]
Partially covered here https://github.com/qgis/QGIS-Documentation/pull/5973

I just added a `tip` that mention this chance, but at least we have a python API reference (and we know that it is possible to do :) )
