### ISSUE TITLE
Missing "Next" button at the top of the Testing doc

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#2073]
## Description

The Testing documentation doesn't provide a `Next` button (at the top right of the screen) to help navigate from page to page (e.g. http://docs.qgis.org/testing/en/docs/user_manual/preamble/foreword.html)

@rduivenvoorde ?
## Checklist
> This is the issue/bug trackers for [QGIS Documentation](https://docs.qgis.org).
Cleaning the queue is a process done by project maintainers, mostly on a volunteer basis.
We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items.

- [x] I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage. If it's related to QGIS application or website, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html for the right issue tracker or to the [support channels](http://qgis.org/en/site/forusers/support.html)
- [x] I have added a link to the page concerned by the issue

**Comment by rduivenvoorde** [comment]
@ghtmtt @DelazJ mmm, I have been looking into this. But the html code is actually just build, it is not a styling thing, it is just not there....

http://docs.qgis.org/2.18/en/docs/user_manual/index.html
vs
http://docs.qgis.org/testing/en/docs/user_manual/index.html

Only thing I can think of is that the testing docs are build with a newer Sphinx/Python/Docker combi.
That is: we build it using the older Sphinx templates.
On my wish list (before releasing) is to get/adjust a new template based on one of the modern Sphinx templates. So I think I'll leave it for now?

**Comment by DelazJ** [comment]
Fixed, apparently.
