### ISSUE TITLE
[FEATURE] Split minimum enclosing geometry algs into separate
feature based algorithms

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2077]
Original commit: https://github.com/qgis/QGIS/commit/85cd1c1673bfa150c8f9ef785dfeda2ad6d59c35 by nyalldawson

Instead of algorithms which handle both whole layers/groups
of features/individual features, we leave the whole layer
and group of features handling to the "Minimum bounding
geometry" algorithm.

The feature-by-feature algorithms are now native c++
algorithms.

This affects:
- bounding boxes
- convex hulls
- minimum enclosing circle
- minimum oriented rectangles

**Comment by DelazJ** [comment]
Fixed in #2255
