### ISSUE TITLE
Merge pull request #5111 from nyalldawson/min_bounding_geom_alg

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2078]
Original commit: https://github.com/qgis/QGIS/commit/b5bb7df7eb0c1f5b8bb64c52780d4e7fabcb0bb4 by web-flow

[FEATURE] New processing algorithm "minimum bounding geometry"

**Comment by DelazJ** [comment]
duplicate #2076
