### ISSUE TITLE
[FEATURE] Native 'Promote to Multipart' algorithm

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2079]
Original commit: https://github.com/qgis/QGIS/commit/3484eb019c2b8eb682e5a41ff9e6e4b14b9e97d4 by nyalldawson

This algorithm is basically the equivalent of the ST_Multi(...)
command - it forces a feature's geometry to become multipart,
regardless of the input geometry type.

If input geometries are singlepart, they will output as
multipart with just 1 part. If they are already multipart,
they will be output unchanged.

**Comment by ghtmtt** [comment]
closed by 3b4c1a97e84950db62bfdb8c8a755cb6edcd7f0f
