### ISSUE TITLE
[FEATURE] Remove Singleparts to Multiparts algorithm

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2081]
Original commit: https://github.com/qgis/QGIS/commit/a55fbd8ef349a52c166b69b70ce6cfccad8c42aa by nyalldawson

This algorithm is no longer required - it's been replaced by
the 'Promote to multipart' and 'Collect geometries" algorithms.

Tagged as feature to remember to include in release notes

**Comment by ghtmtt** [comment]
closed by 3b4c1a97e84950db62bfdb8c8a755cb6edcd7f0f
