### ISSUE TITLE
[FEATURE][needs-docs] Add XYZ connection to provide default OpenStreetMap tiles

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2089]
Original commit: https://github.com/qgis/QGIS/commit/f0e021c2fda13c56649698430645b15ef930e1a9 by web-flow

[FEATURE][needs-docs] Add XYZ connection to provide default OpenStreetMap tiles

**Comment by DelazJ** [comment]
closed in #4800
