### ISSUE TITLE
[FEATURE] Improve Stats by Categories algorithm

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2090]
Original commit: https://github.com/qgis/QGIS/commit/4e78e034a1fdea4bc8bede8a872c72be32cf9684 by nyalldawson

- allow non spatial inputs
- allow calculation of stats on any field type, with specific
string and datetime stats calculated when field type matches
- output a full set of stats for numeric fields (including median
, quartiles, etc)
- also calculate stats for 'null' category

**Comment by DelazJ** [comment]
I wonder if it's not already documented

**Comment by ghtmtt** [comment]
@DelazJ in fact yes:

https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/vectoranalysis.html#statistics-by-categories

or better, I don't see anything to add to the description. 

I'll go on and close this issue (we can reopen it)
