### ISSUE TITLE
[FEATURE] Allow multiple category fields in 'stats by category'

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2091]
Original commit: https://github.com/qgis/QGIS/commit/30866190e984290583a9690f443db7a26e5f2bd5 by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by ghtmtt** [comment]
already mentioned in the documentation that the user can use multiple fields

https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/vectoranalysis.html#statistics-by-categories
