### ISSUE TITLE
[feature][needs-docs] Add Gpkg tab in source select dialog

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2093]
Original commit: https://github.com/qgis/QGIS/commit/32dee4480c660979eae0853ecb8705503027c52f by web-flow

[feature][needs-docs] Gpkg tab in source select dialog

**Comment by havatv** [comment]
Some illustrations may need to be updated?

**Comment by DelazJ** [comment]
We can see gpkg tab in the main screenshot [here](https://docs.qgis.org/testing/en/docs/user_manual/managing_data_source/opening_data.html#opening-data) and that path is also mentioned when [creating a gpkg layer](https://docs.qgis.org/testing/en/docs/user_manual/managing_data_source/create_layers.html#creating-a-new-geopackage-layer) so this one can be closed
