### ISSUE TITLE
[FEATURE] QGIS - GeoNode Integration: Integrate with QGIS Browser Panel (#4816)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2094]
Original commit: https://github.com/qgis/QGIS/commit/bea89b32ca19a63d9eb2f582490e33efe7023e7f by nyalldawson
Include GeoNode as one of the sources of the data in QGIS. GeoNode has WFS, WMS, WCS that can be consumed by QGIS. This PR is the implementation of adding GeoNode as a new source in data source manager dialog in QGIS.
See https://github.com/qgis/QGIS/pull/4816 for more context

**Comment by DelazJ** [comment]
As a tab of the "[Data Source Manager](https://docs.qgis.org/testing/en/docs/user_manual/managing_data_source/opening_data.html)" I think it should be documented (mentioned at least). 
I cleaned a bit the initial repot message.

**Comment by havatv** [comment]
GeoNode is mentioned in the Browser panel section (13.1.1.) of the Opening Data part of Managing data sources chapter.
