### ISSUE TITLE
[FEATURE] Reworked processing 'Join by location' alg

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2097]
Original commit: https://github.com/qgis/QGIS/commit/458e994d39fe1033a0a27e02c7d59416446fe6a0 by nyalldawson

Improvements:
- transparently handle different source/join CRS
- added option to create output feature for EVERY joined
feature (i.e. 1 to many type join)
- added option to select joined fields to take
- optimised performance of algorithm

The previous option to create a summary of joined features has been
removed, and will be moved to a separate 'Join by location (summary)'
algorithm.

**Comment by DelazJ** [comment]
fixed in #2334
