### ISSUE TITLE
[FEATURE][processing] Add 'Join by location (summary)' algorithm

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2098]
Original commit: https://github.com/qgis/QGIS/commit/be88da8173a5ca16071f976da10f14c30be9177a by nyalldawson

Like the main Join Attributes by Location algorithm, this algorithm
takes two layers and combines the attributes based on a spatial
criteria.

However this algorithm calculates summaries for the attributes for
all matching features, e.g. calculating the mean/min/max/etc.

The list of fields to summaries, and the summaries to
calculate for those, can be selected.

**Comment by DelazJ** [comment]
fixed in #2334
