### ISSUE TITLE
[FEATURE][processing] Allow drag and drop of model files onto QGIS window
to execute them

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2101]
Original commit: https://github.com/qgis/QGIS/commit/6300464275914ab8bfef6dd5eb2617bc9c9ff26e by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment]
Fixed in #5440 and follow-ups.
