### ISSUE TITLE
Broken link: Sample data - 14.1.1. Forestry Sample Data

### ISSUE THREAD

**Issue by xaaria** [qgis/QGIS-Documentation#2105]
Link to the sample data on page https://docs.qgis.org/2.2/en/docs/training_manual/forestry/forestry_intro.html
is broken. Please fix it.

**Comment by DelazJ** [comment]
@xaaria QGIS 2.2 is no longer maintained and you'll find the same exercise (with I hope valid data in [QGIS 2.18 training manual](https://docs.qgis.org/2.18/en/docs/training_manual/forestry/forestry_intro.html). Please follow that doc.
