### ISSUE TITLE
Keeping Vector and Raster menus sections in Processing chapter?

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#2123]
Looking at 
http://docs.qgis.org/testing/en/docs/user_manual/processing/index.html… i am a bit uncomfortable to have the Vector menu (and obviously Raster menu in the future) at that place because:
- this chapter is about Processing configs and main tools/providers/scripting while Vector is mainly about algorithms description (algorithms do have their own description chapter)
- it's weird to begin the chapter with algs description
- the Processing doc refactoring will describe these algs so kind of redundancy

With the current implementation, Vector and Raster are filled either by Processing algorithms or plugins (Core or external). We could
- just mention that in [QGIS GUI](http://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_gui.html#vector) chapter
- and add an information in each concerned algorithm description whether a default shortcut is provided (and which one it's). 

## Checklist
> This is the issue/bug trackers for [QGIS Documentation](https://docs.qgis.org).
Cleaning the queue is a process done by project maintainers, mostly on a volunteer basis.
We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items.

- [x] I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage.
If it's related to QGIS application or website, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html
for the right issue tracker or to the [support channels](http://qgis.org/en/site/forusers/support.html)
- [x] I have added a link to the page concerned by the issue

**Comment by SrNetoChan** [comment]
@DelazJ sorry for the delayed reply. I agree. I would feel much more comfortable to have it directly in the GUI (which may be a bit overkill), or in Working with Vectors (not strong opinion where).

I think for each menu item there is also missing a link to more in details explanation in the algorithms section. That is, together with you #2215 proposal, there would be a 2 way connection between the Processing Algorithm description and the menu items descriptions.

**Comment by DelazJ** [comment]
> sorry for the delayed reply. 

No problem
> I would feel much more comfortable to have it directly in the GUI (which may be a bit overkill)

Not only it would be overkill but it would also break current structure: from what i can see only the first level items are mentioned in the GUI tables, not sub-items. Hence algs can't be listed there nor described and in any case description would be redundant with processing help chapter.
> or in Working with Vectors (not strong opinion where).

I can't see where in the Working with Vectors chapter and still my concern is duplication of algs description. We should take advantage of @ghtmtt refactoring to move any valuable information to Processing chapter and remove these chapters (old Ftools and Gdal).

Still, it'll remain the need to cross link vector/raster menus from GUI chapter to Processing algs.
### From now I'm thinking aloud
Assuming we want to point each vector submenu (say "Analysis Tools") to a (single) page in Processing we'd need to:
- ensure that submenu has the same name than Processing Toolbox algs group (I'm not sure there's any correspondance) - Not sure how those namings are chosen and maybe it's a nice time to  try to normalize this.
- ensure that all tools from the Vector submenu belong to a unique group in the Toolbox - not sure it's the case and it's desirable if we want to freely push default shortcut to any alg.

An alternative I can see is to add something like an [index list](http://docs.qgis.org/2.18/en/genindex.html) of algorithms:
- clicking the link in GUI chapter will bring to that page with all the algorithms listed but also organized in a way that imbricates them under the submenus (the kind of things you get doing `.. index:: Analysis Tools; Distance Matrix`)
- clicking the algorithm from the "index" page" will bring to its help section

What I don't know in this scenario is how to generate the list of algorithms and how to add link from inside the vector table to that list. Any Sphinx guru?
Sorry for the looong monologue
