### ISSUE TITLE
Merge pull request #5213 from mhugent/capabilities_exclusive_groups

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2125]
Original commit: https://github.com/qgis/QGIS/commit/f4d5ca75c6e4d8a8d5b0029e7278c1a08e762868 by web-flow

[FEATURE]: In GetProjectSettings, show if a legend group is mutually exclusive

**Comment by DelazJ** [comment]
Duplicate. #2124
