### ISSUE TITLE
Proxy authentication integration with QGIS authentication system

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2127]
Original commit: https://github.com/qgis/QGIS/commit/829702bd24c65511f8a3e37ee18c21cb216d4fe4 by web-flow

[auth][feature][needs-docs] Proxy authentication integration with QGIS authentication system

**Comment by ghtmtt** [comment]
@DelazJ do you think we need to be more explicit? We already have this feature described in the docs:

https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html#network-settings

with a link to the auth configuration of QGIS. 

Screenshot is also updated

**Comment by DelazJ** [comment]
Indeed, I don't think we need more, here. Fixed in #2416
