### ISSUE TITLE
[FEATURE] Default values on update

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2132]
Original commit: https://github.com/qgis/QGIS/commit/08cb2d78d3be51e951e40f1bee80dc6209c34f64 by m-kuhn

Add an option to add default values on update of attributes or geometry.
This can be seen as a "derived value" that will be saved to the database
(like area of a polygon) or as a means to track last_modified dates etc.

See #5218

**Comment by DelazJ** [comment]
The default value ignores the other fields when creating the features, reason why they are not proposed in the expression builder dialog. Now with the update option, meaning that there are old, and I guess known, values in the other fields, how would this option behave if someone tries to use the other fields in an expression? Or does it still ignore anything from the other fields of the feature being updated?
@m-kuhn @nyalldawson

**Comment by m-kuhn** [comment]
It will respect other field's values, with various interdependent default values it is undefined behavior.
