### ISSUE TITLE
[needs-docs] Reshaping the Authentication widget

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2135]
Original commit: https://github.com/qgis/QGIS/commit/5bdb605fdaa41d03fbab203df04b743ebfd8f44e by web-flow

[auth][needs-docs] Authentication widget (see https://github.com/qgis/QGIS/pull/5270)

* Authentication widget that embeds both the username/password and the QGIS Authentication DB configurations
* Functionality to convert a username/password to a Basic auth configuration and store it in the auth DB
* Full test coverage for the new widget

**Comment by ghtmtt** [comment]
I think this feature is already documented in the whole QGIS doc. I scrolled many sections (https://docs.qgis.org/testing/en/docs/user_manual/managing_data_source/opening_data.html#creating-a-stored-connection, https://docs.qgis.org/testing/en/docs/user_manual/auth_system/auth_overview.html) and screenshots are updated and also the explanation is good IMHO.

I'm closing this, of course reopen if necessary and I'll be glad to add sections wherever you think they should :)
