### ISSUE TITLE
[FEATURE] Feature selection is also displayed in 3D map view for points

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2138]
Original commit: https://github.com/qgis/QGIS/commit/b0c98b7fccb9aa174c2456fb3953f8cc5bc91b60 by wonder-sk

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment]
Nothing to document here, or?

**Comment by ghtmtt** [comment]
@DelazJ @havatvI think we can close this issue. It is most related to the first implementation of 3D in QGIS. Please reopen if necessary :)
