### ISSUE TITLE
[FEATURE] support 3d models

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2139]
Original commit: https://github.com/qgis/QGIS/commit/7d3cf228d89e18b02f4095e1bb8c884e73fa0ea9 by wonder-sk

Unfortunately this naughty coder did not write a description... :-(

**Comment by anitagraser** [comment]
As far as I can see, this should be documented in https://docs.qgis.org/3.22/en/docs/user_manual/style_library/3d_symbols.html?highlight=3d%20model 

![image](https://user-images.githubusercontent.com/590385/201413668-b1abe950-df63-456f-b001-6bc1fe021429.png)

**Comment by anitagraser** [comment]
Should mention https://plugins.qgis.org/wavefronts/
