### ISSUE TITLE
[FEATURE] QGIS 3D (pull request #5203)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2140]
Original commit: https://github.com/qgis/QGIS/commit/68bb68d17682937bb8a9d1b26968303dc0de87fb by web-flow

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment]
Not complete, but 3D has now been documented.  I suggest that we close this one as it is way to general to be meaningful as a documentation issue.
