### ISSUE TITLE
[Feature][OGR] Support Triangle, TIN and PolyhedralSurface geometry types by mapping them to Triangle and MultiPolygon respectively

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2146]
Original commit: https://github.com/qgis/QGIS/commit/abaeb9e9c1767da3be0e03440b5e7907c188e24e by manisandro

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment]
I can't see what we could do for this one. Too low level. I suggest we close. Opinions?
