### ISSUE TITLE
Merge pull request #5298 from manisandro/ogr_tin_triangle

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2147]
Original commit: https://github.com/qgis/QGIS/commit/2f44d52ee547a306df39a0a2c9914020b5d49fca by web-flow

[Feature][OGR] Support Triangle, TIN and PolyhedralSurface geometry types by mapping them to Polygon and MultiPolygon respectively

**Comment by DelazJ** [comment]
duplicate #2146
