### ISSUE TITLE
[auth][needs-docs] Provider connection dialogs use the new auth settings widget

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2148]
Original commit: https://github.com/qgis/QGIS/commit/dcc672520cd0c8643f35ae69b2ed0d4b9f2ca563 by web-flow

[auth][needs-docs] Provider connection dialogs use the new auth settings widget

**Comment by ghtmtt** [comment]
Already documented, see https://docs.qgis.org/testing/en/docs/user_manual/managing_data_source/opening_data.html#creating-a-stored-connection
