### ISSUE TITLE
[FEATURE] Add 'materialize' method to QgsFeatureSource

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2158]
Original commit: https://github.com/qgis/QGIS/commit/bcb3e5f42594612177d07097f29e7c5e70c16584 by nyalldawson

When called, materialize takes a QgsFeatureRequest argument
and runs it over the source. The resultant features
are saved into a new memory provider based QgsVectorLayer, which
is returned by the function (along with ownership of the layer)

This makes it easy to create a new layer from a subset of an
existing one.

Materialize also considers subsets of attributes, so that the
returned layer only contains fetched fields (and not blank
fields filled with NULL values).

**Comment by havatv** [comment]
This is well documented in the QGIS API docs.
