### ISSUE TITLE
[FEATURE][processing] New 'assign projection' algorithm

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2161]
Original commit: https://github.com/qgis/QGIS/commit/61dc8ea28f42a5fed7e37cf5db8297c34b88accf by nyalldawson

This algorithm assigns a new projection to a vector layer.
It creates a new layer with the exact same features and
geometries as the input one, but assigned to a new CRS.
E.g. the geometries are not reprojected, they are just
assigned to a different CRS.

This algorithm can be used to repair layers which have
been assigned an incorrect projection.

**Comment by DelazJ** [comment]
fixed in #2334
