### ISSUE TITLE
[FEATURE] Port autoincremental field to c++

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2162]
Original commit: https://github.com/qgis/QGIS/commit/97c1b0d3223318e6110fa6c496b560e29e3a58c8 by nyalldawson

Also add:
- support for setting initial value for field to start at
- support for user-set field names (instead of always using 'AUTO')

**Comment by DelazJ** [comment]
Fixed in #2340
