### ISSUE TITLE
[FEATURE][DB Manager] Be able to update every Db layer from Postgres, Spatialite and Oracle

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2165]
Original commit: https://github.com/qgis/QGIS/commit/e6c64f69ce5c6f0c374f0d5a21f2052b262b97c0 by rldhont

Unfortunately this naughty coder did not write a description... :-(

**Comment by ghtmtt** [comment]
@DelazJ is this issue worth to document? IMHO it is handling something very useful, but under the hood. I'm closing this, please reopen if you think it is necessary!
