### ISSUE TITLE
Merge pull request #5316 from rldhont/db_manager_update_dblayer

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2166]
Original commit: https://github.com/qgis/QGIS/commit/949d2167449bb400f51def825b6b958b6ad503a2 by web-flow

 [FEATURE][needs-docs][DB Manager] Be able to update every Db layer from Postgres, Spatialite and Oracle

**Comment by DelazJ** [comment]
Duplicate #2165
