### ISSUE TITLE
[Server][FEATURE][needs-docs] Support WFS 1.1.0

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2172]
Original commit: https://github.com/qgis/QGIS/commit/ab107d0e8c248c8f71791ae41a55b48a0fe2fe14 by web-flow

[Server][FEATURE][needs-docs] Support WFS 1.1.0

**Comment by DelazJ** [comment]
@elpaso is this closed by your latest commits #2404 and #2405

**Comment by DelazJ** [comment]
Fixed in #2404 and #2405
