### ISSUE TITLE
Put GeoPackage at first place in the menu [FEATURE] [needs-docs]

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2178]
Original commit: https://github.com/qgis/QGIS/commit/516540a2019ca6a11edf97900d055f37bbf6fffc by jachym

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment]
I think that a new section explaining specificities/promoting(?) geopackage in http://docs.qgis.org/testing/en/docs/user_manual/managing_data_source/supported_data.html#vector-data would be very welcome if we want to really give a chance to this first place promotion. We already have some of the other formats there, including shapefiles and PostGIS...

**Comment by havatv** [comment]
The section on GeoPackage has been added (#4736).
