### ISSUE TITLE
[needs-docs][feature] New button for empty the composer table (#5407)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2183]
Original commit: https://github.com/qgis/QGIS/commit/9388717843af9877705d8671b6227fa48146f8ad by nyalldawson

Adds a button to empty a composer table. Useful when you have a table
with a lot of columns and you want only a few.

Also change table  from SingleSelection to MultiSelection and allow to
delete selected rows and move selections up and down.

**Comment by Drewfore** [comment]
Sorry not across the documentation process yet, but on the advice in Tims blog post I wrote the prose for the columns section that would need to be updated.
Prose for columns section modified to capture additional buttons. [Composer attribute table buttons.pdf](https://github.com/qgis/QGIS-Documentation/files/1530745/Composer.attribute.table.buttons.pdf)
[Screen shot of new select attributes dialog](https://user-images.githubusercontent.com/8980482/33602290-01daef9a-da03-11e7-885e-a1836bcf928d.png)

**Comment by DelazJ** [comment]
Thanks @Drewfore much appreciated.

**Comment by Drewfore** [comment]
@DelazJ  just getting up to speed on the documentation guidelines. Apologies I wasn't aware the screenshot need to be using Ubuntu - next time!
