### ISSUE TITLE
[auth][needs-docs][feature] Clear access cache

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2184]
Original commit: https://github.com/qgis/QGIS/commit/821be45c4f86680b9f83d7490267a4ec2d1cda1d by web-flow

[auth][needs-docs][feature] Clear access cache

**Comment by havatv** [comment]
Is this related to *Utilities-> Clear network authentication access cache* and/or *Automatically clear network authentication access cache on SSL errors* in 3.12?
Related to #1820?
