### ISSUE TITLE
[feature] Allow to specify timeout when requesting features

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2192]
Original commit: https://github.com/qgis/QGIS/commit/49de489c09db539968b494f020599ca02ba253dc by m-kuhn

This is potentially interesting for race conditions, but whenever it is specified,
iterators will need to be carefully checked for validity and error handling needs
to be taken care of.

**Comment by nyalldawson** [comment]
API only
