### ISSUE TITLE
[FEATURE] add grid renderer for points displacement. funded by Kartoza

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2195]
Original commit: https://github.com/qgis/QGIS/commit/ff2ade9843ac80777fb749fa9b81dc519e570133 by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by SrNetoChan** [comment]
![image](https://user-images.githubusercontent.com/3607161/32233955-8e316ef4-be53-11e7-8906-4efac137f145.png)
