### ISSUE TITLE
[FEATURE]: Fetch geometry and maptip in feature info only if requested by the client

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2205]
Original commit: https://github.com/qgis/QGIS/commit/5bd63b7e1789a72c2692d8d61fab267ec2258eb5 by mhugent

Unfortunately this naughty coder did not write a description... :-(

**Comment by ghtmtt** [comment]
isn't this fixed by @elpaso #2424?

**Comment by DelazJ** [comment]
Indeed. Already documented
