### ISSUE TITLE
[FEATURE] Snapping feedback improvements

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2209]
Original commit: https://github.com/qgis/QGIS/commit/568b22d53fcde729eea5cdaeb5aa6ba9b3297c40 by wonder-sk

- tooltips with name of the layer that has been snapped
- different markers for different snap types (cross for vertex, X for intersection, box for edge)
- snapping marker color can be customized in options (default: magenta - as before)
- whether to show tooltips can be customized in options (default: off)

**Comment by roya0045** [comment]
@DelazJ This seems integrated already.

**Comment by DelazJ** [comment]
Indeed. Closing...
