### ISSUE TITLE
Add a "default shortcut menu" to Processing algorithm description

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#2215]
I've suggested this in #2123 but I think it deserves its own feature request report and needs a decision now that processing refactoring is going on.
Some of the Processing algorithms have a default menu shortcut, in Vector or Raster menu. It could be nice to add a section (when applicable) in the description to show that shortcut path.
Question is where could we place that?
@ghtmtt @SrNetoChan @yjacolin

**Comment by yjacolin** [comment]
+1 from me. Best place should be close enought to the title (an icon in the title ?  a sentence right away after the title ?).

**Comment by SrNetoChan** [comment]
+1 I also propose that we add links in the Vector/Raster menus descriptions to the corresponding algorithm description in processing providers and algorithms.
