### ISSUE TITLE
Add an icon for Processing algorithm

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#2216]
Some of the Processing algorithms have kept their initial icon from GDALTools or fTools period. 
Do we show these icons in algorithms' help?
Note that this could be mixed with solving #2215 by adding path like :menuselection:`Vector --> Section -->|icon| alg_name` (this spelling won't work but you get the idea ;) )

**Comment by DelazJ** [comment]
See #2587 that adds the default menu for algs. I'm not sure it's worth going further (for icons).

**Comment by SrNetoChan** [comment]
@DelazJ I guess this may only have impact on the screenshots related to processing, right?

**Comment by havatv** [comment]
It looks nice, but it should not be necessary to include the processing alg icons in the docs (the name should suffice). So I close this issue as very low priority.
