### ISSUE TITLE
[FEATURE] add "title" feature to composer's attribute tables

### ISSUE THREAD

**Issue by ADAMKEPES** [qgis/QGIS-Documentation#2217]
Attribute tables can only show field names, but a table title cannot be added and visualized like on the image i have attached. This is mostly the problem when more tables are used on one composer->pdf document!

![qgis](https://user-images.githubusercontent.com/33433984/32464192-80df62b0-c33f-11e7-8e73-7348ab0c6c4e.jpg)

**Comment by yjacolin** [comment]
Hello,

Thanks for you ticket but this repository is for documentation. You can fill a bug here for a new feature: https://issues.qgis.org/projects/qgis/issues/

Thanks,

Y.
