### ISSUE TITLE
[FEATURE][processing] Package layers algorithm

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2234]
Original commit: https://github.com/qgis/QGIS/commit/a8eee62461db04cc606641b76e42d36886fba2ab by nyalldawson

Allows multiple vector layers to be collected together into a
geopackage database output

Previously all existing methods avilable in QGIS rely on adding
layers one-at-a-time, which is tedious for large numbers of layers.

Sponsored by SMEC

**Comment by ghtmtt** [comment]
fixed by 4af431f
