### ISSUE TITLE
Update installation for Debian stretch

### ISSUE THREAD

**Issue by mvhconsult** [qgis/QGIS-Documentation#2246]
## Description

Installation mentioned older Debian version
http://docs.qgis.org/2.18/en/docs/user_manual/working_with_ogc/server/getting_started.html

Packages are present for Debian 9 (stretch), why not update the documentation to reflect this?
Current code:

$ cat /etc/apt/sources.list.d/debian-gis.list
deb http://qgis.org/debian trusty main
deb-src http://qgis.org/debian trusty main

Change to
$ sudo vi (or vim, or nano) /etc/apt/sources.list.d/debian-gis.list
Add these lines in there
deb http://qgis.org/debian stretch main
deb-src http://qgis.org/debian stretch main

## Checklist
- [x ] I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage.

- [x ] I have added a link to the page concerned by the issue

**Comment by DelazJ** [comment]
> Packages are present for Debian 9 (stretch), why not update the documentation to reflect this?

Afaics, This code is not wrong and may be of use for some users. Do not forget that it is a sample code and as such should be easily usable in different environment. Are vi, vim, nano in default installation (do not forget beginners )?
I'm not sure it would worth the effort (anybody should be able to reuse/adapt the code to his os) and if it's possible in trusty, it might be in xenial, stretch or.... 
If there were things to change here (and it relates to your #2245 report) it'd be to minimize/reduce these installation instructions and link the QGIS website installation page http://qgis.org/en/site/forusers/alldownloads.html#linux (then we have a single place to update and which offers more instructions for different distributions)

**Comment by mvhconsult** [comment]
I do fully agree this should be simple starter code.

- So why use cat (which lists the code, not adds code)?
- Why not point people to current distributions, but to older ones? I think the current stable releases (LTS as you wish) should be suggested, reducing need to upgrade soon. Squeeze is out, sorry (LTS stopped at Feb 2016...)

For your reference: I tried to follow these simple steps and ran into trouble nearly immediately. The 'lesson' page is much more elaborate.
