### ISSUE TITLE
[needs-docs] Add "delete layout" action to layout designer menu

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2251]
Original commit: https://github.com/qgis/QGIS/commit/b6dab6ff48bc6a0e40d3ca79e0d44fabde9df9bd by nyalldawson

Fixes #10436

**Comment by pedlino** [comment]
Help to help! I would like to contribute to version 3.0
Where do I start to document this feature?

**Comment by DelazJ** [comment]
@pedlino thanks for offering your help. it could be added in this chapter https://docs.qgis.org/testing/en/docs/user_manual/print_composer/overview_composer.html#menus-tools-and-panels-of-the-print-composer (and source file is available by clicking the "fix me" link at the bottom of the page).
If you need more information, just ask

**Comment by DelazJ** [comment]
@pedlino did this answer help you? (maybe i should have added that once you get the source file using the fix me link you can replace ˋqgisˋ and ˋmasterˋ by ˋpedlinoˋ and ˋYourBranchNameˋ(?) in the url if you want to work on your own branch)
