### ISSUE TITLE
Refactor the "Add new geopackage" and "Add new SpatiaLite" dialogs

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#2254]
The dialogs have been updated https://github.com/qgis/QGIS/pull/5824 and https://github.com/qgis/QGIS/pull/5682
Placeholder: https://docs.qgis.org/testing/en/docs/user_manual/managing_data_source/create_layers.html#creating-new-vector-layers

**Comment by shakasom** [comment]
Hi. New here and would like to help. I have gone through the documentation and all documentations are from Linux based distributions. Can it be accepted with Windows as well

**Comment by DelazJ** [comment]
> Hi. New here and would like to help 

Hi @shakasom welcome and thanks for offering your help
Only screenshots (not all btw) are Linux based. QGIS is the same across the OSes so documentation should be the same... unless i misunderstand you

**Comment by shakasom** [comment]
Thanks. @DelazJ
