### ISSUE TITLE
Missing vs done Processing tests list on website 

### ISSUE THREAD

**Issue by ghtmtt** [qgis/QGIS-Documentation#2261]
## Description

An issue has been already opened in the QGIS-Website repository (https://github.com/qgis/QGIS-Website/issues/487) but maybe cross-posting also here could be a good idea.

Me and @m-kuhn have an idea on how to enhance the *visual* status of the Processing Test framework.

Currently a willing person that wants to add more Processing tests have to check *manually* the `yaml` file and look for missing tests. 

The idea we had is to use a script like the following one that will check all the QGIS Processing algorithms and compares that list with the algorithms with test:

https://gist.github.com/ghtmtt/1c3cada5d079e22fff29509627c46c76

What we image is a workflow like:

- running the script in travis
- travis pushes a whatever text file (json, rst, yaml) of done vs missing tests to a directory on the qgis server
- the qgis-documentation has some javascript to load this file and display it in a nice styled way

For the visual part what  about having a list with green tick (done), red cross (missing) and - potentially - yellow dot (partially done) according to the parameter suggestion?

With a lists (for each provider!?) like these it'd super easy also to make some fancy statistics ;)
 
I can handle the script part, @m-kuhn the Travis one? what about the fancy javascript (that looks like a monster for me ;) )? Some js guru volunteer?

We will be happy to hear some feedbacks and maybe start a discussion.

Thanks

**Comment by DelazJ** [comment]
@ghtmtt Not sure what the status of this proposal is but do you think it's worth keeping a duplicate issue report? In the repo cleanup process, It would be nice to keep only issues that belong to docs.

**Comment by ghtmtt** [comment]
unfortunately this proposal was never taken into account. I can try to resurrect it but for the moment I think we can go on and close it.

Thanks for the cleaning @DelazJ
