### ISSUE TITLE
layers / shapefiles misalignment after export to jpg or pdf

### ISSUE THREAD

**Issue by sinasio** [qgis/QGIS-Documentation#2263]
I have polygon and points layers (shapefiles) wich are on the right location in print composer but when you export it to jpg or pdf all the layers are misaligned and do not appear to be in its proper location.

A.) First photo shows polygon and point layers are in the right position/location 
![printcomposer_layers are in correct location](https://user-images.githubusercontent.com/34472439/33874977-be7add80-df31-11e7-899b-669367bec226.jpg)

B.) Second photo shows layers show misalignment or do not fall on correct locations when exported as jpg or pdf

![misaligned after export](https://user-images.githubusercontent.com/34472439/33875019-ed3c4a6e-df31-11e7-8dce-852b6b3d28d5.jpg)

**Comment by DelazJ** [comment]
@sinasio As mentioned in the issue template, this repository is dedicated to [QGIS documentation](https://docs.qgis.org) issues and not QGIS bugs. You may want to ask help in the qgis-users mailing list (see https://qgis.org/en/site/forusers/support.html#mailing-lists) or do a web search: this looks like and "old" issue related to online data use (but i may be mixing things).
