### ISSUE TITLE
Added search and replace functionality to script editors in Processing

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2266]
Original commit: https://github.com/qgis/QGIS/commit/492fb4a67a216be52d170af196a55af8a4dccacc by web-flow

[FEATURE][processing][needs-docs]Script search

**Comment by havatv** [comment]
I don't think this is worth documenting.  The only change is that a magnifier button is added to the script editor.  I think it is self explaining. I don't think it is a problem that some screenshots of the script editor miss this magnifier button.  I have updated the illustrations in the R intro part of the training manual in  #4380 and #4382.  That should be enough for now.
