### ISSUE TITLE
[FEATURE][needs-docs] Add OGC filters to WMS

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2271]
Original commit: https://github.com/qgis/QGIS/commit/b8f708ff1b110bb3c9d9fb96c17d2bacb81708f6 by pvalsecc

Implement https://github.com/qgis/QGIS-Enhancement-Proposals/issues/104

**Comment by DelazJ** [comment]
@pblottiere Sorry to bother you... If I correctly understand this QEP and feature, is it like adding this type of [WFS Filter](https://docs.qgis.org/3.28/en/docs/server_manual/services/wfs.html#filter) to WMS? In which case how does it play with current [WMS Filter](https://docs.qgis.org/3.28/en/docs/server_manual/services/wms.html#filter)? There would be two ways to filter wms get.. (map?)?
