### ISSUE TITLE
[FEATURE][processing][needs-docs] add find and replace functionality to
Processing script editor (forward-port from 2.18 branch)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2273]
Original commit: https://github.com/qgis/QGIS/commit/5016c21ed3046d049d614ccba6aabaa2a85802bb by alexbruy

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment]
Related to #2266
