### ISSUE TITLE
Update list in QGIS Features page

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#2286]
## Description

The [Features chapter](https://docs.qgis.org/testing/en/docs/user_manual/preamble/features.html) may need some updates with all the new features QGIS got (3D (done in #3290), qgz format, Processing as Core (and maybe cleanup the list of plugins), anything else you remember and is worth listing here...  )

## Checklist
> This is the issue/bug trackers for [QGIS Documentation](https://docs.qgis.org).
Cleaning the queue is a process done by project maintainers, mostly on a volunteer basis.
We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items.

- [x] I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage.
If it's related to QGIS application or website, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html
for the right issue tracker or to the [support channels](http://qgis.org/en/site/forusers/support.html)
- [x] I have added a link to the page concerned by the issue

**Comment by havatv** [comment]
3D mentioned in #3290.
