### ISSUE TITLE
Hi Why does not some files open in QGIS while it opens in other software?!

### ISSUE THREAD

**Issue by hamidreza2020** [qgis/QGIS-Documentation#2290]
## Description

Include sentences with details describing the issue you have encountered (e.g., actual behavior, expected behavior, steps to reproduce).

## Checklist
> This is the issue/bug trackers for [QGIS Documentation](https://docs.qgis.org).
Cleaning the queue is a process done by project maintainers, mostly on a volunteer basis.
We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items.

- [ ] I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage.
If it's related to QGIS application or website, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html
for the right issue tracker or to the [support channels](http://qgis.org/en/site/forusers/support.html)
- [ ] I have added a link to the page concerned by the issue

**Comment by DelazJ** [comment]
@hamidreza2020 hard to answer this question without any details on the format or what you are trying. 
Anyway, as stated in the checklist section of your message, this repository is for issues related to QGIS-Documentation, ie anything in https://docs.qgis.org. 
For help or question, contact the user mailing list or other support channels mentioned at https://qgis.org/en/site/forusers/support.html. 
Thanks. I'm closing the ticket.
