### ISSUE TITLE
[FEATURE] Reporting framework

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2309]
Original commit: https://github.com/qgis/QGIS/commit/1ea5a5fb9816b0586d9af2e66a1c672de8f67994 by nyalldawson

Reports are based on the new layouts engine. They consist of multiple
nested sections. Each individual section (and the report itself)
can have an optional header and footer (which are themselves layouts,
and can consist of multiple pages!).

Two different types of sections are implemented so far:
- a standard section, which has a single, static body layout. This
can be used to embed static layouts mid way through a report
- a "field group" section, which repeats its body layout for
every feature in a layer. The features are sorted by the selected
grouping feature (with an option for ascending/descending sort).
If a field group section has child sections (e.g. another field
group section with a different field, then only features
with unique values for the group feature are iterated over.
This allows nested reports, e.g.

Report
- Country: Australia
    - State: NSW
        - Town: Sydney
        - Town: Woolongong
    - State: QLD
        - Town: Beerburrum
        - Town: Brisbane
        - Town: Emerald
- Country: NZ
    - State: ... etc

In this example country, state or town groups can have their
own headers and footers which will be inserted in the report.

Reports are configured through a new panel in the layout designer
dialog, which is shown when editing a report (created through
the Layout Manager Dialog). The organizer allows for adding
(and removing) sections to the report, and for selecting which
layout (e.g. headers, footers, bodies) to edit within the
layout designer.

**Comment by rduivenvoorde** [comment]
Usefull as input for docs: 

https://north-road.com/2018/01/23/exploring-reports-in-qgis-3-0-the-ultimate-guide/ 

@nyalldawson ok to use that (or image from it)?

**Comment by nyalldawson** [comment]
@rduivenvoorde 

Sure, take whatever you need!
