### ISSUE TITLE
[FEATURE] "Duplicate feature redigitized" in MapLayerActions

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2312]
Original commit: https://github.com/qgis/QGIS/commit/9e704ebceb06835e2c28db91e17b45ad296bd207 by web-flow

[FEATURE]  "Duplicate feature redigitized" in MapLayerActions

**Comment by ghtmtt** [comment]
I cannot find other places than https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/vector_properties.html#actions-properties to describe this feature. 

We are not describing *each* default action that is created by QGIS. Should we describe this default action as an example together with the other(s)? 

Opinions?

**Comment by ghtmtt** [comment]
Closing this issue. because screenshots are already updated and I don't see any reason to document only this action and not all the others.

Reopen if necessary
