### ISSUE TITLE
[needs-docs] Rename some processing input types in modeler for clarity

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2316]
Original commit: https://github.com/qgis/QGIS/commit/5a7da0906014589776ec7c1a49ad02495a7c082a by nyalldawson

Refs #17671

**Comment by havatv** [comment]
PARAMETER_VECTOR changed from 'Feature Source' to 'Vector Features'
PARAMETER_TABLE_FIELD changed from 'Layer Field' to 'Vector Field'

**Comment by havatv** [comment]
I can't find any use of 'Feature Source' or 'Layer Field' in the user guide or training manual. Where does this need to be fixed?

**Comment by havatv** [comment]
User manual:
The QGIS Processing Framework chapter has some screenshots that could be updated. I found:
"Fig. 21.2: Processing Modeler" and "Fig. 21.18: Modeler"
There is also some text that could need an update, for instance in "21.5.1 Definition of inputs"
