### ISSUE TITLE
[needs-docs][processing] Add tooltips to input types in modeler

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2317]
Original commit: https://github.com/qgis/QGIS/commit/5da28ed9f0480525d1549feeddd9a94c7ef55c4a by nyalldawson

...to help clarify for users what the different input types mean.

Fixes #17671, which is a result of unclear distinction between
the uses of vector features vs vector layer inputs.

Tagged as needs-docs, as it may help with documentation for 3.0

**Comment by havatv** [comment]
Do we document tooltips?

**Comment by DelazJ** [comment]
Tooltips are just kind of gui labels; they don't need to be specially "documented" unless we write about the tool. And giving a look to the tooltips in this particular case, I'm not sure of the situation we'd need to reuse them in docs. just my 2 cts.

**Comment by havatv** [comment]
I close this one.  If this is a real issue, please reopen with pointers to where updates need to be done.
