### ISSUE TITLE
[processing][needs-docs] Drop Fixed Distance Buffer algorithm

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2318]
Original commit: https://github.com/qgis/QGIS/commit/95db682acf4110e0cc0cdfbff80248a2f73a2f78 by nyalldawson

Since it's functionality is a subset of the native c++ "buffer"
algorithm, it's no longer required.

**Comment by DelazJ** [comment]
fixed in #2255
