### ISSUE TITLE
Unclear part in "Map Rendering and Printing"

### ISSUE THREAD

**Issue by JakobMiksch** [qgis/QGIS-Documentation#2323]
## Description

In the docs for 2.18 ["Map Rendering and Printing" Section "Simple Rendering"](https://docs.qgis.org/2.18/en/docs/pyqgis_developer_cookbook/composer.html#id1) is an unclear part:

```
# set layer set
lst = [layer.getLayerID()]  # add ID of every layer
render.setLayerSet(lst)
```

Does `layer` refer to one specific layer or to the list of all available layers?
Which class does `layer` belong to? 

When I use a `QgsVectorLayer` as `layer` (like in the examples before), I get this output:

```
type(layer)
<class 'qgis._core.QgsVectorLayer'>
layer.getLayerID()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: 'QgsVectorLayer' object has no attribute 'getLayerID'
```

## Checklist
> This is the issue/bug trackers for [QGIS Documentation](https://docs.qgis.org).
Cleaning the queue is a process done by project maintainers, mostly on a volunteer basis.
We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items.

- [x] I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage.
If it's related to QGIS application or website, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html
for the right issue tracker or to the [support channels](http://qgis.org/en/site/forusers/support.html)
- [x] I have added a link to the page concerned by the issue

**Comment by yjacolin** [comment]
What are the release number of your QGIS?

**Comment by yjacolin** [comment]
The previous example explain that we can use isValid() method which is not documented in the API. Same issue for getLayerID.

**Comment by havatv** [comment]
I will close this issue.
Reason: The code in the documentation has been completely changed, both for QGIS 2 (since 2.8) and for QGIS 3.
getLayerID is from QGIS 1 (gone in QGIS 2).
