### ISSUE TITLE
[needs-docs][processing] move providers actions into the processing 

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2327]
Original commit: https://github.com/qgis/QGIS/commit/c5d9830db2e8bcc9d60bdc1451e3cd318edc9fd5 by web-flow

panel toolbar (#6150)

**Comment by havatv** [comment]
I can't find a place to update the documentation to address this.  I have no problems with reopening this, but please provide pointers to the places where updates are needed.

**Comment by ghtmtt** [comment]
fully agreed with @havatv here. In the screenshot of the documentation we already have updated screenshots (see https://docs.qgis.org/testing/en/docs/user_manual/processing/intro.html or here https://docs.qgis.org/testing/en/docs/user_manual/processing/intro.html) where the actions of the additional providers are shown in the Processing toolbar. 

Closing this, but feel free to reopen if necessary.
