### ISSUE TITLE
[processing][needs-docs] remove Get scripts and models functionality

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2335]
Original commit: https://github.com/qgis/QGIS/commit/6841c52210a66ddca7f5f4c31bd9583f9f95d8dd by web-flow

[processing][needs-docs] remove Get scripts and models functionality

**Comment by havatv** [comment]
It would be nice if someone could point to where this is described in the documentation.  I have not found it, except for R scripts, where I have updated the documentation of the online collection of R scripts (#4369).
