### ISSUE TITLE
[processing][needs-docs] use native syntax for Processing scripts

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2336]
Original commit: https://github.com/qgis/QGIS/commit/b6c2de48fa363d0cd9d39a1d54cdc5b9d5160f25 by web-flow

[processing][needs-docs] use native syntax for Processing scripts

**Comment by havatv** [comment]
It would help with some more explanation.

**Comment by havatv** [comment]
This has been fixed for both 3.4 and master.
