### ISSUE TITLE
[needs-docs] Use correct open form icon in identify results toolbar

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2341]
Original commit: https://github.com/qgis/QGIS/commit/147903125d6b8334de1b4f131296ce9ac8fcc94e by nyalldawson

Before we used a different (non obvious) icon for "open form"
in the toolbar. This changes the toolbar icon to reuse the
same (clearer) icon which is used when expanding out the
tree and finding the "show feature form" action.

I've also moved the Open Form action to be first in the
toolbar, since it's the most frequently used action.

**Comment by nyalldawson** [comment]
This only needs docs if there's screenshots involved - maybe it can be closed

**Comment by DelazJ** [comment]
it's ok: there's a screenshot and the action itself is mentioned so need a fix.
