### ISSUE TITLE
[needs-docs][ui] harmonize title of panels

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2347]
Original commit: https://github.com/qgis/QGIS/commit/8697c7999375e07d00d0c7a53d51c3f03d21d5b1 by nirvn

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment]
May have consequences for some illustrations containing user interface screen shots.

**Comment by havatv** [comment]
In 3.4.4, the title of the processing toolbox is "Processing Toolbox", and not "Processing Toolbox Panel".  Should milestone be changed, or the issue be closed?

**Comment by DelazJ** [comment]
@havatv any link, please? hard to find what's 3.4.4 (in the pdf?).
Anyway, I think this PR has been reverted given that afaics, no panel shows "panel" in its title. Hence can be closed.

**Comment by havatv** [comment]
If it has been reverted we should close the issue.  My point was that if all these panels have changed names, then there are probably some screenshots of these panels with the "old" names.  I have not looked for them.

**Comment by DelazJ** [comment]
I'm not sure it's worth spending time on looking for them (there should be few cases). Let's just fix them when we (accidentally) find them or while fixing another issue on the screenshot. And close this report, meanwhile.
