### ISSUE TITLE
Move Processing Interpolation example to the Traning Manual

### ISSUE THREAD

**Issue by ghtmtt** [qgis/QGIS-Documentation#2351]
## Description

Move Processing Interpolation example to the Traning Manual.

## Checklist
> This is the issue/bug trackers for [QGIS Documentation](https://docs.qgis.org).
Cleaning the queue is a process done by project maintainers, mostly on a volunteer basis.
We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items.

- [x] I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage.
If it's related to QGIS application or website, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html
for the right issue tracker or to the [support channels](http://qgis.org/en/site/forusers/support.html)
- [x] I have added a link to the page concerned by the issue

**Comment by havatv** [comment]
I can't find any interpolation examples to move. Closing.
Reopen with more information about what to move if this is still an issue.
