### ISSUE TITLE
[needs-docs] Remove " Panel" suffixes from panel titles

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2359]
Original commit: https://github.com/qgis/QGIS/commit/5f664944461d200f7b924e60f19fb252d6e0b232 by nyalldawson

This extra text adds a lot of visual clutter to the interface,
and makes tabbed dock's tab bars take up a lot of room.

Instead only show the "panel" suffix in the menus.

**Comment by DelazJ** [comment]
Fixed as it's a removal of a (not reported) change that was neither documented.
