### ISSUE TITLE
add button to refresh a materialized view in browser [needs-docs]

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2368]
Original commit: https://github.com/qgis/QGIS/commit/8e38788d64f1e158f8cfdcd1c5cc87327da61d37 by Gustry

Unfortunately this naughty coder did not write a description... :-(

**Comment by Gustry** [comment]
The tag must be 3.2 and not 3.0 (and all new commits created this morning in the repo)

**Comment by Gustry** [comment]
I'm just adding my screenshot:
<img width="367" alt="screen shot 2018-02-17 at 15 06 27" src="https://user-images.githubusercontent.com/1609292/36340782-a608e736-13f4-11e8-875c-4e5ed8518055.png">

If it can help doc writers
