### ISSUE TITLE
Help links do not work

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#2382]
A link like https://docs.qgis.org/3.0/en/docs/user_manual/index.html (opened from the Help menu of QGIS 3.0) should bring https://docs.qgis.org/testing/en/docs/user_manual/index.html instead of a 404 not found page.

**Comment by rduivenvoorde** [comment]
Oops, sorry sorry. Forgot.
I know redirect 3.0 to testing, that is ok isn't it?

0nly 2.99 was pointing to testing

**Comment by DelazJ** [comment]
> I know redirect 3.0 to testing, that is ok isn't it?

Yes, it should fix it (I do not have currently a working 3.0). Thanks.
And btw, do you have any idea for #2385
