### ISSUE TITLE
Please document the QGIS 3D config options

### ISSUE THREAD

**Issue by palmerj** [qgis/QGIS-Documentation#2384]
## Description

Please document the meaning of max tile resolution, max screen error, and max ground error in QGIS 3D config. This parameters are hard to understand why and why you should use them. The documentation should explain this.

## Checklist
- [x] I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage.
- [ ] I have added a link to the page concerned by the issue

**Comment by DelazJ** [comment]
Hi @palmerj 
It'b de nice but given the few hands currently available to write documentation (despite all the calls), i'm afraid it could take some time before this chapter and nice feature lands in doc (every one use to write on areas he knows better) unless some 3D expert gives a hand/some non-3D user gives a hand elsewhere (to clean the issues queue).
Meanwhile better ask for tooltips in the application (see https://issues.qgis.org/issues/17629 from a 3D non expert).
Regards.

**Comment by DelazJ** [comment]
@palmerj, i came across reading https://www.lutraconsulting.co.uk/blog/2018/03/01/working-with-qgis-3d-part-1/ (could be helpful if you did not find it yet)

**Comment by palmerj** [comment]
Wow this page looks great. Can we just port that into the 3.0 docs?

**Comment by DelazJ** [comment]
> Wow this page looks great. Can we just port that into the 3.0 docs?

Would require @saberraz and/or @wonder-sk agreement

**Comment by DelazJ** [comment]
@saberraz @wonder-sk may I reiterate the request of picking part of your article (text, images...) for the docs? Thanks

**Comment by saberraz** [comment]
@DelazJ for sure...feel free to use the content (text, image, etc) from the the blog post for the documentation. The aim of the blog posts of new features are to provide the details of the new features to the community.
