### ISSUE TITLE
[needs-docs] Add Alt+{no} shortcut for panels (#5895)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2385]
Original commit: https://github.com/qgis/QGIS/commit/22d19c9b9926cd2cbdb8cdf76c791117e6dee2b3 by web-flow

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment]
Hi @rduivenvoorde any idea why it's milestoned 3.0 instead of 3.2?

**Comment by rduivenvoorde** [comment]
Mmm, probably because you updated the code, but I did not update the code that is running on the server. Will have a look.

**Comment by DelazJ** [comment]
Ok, thanks again.

**Comment by rduivenvoorde** [comment]
Ok, should work now...I took the new version from github, added the password to it etc

Plz close when we know it is working.

**Comment by DelazJ** [comment]
works like a charm, @rduivenvoorde 
Maybe should we delete this discussion for a cleaner issue report page?
