### ISSUE TITLE
[FEATURE] Indicators for layer tree view + filter indicator implementation

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2390]
Original commit: https://github.com/qgis/QGIS/commit/f56d70f3f83d39b97b29521fe9071afa0aa08cac by wonder-sk

This adds a mini-framework for display of extra icons in layer tree views
next to layer and group names. Tool tip text can be associated with indicators
to give extra context for indicators. In addition, a signal gets emitted
when user clicks indicators and custom actions can be defined.

The main window's layer tree view (ToC) gets support for indicators
that are shown when a vector layer has a filter applied. This makes it easier
for users to understand that they are looking at a subset of all data.
Clicking the indicator's icon brings up query builder.

**Comment by DelazJ** [comment]
From a user point of view i can see a filter icon next to layer name when it's filtered. Is there anything else in this commit that should be mentioned (like some other icons that would appear in other circumstances, eg using a layer action)? Or can a user customize this (in Gui or programmatically) ? The PR mentioned some future use case but i guess it's not yet implemented. Right?
@wonder-sk?

**Comment by Gustry** [comment]
AFAIK, only this filter icon is available for now. But the API is available for other icons to come later.

**Comment by DelazJ** [comment]
Ok thanks you both confirm what I understood. Pull-request done.
