### ISSUE TITLE
[FEATURE][processing] add discard non matching option to join attribute table alg

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2398]
Original commit: https://github.com/qgis/QGIS/commit/1542b484bec3ac639695c9ebedcaf5732395bdc8 by nirvn

Unfortunately this naughty coder did not write a description... :-(

**Comment by ghtmtt** [comment]
isn't this fixed bt #2552?

**Comment by DelazJ** [comment]
closed now!
