### ISSUE TITLE
Node Tool need to be renamed to Vertex Tool in Training Manual

### ISSUE THREAD

**Issue by skorasaurus** [qgis/QGIS-Documentation#2400]
Hi all, 

The training manual needs its references of the Node Tool changed to the Vertex Tool. 

The node tool was renamed to the Vertex Tool (see https://github.com/qgis/QGIS-Documentation/pull/2348#issuecomment-366599591 and https://github.com/qgis/QGIS/pull/6140) 
These changes were merged into the user guide in the above PRs. (Note that these changes have been merged into master but don't appear yet in https://docs.qgis.org/testing/en/docs/user_manual/index.html) 

There are several pages in the Training Manual where this text needs to change including [topo editing](https://github.com/qgis/QGIS-Documentation/blob/18abf253b12c6a5e0e424cc0d55480169f5d53e1/source/docs/training_manual/create_vector_data/topo_editing.rst) and [creating new vectors](https://github.com/qgis/QGIS-Documentation/blob/b610e27780848b929ff740e679b3409e57e043df/source/docs/training_manual/create_vector_data/create_new_vector.rst). There may be additional places in the training manual (like this [translation file](https://github.com/qgis/QGIS-Documentation/blob/42b0c2370eb6f050eb382a9d715d23c55f3dae3c/i18n/en/LC_MESSAGES/docs/training_manual/create_vector_data/topo_editing.po) (I'm not sure if that file needs to be opened too).

## Checklist
> This is the issue/bug trackers for [QGIS Documentation](https://docs.qgis.org).
Cleaning the queue is a process done by project maintainers, mostly on a volunteer basis.
We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items.

- [X] I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage.
If it's related to QGIS application or website, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html
for the right issue tracker or to the [support channels](http://qgis.org/en/site/forusers/support.html)
- [X ] I have added a link to the page concerned by the issue

**Comment by DelazJ** [comment]
Good catch @skorasaurus and it's not only about renaming, description may need tweaks to match the click-click behavior
Btw there are still some occurrences in the User Manual

**Comment by DelazJ** [comment]
Changes are available at https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/editing_geometry_attributes.html#vertex-tool (section was too low-level to get shown in the table of content of the docs). 

No worries for translation files; they are [handled elsewhere](https://www.qgis.org/en/site/getinvolved/translate.html) and testing (3.0) is not translated. So it should be good.
