### ISSUE TITLE
[needs-docs] Add welcome screen action to project menu

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2401]
Original commit: https://github.com/qgis/QGIS/commit/0e80b72d0c0e68a5b660ec34ce11b0903f80c353 by NathanW2

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment]
I can't find this in the project menu in 3.4.4.

**Comment by DelazJ** [comment]
Me neither. I wonder if this is not more of an initial step to implement https://github.com/qgis/QGIS-Enhancement-Proposals/issues/102... Don't really know. @NathanW2 can give more details.

**Comment by ghtmtt** [comment]
I cannot see the action in the menu either. @NathanW2 should it be available in the `Project` menu?

**Comment by anitagraser** [comment]
There is no mActionWelcomePage in current  https://github.com/qgis/QGIS/blob/5c6c63d0e77d0fa32fd66cbb6c405c07aa4cca9f/src/ui/qgisapp.ui anymore. I think this ticket is obsolete.
