### ISSUE TITLE
Add more relation between algorithms help

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#2419]
It could be nice to have a more intensive use of the "See Also" section of alg description and link them. 
For example, a minima, when alg A is listed in alg B see also, the inverse should be true. Which is not the case currently. But there might also be missing links.

**Comment by ghtmtt** [comment]
@DelazJ is this issue still valid? If yes, maybe we can remove the `3.0` label because it is related also to different releases

**Comment by DelazJ** [comment]
#2412 mentions this in the guidelines and we have added these links over the years. It does not need an issue report anymore. Closing
