### ISSUE TITLE
[FEATURE][processing] Add line sinuosity to "Export Geometry Info"

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2425]
Original commit: https://github.com/qgis/QGIS/commit/251e1d53523a88ef556f0fbd27d8517c5bf08e7f by nyalldawson

Adds line sinuosity and straight distance to the stats calculated
by "Export Geometry Info"

Fixes #12376

**Comment by DelazJ** [comment]
@nyalldawson, looks like these information are added only for some types of provider/datatypes...
I have a PG linestring which only returns length, even when I draw circle or arc geometries in the layer. works pretty well with a memory linestring layer.

**Comment by nyalldawson** [comment]
@delazj maybe it's MultiLineString geometries?

**Comment by DelazJ** [comment]
Indeed, it was a MultiLineString PG (though with single geometries) and MultiLineString neither adds these info for a memory layer. So I guess they only show for LineString and CompoundCurve geometries... Right?

**Comment by nyalldawson** [comment]
Correct. Because otherwise you can't store them in a single field - there's a different value for each part

**Comment by DelazJ** [comment]
Yes, I see. Btw It doesn't work with shapefile as they are now by default promoted to multi.
PR at #2693
