### ISSUE TITLE
[needs-docs] Don't mark a project as dirty when only the canvas extent
changes

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2428]
Original commit: https://github.com/qgis/QGIS/commit/773ec220ba8c81784f69bef2911bc9cf9e788f7a by nyalldawson

Since this is a view operation, not an edit operation, we don't
mark it as changing the project state. (Much like how loading a
doc in a word processor and scrolling to the last page isn't
changing the document state).

**Comment by nyalldawson** [comment]
On second thoughts not sure why I tagged this as needs docs
