### ISSUE TITLE
[FEATURE][needs-docs] Save/Load connections for Tiles XYZ

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2451]
Original commit: https://github.com/qgis/QGIS/commit/504e50df5eac01391f41a4873ba43a9b5f494c77 by slarosa

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment]
xyztiles does not seem to be documented yet (at least not in the user manual).
https://www.spatialbias.com/2018/02/qgis-3.0-xyz-tile-layers/

Related to #2089, #1998, #1719, #1397.
