### ISSUE TITLE
Broken links in training manual (no data available for download)

### ISSUE THREAD

**Issue by ghtmtt** [qgis/QGIS-Documentation#2456]
## Description
Missing data (dropbox link) here: https://docs.qgis.org/testing/en/docs/training_manual/complete_analysis/analysis_exercise.html#solution-outline

Somebody knows how we should ping?

## Checklist
> This is the issue/bug trackers for [QGIS Documentation](https://docs.qgis.org).
Cleaning the queue is a process done by project maintainers, mostly on a volunteer basis.
We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items.

- [x] I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage.
If it's related to QGIS application or website, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html
for the right issue tracker or to the [support channels](http://qgis.org/en/site/forusers/support.html)
- [x] I have added a link to the page concerned by the issue

**Comment by DelazJ** [comment]
> Somebody knows how we should ping?

git blame led to this [pull-request of mine](https://github.com/qgis/QGIS-Documentation/pull/1694) fed by https://github.com/qgis/QGIS-Website/issues/216#issuecomment-190325471 so I'd say @timlinux 
I realize that there was meanwhile new comment that this dropbox data did not contain all needed files...

**Comment by ghtmtt** [comment]
thanks for the update @DelazJ

**Comment by havatv** [comment]
I have sent an email to S. Motala.

**Comment by havatv** [comment]
The dropbox reference has been removed in master and 3.10. Closing.
