### ISSUE TITLE
Section 9.4.2: more_analysis folder not available in exercise_data

### ISSUE THREAD

**Issue by brylie** [qgis/QGIS-Documentation#246]
In section 9.4.2, the reader is instructed to refer to the more_analysis directory (exercise_data/more_analysis). I cannot find this directory, and have downloaded the exercise data from the following location:
http://qgis.org/downloads/data/training_manual_exercise_data.zip

**Comment by w1malik** [comment]
This is wonderful to share the data but still admin boundary Western_Cape_UTM33S.shp file does not contain the boundary of districts mentioned in section 9.4.8 there is only one entry that is availble against Name_2 field that is Bellville.

**Comment by henkth** [comment]
It would be great if the license issues could be resolved. Otherwise it would be a wonderful idea if exercise 9.4 could be rewritten with other data, to provide a thorough learning experience.

**Comment by Andre-J** [comment]
Unfortunately, the issue of https://github.com/qgis/QGIS-Documentation/issues/246?_pjax=%23js-repo-pjax-container#issuecomment-71265056 is still unsolved. The file  admin_boundaries/Western_Cape_33S.dbf is missing. Hence the attribute table is empty.
