### ISSUE TITLE
[FEATURE][layouts] Export project metadata as SVG RDF metadata

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2464]
Original commit: https://github.com/qgis/QGIS/commit/a600b51badf72e67712cd621a4f6f6df297cd1fb by nyalldawson

Adds an option to include project metadata into SVG exports
generated from layouts, using the SVG RDF standard.

Developed for Arpa Piemonte (Dipartimento Tematico Geologia e Dissesto)
within ERIKUS project

**Comment by havatv** [comment]
Is there a need for more documentation?

**Comment by DelazJ** [comment]
The screenshot was not updated (I was stuck on Windows at that time)
