### ISSUE TITLE
[FEATURE][layouts] Export project metadata in PDF/image exports

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2465]
Original commit: https://github.com/qgis/QGIS/commit/2eacc4c4b41d1740f45349f6fcbab5f34f261588 by nyalldawson

Includes project metadata in PDF exports, and supported image
based formats.

Image based metadata support depends on the format and the
Qt library's handling of each particular format (e.g. PNG
outputs are well supported).

Developed for Arpa Piemonte (Dipartimento Tematico Geologia e Dissesto)
within ERIKUS project

**Comment by havatv** [comment]
Could perhaps be mentioned, but where (project -> export as)?

**Comment by DelazJ** [comment]
This is at least in the dialog that opens when exporting a [layout to pdf](https://docs.qgis.org/testing/en/docs/user_manual/print_composer/create_output.html) (can't tell which are the supported image formats mentioned in the report)
