### ISSUE TITLE
Cellsize.... Interpolation IDW and TIN (QGIS 3.0)

### ISSUE THREAD

**Issue by alepr** [qgis/QGIS-Documentation#2466]
I suggest put the option of cellsize in the interpolation module (IDW and TIN)

**Comment by DelazJ** [comment]
Hi @alepr,
Is this:
* a feature request for the application ? in which case,  the place to report is instead https://issues.qgis.org
* or a missing information in the docs? In which case, you are at the right place but we would need you to point to the docs page where the information should be added. 

Thanks

**Comment by DelazJ** [comment]
Looks like a report is created at https://issues.qgis.org/issues/18556 so i'm closing this one
