### ISSUE TITLE
10.2.1: Raster Terrain Analysis Plugin - move to earlier in book

### ISSUE THREAD

**Issue by brylie** [qgis/QGIS-Documentation#247]
The chapter detailing plugin installation, specifically the Raster Terrain Analysis Plugin, is out of sequence with the tutorial that uses the Raster Terrain Analysis Plugin (chapter 8.3). It seems reasonable to cover plugins after covering core functionality, as is currently the case. Is there some way to reduce the duplication in the book regarding the Raster Terrain Analysis Plugin?

**Comment by purplexed** [comment]
The plugin is described also in the 10.2 lesson of the training manual. You can find its reference points [https://docs.qgis.org/2.8/en/docs/user_manual/plugins/plugins_raster_terrain.html](url), [https://docs.qgis.org/2.8/en/docs/training_manual/qgis_plugins/plugin_examples.html](url) and [https://docs.qgis.org/2.8/en/docs/training_manual/rasters/terrain_analysis.html](url).

Should we merge everything under the 8.3 lesson?
