### ISSUE TITLE
[needs-docs] Use QgsScaleBarRenderer to power up scale bar decoration (#6689)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2477]
Original commit: https://github.com/qgis/QGIS/commit/5fe1ea85bf41a5318c21f39f31ee6b45a84cf366 by web-flow

Main short-term benefit: scale bar font size and family can be customized.

**Comment by havatv** [comment]
If this is to be documented - where?
In "Laying out the maps"-> "Layout items" -> "The Scale Bar Item", the figure labelled "Scale Bar Item Properties Panel" reflects 3.4.4.
