### ISSUE TITLE
[needs-docs] Use QgsTextRender to power up copyright decoration styling (#6684)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2478]
Original commit: https://github.com/qgis/QGIS/commit/93a6115c9e20d08aad22fd9438d2c2fae9364acb by web-flow

- we gain all of the styling capabilities of our text renderer engine (i.e. what powers
the rendering of labels)
- HTML support is gone for now, with virtually all of styling possibilities
covered by the above text renderer

**Comment by havatv** [comment]
This seems to be related to view-> decorations-> copyright
