### ISSUE TITLE
[needs-docs] geometry smooth algorithm now also retains and smooths z/m values

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2480]
Original commit: https://github.com/qgis/QGIS/commit/f02602b9bbd80394414eec73f4f5688a52df91a2 by nyalldawson

...instead of just discarding them

Applies to processing algorithm and expression function (and
QgsGeometry::smooth method)

**Comment by nyalldawson** [comment]
API only
