### ISSUE TITLE
State of layer reprojection operations before using Processing algorithms

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#2488]
https://docs.qgis.org/testing/en/docs/user_manual/processing/toolbox.html#a-note-on-projections explains that layers should be reprojected to the same crs before processing any algorithm. 
I remember some discussion (or PR) that mentions that some algs no more needs it.
As I could not find any information on this in the repo i'd like to know if it's really the case. Does it apply to all algs or only some of them (what then makes the difference: alg providers, datasource... )? 
IOW Should we keep this note in the doc, remove it or add some precision ?

Any information is more than welcome.. Thanks
@nyalldawson @alexbruy @ghtmtt... ?

**Comment by nyalldawson** [comment]
It should apply at least to all QGIS native algorithms - if not, that's a bug and needs fixing. 

I'm not sure if it also applies to GDAL, GRASS and SAGA though - I haven't been actively engaged in the ports of those providers.

**Comment by DelazJ** [comment]
Sorry for the late reply. Thanks Nyall for the info. 
> if not, that's a bug and needs fixing.

 I was just looking for information and didn't try this feature so no bug to report. 
> I'm not sure if it also applies to GDAL, GRASS and SAGA though - I haven't been actively engaged in the ports of those providers.

Anyone involved in this area... ?

**Comment by ghtmtt** [comment]
Hi.. sorry too for the late reply. I'm testing some algorithms and I have a small doubt. Suppose you want to perform a simple buffer on one layer in 4326 and the project CRS is set to 32632. There seems no way to tell the buffer (and also other algorithm with distances) to consider the distance of the project CRS, Processing takes automatically the **layer** CRS, right?

**Comment by nyalldawson** [comment]
Yes - it's always layer crs.

**Comment by DelazJ** [comment]
@nyalldawson 
> It should apply at least to all QGIS native algorithms - if not, that's a bug and needs fixing.

And in which CRS the operations are performed: the first input layer, second input layer or project crs? From my test, I'd say the first input layer. Am I right?
> I'm not sure if it also applies to GDAL, GRASS and SAGA though

I made a test with GDAL "clip by mask layer" alg and it does return empty file (where native Clip returns featured one). GDAL "clip vector by extent" alg using the other layer extent however returns the right features.
The weird thing is that although the "warn when different CRS" option is checked in Options, the dialog does not prompt (So seems there's a bug there).

**Comment by nyalldawson** [comment]
@DelazJ should be fixed by https://github.com/qgis/QGIS/pull/6905
