### ISSUE TITLE
[processing][needs-docs] Rename "Add Script from Template" to
"Create New Script from Template"

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2496]
Original commit: https://github.com/qgis/QGIS/commit/ad3f1781d76991cd3beeb9580838ad99671f59ad by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment]
Backported to 3.0 in #2544.
