### ISSUE TITLE
Replace osm downloader instructions with QuickOSM in Training manual

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#2498]
Core OSM downloader has been removed (#2164) and cleared from user manual (#2433). But i's also used in the Training manual in few places.
[Advice](http://osgeo-org.1560.x6.nabble.com/QGIS-Developer-Future-of-OSM-integration-tp5338005p5358269.html) is to replace these instructions by steps with QuickOSM plugin (show the steps in one place and refer to it if required later - to ease update if ever modified).

**Comment by ghtmtt** [comment]
@DelazJ it was not exactly possible to replicate the OSM downloader with the QuickOSM plugin... until now ;) (version 1.7 of QuickOSM). Now it is possible to download **all** the key - values given an extent.

**Comment by DelazJ** [comment]
Should be fixed at least in #3054
