### ISSUE TITLE
[FEATURE] add zoom to related feature in forms

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2499]
Original commit: https://github.com/qgis/QGIS/commit/7d48179223e9e619a70295093425ada2f4279b7b by jef-n

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment]
User manual: Working with vector data-> Working with attribute data-> Creating one or many to many relations?
The zoom to button seems to be there in the current version of the user guide.

**Comment by DelazJ** [comment]
Fixed in #2893
