### ISSUE TITLE
[needs-docs] In merge features dialog, if a layer has default
values/default value clauses present, then use these as the
initial value for the merged feature

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2504]
Original commit: https://github.com/qgis/QGIS/commit/615cb6ca71e14ea45252951f0ca3fe7e95343eb8 by nyalldawson

Otherwise the dialog defaulted to skipping these attributes
or taking a value from an existing feature, which meant
that it could violate constraints on the backend.

Users can still easily overwrite these values if desired.

Fixes #18397

**Comment by DelazJ** [comment]
duplicate #2511
