### ISSUE TITLE
[FEATURE][processing] Add algorithm to swap x/y coordinate values

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2508]
Original commit: https://github.com/qgis/QGIS/commit/8aa9a82d2893e285c08de2a91df5aa12e99ad17b by nyalldawson

This algorithm swaps the X and Y coordinate values in input
geometries. It can be used to repair geometries which have
accidentally had their latitude and longitude values reversed.

**Comment by DelazJ** [comment]
fixed in #2749
