### ISSUE TITLE
[needs-docs] In merge features dialog, if a layer has default
values/default value clauses present, then use these as the
initial value for the merged feature

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2511]
Original commit: https://github.com/qgis/QGIS/commit/368fa9087a6b5c8f16c664541e3191f2fde52e7a by nyalldawson

Otherwise the dialog defaulted to skipping these attributes
or taking a value from an existing feature, which meant
that it could violate constraints on the backend.

Users can still easily overwrite these values if desired.

Fixes #18397

(cherry-picked from 615cb6c)

**Comment by DelazJ** [comment]
fixed in #3140
