### ISSUE TITLE
[FEATURE] Mark layers as required in the project

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2538]
Original commit: https://github.com/qgis/QGIS/commit/42517f8b58bc61498f3cb74bff4e528da27bea27 by wonder-sk

Required layers are not allowed to be removed from the project.
This adds extra safety to protect project users from removing layers
they may think are not needed (e.g. used in joins, relations, expressions).

Users can set/unset layers that are required in project properties dialog.

**Comment by gioman** [comment]
see https://github.com/qgis/QGIS-Documentation/pull/2611
