### ISSUE TITLE
[FEATURE][processing] Add buttons to save/clear/copy log

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2553]
Original commit: https://github.com/qgis/QGIS/commit/4a594d3f32c47059af35ff42b7ba2d81d8212257 by nyalldawson

In the algorithm execution dialog, this adds buttons to allow
users to save the current log (to text or HTML files), copy the
log contents to the clipboard, and clear the log.

**Comment by DelazJ** [comment]
These buttons are in the Log panel of any algorithm dialog and are good to know imho. Also good candidates for tips addressing issues related to log message, or copy-paste and run in console a previous call, (maybe use to build a model?)...
