### ISSUE TITLE
add paragraph about QGIS Server installation on Windows

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS-Documentation#2554]
## Description

A proven to work procedure is
http://level2.si/2018/03/qgis-server-3-0-on-windows-10/

https://docs.qgis.org/testing/en/docs/user_manual/working_with_ogc/server/getting_started.html

## Checklist
> This is the issue/bug trackers for [QGIS Documentation](https://docs.qgis.org).
Cleaning the queue is a process done by project maintainers, mostly on a volunteer basis.
We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items.

- [ ] I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage.
If it's related to QGIS application or website, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html
for the right issue tracker or to the [support channels](http://qgis.org/en/site/forusers/support.html)
- [ ] I have added a link to the page concerned by the issue

**Comment by gioman** [comment]
This ticket can be assigned to me, as I will do it as also https://github.com/qgis/QGIS-Documentation/issues/2547 and many more... so maybe it just better to give me permissions to assign tockets?

**Comment by elpaso** [comment]
I still wonder if (and why) we want to support or recommend QGIS Server on windows. 
And **who** will support it.

**Comment by jef-n** [comment]
@elpaso why do you care less about desktop users? ;)

**Comment by gioman** [comment]
Is not a matter of suggesting use Windows (on servers or desktops), which I don't, or supporting QGIS Server on Windows in way different compared to how it is supported on Linux. QGIS Server is in OSGeo4W and there never was a clear piece of official documentation on how install it. On OSGeo4W 32 bit there is the Apache (with appropriate Apache conf files) so it is kind of a "next, next, finish" installation, but this is only for 2.*  bacause with QGIS3 this does not work anymore. On OSGeo4w 64 bit there never was the Apache package, meaning that it has to be installed and configured manually by other means.

There is also the fact that many have no choice, because the server where they would like use QGIS Server is Windows, or maybe just because they need a way to showcase the technology and they just do Windows on their desktops (an examples about this: Nodebo 2015, workshop on QGIS Server, room with around 25 persons from Danish administrations/companies, not a single one was interested in seeing the workshop based on Linux).

**Comment by gioman** [comment]
See https://github.com/qgis/QGIS-Documentation/pull/2604
