### ISSUE TITLE
[FEATURE][needs-docs] Hyperlink functions to show help in builder (#6796)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2555]
Original commit: https://github.com/qgis/QGIS/commit/b22121ac750717608ce7dec226bb95ba47fdc955 by web-flow

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment]
@NathanW2 I'm unable to get this work (commit aae7a325bd):
* i get the hyperlink indication but clicking on the function does nothing
* the hyperlink appears only after the function parameters are correctly filled: this makes the option a bit useless imho; isn't the help supposed to help me find the right parameters? I'd expect it appear once the spelling matches an existing function...
* is that normal the hyperlink is not triggered when using variables or `$` records?

**Comment by NathanW2** [comment]
Hey, Yeah I'm going to review this for next release. So you can leave it
out of the release notes if you wish. There is a better ways to do what I
have done just don't have time to fix at the moment.

**Comment by DelazJ** [comment]
Too late, already in docs 😄 . I however only pick the minimalist information ( that is `you can shift-click to show help`) and for details, reported feature requests/issues in Redmine regarding my comment above: [19135](https://issues.qgis.org/issues/19135), [19134](https://issues.qgis.org/issues/19134), [19133](https://issues.qgis.org/issues/19133). So it should be OK and thanks for any improvement.
