### ISSUE TITLE
[FEATURE][needs-docs] Don't bail on first expression error (#6838)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2561]
Original commit: https://github.com/qgis/QGIS/commit/76b956a6a3dc178d57ae7ed08335ab46d7795433 by web-flow

Unfortunately this naughty coder did not write a description... :-(

**Comment by gioman** [comment]
Seems very low level.

**Comment by DelazJ** [comment]
See #2573 that documents the next step so I assume closes it.
