### ISSUE TITLE
[FEATURE] QgsMeshLayer part 1: Reading raw mesh

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2570]
Original commit: https://github.com/qgis/QGIS/commit/50422a116516cfb7e05f2e60062eb9d7555592ae by PeterPetrik

Introducting MDAL, QgsMeshLayer, mesh data providers (mesh_memory, mdal)
to read and visualize raw meshes: vertices and faces. Support dragging
2dm files from browser on canvas to visualize 2dm meshes.
Support for QgsMeshLayer in Python API.

**Comment by nyalldawson** [comment]
API only
