### ISSUE TITLE
[FEATURE][ogr/gdal] Add UI to expose HTTP(S) and cloud datasets

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2572]
Original commit: https://github.com/qgis/QGIS/commit/e875e5ed400f69426c1dd32b643a19064ebd0e65 by nirvn

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment]
In the user guide, the following is written about this:
"The last source type, Protocol, enables to open data from the web using for example GeoJSON or CouchDB format. After selecting the type you have to fill URI of the source."
This implies that not all the protocols are listed.  There is also no screenshot to update.
