### ISSUE TITLE
 [FEATURE][needs-docs] Move layer or group to top of layer panel

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#2575]
Source: https://github.com/qgis/QGIS/pull/6671
A feature that moves the layer(s) or group(s) to the top of the layer panel. This code implements the feature request: https://issues.qgis.org/issues/16936.

### The reason behind the new feature:
This functionality is developed to make it easier to move a layer, layers or group(s) with layers to the top of the layer panel. This is especially a useful feature when the layer panel contains a lot of layers. Without this functionality, a user needs to drag the layer with the mouse to the top of the layer panel. This is cumbersome when the layer panel contains a lot of layers. Furthermore, sometimes it’s a little bit difficult to drop the layer at the correct place at the very top of the layer panel. When I switched from ArcMap to QGIS, this was one of the features that I missed in QGIS, especially when I add a layer to my QGIS-project, and then it is placed somewhere in the layer panel (just above the selected layer), quite often I want to have this layer at the very top – with this new feature, I just click on the layer and select ‘Move to Top’.

### Description of the new feature
This code adds the ‘Move to Top’-functionality to the context menu in the layer panel. This is the menu that appears when right-clicking on a layer/layers or a group/groups in the layer panel.

The feature works this way:

#### One layer (not in a group)
When the user right clicks on one layer (not in a group) and select ‘Move to Top’, the layer is moved to the very top of the layer panel.
#### Multiple layers (none of these are in a group)
When the user has selected more than one layer, right clicks on one of them and select ‘Move to Top’, the selected layers are all move to the very top of the layer panel – and with the same order as before.
#### Group(s) with layers
When the user right clicks on a group with layers and select ‘Move to Top’, the group(s) - with all the layers in the group – is/are moved to the top of the layer panel.
#### One layer or more layers in a group
When the user clicks on one layer or more layers within a group, the layer(s) is/are moved to the top of this group. I think this is the most intuitive way to handle this case. If a user wants to move a layer in a group to the top of the layer panel. The workflow would be first to use the ‘Make top level’-function to move a layer out of the group(s) and then use the ‘Move to top’ to move the layer to the top of the layer panel.

To avoid displaying the functionality where it does not make any purpose – i.e. if user clicks on a layer or a group that is already at the top, the code checks if this is the case and decide whether to show the functionality or not.

**Comment by simon1tan** [comment]
I like the idea but let's enhance this by using"Move Layer" and the user would type in the desired layer number. 0 being top, -1 being bottom, and any number between 0 and the number of layers. This would be more flexible. Otherwise somebody will want a "Move to Bottom". Might also implement layer numbering to make it easy to know the number to move to.

**Comment by DelazJ** [comment]
Dear @simon1tan 
Thanks for your suggestion. 
The described feature is already implemented in upcoming 3.2 and this repository only has to document it. If you want to give more chance to your ideas, you should report them at the application issue tracker (https://issues.qgis.org) or discuss it in the qgis-developer mailing list (see https://qgis.org/en/site/forusers/support.html) and/or (better, if you are skilled enough) propose the code at https://github.com/qgis/QGIS
Regards.
