### ISSUE TITLE
Add parameters to 'Execute SQL' algorithm

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2579]
Original commit: https://github.com/qgis/QGIS/commit/3984e906ea5487a70bc03ce20075adbb60f16103 by web-flow

[FEATURE][needs-docs] Add parameters to 'Execute SQL' algorithm

**Comment by havatv** [comment]
The new parameter type (ParameterExecuteSql) is (only) used in Execute SQL (Processing alg, QGIS, Vector general). It is currently only described as a string:

`SQL query [string] Type here the string of your SQL query, e.g. SELECT * FROM input1.`

https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/vectorgeneral.html#execute-sql
