### ISSUE TITLE
[FEATURE] Offline editing support for Z and M coordinates

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2581]
Original commit: https://github.com/qgis/QGIS/commit/8ad579b75492aacdf7a9e713c2a9295c02bfe431 by m-kuhn

Unfortunately this naughty coder did not write a description... :-(

**Comment by gioman** [comment]
Seems a good candidate to be closed, as user I would expect anyway full support for any kind of geometries in the off-line editing tool.

**Comment by nyalldawson** [comment]
More of a bug fix then a feature
