### ISSUE TITLE
[FEATURE] Optionally add back faces of polygons in tessellator

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2612]
Original commit: https://github.com/qgis/QGIS/commit/875da3f56c61694d78acc6ac972b45efafb3cbdb by wonder-sk

Often the polygonZ/multipatch data do not have consistent ordering of vertices
(e.g. all clock-wise or counter clock-wise). Disabling culling helps to avoid
seemingly missing surfaces, but the shading is still not correct due to reversed
normals. This new option to add back faces fixes the problem: for each triangle
we create both front and back face with correct normals - at the expense of increased
number of vertex data.

**Comment by havatv** [comment]
3D map view? But when will the user see this option?

**Comment by roya0045** [comment]
@havatv @DelazJ Is there a specific protocol for such old issues? I assume they are not documented but is a cleaned version needed or can the commit message be used?

**Comment by DelazJ** [comment]
Do you have a particular "protocol" in mind @roya0045 ?
Afaict the single plan is to document the feature if still available in current version(s) and close the report. And yes, this one is undocumented. IMO as long as the commit message is clear enough for end users and explains how or why they would use the feature, it's good enough to use. Here I see explanation of two features. Whether it can be pasted as is might depend also on how the [corresponding section](https://docs.qgis.org/3.16/en/docs/user_manual/style_library/3d_symbols.html#polygon-layers) in the docs is organized.

**Comment by DelazJ** [comment]
Ps: Thanks for willing to pick it ;)
