### ISSUE TITLE
[FEATURE] Introduction of QGIS Quick library

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2619]
Original commit: https://github.com/qgis/QGIS/commit/b1bf9b280948ece2659331e6bd7723312f1e076f by PeterPetrik

This pull request is a subset of #6490

This adds a new library for creation of applications based on Qt Quick
framework.
It contains reusable QML / Qt Quick components based on QGIS core
library.
The initial work introduces MapCanvas

To enable compilation of the library, use WITH_QUICK=TRUE

Further documentation of the library is located in doc/qgsquick.dox

For background information see the associated QEP:
qgis/QGIS-Enhancement-Proposals#109

The initial implementation is largely based on the work of Matthias Kuhn
and Marco Bernasocchi on QField probject - kudos to them for the great
job!

**Comment by DelazJ** [comment]
I guess we don't have to doc this...

**Comment by nyalldawson** [comment]
I don't think it needs documenting here either
