### ISSUE TITLE
[FEATURE][layouts] Use text renderer for drawing scalebar text

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2625]
Original commit: https://github.com/qgis/QGIS/commit/9d2c4fca1986a144f4e1cc8ada8a4450acb47e59 by nyalldawson

Allows the full range of formatting options exposed through
text renderer - e.g. scalebar text with buffers, shadows,
background shapes, letter spacing, etc.

Say goodbye to unreadable scale bar text!

**Comment by havatv** [comment]
Should not be necessary to document this, or?
