### ISSUE TITLE
[needs-docs][processing] vectorize and improve remaining geometry tools menu icons

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2632]
Original commit: https://github.com/qgis/QGIS/commit/5cb8c2523ec83eecc5d9a9476d3816aa30413b3b by nirvn

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment]
We do not show algorithms icons so not worth documenting
