### ISSUE TITLE
[needs-docs][processing] vectorize and improve remaining data analysis menu icons

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2634]
Original commit: https://github.com/qgis/QGIS/commit/9a82dbe19705978f28e718ede1dfe4cf7b02ac18 by nirvn

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment]
We do not show algorithms icons so not worth documenting
