### ISSUE TITLE
[needs-docs] Place core plugin actions into top level menus
when plugin only has a single action

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2636]
Original commit: https://github.com/qgis/QGIS/commit/408da458772657de1567899e3fcc0ca4acb48713 by nyalldawson

Affected actions:
- Database -> DB Manager -> DB Manager
- Coordinate Capture -> Coordinate Capture
- Vector -> Geometry Tools -> Geometry Checker
- Raster -> Georeferencer -> Georeferencer
- Vector -> Topology Checker -> Topology Checker

These are now just top level actions, e.g.
- Database -> DB Manager

**Comment by DelazJ** [comment]
This one needs to be documented: we have texts that instruct to eg `go to Vector -> Geometry Tools -> Geometry Checker` and should become `go to Vector -> Geometry Checker`

**Comment by havatv** [comment]
GPS should be fixed for the user guide in a7325e1 .
DB Manager, Geometry Checker, Topology Checker, Georeferencer and Coordinate Capture as menu items are not referenced in the user guide.
So when #3418 is merged, the user guide should be ok.

**Comment by DelazJ** [comment]
> DB Manager, Geometry Checker, Topology Checker, Georeferencer and Coordinate Capture as menu items are not referenced in the user guide.
So when #3418 is merged, the user guide should be ok.

I'm not that sure: see [Geometry checker occurrences](https://docs.qgis.org/testing/en/docs/user_manual/plugins/plugins_geometry_checker.html#geometry-checker-plugin), [Coordinate capture](https://docs.qgis.org/testing/en/docs/user_manual/plugins/plugins_coordinate_capture.html) (step 3 is assuming there's a sub-menu in vector)

**Comment by havatv** [comment]
I did see those, but did not think they were problematic (the name and icon are the same).  But I can fix them.

**Comment by havatv** [comment]
Should be fixed.
