### ISSUE TITLE
[FEATURE] Scalar/vector data in mesh data providers

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2648]
Original commit: https://github.com/qgis/QGIS/commit/3154102aa6952c156f4c219ac1adba8f277b3748 by PeterPetrik

Reading and processing scalar (e.g. water depth) and vector (e.g.
velocity) data from mesh data providers (e.g. MDAL)

**Comment by nyalldawson** [comment]
API only
