### ISSUE TITLE
[FEATURE] Rendering of vector data on mesh layers

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2650]
Original commit: https://github.com/qgis/QGIS/commit/aea3dccea78d253dbb8e2a9e51ae84ea1a110ec6 by PeterPetrik

Rudimentary support of rendering of vector data (e.g. velocity) on mesh map layers.
Rendering can be adjusted by QgsMeshRenderer*Settings. Only in Python
API, no GUI widgets for styling present.

**Comment by nyalldawson** [comment]
This is API only, so no need for docs
