### ISSUE TITLE
Add about migrating from Qgis2 to Qgis3

### ISSUE THREAD

**Issue by RemiDesgrange** [qgis/QGIS-Documentation#2651]
## Description

I didn't found any content in the master branch about migrating from qgis2 to qgis3 there are a lot of blog post about it on the internet but not a centralize one. One of the things I'm thinking about is 

* why my plugins dont work anymore
* where is the settings folder, can't find `.qgis3` or whatever
* etc...

What do you think ?

**Comment by DelazJ** [comment]
Hi @RemiDesgranges see what was begun at https://github.com/qgis/QGIS/wiki/Plugin-migration-to-QGIS-3

**Comment by DelazJ** [comment]
Should we not let this kind of information for bloggers, mailing lists, forum, social media? Or a wiki for users (in which case i'm not sure it should be bound to doc repo)?
My conception is that the documentation should care only about what is available in the release it's tackling, showing where features are and explaining them but without mentioning how things were working, named or located beforehand. Reason why I personally avoid expressions like `Previously`, `in QGIS 2.x`, `feature X has been moved from ... to ...`...
Taking the examples you give I'd say that according to me, the docs are a good place to answer 
> where is the settings folder

But not the right one to directly address
> why my plugins dont work anymore
> Where is the Composer ?
> can't find .qgis3

Those questions can be easily answered by doing a little search on Internet imho. Though the third one can indirectly be tackled in docs.
As said, this is my view and I may be wrong. And as always, it needs someone to do it (or at least prototype it)

**Comment by yjacolin** [comment]
We probably need to create a FAQ. When some contents are too big for a FAQ, we can add it in the documentation.

It could be easy to add a link from the QGIS Website and host it somewhere where user can easily contribute (wiki ? github pages ?).

**Comment by RemiDesgrange** [comment]
@DelazJ A lot of blogger already have made some post about migrating from qgis 2 to 3 (which is amazing),  maybe putting link to usefull blogpost *for the end user* in a FAQ ?

**Comment by DelazJ** [comment]
For the record, there's a FAQ page at https://qgis.org/en/site/getinvolved/faq/index.html that just needs some love.

**Comment by RemiDesgrange** [comment]
Ok I'll open a issue in Qgis-website repo then.

**Comment by yjacolin** [comment]
@RemiDesgrange, a PR is much better :)
