### ISSUE TITLE
[FEATURE][auth] OAuth2 authentication method plugin

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2679]
Original commit: https://github.com/qgis/QGIS/commit/244e8861dcbfee0cc6d7fe70e435ce1cf2cef816 by dakcarto

- Supports authentication code, implicit and resource owner grant flows
- Allows for preconfigured connections, read from default locations
- Offers caching of access token beyond QGIS restarts
- Save/load configurations
- Has documentation written

Sponsored by Monsanto Company

**Comment by Gustry** [comment]
This commit has been pushed to another branch than 'master' and this ticket should be closed for now I think

**Comment by elpaso** [comment]
Unfortunately the oauth2 auth provider was never merged, we can close this.

**Comment by DelazJ** [comment]
Interesting... why did that trigger a new issue report here?

**Comment by Gustry** [comment]
The branch has been pushed to the main `qgis/QGIS` repository.
https://github.com/qgis/QGIS/tree/oauth2

It seems the script took it as a new commit so it created this ticket here.

**Comment by DelazJ** [comment]
> The branch has been pushed to the main qgis/QGIS repository.
https://github.com/qgis/QGIS/tree/oauth2

Thanks @Gustry just read the concerned PR discussion. Issue creation makes sense indeed: we used to get simultaneously 2.18 and master commits in the past; no reason to limit to master branch only.
