### ISSUE TITLE
[OGR provider] [FEATURE] Add support for transactions on GPKG databases

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2721]
Original commit: https://github.com/qgis/QGIS/commit/6a987f913bbbc4b7a53ed4016a1ea26a0b9a2565 by rouault

For complete support, it requires two GDAL fixes:
- One to avoid feature count to be invalid when using ROLLBACK TO SAVEPOINT
  https://github.com/OSGeo/gdal/commit/f73ec8cd1dac08e66845397f59e47e4304f110d4

- Another one to avoid nasty issues, at least on Linux, with the POSIX
  advisory locks used by libsqlite that could be invalidated due to how GDAL
  could open files behind the back of libsqlite. The consequence of this
  could be the deletion of -wal and -shm files, which caused issues in QGIS
  (non working iterators when the edit is finished, and later edits in the
  same session not working). Those issues could appear for example if doing
  ogrinfo on the .gpkg opened by QGIS, or if opening two QGIS session on the
  .gpkg

Both fixes are queued for GDAL 2.3.1

**Comment by timlinux** [comment]
Do we have something  to describe in the docs here?

**Comment by DelazJ** [comment]
Nothing clear to me, afaict. 
I suggest we close it.
