### ISSUE TITLE
[qgsquick] [feature] Added identify and highlight feature

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2724]
Original commit: https://github.com/qgis/QGIS/commit/c780d607cc952f2e2762afb72a6625bfce162140 by web-flow

[qgsquick] [feature] Identify and highlight

**Comment by DelazJ** [comment]
@m-kuhn do you think this needs a particular documentation?

**Comment by PeterPetrik** [comment]
I think we would need to document the whole new library before 3.4 release. One thing is that the library is developer-only and there is no direct executable that users can use. It is for companies that want to create their own mobile GIS application based on QGIS core rendering, etc. Maybe some cookbook stuff or so?

**Comment by DelazJ** [comment]
It's not Python_isable_, right? Then I guess https://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/index.html which is the most developer friendly section in this repo is not suitable. So, does this issue report belong to this repository (aka close it?) or do _we_ need to set/find a new place for all these (in case https://qgis.org/api/group__quick.html and related are not enough)?

**Comment by PeterPetrik** [comment]
@wonder-sk can you please comment, I am not sure

**Comment by DelazJ** [comment]
API related. Not to document here.
