### ISSUE TITLE
[WFS provider] [FEATURE] Allow user to enable/disable paging and specify page size (fixes #18935)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2727]
Original commit: https://github.com/qgis/QGIS/commit/e998fcf0b2a1c7e07e6433b656a652eae46c6c35 by rouault

The 'maximum number of features' settings is now always the maximum number of
features requested, even in WFS 2.0 with paging.
For WFS 2.0, we add a checkbox to enable/disable paging and a text entry to
specify the page size (if let to empty, server default is used)
We also add a Detect button so that the WFS version is autodetected.

**Comment by havatv** [comment]
Update needed in the "WFS and WFS-T Client" section of Working with OGC data -> QGIS as OGC Data Client in the user manual.  The figure needs to be updated, and a description of the options could be useful.

**Comment by lajunek** [comment]
@havatv I will make the update
