### ISSUE TITLE
QGIS3.0

### ISSUE THREAD

**Issue by Greenyzac** [qgis/QGIS-Documentation#2735]
## Description

No Vector layer in top tool bar
No fTools in plug in do work with buffers ?
Bug in QGIS 3.0 ?

**Comment by Gustry** [comment]
Your request is clearly not understandable.

Are you reporting a bug in QGIS 3 Desktop? If yes, you must have read the template saying this repository is NOT the issue tracker.

What do you mean by "no vector layer in toolbar"?
FTools was removed since 2016 (QGIS 2.16)

**Comment by DelazJ** [comment]
To complete @Gustry answer, ensure you have checked "Processing" in the Plugin Manager or that the "vector" menu is not placed at the end of the menu bar (a bug in translated environment).
Anyway this looks like an application issue/question and not a documentation issue.

**Comment by DelazJ** [comment]
Closing...

**Comment by Greenyzac** [comment]
Dear Etienne,
The toolbar at the top of QGIS shows only the raster tab- there is no
vector tab. Is vector a plugin in QGIS 3?
Also the Geoprocessing tools, research tools etc.., where do they show up
in QGIS 3?
Thanks,
Greeny


On Sun, Jun 24, 2018 at 5:32 PM, Etienne Trimaille <notifications@github.com
