### ISSUE TITLE
Standardise style of keyboard shortcuts

### ISSUE THREAD

**Issue by jdugge** [qgis/QGIS-Documentation#2743]
## Description

At the moment, keyboard shortcuts are not completely uniform throughout the documentation:
* single letter key presses are sometimes displayed as [<kbd>A</kbd>](https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/editing_geometry_attributes.html#id30) and sometimes as [<kbd>a</kbd>](https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/editing_geometry_attributes.html#id71)
* special keys are sometimes displayed as [<kbd>Esc</kbd>](https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/editing_geometry_attributes.html#id41), and sometimes as [<kbd>ESC</kbd>](https://docs.qgis.org/testing/en/docs/user_manual/introduction/general_tools.html#id57)
* key combinations are sometimes displayed as [<kbd>Shift+R</kbd>](https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/editing_geometry_attributes.html#id67), sometimes as [<kbd>Shift + R</kbd>](https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/editing_geometry_attributes.html#id41), and sometimes as [<kbd>Shift R</kbd>](https://docs.qgis.org/testing/en/docs/user_manual/introduction/general_tools.html#id62)

It would be desirable to display keyboard shortcuts in a consistent style to avoid confusion about what the user is expected to do ("Does <kbd>S</kbd> mean just pressing the key with an 'S' on it, or pressing the key with an 'S' on it while also holding down the 'Shift' key?")

I would suggest the following conventions, which are already most commonly used in the documentation:
* Letter keys displayed using uppercase: <kbd>S</kbd>
* Special keys displayed with an uppercase first letter: <kbd>Esc</kbd>
* Key combinations displayed with a `+` sign between keys, without spaces: <kbd>Shift+R</kbd>

## Checklist
> This is the issue/bug trackers for [QGIS Documentation](https://docs.qgis.org).
Cleaning the queue is a process done by project maintainers, mostly on a volunteer basis.
We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items.

- [x] I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage.
If it's related to QGIS application or website, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html
for the right issue tracker or to the [support channels](http://qgis.org/en/site/forusers/support.html)
- [x] I have added a link to the page concerned by the issue

**Comment by jdugge** [comment]
This came up in #2706

**Comment by DelazJ** [comment]
Makes sense to me. Thanks for raising this.
