### ISSUE TITLE
Improve algorithm parameters description using tables

### ISSUE THREAD

**Issue by SrNetoChan** [qgis/QGIS-Documentation#2745]
## Description

This is a place holder to discuss the possible use of tables to describe the processing algorithms parameters instead of headings and bold syntax.

As discussed in Nodebo Hackfest, tables are hard to maintain in Sphinx. Meanwhile, while discussing #2738, I found some nice directives that may make it easier:

https://rest-sphinx-memo.readthedocs.io/en/latest/ReST.html#csv-table

I will try to come up with a structure for using them with the parameters. And see if it works.

Other improvements:

- [ ] See whether some data inputs should be more explained in a particular chapter
- [x] Add the Python identifier for each parameter
- [ ] Add the Python call for the algorithm
- [ ] Find where to place these "new" features in the formating
- [ ] Study whether a table structure is adapted for the alg description
- [ ] (optional) Add the custom icon of the algorithm when available - not a priority but if we come with a nice organization, it could be a plus
- [ ] Information whether the algorithm produces a new file or modifies the input one is inequally present. Could be nice to have a dedicated section (instead of inline comment in the description as now)

**Comment by SrNetoChan** [comment]
@DelazJ @ghtmtt 

I created a PR #2270 just to show how we could use tables in processing algorithms. I used table-lists with are not that bad to maintain (once you are used to it)

It's a bit more verbose than current syntax, but I think it looks better in the output.

I have added the python identifier to the parameter's name column and the (optional) information. I have put the Default value in the Type column.

Anyway, let's talk about this a see what is the pros an cons of this approach.

This is how the Count points in polygons would be written:

```
Parameters
..........

.. list-table::
   :header-rows: 1
   :widths: 20 20 60
   :stub-columns: 0

   *  -  Name
      -  Type
      -  Description

   *  -  **Polygons**

         ``POLYGONS``
      -  [vector: polygon]
      -  Polygons layer

   *  -  **Points**

         ``POINTS``
      -  [vector: polygon]
      -  Points layer

   *  -  **Weight field**

         ``WEIGHT``

         (Optional)

      -  [tablefield: any]
      -  The count generated will be the sum of the weight field for each point
         contained by the polygon.

   *  -  **Class field**

         ``CLASSFIELD``

         (Optional)
      -  [tablefield: any]
      -  Points are classified based on the selected attribute and if several
         points with the same attribute value are within the polygon, only one
         of them is counted. The final count of the point in a polygon is,
         therefore, the count of different classes that are found in it.

   *  -  **Count field name**

         ``FIELD``
      -  [string]

         Default: *NUMPOINTS*
      -  Points are classified based on the selected attribute and if several
         points with the same attribute value are within the polygon, only one
         of them is counted. The final count of the point in a polygon is,
         therefore, the count of different classes that are found in it.

Outputs
.......


.. list-table::
   :header-rows: 1
   :widths: 20 20 60
   :stub-columns: 0

   *  -  Name
      -  Type
      -  Description

   *  -  **Count**

      -  [vector: polygon]
      -  Resulting layer with the attribute table containing the new column of
         the points count.
```

And this is how it renders:

![image](https://user-images.githubusercontent.com/3607161/42160248-69c33484-7dee-11e8-9b70-c1823e36f516.png)

**Comment by havatv** [comment]
I think we can close this now. #4429 should cover what is left.

**Comment by SrNetoChan** [comment]
Wow...huge work! Thanks @havatv for implementing this. It's kinda embarrassing not being able to do a single conversion myself...
