### ISSUE TITLE
[FEATURE][auth] OAuth2 authentication method plugin

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2750]
Original commit: https://github.com/qgis/QGIS/commit/b66a751cd879f87035974d75766e03914fec439d by elpaso

- Supports authentication code, implicit and resource owner grant flows
- Allows for preconfigured connections, read from default locations
- Offers caching of access token beyond QGIS restarts
- Save/load configurations
- Has documentation written

Sponsored by Monsanto Company

**Comment by havatv** [comment]
The figure showing available method plugin list should be updated, and a new illustration of the oauth2 authentication configuration window added.
A new subsection on oauth2 could be considered.
