### ISSUE TITLE
[mesh] [feature] App widgets for styling mesh layers

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2752]
Original commit: https://github.com/qgis/QGIS/commit/aeea1848902afb7a7e78386212f5778aaf400aa2 by PeterPetrik

- Adding datasets to mesh layer from properties panel
- Information and source panel in properties panel
- Selection of active dataset (properties or styling panel)
- Styling of contours/scalars (properties or styling panel)
- Styling of mesh frame (properties or styling panel)
- Styling of vector arrows (properties or styling panel)

**Comment by havatv** [comment]
This will probably have effects on illustrations in (a new mesh layer section of?) the user manual.

**Comment by havatv** [comment]
@DelazJ, could we close this one (the chapter is in place, and much is already included there)? In my opinion, it would be better to close and encourage more specific issues for the missing parts.
