### ISSUE TITLE
Add a warning on top of Cookbook pages

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#2754]
Because people still try to reuse code snippets in the Cookbook and because |updateDiclaimer|, while stating update is in process, doesn't let you know the place that are up to date and those that may be not, I'd like to suggest to add a warning message at the top of those pages:
* I'm targeting the Cookbook as this is where the outdated information can be harmful for developers or wannabe devs. No need to add that info in the user manual or training one I think.
* we save time to python devs by redirecting them to the pyqgis docs (advertising that one at the same occasion)
* we can point people to that warning if ever someone complains AGAIN about wrong commands
* when a page is globally updated (pyqt5, py3, new API at the time of writing), we remove the mention
* when a page is partially updated, assuming the updates comes from the top, we move the warning position up to the last changes (see https://github.com/qgis/QGIS-Documentation/pull/2744/files#diff-42f28cb6ff4ab72554d8ac85e4b1f84dR248) and if the update has been done erratically, the message stays at the top of the page.
* make a "permanent" call for updaters (I don't know whether it gives good signal from the QGIS doc quality but there's a lack in this area) ; If a dev is looking for docs it's because he doesn't know something but I assume he knows some other thing a little bit and if he can help... 🤞 

A kind of message (correction and remarks are more than welcome):

`.. warning:: Information beyond this line are not updated for QGIS 3. Refer to https://qgis.org/pyqgis/master for  an up to date python documentation or, give a hand to update the chapters you know about. Thanks.`

_Hoping that such a message wouldn't stay there forever...._

**Comment by DelazJ** [comment]
I got no reaction on this proposal but you'll find an implementation at #2776 (in case it's worth going forward)

**Comment by raymondnijssen** [comment]
I'm planning to spend some time on the cookbook during the foss4g europe code sprint. I want to test every piece of code from the cookbook in qgis (3.3) and mark all the errors with a line: "TODO: fix this for 3.x". Then we will have an idea of how much we need to update and can ask people to help fixing all of them.

This line of comment will also function as a warning for devs.

**Comment by DelazJ** [comment]
@raymondnijssen good news, that!
> This line of comment will also function as a warning for devs.

Do you mean that it'd not be worth adding a "top movable to bottom" warning for the whole page (#2776)? Other than code sample, there are also texts describing the context of implementation or the logic of the methods; we would still need to identify the obsolete ones...
