### ISSUE TITLE
[feature] [qgsquick] Add PositionKit, PositionMarker and CoordinateTransformer

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2763]
Original commit: https://github.com/qgis/QGIS/commit/569db8e06916cda89b07a10a3876a395550aece4 by web-flow

[feature] [qgsquick] Add PositionKit, PositionMarker and CoordinateTransformer

**Comment by DelazJ** [comment]
I don't think there is anything to do here, from the docs perspective...
