### ISSUE TITLE
[FEATURE] QgsSpatialIndexKDBush

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2775]
Original commit: https://github.com/qgis/QGIS/commit/0df1056dd4fd7d4d86118c8d2d2b1963917afbb9 by nyalldawson

A very fast static spatial index for 2D points based on a flat KD-tree,
using https://github.com/mourner/kdbush.hpp

Compared to QgsSpatialIndex, this index:
 - supports single point features only (no multipoints)
 - is static (features cannot be added or removed from the index after construction)
 - is much faster!
 - supports true "distance based" searches, i.e. return all points within a radius
from a search point

**Comment by DelazJ** [comment]
API related

**Comment by Gustry** [comment]
I think we can update these snippets: https://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/vector.html#using-spatial-index

This new index seems much better according to Nyall's benchmark. I think it's worth updating this chapter. I will try to do it

**Comment by havatv** [comment]
@Gustry, how is this progressing?
