### ISSUE TITLE
Revert "[processing][needs-docs] Add 'not selected' option for optional layer parameters in processing models"

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2779]
Original commit: https://github.com/qgis/QGIS/commit/5f48fa2b768d2b712336ed5503b25419e0ab83c7 by web-flow

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment]
This reverts something that was not added to this repo, hence closing
