### ISSUE TITLE
[general tools] Identify tools has been changed (new ui, new feature)

### ISSUE THREAD

**Issue by yjacolin** [qgis/QGIS-Documentation#278]
* icons has been move at the top of the dialog
* new combo box allow user to change identify mode
* allow auto open form
* view combo box

See http://docs.qgis.org/testing/en/docs/user_manual/introduction/general_tools.html?highlight=selection#identify

@3nids: what view combox box is used for? How can I enable it?

Todo:
* add new text ( @yjacolin )
* update screenshot ( @SrNetoChan )

**Comment by junek** [comment]
I inserted the rest of the missing information into the user manual 2.8.!
