### ISSUE TITLE
[feature] addMeshLayer to qgsinterface

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2783]
Original commit: https://github.com/qgis/QGIS/commit/e135b9cf9fb66f4dfda22c418ce54469dc287abf by wonder-sk

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment]
A data source type in the data source manager.  Data source manager illustration(s) may need to be updated.
This type of data source should probably also be described.

**Comment by lajunek** [comment]
@havatv @DelazJ I can implement this

**Comment by DelazJ** [comment]
@lajunek don't manually close the issue; add "fix #issuenumber" in your pull request message and this will be closed when merged. Also this helps to know which change addresses a particular issue
