### ISSUE TITLE
[quick] [feature] Feature attribute panel

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2784]
Original commit: https://github.com/qgis/QGIS/commit/4ca91b2858748b937871395296b7aa7e11e71b1a by PeterPetrik

Allow to show feature attribute form and edit/save the modification
of the attributes. Support most frequent QGIS edit widgets such
as text edit, value map or external resource (photo capture)

**Comment by DelazJ** [comment]
This is for mobile and not really a new feature. Closing.
