### ISSUE TITLE
QGIS Crashed

### ISSUE THREAD

**Issue by GohanSan17** [qgis/QGIS-Documentation#2787]
h2. User Feedback

h2. Report Details

*Crash ID*: 2158b01f96452b8cf079fabd6f476862ce1a56f9

*Stack Trace*
<pre>
QDockWidget::toggleViewAction :
QgisApp::removeDockWidget :
QgsPresetSchemeColorRamp::clone :
PyCFunction_FastCallDict :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyErr_Occurred :
PyEval_EvalCode :
PyArena_Free :
PyRun_StringFlags :
instance :
instance :
QgsPluginRegistry::unloadAll :
QgisApp::saveWindowState :
QMetaObject::activate :
QCoreApplicationPrivate::execCleanup :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.2.0-Bonn
QGIS code revision: commit:bc43194061
Compiled against Qt: 5.9.2
Running against Qt: 5.9.2
Compiled against GDAL: 2.2.4
Running against GDAL: 2.2.4

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by DelazJ** [comment]
Hi @GohanSan17
The issue you are reporting is an application one and should be reported at https://issues.qgis.org. This repository is dedicated to QGIS documentation matters.
Thanks
