### ISSUE TITLE
[FEATURE][needs-doc] Vertex tool can work on the current layer only

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2799]
Original commit: https://github.com/qgis/QGIS/commit/6363aba94e36d4611da234cf3e5a5b364e697f71 by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by ghtmtt** [comment]
Closing this because already well documented (see https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/editing_geometry_attributes.html#digitizing-an-existing-layer)
