### ISSUE TITLE
Unexpected removal of references when updating substitutions list with the automatic script

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#2810]
When executing the `./scripts/find_set_subst.py` script, it happens that references to some substitutions (`|plugin-new|` and `|plugin-upgrade|`) in the `source/docs/pyqgis_developer_cookbook/plugins.rst` are removed despite they are being used in the file.

**Comment by SrNetoChan** [comment]
Thanks @DelazJ

**Comment by SrNetoChan** [comment]
Found that the script does not like the use of hyphens in the substitutions.

**Comment by SrNetoChan** [comment]
this should fix it:
https://github.com/boundlessgeo/QGIS-Documentation/commit/1c671c2ab2f58037f401b8d4f63f08613fe14932
