### ISSUE TITLE
[FEATURE][processing] Choice of units for non degree/unknown distances

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2822]
Original commit: https://github.com/qgis/QGIS/commit/2692de6ed084cb068bbefe00d6c87f0fd10e0c57 by nyalldawson

When an algorithm has a distance parameter in meters/feet/etc (i.e.
non-geographic distances), show a combo box allowing choice of
unit type.

(We don't (and should never) expose this for distances in degrees --
it's up to users in this situation to choose a suitable local
projection and reproject their data to match. Refs: a recent
talk by @volaya)

**Comment by havatv** [comment]
I could not find any places where the documentation needs to be updated because of this. I found one screenshot in the training manual that included this combo box, and it was properly explained. So I am closing. Please reopen if you have other suggestions.
