### ISSUE TITLE
[FEATURE] Simple rendering of 3D linestrings

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2826]
Original commit: https://github.com/qgis/QGIS/commit/6482a3b4d0f716915f0cecfb73c2692da582d7f4 by wonder-sk

This mode of 3D line rendering will use OpenGL line rendering
instead of buffering lines into polygons and rendering them as meshes.

The advantage is that the 3D lines do not loose their Z coordinate
which is the case currently with "ordinary" 3D rendering after buffering.

The disadvantage is that the lines cannot be wide (supported in Qt3D only
since 5.10, but even then their rendering won't have nice joins/caps)
and only ambient color is used from the material.

**Comment by ghtmtt** [comment]
@DelazJ do you think this is worth to document? IMHO the PR introduces something *behind the scenes* that the user is not aware (and should not be aware of). Opinions?

**Comment by DelazJ** [comment]
Agreed. Behind the scene. Closing
