### ISSUE TITLE
[FEATURE] Add Open Directory option to disabled welcome page projects

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2833]
Original commit: https://github.com/qgis/QGIS/commit/efd5cc546549b70c5c361d411f5c33a32a1b1105 by nyalldawson

This allows users to open the closest existing path to the original
project location in their file manager, to hopefully help them
re-locate missing/moved/renamed projects.

**Comment by selmaVH1** [comment]
@DelazJ This looks like it's already mentioned in [https://docs.qgis.org/3.28/en/docs/user_manual/introduction/project_files.html](url) . Is there a need for a detailed description, or can we close this?
