### ISSUE TITLE
[FEATURE] Add linux native progress report API (#7549)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2840]
Original commit: https://github.com/qgis/QGIS/commit/9664103f22e43412dbb59ba83f29f6b0b59d92e0 by web-flow

Works on: 
- Unity
- Gnome-Shell (dash to dock extension)
- KDA Plasma

**Comment by DelazJ** [comment]
@nirvn anything worth documenting here?

**Comment by nirvn** [comment]
Not really, this merely adds a progress bar into the user's taskbar on most linux distros.

**Comment by DelazJ** [comment]
Thanks.
