### ISSUE TITLE
Enable Plugins

### ISSUE THREAD

**Issue by 14benguetgeotagging** [qgis/QGIS-Documentation#2843]
## I need to enable my plugins in QGIS version 2.16.1. There was a sudden power surge in our area and my PC automatically turned off, my UPS was not working so the whole unit turned off entirely. I was not able to close the app properly and now I was able to open QGIS but all my original plugins won't show. I don't know how to enable the plugins back. Please see attached image for details.
![plugin error](https://user-images.githubusercontent.com/42225777/43873417-207f1f5c-9bb9-11e8-81fb-7cae3cc34253.png)

## Checklist

- [ ] I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage.
If it's related to QGIS application or website, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html
for the right issue tracker or to the [support channels](http://qgis.org/en/site/forusers/support.html)
- [ ] I have added a link to the page concerned by the issue

**Comment by Gustry** [comment]
Did you read the checklist at the bottom of your issue?

> I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage.

FYI, 2.16 is not maintained anymore. Try to update to 2.18 if you need to stay on QGIS 2.
Try to disable all plugins first and then restart QGIS. Enable them one per one.

**Comment by 14benguetgeotagging** [comment]
I see so sorry about that, this is the first time that I experienced it
that is why I reported it and I never had any issues on the old version not
until now. But thank you.

On Thu, Aug 9, 2018 at 10:16 AM, Etienne Trimaille <notifications@github.com

**Comment by DelazJ** [comment]
Closing this report. Thanks.
