### ISSUE TITLE
[mesh] [feature] function to get value for the point on map

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2851]
Original commit: https://github.com/qgis/QGIS/commit/ad4ddb186a7100b55e95da1b84b66f8a969f3a80 by web-flow

[mesh] [feature] function to get value for the point on map

**Comment by DelazJ** [comment]
Not convinved there is anything more we have to do here. It looks like some API improvements, a ground work for mesh element identifcation (#5894) and information about data on vertice/face is mentioned in #6845.
