### ISSUE TITLE
[FEATURE] Add a button in attribute table toolbar to switch between
docked and window mode

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2855]
Original commit: https://github.com/qgis/QGIS/commit/1e051f0efb32d56b804afee1fc3407f8cfef8548 by nyalldawson

Previously you had to change an option in the settings dialog and
open a new table in order to switch between docked/undocked, but
that's painful if you decide after a table is already open that
you'd like to dock/undock it...

**Comment by enzedrailmaps** [comment]
Hi Nyall
What is exactly this functionality? I know the GUI well but don't know what "docking" means in this context.

**Comment by Gustry** [comment]
Look at the pull request. There is a GIF.
https://github.com/qgis/QGIS/pull/7578

It's a dock when it's embedded in the main QGIS application window and not as a separated window on top of QGIS window.
