### ISSUE TITLE
[FEATURE] New geometry API call to return a curve substring

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2857]
Original commit: https://github.com/qgis/QGIS/commit/513bcb68e48faff5546b7c7ed02e7f7cc68eb9b3 by nyalldawson

Returns a new curve representing a substring of a curve, from
a start distance and end distance.

If z or m values are present, the output z and m will be interpolated using
the existing vertices' z or m values.

Handles curved geometries without loss.

**Comment by ghtmtt** [comment]
I think #2886 fixes also this. Or maybe better: this issue just explain that we have new API. I will close this.
