### ISSUE TITLE
[FEATURE] Use native interpolate point method instead of GEOS method

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2861]
Original commit: https://github.com/qgis/QGIS/commit/c6a91dab094d8b55ac6c09b04c805f351e5ba701 by nyalldawson

Because:
- Exactly follows curves and doesn't require segmentizing input geometry
- Also interpolates z/m values if they are present in input geometry
- Is faster

**Comment by DelazJ** [comment]
not sure it's worth documenting
