### ISSUE TITLE
[FEATURE] Script-provided algorithms support for run script action

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2875]
Original commit: https://github.com/qgis/QGIS/commit/fcd01577036f88e77035e6d8848f8e555d8eca68 by nirvn

Scripts with now launch a processing algorithm dialog (when appropriate) when:
- drag and dropping a python script onto the main window
- using the browser panel's right-click run script action

**Comment by havatv** [comment]
I have not been able to make this work in 3.4 (I am able to right-click in the browser and choose "Run Script", but only receive errors with the scripts under /usr/share/qgis/python/plugins/processing/algs/qgis).  Has anyone successfully used this feature? If it works, how and where should it be documented?
