### ISSUE TITLE
[Processing] Scope of the [vector: any] tag for parameters

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#2887]
The `[vector: any]` tag next to an algorithm parameter is used to indicate when it supports point, line and polygon layer (eg, "Add geometry attributes" alg).
But when it also supports geometryless layer (ie simple table - eg "select by expression" alg), what should we use?

**Comment by ghtmtt** [comment]
I agree with your doubts: but, isn't a geometryless table a kind of subset of the main vector type? I know that is seems forced, but I think users won't get confused.

**Comment by havatv** [comment]
I agree with @ghtmtt. I think we can close this issue. But it is up to you, @DelazJ.
