### ISSUE TITLE
[Server][Feature][needs-docs] Create WMTS service Tests

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2919]
Original commit: https://github.com/qgis/QGIS/commit/385de9db003e42d8fd7b7852b9bb75fedef8efee by rldhont

Unfortunately this naughty coder did not write a description... :-(

**Comment by pblottiere** [comment]
I don't think this issue needs documentation (it's not a feature). I'm in favor of closing it.

What do you think @tudorbarascu?
