### ISSUE TITLE
[Server][Feature][needs-docs] Add QgsWmtsParameters to WMTS service

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2924]
Original commit: https://github.com/qgis/QGIS/commit/408484d48637fed9e59fe7af27c98dc31d524f47 by rldhont

Unfortunately this naughty coder did not write a description... :-(

**Comment by pblottiere** [comment]
I don't think this issue needs documentation (it's not a feature). I'm in favor of closing it.

What do you think @tudorbarascu?

**Comment by pblottiere** [comment]
@havatv 

Actually there's a lot of "false issue" for the WMTS support: https://github.com/qgis/QGIS-Documentation/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Aserver+wmts+

**Comment by havatv** [comment]
I suggest that you close all those issues an add a new issue for documenting WMTS support in QGIS server (if it is not already documented - I could not find it).

**Comment by pblottiere** [comment]
> I suggest that you close all those issues an add a new issue for documenting WMTS support in QGIS server 

I don't have enough rights to close issues on QGIS-Documentation :). But I totally agree with your approach.

> (if it is not already documented - I could not find it).

No it's not. I'm currently working on it.

**Comment by havatv** [comment]
OK.  As soon as you have created the new issue, I suggest that @tudorbarascu closes this and the other issues you have pointed at.  I can also close them if you ping me later.
