### ISSUE TITLE
[Processing][Needs-docs] Allow optional "value" in "select by attribute" algorithm

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2937]
Original commit: https://github.com/qgis/QGIS/commit/4d6211d18b5a49005fc0dc28d6d7de86bb071f30 by nyalldawson

because it's not needed to run null checks (fixes #19469 which is actually reported in the wrong way)

(cherry picked from commit 4e1d29ee241f53297ff2a332554154fd0ad27b73)

**Comment by DelazJ** [comment]
Duplicate of #2934
