### ISSUE TITLE
[Spanish] wrong translation in options

### ISSUE THREAD

**Issue by yjacolin** [qgis/QGIS-Documentation#2953]
Hi

I find a mistake on the spanish translation in the USER GUIDE/MANUAL (QGIS 2.18) options, from up to down next to "Administrar el origen de datos" you write "Trabajar con catos vectoriales" and next to that "Trabajar con catos raster" is DATOS intead of "CATOS".

Thanks for your time and work

From: https://github.com/qgis/QGIS-Website/issues/560

**Comment by yjacolin** [comment]
@Lexfhebry Could you give us a link to the html page where you find this error?

**Comment by DelazJ** [comment]
This is an issue that we, as doc writers, can not fix. And This is likely where language-based community members are needed. @Lexfhebry you'll find all needed information to get it fixed by yourself (and btw help to fix/translate many other strings) at https://qgis.org/fr/site/getinvolved/translate.html#becoming-a-translator

@yjacolin this is the docs TOC.

**Comment by DelazJ** [comment]
@luipir can you give this a look, please: using "catos" instead of "datos" in title (see https://docs.qgis.org/3.4/es/docs/user_manual/index.html)? I'd like to close this issue we, as writers but no spanish translators, can't fix.
PS: sorry, you are the spanish speaker that came to my mind...

**Comment by luipir** [comment]
ok @DelazJ I'll do tomorrow... strange that none of spanish translation group noticed the error.

**Comment by DelazJ** [comment]
I was also surprised to find it still true after so long. Thanks for taking care.

**Comment by luipir** [comment]
@DelazJ some member of QGIS.es already fixed in transifex... looking a way to have a reference to this change

**Comment by DelazJ** [comment]
Great. I'm closing then. Thanks @luipir

**Comment by luipir** [comment]
@DelazJ btw I find hard to trace modification in transifex with git issues... I didnt' find a way to point to a versioning of the translation in transifex, and in transifex web interface I can't find modifications (latest is  6th of Dec :/ )

**Comment by DelazJ** [comment]
I'm not sure I understand what you tried but these are two separate "projects". And it is not necessary to link the issues. As long as they are fixed, everybody is happy 😄

**Comment by luipir** [comment]
@DelazJ welll.... I'm not used to have a platform without possibility to trace modifications (also among different project) would be enough to have a link to the modification (with an commit hash or something eelse). BTW if everybody is happy, I'm happy too :)

**Comment by luipir** [comment]
BTW tnks to take care of the cleaning of the documentation issues @DelazJ

**Comment by DelazJ** [comment]
> BTW if everybody is happy, I'm happy too :)

👍 Actually, that bug should have never been reported here I think. And in transifex reporting system is quite hidden
> BTW tnks to take care of the cleaning of the documentation issues @DelazJ

You are welcome. We try to do our best.
