### ISSUE TITLE
[FEATURE] Style manager opens non-modally

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2958]
Original commit: https://github.com/qgis/QGIS/commit/41e2892af79355d2cfa8e0c3865668d668e631f6 by nyalldawson

Allows style manager dialog to be used alongside main QGIS window,
just like the layout manager.

**Comment by DelazJ** [comment]
I'm not sure we ever say it was modal so closing...
