### ISSUE TITLE
[FEATURE][metasearch] Add FILE:GEO to known link types

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2961]
Original commit: https://github.com/qgis/QGIS/commit/689126b18a52fa7aae9884be8e1277c927599afa by nyalldawson

Adds GIS File link type to known link types, and for records with
a FILE:GEO link enables a new "Add GIS File" action. Clicking this
adds the linked GIS file to the current project.

**Comment by timlinux** [comment]
@selmaVH1 can you add this to https://docs.qgis.org/3.28/en/docs/user_manual/plugins/core_plugins/plugins_metasearch.html ?
