### ISSUE TITLE
[FEATURE][native] Add badge count support for the linux platform

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2970]
Original commit: https://github.com/qgis/QGIS/commit/5030121e8a25674749666ffd9efccfd5e71469ff by nirvn

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment]
I don't think this should be described in the documentation.

**Comment by DelazJ** [comment]
Agreed
