### ISSUE TITLE
Snap to grid for maptools [FEATURE]

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2974]
Original commit: https://github.com/qgis/QGIS/commit/32ee71634fe96699964fa86dea98273454f977db by web-flow

Snap to grid for maptools [FEATURE]

**Comment by havatv** [comment]
How does one activate this feature in 3.4.3?

**Comment by roya0045** [comment]
@m-kuhn I had a look at the referenced feature and I'm not sure how to enable the 'grid', do you remember how to replicate your gif? The procedure seems rather hidden, if still doable.

**Comment by m-kuhn** [comment]
Please unhide it, it's still doable, but so far only documented in the PRs with short descriptions and gifs

- https://github.com/qgis/QGIS/pull/7672
- https://github.com/qgis/QGIS/pull/7711

**Comment by roya0045** [comment]
@m-kuhn what I meant by hiden is that no one knew where to look for. But the gif in 7711 gave me the clue I needed. Thanks!
