### ISSUE TITLE
[FEATURE] 3D identify tool working on 3D entities

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2997]
Original commit: https://github.com/qgis/QGIS/commit/2085dfa6aefc39800f453f2ab4a1242568701817 by wonder-sk

Until now the tool only considered terrain. This commit adds support
for 3D renderers created from vector layers, so it is possible to
correctly identify polygons and linestrings in 3D.

**Comment by havatv** [comment]
I guess that users are expecting this behaviour, so does it need to be documented?
