### ISSUE TITLE
[FEATURE][needs-doc] Support QGIS Server logs to stderr

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3005]
Original commit: https://github.com/qgis/QGIS/commit/e33954c1c35f8980a15155cf388ae72fc9fafc79 by elemoine

This commit makes it possible to configure QGIS Server to make it
write its logs to stderr.

This is done by setting the QGIS_SERVER_LOG_FILE env var to the
special value "stderr".

**Comment by DelazJ** [comment]
Closed in #3014
