### ISSUE TITLE
[FEATURE][needs-doc] Introduce QGIS_SERVER_LOG_STDERR and deprecate file logging

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3006]
Original commit: https://github.com/qgis/QGIS/commit/5b808f6a22637ca052ca9d696d0a4a93c42dcde3 by elemoine

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment]
closed in #3014
