### ISSUE TITLE
[FEATURE] QML chart and drawings widget

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3007]
Original commit: https://github.com/qgis/QGIS/commit/b75f9f3b5b4df58a7974c60f629a58f2b1ae42b1 by web-flow

[FEATURE] QML chart and drawings widget

**Comment by felixfeckler** [comment]
@DelazJ 
I guess this one was fixed by https://github.com/qgis/QGIS-Documentation/pull/6919 . But i am not sure if sufficient since it only mentions the QML option and i guess a little bit more documentation of this feature would be nice?

**Comment by DelazJ** [comment]
I wouldn't call that a fix for this issue. I still have no idea how to begin working with these QML and HTML widgets and this is what I was trying to state in _https://github.com/qgis/QGIS-Documentation/pull/6919#discussion_r703600542_

> _Furthermore, and I'm not necessarily asking for this PR, we can imagine a new line for QML and HTML widgets with same kind of minimal text (**until someone one day cares about explaining what they are about**)_

So yes, a little bit doc is welcome. Thanks @felixfeckler
