### ISSUE TITLE
Merge pull request #7889 from borysiasty/plugins_from_encrypted_zips

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3009]
Original commit: https://github.com/qgis/QGIS/commit/ec2ddb4295badd6953237e5e9182b7903f429e5a by web-flow

[FEATURE][Plugin installer] Support for encrypted zips when installing plugins from local files

**Comment by DelazJ** [comment]
Duplicate of #3008
