### ISSUE TITLE
[FEATURE] Append raster layer to an existing Geopackage in the 'Save Raster Layer As' dialog. Fixes #17926

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3010]
Original commit: https://github.com/qgis/QGIS/commit/60fa8eae073891bc2e2f1cb86ae10b71434cb11c by borysiasty

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment]
I don't get what this update does.
Is it something that needs to be documented?

**Comment by havatv** [comment]
If should be sufficient to document that GeoPackage is a supported (and recommended) container also for raster data. I have tried to do that in #4849. When it has been merged, this issue can be closed (and we can be happy that the QGIS bug was fixed). :-)
