### ISSUE TITLE
[FEATURE] Snap geometries algorithm

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3012]
Original commit: https://github.com/qgis/QGIS/commit/4a0669714bbe8337f8edb9537259b6279117ae20 by wonder-sk

Makes sure that any two vertices of the vector layer are at least at distance given by the threshold value.
The algorithm moves nearby vertices to one location and adds vertices to segments that are passing around other
vertices within the threshold. It does not remove any vertices. Also, it does not modify geometries unless
needed (it does not snap coordinates to a grid).

This algorithm comes handy when doing vector overlay operations such as intersection, union or difference
to prevent possible topological errors caused by numerical errors if coordinates are very close to each other.

After running the algorithm some previously valid geometries may become invalid and therefore it may be useful
to run Fix geometries algorithm afterwards.

**Comment by DelazJ** [comment]
@nyalldawson @wonder-sk Am I right that the description from the commit is wrong and this [feature](https://github.com/qgis/QGIS/pull/7194) resulted, for the user manual, only in an additional item to the "Behavior" drop down menu described at https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/vectorgeometry.html#snap-geometries-to-layer? Anything else?

**Comment by nyalldawson** [comment]
@DelazJ correct. There's (quite lengthy) discussion https://github.com/qgis/QGIS/pull/7194 which relates.
