### ISSUE TITLE
[feature] Identify/Select polygon from existing feature geometry

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3016]
Original commit: https://github.com/qgis/QGIS/commit/b70489bf06ba556ef64f9307fcd3fed3158c5b7a by PeterPetrik

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment]
No new entries in the user interface.  Only the possibility to choose an existing polygon instead of drawing a new one with `Edit-> Select feature-> Select Features by Polygon` and right-click inside a polygon.
Also available for the identify features dialogue (`Identify Features by Polygon`).
