### ISSUE TITLE
[feature] Adapted k-neighbour concave hull plugin as QGIS 3 algorithm

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3018]
Original commit: https://github.com/qgis/QGIS/commit/52ccc43ebb238db84d2ef4758d864a4257848a41 by rudivs

Co-authored-by: Detlev Neumann <dneumann@geospatial-services.de>

**Comment by havatv** [comment]
Are all "standard" processing algorithms documented? And if they are - where?

**Comment by DelazJ** [comment]
what do u call "standard" algorithm? https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/?

**Comment by DelazJ** [comment]
This alg is under qgis > geometry and should be documented

**Comment by havatv** [comment]
Thanks for the information, @DelazJ.  I have added documentation (without illustrations) and updated the name of the original concave hull algorithm.
