### ISSUE TITLE
[FEATURE][needs-docs] import/export section of vector layer style 

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#3022]
See https://github.com/qgis/QGIS/pull/7863

**Comment by haubourg** [comment]
ping @m-kuhn is there work in progress around here ?

**Comment by m-kuhn** [comment]
pint @3nids

**Comment by 3nids** [comment]
Yes, still on the list.

**Comment by havatv** [comment]
Documented in https://docs.qgis.org/testing/en/docs/user_manual/introduction/general_tools.html#managing-custom-styles
