### ISSUE TITLE
[Plugin manager][needs-docs] Better looking links to the installed and available version. Remove no longer used code.

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3023]
Original commit: https://github.com/qgis/QGIS/commit/3dc0c5670e43141afb76d4169b127a5621cda616 by borysiasty

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment]
I don't think this needs to be documented.

**Comment by ghtmtt** [comment]
closing. Reopen if necessary!
