### ISSUE TITLE
[Plugin manager][needs-docs] Deprecated plugins are listed gray. Fixes #19125

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3025]
Original commit: https://github.com/qgis/QGIS/commit/05c9e0180e65e2505414249ad0f15797ff97e0a3 by borysiasty

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment]
The rendering of deprecated plugins in the plugin manager has not been documented before.  Should it be documented now, or can this issue be closed?  If it is to be documented, I guess that we can change "They appear among invalid plugins list" to "They are rendered as disabled (grey text) and appear among the invalid plugins"
