### ISSUE TITLE
 Updated ms installer icons

### ISSUE THREAD

**Issue by m-kuhn** [qgis/QGIS-Documentation#3026]
The icons have been changed, see: https://github.com/qgis/QGIS/pull/7930

As per the comments there, @anitagraser was not sure if they are actually used somewher in the docs.

**Comment by DelazJ** [comment]
Sorry but I do not understand what is solved in the software. Any hint where these icons are used in the app and where they could be used in the docs?

**Comment by anitagraser** [comment]
As far as I know, these are the application icons of the QGIS installer for Windows.

**Comment by DelazJ** [comment]
I'm not sure we have in docs a dedicated place for windows installer. All the icons we used are in static/ folder and I see an old logo being used (see #3052) but this old logo is also used as icon for tabs in eg Firefox. Don't know where they are configured but maybe Travis will fail and help to flush them out.

**Comment by rduivenvoorde** [comment]
@DelazJ are we talking about: 

![image](https://user-images.githubusercontent.com/731673/46293346-81012380-c593-11e8-8f24-cc7100046833.png)

Those are facivons I think...

**Comment by rduivenvoorde** [comment]
Yep, see: 
https://github.com/qgis/QGIS-Documentation/blob/master/themes/qgis-theme/static/images/favicon.ico
vs
https://raw.githubusercontent.com/qgis/QGIS-Website/master/themes/qgis-theme/static/images/favicon.ico

**Comment by DelazJ** [comment]
Yes. Thanks!

**Comment by DelazJ** [comment]
> As far as I know, these are the application icons of the QGIS installer for Windows

Afaik, nothing is related to this in the docs so closing
