### ISSUE TITLE
[BUGFIX][NEEDS-DOCS] add command line option to hide browser (refs #18260)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3035]
Original commit: https://github.com/qgis/QGIS/commit/4911d2e7457549ead085a8a3f690348afde6e54a by jef-n

Unfortunately this naughty coder did not write a description... :-(

**Comment by SrNetoChan** [comment]
It seems that other command line options need to be updated on documentation. there's no longer options path, instead there's a globalsettings path. There is also profile name and profile-path command line option.

**Comment by DelazJ** [comment]
Yes, this is part of what i refer to as "user profile" description in my mail on the lists. Only the command line part [could be updated](https://github.com/qgis/QGIS-Documentation/pull/2739) at that time

**Comment by SrNetoChan** [comment]
There is a small description below the qgis --help result. I will try to update that.
