### ISSUE TITLE
Update screenshots for "translate" and "array of translated features" algorithms

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#3050]

**Comment by havatv** [comment]
This seems to have been fixed in #2898.
The current illustrations look fine to me (except that both points and polygons are shifted in the illustrations).
Please re-open if improvements are needed (and explain what needs to be improved).

**Comment by DelazJ** [comment]
Actually this was open after #2898 (so could not have fixed it ;) ) because I was not satisfied with the quality of the screenshots I made (too childish IMHO). Why? Dunno...
> The current illustrations look fine to me (except that both points and polygons are shifted in the illustrations).

Why should they not be shifted? Or what do you mean by "shift" ?

**Comment by havatv** [comment]
I thought it would be less confusing if only one layer (so only one geometry type) had its geometry shifted.

**Comment by DelazJ** [comment]
I think the idea was to show that unlike (I think) the offset one, it runs on every geometry type...

**Comment by havatv** [comment]
OK. So perhaps the points could be "translated" in a different direction from the polygons, and then we can explain in the figure caption.
