### ISSUE TITLE
Style manager description may no longer make sense to be on working with vectors

### ISSUE THREAD

**Issue by SrNetoChan** [qgis/QGIS-Documentation#3058]
## Description

Currently, the Style Manager is located inside the Working with vectors section.

https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/style_library.html

Since symbols can be used also in layouts, and color ramps can be used or rasters, I think it would make sense to move the section out of working with vector.

Probably the best place would be the general tools section, which is getting quite large IMHO

https://docs.qgis.org/testing/en/docs/user_manual/introduction/general_tools.html

 or, since the style manager entrance in the settings menu, it could land on QGIS configuration as well:

https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html

## Checklist

- [x] I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage.
If it's related to QGIS application or website, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html
for the right issue tracker or to the [support channels](http://qgis.org/en/site/forusers/support.html)
- [x] I have added a link to the page concerned by the issue

**Comment by SrNetoChan** [comment]
I think I would prefer the QGIS configuration, not sure it needs its own subsection, but would not like to make the general tools bigger.

Let's see what others say.

**Comment by DelazJ** [comment]
> not sure it needs its own subsection, 

It's already the case (it has its own page), and it would be the same as "Custom projections" in the next chapter
> General tools, common widgets?

The general tools chapter is already big and i'd be interested in splitting it (maybe a chapter dedicated to the View --> Panels? but i did not dig more and i'm afraid this will increase resources and build time). 
And i'm less convinced in "common widgets" whose aim was to describe those small buttons you can find in almost every dialog to tweak features and items. 
The style manager is imho a level up.
