### ISSUE TITLE
[mssql][needs-docs] Add connection setting to ignore invalid geometry handling

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3063]
Original commit: https://github.com/qgis/QGIS/commit/dafeaf4372b9e029160438345cce852dbfcf0741 by nyalldawson

Sets whether the connection should skip all handling of records with
invalid geometry, which are slow and costly.

This speeds up the provider, however, if any invalid geometries
are present in a table then the result is unpredictable and may
include missing records. Only check this option if you are certain
that all geometries present in the database are valid, and any newly
added geometries or tables will also be valid!

Why would we want this? Well, SQL Server invalid geometry handling
is AWEFUL. A seriously lame, data mangling and corrupting
piece of s***. Use Postgres instead. But if you can't, then you
can at least choose to use your layers at full speed, if you
can take the responsibility that a SINGLE invalid geometry
hiding somewhere in the table will result in a whole bunch
of missing (valid) features.

SQL server is at fault here, not us. There's nothing we (or
GDAL, or MapServer, or GeoServer, or anyone else) can do
to fix this.

Suffice to say, this option is off by default, as we're better
to have a slow provider which actually shows all features.

Fixes #15752

Rant over

**Comment by tudorbarascu** [comment]
This should be closed as there's nothing to be documented here.

**Comment by DelazJ** [comment]
not sure of that. There's a new checkbox in mssql setting dialog: https://docs.qgis.org/testing/en/docs/user_manual/managing_data_source/opening_data.html#connecting-to-mssql-spatial might need more details then.

**Comment by havatv** [comment]
The tooltips for this and other options in `Create a New MSSQL Connection` are quite good.  Do we need more?
