### ISSUE TITLE
[FEATURE] [needs-docs] Use raster band names in QGIS

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3064]
Original commit: https://github.com/qgis/QGIS/commit/b86f84edb5f40c3bf1275f3f2511b2d315e5f88b by nyalldawson

Extracts band name info using gdalapi in QgsGdalProvider

**Comment by DerLude** [comment]
I assume that this issue relates to [my question](https://gis.stackexchange.com/questions/342351/qgis-feature-generate-band-name-with-netcdf-extra-dim-which-netcdf-attribute) how to make use of the band name feature. Maybe the topic is too specific for the general documentation but I couldn't find any information how to use the band naming at all. Could any of you guys give me an advise, which NetCDF variable/attribute is used for band names?
