### ISSUE TITLE
Typo in Coordinate Reference Systems documentation

### ISSUE THREAD

**Issue by jurentie** [qgis/QGIS-Documentation#3066]
## Description

It appears that the following sentence has a typo in the documentation on line `186` in the file `coordinate_reference_systems.rst`:
> On the other hand, an equal area projection results in** distortions of angular conformity** when dealing with large areas.

It is my assumption that the sentence should be formatted as the following:
"On the other hand, an equal area projection results in **distortions of angular conformity** when dealing with large areas."

[Issue Page](https://github.com/qgis/QGIS-Documentation/edit/master/source/docs/gentle_gis_introduction/coordinate_reference_systems.rst)

## Checklist

- [x] I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage.
If it's related to QGIS application or website, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html
for the right issue tracker or to the [support channels](http://qgis.org/en/site/forusers/support.html)
- [x] I have added a link to the page concerned by the issue

**Comment by DelazJ** [comment]
@jurentie you assume right. A pull-request?

**Comment by DelazJ** [comment]
Closed in #3067
