### ISSUE TITLE
inconsistency between file location and training manual description

### ISSUE THREAD

**Issue by thymaro** [qgis/QGIS-Documentation#3084]
## Description

[vector_data.rst](https://github.com/qgis/QGIS-Documentation/blob/master/source/docs/training_manual/basic_map/vector_data.rst) or training manual page [vector_data.html](https://docs.qgis.org/testing/en/docs/training_manual/basic_map/vector_data.html#basic-fa-loading-vector-data-from-a-database) (I don't know which one I should link to)

contains on lines 93 and 94

```
#. In the main folder of the Training Data, you should find the file
   :file:`landuse.sqlite`. Select it and click :guilabel:`Open`.
```

although **landuse.sqlite** is not in the **main** folder, but in the **shapefiles** folder. Either the file should be moved or the text needs correction to reflect the right location.

## Checklist

- [x] I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage.
If it's related to QGIS application or website, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html
for the right issue tracker or to the [support channels](http://qgis.org/en/site/forusers/support.html)
- [x] I have added a link to the page concerned by the issue

**Comment by DelazJ** [comment]
Good catch! I think it makes sense to place it out of a folder named "shapefiles" as it's not a shapefile.

**Comment by havatv** [comment]
> Good catch! I think it makes sense to place it out of a folder named "shapefiles" as it's not a shapefile.

I would also suggest to rename the "shapefiles" folder to "shapefile", as "shapefile" is the name of the format, and I guess that we are organising according to format.  Any thoughts?

**Comment by DelazJ** [comment]
fixed in https://github.com/qgis/QGIS-Training-Data/pull/13
