### ISSUE TITLE
[needs-docs] Layers panel: Indicators refactoring + bad layers indicator

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3096]
Original commit: https://github.com/qgis/QGIS/commit/ceaaade6a815d5bd76fe5fabe2794b77965f8749 by web-flow

[needs-docs] Indicators refactoring + bad layers indicator

**Comment by elpaso** [comment]
Note to doc writers: the new icon will normally not be visible because there is currently no way to get "bad" layers into a project when loading.

But the indicator is part of a bigger plan for the "bad" layers handling refactoring that will make it possible to keep "bad" layers in a project.

**Comment by DelazJ** [comment]
@elpaso from an end user point of view, is there anything worth documenting in this report? For 3.4? Thanks.

**Comment by elpaso** [comment]
The bad layer handling had a new "deferred" options, I don't know if you have another ticket to handle the whole change, the indicator is just a part of a bigger change.

**Comment by DelazJ** [comment]
> The bad layer handling had a new "deferred" options

Sorry but I don't get what that means.
Opening a project with unavailable layers, I can't see anything in 3.4 dialog different from 2.x period. And can't see a setting anywhere so i'd tend to think that the "Handle bad layers" refactoring is not (yet?) relevant for 3.4 docs.

**Comment by elpaso** [comment]
Oh sorry, you are right, it's for 3.6. So the answer to your question is NO

**Comment by DelazJ** [comment]
OK Thanks.
