### ISSUE TITLE
[needs-docs] Save vector layer as CSV: add STRING_QUOTING create option to the predefined drop-down widgets. 

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3098]
Original commit: https://github.com/qgis/QGIS/commit/f227bfb685abb2ca261f2d73375c70ff9fcd826d by borysiasty

Add STRING_QUOTING (IF_NEEDED|IF_AMBIGUOUS|ALWAYS) to the predefined drop-down widgets. Only available with GDAL >= 2.3 (from that GDAL version the default value changed from IF_NEEDED to IF_AMBIGUOUS, so integer values became double-quoted by default)

**Comment by havatv** [comment]
The user guide does not go into detail on export options.  So I guess this should not be documented.

**Comment by DelazJ** [comment]
@havatv I'd tend to agree on closing. The drop down menu has a tooltip that explains how to use the option so should be good.
On a wider context, [our doc](https://docs.qgis.org/testing/en/docs/user_manual/managing_data_source/create_layers.html#vector-specific-parameters) points to gdal/ogr main page regarding all the layer/data source/custom options you can find in this dialog. If someone knows a more appropriate/accurate page that would help user quicker than browsing the gdal docs to find it, we should better use that link imho.
