### ISSUE TITLE
Merge pull request #8289 from borysiasty/csv_string_quoting

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3099]
Original commit: https://github.com/qgis/QGIS/commit/302529a10c8e5d033588985ed51b1cf7861625dd by web-flow

[needs-docs] Save layer as CSV: add STRING_QUOTING option to the predefined drop-down widgets

**Comment by havatv** [comment]
The user guide does not go into detail on export options.  So I guess this should not be documented.

**Comment by DelazJ** [comment]
Duplicate of #3098
