### ISSUE TITLE
[FEATURE] Add "export to file" options for raster and vector layers
within the browser panel

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3104]
Original commit: https://github.com/qgis/QGIS/commit/7ac521529bfbcc188bc18f9419cb6d971174bca9 by nyalldawson

Allows direct export of these files (e.g. to a different format,
crs, etc) without having to actually load them into a project
first.

**Comment by havatv** [comment]
Fixed (as a side effect) in #4844.
