### ISSUE TITLE
[FEATURE][browser] Restore preview functionality from old 2.x standalone
browser into inbuilt browser dock panel layer properties widget

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3113]
Original commit: https://github.com/qgis/QGIS/commit/17447e4b5ca6cde9e349c55daed558a85766debb by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment]
I guess this has to do with the layer properties opened from the context menu in the browser.
In that case it has been fixed with #4844.
