### ISSUE TITLE
[FEATURE] Show QGIS style xml libraries in browser and support
drag and drop of style .xml files to main QGIS window

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3114]
Original commit: https://github.com/qgis/QGIS/commit/187f74148c0340fa040e21f44efa140fee7857a5 by nyalldawson

Double clicking the databases or dragging them to QGIS
triggers the import from style dialog with the corresponding
input file already selected

**Comment by havatv** [comment]
This is mentioned in chapter 13.1.5 QLR - QGIS Layer Definition File. Should be sufficient. If more is needed, create an issue with a description of where and how.
