### ISSUE TITLE
[FEATURE][processing] New algorithm "Delete duplicates by attribute"

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3116]
Original commit: https://github.com/qgis/QGIS/commit/4e9da6f1906c6ba6076742e9aa3d49bebd1965b6 by nyalldawson

Allows for removal of duplicate features, identified using the values
in one (or more) field values from the input features.

Optionally any discarded (duplicate) features can be saved to a separate
sink.

**Comment by DelazJ** [comment]
To add to https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/vectorgeneral.html
