### ISSUE TITLE
[FEATURE] New form widget for binary (blob) fields

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3151]
Original commit: https://github.com/qgis/QGIS/commit/d96ce7a1d7799221b8a557042593b0a21ca388b5 by nyalldawson

This widget is available for binary fields only (and is the default
widget used for binary fields). It offers a label showing
whether the blob field is empty or not, and if non-empty shows
the content size (in bytes/kb/etc).

A drop down menu button allows users to save the current binary
contents of the field out to a disk based file, clear the contents
of a blob field, or embed binary contents by picking a file
from their system.

**Comment by timlinux** [comment]
See also #3150 and #3149 - I think they can call be addressed here together.

@selmaVH1 we are talking about this workflow:

Layer creation:

![image](https://github.com/qgis/QGIS-Documentation/assets/178003/2e7fa642-4aa5-4678-87b4-50fb59042a5a)


Layer Forms:

![image](https://github.com/qgis/QGIS-Documentation/assets/178003/aa9a6551-5751-4906-98a4-47d78d60a7cd)


![image](https://github.com/qgis/QGIS-Documentation/assets/178003/193282e2-ca0a-4d67-a911-c795e0f31149)

![image](https://github.com/qgis/QGIS-Documentation/assets/178003/ed9c0c74-70f9-4e27-b04d-d1819b44c3e3)
