### ISSUE TITLE
[FEATURE] Title label decoration

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3158]
Original commit: https://github.com/qgis/QGIS/commit/95f69c5de349b8993128cba40c7cb6d83ea5272e by nirvn

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment]
When this feature is documented, remember to make visible the help button in the dialog by removing the text below in the[ src/app/decorations/qgsdecorationtitledialog.cpp](https://github.com/qgis/QGIS/blob/master/src/app/decorations/qgsdecorationtitledialog.cpp) file of the active branches in QGIS repo. 

> // once the documentation for this dialog is added, remove the line below
   buttonBox->button( QDialogButtonBox::Help )->setVisible( false );
