### ISSUE TITLE
[FEATURE][needs-docs]Add buttons to load and save an external SQL file

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3170]
Original commit: https://github.com/qgis/QGIS/commit/4e209724cf4ba361c917d200be67a4aef4de10da by web-flow

[FEATURE][needs-docs]Add buttons to load and save an external SQL file

**Comment by timlinux** [comment]
Closing as relates to dbmanager which should be deprecated right?
