### ISSUE TITLE
[needs-docs] Fix use of duplicate action name

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3176]
Original commit: https://github.com/qgis/QGIS/commit/152b1b09ff0e45b30a72d53904437af032e8659e by nyalldawson

(Properties is already used by project properties)

Comment by havatv: Change of name of an entry (`Properties...` -> `Layer Properties...`) in the top level Layer menu.

**Comment by DelazJ** [comment]
Duplicate of #3188
