### ISSUE TITLE
[needs-docs][FEATURE] Trim/extend

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3180]
Original commit: https://github.com/qgis/QGIS/commit/d1d3a51efbe5a9f138cc7fbc8d36a2842f8ba12e by web-flow

[needs-docs][FEATURE] Trim/extend

**Comment by DelazJ** [comment]
This feature has already [a hidden documentation](https://github.com/qgis/QGIS-Documentation/pull/3173) for post 3.4 release

**Comment by DelazJ** [comment]
fixed in #3343
