### ISSUE TITLE
[Processing R provider] Add section to describe porting of old scripts

### ISSUE THREAD

**Issue by ghtmtt** [qgis/QGIS-Documentation#3194]
## Description

A reminder to add a section on the migration of R scripts from 2.x to 3.x once the plugin is released. Till now issues are R related rather than QGIS, but users that will port their scripts can freak out when they are not working anymore.

Related to https://github.com/north-road/qgis-processing-r/issues/12

**Comment by havatv** [comment]
@ghtmtt, it is my experience, QGIS 2 R scripts can be run in QGIS 3 with the Processing R Provider plugin without any modifications.  So if you have not have problems running QGIS 2 R script in QGIS 3, I guess this issue can be closed.
