### ISSUE TITLE
the main menü Processing is totally disappeared 

### ISSUE THREAD

**Issue by madiraneem** [qgis/QGIS-Documentation#3201]
## Checklist

- [ ] I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage.
If it's related to QGIS application or website, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html
for the right issue tracker or to the [support channels](http://qgis.org/en/site/forusers/support.html)
- [ ] I have added a link to the page concerned by the issue

**Comment by madiraneem** [comment]
Hello QGIS community,
I donot know if I am in the right place to asign my QGIS problem
the problem is that suddenly the main menü Processing dissapeared and the Menü vector has no contents any more I deinstalled Qgis and reinstalled the newest version but tha same problem occured again please help me to find the solution is that ahardware problem??? or somethingelse??
Best Regards
R Madi

**Comment by DelazJ** [comment]
Hi @madiraneem no, you are not at the right place for this issue. Here it's all about [QGIS documentation](https://docs.qgis.org) purpose. Your request would be better served in the qgis user list. More about QGIS support at https://qgis.org/en/site/forusers/support.html
About your issue:
1. go to Plugins menu --> Manage and install plugins
1. in the installed tab, check if there's a Processing entry and click the checbox if it was not in a checked state
1. Close the Plugins dialog and look at the Vector menu again.

**Comment by DelazJ** [comment]
Closing....
