### ISSUE TITLE
The script to clean image folder is broken

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#3205]
With restructuring image folders out of the static folder, the ./scripts/clean_unused_images.sh
script which helped to quickly find and delete unused/deprecated screenshots does no longer seem to work.

**Comment by SrNetoChan** [comment]
When you say it does not look to be working, what do you mean? I have run it, and just deleted a bunch of images on the training part of the documentation.

**Comment by DelazJ** [comment]
euh... with a so poorly detailed report, I can't remember what was the actual problem: I guess it might simply have not returned results while I knew there were unused images (maybe I was on a windows machine?).
Anyway, if you made it work then all is good and we can close this report.

**Comment by DelazJ** [comment]
@SrNetoChan I'm back to this. Looks like one of the issues with the script is that it does not handle translated screenshot (as you can see in #3804 or #3805). I don't know if it did in the past.

**Comment by SrNetoChan** [comment]
Now that I think, probably the script is not working at all. The images were all moved. I will have a look at it asap.
