### ISSUE TITLE
Building QGIS from source (Windows): suggested minor changes

### ISSUE THREAD

**Issue by juanmpd** [qgis/QGIS-Documentation#3206]
I'm trying to build QGIS from source in Windows, following 'INSTALL.txt' / 'doc\INSTALL.html' steps.
I've been stuck for some hours in the steps before getting the MSVC solution file build.
Based on this experience, I suggest some changes to this documentation.

I've read that, theoretically, INSTALL.txt nor doc/INSTALL.html should be directly edited but, instead, one should edit 'doc/INSTALL.t2t'. I was thinking about editing it myself, but I've seen INSTALL.t2t has not been updated in the last 10 months, while INSTALL.txt and doc/INSTALL.html seem to be more updated. So, I've thought it would be better not to edit anything, and simply describe here the proposed changes:

- Chapter 4.1.2, it states to install "qgis-dev-deps" from OSGeo4W. It should also request to install 'oci-devel'. Not doing this ends in:
```
CMake Error at src/providers/oracle/ocispatial/cmake/FindOCI.cmake:39 (MESSAGE):
  Could not find OCI
Call Stack (most recent call first):
  src/providers/oracle/ocispatial/CMakeLists.txt:5 (FIND_PACKAGE)
```

- Chapter 4.1.3. I found Git under Windows showing a lot of files as updated, when they had not actually been edited. Finally I found the solution here: https://stackoverflow.com/questions/5787937/git-status-shows-files-as-changed-even-though-contents-are-the-same/13388544#13388544
So I would suggest also to add this, after the instructions to clone the git repo:

```
And, to avoid Git in Windows reporting changes to files not actually modified:

  git config core.filemode false

```

- And to end, a change of very little relevance: references to "configonly.cmd" might be changed to "configonly.bat"

**Comment by DelazJ** [comment]
@juanmpd doc/INSTALL.t2t is simply a (script?) file that aggregates contents from other parts so normal that it's not updated every day. At the end of that file, there are include calls that list the files to update (in your Windows case, you probably have to update **doc/msvc.t2t**).

INSTALL and doc/INSTALL.html are generated files based on the aggregated contents of doc/INSTALL.t2t.
Hope that helps. And nice to see that there are contributions for Windows builds.

**Comment by juanmpd** [comment]
Thanks @DelazJ 
I just created a pull request with this change (https://github.com/qgis/QGIS/pull/8578)

**Comment by DelazJ** [comment]
Great!
