### ISSUE TITLE
[FEATURE] Add option to force right-hand-rule during polygon symbol rendering

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3207]
Original commit: https://github.com/qgis/QGIS/commit/50cbb2959d0c525ebcd060018a046ca1fb4da51a by nyalldawson

This new option, available under the "Advanced" button for fill symbols,
allows forcing rendered polygons to follow the standard "right hand
rule" for ring orientation (where exterior ring is clockwise, and
interior rings are all counter-clockwise).

The orientation fix is applied while rendering only, and the original
feature geometry is unchanged.

This allows for creation of fill symbols with consistent appearance,
regardless of the dataset being rendered and the ring orientation
of individual features.

Refs #12652

(cherry picked from commit 8269031cc61bf813574bb2f2019bd0b23f58ffcf)

**Comment by havatv** [comment]
Not in 3.4.3.
Option (under Advanced) in the style manager (available from Layer-> Symbology) when selecting a fill symbol.

**Comment by DelazJ** [comment]
> Not in 3.4.3.

Are u sure :thinking:? This commit is 3 weeks older than 3.4.3 and  i can see the option in the place you indicate

**Comment by havatv** [comment]
Not sure, I was switching between computers - I might have been on a master version...
I will check.
