### ISSUE TITLE
[FEATURE] Add option to simple line and marker line to only
render exterior ring or interior rings

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3208]
Original commit: https://github.com/qgis/QGIS/commit/a5b969f27cd2e8e275b45e9c7a2077f3c56f1e08 by nyalldawson

This option is shown whenever a simple line symbol or
marker line symbol is used as part of a fill symbol for
rendering polygons.

The default behavior is to render both interior and exterior
rings, but this new setting allows users to set the symbol
layer to render only for the exterior ring OR only
for interior rings.

This allows for symbolisation which wasn't directly possible
before, such as a marker line with markers for interior
rings angled toward the interior of the polygon.

Sponsored by the German QGIS User Group

Fixes #12652

(cherry picked from commit 4c9537ee64b01e45890c3c1dac596063812276ae)

**Comment by havatv** [comment]
Not in 3.4.3.
Option (available from Layer-> Symbology) when specifying symbol layer type for polygon layers

**Comment by DelazJ** [comment]
>Not in 3.4.3.

I wonder there's an issue with your build or version of QGIS. Could you check you are not on 3.4.2?

**Comment by havatv** [comment]
Not sure, I was switching between computers - I might have been on a master version...
I will check.
