### ISSUE TITLE
Building QGIS from source (Windows): suggested comments to avoid plugins not working

### ISSUE THREAD

**Issue by juanmpd** [qgis/QGIS-Documentation#3209]
Following the steps outlined in "Running QGIS from within MSVC", QGis opens, but some errors are shown, due to python modules not being found. Those errors prevent "processing", "MetaSearch", and "openlayers_plugin" plugins to be properly loaded.
I've found the culprit seems to be the 'site-packages' that comes bundled with OSGeo4W64. Compared to the 'site-packages' folder that the QGis 3.4 standard installation creates, one can see that it seems more outdated, and with less packages.
So far, the workaround I'm succesfully using is simply replace this folder:
   C:\OSGeo4W64\apps\Python37\lib\site-packages
With the contents from:
   C:\Program Files\QGIS 3.4\apps\Python37\Lib\site-packages
I think it would be nice to have the documentation pointing this issue and this (if not other) workaround.

**Comment by DelazJ** [comment]
@juanmpd as mentioned in #3206, this is not the right place to report issues with QGIS; use https://issues.qgis.org instead.
And in case it's not a local issue nor a missing command, I don't think that it has to be handled in QGIS-Documentation repo (btw, the doc does not treat build processes). A mention in the msvc.t2t build documentation (like you did last time) looks more appropriate.

**Comment by juanmpd** [comment]
Sorry!
