### ISSUE TITLE
[needs-docs][processing] Rename "remove duplicates by attribute" to
"delete duplicates by attribute"

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3211]
Original commit: https://github.com/qgis/QGIS/commit/d79cee1fe1108965a1e62922809ff4082dcad018 by nyalldawson

for consistency with "delete duplicate geometries". Also add some
tags to delete duplicate geometries algorithm.

**Comment by DelazJ** [comment]
merged with #3116
