### ISSUE TITLE
[FEATURE][API] Add a content cache for raster images

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3212]
Original commit: https://github.com/qgis/QGIS/commit/84838d1ec6f8499bfb74ca4ecf01fd082517ec98 by nirvn

This new class QgsImageCache is the equivalent of QgsSvgCache
but for raster images.

QgsImageCache stores pre-rendered resampled versions of raster
image files, allowing efficient reuse without incurring the
cost of resampling on every render.

Additionally, it offers the other benefits QgsSvgCache has,
such as thread safety, ability to transparently download remote
images, and support for base64 encoded strings.

**Comment by DelazJ** [comment]
I'd say not doc!
