### ISSUE TITLE
Hi Guys, I got the following error after installing QGIS 3.4, It suddenly got crashed.

### ISSUE THREAD

**Issue by ShivamRai2003** [qgis/QGIS-Documentation#3231]
Crash ID: 769c8bf188bf81a7336e2cc49f088844960187e1

Stack Trace

QList::size :
QgsMessageBar::pushMessage :
QgsMessageBar::pushInfo :
QgisApp::showSystemNotification :
QgisApp::authMessageOut :
QMetaObject::activate :
QgsAuthManager::messageOut :
QgsAuthManager::authDbQuery :
QgsAuthManager::sslCertCustomConfigByHost :
QgsNetworkAccessManager::createRequest :
QNetworkAccessManager::get :
QgsVectorLayerLoadStyleDialog::updateLoadButtonState :
QgsVectorLayerLoadStyleDialog::updateLoadButtonState :
QgisApp::QgisApp :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.4.2-Madeira
QGIS code revision: 22034aa070
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.3.2
Running against GDAL: 2.3.2

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.3.9600

**Comment by havatv** [comment]
You have come to QGIS documentation, and crash reports are not that relevant here.

**Comment by DelazJ** [comment]
@ShivamRai2003 please report your issue at https://issues.qgis.org (check beforehand if not already reported). That's the place for the application bugs, crashes and feature requests. Here, it's only about writing QGIS documentation (https://docs.qgis.org).
