### ISSUE TITLE
[FEATURE][needs-docs] Add new @alg decorator for nicer python processing scripts. (#8586)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3234]
Original commit: https://github.com/qgis/QGIS/commit/87d2da13fbc760f8511316b618ba482062b76544 by web-flow

@alg()
@alg.help()
@alg.input()
@alg.output()

**Comment by havatv** [comment]
This is now covered by the documentation. Closing.
