### ISSUE TITLE
[needs-docs] Use a combo box in layout SVG settings dialog for text export format

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3237]
Original commit: https://github.com/qgis/QGIS/commit/15abbcf86b61684853aa4d8b840584c6483d0e1a by nyalldawson

This makes it match the label engine settings dialog, and opens the possibility
for additional text export modes to be added in future.

**Comment by DelazJ** [comment]
Duplicate of #3240
