### ISSUE TITLE
[needs-docs] Upgrade project level setting for Label as Outlines/text setting to use newer API

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3239]
Original commit: https://github.com/qgis/QGIS/commit/588a5a77a41ef25448abda34913cb4eb1888854c by nyalldawson

And replace labeling engine dialog "Draw text as outlines" checkbox with a combobox
presenting the choice of always rendering as outlines OR text.

(This will allow us to easily add additional methods in future, e.g. potentially
a "Render as text wherever possible" setting, for defaulting to text objects
whenever it doesn't impact the rendering quality to do so)

(cherry picked from commit 52e072c0a1e7d3af89f16bc199d94ff079a49038)

**Comment by havatv** [comment]
Not in 3.4.3.
Changed dialogue:
Layer properties -> Labels -> `Automated placement settings (applies to all layers)` (button)
