### ISSUE TITLE
[needs-docs] Use a combo box in layout SVG settings dialog for text export format

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3240]
Original commit: https://github.com/qgis/QGIS/commit/de18cc790bb77ba1ab63654e35f6328e45831b8f by nyalldawson

This makes it match the label engine settings dialog, and opens the possibility
for additional text export modes to be added in future.

(cherry picked from commit 7b426c047cc720f83585197a5242c09a91c2934a)

**Comment by havatv** [comment]
User manual -> Laying out the maps -> Creating an output -> Export as SVG: Illustration needs to be updated,
as well as the text (a new bullet point for the text export combo box).
