### ISSUE TITLE
[layouts][needs-docs] Add a PDF export settings dialog which is shown
whenever exporting a layout to PDF

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3241]
Original commit: https://github.com/qgis/QGIS/commit/aa1551232c33dba103666dfa5bf93236f2cad1f2 by nyalldawson

This matches the behavior with SVG and raster exports, and allows users
to set specific properties for the export (such as text rendering format)

Fixes #8844

(cherry picked from commit 484d5d9450046188c2799d2a804f6e23c25849b0)

**Comment by havatv** [comment]
For PDF export the dialogue is not shown in the user manual.  So this change does not invalidate it.  We could consider adding an illustration of the export options (as for SVG export).

**Comment by DelazJ** [comment]
There was no dialog for PDF and yes, we could consider adding it.

**Comment by havatv** [comment]
Should be fixed with #4437.
