### ISSUE TITLE
Move value group box under help area [Expression builder] [needs-docs]

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3247]
Original commit: https://github.com/qgis/QGIS/commit/2f7d634e8207b75dbbd116ba96a97128b57c81ef by web-flow

move value group box under help area [Expression builder] [needs-docs]

**Comment by havatv** [comment]
User manual - working with vector data - expressions - List of functions: Update illustration "The expression tab".
User manual - working with vector data - working with the attribute table - Editing attribute values: Update illustration "Field calcuator".

**Comment by DelazJ** [comment]
> User interface only? Only affects illustrations including the expression builder?

No. Text at the end of https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/expression.html#list-of-functions should also be adjusted.
