### ISSUE TITLE
[FEATURE][processing] Add a new parameter type for authentication config

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3252]
Original commit: https://github.com/qgis/QGIS/commit/11ea28a5b3fecf7f541f7404c31fc6fb517c995e by nyalldawson

This adds a new available parameter type for processing algorithms,
QgsProcessingParameterAuthConfig, allowing selection from available
authentication configurations (and creation of new ones).

It allows creation of processing algorithm which can fully take
advantage of QGIS' mature authentication handling, avoiding the
need to use insecure string parameters for users to input
sensitive logon credentials.

QgsProcessingParameterAuthConfig parameters are evaluated using
QgsProcessingAlgorithm.parameterAsString(), which returns the
selected authentication configuration ID.

**Comment by havatv** [comment]
This parameter is described in the documentation (https://docs.qgis.org/testing/en/docs/user_manual/processing/scripts.html). Closing.
