### ISSUE TITLE
[FEATURE][API] Add option to specify a custom boundary geometry
in QgsMapSettings to restrict where labels are allowed to be placed
within.

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3254]
Original commit: https://github.com/qgis/QGIS/commit/4252aabe005c2eacefdaa047e5f27999d21e3703 by nyalldawson

If set, this overrides the default behavior of allowing labels to
be placed anywhere inside the rendered map extent.

**Comment by roya0045** [comment]
I don't think api-only changes should be in the user manual. Or am I wrong?
