### ISSUE TITLE
[FEATURE][API] Add API to set a margin for labels for layout map items

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3255]
Original commit: https://github.com/qgis/QGIS/commit/35855b88e1686ce1f360d6e375ab224efd6a8aa8 by nyalldawson

This controls how close labels are permitted to the edges of the map
item. The labeling engine will then try other candidate positions
in order to avoid placing labels within this margin.

**Comment by DelazJ** [comment]
API. The feature is in #3256
