### ISSUE TITLE
[needs-docs][ux] Remove custom group box styling and option for QGIS styled group boxes

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3259]
Original commit: https://github.com/qgis/QGIS/commit/c8a7e4d69ea09f28f359cae42d5eaf59d5428df6 by nyalldawson

This setting is causing issues on newer operating systems, e.g. MacOS
on dark themes. It's a 6 year old workaround for styling issues
which have likely since been fixed in Qt and the DEs themselves.

(cherry picked from commit 8f06b5a9966c4a7ebbc40d9d57218028e79822b3)

**Comment by havatv** [comment]
Not in 3.4.3.
Update needed for illustrations that show the general tab of the QGIS options (Settings-> Options).  Application part.

**Comment by DelazJ** [comment]
@havatv Afaics color is not concerned by this change. It affects only the "QGIS-styled group boxes" checkbox.

**Comment by havatv** [comment]
Sorry, I only noticed the deletion (not the insertion) of the "Use native color chooser dialogs" option in qgsoptionsbase.ui.
