### ISSUE TITLE
[FEATURE][expression] Enable use of square brackets to access map and array elements

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3267]
Original commit: https://github.com/qgis/QGIS/commit/3490217209b785fb5f74ff82da6c086e6b3a20be by nyalldawson

Allows expressions like:

- array(1,2,3)[0] -> 1
- array(1,2,3)[2] -> 3
- array(1,2,3)[-1] -> 3 (Python style, negative indices count from end of array)
- array(1,2,3)[-3] -> 1
- map('a',1,'b',2)['a'] -> 1
- map('a',1,'b',2)['b'] -> 2

**Comment by DelazJ** [comment]
Add examples at the end of [Arrays](https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/expression.html#array-functions) and/or [Maps](https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/expression.html#maps-functions) expression groups.
