### ISSUE TITLE
[FEATURE][expression] Brand new array_sort() function

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3270]
Original commit: https://github.com/qgis/QGIS/commit/e9e1e0d6f35edc5255b19d2eb4c97ca30c37d701 by web-flow

Unfortunately this naughty coder did not write a description... :-(

**Comment by m-kuhn** [comment]
Expression functions are one of the best documented piece of QGIS.
There shouldn't be a discussion on a per-feature basis if it's appropriate to document but a general decision taken (maybe that has already happened?). All documentation is [available in a structured way](https://github.com/qgis/QGIS/tree/master/resources/function_help/json).

**Comment by havatv** [comment]
In user_manual/working_with_vector/expression.rst, there is a table under "Array functions" that needs to be updated.  Anywhere else?

**Comment by DelazJ** [comment]
> In user_manual/working_with_vector/expression.rst, there is a table under "Array functions" that needs to be updated. Anywhere else?

No.
