### ISSUE TITLE
[FEATURE] A new grayscale theme, "blend of gray"

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3278]
Original commit: https://github.com/qgis/QGIS/commit/304771a583a792117d5e7b35c5f3d22714cc54a0 by nirvn

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment]
It's a new item under Options --> General --> [UI theme](https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html#general-settings) combobox

**Comment by liamseanturner** [comment]
Going to add this to the documentation
