### ISSUE TITLE
[processing][needs-docs] Add cell size parameter to native interpolation algorithms

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3286]
Original commit: https://github.com/qgis/QGIS/commit/84d155eaf0467204aa087b78c8b5d7a0f3d1c9bc by web-flow

[processing][needs-docs] Add cell size parameter to native interpolation algorithms (fix #18556, #20114)

**Comment by havatv** [comment]
user_manual/processing_algs/qgis/interpolation (TIN and IDW).
