### ISSUE TITLE
[processing][needs-docs] Expose resampling and format options in the gdaladdo

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3287]
Original commit: https://github.com/qgis/QGIS/commit/1233a21ac2fbe7931ef9ede09d59179dbf94ae77 by web-flow

[processing][needs-docs] expose resampling and format options in the gdaladdo (fix #20432)

**Comment by DelazJ** [comment]
committed to 3.4 branch as per https://github.com/qgis/QGIS/commit/cee8a205fd70b953d5e769f3f00915900505e277#diff-b7c211451bde6acb886e7c5006b40139 and https://github.com/qgis/QGIS/commit/be60f12e0461ddacf2d38c00cb8e0b0c4533aea4#diff-b7c211451bde6acb886e7c5006b40139
About docs, parameters are already listed (from 2.x I guess). They only need the Optional tag: https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/gdal/rastermiscellaneous.html#gdaloverviews
