### ISSUE TITLE
[FEATURE][API] Add flexible framework for custom "validity checks"

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3291]
Original commit: https://github.com/qgis/QGIS/commit/7ccaa3df3261a73a0c29f69727841acf60902511 by nyalldawson

Adds a new interface QgsAbstractValidityCheck which defines
a single "check" which can be performed on a given QgsValidityCheckContext.
A new application-wide QgsValidityCheckRegistry registers
and manages instances of all known checks, and allows running
of all registered checks of a specific type at once.

Initially the framework is focused toward print layout validity
checks, but the interface has been designed to be generic enough
to allow alternative types of validity checks (e.g. project save
validity checks, processing model validity checks, etc.).

The API is designed to be used both by internal validity checks
and also to be extended by custom, organisation-specific
validity checks. E.g., for print layout validity checks we could have:

**Comment by nyalldawson** [comment]
Related follow up #3350

i think what should be documented here is that when exporting layouts, a number of predefined checks are automatically applied to the layout. Currently these checks include testing that scalebars are correctly linked to map items, and that map overview items are also correctly linked to a map. If the checks fail, users are shown a nice warning advising them of the issue.

#3351 also covers the PyQGIS cookbook documentation for this.
