### ISSUE TITLE
[processing][needs-docs] Standardize names of z/m value algorithms

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3296]
Original commit: https://github.com/qgis/QGIS/commit/d59a34656086097b2e41ecf0ae230f6578d417c7 by nyalldawson

Ensures consistent capitalization and (non)hyphenation of algorithm names

**Comment by havatv** [comment]
Only change is m-value -> M value and z-value-> Z value (in display names, descriptions and short help).
Not sure how much the documentation is affected.
