### ISSUE TITLE
Add comment option on db_manager pluging postgis tables (#8734) [FEATURE]

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3305]
Original commit: https://github.com/qgis/QGIS/commit/ed9c9b33af4fd368581bdb57ec967c59220599b1 by m-kuhn

Add possibility to create a comment on a postgres table when import or using the alter table button from db_manager.

**Comment by havatv** [comment]
The comment can be manipulated (Add comment / Delete comment) in DB Manager (*Table-> Edit table*; Comment tab). Must have sufficient DB rights.
