### ISSUE TITLE
[FEATURE]: Possibility to set ATLAS_PK in GetPrint request to print atlas sheet(s)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3309]
Original commit: https://github.com/qgis/QGIS/commit/21e3adfbcac4ffa339b28a4fb5fefc3a704bd2fb by mhugent

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment]
It would be nice to get some more information about where and how this should be documented.
Does it have something to do with making WMS layer rendering in Atlases dependent on more than the atlas feature location.

**Comment by DelazJ** [comment]
Fixed in #3349
