### ISSUE TITLE
TM 4.3.3 mentions farm which is not in the example data

### ISSUE THREAD

**Issue by janneke-qgis** [qgis/QGIS-Documentation#3314]
## Description
Farm is mentioned referring to earlier exercises that do not exist anymore

## Checklist

- [ x] I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage.
If it's related to QGIS application or website, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html
for the right issue tracker or to the [support channels](http://qgis.org/en/site/forusers/support.html)
- [x ] I have added a link to the page concerned by the [issue](https://docs.qgis.org/testing/en/docs/training_manual/vector_classification/classification.html?highlight=farm)

**Comment by havatv** [comment]
Seems to have been fixed. Can't find "farm" in 4.3.3 (Follow Along: Ratio Classification).
