### ISSUE TITLE
TM 6.1.1. update screen shot

### ISSUE THREAD

**Issue by janneke-qgis** [qgis/QGIS-Documentation#3316]
## Description
Current version has drop down for type, not radio buttons

## Checklist

- [ x] I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage.
If it's related to QGIS application or website, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html
for the right issue tracker or to the [support channels](http://qgis.org/en/site/forusers/support.html)
- [x ] I have added a link to the page concerned by the [issue](https://docs.qgis.org/testing/en/docs/training_manual/create_vector_data/create_new_vector.html#basic-fa-the-layer-creation-dialog)

**Comment by havatv** [comment]
This has been fixed.
