### ISSUE TITLE
TM 6.1.2 change Add Raster Layer button to Add Layer button

### ISSUE THREAD

**Issue by janneke-qgis** [qgis/QGIS-Documentation#3317]
## Description
It might not be clear that the Add Raster Layer button can only be found after clicking the Add Layer button and that it's now called Raster

## Checklist

- [x ] I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage.
If it's related to QGIS application or website, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html
for the right issue tracker or to the [support channels](http://qgis.org/en/site/forusers/support.html)
- [x ] I have added a link to the page concerned by the [issue](https://docs.qgis.org/testing/en/docs/training_manual/create_vector_data/create_new_vector.html#basic-fa-data-sources)

**Comment by havatv** [comment]
Has been fixed.
