### ISSUE TITLE
TM 8.1.2 Use visible raster layers for input not available anymore

### ISSUE THREAD

**Issue by janneke-qgis** [qgis/QGIS-Documentation#3323]
## Description
The tool Build Virtual Raster now needs you to click on the ellipse to select the rasters that you want to form into a virtual raster

## Checklist

- [x ] I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage.
If it's related to QGIS application or website, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html
for the right issue tracker or to the [support channels](http://qgis.org/en/site/forusers/support.html)
- [x ] I have added a link to the page concerned by the [issue](https://docs.qgis.org/testing/en/docs/training_manual/rasters/data_manipulation.html#basic-fa-create-a-virtual-raster)

**Comment by janneke-qgis** [comment]
Yes, indeed, addressed in #3168 so can be closed again.

**Comment by DelazJ** [comment]
Thanks
