### ISSUE TITLE
TM 8.3.1 and further: DEM tools now directly under Raster analysis

### ISSUE THREAD

**Issue by janneke-qgis** [qgis/QGIS-Documentation#3324]
## Description
All terrain tools are now directly under Raster analysis and no longer under DEM (Terrain models)

## Checklist

- [x ] I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage.
If it's related to QGIS application or website, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html
for the right issue tracker or to the [support channels](http://qgis.org/en/site/forusers/support.html)
- [x ] I have added a link to the page concerned by the [issue](https://docs.qgis.org/testing/en/docs/training_manual/rasters/terrain_analysis.html#basic-fa-calculating-a-hillshade)

**Comment by janneke-qgis** [comment]
I take it these changes are not yet online? What is the easiest way for 
me to see these changes? I'm not so familiar with git...

**Comment by DelazJ** [comment]
> I take it these changes are not yet online?

Yes they aren't published yet. They are in the review process. So any inputs are welcome.
> What is the easiest way for me to see these changes?

1. Go to https://github.com/qgis/QGIS-Documentation/pull/3202/files and press the `View file` button next to the "terrain_analysis" file to see it in situation.
1. If there are part you would like to comment, go to https://github.com/qgis/QGIS-Documentation/pull/3202/files and press `load diff` for the same file and add your comment/suggestion where you feel it's needed.

**Comment by janneke-qgis** [comment]
If I understand it correctly, the whole 'current' published chapter 8 is replaced by the
3 PRs [Training Manual] 1/3 Chapter 8 (Raster), 2/3 and 3/3? That all worked (one minor exception with the raster calculator) - so indeed that means that this one can be closed too.

**Comment by ghtmtt** [comment]
fixed in c852a84de2b9d2332f95ff030fe13a53d7f69756
