### ISSUE TITLE
TM 9.3.2 data not available

### ISSUE THREAD

**Issue by janneke-qgis** [qgis/QGIS-Documentation#3326]
## Description
Data are not available from the dropbox link, maybe this is an old problem? I seem to remember reading about it - if it is old, then it's now back

## Checklist

- [x ] I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage.
If it's related to QGIS application or website, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html
for the right issue tracker or to the [support channels](http://qgis.org/en/site/forusers/support.html)
- [ x] I have added a link to the page concerned by the [issue](https://docs.qgis.org/testing/en/docs/training_manual/complete_analysis/analysis_exercise.html)

**Comment by Sitsketw** [comment]
I found the data available on https://www.dropbox.com/sh/n7kzrv7b8fzprxp/AABrvs2LQdNdJrCsC1VA3stMa?dl=0
It worked for me.
I found the data on administrative boundaries on https://www.diva-gis.org/datadown; the layer ZAF_adm2 contains the missing admininstrative boundaries (districts). CRS has to be changed though

**Comment by havatv** [comment]
Fixed with #5461.
