### ISSUE TITLE
TM 11.1.1 on the fly not available anymore

### ISSUE THREAD

**Issue by janneke-qgis** [qgis/QGIS-Documentation#3327]
## Description
the on the fly check box does not exist anymore, I don't know if the 'no projection' check box is the same. It will need to be adjusted in the text at https://docs.qgis.org/3.4/en/docs/training_manual/online_resources/wms.html#basic-fa-loading-a-wms-layer

## Checklist

- [ x] I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage.
If it's related to QGIS application or website, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html
for the right issue tracker or to the [support channels](http://qgis.org/en/site/forusers/support.html)
- [x ] I have added a link to the page concerned by the [issue](https://docs.qgis.org/testing/en/docs/training_manual/online_resources/wms.html#basic-fa-loading-a-wms-layer)

**Comment by havatv** [comment]
The "Project properties" illustration needs to be replaced to reflect the 3.4 UI.
The "on the fly" phrases will have to be changed according to the new "terminology" ("No projection (or unknown/non-Earth projection"). Three instances?

**Comment by havatv** [comment]
I did not change "on-the-fly", but made some changes to reflect the 3.4 UI. The illustration has been updated.
