### ISSUE TITLE
11.1.4 using spatineo to search for WMS did not work

### ISSUE THREAD

**Issue by janneke-qgis** [qgis/QGIS-Documentation#3329]
## Description
Again not sure if this is due to limited internet connection, but I could not find any layer through that link. If it is just me then these can just be closed again
https://docs.qgis.org/testing/en/docs/training_manual/online_resources/wms.html#hard-ty

## Checklist

- [x] I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage.
If it's related to QGIS application or website, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html for the right issue tracker or to the [support channels](http://qgis.org/en/site/forusers/support.html)
- [x] I have added a link to the page concerned by the issue

**Comment by kannes** [comment]
This can be closed. The site is not super intuitive but it works fine.
