### ISSUE TITLE
TM 13.2.3 r.info should be r.reclass

### ISSUE THREAD

**Issue by janneke-qgis** [qgis/QGIS-Documentation#3332]
## Description
"look for the r.info module" should be "look for the r.reclass module"

## Checklist

- [x ] I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage.
If it's related to QGIS application or website, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html
for the right issue tracker or to the [support channels](http://qgis.org/en/site/forusers/support.html)
- [x ] I have added a link to the page concerned by the [issue](https://docs.qgis.org/testing/en/docs/training_manual/grass/grass_tools.html#moderate-fa-the-reclass-tool)

**Comment by ghtmtt** [comment]
@janneke-qgis yes I think this is not a duplication. Chapter 13 uses GRASS r.reclass while in chapter ( we are using native reclass tool of QGIS. 

I'm closing this issue, don't hesitate to reopen or add other comments! Thanks for reviewing the manual

**Comment by janneke-qgis** [comment]
If this is not a duplication this issue should remain open (as it would remain in 13.2.3)

**Comment by janneke-qgis** [comment]
How can I reopen it? Or should someone else do that?

**Comment by ghtmtt** [comment]
By "it is not a duplication" I meant that it is OK to have both reclassify example in different chapters

**Comment by ghtmtt** [comment]
fixed in fcb0680

**Comment by janneke-qgis** [comment]
The issue at hand is not that it is a duplication, but that the text refers to r.info, where it is supposed to refer to r.reclass, so if the exercise is not removed from chapter 13, this text needs to be updated - whence it shouldn't be closed. If it had been a duplicate, the text wouldn't need to be changed and the issue could be closed.

**Comment by janneke-qgis** [comment]
pfffff - yes! I'm sorry it's taking me very long to find my way through all the files and tabs, not being quite sure if I'm looking at the latest version at the right place...I'll get there. So yes, that latest patch includes it. Thanks!
