### ISSUE TITLE
[FEATURE][georefencer] Make minimizing georeferencer when adding points
from canvas an option

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3335]
Original commit: https://github.com/qgis/QGIS/commit/6ed0b4762f1777bbdedc2a4ffa61f26d461eab74 by nyalldawson

Allows users to disable this option, which is annoying on multi-monitor
setups where it can be desirable to have both windows visible while
adding points.

The option is added as a checkbox in the "add map coordinates" dialog:
"Automatically hide georeferencer window". We show it directly in that
dialog for maximum discoverability, and to allow easier change of setting
for users who move between single/multi monitor setups.

Fixes #20449

**Comment by roya0045** [comment]
I don't think this is worth documenting.

**Comment by roya0045** [comment]
@DelazJ Do you think this should be closed?
