### ISSUE TITLE
Add NULLIF expression function [FEATURE]

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3338]
Original commit: https://github.com/qgis/QGIS/commit/af027d9d102191229a2b5e26b827ac18df85f6ba by m-kuhn

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment]
API only?

**Comment by Gustry** [comment]
It should go in https://github.com/qgis/QGIS-Documentation/blob/master/source/docs/user_manual/working_with_vector/expression.rst#conditional-functions

**Comment by havatv** [comment]
Thanks!
