### ISSUE TITLE
[FEATURE][API] Add method to QgsDistanceArea to split a (multi)line geometry
at the antimeridian

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3356]
Original commit: https://github.com/qgis/QGIS/commit/a8bd12c4e39406f561738c397685b6a75e787401 by nyalldawson

Whenever line segments in the input geometry cross the antimeridian, they
will be split into two segments, with the latitude of the breakpoint being
determined using a geodesic line connecting the points either side of this
segment.

If the geometry contains M or Z values, these will be linearly interpolated
for the new vertices created at the antimeridian.

**Comment by DelazJ** [comment]
Not sure we have anything to document here

**Comment by havatv** [comment]
Me neither.

**Comment by DelazJ** [comment]
Great! Closing...
