### ISSUE TITLE
[FEATURE] Add "All" tab to style manager

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3360]
Original commit: https://github.com/qgis/QGIS/commit/180bb6a43eda8ac2ee7b0e594cf39cbe52547bf1 by nyalldawson

This allows you to see ALL the symbols/ramps matching the current
group/tag/filter. It makes it easier to manage groups which consist
of both markers/lines and fills.

**Comment by DelazJ** [comment]
Should be mentioned at https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/style_library.html#organizing-symbols-and-color-ramps

**Comment by lajunek** [comment]
@DelazJ @SrNetoChan @havatv I will mention the new feature

**Comment by lajunek** [comment]
@DelazJ does this mean that the menu `All` in the `Organizing symbols and color ramps` should be extended? Are we talking about this feature?

**Comment by DelazJ** [comment]
Hi Larissa. It's about this tab 
![image](https://user-images.githubusercontent.com/7983394/60684285-16bc3d00-9e9d-11e9-9be7-01ca797b5cb4.png)
The `All` that is currently documented is the one in the left panel (under `Favorites`), and shows all the items within the active tab. So it's a bit different.

**Comment by lajunek** [comment]
@DelazJ I wonder if it's good idea to place a screenshot and a description at the end of the chapter, with a text like `Finally you can find all your matching symbols in the tab All. Here all kinds of symbols are listed`. Something like this. Another suggestion?

**Comment by DelazJ** [comment]
@lajunek I think the (updated version of the) screenshot at the top beginning of the page should be enough here. aka the one I added yesterday.
And about the text, the first sentence of the above-mentioned section already lists the tabs. So I think the list only needs to be extended with the new tabs. You can indeed add more details to the All tab.

**Comment by lajunek** [comment]
@DelazJ I tried to replace the screenshot in #3988 ; right procedure?

**Comment by DelazJ** [comment]
> @DelazJ I tried to replace the screenshot in #3988 ; right procedure?

I think you maybe wanted to add the comment in #3746 
This issue was fixed in #3986, hence I'm closing it (I'll answer in the appropriate PR).
