### ISSUE TITLE
[feature] [3d] [mesh] Display mesh faces in 3D view as terrain

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3366]
Original commit: https://github.com/qgis/QGIS/commit/d695c4b34bf92ea350b09b45176c81962b14c385 by PeterPetrik

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment]
@PeterPetrik same question: this GUI is no longer in QGIS, right?

**Comment by DelazJ** [comment]
Looking into the code PR, the GUI does not exist anymore for mesh 3d, but for vector layer, and is described in he style manager. Also we already state that mesh layer can be used as terrain in 3D Map view settings so closing
