### ISSUE TITLE
[feature] Add expression for square by diagonal and rectangle from 3 points

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3368]
Original commit: https://github.com/qgis/QGIS/commit/aaede28b4366fd3f639e45581b88b9c07913fbf0 by nyalldawson

With the new class QgsQuadrilateral, we can add expressions to create a square by a diagonal and rectangles by 3 points

**Comment by DelazJ** [comment]
Fixed in #4221
