### ISSUE TITLE
[FEATURE] New expression variables for legend items

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3373]
Original commit: https://github.com/qgis/QGIS/commit/b43943a9b0171f2313e45adf30e8b55ff9474700 by nyalldawson

Adds new variables for use in data defined expressions for layout legend items, including

- @legend_title
- @legend_column_count
- @legend_split_layers
- @legend_wrap_string
- @legend_filter_by_map
- @legend_filter_out_atlas

Additionally, if the legend is linked to a map, then expressions used in that legend will also have access to the linked variables, including @map_scale, @map_extent, etc.

**Comment by DelazJ** [comment]
default addition to https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/expression.html#variables-functions and mention + example of usage somewhere in https://docs.qgis.org/testing/en/docs/user_manual/print_composer/composer_items/composer_legend.html
