### ISSUE TITLE
[processing][needs-docs] force multipart output from GDAL-based dissolve
algorithm (fix #20025)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3395]
Original commit: https://github.com/qgis/QGIS/commit/32f6034be708b305ed4e19b4f6ade1a8b409993b by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment]
Duplicate of #3396
