### ISSUE TITLE
[processing][needs-docs] force multipart output from GDAL-based dissolve
algorithm (fix #20025)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3396]
Original commit: https://github.com/qgis/QGIS/commit/f8893d769b05dac137a8623863cecd27ad8fcf67 by nyalldawson

(cherry picked from commit 32f6034be708b305ed4e19b4f6ade1a8b409993b)

**Comment by havatv** [comment]
GDAL is not documented anywhere in user manual or the training manual. I suggest we close it. What do you say @DelazJ

**Comment by DelazJ** [comment]
We have https://docs.qgis.org/3.4/en/docs/user_manual/processing_algs/gdal/index.html (not complete btw)

**Comment by havatv** [comment]
OK. We can leave it as input for the documentation of the GDAL Dissolve algorithm (it has not yet been documented).  I may start documenting GDAL algorithms soon (there are many that have not yet been documented). Perhaps I should start with Dissolve... :-)
