### ISSUE TITLE
[processing][needs-docs] native vector split algorithm now outputs
GeoPackages instead of shapefiles (refs #20557)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3409]
Original commit: https://github.com/qgis/QGIS/commit/8446d3bdf0089cdee6316e40a7cd0047dbf455c1 by nyalldawson

Also remove default output extension Processing settings as they are not
used anymore.

**Comment by havatv** [comment]
Fixed by #4144.
