### ISSUE TITLE
[processing][needs-docs] Add friendlier API for running algorithms as sub-steps
of main algorithm

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3410]
Original commit: https://github.com/qgis/QGIS/commit/7f7c7a97899637f59ceb76f30abbec6ba924bec6 by nyalldawson

Using code like:

    buffered_layer = processing.run(..., context, feedback)['OUTPUT']
    ...
    return {'OUTPUT': buffered_layer}

can cause issues if done as a sub-step of a larger processing algorithm. This
is because ownership of the generated layer is transferred to the caller
(Python) by processing.run. When the algorithm returns, Processing
attempts to move ownership of the layer from the context to the caller,
resulting in a crash.

(This is by design, because processing.run has been optimised for the
most common use case, which is one-off execution of algorithms as part
of a script, not as part of another processing algorithm. Accordingly
by design it returns layers and ownership to the caller, making things
easier for callers as they do not then have to resolve the layer reference
from the context object and handle ownership themselves)

This commit adds a new "is_child_algorithm" argument to processing.run.
For algorithms which are executed as sub-steps of a larger algorithm
is_child_algorithm should be set to True to avoid any ownership issues
with layers. E.g.

    buffered_layer = processing.run(..., context, feedback, is_child_algorithm=True)['OUTPUT']
    ...
    return {'OUTPUT': buffered_layer}

**Comment by DelazJ** [comment]
@havatv just to indicate that this is a 3.6 feature... :)

**Comment by havatv** [comment]
Thanks. This time I was actually aware of it, so I was not planning to work on this now. ;-)

**Comment by DelazJ** [comment]
You can work on this now...

**Comment by DelazJ** [comment]
@havatv This one can be closed, right?

**Comment by havatv** [comment]
The features is used in the code, but I am not sure that it is sufficiently documented (probably only as comments in Python code).

**Comment by DelazJ** [comment]
Closing. Explanation of the is_child_algorithm has been added in the text (not only as code comment) meanwhile ( [here](https://docs.qgis.org/3.16/en/docs/user_manual/processing/console.html?highlight=is_child_algorithm#creating-scripts-and-running-them-from-the-toolbox) or [here](https://docs.qgis.org/3.16/en/docs/user_manual/processing/scripts.html?highlight=is_child_algorithm#extending-qgsprocessingalgorithm))

**Comment by anitagraser** [comment]
For future reference, ScriptTemplate.py in the QGIS main repo (https://github.com/qgis/QGIS/blob/391dfd0c99c7f91d1f8370fdf06e7d7c11bf6ed8/python/plugins/processing/script/ScriptTemplate.py) does not use `is_child_algorithm` for reasons being discussed in https://github.com/qgis/QGIS/pull/46851#issuecomment-1015046254
