### ISSUE TITLE
[processing][needs-docs] allow to exclude features without category from GRASS export

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3414]
Original commit: https://github.com/qgis/QGIS/commit/662af5cf791141b3ffa851ffe61900ba930819fe by web-flow

[processing][needs-docs] allow to exclude features without category from GRASS export

**Comment by DelazJ** [comment]
I suggest we close this one as we do not document GRASS algorithms parameters

**Comment by DelazJ** [comment]
Agreeing with myself....
