### ISSUE TITLE
OGR: add a download option to the protocol data source [needs-docs]

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3437]
Original commit: https://github.com/qgis/QGIS/commit/0557c70034c6b603ab7e8c6c0f4881587fe0e84b by nyalldawson

OGR: add a download option to the protocol data source [needs-docs]

Cherry-picked from master 1f8708f270

**Comment by DelazJ** [comment]
Duplicate of #3404
