### ISSUE TITLE
--config path no longer works in 3.4.4

### ISSUE THREAD

**Issue by Hoyle101** [qgis/QGIS-Documentation#3440]
## Checklist

- [ ] I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage.
If it's related to QGIS application or website, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html
for the right issue tracker or to the [support channels](http://qgis.org/en/site/forusers/support.html)
- [ ] I have added a link to the page concerned by the issue

**Comment by DelazJ** [comment]
Hi @Hoyle101 
Can you better explain what the issue is? configpath is indeed a 2.x option so it's normal it does not work in 3.x (you should give a look to the replacement options at https://docs.qgis.org/2.18/en/docs/user_manual/introduction/getting_started.html#command-line-options). Otherwise, did you find a mention of --configpath in the current docs?

**Comment by Hoyle101** [comment]
Hi,

After further digging i did find what changed for 3.x.

No longer is --config path used,  instead its --profiles path


Thank you for following up, I'd like to have qgis update the 3.x
documentation with this info, as it wasn't listed on thier site docs.

**Comment by DelazJ** [comment]
> I'd like to have qgis update the 3.x documentation with this info, as it wasn't listed on thier site docs

Isn't it listed in the link I provided in my previous comment? Or where would you expect to find the information?

**Comment by Hoyle101** [comment]
That's a doc for 2.18.

The switch listed there for external installation media is no longer
operational in 3.x.

There is limited documentation for 3.x, and i could not find anywhere what
the replacement switch was. Again, it's now changed to --profiles path

This answer was actually found on a gis website.

**Comment by DelazJ** [comment]
> That's a doc for 2.18.

Check it again;  the first message had a 2.18 link but it has been edited few minutes later, showing the actual link for 3 (https://docs.qgis.org/testing/en/docs/user_manual/introduction/getting_started.html#advanced-command-line-options).

>  The switch listed there for external installation media is no longer operational in 3.x.

[Indeed](https://docs.qgis.org/testing/en/docs/user_manual/introduction/getting_started.html#installing-on-external-media).  A fix is proposed at #3445
