### ISSUE TITLE
Vertex tool updates in 3.4 and 3.6

### ISSUE THREAD

**Issue by wonder-sk** [qgis/QGIS-Documentation#3450]
This is a summary of all recent improvements done for 3.4.5 and 3.6:

### Select ("lock") feature before editing

In QGIS 2.18 you always had to select a feature first before editing it. In QGIS 3 there was no such thing - editing would be done on any feature any time. Now we are making the selection of feature ("lock") available again - using **right click**.

In earlier QGIS 3 versions, right click on a feature would bring up a small popup menu that offers display of vertex editor. **Now, right click on a feature will immediately show the vertex editor and disable editing of any other features.**

When a feature is "locked", it can be again unlocked by clicking on it or by clicking on an empty area - this will bring us back to the default mode when multiple features can be edited.

**When there are multiple features in one mouse location, repeated right clicks will loop over them** - with every right click you will lock to a different feature. Finally when all features have been offered, no feature will be locked and further right clicks will start the loop again.

The locking is possible when clicking a feature's vertex, edge or interior (for polygons).

### Add new vertex without moving it

It is now possible to use **Shift + double click to add a new vertex without placing it to a new location**. Sometimes this is useful when users want to add extra vertices on the existing segments.

### "Current layer" mode is now the default

From the two modes of vertex tool, "all layers" used to be the default one. But from the user feedback that seemed like less common case and users prefer to have "current layer" as the default.

**Comment by wonder-sk** [comment]
cc @bstroebl @nirvn @3nids 

Pending improvements (to arrive probably also to 3.4.x and 3.6.x) - synchronization of selection of vertices between vertex editor panel and map canvas.

**Comment by nirvn** [comment]
Worth expending on the "locked" state: when in locked state, vertex highlights and selection (dragging or clicking) will only show / select vertices from the selected feature. 

That's worth highlighting as it was a recurring complaint I often heard.

**Comment by bstroebl** [comment]
@nirvn  I agree
Proposed text: In earlier QGIS 3 versions, right click on a feature would bring up a small popup menu that offers display of vertex editor. Now, right click on a feature will immediately show the vertex editor and lock this feature thus disabling the editing of any other features. While being locked a feature is exclusive for editing: Selecting and moving of vertices and segments by clicking or dragging is only possible for this feature. New vertices can only be added to the locked feature.

**Comment by nirvn** [comment]
Also, the vertex editor panel now opens itself automatically upon activating the vertex tool, and its position/docked state remembered across uses.

**Comment by lajunek** [comment]
I will insert a text about the above mentioned feature

**Comment by SrNetoChan** [comment]
Great example of developers providing enough information for documentation team to pick it up. Thanks @wonder-sk et al.
