### ISSUE TITLE
[FEATURE][expressions] Simplified variant of "attribute" function

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3456]
Original commit: https://github.com/qgis/QGIS/commit/db1a1929a41d0ac44e5679627f1db49c426182d0 by nyalldawson

This adds a second variant for the existing "attribute" function.
The current function requires both a target feature and attribute
name to be specified, while the NEW variant just uses the current
feature.

E.g.

NEW:

attribute( 'name' ) -> returns the value stored in 'name' attribute
for the current feature

EXISTING:

attribute( @atlas_feature, 'name' ) -> returns value stored in 'name'
attribute for the current atlas feature

It's just a faster shorthand version!

**Comment by DelazJ** [comment]
The current description should be enough to cover this alternative. and anyways, we do not document functions in details so I think we can close this one
