### ISSUE TITLE
[FEATURE][processing] Allow expression variables to be set for a model

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3458]
Original commit: https://github.com/qgis/QGIS/commit/c1aac3228c44f5add412be77a5221af34fd1a671 by nyalldawson

This adds a new "Model Variables" dock panel to the model editor, allowing
users to create and set custom expression variables for use in the model.
These variables are available anywhere expressions are (correctly) evaluated
within the model, so can be used as input parameter values for child
algorithms, within data-defined dynamic parameters, etc.

The use case here is for models which use a constant value throughout
multiple steps within the model (e.g. @target_resolution: a target
raster resolution, @max_simplification: a simplification value for
input features coming from different sources, etc), allowing users
one single place to define and edit these constant values (instead
of hunting down and setting them in multiple places throughout the model).

These variables are stored within the model itself, and are not exposed
outside of the model designer dialog.

**Comment by roya0045** [comment]
@DelazJ This seems to be already in the documentation, I suggest closing this.

**Comment by DelazJ** [comment]
Can we expand a bit on this one (how, when, use-case), please? It does not look obvious imho

**Comment by roya0045** [comment]
@DelazJ No problem!
