### ISSUE TITLE
Vector Layers page of pyqgis_developer_cookbook needs updating to Python3

### ISSUE THREAD

**Issue by ianturton** [qgis/QGIS-Documentation#3465]
## Description

The [vector page ](https://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/vector.html#modifying-vector-layers) of the pyqgis_developer_cookbook needs to be updated.

## Checklist

- [x] I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage.
If it's related to QGIS application or website, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html
for the right issue tracker or to the [support channels](http://qgis.org/en/site/forusers/support.html)
- [x] I have added a link to the page concerned by the issue

**Comment by ianturton** [comment]
See PR https://github.com/qgis/QGIS-Documentation/pull/3451

**Comment by Gustry** [comment]
Small note, as written in the issue template guideline, you need to **replace** the space by an `x` ;-)
