### ISSUE TITLE
[feature][needs-docs] Store projects into geopackage

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3495]
Original commit: https://github.com/qgis/QGIS/commit/60942cdf84c2f74b00d1fb666deb88d7b9b3fd88 by elpaso

Store and load QGIS projects to/from geopackage.

(This is the same functionality previously available
only for postgis)

**Comment by felixfeckler** [comment]
Documented and fixed by #4736
