### ISSUE TITLE
Wrong links to PyQGIS API doc

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#3504]
Browsing the https://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/vector.html#writing-vector-layers link, it seems that many classes return a 404 because of an intermediate "section" in the link, eg
1. QgsCoordinateReferenceSystem: https://qgis.org/pyqgis/3.4/core/Coordinate/QgsCoordinateReferenceSystem.html#qgis.core.QgsCoordinateReferenceSystem instead of https://qgis.org/pyqgis/3.4/core/QgsCoordinateReferenceSystem.html#qgis.core.QgsCoordinateReferenceSystem
1. QgsVectorLayer: https://qgis.org/pyqgis/3.4/core/Vector/QgsVectorLayer.html#qgis.core.QgsVectorLayer instead of https://qgis.org/pyqgis/3.4/core/QgsVectorLayer.html#qgis.core.QgsVectorLayer
1. QgsVectorFileWriter: https://qgis.org/pyqgis/3.4/core/Vector/QgsVectorFileWriter.html#qgis.core.QgsVectorFileWriter instead of https://qgis.org/pyqgis/3.4/core/QgsVectorFileWriter.html#qgis.core.QgsVectorFileWriter

Browsing randomly some other pages, I did not find a single working link.

**Comment by DelazJ** [comment]
Thanks to whoever fixes the redirection. 
What remains now is to make testing doc open master's and not 3.4

**Comment by SrNetoChan** [comment]
@DelazJ so the links are working now?

**Comment by DelazJ** [comment]
A kind of. They all point to 3.4 pyqgis API while link on testing branch should imho open master API

**Comment by SrNetoChan** [comment]
Fixed :-)

**Comment by DelazJ** [comment]
Thanks
