### ISSUE TITLE
New branch release requirements

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#3507]
There are some mandatory cleanups to do when releasing a new branch and i don't know if there are available somewhere nor where they could be put, so i'm listing them here (i'll take 3.4 as example):

- [x] Mention in the readme the new current release (for both 3.4 and master branches)
- [x] Move in the [main front page](https://www.qgis.org/en/docs/index.html) the previous release to the archives section
- [x] Redirect appropriate application releases to corresponding branch, ie QGIS 3.0/3.2/3.4 help buttons point to 3.4 branch while master/3.6/3.8/3.10 (we can prepare it now avoiding complaints from quick testers at release time) point to testing doc
- [x] Update the release mention in the [what's new](https://docs.qgis.org/testing/en/docs/user_manual/preamble/whats_new.html)  chapter, for master --- i really wonder if this chapter could be merged with an [updated](https://github.com/qgis/QGIS-Documentation/issues/2286) [Features chapter](https://docs.qgis.org/testing/en/docs/user_manual/preamble/features.html) 
- [x] Remove the update disclaimer mention on top of all the pages, in 3.4. Up to now, we were disabling it in the conf.py, leading to some (ugly) signs on top of the pages (see \`\` in 2.18 docs header)
- [x] Remove the |32|, |34| tags next to functions and algorithms --- in both branches, right? We assume that the 3.4 doc is intended to QGIS 3.4 users?
- [ ] Remove the doc in progress mention inside the released cookbook

i know @rduivenvoorde already takes care of most of these points (and i'm pretty sure i forget some) but it may be good to acknowledge everyone of what has to be done and if we can share the workload... I think that the last three issues are mainly writing issues (something any of us could do) and if we can get a script that does that, it would be great (actually the reason of this report, manual cleaning could be a nightmare)

**Comment by ghtmtt** [comment]
> Mention in the readme the new current release (for both 3.4 and master branches)
 done in f08e797

> Move in the main front page the previous release to the archives section
> Redirect appropriate application releases to corresponding branch, ie QGIS 3.0/3.2/3.4 help buttons point to 3.4 branch while master/3.6/3.8/3.10 (we can prepare it now avoiding complaints from quick testers at release time) point to testing doc

done in https://github.com/qgis/QGIS-Website/pull/604

**Comment by ghtmtt** [comment]
> Update the release mention in the what's new chapter, for master --- i really wonder if this chapter could be merged with an updated Features chapter

done in https://github.com/qgis/QGIS-Documentation/pull/3515 not merged the chapters as you suggested, but in the meanwhile it is good to have the correct links to the correct versions

**Comment by DelazJ** [comment]
Closing this. Was targeting a specific scenario which is no longer pertinent.
