### ISSUE TITLE
Currently splitting pyqgis cookbook chapter

### ISSUE THREAD

**Issue by ghtmtt** [qgis/QGIS-Documentation#3508]
Who is interested to picking up one chapter of the pyqgis cookbook and verify all the code, add you name next to the chapter.

PR should be made against **master** branch.

It is a very important task. Basically you have to check all the code snippet and test them in the pyqgis console. **Important**: in each page the code snippet should work *alone*, meaning that if you are using a vector layer, you should declare it. The typical use case is: a user wants to work on the `geometry` chapter and a snippet code is referring to a `vlayer` defined in the `vector` chapter. 

- [ ] intro
- [ ] loadproject @SrNetoChan 
- [x] loadlayer @tudorbarascu 
- [x] raster @ghtmtt 
- [ ] vector @raymondnijssen 
- [x] geometry @arongergely
- [x] crs @ghtmtt @arnaud-morvan @SrNetoChan
- [x] canvas @tudorbarascu
- [x] composer @tudorbarascu
- [x] expressions @carolinux 
- [x] settings @carolinux
- [x] communicating @tudorbarascu 
- [ ] authentication
- [ ] tasks
- [ ] plugins/index
- [ ] processing
- [ ] network_analysis @tudorbarascu 
- [ ] server

**Comment by arongergely** [comment]
I would like to help! I start with `geometry`.

**Comment by ghtmtt** [comment]
@arongergely I've put your name in the main issue text so other users will noticed it immediately.

**Comment by arongergely** [comment]
Thanks - The main issue text is non-editable from my account, that is why i responded in a comment.

**Comment by carolinux** [comment]
@ghtmtt I can take the settings page

**Comment by tudorbarascu** [comment]
@carolinux I added you to the settings page, thank you!

**Comment by tudorbarascu** [comment]
@arongergely @carolinux There's a cookbook testing branch where we should work. It contains a demo project + data so that the code is applied to them etc.

**Comment by carolinux** [comment]
Please see #3514 for my bit

**Comment by arongergely** [comment]
Updated `geometry.rst`, please see my pull request #3522

**Comment by carolinux** [comment]
@ghtmtt I will take expressions.rst too

**Comment by ghtmtt** [comment]
thanks @carolinux. Did you have a look at the new [testing framework](https://docs.qgis.org/testing/en/docs/documentation_guidelines/cookbook_guidelines.html)?

**Comment by carolinux** [comment]
@ghtmtt it looks good! Just like discussed in the hackfest :)
One thing I am not sure about is if it's possible to load test files in the code using a path?
Don't see test files here: https://github.com/qgis/QGIS-Documentation/tree/master/source/docs/pyqgis_developer_cookbook

**Comment by ghtmtt** [comment]
Hi @carolinux not sure about that. Maybe @arnaud-morvan has some ideas? Anyway: do you have long scripts that you want to include in the rst file? Is this the reason you want to include external files?

**Comment by carolinux** [comment]
I might need to. Do we have ways to create test vector layers (with actual
data in them) without loading from a file? I will look into how it is done
in the other rsts. And maybe there is some ways with MemoryLayers and/or
StringIo to achieve that.

**Comment by DelazJ** [comment]
@carolinux https://github.com/qgis/QGIS-Documentation/tree/master/qgis-projects/python_cookbook?

**Comment by DelazJ** [comment]
These should be fixed now after @elpaso update
