### ISSUE TITLE
Redirect all languages to English when they do not exist in a branch

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#3518]
I know that 3.4 doc is not yet pushed to transifex, so it's normal that i got nothing frenchy using https://docs.qgis.org/3.4/fr/docs/pyqgis_developer_cookbook/vector.html#writing-vector-layers but i wouldn't expect a «Not found» message. 
If i try the same on testing branch, https://docs.qgis.org/testing/fr/docs/pyqgis_developer_cookbook/vector.html#writing-vector-layers opens the English version. So given that 3.4 French is neither here, let's open the 3.4 English page meanwhile.
Why this request? Since i know that the next translatable doc is 3.4, i always indicate docs to people in french community using `3.4/fr` instead of `testing/en`, ensuring that when translation is available, these links will be directly operational for the requesters. They are broken now.

**Comment by rduivenvoorde** [comment]
@DelazJ I just cannot get this to work, sorry. Hope that we get the translations to work soon, so the old system will work again

**Comment by DelazJ** [comment]
Fixed also
