### ISSUE TITLE
Redirect older releases help button to 3.4

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#3519]
Few days, ago, this 3.2 link https://docs.qgis.org/3.2/fr/docs/pyqgis_developer_cookbook/vector.html#writing-vector-layers would open testing, ie https://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/vector.html#writing-vector-layers
With 3.4 branched, 3.0 to 3.3 links should redirect to 3.4 docs (making the help button in the application still usable) and not return a "Not found" page.
related to #3518
thanks. 
@rduivenvoorde?

**Comment by ghtmtt** [comment]
is working for me: 3.4 redirects to https://docs.qgis.org/3.4/en/docs/user_manual/working_with_vector/attribute_table.html#creating-one-or-many-to-many-relations and teh same button on master redirects to https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/attribute_table.html#creating-one-or-many-to-many-relations

**Comment by rduivenvoorde** [comment]
@ghtmtt I know but @DelazJ means: https://docs.qgis.org/3.2/en/docs/user_manual/working_with_vector/attribute_table.html#creating-one-or-many-to-many-relations or other versions (from 3.0 - 3.3).
I've tried to 'fix' those redirect rules in apache.conf but am not able to fix it.

If anybody else wants to try, let me know I can give you access to the server if you need it? 
@jef-n maybe?

**Comment by DelazJ** [comment]
Fixed now!
