### ISSUE TITLE
Install backport github app

### ISSUE THREAD

**Issue by m-kuhn** [qgis/QGIS-Documentation#3520]
As per this request to not sidetrack the other discussion https://github.com/qgis/QGIS/pull/9448#issuecomment-471231206

- [x] Request app installation on github repository
- [x] Accept request for app installation
- [x] Create labels for backport targets
- [ ] Start using it

**Comment by DelazJ** [comment]
Thanks @m-kuhn

**Comment by m-kuhn** [comment]
Up and running.

Thx @timlinux

**Comment by ghtmtt** [comment]
could be provide some small description for this? It looks really really promising as an automated feature. We just need to add the label `backport release_name_branch_name` to automatic enable the backporting?

**Comment by m-kuhn** [comment]
Yep, whenever you have a PR which you want to backport, you label it. After merge, the backport PR will be opened (or a comment left that it failed).

You can also label pull requests which have already been merged and they will be backported too.

**Comment by ghtmtt** [comment]
that's really really cool, thanks @m-kuhn . @DelazJ I think we should start to think adding a small section of `Reviewer guidelines`. People without commit rights cannot label issues and PR. So maybe also adding an additional checkbox (or whatever) to the #3513, like "this PR should be backported also for 3_4 release" could be good

**Comment by m-kuhn** [comment]
That's probably the first time I really see benefit for a checkbox in a pull request template! (Compared to a checkbox to acknowledge that pull requests will pass which have not even been run yet and whose results will be shown highly visible anyway ;P )

**Comment by ghtmtt** [comment]
> That's probably the first time I really see benefit for a checkbox in a pull request template!

:) just thinking aloud... is there maybe a magic way to automatic create a label (backporting one) when a checkbox is checked?

**Comment by m-kuhn** [comment]
There would be if

- anyone feels like digging into nodejs / [probot](https://probot.github.io/docs/) / [zeit](https://zeit.co/)
- or someone would set up a service with another technology and host it on our servers

**Comment by ghtmtt** [comment]
> There would be if
>
>  *  anyone feels like digging into nodejs / probot / zeit
>   * or someone would set up a service with another technology and host it on our servers

ok, just kidding :)

**Comment by DelazJ** [comment]
> So maybe also adding an additional checkbox (or whatever) to the #3513, like "this PR should be backported also for 3_4 release" could be good

+1
