### ISSUE TITLE
[FEATURE][processing] New Raster Boolean logical OR/AND algorithms

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3523]
Original commit: https://github.com/qgis/QGIS/commit/b66b94453579e86ce4bf25a1d10438c34f672eba by nyalldawson

These algorithms calculate the boolean OR or AND for a set of input
rasters. For AND, if all of the input rasters have a non-zero value
for a pixel, that pixel will be set to 1 in the output raster, otherwise
it will be set to 0. For OR, if ANY of the input rasters have a non-zero
value for a pixel, that pixel will be set to 1 in the output raster,
else 0.

A reference layer parameter specifies an existing raster layer to use
as a reference when creating the output raster. The output raster will
have the same extent, CRS, and pixel dimensions as this layer

By default, a nodata pixel in ANY of the input layers will result in
a nodata pixel in the output raster. If the 'Treat nodata values
as false' option is checked, then nodata inputs will be treated the
same as a 0 input value.

Makes for much simpler raster boolean logic calculation without
the complexity of using the raster calculator (and that's not
always possible to do anyway, e.g. when ANY of the input rasters
has a nodata pixel). It's also scalable dynamic to any number of
input rasters (unlike raster calc), so is more flexible when
used within models.

**Comment by DelazJ** [comment]
Should be added at https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/rasteranalysis.html

**Comment by havatv** [comment]
I don't think https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/rasteranalysis.html needs to be updated, as none of the operators are discussed in detail, and only a few are mentioned. The AND and OR operators are both shown in the https://docs.qgis.org/testing/en/docs/user_manual/working_with_raster/raster_analysis.html#raster-calculator figure.

**Comment by DelazJ** [comment]
I don't have QGIS right now but these are algorithms per se: "Boolean and" and "Boolean or"
