### ISSUE TITLE
[FEATURE] [needs-docs] add new vertical and horizontal equispaced distributions

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3533]
Original commit: https://github.com/qgis/QGIS/commit/7c6b66be8a54636be0ddd171cbc1a94e7ba69c11 by nastasi-oq

Unfortunately this naughty coder did not write a description... :-(

**Comment by roya0045** [comment]
@DelazJ Are the other spacing options documented? I though they would be in the composer overview,
