### ISSUE TITLE
[FEATURE][processing] New parameter types for layouts and layout items

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3536]
Original commit: https://github.com/qgis/QGIS/commit/021d1ef237065dd40c80b9b5044406f6319b18e0 by nyalldawson

Allows processing algorithms which operate on a specific layout
and layout item selection

**Comment by havatv** [comment]
Documented (included in the processing algorithm parameters table) in the user manual (script.rst).
