### ISSUE TITLE
 F1 key does not lead to a web help file in 3.2.3 Bonn

### ISSUE THREAD

**Issue by monkey722** [qgis/QGIS-Documentation#3543]
## F1 key does not lead to an English web help file in 3.2.3 Bonn

If I choose the Help tab in 3.2.3 Bonn, it leads to a 404 error:
![qgis_323_help_error](https://user-images.githubusercontent.com/43815936/54361032-8a131800-463c-11e9-8cfb-5d95c65dbdc1.jpg)

https://docs.qgis.org/3.2/en/docs/user_manual/index.html

**Comment by DelazJ** [comment]
See also #3519

**Comment by DelazJ** [comment]
Fixed now
