### ISSUE TITLE
Add option to format time in mesh layer (#9452)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3550]
Original commit: https://github.com/qgis/QGIS/commit/37faa0d883ae2bba3f795a7cc66898cc24b76c7a by web-flow

[feature] [mesh] #20731 add option to format time in mesh layer

There is new settings dialog that can be opened by button next to time slider. User can set reference time and time format (e.g. 2019-03-21 22:01:11).

**Comment by DelazJ** [comment]
Considering the GUI displayed in qgis/QGIS#9452, I'm not sure this is still available as is in QGIS. Can you confirm @PeterPetrik?

**Comment by DelazJ** [comment]
Obsolete report
