### ISSUE TITLE
Move the "fix me" buttons in the 2.18 release pages to 3.4

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#3559]
## Description

With 3.4 being the release we maintain now, it's time to remove the "fix me" links that open the source pages and translation files, in 2.18 documentation. And enable them for 3.4 branch.

## Checklist

- [x] I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage.
If it's related to QGIS application or website, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html
for the right issue tracker or to the [support channels](http://qgis.org/en/site/forusers/support.html)
- [x] I have added a link to the page concerned by the issue

**Comment by ghtmtt** [comment]
agreed. As discussed with @rduivenvoorde we should make the `fix me` button more visible (also in the maybe upcoming vanilla theme). Having a ribbon or something similar to the `fork me` button you find in some website (changing it to `enhance me` or similar) would maybe help to have more contributors

**Comment by DelazJ** [comment]
The fix is there but since the 2.18 doc is now archived (I should have remarked that!), I guess nothing would change in the published doc. Closing.
