### ISSUE TITLE
Improved and semi automated bad layer handling 

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#3588]
This PR aims to make handling bad layer less painful.

The basic gist is that layers are often clustered together and the current bad layer handler forces someone to change all the path.

The goal is to keep track of the basepaths associated with layers and propagate the same modification to all other layers sharing the exact same basepath.

See https://github.com/qgis/QGIS/pull/9583 for reference

**Comment by roya0045** [comment]
Would you need a better description or is this sufficient?

**Comment by DelazJ** [comment]
I'd say that better description is always better 😄 , if you have any. The more detailed inputs the writers have, the easier they can address the issues imho. Thanks.

**Comment by roya0045** [comment]
Something along those lines should be better then:

> Bad layers are usually clustered and can occur from moving the project or a folder. In order to not correct every layer manually one by one the layer handler will now keep track of the base path of layers.
> 
> On the base path of a layer has changed the new base path will be applied to every other layer that shares the same base path when apply is clicked.
> 
> This way a user should only have to fix one base path (everything before the name of the file) in order to fix the path to every other file that is in the same folder.

Is this good? I can also do it in french if needed.

**Comment by DelazJ** [comment]
> Is this good? I can also do it in french if needed.

Should help. Thanks @roya0045.
Non, pas nécessaire car la contribution se fait par défaut en anglais (et peu de francophones dans les parages, sauf si tu veux nous rejoindre 👍 ).

**Comment by roya0045** [comment]
Roger that
