### ISSUE TITLE
Should we use the assert in PyCookbook tutorial so often?

### ISSUE THREAD

**Issue by SrNetoChan** [qgis/QGIS-Documentation#3635]
```
exp = QgsExpression('1 + 1 = 2')
exp.hasParserError() #will return False
```

vs

```
exp = QgsExpression('1 + 1 = 2')
assert not exp.hasParserError()
```

I'm not a python expert, but I learned to avoid `assert` in production code.
These `assert` statements are for errors coming from programmers, not for errors coming from users.  These statements might not be executed in some python production environment.

CF: https://softwareengineering.stackexchange.com/questions/225956/python-assert-vs-if-return

So I'm not sure we should use these in a tutorial.
My 2 cents

_Originally posted by @Gustry in https://github.com/qgis/QGIS-Documentation/pull/3620_

**Comment by SrNetoChan** [comment]
@DelazJ @Gustry @arnaud-morvan @ghtmtt @havatv @carolinux ping

**Comment by carolinux** [comment]
I can see the case where the reader is confused by the assert (because when everything works, it shows nothing). Maybe we can have both asserts and print statements?

**Comment by SrNetoChan** [comment]
I am far from an expert in Python, so I will let the experts talk. If we really need to use the assert to validate the code, we can use it in a hidden testcode directive following that one, or in a testcleanup directive.

https://www.sphinx-doc.org/en/master/usage/extensions/doctest.html#directive-testcleanup

**Comment by SrNetoChan** [comment]
I do think we should clearly separate what is the tutorial content (aimed for users that wanna learn PyQGIS) from what needs to be used to test it (unless the output is all it's needed to test). The main goal should be keeping the examples simple to follow, while following Python/PyQGIS best practices.

**Comment by Gustry** [comment]
As I said, I'm not the python expert, I just learned that from colleagues. In some production environment, because `assert` is designed for programmers, these statements might not be executed in production code. But I don't know if it will happen in a QGIS environment.

But our readers will learn that and might use them outside of the QGIS context. Maybe I'm overthinking ;-)

But to come back on code readability as a python beginner, I think that these `assert` brings a little bit of complexity in the readability.

Can strip out lines on the doxygen compilation?

**Comment by arnaud-morvan** [comment]
IMHO, in tests (not production) is is preferable to use ``assert`` than to check the output (assert is often used in tests) because it easier to debug / maintain.
It should be possible to put assertions in a testcleanup section to mask them to the reader.

**Comment by ghtmtt** [comment]
> I can see the case where the reader is confused by the assert (because when everything works, it shows nothing). Maybe we can have both asserts and print statements?

I think the main reason of this enhancement is to transform out code in rock-solid code. I can understand the confusion of users when reading ``assert`` but, as @SrNetoChan found, if we can still test the code and hiding assert than I'm in favor of this.

We can then still use print statements or simple `exp.hasParserError() #will return False` (`isValid`.. et al) to show people they still can use them.

**Comment by DelazJ** [comment]
If we all agree that the most hidden assert is, the better it is, can any of you provide an example with how testcleanup should be used to fix this situation. I can try to fix what is already done but don't want to waste my time on trials and errors. Or if someone wants to do the cleanup...
Thanks.

**Comment by anitagraser** [comment]
+1 for hiding asserts where they are not relevant for the reader
