### ISSUE TITLE
[FEATURE] New Processing algorithm "Join attributes by nearest"

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3637]
Original commit: https://github.com/qgis/QGIS/commit/95af4d4a45f48889358446a0c9d02eb9d54860d7 by nyalldawson

K-nearest neighbour joins from the Processing toolbox!

This algorithm takes an input vector layer and creates a new
vector layer that is an with additional attributes in its attribute table
The additional attributes and their values are taken from a second
vector layer, where features are joined by finding the closest features
from each layer.

By default only the single nearest feature is joined, but optionally
the join can use the n-nearest neighboring features instead.

If a maximum distance is specified, then only features which are
closer than this distance will be matched.

**Comment by lbell** [comment]
Question: If I'm `joining on nearest` a Line layer to a Point layer, where on the line is considered in this process? 

Ie, if I have 3 points: one on the end vertex of the line, the middle vertex, and a vertex somewhere in between, which point is considered "nearest" to the line?

**Comment by havatv** [comment]
My guess is that it does not have to be a vertex. It should just use the distance between the *line* and the point.

**Comment by lbell** [comment]
Fair point. Further experimentation and it appears that the point that is closest to ANYWHERE on the line (or the first point that is actually ON the line) gets grabbed...
