### ISSUE TITLE
[FEATURE] New line symbol type: Hash line

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3638]
Original commit: https://github.com/qgis/QGIS/commit/48d2a370570e43cd6c9dedf802ca4549d74f7af8 by nyalldawson

This line symbol type is designed to replicate the ArcGIS Hash Line
symbol layer type. It allows for a repeating line segment to be
drawn over the length of a feature, with a line-sub symbol used
to render each individual segment.

To reduce code duplication, this is heavily based off the current
line marker symbol layer, since the functionality is almost
identical (draw some sub symbol at some interval along a line).
Accordingly, I've split off QgsMarkerLineSymbolLayer to move
as much of the common functionality as possible to a new abstract
base class, so that only the actual marker/line segment rendering
occurs in the marker line/hash line subclasses.

This also gives the hash line all the existing placement options
permissible for marker lines -- e.g. first/last vertex, mid points,
regular intervals, etc.

The hash line length and angle can have data defined overrides,
which are evaluated per-line segment, allowing for the hash line
to change size and angle over the length of a single rendered
feature.

**Comment by DelazJ** [comment]
Should be mentioned at https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/style_library.html#line-symbols and its `outline: hashed line` alter ego at https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/style_library.html#fill-symbols (and maybe it can have its own section under https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/style_library.html#the-symbol-layer if you feel expanding on the feature)
