### ISSUE TITLE
[FEATURE] Average line angles for marker and hashed line symbology

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3646]
Original commit: https://github.com/qgis/QGIS/commit/426382c919a0082e86d22b63200bb9c39b065573 by nyalldawson

Previously, when marker or hash lines were rendered using interval
or center point place placement, the symbol angles were determined
by taking the exact line orientation at the position of the symbol.

This often leads to undesirable rendering effects, where little
jaggies or corners in lines which occur at the position of the
symbol cause the marker or hash line to be oriented at a very
different angle to what the eye expects to see.

With this new option, the angle is instead calculated by averaging
the line over a specified distance either side of the symbol. E.g.
averaging the line angle over 4mm means we take the points along
the line 2mm from either side of the symbol placement, and use these
instead to calculate the line angle for that symbol. This has the
effect of smoothing (or removing) any tiny local deviations from
the overall line direction, resulting in much nicer visual
orientation of marker or hash lines.

Like all symbol settings, the average angle smoothing distance
can be set using mm/pixels/map units/etc, and supports data-defined
values.

Closed rings also correctly consider wrapping around these average
angles from the start/end vertex.

(Sponsored by an anonymous corporate backer)

**Comment by havatv** [comment]
Nothing to document here, in my opinion.  However, there may be illustrations that need to be updated (I have not checked).

**Comment by DelazJ** [comment]
I think there's something to document: looking to the diff there's GUI changes with at least one new option and while documenting the hash line (#3638) will be done, I guess, as a whole, including this option, I'm afraid that  closing this PR now may hide the description Nyall wrote above to writers.

**Comment by havatv** [comment]
Yes, new options should be documented.
