### ISSUE TITLE
[FEATURE][expression] Add concatenate_unique() aggregation function

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3647]
Original commit: https://github.com/qgis/QGIS/commit/578c3982193aaccf2ce6fc0757b52b23f397d15d by nirvn

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment]
See https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/expression.html#aggregates-functions

*tip*: use the `Fix me` link in the footer of the page to open the source file in edit mode.
