### ISSUE TITLE
[FEATURE][processing] Add concatenate_unique support to the aggregate alg

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3648]
Original commit: https://github.com/qgis/QGIS/commit/5e0fd15570555f9c8ff49595fede006ee735a63f by nirvn

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment]
No aggregate functions are mentioned in the documentation for the aggregate alg, so this one could be closed, in my opinion.

**Comment by DelazJ** [comment]
Agreed; we are using a link to the algs list in the parameter description so fixing #3647 will implicitly fix this one
