### ISSUE TITLE
error to calculate NDVI index in stacked image 

### ISSUE THREAD

**Issue by andbrs** [qgis/QGIS-Documentation#3649]
I'm doing a research project where I do multispectral image processing, but I would like to check if this works the QGIS at the time of using the roster calculator I get the following error:

Procesando algoritmo...
Algoritmo 'Raster calculator' comenzando…
Parámetros de entrada:
{ 'CELLSIZE' : 0, 'CRS' : None, 'EXPRESSION' : '(bgrne2@4 - bgrne2@3) % (bgrne2@4 + bgrne2@3)', 'EXTENT' : None, 'LAYERS' : ['C:/Users/felip/Desktop/imageprocessing/bgrne2.tiff'], 'OUTPUT' : 'C:/Users/felip/Desktop/ndvi.tif' }

Traceback (most recent call last):
File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\algs\qgis\RasterCalculator.py", line 191, in processAlgorithm
raise QgsProcessingException(self.tr("Error parsing formula"))
_core.QgsProcessingException: Error parsing formula

La ejecución falló después de 0.13 segundos

Cargando las capas resultantes
Algoritmo 'Raster calculator' finalizado

this is the image: https://drive.google.com/file/d/1J0yiMeI-sNnW5Ep7-eZfJInCm_2zn3Tb/view?usp=sharing

**Comment by DelazJ** [comment]
@andbrs this is not a [QGIS Documentation](docs.qgis.org) issue but an application one, so please either fill an issue report with necessary information at https://issues.qgis.org (see [guidelines](https://qgis.org/fr/site/getinvolved/development/bugreporting.html) for more details) or ask for help from the [community](http://qgis.org/fr/site/forusers/support.html).
This repository is dedicated to QGIS documentation matters. 
I'm closing.
Thanks
