### ISSUE TITLE
[FEATURE] postgres provider: add support for generated identity columns (implements #21745)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3653]
Original commit: https://github.com/qgis/QGIS/commit/59dd85103ddbfc640662c9ed220235d94cb7c7c2 by jef-n

Unfortunately this naughty coder did not write a description... :-(

**Comment by felixfeckler** [comment]
I dont think this need documentation, users would expect that generated id columns work?!
