### ISSUE TITLE
[FEATURE][expression] New array_all() function to check whether
an array contains _all_ values of another given array.

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3662]
Original commit: https://github.com/qgis/QGIS/commit/2582399ab5895be19d09e7d24810748f4a597ba2 by nirvn

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment]
See https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/expression.html#array-functions

*tip*: use the `Fix me` link in the footer of the page to open the source file in edit mode.
