### ISSUE TITLE
[needs-docs] Fixes intersection on (multi)linestring/polygon Z, M and ZM. Fixes #21422

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3675]
Original commit: https://github.com/qgis/QGIS/commit/30399dfed2b622c8dc7ec885de55ab6fb517eed9 by lbartoletti

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment]
Isn't this a bug fix? What should be added / changed in the documentation?

**Comment by DelazJ** [comment]
Can we keep it around for a moment? I need to check the docs, but the underlining issue/lack is that there's quite no information about how digitizing 3D features works in QGIS. And this is something 3D users can help with imho.

**Comment by DelazJ** [comment]
Could be closed now considering the different linked PR
