### ISSUE TITLE
Update Documentation: "4.3.5 Rule-based Classification" must be updated.

### ISSUE THREAD

**Issue by nicone93** [qgis/QGIS-Documentation#3690]
While I was doing the training, if found out that all part "4.3. Lesson Classification" is completely different in QGIS 3.4 Noosa and also I was not able to understand it. 
So I am here to ask you to fix it please.

Thank you.

**Comment by havatv** [comment]
Illustrations need to be updated. Part of training manual affected: https://github.com/qgis/QGIS-Documentation/blob/master/source/docs/training_manual/vector_classification/classification.rst (search for "Rule-based Classification").

The user guide illustrations seem to be OK.
