### ISSUE TITLE
[FEATURE] Expression functions which return file info

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3703]
Original commit: https://github.com/qgis/QGIS/commit/762b2a423b3f8740b7d8216804f68c2e6e319de6 by nyalldawson

base_file_name: Returns the base name of the file without the directory or file suffix.
file_exists: Returns true if a file exists
file_name: Returns the file name from a full path
file_path: Returns the directory/path from a full file path
file_size: Returns a file size
file_suffix: Returns a files suffix/extension
is_directory: Returns true if a file path is a directory
is_file: Returns true if a file path is a file

**Comment by DelazJ** [comment]
A path group with functions should be added at https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/expression.html

*tip*: use the `Fix me` link in the footer of the page to open the source file in edit mode.
