### ISSUE TITLE
[FEATURE] Make the custom dash pattern dialog a style dock widget

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3704]
Original commit: https://github.com/qgis/QGIS/commit/cd5642aca0dab70b104e2325ca0e7448dddbd9a5 by nirvn

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment]
Not sure there's anything worth documenting here. It now follows behavior of layer properties options
