### ISSUE TITLE
[FEATURE] Add order by support to expression aggregate and concatenation functions

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3730]
Original commit: https://github.com/qgis/QGIS/commit/2e5257372bc3866e13626ba0602971f401977727 by nyalldawson

Because certain aggregates and concatenation requires results in
a certain order, this change allows specific control of the order
features are added to the aggregate during an expression evaluation.

E.g.

concatenate("Station",concatenator:=',', order_by:="Station")

will give a comma separated list of station names in alphabetical
order, rather than layer feature order.

Sponsored by SMEC/SJ

**Comment by DelazJ** [comment]
We do not document functions in details so I think we can close this one
