### ISSUE TITLE
[FEATURE] vertextool : chained add vertex at endpoint

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3735]
Original commit: https://github.com/qgis/QGIS/commit/0b2a9258d7eb4bfd1339eedf95280e97c2f51b1b by olivierdalang

This makes it possible to digitizle multiple points at
once when extending a line feature with the vertex tool

**Comment by DelazJ** [comment]
To doc at https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/editing_geometry_attributes.html#basic-operations
