### ISSUE TITLE
[FEATURE][processing] New algorithm "Overlap analysis"

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3736]
Original commit: https://github.com/qgis/QGIS/commit/2ec429cb890242d29e04908fa0eabe74bbb3a899 by nyalldawson

This algorithm calculates the area and percentage cover
by which features from an input layer are overlapped by
features from a selection of overlay layers.

New attributes are added to the output layer reporting
the total area of overlap and percentage of the input
feature overlapped by each of the selected overlay layers.

This is quite a common GIS task request, yet is full
of traps for inexperienced users, and the amount of
manual data work usually done by users to calculate
these figures can often lead to mistakes and inaccurate
results. It's nice to have a robust, fast, inbuilt
algorithm which allows this task to be done in a
single step without risk of human error.

**Comment by DelazJ** [comment]
To doc at https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/vectoranalysis.html
