### ISSUE TITLE
[FEATURE][processing] Add "Save layer styles into GeoPackage" option for Package Layers algorithm

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3739]
Original commit: https://github.com/qgis/QGIS/commit/2d644376be3a1b2803cc12dad87fabeffc042b67 by nyalldawson

Allows embedding of the current layer styles into the packaged layers
as the default layer styles.

**Comment by DelazJ** [comment]
https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/database.html#qgispackage
