### ISSUE TITLE
[FEATURE] add toolbar in attribute table to browse feature list

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3746]
Original commit: https://github.com/qgis/QGIS/commit/f680466bf7519857c2ae526fcfafcee2ee1d1b68 by 3nids

arrows allow browsing the feature list in the attribute table in form view
the current edited feature can be highlighted and the map canvas automatically panned or zoomed

**Comment by lajunek** [comment]
@DelazJ @havatv @SrNetoChan I will implement this

**Comment by lajunek** [comment]
@DelazJ i think this is implemented already. Can I click on Close and comment?

**Comment by DelazJ** [comment]
@lajunek any reference to the page in docs, please?

**Comment by lajunek** [comment]
@DelazJ sure here i found it : [(https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/attribute_table.html#table-view-vs-form-view)]

**Comment by DelazJ** [comment]
I think the most recent change in this section predates the implementation of [this feature](https://github.com/qgis/QGIS/pull/9992) which is about the tools exposed above the "Show all features" menu in the following screenshot
![image](https://user-images.githubusercontent.com/7983394/60755162-e20acb80-9feb-11e9-98b7-5600cdefca53.png)

**Comment by lajunek** [comment]
@DelazJ sure here i found it : [(https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/attribute_table.html#table-view-vs-form-view)]
@DelazJ ok, I see there can be much more description about this new feature!
