### ISSUE TITLE
[needs-docs] Harmonize display of GDAL build vrt options

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3763]
Original commit: https://github.com/qgis/QGIS/commit/48f837a38cb0db2c421bf188950dcf7df51766f8 by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment]
https://docs.qgis.org/3.4/en/docs/user_manual/processing_algs/gdal/rastermiscellaneous.html#build-virtual-raster
