### ISSUE TITLE
[needs-docs][processing] Avoid field collision via optional prefix in overlay algorithms (#10092)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3767]
Original commit: https://github.com/qgis/QGIS/commit/a88898656782ce971e6ce45b6f9487e67de9154f by web-flow

Makes for a more predictable collision avoidance, which
can be neccessary for some models.

**Comment by DelazJ** [comment]
See also #3736

**Comment by havatv** [comment]
This has been documented for all the relevant overlay algorithms now:
Intersection, Line intersection, Symmetrical difference and Union.
