### ISSUE TITLE
[needs-docs] Append a local, user writable folder to proj 6 search paths

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3777]
Original commit: https://github.com/qgis/QGIS/commit/a4e5e6a598ce29ade92df1064cb210bf0f4eb88c by nyalldawson

Now, proj will search in the current user profile "proj" folder (e.g.
.local/share/QGIS/QGIS3/profiles/default/proj" on linux) for
grid files and other proj helper files.

This allows users (and plugins) to install grid files and make them
available for use in QGIS without requiring administrator access
to the system.

**Comment by roya0045** [comment]
@DelazJ Not sure about the tag of this one and the target audience
