### ISSUE TITLE
[needs-docs] Make label map tools follow click-click behavior

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3779]
Original commit: https://github.com/qgis/QGIS/commit/8b83a461f9131cdf971bde9ff19837ac247de15c by nyalldawson

It's rather jarring that the move label and rotate label tools
don't follow the rest of the application in using click-click
to move and rotate and rotate labels, and instead use the older
click-and-drag behaviour. This commit reworks the tools to use
click to start, click to end behaviour instead.

It also makes them respect the same conventions as the move
and rotate features tools, where a right click cancels the
move/rotate, and same with pressing "esc" mid-operation.

**Comment by roya0045** [comment]
Is the old behaviour even detailed somewhere? It's a UX bugfix at the limit. I'm not sure this need to be documented.
