### ISSUE TITLE
Offer downloadable documentation for offline use

### ISSUE THREAD

**Issue by jidanni** [qgis/QGIS-Documentation#3782]
On https://qgis.org/api/ we see
```
You can also download this documentation or a Qt help file for offline
use.
```

OK, so the API documentation has a downloadable offline version.

Now turning to the main documentation,

https://qgis.org/en/docs/index.html

such a similar link is missing.

Hence e.g., on Debian all one can find is
```
$ aptitude search qgis | grep doc
p  qgis-api-doc - QGIS API documentation
```
as an additional
```
p  qgis-doc - QGIS documentation
```
is not possible yet.

**Comment by jidanni** [comment]
file:///usr/share/qgis/doc/nohelp.html says
> The offline help files are not available or the location of these files is not properly configured

But at `#17`
```
$ aptitude search --sort '~installsize' --display-format '%I %p' '~n' | sed '/^ /d'|nl|sed /qgis/q
     1  14.2 GB astrometry-data-2mass-00
     2  9,252 MB astrometry-data-2mass-01
... 
    17  1,326 MB qgis-api-doc
```
of all Debian packages, one doesn't dare download it...

**Comment by jef-n** [comment]
qgis-api-doc only contains the api documentation, which is built from the qgis source with doxygen.

**Comment by DelazJ** [comment]
@jidanni It's possible to download a pdf version or build your own html version. Can you clarify what you are looking for? and the format?

**Comment by jidanni** [comment]
I was hoping there would be a reasonably sized Debian package that would contain the HTML docs.

**Comment by havatv** [comment]
I think this is out of scope for the documentation team.

**Comment by DelazJ** [comment]
@havatv, @SrNetoChan build improvements PR include generation of a zip file of the HTML so despite it's not an "apt" oriented method, we will provide HTML doc that people can download and use offline.
Reopening because once done, we'd need to mention the new capability that people can connect to their software to locally browse the help files.

**Comment by havatv** [comment]
@DelazJ, OK - I have assigned it to you, then.

**Comment by DelazJ** [comment]
Hi @jidanni
In the bottom left menu of the documentation pages, there's an entry to download html zipped folder. Would that meet your needs?

**Comment by jidanni** [comment]
@DelazJ I don't know as I already have uninstalled qgis. OK I will unsubscribe from this bug.

**Comment by DelazJ** [comment]
Closing then
