### ISSUE TITLE
Reorder index QGIS cheat sheet

### ISSUE THREAD

**Issue by All4Gis** [qgis/QGIS-Documentation#3786]
## Description

Based on [# 3621 (review)](https://github.com/qgis/QGIS-Documentation/pull/3621#pullrequestreview-240631192) , I propose this new index.
We start with the most "visual" and we go from less to more, leaving complex things like the decorators in the end.

**User Interface
Settings
Toolbars
Menus
Canvas
Layers
Table of contents
Advanced TOC
Processing algorithms
Decorators
Sources**

What do you think? 

Page URL: https://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/cheat_sheet.html

**Comment by ghtmtt** [comment]
+1 for me

**Comment by DelazJ** [comment]
Hi @All4Gis Looks good to me too.
I think however that there are some sample codes we can move sections, particularly what's in the "Table of contents" section. Most of them can go to either "map canvas" or "layers", hence the remaining items will be merged with the "advanced toc"'s.
And from "layers" maybe we can extract a "Features" section (for feature and geometry access and manipulation)?
Just some more thoughts.
Thanks.

**Comment by All4Gis** [comment]
Yes ,you are right!Maybe **Add vector layer** for example is better in layer section.Perfect, I change it and I do PR

**Comment by All4Gis** [comment]
Make PR # 3792, sorry for my previous PR, I have already closed it since I didnt have my branch cleaned. Sorry, again

**Comment by DelazJ** [comment]
no problem @All4Gis I can bet that EVERY github user has fallen at least once in this trap 😄

**Comment by ghtmtt** [comment]
once?! :D

**Comment by DelazJ** [comment]
fixed in #3792
