### ISSUE TITLE
[needs-docs] Reorganise Zoom to Native action to sit next to
other layer-related zoom actions

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3816]
Original commit: https://github.com/qgis/QGIS/commit/5201151c1c89e191dc1cfc1ee07b1fc47badf4bc by nyalldawson

Instead of sitting next to global map based zoom actions

**Comment by DelazJ** [comment]
Reorder sequence of items in the table at https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_gui.html#view

**Comment by DelazJ** [comment]
Fixed in #4543
