### ISSUE TITLE
Make the target crs optional in gdal warp algorithm [needs-docs]

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3817]
Original commit: https://github.com/qgis/QGIS/commit/1e2b59afc461e0c760e587e623ed607de1aaa8e4 by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment]
This was recently documented:
https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/gdal/rasterprojections.html#warp-reproject
