### ISSUE TITLE
[needs-docs] Add --version|-v cli option to qgis executable

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3839]
Original commit: https://github.com/qgis/QGIS/commit/ebfce9b3ec2e1746444eae3dd1d4b1a81db182ca by web-flow

[needs-docs] Add --version|-v cli option to qgis executable

**Comment by DelazJ** [comment]
https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html#running-qgis-with-advanced-settings
