### ISSUE TITLE
Fix attribute table shortcuts when docked [needs-docs]

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3843]
Original commit: https://github.com/qgis/QGIS/commit/cd8f2f1e00736765c93c0479d0b6e7b66d0d1694 by nyalldawson

Closes #29633, fix #29945

**Comment by lajunek** [comment]
@QGIS-feature-tracker can you give some information about these shortcuts?

**Comment by SrNetoChan** [comment]
@lajunek the original commit was done by @jgrocha, so better aks him. the @QGIS-feature-tracker is just a bot, and won't answer.
Looking at the code looks like some shortcuts were missing in the attribute table when it was in window mode. They seem to be already described in here:

https://docs.qgis.org/3.4/en/docs/user_manual/working_with_vector/attribute_table.html#introducing-the-attribute-table-interface

Therefore, probably there is nothing new to document in this case.

**Comment by DelazJ** [comment]
> Therefore, probably there is nothing new to document in this case.

Actually there's. @lajunek see the PR message at https://github.com/qgis/QGIS/pull/29996 for what might need to be done

**Comment by SrNetoChan** [comment]
@DelazJ thanks for finding this. I am not very experienced in finding the original PR, it was almost hidden.

**Comment by DelazJ** [comment]
Currently you need to click the commit ref in the first message above and then click the PR number which is shown next to the master branch (in the upper part of the new page). But Matthias grant proposal should make it directly accessible in the future.
