### ISSUE TITLE
[needs-docs] [labeling] Allow data defined control over line placement options

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3851]
Original commit: https://github.com/qgis/QGIS/commit/3bd3aba25b60f32c2170e519a5e9b37249d49be2 by nirvn

Allows users to override the line placement settings (e.g.
above/below/on line options) on a per-feature basis. Somehow
this one was the only(?) setting from labeling which
was missing a data defined control...

**Comment by DelazJ** [comment]
Duplicate of #3852
