### ISSUE TITLE
[needs-docs] [labeling] Allow data defined control over line placement options

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3852]
Original commit: https://github.com/qgis/QGIS/commit/9acc3b63093312e15ecb2e24572d71f0719f7229 by nirvn

Allows users to override the line placement settings (e.g.
above/below/on line options) on a per-feature basis. Somehow
this one was the only(?) setting from labeling which
was missing a data defined control...

(cherry picked from commit 3bd3aba25b60f32c2170e519a5e9b37249d49be2)

**Comment by DelazJ** [comment]
Since we don't need to document data-defined widget, it may be only about adding/updating screenshot at https://docs.qgis.org/3.4/en/docs/user_manual/working_with_vector/vector_properties.html#labels-properties (i realize we don't have enough there)

**Comment by DelazJ** [comment]
Data-defined button is nowadays part of any gui option so no need to mention it. Also for this particular feature, we provide rendering example instead of dialog screenshot. Closing then.
