### ISSUE TITLE
[feature][needs-doc] format strings

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3856]
Original commit: https://github.com/qgis/QGIS/commit/aa2aed9e1f310bea0a12a6eb9adfd2d10b9c369b by ghtmtt

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment]
Nothing to document here, no? @ghtmtt

**Comment by DelazJ** [comment]
"Fixed" somehow in #3864
