### ISSUE TITLE
[processing][feature][needs-docs] allow to define model parameters as
advanced

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3872]
Original commit: https://github.com/qgis/QGIS/commit/625cc01fc3f5d20a0189c07f08aa666e97d75c4c by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by alexbruy** [comment]
@lajunek it marks parameter as advanced, so it is placed inside the "Advanced paramters" collapsible groupbox in the algorithm dialog.

**Comment by lajunek** [comment]
@havatv @DelazJ I can update the screenshots for "The graphical modeler". These will be from Windows.

**Comment by roya0045** [comment]
The doc seem to include this at the moment, maybe screenshot needs an update but text seems fine.

**Comment by DelazJ** [comment]
I don't think the screenshot needs an update; the one just above the mention of "advanced" property shows it (https://docs.qgis.org/testing/en/docs/user_manual/processing/modeler.html#definition-of-inputs). Good enough.
Fixed in #6027
