### ISSUE TITLE
Symbols that represent exercises level of difficulty are too close for colourblind people

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#3876]
_This is part of a series of issue reports inspired by Jared Morgan [review of QGIS training manual](https://docs.google.com/document/d/1_0CalcMFFUtM0UxhLareUWNEZZVxslqynZn5fmLKkDQ/edit#) in prelude of [Osgeo participation to GSOD](https://wiki.osgeo.org/wiki/Season_Of_Docs_2019)_

Currently, we are using the following icons to differentiate ![image](https://user-images.githubusercontent.com/7983394/60012213-aed74c80-967b-11e9-9a24-76b2facc902f.png)  basic, ![image](https://user-images.githubusercontent.com/7983394/60012260-c7476700-967b-11e9-8c57-9ed2c1d95fbb.png) intermediate or 
![image](https://user-images.githubusercontent.com/7983394/60012272-d3cbbf80-967b-11e9-8df7-4371aed4a203.png) advanced level of learning in the training manual.

> Colourblind people are going to have issues with working out whether this Follow-along is pitched right for them based on the tag colour and without any context about what the tag colour means.
>
> Alternative approaches:
>
> 1. Have a declaration about the experience level directly below the title.
> 2. If you need the context of the lesson difficulty in the heading, consider putting it into something like Follow Along [Beginner]: Prepare a Map.
>
> Even better, have an index of all the Follow Alongs (basically How-to's) that are tagged with the label so you can find them in groups.

Expanding the last point:

>Depending on how you structure these Follow Alongs you could apply a label metadata tag in the document, which could be used to filter across all the follow-along topics to display them in an appendix section.
>
>In this section, you could group them according to their difficulty level so new users could see them all in one place.

Another alternative is see could be to base the differentiation on number of symbols: double or triple the icon to show the level is increasing; you know... the kind of icons to show how spicy is a food. Not sure then which colour we would keep.

**Comment by havatv** [comment]
What about also adding a (black?) capital(?) letter to each icon to make it easier to differentiate between them (B - basic for the green one, I -intermediate for the blue one and A - advance for the orange one?

For example like this (green icon): ![greenicon](https://user-images.githubusercontent.com/1598812/60021313-139da180-9692-11e9-93b6-a0f28f1702f5.png)

**Comment by DelazJ** [comment]
These letters have meaning for english speakers. I'm not sure they have meaning for all languages.

**Comment by havatv** [comment]
The point was to make it easier to see the difference.
What about A, B, C, then (or 1, 2, 3)?

**Comment by havatv** [comment]
What about something like this (inspired by https://cdn.dribbble.com/users/46353/screenshots/1392616/difficulty-icons.png):
![lavel_easy](https://user-images.githubusercontent.com/1598812/81476853-7a796a00-9214-11ea-9980-487b2462f39b.png) ![lavel_medium](https://user-images.githubusercontent.com/1598812/81476854-7cdbc400-9214-11ea-9274-4a3ffb1eefae.png) ![lavel_difficult](https://user-images.githubusercontent.com/1598812/81476867-98df6580-9214-11ea-880f-ec0f2c5d68d8.png)
