### ISSUE TITLE
Add a section concerning write documentation in the page GetInvolved

### ISSUE THREAD

**Issue by rosaguilar** [qgis/QGIS-Documentation#3886]
## Description
Include a short text (and link) about "write documentation" similar to the "Translate QGIS" in the main content (right side) of _Get Involved_ page so users can quickly access to this section.

Page URL: https://www.qgis.org/en/site/getinvolved/index.html

**Comment by rosaguilar** [comment]
An initial idea:
**Document QGIS** 
The QGIS project aims to provide clear documentation concerning
 a User guide, GIS concepts, and training material.
Writing documentation provides an ideal platform for your first 
contribution to the project.
 If you want to join to 
 the documentation effort, you can
find a gentle introduction and guidelines here:
[Write Documentation](https://www.qgis.org/en/site/getinvolved/document.html)

**Comment by DelazJ** [comment]
Thanks @rosaguilar. LGTM. Can you please open a PR for that in the website repo?
I can see that each section has an image associated. Anyone knows where those come from and whether there's one we can associate to docs?

**Comment by raymondnijssen** [comment]
![get-involved-documentation](https://user-images.githubusercontent.com/681851/60394688-c786ad00-9b28-11e9-8d8d-a3ea5bed295a.png)

Is this one ok?

**Comment by DelazJ** [comment]
Thanks @raymondnijssen. I'm fine with your proposal.
> Is this one ok? (Click it to view it, it is just transparent and white)

And thanks for the tip

**Comment by rosaguilar** [comment]
Thanks @raymondnijssen. The PR is done @DelazJ. Thanks.

**Comment by DelazJ** [comment]
Fixed in https://github.com/qgis/QGIS-Website/pull/647
