### ISSUE TITLE
[needs-docs] Ensure the layers panel is horizontally scrollable

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3889]
Original commit: https://github.com/qgis/QGIS/commit/f4348259c95b1f37de80f984340125302f6baab3 by web-flow

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment]
Should not require any text updates, but perhaps some illustrations could be updated to show the horizontal scrollbar.

**Comment by DelazJ** [comment]
I'm not convinced we need to document anything. This looks more like a bugged GUi fix and I can't see the context in which this could be introduced in the doc...

**Comment by SrNetoChan** [comment]
Let's just close this. There's no point in forcing a horizontal scroll bar in screenshots.
