### ISSUE TITLE
[FEATURE] [OGR provider] Handle read-write support for .shz and .shp.zip with GDAL 3.1

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3891]
Original commit: https://github.com/qgis/QGIS/commit/de7e3fa8a5d85ea4918b056df54cc43e068d7ac2 by nyalldawson

GDAL 3.1 will bring read-write supprot for single-layer ZIP compressed shape
files (.shz), or multi-layer ones (.shp.zip). Do the few tweaking in QGIS so
that it is handled properly.

Related GDAL PR: https://github.com/OSGeo/gdal/pull/1676

**Comment by DelazJ** [comment]
Could maybe fall somewhere in https://docs.qgis.org/testing/en/docs/user_manual/managing_data_source/supported_data.html#esri-shapefile?

**Comment by lajunek** [comment]
@DelazJ @hatav I chekced the gdal version for QGIS 3.10.7 . This is only compiled against GDAL 3.03. So, do we need to add the read-write support for shp.zip and shp.shz for 3.10 documentation ?

**Comment by lajunek** [comment]
@DelazJ @havatv perhaps we can insert a tip and describe that when QGIS 3.10 is compiled against GDAL 3.1 we have read-write support for shp.zip and shp.shz?

**Comment by DelazJ** [comment]
Not necessarily a tip frame. It can be in the "normal" text but, yes, with a gdal version mention.
