### ISSUE TITLE
Add a really basic code sample for expression

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#3895]
## Description
Quoting @nyalldawson at https://github.com/qgis/QGIS-Documentation/pull/3769#discussion_r287880494 about the [basic expression code sample](https://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/expressions.html#basic-expressions) in the Cookbook
> This example is rather confusing as a first one. It relies on the concept that 1==true, which isn't obvious for new users. Maybe a simple math expression would serve here instead?

Page URL:https://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/expressions.html#basic-expressions

**Comment by marcu** [comment]
this issue can be closed
