### ISSUE TITLE
[FEATURE][layouts] Expose choice of arrangement of legends (i.e.
symbols to the left OR symbols to the right of legend text), and
alignment for group/subgroup/item text

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3900]
Original commit: https://github.com/qgis/QGIS/commit/6aeedfe20bfabbbe89b1e9ecb64df018b831b6f2 by nyalldawson

Allows creation of right-to-left locale friendly legends. Additionally,
we default to this right-to-left style alignment when creating new
legends under a RTL based locale.

**Comment by DelazJ** [comment]
https://docs.qgis.org/testing/en/docs/user_manual/print_composer/composer_items/composer_legend.html

**Comment by TBreure** [comment]
I tried looking into this but could not find the RTL based locale in the legend item properties, does this only appear when language settings are in a RTL based language? Unfortunately navigating in arabic is not a skill I have..
 @nickbearman

**Comment by DelazJ** [comment]
This ((as well as anything tagged with the [milestone "QGIS 3.10"](https://github.com/qgis/QGIS-Documentation/milestone/13)) is a to-be 3.10 feature so it requires installing 3.9 dev version beforehand.
In the meantime, here's what the dialog look like:
![Capture du 2019-09-21 13-39-11](https://user-images.githubusercontent.com/7983394/65372863-15b5d300-dc76-11e9-8b1c-477c2275e816.png)

The original feature description is at https://github.com/qgis/QGIS/pull/30426 (can be accessed following the url in the first message of the report)

**Comment by nickbearman** [comment]
Thanks @DelazJ, I was working on this with @TBreure and we had the right QGIS version and dialog, but missed what we were looking for! @TBreure had to head off but hopefully can pick this up in the future.
