### ISSUE TITLE
Add screenshot to getting started chapter

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#3922]
## Description
It could be nice to add some screenshots to the getting started chapter. More helpful for beginners.

Page URL: https://docs.qgis.org/testing/en/docs/user_manual/introduction/getting_started.html

**Comment by lajunek** [comment]
@DelazJ @havatv @SrNetoChan I will add some screenshots

**Comment by DelazJ** [comment]
Some screenshots have been added. But it could be nice to add ones showing the map, with labels and with decoration(s).

**Comment by DelazJ** [comment]
@selmaVH1 Maybe should we consider this one as closed by #8408?

**Comment by selmaVH1** [comment]
@DelazJ Later on I will fix those two screenshots ( smaller dialogs before taking screenshot because of resolutions in html and pdf ), but yes, we can consider this one as closed if you agree.

**Comment by DelazJ** [comment]
Closing then
