### ISSUE TITLE
[processing][needs-docs] Allow string parameters in models to be multi-line input style

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3947]
Original commit: https://github.com/qgis/QGIS/commit/b9c9ad05bc678d52d4a4857cd458e66493c1c6d8 by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by ghtmtt** [comment]
I'm not sure we have to document this feature. It's something in addition to the original parameter, but it should be straightforward to understand what it does.

It's like documenting the `checked` chance of the boolean operator. Opinions? @DelazJ @havatv

**Comment by havatv** [comment]
I  agree.
