### ISSUE TITLE
[FEATURE][API] Visitor API for style entities

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3958]
Original commit: https://github.com/qgis/QGIS/commit/590d1aae9d7541d36cf3ae612d1011cb81bb4606 by nyalldawson

Adds a new visitor pattern API for creation of visitors which visit
all the style entities (symbols, color ramps, text formats, and
label styles) associated with different objects. Can be used on a
renderer, map layer, or project wide level.

E.g. on a project wide level, allows collection of ALL the style
symbols/color ramps/text settings inside a project, including those
in layouts or annotations!

**Comment by DelazJ** [comment]
API stuffs
