### ISSUE TITLE
[FEATURE][processing] Allow file filter and default value to be set
for file/folder inputs in models

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3968]
Original commit: https://github.com/qgis/QGIS/commit/5a7105af7dd89078750f31747e4dc6cb573dfe43 by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by lajunek** [comment]
@DelazJ we don't use a File/Folder input in the graphical model described in "22.5.1. Definition of inputs". I wonder if we should update the whole chapter and describe a graphical model containing such an input (in order to show file filter and default value).

**Comment by roya0045** [comment]
File/Folder is now listed. Though not detailed, like the other input. Unsure if this should remain open.
