### ISSUE TITLE
[needs-docs][labeling] When using the Show/Hide Label tool, a single
click on a label toggles this label

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4020]
Original commit: https://github.com/qgis/QGIS/commit/d8a3031d65417075d0aa2ab8c94b6d177836d2e6 by nyalldawson

Unlike in marquee mode, where users must hold ctrl while dragging
over labels to hide them, when only a click on an existing label
is made we trigger a toggle of the label. It's a more intuitive
UX.

**Comment by lajunek** [comment]
@havatv the single-click action is described in short in https://docs.qgis.org/3.10/en/docs/user_manual/working_with_vector/vector_properties.html#labels-properties: 

>  If you click or drag an area holding Shift, then label(s) are hidden. When a label is hidden, you just have to click or drag an area around the feature’s point to restore its visibility.

IMHO we can close this issue

**Comment by lajunek** [comment]
@havatv ok, I see. We only describe working with Shift. I will mention the single-click for hiding the labels.
