### ISSUE TITLE
[FEATURE] Allow copying symbols from style manager

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4032]
Original commit: https://github.com/qgis/QGIS/commit/732bc29322ca86aaf7e397d3be8745d6666c19dc by nyalldawson

Allows symbols to be copied from the style manager dialog, so that
they can be pasted elsewhere in QGIS (e.g. in symbol or color buttons)

**Comment by DelazJ** [comment]
See https://docs.qgis.org/testing/en/docs/user_manual/style_library/style_manager.html#adding-editing-or-removing-an-item

**Comment by lajunek** [comment]
@nyalldawson can you give precise information (or link to information) about pasting the style in symbol or color buttons?
