### ISSUE TITLE
[FEATURE] Add "Paste" action to style manager dialog menu

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4033]
Original commit: https://github.com/qgis/QGIS/commit/644c002c8dd09d2c2eb2b984b745d17ef3894326 by nyalldawson

Allows pasting copied symbols directly into a style

**Comment by DelazJ** [comment]
see https://docs.qgis.org/testing/en/docs/user_manual/style_library/style_manager.html#adding-editing-or-removing-an-item
