### ISSUE TITLE
[needs-docs] Show current tags for symbol when right clicking a symbol
in style manager

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4034]
Original commit: https://github.com/qgis/QGIS/commit/d775061bc6a01b9cc0c994dee3733d0c5e3db10d by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment]
At https://docs.qgis.org/testing/en/docs/user_manual/style_library/style_manager.html#adding-editing-or-removing-an-item
