### ISSUE TITLE
Documentation for shape toolbar

### ISSUE THREAD

**Issue by lbartoletti** [qgis/QGIS-Documentation#4038]
## Description

@SrNetoChan @pigreco 
To do with our discussion on twitter, here some information about all tools in the shape toolbar.

There is a [section](https://github.com/qgis/QGIS-Documentation/blob/master/source/docs/user_manual/working_with_vector/editing_geometry_attributes.rst#shape-digitizing) about it, containing only an information for circular string / arc.

For every tool, you can enter coordinate with The Advanced Digitizing panel.

## Circle:

Circles are converted to circular string, so it can be in curved geometry or not depending of the data provider.

- **Circle from 2 points**: Points define the diameter and the orientation of the circle. / Left click, right click.[QCAD manual](https://qcad.org/doc/qcad/latest/reference/en/scripts/Draw/Circle/Circle2P/doc/Circle2P_en.html)
- **Circle from 3 points**: Draws a circle from three known points on the circle. / Left click, left click, right click.[QCAD manual](https://qcad.org/doc/qcad/latest/reference/en/scripts/Draw/Circle/Circle3P/doc/Circle3P_en.html)
- **Circle from center and a point**: Draws a circle with a given center and a point on the circle. With advanced digitizing panel can be "center and a radius" using the distance tool  / Left click, right click. [QCAD manual](https://qcad.org/doc/qcad/latest/reference/en/scripts/Draw/Circle/CircleCP/doc/CircleCP_en.html)
- **Circle from 3 tangents**: Draws a circle that is tangential to three entities. **You have to activate snapping segment.** Obviously, you must click on a segment to add a tangent. If two tangents are parallels a message appear and clear input. <-- but I don't remember why I did that... bug report https://github.com/qgis/QGIS/issues/30933  / Left click (on a segment), left click (on a segment), right click (on a segment).[QCAD manual](https://qcad.org/doc/qcad/latest/reference/en/scripts/Draw/Circle/Circle3T/doc/Circle3T_en.html)
- **Circle from 2 tangents and a point**: As circle from 3 tangents, except that you have to select to tangents, enter a radius and select the center. This tool is the same as QCad and not as AutoCAD. https://twitter.com/lo_bartoletti/status/1154278602046943233   / Left click (on a segment), left click (on a segment), right click. [QCAD manual](https://qcad.org/doc/qcad/latest/reference/en/scripts/Draw/Circle/Circle2TR/doc/Circle2TR_en.html)

## Ellipse:

Ellipse cannot be converted as circular string, so it will always segmented.

- **Ellipse from center and two points**: Draws ellipses with a given center, major axis and minor axis.   / Left click, left click, right click. [QCAD manual](https://qcad.org/doc/qcad/latest/reference/en/scripts/Draw/Ellipse/EllipseCPP/doc/EllipseCPP_en.html)
- **Ellipse from center and a point**: Like an ellipse drawn into a bounding box with center and a corner.   / Left click, right click.
- **Ellipse from extent**: An ellipse into a bounding box  / Left click, right click.
- **Ellipse from foci**: Draws an ellipse by 2 points for foci and a point on the ellipse.   / Left click, left click, right click.https://en.wikipedia.org/wiki/Ellipse#/media/File:Ellipse-var.svg

## Rectangle:
- **Rectangle from center and a point**: Draws an orthogonal rectangle from the center and a corner / Left click, right click.
- **Rectangle from extent**: Same but with diagonal points / Left click, right click.[QCAD manual](https://qcad.org/doc/qcad/latest/reference/en/scripts/Draw/Shape/ShapeRectanglePP/doc/ShapeRectanglePP_en.html)
- **Rectangle from 3 points (distance)**: Draws an oriented rectangle by 3 points. First and second point determine the first length. Third and second point, the second length. The rectangle is oriented by the points. First and second are corners of the rectangle. Third and fourth points are projected from first and second with the distance computed.  / Left click, left click, right click.
![illustration](https://user-images.githubusercontent.com/7521540/61991742-2ae6fa80-b055-11e9-91df-650f0d0e6f0e.png)
- **Rectangle from 3 points (projected)**: https://github.com/qgis/QGIS/pull/8480 Same as precedent, but the distance is computed from a projection of the third point on the segment of the first and second point.   / Left click, left click, right click.
![Illustration](https://user-images.githubusercontent.com/7521540/61991757-510c9a80-b055-11e9-822d-f7ed24ca6481.png)

## Regular polygon

Left click, and a dialog appear to enter the number of side. Right click to finish.

- **Regular polygon from center (and a corner)**: The corner defines the orientation of the regular polygon. [QCAD manual](https://qcad.org/doc/qcad/latest/reference/en/scripts/Draw/Shape/ShapePolygonCP/doc/ShapePolygonCP_en.html)
- **Regular polygon from 2 corners**: Creates polygons with two corners given. [QCAD manual](https://qcad.org/doc/qcad/latest/reference/en/scripts/Draw/Shape/ShapePolygonPP/doc/ShapePolygonPP_en.html)

Note: You may find on other software, something like "Square from center", "circle from center and radius", etc. but the are useless as it can be drawn with other tools ("regular polygon from center", "circle from center and a point", ...) and the advanced digitizing panel

## Related PR in QGIS:
First PR for the tool, with a little doc and screencast: https://github.com/qgis/QGIS/pull/4947
Second PR for rectangle by 3 points (projected): https://github.com/qgis/QGIS/pull/8480

**Comment by lbartoletti** [comment]
For left-click / right-click. There is an opened issue https://github.com/qgis/QGIS/issues/25598 by @DelazJ

**Comment by pigreco** [comment]
thanks a lot

**Comment by SrNetoChan** [comment]
The examples are very good. thanks. I will try to write the necessary docs for this interesting tools

**Comment by DelazJ** [comment]
> First PR for the tool, with a little doc and screencast: qgis/QGIS#4947
Second PR for rectangle by 3 points (projected): qgis/QGIS#8480

PRs that respectively generated #2179 and #3172 so don't forget to close them also.

**Comment by SrNetoChan** [comment]
Only a part of the features were described. Let's keep this open or we will forget it.

**Comment by SrNetoChan** [comment]
@lbartoletti I have just noticed that there's a tool called Ellipse from foci. Isn't Foci the Italian translation for Focus?

**Comment by lbartoletti** [comment]
> @lbartoletti I have just noticed that there's a tool called Ellipse from foci. Isn't Foci the Italian translation for Focus?

In English, foci is the plural of focus. There is two focus in an ellipse. https://www.mathopenref.com/ellipsefoci.html
The Italian translation of foci should be 'fuochi', 'foyers' in French (and 'focos' in Portuguese?) .

**Comment by SrNetoChan** [comment]
> > @lbartoletti I have just noticed that there's a tool called Ellipse from foci. Isn't Foci the Italian translation for Focus?
> 
> In English, foci is the plural of focus. There is two focus in an ellipse. https://www.mathopenref.com/ellipsefoci.html
> The Italian translation of foci should be 'fuochi', 'foyers' in French (and 'focos' in Portuguese?) .

All good then. Em Portuguese its Focal and the plural Focais.
