### ISSUE TITLE
[FEATURE][labelling] Expose "label all parts" option via label
properties tool

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4046]
Original commit: https://github.com/qgis/QGIS/commit/5911f96fa9aac80793328c594d130389a0f2cf5d by nyalldawson

Makes it easier to set this option per-feature

**Comment by lajunek** [comment]
@nyalldawson were you talking about this:
![label_properties_dialog](https://user-images.githubusercontent.com/47246213/71557573-3c8b5e80-2a48-11ea-98da-9577c1ea104a.PNG)

**Comment by nyalldawson** [comment]
@lajunek yes, that's it!
