### ISSUE TITLE
[needs-docs] Add option to show superseded (but not deprecated)
coordinate operations when selecting operations

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4049]
Original commit: https://github.com/qgis/QGIS/commit/2aec816b16f52821ae906e371bf65e97e9288fd1 by nyalldawson

This is the closest equivalent for the existing "hide deprecated"
checkbox which is available in proj < 6 builds.

Requires Proj >= 6.2

**Comment by felixfeckler** [comment]
Removed with [#33474](https://github.com/qgis/QGIS/pull/33474).
