### ISSUE TITLE
[FEATURE] Add "copy symbol" and "paste symbol" actions to layer right click, style menu

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4055]
Original commit: https://github.com/qgis/QGIS/commit/47f83b582f4631ab8522e310f940ba53d18168f2 by nyalldawson

Allows for individual symbols to be copied and pasted between layers or rule/categorized/graduated
nodes

**Comment by DelazJ** [comment]
https://docs.qgis.org/testing/en/docs/user_manual/introduction/general_tools.html#overview-of-the-context-menu-of-the-layers-panel
