### ISSUE TITLE
[FEATURE] Add option to georeference PDFs and TIFs to save map canvas as image/PDF

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4083]
Original commit: https://github.com/qgis/QGIS/commit/2e4a5677b512bbd67d4ff5f826e851ad81cc81cd by nirvn

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment]
Should be fixed with #4437.
