### ISSUE TITLE
[needs-docs][layout] Limit georeferencing of exported PDFs when reference map is on the first page

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4085]
Original commit: https://github.com/qgis/QGIS/commit/4b0b8d4c93f834267e8d3a48b6d0375a01c1d388 by nirvn

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment]
Concerns layouts.

Georeferencing PDFs is only possible when there is a reference map on the first page. Correct, @nirvn?

**Comment by roya0045** [comment]
This seems to mostly add the georeference check. Which was included in #4483, I think this can be closed.
