### ISSUE TITLE
[FEATURE][expression] Optional format parameter for to_date, to_datetime, to_time functions

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4088]
Original commit: https://github.com/qgis/QGIS/commit/b58a2a6c21f70ea4de9d44558257caa75dc3094f by nirvn

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment]
We do not document functions in details so I think we can close this one
