### ISSUE TITLE
[needs-docs] Rename "Source Fields" into "Fields" in vector layer properties dialog

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4089]
Original commit: https://github.com/qgis/QGIS/commit/f9b4d86898075a9adc1f24f474503d09cff9c37f by DelazJ

Unfortunately this naughty coder did not write a description... :-(

**Comment by haridevelops** [comment]
@QGIS-feature-tracker can you let me know what needs to be done, i can help you with this ..

**Comment by DelazJ** [comment]
Hi @haridevelops 
@QGIS-feature-tracker is a bot we use to automatically generate issue reports based on features created in QGIS application.
To solve this issue, you'd need to replace occurrences of "Source fields" in https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/vector_properties.html
Update the screenshot in the "[source fields](https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/vector_properties.html#source-fields-properties)" section would be good also.
Thanks for your offer.
