### ISSUE TITLE
[FEATURE] Add GUI option when exporting canvas to PDF for GeoPDF export

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4093]
Original commit: https://github.com/qgis/QGIS/commit/ec42cc76d3db998e52fd6273f1c12207c0de631a by nyalldawson

Adds a checkbox allowing users to control whether GeoPDF files should
be created when exporting the canvas as a PDF. If GeoPDF isn't available
(e.g. due to having GDAL < 3.0, or GDAL built without PDF read support),
then this option is disabled and an explanation shown as to why instead.

**Comment by havatv** [comment]
Should be fixed with #4437.
