### ISSUE TITLE
[FEATURE] Add option on whether to include RDF metadata during
save map to GeoPDF operations

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4094]
Original commit: https://github.com/qgis/QGIS/commit/8d89dd99cd8d92a4976d3c651747be5b547fc529 by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by lajunek** [comment]
@hatav there is a description of the "Export RDF metadata" option. I think we can close this issue.
