### ISSUE TITLE
[needs-docs] Expose choice of GeoPDF export format to users

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4096]
Original commit: https://github.com/qgis/QGIS/commit/446eb066d5faaa45e9efee6c7a88207c3dad8086 by nyalldawson

Either "ISO3200 extension" or "OGC 'best practice'" options are availab.e

ISO3200 format is recommended, and results in Geospatial PDF files compatible
with the built-in Acrobat geospatial tools.

The OGC Best Practice format results in GeoPDF files compatible with the TerraGo
suite of tools, but can break compatibility with the built-in Acrobat
geospatial tools (yes, GeoPDF format is a mess!).

**Comment by havatv** [comment]
Should be fixed with #4437.

**Comment by DelazJ** [comment]
Since #4437 does not go into details can we keep this open? this imho is part of the enhancement Alex was mentioning in the other thread.

**Comment by DelazJ** [comment]
OK I see #4440. Re closing ;)
