### ISSUE TITLE
[FEATURE] Brand new map canvas image decoration (#31291)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4100]
Original commit: https://github.com/qgis/QGIS/commit/a726f4f7fca0fd4c70a6b8da6a56fd0cdf484d37 by web-flow

Unfortunately this naughty coder did not write a description... :-(

**Comment by diethard2** [comment]
It is described in the visual changelog for https://qgis.org/nl/site/forusers/visualchangelog310/index.html#feature-new-map-canvas-image-decoration.
I have tested the new feature and see it works great to allways draw a picture in the same position on the screen, so it is great for example for presentations etc..

**Comment by diethard2** [comment]
Described in master and release_3.10
