### ISSUE TITLE
[FEATURE][layouts] Option to export multiple map themes while
creating GeoPDF documents from layouts

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4105]
Original commit: https://github.com/qgis/QGIS/commit/dbf9d917dd749d36397dd0a5ce2328e93bf20af9 by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment]
Should be fixed with #4437.
