### ISSUE TITLE
[FEATURE] Add UI for configuring layer-by-layer export attributes and layer groups to GeoPDF export

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4112]
Original commit: https://github.com/qgis/QGIS/commit/7c22da07f52e5132fcf30f64254bdab37d521b66 by nyalldawson

Allows users to set on a layer-by-layer basis whether layers should be identifiable
and include vector features in a GeoPDF export, and optionally whether to group multiple
layers together into a single logical, switchable entry in the GeoPDF layer tree.

**Comment by havatv** [comment]
Should be fixed with #4437.
