### ISSUE TITLE
[FEATURE] When a layer path is fixed in a project, auto scan through
all other broken paths and try to auto-fix any others which were
also pointing to the same original broken file path

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4124]
Original commit: https://github.com/qgis/QGIS/commit/f62f85769e509ce77b43e07a6a76f8e2b36fec28 by nyalldawson

AKA the ArcMap behavior

**Comment by lajunek** [comment]
@havatv I think we can describe the handling of broken file paths in "Managing Data Source"
