### ISSUE TITLE
 add feeding of layout pictures with blobs

### ISSUE THREAD

**Issue by jef-n** [qgis/QGIS-Documentation#4133]
Original commit: qgis/QGIS@ea4756ab1a26d by jef-n

**Comment by lajunek** [comment]
@jef-n can you give a description about the new functionality in QGIS? Or a link to a description?

**Comment by lajunek** [comment]
@hatav do you know about this new functionality? Is there a description in the web?

**Comment by havatv** [comment]
> @hatav do you know about this new functionality? Is there a description in the web?

I guess that it means that you can use images stored as BLOBs in table fields directly. Currently image fields have to contain file URLs (strings).

**Comment by lajunek** [comment]
@hatav I checked out a drag&drop from a windows browser. First create a new picture item in the print layout and then adding the picture from the browser. There is attached a +copy functionality, but what does the user have to do in detail to finally import the picture!

**Comment by havatv** [comment]
I guess drag and drop is not supported. I tried to check the code, and It seems as if the BLOB has to be a QImage object, but you should ask the developers for verification (and more information).

**Comment by jef-n** [comment]
QGIS can use blob fields in datasources (e.g. PostgreSQL).  These can be used in QGIS to upload files to them or save their content to files.  Above adds the option to use the stored data as input for legend pictures, before you could only references files.

**Comment by jef-n** [comment]
@andreasneumann was that actually used the the FOSS4G 2019 workshop and are there slides?

**Comment by havatv** [comment]
> QGIS can use blob fields in datasources (e.g. PostgreSQL). These can be used in QGIS to upload files to them or save their content to files. Above adds the option to use the stored data as input for legend pictures, before you could only reference files.

@jef-n, was I correct in assuming that only QImage objects are supported?
And can these BLOB fields be used in layouts / reports / atlases (in addition to legends)?

**Comment by lajunek** [comment]
@jef-n @havatv @andreasneumann studiying the item properties of the legend I found these in the expression string builder:
![grafik](https://user-images.githubusercontent.com/47246213/82814060-a9d7da00-9e96-11ea-9c90-7866d466852c.png)
Do the BLOBs hidden in these expressions?

**Comment by havatv** [comment]
These should not have anything to do with BLOBs - only "traditional" file / directory structure functions as far as I can tell.

**Comment by havatv** [comment]
> @jef-n @havatv @andreasneumann studiying the item properties of the legend I found these in the expression string builder:
> 
> Do the BLOBs hidden in these expressions?

These should not have anything to do with BLOBs - only "traditional" file / directory structure functions as far as I can tell.

**Comment by lajunek** [comment]
@havatv this is what i assumed, too.

**Comment by andreasneumann** [comment]
Sorry, that discussion slipped my attention.

That workshop can be found at: https://gitlab.com/aneumann/qgis-layouts-atlas-reports

But: I didn't cover this blob thing in the workshop. @jef-n and I sat next to each other when I was preparing for the workshop and we discussed that it would be useful to also load an image directly out of a PG blob column. Jef implemented it shortly after ;-)

As far as I remember, you just assign the attribute field. That's all. No more magic. QGIS detects that the field is a blob and extracts the image.

As far as I remember you create a blob column in PostgreSQL and you paste a base64 encoded image (png, jpeg or svg) into it. You can use a service, like https://www.base64-image.de/ to convert your image, or use a commandline tool for the conversion.

Disclaimer: I didn't try it out now. But I remember that worked like this. I will try it out tonight and will report back about it.

**Comment by lajunek** [comment]
@andreas did you check out the BLOB?

**Comment by andreasneumann** [comment]
@lajunek - Thanks for the reminder. I just tested it out. It works fine. No need to base64 encode it (opposing my above statement).

Here is an explanation how it works:

1. You need a column of type "bytea" in PostgreSQL:
![image](https://user-images.githubusercontent.com/884476/83653869-9a564080-a5bc-11ea-9d46-9148492fa5df.png)

2. In some software (I used dbeaver) just load an image file (PNG, JPEG and SVG all work fine). No need to base64 encode it. Just load it:
![image](https://user-images.githubusercontent.com/884476/83654039-dab5be80-a5bc-11ea-8c4f-044c57be0869.png)

3. In QGIS in the layout in Atlas context you can select an expression of a raster image:
![image](https://user-images.githubusercontent.com/884476/83653768-7abf1800-a5bc-11ea-9f83-c54bcb7205ff.png)

4. in the expression editor just type the column name:
![image](https://user-images.githubusercontent.com/884476/83654216-13559800-a5bd-11ea-9959-dd727916e32c.png)

**Comment by andreasneumann** [comment]
Ah - step 2 could also be done in QGIS:

![image](https://user-images.githubusercontent.com/884476/83654488-7ba47980-a5bd-11ea-95c0-dfc66f5ced69.png)

**Comment by andreasneumann** [comment]
So it actually works really fine - all within QGIS ;-) without the need of external software.

**Comment by lajunek** [comment]
@andreasneumann fine, thanks a lot !

**Comment by lajunek** [comment]
@andreasneumann thanks a lot. Now nearly clear: I still have the question when does the selection +svg image or +raster image appear? I just find picture --> item properties --> main properties --> Image source. I inserted an image to the layout and went to the Item properties in atlas context. Or does the Item Properties menu change when defining a picure in PostgreSQL?
Actually can we realize this in QGIS 3.10 LTR? 
This is where I'm stuck:
![grafik](https://user-images.githubusercontent.com/47246213/84173348-7479e180-aa7d-11ea-8516-5dac582dbac7.png)

**Comment by andreasneumann** [comment]
ah - I think I know your problem. You need to do this in atlas context.

Otherwise it wouldn't make much sense. If you have a static layout, you can also use a static image.

If you create an atlas, you can select the column with the binary file (image) in the list of fields, using the expression editor (data-defined button next to the image source):

**Comment by andreasneumann** [comment]
> Actually can we realize this in QGIS 3.10 LTR?

Yes, it works in QGIS 3.10. But only if you use the atlas context and the atlas coverage layer contains the column with the blob where the image is stored within. I guess it would also work from another table though, if you use getFeature(getAttribute()), etc - it would then also work from outside atlas, but it wouldn't make much sense to me to use a dynamic image source on a static layout?

**Comment by andreasneumann** [comment]
If you open the expression editor next to the image source, and the atlas is active, you should see all atlas colums in the category "Fields and Values". There you select the column containing the image. That's it. You don't even need the double quotes, normally, if you use lower case column names (as recommended in PostgreSQL anyway).

**Comment by lajunek** [comment]
@havatv @DelazJ @ghtmtt @SrNetoChan how do we want to implement the above descriptions. The user can create a bytea column for BLOBs in PostgreSQL tables and then refer to these files (images) from the atlas context. It is a dynamic image source then. 
We don't describe PostgreSQL in the user manual. Do we want to insert a tip into the "Generate an Atlas" section? We already implemented the usage of data-defined override, so we can place the tip here. Are there any votes for describing the layout pictures with blobs in the training manual?

**Comment by havatv** [comment]
@lajunek, Geopackage also supports BLOBs, so you don't need a relational database connection.
I think we can mention a BLOB field as an (easier) alternative for pictures in the "Generate an Atlas" section in the user manual. We should also consider to mention BLOB fields among the other possible field types in the relevant parts (working with vector data?) of the user manual.
I don't think we should give priority to the user manual (over the training manual).

BLOB support is already mentioned in "Creating a new GeoPackage layer" in the user manual, and the PostgreSQL binary type is also mentioned in the user manual (in "PostGIS Layers" - managing data sources).

**Comment by lajunek** [comment]
@andreasneumann shame on me - still have a question. In 3. you sent a screenshot where one can choose between 

- svg image

- raster image

Then (6 days ago), there is a screenshot where one just defines the image source with the expression editor. This is what I can create, too. But I don't have a menu like in 3. ....

**Comment by DelazJ** [comment]
@lajunek, This is because Andreas is using 3.13. The svg/raster selection UI is implemented in https://github.com/qgis/QGIS-Documentation/issues/5053
