### ISSUE TITLE
Training Manual refers to files that DO NOT exist in exercise_data folder

### ISSUE THREAD

**Issue by vicnsi** [qgis/QGIS-Documentation#4147]
## Description

Page URL:

**Comment by DelazJ** [comment]
@vicnsi we need more information. Eg page url, missing file name...

**Comment by vicnsi** [comment]
Hi! am newly learning QGIS. I have been trying to work along with the examples in the User guide & Training Manual; both keep refering to **exercise_data folder**, but files mentioned don't seem to be in there. I have done multiple re-installs to make sure during installation process that all datasets get downloaded. I even tried downloading **exercise_data** manually from https://qgis.org/downloads/data/

Example of page urls refering to missing folders/files/packages: 

https://docs.qgis.org/3.4/en/docs/training_manual/foreword/preparing_data.html
**3. Use the … button to browse to the exercise_data/shapefile/ folder and save the file as places.shp.**

https://docs.qgis.org/3.4/en/docs/training_manual/introduction/preparation.html
**4. Select the exercise_data/shapefile/protected_areas.shp file in your training** 

https://docs.qgis.org/3.4/en/docs/training_manual/basic_map/vector_data.html
**3. Click on the New button and browse to the training_data.gpkg file in the exercise_data folder you downloaded before.**


... etc...

**Comment by DelazJ** [comment]
Download instead the data at https://docs.qgis.org/3.4/en/docs/training_manual/foreword/foreword.html#data

**Comment by vicnsi** [comment]
Great! many thanks.
correct "Training data repository" is currently at: 
**https://github.com/qgis/QGIS-Training-Data/archive/v2.0.zip**

**Comment by Codym48** [comment]
Related to qgis/QGIS-Training-Data#21

**Comment by havatv** [comment]
Since the correct location of the download is described in the training manual, and https://qgis.org/downloads/data/ is not mentioned, I close this issue.
