### ISSUE TITLE
[FEATURE][oracle] Database transaction support

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4152]
Original commit: https://github.com/qgis/QGIS/commit/b656ce7ff4a0e40deba2acee1d1a9a8ebbbd8dfd by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by lajunek** [comment]
@havatv @DelazJ I think we don't have to go into detail here as we have just a description about how to connect to an oracle spatial database. Or should we add more information about working with oracle spatial databases?

**Comment by havatv** [comment]
Transaction groups are mentioned in the user manual (for instance in ch. 9), but only PostgreSQL is mentioned as relevant for this feature. We could perhaps ask @nyalldawson if he thinks that we should update the descriptions to also mention Oracle Spatial (and may be other database connection types?).

**Comment by lajunek** [comment]
@nyalldawson we deal with the descriptions about Oracle Spatial here. should we explain about Oracle spatial here  :?https://docs.qgis.org/3.10/en/docs/user_manual/introduction/qgis_configuration.html#data-sources-settings , chapter 9.3.5 Thanks, Larissa

**Comment by lajunek** [comment]
@nyalldawson when having database transaction support for Oracle, does the setting "Automatically create transaction group where possible" work too? so far, we say that this setting works with PostGIS layers.

**Comment by DelazJ** [comment]
Hi,
I think  that's the feature: extend this setting to Oracle. I'd suggest we either remove PostgreSQL or complete the list with GeoPackage or Oracle DB (for those I'm aware of). I don't think there's here a need to go into details.

**Comment by nyalldawson** [comment]
Thanks @DelazJ -- that's exactly correct

**Comment by elpaso** [comment]
@DelazJ and spatialite.

**Comment by DelazJ** [comment]
Thanks for the info @elpaso . The fix @lajunek provided was to not name any DB so should be fine.
