### ISSUE TITLE
[FEATURE][3D] Billboard Rendering for Points (#31308)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4154]
Original commit: https://github.com/qgis/QGIS/commit/b9978d53d11fc205207f98df8d749a1b8e3445be by wonder-sk

* Add button to change billboard symbol.

* Add shaders for billboards.

* Add billboard material class.

* Add sample billboard image.

* Add dummy handler for billboard.

* Add billboard geometry class.

* First working version of 3D point as billboard.

* Make selected feature bigger.

* Use default symbol preview as billboard.

* Update billboard when changes the viewport size.

* Use QgsTerrainTextureImage for adding image to texture.

* Show better quality of billboard default symbol.

* Promote QgsSymbolButton not working.

* Add QgsSymbolButton properly.

* Add seTexture2DFromSymbol.

* Use default symbol

* [On Progress] Get symbol from the QgsSymbolButton.

* [On progress] failed to change the symbol

* Fix billboard fragment shader for macOS

* Better transparency handling.

* Use size from the symbol.

* Add set layer for 3d billboard symbol.

* Set billboard size from the symbol pixel size * 20

* Use size from the image.

* [Debug] set white symbol to success kid, it work when previous billboard is success kid.

* Use store and restore symbol from Nyall.

* Remove unrelated code.

* Apply random extent to fix the bug, from Martin.

* Remove add mesh entities for billboard.

* Hide material and transformation widget for billboard.

* Remove add scene entities for billboard.

* Add selected as parameter in drawPreviewIcon.

* Add QgsMarkerSymbol to store the symbol in billboard

* Put billboard symbol in point3dsymbol serialization.

* Add billboard height in the UI.

* Set height for billboard.

* Store billboard height separately. Perhaps better to use existing transform.

* Set height of billboard to TY.

* Flipped image for billboard symbol.

* Add helper function to set billboard function.

* Generate billboard transform from general transform.

* Use static dpi for context size.

* Remove debug message.

* Use Qgs3DRenderContext for selection color and dpi from QgsApplication.

* Remove unnecessary file and code.

* Remove commented iut code.

* Add documentation of new classes.

* Fix banned keywords.

* Add missing parameter's documentation.

* Address PR review.

* Use context from readXML.

* Remove one line function.

* Fix billboard size.

* Make some functions private, remove unused function.

* Use unique_ptr for the ownership.

* Use unique_ptr for default symbol to avoid memory leak.

* Add parent to texture2D.

* Fix documentation.

* Add copy constructor.

* Fix documentation.

* Remove documentation warning.

* Fix sip error.

* Add unit test for billboard rendering.

* Set ambient to not transparent for measurement line.

* Add dpi in the Qgs3DMapSetting

* Update billboard rendering unit test.

* Remove layer from 3d point widget since it's not supported yet.

* Addressing PR review from Martin.

* Attach dom directly for the billboard symbol.

* Remove unused constructor for point3dsymbol.

* Use stroke width ratio for solving big stroke width.

* Update unit test for rendering with some stroke color.

* Fix typo.

**Comment by lajunek** [comment]
@wonder-sk are the billboard forms a way to depict points in 3D when the others forms are not possible?

**Comment by lajunek** [comment]
@DelazJ I want to expand 'The Vector Properties Dialog' with the '3D View' feature (including the billboard shape) first and then add a description of the 3D Map View feature (still have to look for a suitable place)

**Comment by DelazJ** [comment]
@lajunek Go ahead, please. Just: I'm not sure of how the vector properties dialog is close to the billboard shape but fyi we have https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_gui.html#d-map-view about the "3D map view" in which the billboard widget is embedded afaict.

**Comment by lajunek** [comment]
@havatv @DelazJ @SrNetoChan is there detailed information about the settings of the 3D View properties available?

**Comment by havatv** [comment]
> @havatv @DelazJ @SrNetoChan is there detailed information about the settings of the 3D View properties available?

@lajunek I don't think so.
We probably have to rely on the developers and the code. The developers often describe / announce new features on the web, so you may find useful information out there.

**Comment by lajunek** [comment]
@andreasneumann Hello Andreas I found https://www.youtube.com/watch?v=Nj014eOZaAc , can you give a short description about setting a sphere for usage of point layers in the 3D View tool? I didn't find the clue so far in the layer properties 3D View tab. Would like to make a screenshot. Thanks.

**Comment by lajunek** [comment]
@wonder-sk For documentation purposes I'd like to set up in QGIS 3.10 a small 3D scene (to prevent the 3D view tool from crashing) and place some point vectors defined by a billboard symbol on it. Can you give a recommendation which data I could use? I have the idea to use qgis_sample_data, SR_50M_alaska_nad.tif for elevation, but I'm stuck in setting this up for the 3D-view as I just created a flat scene in the 3D view tool. It would be nice answering my question as there is only small information about the 3D View tool in the internet.

**Comment by lajunek** [comment]
@wonder-sk when setting the "billboard height", does the size refer to the units of the chosen CRS in the QGIS project?
