### ISSUE TITLE
[needs-docs] Labels toolbar actions no longer need the layer to be in edit mode

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4162]
Original commit: https://github.com/qgis/QGIS/commit/c70d3cef2b54588c4acedc6df85a202eae9abb82 by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by lajunek** [comment]
@nyalldawson I see that in QGIS 3.4.5 I don't need to be in edit mode. What is exactly the new feature here, in QGIS 3.10 (testing)?
