### ISSUE TITLE
[FEATURE][layouts] Data defined control over grid properties

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4164]
Original commit: https://github.com/qgis/QGIS/commit/658cb0c74035647e26a652b72ae1c491373c7d60 by nyalldawson

Adds data defined control over layout map grid:
- enabled state
- interval X/Y
- offset X/Y
- frame size and margin
- annotation distance from frame
- cross size
- frame line thickness

Fixes #30246, fixes #27737

**Comment by DelazJ** [comment]
I think this does not need to be written: dd button is well-known now and [screenshots](https://docs.qgis.org/testing/en/docs/user_manual/print_composer/composer_items/composer_map.html#grid-appearance) reflect the features. I suggest we close.
@havatv?
