### ISSUE TITLE
[needs-docs][layouts] Move grid "enabled" check box to grid properties
panel

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4165]
Original commit: https://github.com/qgis/QGIS/commit/2d45eb5c70f3de4b343e3b2c11dea05e1815cb0d by nyalldawson

Allows it to sit next to the corresponding data defined button

**Comment by DelazJ** [comment]
At https://docs.qgis.org/testing/en/docs/user_manual/print_composer/composer_items/composer_map.html#grids

**Comment by lajunek** [comment]
@DelazJ I will implement this new feature

**Comment by DelazJ** [comment]
@lajunek If you don't mind I have a branch on this that I forgot to push online. I could do it later tonight and have your feedback on it?
