### ISSUE TITLE
[FEATURE][layouts] Add "fit segment size" mode for map grid interval

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4166]
Original commit: https://github.com/qgis/QGIS/commit/1e409fcee41db3ecf4808e57d6390d582c207756 by nyalldawson

Like the existing scalebar setting of the same name, this allows
users to set a page-size-based range for map grid intervals. The
grid interval will be dynamically calculated based on the map
extent and scale to pick the largest possible "pretty" interval
which results in grid sizes inside the desired range.

**Comment by DelazJ** [comment]
At https://docs.qgis.org/testing/en/docs/user_manual/print_composer/composer_items/composer_map.html#grid-appearance
