### ISSUE TITLE
[FEATURE] Allow array values as a valid result for data defined offset
or size properties

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4171]
Original commit: https://github.com/qgis/QGIS/commit/ddbb1b175f20f6e275fa4df93002276d5f51a36a by nyalldawson

Previously only string values of the format 'x,y' would be permitted. But
I've seen MANY bug reports and questions about this, so also allow
arrays of doubles as a valid result. E.g. "array(3,5)". In any case, it's
just nicer.

Fixes #31444

**Comment by DelazJ** [comment]
Can't see any placeholder for this. We don't go at this level of details, unless showing an example.

**Comment by DelazJ** [comment]
Closing...
