### ISSUE TITLE
[FEATURE] New expression function "collect_geometries"

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4173]
Original commit: https://github.com/qgis/QGIS/commit/36173d7c4039243f44978735cc0c810d356a0e7d by nyalldawson

Collects a set of geometries into a multi-part geometry object.
Geometry parts can either be specified as seperate arguments to the
function, or (more flexibly), as an array of geometry parts.

This allows geometries to be generated using iterator based approaches,
such as transforming an array generated using generate_series, e.g:

  collect_geometries(
    array_foreach(
      generate_series( 0, 330, 30),
      project($geometry, .2, radians(@element))
    )
  )

Gives a nice radial effect of points surrounding the central feature
point when used as a MultiPoint geometry generator

**Comment by DelazJ** [comment]
https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/expression.html#geometry-functions
