### ISSUE TITLE
[FEATURE] Add make_line expression function variant which accepts
an array of points

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4174]
Original commit: https://github.com/qgis/QGIS/commit/80d77b4788a08b8daa9782e3b99de4c56b48c074 by nyalldawson

Allows creation of lines from variable numbers of points, and
from sequences from aggregates/dynamically generated sequences

Fixes #31268

**Comment by DelazJ** [comment]
At https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/expression.html#geometry-functions (and we could also extend the existing description with an example of this alternative)
