### ISSUE TITLE
[FEATURE] Symbol feature expression

### ISSUE THREAD

**Issue by roya0045** [qgis/QGIS-Documentation#4186]
## Description

The feature is not yet fully implemented,

This feature allows the used to specify an expression for a given layer in the legend. This expression will be applied to each symbol of this layer.

To specify the expression simply select the desired layer, in the layout symbology and click the rightmost button below the legend items (see gif below).

Currently the expression are not fully operational but possibly in the next release aggregate expressions should have an extra parameter that will allow to evaluate the expression only on the features of the symbol.

This should be enabled by adding `symbol_id:=@symbol_id` to the expression once https://github.com/qgis/QGIS/pull/9915 and https://github.com/qgis/QGIS/pull/30727 are merged.

This image showcases the first prototype.
![ext](https://user-images.githubusercontent.com/12854129/64112377-36fd6080-cd55-11e9-85af-a3f689f581d0.gif)

**Comment by roya0045** [comment]
@DelazJ Let me know what changes to make to make things coherent. The fact that this needed to be split in multiple PR due to the complexity and the speed of the merging process mean that the next release will have a semi functional feature ( it will work but not up to its fullest capacity).

**Comment by DelazJ** [comment]
I'm not sure whether I understand the question since I don't know the level of the implementation, yet. But generally speaking, I think the doc should reflect what is actually implemented in the application, ie anything worth documenting that is available in <=3.10 will be pushed to the current master and anything that comes later will have to wait for the next branch.
I can see two places where the features would go:
* https://docs.qgis.org/testing/en/docs/user_manual/print_composer/composer_items/composer_legend.html#legend-items for the new button (hence new screenshot), explanation  and an example of expression ( and rendering?) could be great
* https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/expression.html#variables-functions for the new variables you are introducing

**Comment by roya0045** [comment]
I agree with your assessment, I will try to check if I still have my prototype on my VM to provide a screenshot for the legend, at aleast enough to edit the image.

Do you want that documentation for the two items here or elsewhere/in separate PR/Issues?

**Comment by roya0045** [comment]
![legend_qgis](https://user-images.githubusercontent.com/12854129/64123217-bf89fa00-cd71-11e9-8e89-9801cb64183a.PNG)
Here is the legend, the icon itself is located at https://github.com/qgis/QGIS/blob/master/images/themes/default/mActionAddExpression.svg

Let me know if this is satisfactory.

Concerning the variable those are only available when there is the symbol scope IE when the button is clicked in the legend.

Here are the variables
1. "symbol_label", "Label of the symbol, user defined label will be used, otherwise will default to the label made by QGIS."
2. "symbol_id", "Id of the symbol."
3. "symbol_count", "Total number of features defined by this symbol."

No new variable shall be added, but a parameter might be added in the aggregate expression to accept the symbol_id variable

In the meantime I could add a gif if you need something in particular.

**Comment by DelazJ** [comment]
> Do you want that documentation for the two items here or elsewhere/in separate PR/Issues?

TBH, Documentation improvement are better served as PRs. The most atomic, the better. So if you can provide some, please go ahead. We'd greatly appreciate. As you might know, we are looking for help. From the footer of the links I sent above, you should directly be able to edit the source files in your fork.
> Here is the legend, the icon itself is located at https://github.com/qgis/QGIS/blob/master/images/themes/default/mActionAddExpression.svg
>Let me know if this is satisfactory.

Should be! Even better in a PR 😉 
May I ask why a new icon has been set here? Was the simple [expression](https://docs.qgis.org/testing/en/_images/mIconExpression.png) icon, used to apply expression in many other areas, not enough?
> In the meantime I could add a gif if you need something in particular.

Not necessary I think. We do not use gif in the docs (for the moment? And actually I don't know how it'd play in pdf) but I think it's something you can keep for the changelog.
Thanks for offering your help @roya0045

**Comment by roya0045** [comment]
> May I ask why a new icon has been set here? Was the simple [expression](https://docs.qgis.org/testing/en/_images/mIconExpression.png) icon, used to apply expression in many other areas, not enough?
In this case I wanted to distinguish it from the filter expression and I felt that this icon conveyed the message better as it allows the user to add an expression to the existing label text (which gets converted to a variable for ease of use in the expression.)

**Comment by DelazJ** [comment]
Hmmm. Sorry but I fail to see the difference with the expression button which also adds an expression to an existing label, replaces it with anything else... (maybe the trick is in "which gets converted to a variable for ease of use in the expression" which is not yet clear to me). I'm not sure that adding a new icon is worth it (actually, this icon was already used and its occurrences have been replaced with the expression one, for consistency). Also, the expression button becomes yellow/red in some context, is this behavior available with this icon?
Anyways, these are more development considerations than docs'. and sorry for the "digression".

**Comment by roya0045** [comment]
Was this icon already in use? I remember making it it to contrast with the filter icon, maybe this can be debated in the mailing list, I don't mind too much but I felt that users might think that this icon would be an error and just a bad 'expression filter icon' rather than something else. Adding this is the doc is for consistency.

**Comment by DelazJ** [comment]
> Was this icon already in use?

No. I checked and  I was confused with another icon. Sorry about that.
