### ISSUE TITLE
[FEATURE][API] New class QgsBookmarkManager

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4198]
Original commit: https://github.com/qgis/QGIS/commit/d8300987e84ccb2e442a18e0551c400db4794082 by nyalldawson

Attached to QgsProject, this provides a stable, supported method
of managing project bookmarks (vs the old undocumented, not stable
approach of directly manipulating project keys)

**Comment by DelazJ** [comment]
API related. Not to document.
