### ISSUE TITLE
WMS OGC Filter

### ISSUE THREAD

**Issue by alexlionnel** [qgis/QGIS-Documentation#4205]
Hello.How can i use ogc filter in wms query?

**Comment by DelazJ** [comment]
@alexlionnel 
I'm not sure I understand your question but in all cases, better ask for help in qgis-user list (see [support channels](http://qgis.org/en/site/forusers/support.html)).
This repository is actually dedicated to the doc writing.
Thanks.

**Comment by alexlionnel** [comment]
The problem is that the 'like' or 'contains' filter does not work for wfs query
