### ISSUE TITLE
[FEATURE] Allow bookmarks to be dragged onto map canvases to zoom to bookmark

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4207]
Original commit: https://github.com/qgis/QGIS/commit/f26f77c6677cfdd72d872c3a2f0db4d8c0e1a880 by nyalldawson

This allows bookmarks to play nice in multi-canvas projects, since you can
drop them onto a specific canvas to zoom

**Comment by SrNetoChan** [comment]
Fixed by #4871
