### ISSUE TITLE
[FEATURE] "Reselect Features" action in Edit -> Select menu

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4216]
Original commit: https://github.com/qgis/QGIS/commit/3af35b584483fe9c02e1f1e4958d5fc83531dbae by nyalldawson

Allows restoration of a layer's selection following a selection
clear operation. Handy for anyone who has ever painstakingly
built a custom selection only to accidently click and clear
this selection...

**Comment by DelazJ** [comment]
May be at https://docs.qgis.org/testing/en/docs/user_manual/introduction/general_tools.html#sec-selection (And/or https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_gui.html#edit with other subitems?)

**Comment by nickbearman** [comment]
With the https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_gui.html#edit page, should we add all 10 selection options, because this is quite a lot?
![selection](https://user-images.githubusercontent.com/6410645/65374685-8cf26380-dc84-11e9-9846-6f5dbe7a6c2e.png)

**Comment by DelazJ** [comment]
I'd personally keep it as is. No details there and expand the description in general tools section

**Comment by nickbearman** [comment]
Thanks, yes I would say just have the change in General Tools, and don't add to the QGIS GUI page.
