### ISSUE TITLE
Digitize the geometry from the relation reference widget add button (#30905)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4217]
Original commit: https://github.com/qgis/QGIS/commit/3abbc0f178d7c5e1f15ae8dc24dc4c673626d7cd by m-kuhn

* [FEATURE] [needs-docs] Add the possibility to digitize the geometry
when creating a feature from the plus button on the relation reference widget

**Comment by lajunek** [comment]
@m-kuhn when talking about the plus button: is this the `Add child feature` button?

**Comment by lajunek** [comment]
@m-kuhn i found this
![plusbutton_relation_reference_widged](https://user-images.githubusercontent.com/47246213/71622332-5dcd8580-2bd5-11ea-9441-8b294bbc2a6d.PNG)

**Comment by lajunek** [comment]
@m-kuhn found the plus button for the relation reference widged

**Comment by m-kuhn** [comment]
Thanks @lajunek let me know if you have open questions
