### ISSUE TITLE
[FEATURE] Parallelize snap index build

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4218]
Original commit: https://github.com/qgis/QGIS/commit/ead7481e3f8c3be698f14be8fbf9ed304e11e438 by troopa81

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment]
I'm not sure there's anything of interest for the manual here

**Comment by SrNetoChan** [comment]
I agree with @DelazJ . this is a under the hood improvements. I'm closing this one.
