### ISSUE TITLE
[delimiter text] Add Point{Z,M,ZM} geometry support (fixes #25645) (#31595)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4220]
Original commit: https://github.com/qgis/QGIS/commit/5df309447ebac64a8f58640472ffabf7d3b57179 by web-flow

[FEATURE][delimiter text] Add Point{Z,M,ZM} geometry support (fixes #25645)

**Comment by DelazJ** [comment]
https://docs.qgis.org/testing/en/docs/user_manual/managing_data_source/opening_data.html#importing-a-delimited-text-file

**Comment by lajunek** [comment]
@DelazJ I'd like to update the screenshot `delimited text dialog.png` in the above mentioned section. Will the `:align: center` adapt the size of the screenshot?
