### ISSUE TITLE
[needs-docs] Use "Value" as standard label of the widget

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4230]
Original commit: https://github.com/qgis/QGIS/commit/3c65e52057adc808da2182a4d92caef6b2662e00 by nyalldawson

to filter labeling and symbology (categorized, graduated)
instead of "Label with" and "Column"

**Comment by SrNetoChan** [comment]
Will we need to update the training manual to close this one? I mean, lot's of stuff is outdated on the training manual which are not tagged with training manual. Besides, I think the training manual needs a top-to-bottom approach for updating.

**Comment by havatv** [comment]
It is possible to create a list of places where updates are needed. Then we can keep track of things.
Personally, I think that it is most important to keep the user manual updated.
