### ISSUE TITLE
Description text does not fit into the Methods table

### ISSUE THREAD

**Issue by MrChebur** [qgis/QGIS-Documentation#4246]
## Description

Description text does not fit into the `Methods` table. It may be worth adding a scroll bar or setting up text wrapping on the new line.
GIF Animation of the issue: https://i.ibb.co/cLxSmwr/Cj-Vi-Zr-Lqd9.gif

Page URL: https://qgis.org/pyqgis/master/core/QgsProject.html
Other versions are affected too i.e.: https://qgis.org/pyqgis/3.4/core/QgsProject.html

**Comment by DelazJ** [comment]
@MrChebur Could you please report at https://github.com/qgis/pyqgis/issues which is the place for that website? Thanks

**Comment by MrChebur** [comment]
Sorry. Closed.

**Comment by DelazJ** [comment]
no problem. We need the information to be available on that website so people are correctly directed.
