### ISSUE TITLE
[processing][needs-docs] Resurrect setting for default raster/vector
output format

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4259]
Original commit: https://github.com/qgis/QGIS/commit/cfcf580b610e7bbd83dac1c43f5d66053c7171d4 by nyalldawson

This setting is still used and required in some circumstances, e.g.
it is used as the default selection in outputs file pickers when
the previously used format is not valid.

**Comment by havatv** [comment]
As far as I can tell, the only update that needs to be done is the screen shot "user_manual/introduction/img/options_processing.png" referenced in "user_manual/introduction/qgis_configuration.rst".
