### ISSUE TITLE
[needs-docs][processing] Respect user set default vector output format
in vector split algorithm

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4260]
Original commit: https://github.com/qgis/QGIS/commit/90bac82f124ccb53e43bb99f5d483105bea1c967 by nyalldawson

The created outputs will now be created using the format specified from
the Processing setting default vector format setting.

**Comment by havatv** [comment]
This seems to be a bug fix, so no need to document? The description of the algorithm in the user manual says nothing about output format.
