### ISSUE TITLE
[needs-docs] Add new operators to raster calculator

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4263]
Original commit: https://github.com/qgis/QGIS/commit/860d0201ef32b22d2a3ffaad357243da37a83009 by web-flow

[needs-docs] Fix multiple raster calc issues (+ new operators)

* ABS
* MIN
* MAX

**Comment by marylaure** [comment]
could you pls guide me to the screenshot to be changed ?

**Comment by DelazJ** [comment]
Hi @marylaure 
Thanks for offering your help. The screenshot is at https://docs.qgis.org/testing/en/docs/user_manual/working_with_raster/raster_analysis.html#raster-calculator

**Comment by SrNetoChan** [comment]
Ah, I wasn't able to find it either... Should we had a link here?

https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/rasteranalysis.html#raster-calculator

**Comment by DelazJ** [comment]
> Ah, I wasn't able to find it either... Should we had a link here?

We could, indeed. In an ideal situation, it should be moved to the Processing section but I realize that we actually have two (?) tools, with different GUI. Consequently, the new operators added by @elpaso are not available in the "raster calculator" algorithm.
