### ISSUE TITLE
Fix "Blur only alpha pixels" description for labels shadow

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#4264]
Page URL: https://docs.qgis.org/testing/en/docs/user_manual/style_library/label_settings.html#shadow-tab
In the description of Labels shadow setting, it's mentioned (as a [six-years old comment](https://github.com/qgis/QGIS-Documentation/commit/e916dbfbd0bcf41ea759a35ccfbfb70a2391835b#diff-7780fa8508095c89905755dffa4e1f23R422) hence visible only in writing mode) the following: 
> .. comment FIXME: at the moment there is an error in this setting
> 
>    |checkbox| :guilabel:`Blur only alpha pixels`: It is supposed to show only those pixels that have a partial alpha component beyond the base opaque pixels of the component being blurred.
> For example, if you set the shadow of some text to be gray and turn on that option, it should still show a duplication of the text, colored as per the shadow color option, but with any blurred shadow that extends beyond its text. With the option off, in this example, it will blur all pixels of the duplicated text. This is useful for creating a shadow that increases legibility at smaller output sizes, e.g. like duplicating text and offsetting it a bit in illustration programs, while still showing a bit of shadow at larger sizes.
>    Apparently, there is an error with re-painting the opaque pixels back over top of the shadow (depending upon the shadow's color), when that setting is used.

Since I'm unable to judge the effects of this option nor whether it's still buggy as suggested in the comment, I'd appreciate someone tell me:
1. what the option is designed for (we should anyways document what the option must do) 
1. and whether the bug is still valid (we could open an issue report to get it fixed)

**Comment by DelazJ** [comment]
@nyalldawson sorry to bother you but would you know if this is a valid report, please? And how we could describe this option? Thanks

**Comment by nyalldawson** [comment]
Honestly, I've tried to understand that setting in the past and have failed to understand the impact it actually has on rendering or what the code behind it is actually doing.

**Comment by DelazJ** [comment]
sorry @nyalldawson I missed your reply. That's not good news ;) If nobody knows what it does, should we remove it?

**Comment by nyalldawson** [comment]
Maybe ask on the dev list first?

**Comment by roya0045** [comment]
Is this a thing that must still be fixed?
