### ISSUE TITLE
Specifying version of SVG supported by QGIS (Qt)

### ISSUE THREAD

**Issue by afrigeri** [qgis/QGIS-Documentation#4318]
## Description

In [issue#32270](https://github.com/qgis/QGIS/issues/32270), @andreasneumann noted that Qt5 renders SVG following the SVG Tiny 1.2, so loading SVG which do not follow these specifications would result in _SVG Markers_ badly rendered in QGIS.

I suggest to add a note into the documentation at the voice __SVG Markers__ within this page:

https://docs.qgis.org/3.4/en/docs/user_manual/working_with_vector/style_library.html?highlight=fill%20pattern#svg-marker

Something like:

_QGIS renders SVG files that follow the [SVG Tiny 1.2 profile](https://www.w3.org/TR/SVGMobile12/), intended for implementation on a range of devices, from cellphones and PDAs to laptop and desktop computers, and thus includes a subset of the features included in SVG 1.1 Full, along with new features to extend the capabilities of SVG.  
Some features not included in these specifications might not be rendered correctly in QGIS._

**Comment by DelazJ** [comment]
I wish we had more reports like this.

**Comment by DelazJ** [comment]
Fixed in #4323
