### ISSUE TITLE
[feature] [ios] allow static build of postgres provider

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4329]
Original commit: https://github.com/qgis/QGIS/commit/5672f0d24c5c6a651619a42c145052909442d8ca by PeterPetrik

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment]
Afaics, not something to document in user manual. @PeterPetrik?

**Comment by PeterPetrik** [comment]
@DelazJ yes, you are right, this is more in territory of infrastructure/refactoring/packaging

**Comment by DelazJ** [comment]
Thanks @PeterPetrik
