### ISSUE TITLE
[FEATURE][needs-docs] Add hash functions

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4331]
Original commit: https://github.com/qgis/QGIS/commit/23f4d5eba27e4df927add8b27df9db039e7abcc9 by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by ghtmtt** [comment]
@havatv isn't your PR #4334 closing this issue?

**Comment by DelazJ** [comment]
Anything that is a function is now covered by running Alex script. So yes should be closed.
