### ISSUE TITLE
[needs-docs] add interpolate Z on segment snapping

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4332]
Original commit: https://github.com/qgis/QGIS/commit/58a3540d05eaa7961703ef1b83371e7c0cf5572f by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by SrNetoChan** [comment]
@lbartoletti can you explain this feature a bit more? Thanks!!

**Comment by DelazJ** [comment]
See also https://github.com/qgis/QGIS/pull/31289 but a summary of what has finally been designed would indeed worth it, while it's still fresh in memories.
To writers: We are only 4 months left to release and there are still a lot to fix so can we please ignore >3.10 features and put our energy in older features? Thanks.

**Comment by lbartoletti** [comment]
@SrNetoChan @DelazJ 

It's not really a feature, more a bug, at least for some users :)

My comments will be global about theses PR:
- https://github.com/qgis/QGIS/pull/9294
- https://github.com/qgis/QGIS/pull/9379
- https://github.com/qgis/QGIS/pull/30108
- https://github.com/qgis/QGIS/pull/31171
- https://github.com/qgis/QGIS/pull/31163
- https://github.com/qgis/QGIS/pull/31142
- https://github.com/qgis/QGIS/pull/31035
- https://github.com/qgis/QGIS/pull/31020
- https://github.com/qgis/QGIS/pull/30991

So, what's the problem with the Z and the topological editing?

Editing geometries with Z was not fully supported (there are still things to do such as adding Z and M in the advanced editing tool.)
Until now it was possible to edit the Z by defining a default Z and editing it via the node tool. Similarly, the snapping and topological editing was partial and Z-less.

The qwat group (cc @ponceta) financed 3 axes of corrections: 
- Correction of the Z-support
- Correction of the topological edition on all tools
- Correction of the snap to 3D geometries.

With all these corrections, you can now: 

- when editing 3D geometry, return the Z of the snapped vertex. 
- BTW if you snap to a segment, you can return the interpolated Z [1]. That is, if you have a line [(0 0 0), (10 10 10)], by snapping to the middle you will have a vertex (5 5 5)
- topological editing works on all tools [2] and for all layers snapped by the maptool.

Let me know, if it's easier to understand :)
I can make videos again if you need them.

Thank you

[1] Follow up our discussion on the PR, this is only available if the topological editing is activated. If not, the Z returned will be the default Z value.
[2] I still have to validate the result on shape tools. It works, but for some case, no new topological points is added, but it seems to be an error relative to the digitizing precision and segmentation of geometries

**Comment by SrNetoChan** [comment]
@lbartoletti not sure if the Z editing or it's limitations were ever mentioned in the docs. Nevertheless, this "tips" should be added to digitizing section to avoid people loosing Z values by mistake. I just did it this week!!

**Comment by lbartoletti** [comment]
Yes. Working with Z gives you a headache quickly :)
better have a good documentation on the subject, don't hesitate to ping me!

**Comment by lbartoletti** [comment]
@SrNetoChan Do you need some help?

**Comment by SrNetoChan** [comment]
No @lbartoletti what I need is time 🙂

One off-topic question for you. Do you know if  it's possible to access the node editing panel from python? I would like to create a plugin to change the Z values of multiple nodes. For example, give them all the same value, or interpolate in Z between the first selected node to the last.
