### ISSUE TITLE
[FEATURE][needs-docs] Update vector layer selection from relation
editor widget

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4338]
Original commit: https://github.com/qgis/QGIS/commit/485db34e5643a2811bc81c1c3e6c83e00191bf82 by troopa81

Unfortunately this naughty coder did not write a description... :-(

**Comment by troopa81** [comment]
This feature was about to synchronize selection in canvas with selection in relation editor. I'm not sure this needs to be documented. IMHO we should close this ticket.
