### ISSUE TITLE
[FEATURE][needs-docs] Update vector layer selection from feature
selection dialog

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4339]
Original commit: https://github.com/qgis/QGIS/commit/3c24de55e1c4ba0684e3e9efcdb2eb0529679eaa by troopa81

Unfortunately this naughty coder did not write a description... :-(

**Comment by SrNetoChan** [comment]
@troopa81 can you please explain what this new feature is and why does it need docs? Does this affects the GUI or user interaction?

**Comment by troopa81** [comment]
@SrNetoChan To sum up, the selection in relation editor widget is now the same as the global (layer) one.

 More explanation and Gif in the [PR](https://github.com/qgis/QGIS/pull/31951)

I'm not completely sure this need to be documented

**Comment by troopa81** [comment]
The feature selection dialog is not described in the documentation, only mentioned [here](https://github.com/qgis/QGIS-Documentation/pull/4939) (*The link symbol will open a new dialog where you can select any existing airport which will then be assigned to the current region....*)

I'm not sure this is interesting to tell more about this dialog which propose to select a bunch feature. I propose to close this ticket.

Same comment applies to #4632
