### ISSUE TITLE
[feature] Server wfs3 timefilter dimensions

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4343]
Original commit: https://github.com/qgis/QGIS/commit/e689a65bb317e97927ccce658aa5d641802814d1 by web-flow

[feature] Server wfs3 timefilter dimensions

**Comment by DelazJ** [comment]
@elpaso  is this report fixed in https://docs.qgis.org/3.22/en/docs/server_manual/services/ogcapif.html#feature-filtering or are they different things?

**Comment by elpaso** [comment]
I think it is fixed.
