### ISSUE TITLE
[feature] [mesh] fix #29326 Adding playback function for mesh datasets

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4344]
Original commit: https://github.com/qgis/QGIS/commit/32cfedd074a48d28c9d7a228a25e0a3299455dd0 by PeterPetrik

Unfortunately this naughty coder did not write a description... :-(

**Comment by PeterPetrik** [comment]
please see https://github.com/qgis/QGIS/pull/31875

it adds play(back)&pause button to the mesh layer time slider.

**Comment by DelazJ** [comment]
@PeterPetrik This feature as is is no more in QGIS, right?

**Comment by DelazJ** [comment]
This no longer exists. Closing.
