### ISSUE TITLE
[FEATURE] Parallelize snap index build

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4346]
Original commit: https://github.com/qgis/QGIS/commit/f96e1922cae31c43cded24bb87793f26c50129d5 by troopa81

Unfortunately this naughty coder did not write a description... :-(

**Comment by troopa81** [comment]
This feature is about building snapping cache in parallel to speed up the indexing process and "relaxing" the snapping so you can still edit even when you index cache is not complete. More information [here](https://oslandia.com/en/2020/01/10/en-qgis-snapping-improvements/) (*Relax the snapping cache index build*). 

I take a quick look at the snapping documentation and I think it doesn't need to be updated, and IHMO we should close this issue.

**Comment by roya0045** [comment]
I agree that since this is more of an internal change it doesn't require doc.
