### ISSUE TITLE
Training Manual outdated for QGIS 3.8

### ISSUE THREAD

**Issue by kmccall** [qgis/QGIS-Documentation#4349]
## Description

In the first 100 pages, I have encountered many instances where the dialog boxes shown in the manual do not look like QGIS 3.8. Sometimes this can be navigated by finding the changes buttons or drop downs. Sometimes it leads to apparent frustrating dead ends.

Two examples:
For example, on page 103 in section 5.2.1.5, I’m try to create a dynamic map canvas, when I go to the Item Properties Panel, there is no Position and Size section as described in the documentation. I have not determined a solution for this.

@havatv, 13/6-2020: **The p. 103 issue is not valid. The item properties panel of the map item has a Position and Size section**

Another example: On p. 113 in ‘Creating a New Vector Dataset’, when I try to save the simple dataset, I get an error message: 

‘Layer creation failed: Failed to create file created_shapefile.shp: Permission denied.

In this example, I’ve determined (with listserve help) that the directions at the bottom of p. 114 are wrong. The name and location of the file have to be saved first at the top of the dialog box – which is never shown in the training manual.

@havatv, 13/6-2020: **The p. 113-114 issue has been resolved**

I was asked to open a ticket on these issues. 

Ken McCall

Page URL:

**Comment by kmccall** [comment]
I downloaded the pdf and was using that, but I can do that in the future. 


 

    On Thursday, October 31, 2019, 12:46:42 PM EDT, Harrissou Sant-anna <notifications@github.com> wrote:  
 
 
And if you could point to the html page in https://docs.qgis.org/3.4/en/docs/training_manual/index.html, would be even better

**Comment by kmccall** [comment]
will do


 

    On Thursday, October 31, 2019, 12:40:10 PM EDT, Alexandre Neto <notifications@github.com> wrote:  
 
 
Hi @kmccall this is a pretty valid bug ticket, but it would be more valuable if you could pinpoint each of the problems you have found in a separate issue. At least by section or page.

That would make the documentation team work easier by splitting it in smaller tasks.

Thanks for the report!

**Comment by havatv** [comment]
Since the two problems that were raised in this issue have been resolved, I close the issue.
Thank you for reporting, @kmccall! I hope you will open new issues if you have other problems with the documentation
