### ISSUE TITLE
[feature][processing] add first version of fuzzy logic raster algorithms to QGIS

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4390]
Original commit: https://github.com/qgis/QGIS/commit/d3d0093096f8587cacc50eb60cd8454b4d28abb4 by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by ghtmtt** [comment]
@havatv can we close this issue? I think the two referenced tickets fix this..
