### ISSUE TITLE
[feature][processing] add function pictograms for fuzzy logic functions to toolbox

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4391]
Original commit: https://github.com/qgis/QGIS/commit/18ff21951adc4ddbbfde254ee7bbe45b60e5897e by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by ghtmtt** [comment]
@havatv can we close this issue? I think #5377 and #5479 that documents the algorithm are related to this.
