### ISSUE TITLE
[feature] is_valid expression

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4436]
Original commit: https://github.com/qgis/QGIS/commit/0e7edd55885f590243343cd5167dff61088bbe2e by nyalldawson

Returns true if a geometry is considered valid according to the OGC validity rules

**Comment by lajunek** [comment]
@nyalldawson @SrNetoChan Can you guys give me some information about this new feature? Is this a function in the QGIS core, will there be a error message in qgis when a geometry doesn't fit the OGC validity rules? When is the user in contact with this new feature?

**Comment by DelazJ** [comment]
@lajunek it is available in the Expression dialog.
Simply note that this is a 3.12 feature so should not be prioritized for a fix. This comment should not prevent anyone from providing the requested details, of course.
