### ISSUE TITLE
[FEATURE][labels] allow to delete custom label position

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4455]
Original commit: https://github.com/qgis/QGIS/commit/99bf9687aa0feeeeaf9b1308f5707da5e17eaa06 by 3nids

by pressing DEL key when moving the label

**Comment by roya0045** [comment]
@DelazJ Are the label tools even detailed anywhere? I had a quick look where it could be and saw nothing.

**Comment by DelazJ** [comment]
Something like https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/vector_properties.html?highlight=label#the-label-toolbar?

**Comment by roya0045** [comment]
@DelazJ Thanks! I'll add them to the current PR!
