### ISSUE TITLE
[FEATURE][labels] allow to delete custom label rotation

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4456]
Original commit: https://github.com/qgis/QGIS/commit/0e110cf01a29ebea9cf40f0166e0150f55f471ac by 3nids

by pressing DEL key when moving the label

**Comment by havatv** [comment]
Seems to be a duplicate of #4455.

**Comment by DelazJ** [comment]
Actually, one is about displacement, the other the rotation

**Comment by havatv** [comment]
You are right! Sorry.
