### ISSUE TITLE
Link to download the C++ API is dead

### ISSUE THREAD

**Issue by Gustry** [qgis/QGIS-Documentation#4457]
## Description

On https://qgis.org/api/3.4/

The link to download to documentation is dead:

> You can also download this documentation or a Qt help file for offline use.

https://qgis.org/downloads/qgis-api-doc.zip

**Comment by DelazJ** [comment]
Yep. Seems it's a 7z file https://qgis.org/downloads/qgis-api-doc.7z instead.
Maybe @jef-n?

**Comment by DelazJ** [comment]
Actually my link is for downloading master API. Not sure whether other releases are available.

**Comment by jef-n** [comment]
> Yep. Seems it's a 7z file https://qgis.org/downloads/qgis-api-doc.7z instead.
> Maybe @jef-n?

Yes, changed it back to zip (it's was symlink to the zip).   I changed it because it was a very popular target for bots and forgot to check back…

**Comment by agiudiceandrea** [comment]
@jef-n @DelazJ the link to download the C++ API is dead again.

> You can also download this documentation

points to https://qgis.org/downloads/qgis-api-doc.7z, but there is no qgis-api-doc.7z in https://qgis.org/downloads/.

There is qgis-api-doc.zip, so the correct URL should be https://qgis.org/downloads/qgis-api-doc.zip

Anyway, [qgis-api-doc.zip](https://qgis.org/downloads/qgis-api-doc.zip) is probably outdated: it results last updated on 14-Sep-2019.

**Comment by agiudiceandrea** [comment]
It seems now is again present the file qgis-api-doc.7z in https://qgis.org/downloads/ update on 17-Jan-2021-
