### ISSUE TITLE
[FEATURE][diagrams] New diagram type "stacked bars"

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4475]
Original commit: https://github.com/qgis/QGIS/commit/204bd47b19b096ebb13b8d943f875fd5e42443be by nyalldawson

Stacks bars of varying colors for each attribute on top of each other
vertically or horizontally.

Sponsored by SLYR

**Comment by DelazJ** [comment]
@nyalldawson I can't find how I can make the stacked bars horizontal (as suggested by the commit message). Is that implemented?

**Comment by nyalldawson** [comment]
@DelazJ yes, it's under the "options" group:

![image](https://user-images.githubusercontent.com/1829991/76172257-9f833980-61df-11ea-8bb2-50ac0452d224.png)
