### ISSUE TITLE
Missing link to download  "A gentle introduction in GIS" and C++ API as PDF

### ISSUE THREAD

**Issue by Gustry** [qgis/QGIS-Documentation#4486]
## Description

Page URL: https://www.qgis.org/en/docs/index.html#34

There isn't a link to download the "Gentle introduction in GIS" and the C++ API ( see https://github.com/qgis/QGIS-Documentation/issues/4457) as a PDF.
I know this gentle introduction is getting old, but there are still some pages useful, like "vector data" or "CRS". I don't know if the PDF is generated in background and if only the link is missing.

**Comment by DelazJ** [comment]
>  I don't know if the PDF is generated in background and if only the link is missing.
No, no pdf in background (https://github.com/qgis/QGIS-Documentation/blob/master/source/conf.py#L260 for list of generated pdf)

**Comment by DelazJ** [comment]
Do you think we need to provide the c++ api in pdf in that page? We cuurently have links to **versioned** api pages that provide the link (and more). Another issue is that the pdf doc in the c++ api website is not versioned: all the pages point to the pdf of the master branch, meaning that we'd either add the same link below each section if we want to follow the current structure, or add it once (under which version?)

**Comment by Gustry** [comment]
> Do you think we need to provide the c++ api in pdf in that page? 

Ok, I understand, it makes sense. It was just not very obvious to download the API as PDF last week (I was giving a PyQGIS training, without internet in the training room), but this situation is very rare ;-)

Should I close the ticket? I don't have a strong opinion about gentle introduction to GIS (even if there is some nice sections).
