### ISSUE TITLE
[feature][processing] Port and optimization of Random points in extent algorithm to C++

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4492]
Original commit: https://github.com/qgis/QGIS/commit/a75436c5e34a50348cd0ab483ae470e9bdd1e477 by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment]
Change for docs:
> A new "max iterations" parameter is added
