### ISSUE TITLE
[needs-docs][layouts] Shuffle legend item widget tool buttons
to reduce visual cumbersomeness

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4494]
Original commit: https://github.com/qgis/QGIS/commit/f5d542e4af75bb4c190570acef3e5e637df0f6d5 by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by lajunek** [comment]
@nyalldawson is the `Filter legend by map content` moved to the checkbox `Only show items inside linked map` ?

**Comment by DelazJ** [comment]
@lajunek Yes, that's it.

**Comment by lajunek** [comment]
@nyalldawson we are talking about a `Reset to defaults` option here. Does it still exist?

**Comment by lajunek** [comment]
@nyalldawson [https://docs.qgis.org/testing/en/docs/user_manual/print_composer/composer_items/composer_legend.html](url)

**Comment by lajunek** [comment]
@havatv [https://docs.qgis.org/testing/en/docs/user_manual/print_composer/composer_items/composer_legend.html](url) do you know where to find the `Reset to defaults` ... is this implemented into the print composer? (section `Legend Items`)

**Comment by DelazJ** [comment]
@lajunek Right-click an item in the legend 
> In case you have made some changes to a layer, you can revert them by choosing Reset to defaults **from the contextual menu**.

**Comment by havatv** [comment]
> @havatv [https://docs.qgis.org/testing/en/docs/user_manual/print_composer/composer_items/composer_legend.html](url) do you know where to find the `Reset to defaults` ... is this implemented into the print composer? (section `Legend Items`)

I don't know, @lajunek.
