### ISSUE TITLE
[Processing] Introduce a new type for alg output parameter

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#4502]
When describing an alg, we add as type eg [vector: point], [vector: any] for the input and output layers. But if `input layer [vector: any]` means that I can use any type of geometry as input, `output layer [vector: any]` does not tell me what I actually get. If I use point feature, will I get point or something else? I think we should add a clearer information on the output when it depends on the input, ie something like (only to get the idea)
```
input layer [vector: any]
...
output layer [input layer type]
or 
output  layer [same as input] # input (as well as output) can be replaced with intersect/overlay layer
```
Opinions? Suggestions?

**Comment by havatv** [comment]
I agree that it would be nice to have such a mechanism for output that will have the same geometry type as the input (when the input geometry type is "any" - `[vector: any]`).
I prefer `[same as input]` (or `[input type]`).

**Comment by DelazJ** [comment]
So can we go with [same as input] from now?

**Comment by havatv** [comment]
I hope so.
I have added it to #4506... :-)

**Comment by DelazJ** [comment]
OK! Let's go with `[same as input]` and add it to the guidelines.

**Comment by havatv** [comment]
Is it time to close this issue, @DelazJ?

**Comment by DelazJ** [comment]
Done. Thanks.
