### ISSUE TITLE
[FEATURE] API for rendering frames for mesh vector dataset animation (particles) (#33110)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4514]
Original commit: https://github.com/qgis/QGIS/commit/6d4c995a280febd208ad06146c58e8c47a285ffc by PeterPetrik

* [FEATURE] API for rendering frames for mesh vector dataset animation (particles) 

Adds a renderer to generate frames that represent particle traces in a vector field of a mesh layer. The renderer cannot be chosen in the current GUI, however crayfish plugin can use API to generate avi/gif files with nice animations representing the movement of (random) particles in the mesh layer vector field.

**Comment by DelazJ** [comment]
I don't think this belongs to PyQGIS docs. Looks like an API feature that if I'm not wrong is outdated now (particles can be set in GUI). Closing? @PeterPetrik?

**Comment by PeterPetrik** [comment]
feel free to close

**Comment by DelazJ** [comment]
Thanks.
