### ISSUE TITLE
[needs-docs] When running in label engine v2 mode, discard any candidates where
they collide with an obstacle feature of greater weight when compared
to the label's priority

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4540]
Original commit: https://github.com/qgis/QGIS/commit/19b8d433880378b27cd2c235bff3223d4837fd5e by nyalldawson

Previously, obstacle weight was used ONLY to rank a features' label
candidates relative to each other, but was never used to actually prune candidates
completely. This meant that the labeling obstacle functionality was
confusing and frustrating for users to work with -- because despite
setting layers as the maximum possible blocking weight, you'd still
see labels being placed over these features (e.g. where the labeling
engine had no other choice).

Now, (when a project is set to v2 labeling engine mode), labels will
NEVER be placed over obstacles of greater weight. This means that
labels will potentially be omitted if the only choice is to place
them over a high weighting obstacle. But ultimately, that's much
more understandable for users -- they've manually set a particular
layer to a high obstacle factor, so we should respect that and
never place labels on these features.

In the end, this change makes the labeling placement much simpler
to understand for users, and should give power users a much
nicer experience all round.

Funded by the QGIS grants program

**Comment by roya0045** [comment]
Is there event a way to change the label engine? I can find nothing to this effect, I'll just adapt the doc.

**Comment by roya0045** [comment]
TBH this seems fine in the doc, the behaviour has only been enhanced by the referenced fix it seems.

**Comment by DelazJ** [comment]
Indeed, fixed in #5571
