### ISSUE TITLE
[feature] Support datasets with data defined on faces in mesh calculator (#33248)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4572]
Original commit: https://github.com/qgis/QGIS/commit/b93dfdd0b399375eb8fecbcb88c834e95060a1bf by web-flow

* [feature] support datasets with data defined on faces in mesh calculator, fix #30219, fix #30170

added "driver" and "group name" to the calculator interface.
MDAL now supports 3 drivers for storing results, so user must be able to choose appropriate driver and dataset group name (some drivers store multiple groups to 1 file)

**Comment by DelazJ** [comment]
Fixed in #6957
