### ISSUE TITLE
Screenshot Figure_Composer_Map1 needs an update

### ISSUE THREAD

**Issue by junek** [qgis/QGIS-Documentation#459]
The GUI of the main properties changed.
See
https://github.com/qgis/QGIS-Documentation/commit/e48112421520028d0d07b1275d2f9ca180aa3884

**Comment by SrNetoChan** [comment]
Fixed in this commit:

https://github.com/qgis/QGIS-Documentation/commit/05fe682540424d988ec871c1211b33ed82d4ed74
