### ISSUE TITLE
Algorithm parameters - use of include and handling advanced parameters

### ISSUE THREAD

**Issue by havatv** [qgis/QGIS-Documentation#4628]
## Description

**First**:
We have been "experimenting" with includes for algorithm parameters, and have discovered that the RST `.. include:` has some important limitations. It does not seem to be possible to use it to import a group of elements of a list-table.
Below are some alternatives that we have tested, and I hope we can discuss.
The alternatives are implemented in PR #4627 (in the documentation of the QGIS Network algorithms - probably the only place where includes have a real potential for algorithm parameters).

* Include 1: "Pasting" tables together.
  Demonstrated in "Service area (from layer)".
* Include 2: Placing the "repeating" group of parameters in a separate table.
  Demonstrated for the Advanced parameters in the "Service area (from point)" algorithm.

**Second**:
To help the users, it would be nice to have the "Advanced parameters" group exposed in the parameter tables. Three approaches:

* Advanced 1: Adding a row in the table before and after the Advanced parameters group, as demonstrated in the "Shortest path (layer to point)" algorithm.
* Advanced 2: Including "Advanced" in one of the existing columns. In the "Shortest path (point to layer)" algorithm, it is included in the Label column.
* Advanced 3: A separate column for Advanced in the table. Demonstrated in the "Shortest path (point to point)" algorithm

"Advanced" alternative 2 is easiest to implement, and seems quite logical (placing "Optional" and "Advanced" in the same ("Label") column.

Page URL: https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/networkanalysis.html

**Comment by DelazJ** [comment]
Hi,
@havatv thank you for taking the problem at the right end!
But I guess we need the docs to be built (after 8 pm cet?) before any valuable discussion can be held... Unless @rduivenvoorde triggers a build in the meantime :smile_cat:

**Comment by havatv** [comment]
@DelazJ, should we try to reach a "conclusion" here?
I am fine with using includes, and not "isolate" the advanced parameters.

I would very much like is to be able to "mark" the advanced parameters in the algorithm parameter tables. One reason for wanting to show that a parameter is advanced is that there is a flag for this when defining algorithm parameters (as for optional ones).
I think that adding the word "Advanced" (in italics) in the"Label" column (where we currently show that a parameter is "Optional") is a simple and non-intrusive solution.

So here are my suggestions:

1) For includes, I suggest that we go for @DelazJ's proposal ("Include 1": "Pasting" tables together) - as demonstrated in the documentation of the QGIS Network algorithm "Service area (from layer)" - https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/networkanalysis.html#service-area-from-layer .
A disadvantage of this approach is that the columns are likely to be shifted where the tables are pasted together. But that is, in my opinion, a minor inconvenience.

2) For advanced parameters, I suggest that we go for "Advanced 2": Including "Advanced" (in italics) in the "Label" column - as demonstrated in the "Shortest path (point to layer)" QGIS Network algorithm - https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/networkanalysis.html#shortest-path-point-to-layer
I can't see any significant disadvantages of this approach.

**Comment by DelazJ** [comment]
@havatv sorry for the delay but can you give me some more days, please? I'm working on upgrading the doc infrastructure and the include with tables concatenation is not that nice; the shift can be really important as I could not see how to control columns size. yet.

About the use of "advanced", i'm still not convinced it's worth a mention. Knowing that a parameter is optional allows me to skip it when doing a call. I can't see in what knowing that it's advanced really helps me to use the alg (no significant disadvantages, maybe, but what's the added value?).
But if you think we really have to mention it, I'd also take the mention in italics, and not the separate section.

**Comment by havatv** [comment]
Delaying this is no big deal, so take your time, @DelazJ.

*Advanced*: The reason why I think it is a good idea to include it is that there is an "advanced" flag (``QgsProcessingParameterDefinition.FlagAdvanced``) for processing algorithms, and parameters that are flagged as advanced are grouped under **Advanced parameters** in the GUI. So it should be of some value to the users.
