### ISSUE TITLE
Figure Composer Attribute Table 5 needs an update

### ISSUE THREAD

**Issue by junek** [qgis/QGIS-Documentation#463]
We have a new feature 'Show empty roads'
See
https://github.com/qgis/QGIS-Documentation/commit/8a344157a08c98fee45a509d0a94486a6fe6c15c

**Comment by SrNetoChan** [comment]
Fixed here https://github.com/qgis/QGIS-Documentation/commit/2cf37319a5a72806fcb6fc771886649d49a58477
