### ISSUE TITLE
[needs-docs] Add precision to rotate marker checkbox label

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4631]
Original commit: https://github.com/qgis/QGIS/commit/c235c4c1957ff40755935ef312d7f036886b7ccb by nyalldawson

and harmonize with hash line symbol layer dialog

**Comment by DelazJ** [comment]
https://docs.qgis.org/testing/en/docs/user_manual/style_library/symbol_selector.html#line-symbols
