### ISSUE TITLE
Training Manual 4.2: Layer labeling instructions outdated

### ISSUE THREAD

**Issue by BenjaminRiley** [qgis/QGIS-Documentation#4634]
## Description

I'm running through the training manual on v3.10.1 and it looks like the labeling system has changed a bit since its section was written.

### 4.2.1

- When instructed to click the 'Layer Labeling Options' toolbar button, the 'Layer labeling settings' dialog described in the text does not appear. Instead, a mostly blank 'Layer Styling' sidebar appears. It looks like changing the 'No labels' dropdown to 'Single labels' and ensuring 'Value' is set to `name` replaces checking the 'Label this layer with ...' box.

### 4.2.2

- Left-hand options list is replaced with tabs in the styling sidebar. Since the tabs only have icons without a text label, it might be better to re-write the previous section (4.2.1) to have label styles edited through the layer properties dialogue instead of the layer styling sidebar opened by the toolbar button.
- It's odd that the tutorial declares the font problem solved before explaining how to apply an outline to the text as shown in the screenshot. Especially since making it white as suggested makes it much harder to read and there's no obvious way to fix it without reading ahead.

### 4.2.5

- When setting road label positions, the text mentions the 'Advanced' tab when it probably means the 'Placement' tab

### 4.2.6

- The 'Expression string builder' has a completely different layout to what's shown. Not sure if that's because I'm on Windows and the screenshot is MacOS or if it's been changed since.

### 4.2.7

- This is more of a nitpick, but wouldn't it make more sense for font size to be a decimal number instead of an integer?

Page URL: https://docs.qgis.org/testing/en/docs/training_manual/vector_classification/label_tool.html

**Comment by Codym48** [comment]
@havatv can we close this now that #5463 is merged into master?

**Comment by havatv** [comment]
> @havatv can we close this now that #5463 is merged into master?

Definitely!
