### ISSUE TITLE
[needs-docs] Add a "Validate" button to custom projection dialog
to allow users to validate the currently edited CRS definition
without having to accept the whole dialog

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4635]
Original commit: https://github.com/qgis/QGIS/commit/aa0b9b05470d710b2c40b6ac5270b1a1e54f8534 by nyalldawson

If the validation fails, the proj error messages are shown
to help the user determine why the string is invalid

**Comment by DelazJ** [comment]
Duplicate of #4654
