### ISSUE TITLE
Better documentation for Raster Terrain Analysis plugin

### ISSUE THREAD

**Issue by alexbruy** [qgis/QGIS-Documentation#465]
The terrain analysis plugin is not well documented in the manual: would it be possible to add a few notes (in particular, the unit of measure used, and the meaning of curvature and rougeddness; also, the aspect map is unclear: is it clock or counterclockwise? In any case, it is different from how it is calculated in GRASS, which is very confusing to me).

Original ticket https://hub.qgis.org/issues/2668

**Comment by junek** [comment]
Done !
