### ISSUE TITLE
Improve documentation for interpolation plugin

### ISSUE THREAD

**Issue by alexbruy** [qgis/QGIS-Documentation#466]
It would be very helpful to improve the qgis documentation regarding the interpolation plugins - what's the meaning of some of the options (namely break lines and structured lines) and a short summary on the characteristics of each interpolator avaialable

Notes from the [mailing list](http://lists.osgeo.org/pipermail/qgis-user/2013-July/023240.html), to be added to the manual:

    > So, how are line features supposed to work in interpolation plugin? Or how can i give structure lines hight values that make sense?

Well, somehow you need to say the plugin what the values to interpolate are. Currently possible is to take from attribute or from z-value (for 2.5D geometry types). Where do you have the height values in your data?

    > So, how are line features supposed to work in interpolation plugin?

The line features are used to modify the triangulation. The triangulation is modified such that no edge crosses a breakline or structure line (constrained Delaunay triangulation). The difference between handling of breaklines and structure lines is that cubic interpolation produces a sharp break rather than a continuous one.

Please note that the interpolation plugin has some numerical problems in the TIN creation that may lead to crashes (especially for data in degrees). There is the option to dump the generated triangle net, so you can see what the plugin does.

Original tickets: https://hub.qgis.org/issues/8354 and https://hub.qgis.org/issues/3103

**Comment by junek** [comment]
Nearly done! I'm struggling with numerical problems in the TIN creation. Is this a format problem? Can somebody give further explanations?

**Comment by junek** [comment]
I discussed with Marco Hugentobler and we found that we won't describe the bug concerning the numerical problems ...
