### ISSUE TITLE
Document better the "priority" functionality for labels

### ISSUE THREAD

**Issue by alexbruy** [qgis/QGIS-Documentation#468]
Under Labelling -> Placement, there's a "priority" bar which ranges from "low" to "high". I'm just guessing here, but I suppose this bar is meant to show important the underlying feature is, and therefore whether a label can be placed on it (there's no reference to it under the "help" button help).

Original ticket https://hub.qgis.org/issues/12220

**Comment by junek** [comment]
Done! I inserted some information into the user manual 2.8.
