### ISSUE TITLE
Spatial query plugin: missing explanation in the manual

### ISSUE THREAD

**Issue by alexbruy** [qgis/QGIS-Documentation#469]
Two options (Result feature ID's > Invalid source | Invalid reference) are unclear (to me at least) and not explained in the manual: http://docs.qgis.org/2.2/en/docs/user_manual/plugins/plugins_spatial_query.html?highlight=spatial%20query
Please add two lines of explanation to the manual.

Original ticket https://hub.qgis.org/issues/11530

**Comment by junek** [comment]
Done !
