### ISSUE TITLE
[needs-docs] Add optional global settings allowing for hard limits
to be placed on the maximum number of point, line and polygon candidates
which are generated for label features

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4691]
Original commit: https://github.com/qgis/QGIS/commit/c5e0ada6bde4db2a0e25d8386ad68d81b8e42293 by nyalldawson

These settings are set via the core\rendering\label_candidates_limit_*
settings, and allow for global limits to be set on the maximum number
of candidates allowed for label features. Placing these limits can
improve map rendering time, at the expense of worse label placement or
potentially missing map labels. (By default no global limit is set, which
means the labeling engine auto calculates the limit or uses the project
level settings)

The intended use case is for server administrators who are seeking for
maximum rendering speed to globally set these limits, causing them to
apply to all projects without the need for project-specific tweaks.

**Comment by DelazJ** [comment]
@pblottiere @nyalldawson Is this still something in QGIS? And where should that be covered (if necessary)? We document the [GUI setting](https://docs.qgis.org/3.22/en/docs/user_manual/working_with_vector/vector_properties.html#setting-the-automated-placement-engine) but for this server part, I have no idea what it is about.
Thanks for your insights.
