### ISSUE TITLE
Training manual. modeler_hydro_twi.rst missed images

### ISSUE THREAD

**Issue by alexbruy** [qgis/QGIS-Documentation#471]
modeler_hydro_twi.rst misses the reference to its image.

Original ticket https://hub.qgis.org/issues/9912

**Comment by DelazJ** [comment]
More help: Here's the [file](https://github.com/qgis/QGIS-Documentation/blob/master/source/docs/training_manual/processing/modeler_hydro_twi.rst) and its [published html version](http://docs.qgis.org/testing/en/docs/training_manual/processing/modeler_hydro_twi.html)

**Comment by ghtmtt** [comment]
training manual is going to be rewritten. Closing this issue
