### ISSUE TITLE
Unexplained difference between geometry checking and topology checking

### ISSUE THREAD

**Issue by alexbruy** [qgis/QGIS-Documentation#472]
I'm testing make valid on a sample of real data. It effectively cleans up all the topology errors, as found by the Topology Checker plugin, but geometry errors as found by the Vector --> Geometry Tools --> Check geometry validity tool are left untouched.

I'd appreciate an explanation on this difference; probably we should add it to the manual, and warn the user about it.

Original ticket https://hub.qgis.org/issues/9695

**Comment by junek** [comment]
Just to understand the issue properly: do the errors produced by the rule 'must not have invalid geometries'  differ from the geometry errorrs produced by the 'Check geometry validity tool' ?
I have some resources to write about the issue in the user manual 2.8.

**Comment by ciz** [comment]
As Giovanni Manghi points out in the original ticket, these are independent tools with different algorithms and checks,
so it's no surprise that they return different results.

About the "must not have invalid geometries" check,
the topology plugin goes over all the features and uses GEOS to test the validity by calling GEOSisValid_r() on the feature's geometry representation.
Features that don't have geometry at all, or don't have GEOS representation ( .asGeos() returns NULL)
aren't listed in the report.

Apparently the other tools uses a different techniques, so the outputs varies.
I suggest documenting this in the manual.

**Comment by yjacolin** [comment]
The last commit is just an uncompleted documentation. We should thing how can add better documentation on check geometry validity.

**Comment by dbaston** [comment]
I've been confused by this as well and interpreted it to be a bug in the implementation of the "Check Geometry Validity" tool; see http://hub.qgis.org/issues/12730

Shouldn't these tools should return the same results, unless the intent of the "Check Geometry Validity" tool is to check validity against some other set of rules than OGC?

**Comment by havatv** [comment]
In QGIS 3, there is only "check validity", and it was documented in https://github.com/qgis/QGIS-Documentation/pull/2255.
Closing this issue.
If the current documentation is not correct, new issues should be opened.
