### ISSUE TITLE
[FEATURE] Add setting for format to show angular bearings to projects
and profile options

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4754]
Original commit: https://github.com/qgis/QGIS/commit/c0ad4303d24954c29c1e567024dfe5163c542e33 by nyalldawson

The Settings - Options - Map Tools tab contains a new setting for
controlling the default format to use for displaying angular bearings for
newly created projects. Whenever a new project is created, it will
inherit this default settings.

The Project Properties dialog also has a new setting for the project-specific
bearing format.

The intention is that whenever angular bearings are shown in QGIS,
they will be formatted using the current project's bearing format
settings.

**Comment by DelazJ** [comment]
Duplicate of #4755
