### ISSUE TITLE
[FEATURE][layouts] Add user control over scalebar numeric formats

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4757]
Original commit: https://github.com/qgis/QGIS/commit/16c22541414181055b0ed9fd0af939b9b0839133 by nyalldawson

Gives users control over all the formatting properties for the numbers
in scalebars, including whether they want thousand separators, decimal
places, scientific notation, etc

Fixes #21341

**Comment by DelazJ** [comment]
Duplicate of #4758
