### ISSUE TITLE
grassland.qgs missed from QGIS sample data

### ISSUE THREAD

**Issue by alexbruy** [qgis/QGIS-Documentation#476]
The QGIS User Guide in the general_tools.rst refers to "another project from the Alaska dataset" in the section "Embedding layers". This project is missed from the sample data.

Original ticket: https://hub.qgis.org/issues/7678

**Comment by SrNetoChan** [comment]
@alexbruy The only project inside the Alaska Dataset is one called relations.qgs. I will use that to recreate the example. What do you thing?

**Comment by alexbruy** [comment]
Sounds good for me. Thanks!
