### ISSUE TITLE
[needs-docs][ui] Better placement for the method combobox and auto open action

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4769]
Original commit: https://github.com/qgis/QGIS/commit/0bb554c358418a21e8989065b2528740a128c440 by nyalldawson

(this is a follow up to PR #33643) better combobox / checkbox placement

**Comment by lajunek** [comment]
@nyalldawson what combobox are you talking about? and is it about the action entry when clicking with the i button onto a feature? I checked the code and think this has to do with the Attributes Toolbar

**Comment by nyalldawson** [comment]
@lajunek 
it relates to this checkbox at the bottom of the identify results dock:

![image](https://user-images.githubusercontent.com/1829991/88864713-209fa380-d249-11ea-9697-453db62873ea.png)


It's now moved up here:

![image](https://user-images.githubusercontent.com/1829991/88864760-3f059f00-d249-11ea-8cfa-0140d91b98d3.png)

**Comment by lajunek** [comment]
@nyalldawson may I ask how to get back to the setting without the "Auto open form for single feature results" ?

**Comment by nyalldawson** [comment]
@lajunek sorry I don't understand -- that setting should always be available in the newer releases. For the older ones, the same functionality is available via the "Auto open form" checkbox that sits at the bottom of the screen...

**Comment by SrNetoChan** [comment]
@lajunek  To be able to disable it, you need to open the identify results panel, or try to click two feature at the same time to avoid opening the feature form instead.
