### ISSUE TITLE
Wrong description for attroiibute table sorting

### ISSUE THREAD

**Issue by alexbruy** [qgis/QGIS-Documentation#477]
In QGIS User Guide, file ``working_with_vector/editing_geometry_attributes.rst`` line 894

> The table can be sorted by any column, by clicking on the column header. A small arrow indicates the sort order (downward pointing means descending values from the top row down, upward pointing means ascending values from the top row down).

contains wrong description because in QGIS  the downward pointing arrow means ascending values and upward pointing arrow means descending value.

Original ticket https://hub.qgis.org/issues/12142

**Comment by DelazJ** [comment]
Is this issue true?
I can't reproduce it; QGIS 2.8 (and earlier) behaves like the doc says.

**Comment by alexbruy** [comment]
Then this is invalid one. Closing.
