### ISSUE TITLE
[FEATURE] Add new layout item type for manually created tables

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4782]
Original commit: https://github.com/qgis/QGIS/commit/49d56f6c1929d3fcf37cdabdecb3b63b57d0474c by nyalldawson

Allows for creation of tables with contents manually entered by users
(i.e. spreadsheet style), so that users can create completely custom
tables.

Supports control custom cell contents, foreground and background colors.

**Comment by roya0045** [comment]
Should this be integrated in the composer_table document or something else?
