### ISSUE TITLE
[FEATURE] Allow customization of the items shown in browser (#33679)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4787]
Original commit: https://github.com/qgis/QGIS/commit/ecd90c6ecb72a9f827a0f9ef5899937b3b3326e2 by web-flow

* [FEATURE] Allow customization of the items show is browser. User can select in Interface Customization dialog to hide some of the items in the browser panel

Funded by Limerick City and County Council

**Comment by havatv** [comment]
In case this should be documented - @PeterPetrik, can you provide some more information about the "Interface Customization dialog"? Where to find it, how to open it, ...
