### ISSUE TITLE
[processing][needs-docs] port Rectangle,ovals,diamonds algorithm to C++
and make width, height and rotation parameters dynamic.

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4789]
Original commit: https://github.com/qgis/QGIS/commit/c752919dd0c8e672f101ab9186c6e7faa7ebefa6 by alexbruy

Old Python implementations marked as deprecated to maintain API
compatibility.

**Comment by havatv** [comment]
If this is just a port, there should be no need to update the docs.
