### ISSUE TITLE
PyQGIS CookBook. Snippets in raster.rst should be updated

### ISSUE THREAD

**Issue by alexbruy** [qgis/QGIS-Documentation#479]
Method setColorShadingAlgorithm() was gone after API break in QGIS 2.0, so code snippets not work anymore. Instead we can use setRendererForDrawingStyle() or setDrawingStyle()

Original ticket https://hub.qgis.org/issues/9856

**Comment by elpaso** [comment]
setRendererForDrawingStyle()  it's private and is not in the bindings

**Comment by elpaso** [comment]
Ok, this was a partial fix, at least drawingStyle is now renderer().type() that returns a lowercase string description of the renderer.

This is not consistent and I opened a ticket for the bindings...
http://hub.qgis.org/issues/12635

**Comment by elpaso** [comment]
I've committed some more API updates to the raster.rst file https://github.com/qgis/QGIS-Documentation/commit/531f77ff09f120d50b8996dabd0dac1691884920

**Comment by ThomasG77** [comment]
Any remaining cause to not close?
It seems the update has been done. We can close IMO and reopen if any other concerns later.

**Comment by DelazJ** [comment]
let's close it
