### ISSUE TITLE
Merge pull request #33794 from alexbruy/rectangles-ovals-diamonds

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4790]
Original commit: https://github.com/qgis/QGIS/commit/fe7085de945e9ac4cb0f8f54ab3a15d67c85e78f by web-flow

[processing][needs-docs] port Rectangle,ovals,diamonds algorithm to C++

**Comment by havatv** [comment]
Duplicate of #4789.
