### ISSUE TITLE
[FEATURE] Vector layers are loaded in 3D view in background

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4793]
Original commit: https://github.com/qgis/QGIS/commit/ab887771410d44d68eb8ca3c7fa616097683ac9f by wonder-sk

We are now using chunked entities for vector layers, so they
are split into several chunks (tiles) and each gets prepared
in background thread separately, not blocking main thread.

This is an initial implementation - work in progress.

**Comment by havatv** [comment]
Seems to be an "under the cover" feature. Probably only performance effects and no GUI effects.
Close?

**Comment by SrNetoChan** [comment]
I agree.

**Comment by DelazJ** [comment]
> Seems to be an "under the cover" feature. Probably only performance effects and no GUI effects.

I'm not sure of that. If you follow the commit url it brings to https://github.com/qgis/QGIS/pull/33480 where the description and the discussion seem to say that there are also changes in the GUI.

**Comment by DelazJ** [comment]
@wonder-sk (or any 3D user) is this screenshot expected? ie have the layer 3D rendering options available when 3D symbols of the layer is still off? Thanks
![image](https://user-images.githubusercontent.com/7983394/81013722-eeee8a80-8e5b-11ea-9452-9518b4970806.png)
