### ISSUE TITLE
Document QGIS behaviour on copy string attribute into another

### ISSUE THREAD

**Issue by alexbruy** [qgis/QGIS-Documentation#480]
If one tried to create a new column with type "string" using fields calculator and choose 2 for its length, then when inserting into this column values from another "string" column with length of 5 for example, will lead to extending column size to 5 too.

This can be documented with information from GDAL Shapefile driver
>Starting with GDAL/OGR 1.10, the driver knows to auto-extend string and integer fields (up to the 255 bytes limit imposed by the DBF format) to dynamically accomodate for the length of the data to be inserted.

Original ticket https://hub.qgis.org/issues/11485

**Comment by junek** [comment]
Done !
