### ISSUE TITLE
QGIS Server. Add note about increasing headers size when working with large features 

### ISSUE THREAD

**Issue by alexbruy** [qgis/QGIS-Documentation#481]
In QGIS Server if a feature has many nodes then modifying it or adding new one will fail if it has many nodes.

>Errors: ERROR: 1 geometries not changed.
>Provider errors:
>empty response

Simplified/generalized versions of the same feature will be saved with no problems. In this case it is necessary to raise the maximum body size of a HTTP request, like
```
<IfModule mod_fcgid.c>
FcgidMaxRequestLen 26214400
FcgidConnectTimeout 60
</IfModule>
```

Original ticket https://hub.qgis.org/issues/11497

**Comment by elpaso** [comment]
I'm not sure that this worth adding in the docs: this is an Apache/Nginx/Lighthttpd related configuration, we should remain web-server agnostic. We cannot add each and every system administrator tips needed to run an FCGI script.
IMHO, what we can do is to add a minimal but complete working example configuration, this directives can be added in that configuration.

**Comment by pcav** [comment]
IMHO additional tips never hurt, and can help users. Perhaps this kind of stuff can be added as ``.. note::``

**Comment by elpaso** [comment]
I generally agree, but we have limited resources and tips/hints/notes must be maintained and updated. I would give much higher priority to maintain documentation of QGIS specific topics and we have already a lot to do to update that part.
System administration and web server setup is pretty much standard procedure and is much better covered on dedicated upstream sources. 
This is what happens if we start giving out tips about Apache: http://lists.osgeo.org/pipermail/qgis-developer/2015-April/037528.html

**Comment by junek** [comment]
Ok guys, so the description when working with large features will be found at http://lists.osgeo.org/pipermail/qgis-developer/2015-April/037528.html ? Shoulld I insert a link to this page into the user manual?

**Comment by elpaso** [comment]
Absolutely not! That email link was an example on how much noise was generated on qgis-developer ML by an Apache specific question that had nothing to do with QGIS.

IMHO serving large webservice content has nothing to do with QGIS Server, it is a topic for (web) system administrators and it's well described in the manual pages of the web server the sysadmin decide to use (be it Apache, Nginx or whatever).

Dont' forget that the audience for QGIS Server is not the same as for QGIS desktop.

I suggest we provide an example for a minimal working configuration on Apache and tell the sysadmin to look at the manual pages of the web server (Apache etc.) he is going to use for deployment.

If is there anything in the configuration that is really specific to QGIS (and AFAIK there isn't any) we should provide detailed description of that specific topic.

**Comment by m-kuhn** [comment]
> IMHO additional tips never hurt, and can help users. Perhaps this kind of stuff can be added as .. note::

+1

Tips help to decrease noise on the mailinglists and to be aware of possible problems. Especially for a case like this that is easily missed in basic testing and hard to debug. If maintaining server specific configuration options is too much work just point out the information and link to the appropriate page in the appropriate upstream documentation.

**Comment by junek** [comment]
as i'm currently working on the user manual I can implement a description for a minimal working configuration on Apache if somebody cooperates with me

**Comment by elpaso** [comment]
I believe you can find some recently tested tips here:

http://www.itopen.it/qgis-server-python-plugins-ubuntu-setup/

You may add the following lines with a comment like:

 # Raise the following value in case of WFS editing failures with large geometries
 FcgidMaxRequestLen 26214400

**Comment by junek** [comment]
The new text ist ready!
