### ISSUE TITLE
Figure OGR 1 needs an update

### ISSUE THREAD

**Issue by junek** [qgis/QGIS-Documentation#483]
See new information about Use contextual WMS-Legend
https://github.com/qgis/QGIS-Documentation/commit/b53594dddafa1029c5a2163d4b25ff6db6eafad1

**Comment by SrNetoChan** [comment]
@junek . Although I have been the one creating the current screenshot, I can't seem to find the address for DM Solutions WMS service. Can you help me?

**Comment by SrNetoChan** [comment]
I don't think the DM Solution WMS service is still active. At least the site does not seem to be. Should we choose another example?

**Comment by pcav** [comment]
There is plenty of good WMS around nowadays. better remove the old stuff, and replace with newer ones.
I can point out a collection here:
http://eusoils.jrc.ec.europa.eu/wms/wms.htm

**Comment by junek** [comment]
Yes, let's choose another example  I will adapt the text for http://eusoils.jrc.ec.europa.eu/wms/wms.htm. Alexandre what do you think about it?

**Comment by SrNetoChan** [comment]
Fine for me. I will create a screenshot for it.

**Comment by junek** [comment]
Text is ready.

**Comment by SrNetoChan** [comment]
I will leave it open until I create the screenshot.
