### ISSUE TITLE
purge out of date translated screenshots from doc

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#487]
would be nice to delete from translated doc screenshots that are not up to date.

**Comment by diethard2** [comment]
Dutch Documentation is purged and does not contain outdated localised images

**Comment by yjacolin** [comment]
Could we close this issue now? :)

**Comment by DelazJ** [comment]
Hi,
Yves, can you wait till tonight, please? The pull request I sent was only for 2.6 doc. So even if Dutch are now up-to-date, there are many languages (especially French) using 1.x images. I'll prepare and send a pull request that belongs to 2.8 this day.
thanks

Envoyé depuis mon HTC

----- Reply message -----
De : "Jacolin" <notifications@github.com>
Pour : "qgis/QGIS-Documentation" <QGIS-Documentation@noreply.github.com>
Cc : "DelazJ" <delazj@gmail.com>
Objet : [QGIS-Documentation] purge out of date translated screenshots from doc (#487)
Date : ven., mai 22, 2015 12:57

Could we close this issue now? :)

&mdash;

**Comment by yjacolin** [comment]
No problem to wait! Sorry I didn't want to rush you :)
