### ISSUE TITLE
[needs-docs][gps] Fix mouse cursor GPS distance display for touch screen devices

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4880]
Original commit: https://github.com/qgis/QGIS/commit/ff839a4456ffa537b52d050b78ad17c2512fd4b1 by nyalldawson

On touch screen devices, we can't show the GPS distance status bar message
as the cursor moves (because there's no "hover" mouse move events to trigger
this from). So for these devices, use a tap-and-hold event to trigger the
"current GPS distance from finger" status bar message.

**Comment by havatv** [comment]
I don't think this needs any documentation, unless the problem that this solves is documented.
