### ISSUE TITLE
[needs-docs] Add a recenter button to the GPS information panel

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4881]
Original commit: https://github.com/qgis/QGIS/commit/51f4f032f68391236a4adf67b17312e25f761271 by nyalldawson

There's NO way to recenter the map on the GPS location, which is a
HUGE ux limitation in QGIS' GPS handling. This commit adds a new
"Recenter" button to the panel to allow users to jump right to
the current GPS position.

**Comment by DelazJ** [comment]
Duplicate of #4882
