### ISSUE TITLE
[needs-docs] Rename "Define layer projection" to "Define Shapefile projection"

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4889]
Original commit: https://github.com/qgis/QGIS/commit/9347d9d5311e625df0c70eaf937e20ab0ce51992 by nyalldawson

This algorithm ONLY works on shapefile inputs, so make that clear in the algorithm's
display name and helper strings

(cherry picked from commit 692a14090bcebfd253fa3e58dccf2999ad509894)

**Comment by DelazJ** [comment]
backport of #4875
