### ISSUE TITLE
[feature] add Fill noData cells algorithm and tests

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4931]
Original commit: https://github.com/qgis/QGIS/commit/ea7167e135b47174b240ae4306406a7b3ee8189f by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment]
To place in https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/rastertools.html
