### ISSUE TITLE
[FEATURE][processing] Add algorithms for raising warnings and exceptions from models

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4932]
Original commit: https://github.com/qgis/QGIS/commit/5f533e561c903e37fb6d6498d62278a3ee3b9669 by nyalldawson

These algorithms raise either a custom warning in the processing log, OR raise
an exception which causes the model execution to terminate.

An optional condition expression can be specified to control whether or not
the warning/exception is raised, allowing logic like "if the output layer from
another algorithm contains more then 10 features, then abort the model execution"

Sponsored by Fisel + König

**Comment by DelazJ** [comment]
Fixed in #6713
