### ISSUE TITLE
[feature] Relation widget force suppress popup

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4942]
Original commit: https://github.com/qgis/QGIS/commit/bc12cb12e7a331e086ab21d0bf1cb218d8942253 by elpaso

Adds an option to the relation widget configuration
to suppress form popup open when new features are
added in an embedded form context.

This option overrides the form-level option (that might
still be the desired behavior when the form is used
as a standalone form).

![image](https://user-images.githubusercontent.com/142164/75422772-98d20800-593d-11ea-82af-9519cf8882ed.png)

**Comment by elpaso** [comment]
@DelazJ I just added a snapshot, please let me know if it's enough information.

**Comment by DelazJ** [comment]
Hi @elpaso yes I think there are enough information for anyone willing to document this. Thanks.

**Comment by DelazJ** [comment]
@elpaso Here also, this is what I get in a self-build 3.22
![image](https://user-images.githubusercontent.com/7983394/142183515-e67bde1a-e9f8-4e02-bcc0-28541991d04e.png)
And nothing new in d-d mode

**Comment by elpaso** [comment]
@DelazJ sounds like a bug to me, this isn't what is expected for a relation.

**Comment by DelazJ** [comment]
Do I need some particular modules (or whatever it's called) for building?

**Comment by elpaso** [comment]
> Do I need some particular modules (or whatever it's called) for building?

Sorry, I don't understand what you are asking.

**Comment by DelazJ** [comment]
I meant could it be that while building QGIS on my computer, I forgot to add something in the cmake (hence a local bug) or should the options should just be there, by default, as core (hence a global issue)?

**Comment by elpaso** [comment]
> I meant could it be that while building QGIS on my computer, I forgot to add something in the cmake (hence a local bug) or should the options should just be there, by default, as core (hence a global issue)?

No, you should have it working out of the box with no custom cmake options needed.

**Comment by elpaso** [comment]
@DelazJ I think there is an UX bug: if you switch mode (to d&d) you have to click on the item again to make the config widget appear.

**Comment by elpaso** [comment]
I don't think the bug is related to my PR though.

**Comment by DelazJ** [comment]
I tested and your trick does not work. Opened a report at https://github.com/qgis/QGIS/issues/46138

**Comment by selmaVH1** [comment]
This feature is described in the [D&D section](https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/joins_relations.html#vector-relations). The Autogenerate still has the same problem as @DelazJ mentioned in the [last comment](https://github.com/qgis/QGIS/issues/46138) of this discussion. Let's close this ticket and open a new one when this bug (or what ever it is) gets fixed.
