### ISSUE TITLE
[feature] PostGIS raster expose set filter to app

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4962]
Original commit: https://github.com/qgis/QGIS/commit/542c183f005bc406d251c2ea029452b5e1cc5ad9 by web-flow

[feature] PG raster expose set filter to app

**Comment by felixfeckler** [comment]
I guess this one doesn't need documentation, since in  https://docs.qgis.org/3.22/en/docs/user_manual/managing_data_source/opening_data.html#loading-a-database-layer it is already stated that filters can be used, and there is no distinction between raster and vector tables.
