### ISSUE TITLE
Miss information about where Eclipse/pydev can be found

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#497]
In http://docs.qgis.org/2.6/fr/docs/pyqgis_developer_cookbook/ide_debugging.html, there is a link to reach Pyscripter website but nothing about Eclipse, though the doc is about both. While checking, i was unable to decide how to choose such application. 
Shouldn't some informations be added to help new users to choose convenient Eclipse version?

**Comment by ThomasG77** [comment]
A PR to solve this issue is waiting for a feedback

**Comment by havatv** [comment]
It should not be necessary to tell the reader what to choose.  These are alternatives, and both are described (at least for QGIS 2...).
