### ISSUE TITLE
[FEATURE] Add expression variables for current map temporal range

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4986]
Original commit: https://github.com/qgis/QGIS/commit/6dbf341d04983961ada7ed48a40a636b11843587 by nyalldawson

Adds:

@map_start_time: Start of the map's temporal time range (as a datetime value)
@map_end_time: End of the map's temporal time range (as a datetime value)
@map_interval: Duration of the map's temporal time range (as an interval value)

**Comment by DelazJ** [comment]
doc at https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/expression.html#variables-functions
