### ISSUE TITLE
The description of attribute table item in print composer is outdated

### ISSUE THREAD

**Issue by SrNetoChan** [qgis/QGIS-Documentation#499]
While doing the screenshots for it, I have noticed that the attribute table item description, in the print composer, seem outdated. Several options have disappeared or have changed their places in the item properties. @junek can you have a look at the text, please? 

https://github.com/qgis/QGIS-Documentation/blob/master/source/docs/user_manual/print_composer/print_composer.rst#the-attribute-table-item

Figures Attribute table 1, 2, 4 and 5 must be updated as well.

**Comment by junek** [comment]
I can care about this issue, but have no more resources afterwards for updating the manual )-:

**Comment by junek** [comment]
I see the Figure Attribute Table 1 is correct, or did you update it already?

**Comment by SrNetoChan** [comment]
I have fixed it already. I have a feeling that something is wrong... there is no longer an "appearance" options. But I can't find it's option elsewhere. I will try to get answers in the dev-list

**Comment by junek** [comment]
????
I'm using QGIS 2.8.1 and there is an appearance menu with the features Show empty rows, Display header, Empty tables, Message to display, Background color ... Ok I will read the dev-list

**Comment by SrNetoChan** [comment]
uhm... then it might be a problem with my instalation... or my project.

**Comment by SrNetoChan** [comment]
Ok, it's project related. With a new project, I was able to see the appearance menu. This may be a legacy bug.

**Comment by SrNetoChan** [comment]
I have updated the screenshots here https://github.com/qgis/QGIS-Documentation/commit/cacb92d13de8adda26709ff1dbff48494600f31c.
Once the description is fixed this issue can be closed.

**Comment by junek** [comment]
I see!

**Comment by junek** [comment]
Hello I have compared Figure Composer Attribute Table 2 from your commit cacb92d with the Print Composer Attribute Table Item of QGIS 2.8.1. OpenSuSE. I can see a Relation button in the main properties here ....

**Comment by SrNetoChan** [comment]
I will have a look, maybe I need to have relations set in my projects, or this might be the same problem as before and some options are not shown for old projects (Probable bug).

**Comment by SrNetoChan** [comment]
I have fixed the screenshot of Figure Composer Attribute Table 2. For what I can see, for relation options to show up, we have to choose "relation child" as source.

**Comment by junek** [comment]
Sorry I can't see a relation button in the testing Dokumentation.
