### ISSUE TITLE
QGIS Training 8.1.2. Build Virtual Raster - Error in Executing

### ISSUE THREAD

**Issue by jodieq** [qgis/QGIS-Documentation#4994]
## Description

I have been working through the most recent QGIS training doumentation (link provided) and have receieved an error in processing the algorithm 'Build virtual raster'. Unfortuinately I do not have any programming/coding experience to solve myself. I believe I have followed the steps correctly, as provided on the linked page under step 8.1.2 and using the raster files provided. 

See attached screenshot for error details. 

Steps followed as below:

1. Open the Build virtual raster algorithm from the GDAL ‣ Raster miscellaneous;

2. In the dialog that appears click on the … button next to the Input layers parameter and check all the layers or use the Select All button;

3. Uncheck the Place each input file into a separate band parameter- Notice the text field below. What this dialog is actually doing is that it’s writing that text for you. It’s a long command that QGIS is going to run.

4. Finally click on Run.

Page URL: https://docs.qgis.org/3.4/en/docs/training_manual/rasters/data_manipulation.html
![8-4-1 Build virtual raster](https://user-images.githubusercontent.com/62006782/76288764-74354300-62e2-11ea-96b2-162cf5b2d916.jpg)

**Comment by DelazJ** [comment]
Hi @jodieq 
I followed the steps on both 3.10.0 (macOS) and 3.10.3 (osgeo4w) and it runs OK. We have the same commands but I can see we have different versions of gdal (and proj) and some recent versions were playing weirdly with QGIS. Could you please update your QGIS version to 3.10.3 and try again? Thanks

**Comment by ioalexei** [comment]
I am able to run this part of the tutorial without any errors - QGIS version 3.30.0 GDAL version 3.6.2.

As this issue is 4 years old and cannot be reproduced, could it be closed?
