### ISSUE TITLE
Section 14.4.2: file forest_stands_2012.shp not available in forestry folder

### ISSUE THREAD

**Issue by sn1054** [qgis/QGIS-Documentation#500]
Module Forestry Application of the Training Manual. 
I have downloaded the data for the Forestry Application from this link, mentioned at the beginning of the module:
https://dl.dropboxusercontent.com/u/3200993/forestry_data.zip
The layer forest_stands_2012.shp necessary for section 14.4.2 is not available there. Does any one have it?
Tks

**Comment by dt1985** [comment]
I have the same problem, I haven't found yet the file "forest_stands_2012.shp", i searched on the official qgis website and other ones without any results.
could you get the file missing ?
Thanks

**Comment by sn1054** [comment]
No... 
In the end I made one myself, trying to follow the picture on the manual. It didn't turn out exactly the same, but it was a good exercise and worked fine for the rest of the module. Anyways, if you don't have 2h to do that and if you're interested, I can send you mine to use as a base. Just let me know.
Good luck!

**Comment by dt1985** [comment]
I have no experience in forest interpretation , so it would be nice if you can afford to use your file.
Thank you very much.

**Comment by sn1054** [comment]
Here it is:
https://github.com/sn1054/QGIS

Have fun!

**Comment by dt1985** [comment]
I downloaded your file and I opened it in qgis , it worked!
Thank you for your help, I appreciate it.
Have a nice week end

**Comment by sn1054** [comment]
:) any time. you too!

**Comment by elpaso** [comment]
Thanks! 
I'd suggest to make a pull request to add this file to the official QGIS training manual

**Comment by sn1054** [comment]
Done :) Thank you for the suggestion!

**Comment by henkth** [comment]
Hello sn1054. Your uploaded forest_stands_2012.shp file gives an Page not found error. Could you please be so kind to upload it again. Thanks!

**Comment by rduivenvoorde** [comment]
@yjacolin @sn1054 @egonzale @elpaso @pcav @anitagraser @dassau 

I've taken the shp file from https://github.com/sn1054/forest_stands_2012_complete and added that one and one where the excercise is not done yet, and I added it to the forestry_data.zip which I added in the training_manual_exercise_data.zip, available here:

http://qgis.org/downloads/data/

I removed all zips which were available here 

http://download.osgeo.org/qgis/data/

and merged new parts in the zip's at http://qgis.org/downloads/data/

hopefully it is easier now to maintain one set of data for exercises, now we have ONE canonical download place: http://qgis.org/downloads/data/
