### ISSUE TITLE
[FEATURE][processing] Allow interactive resizing of model components

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5002]
Original commit: https://github.com/qgis/QGIS/commit/3b61938e24d44be93d686a6d5499baf8368561ad by nyalldawson

Allows for components to be freely resized via the standard mouse controls

**Comment by roya0045** [comment]
This is already in.

**Comment by DelazJ** [comment]
Fixed in #6027
