### ISSUE TITLE
[FEATURE][processing] Add action to model designer to delete all selected components

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5003]
Original commit: https://github.com/qgis/QGIS/commit/1e67ee42fa95d7ea3078f346f28a5d29b77c2177 by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by roya0045** [comment]
This seems to be in already under https://github.com/qgis/QGIS-Documentation/blob/6c6b13a390e7d20278643fd6a4899fd0b212ebab/docs/user_manual/processing/modeler.rst with delete Selected components. @DelazJ  ok to close?

**Comment by DelazJ** [comment]
Fixed in #6027
