### ISSUE TITLE
Drag'n'drop improvements backport to 3.10 (#34656)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5006]
Original commit: https://github.com/qgis/QGIS/commit/2225fb641bdb22c9970584108fe2131b38474ae1 by web-flow

* [FEATURE] Merge pull request #34411 from 3nids/dnd_sync_selec

improvement of the Drag'n'Drop designer

* Merge pull request #34433 from 3nids/dnd_part2

drad'n'drop improvents part 2

* drag'n'drop improvements part 3 (#34479)

* drag'n'drop improvements

part 3

this completely removes hidden config accessible under double click
now a widget groupbox (by opposition to the field config) is shown on top of the right panel

* remove assert from a left over (fix crash) (#34503)

the assert was copied from other class and I was running with RelWithDebugInfo and not Debug.

* Update CMakeLists.txt

* Update CMakeLists.txt

* move to moc headers

* sip include

**Comment by DelazJ** [comment]
Fixed in #4983
