### ISSUE TITLE
[feature][processing] Add dedicated parameter type for database schemas

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5010]
Original commit: https://github.com/qgis/QGIS/commit/93c917f7b6e93bae26a16078ace44879ff3930d8 by nyalldawson

Allows selection from the existing database schema for a specific
database provider connection (the provider must implement the connections API)

**Comment by havatv** [comment]
Great addition!
It would be nice to have an ALG decorator for it. Could it be added to `python/processing/algfactory.py` (and `python/plugins/processing/core/parameters.py`)?
