### ISSUE TITLE
[feature][processing] Add dedicated parameter type for database tables

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5011]
Original commit: https://github.com/qgis/QGIS/commit/513966ca804df8631dac381731b99792af0e0b16 by nyalldawson

Allows selection of an existing database table for a specific
database provider connection (the provider must implement the connections API)

**Comment by havatv** [comment]
Great addition!
It would be nice to have an ALG decorator for it. Could it be added to `python/processing/algfactory.py` (and `python/plugins/processing/core/parameters.py`)?
