### ISSUE TITLE
[feature][plugin manager] allow to install stable or experimental

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5021]
Original commit: https://github.com/qgis/QGIS/commit/c924cfd1d24ccabf53aae27a99c2cbc19474bd81 by olivierdalang

Unfortunately this naughty coder did not write a description... :-(

**Comment by roya0045** [comment]
@DelazJ Unsure what to label plugin-manager issues

**Comment by DelazJ** [comment]
Plugins, it's.
