### ISSUE TITLE
[FEATURE][processing] Add new algorithm "Filter by geometry type"

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5028]
Original commit: https://github.com/qgis/QGIS/commit/a7f33be401db108a4f49cab4ca2a5d59728dffea by nyalldawson

This algorithm filters features by their geometry type. Incoming
features will be directed to different outputs based on whether
they have a point, line or polygon geometry.

Allows for model creation which responds to different input
layer geometry types by applying different logic depending on the
input geometry type.

**Comment by havatv** [comment]
Covered by #5030.
