### ISSUE TITLE
[FEATURE][processing] Add algorithm to filter by layer type

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5029]
Original commit: https://github.com/qgis/QGIS/commit/c1470c48304db1d5fa46537a47ee327c5f4cbb7b by nyalldawson

This algorithm allows conditional model branching based on an input
layer type. For instance, it allows a model to adapt to the actual
layer type of a generic "map layer" parameter input, and decide
which branch of the model to run as a result.

**Comment by havatv** [comment]
Covered by #5030.
