### ISSUE TITLE
[FEATURE][MESH] coloring mesh vector dataset with color ramp shader (#35216)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5124]
Original commit: https://github.com/qgis/QGIS/commit/20a7ed44acd68b2a988a4191a175eb64858a7377 by web-flow

fixes #33978 Allows user to color the mesh layer vector dataset (arrow, stream lines, traces) with color ramp shader depending on the magnitude of the vector.

**Comment by DelazJ** [comment]
Duplicate of #5125
