### ISSUE TITLE
Adding attributes to memory layer doesn't work as documented

### ISSUE THREAD

**Issue by anitagraser** [qgis/QGIS-Documentation#516]
No attributes are added to the memory layer when pr.addAttributes is used as described in:
http://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/vector.html#memory-provider

Instead, I could define attributes in the URI using field=name:type syntax.

**Comment by m-kuhn** [comment]
The provider does not notify the vector layer of changes.

Either tell the vector layer to fetch changes from the provider

```
pr.addAttributes(...)
vl.updateFields()
```

or introduce changes in the vector layer and push them to the provider from there

```
vl.startEditing()
vl.addAttribute(...)
vl.commitChanges()
```

**Comment by anitagraser** [comment]
Thanks for the explanation! Has the behavior always been this way? Is this specific to the memory provider?
