### ISSUE TITLE
[feature][processing] Allow saving outputs direct to other database
destinations

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5160]
Original commit: https://github.com/qgis/QGIS/commit/c2161638d16c954186f0ecc4769bc7645636f01f by nyalldawson

Previously outputs could only be written direct to postgres databases.
With this change, this functionality has been made more flexible and
now supports direct writing to any database provider which implements
the connections API (currently postgres, geopackage, spatialite and
sql server)

Ultimately this exposes the new ability to directly save outputs
to SQL Server or Spatialite databases (alongside the previous
GPKG+Postgres options which already existed)

(As soon as oracle, db2, ... have the connections API implemented
we'll instantly gain direct write support for those too!)

**Comment by felixfeckler** [comment]
This one is documented and fixed by #6856
