### ISSUE TITLE
Inconsistency in QGIS Python API documentation pages

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS-Documentation#5168]
## Description

In QGIS Python API documentation pages there are same inconsistencies among various versions:

for **master, 3.10 and 3.4**:

![image](https://user-images.githubusercontent.com/16253859/77742829-63413d00-7017-11ea-90d8-11571e1a13cd.png)

![image](https://user-images.githubusercontent.com/16253859/77741827-d1850000-7015-11ea-85e7-a3e61f2856b6.png)

for **3.8, 3.6, 3.2, 3.0**:

![image](https://user-images.githubusercontent.com/16253859/77742752-43117e00-7017-11ea-97b2-7e76873218f6.png)

![image](https://user-images.githubusercontent.com/16253859/77742361-abac2b00-7016-11ea-911a-2fcb9a0ea406.png)

**Comment by DelazJ** [comment]
@agiudiceandrea qgis python api docs issues are to be reported at https://github.com/qgis/pyqgis/issues.
Closing then. Thanks for your understanding.

**Comment by agiudiceandrea** [comment]
Sorry...

**Comment by DelazJ** [comment]
No worries. Afaik, this is mentioned nowhere...
