### ISSUE TITLE
[FEATURE][processing] Port map layer widget wrapper to new c++ api

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5174]
Original commit: https://github.com/qgis/QGIS/commit/7269d682b315c57dee513620796172357a37fdc9 by nyalldawson

This is a test run, after merged I'll port the other similar map layer
parameters (feature source, raster layer, vector layer, etc)

**Comment by roya0045** [comment]
@DelazJ This seems to be a backend thing and shouldn't be apparent to users.

**Comment by DelazJ** [comment]
Indeed. Closing!
