### ISSUE TITLE
[feature][processing] Port Feature Source, Raster, Vector and Mesh Layer parameters to new API

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5179]
Original commit: https://github.com/qgis/QGIS/commit/d40990e15533cc96e6fb4e170ee1d5aafb1f47e8 by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment]
I'd say API thing. Opinions?

**Comment by DelazJ** [comment]
This one should be fine to close. I think the corresponding parameters are mentioned in the docs.
