### ISSUE TITLE
[FEATURE][processing] Add "random points on lines" algorithm

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5183]
Original commit: https://github.com/qgis/QGIS/commit/c774ade88fc5eb7eb4ab633707f1c55bc1e3c68e by web-flow

The Random points on lines algorithm supplements the existing "Random points along line" algorithm, and will prove to be more useful to the majority of users than the "original".

Features:

The points are distributed randomly over the lines based on "along the line" distance, meaning that the distribution of the points will be flat over the length of the line (each place on the feature has the same probability of being "hit"). 

The Random points along line, on the other hand, uses a line segment based approach, meaning that the density will depend on the segment length (short segments will have a higher point density than longer ones).

**Comment by havatv** [comment]
I will handle this one.
