### ISSUE TITLE
[processing][FEATURE] After running a model through the model designer,
show the obtained values for all child algorithm outputs within the designer
canvas

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5190]
Original commit: https://github.com/qgis/QGIS/commit/5963b90f2ceb398ec1e24058e12dfe1ecef195b0 by nyalldawson

This gives users better tools for debugging models - they can see exactly
what values were output by the child algorithms and flowed into other
parts of their model

**Comment by DelazJ** [comment]
Duplicate of #5191
