### ISSUE TITLE
[FEATURE][processing] Allow creation of group boxes in models

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5203]
Original commit: https://github.com/qgis/QGIS/commit/4fa9083cf6b6aa333c761b5aa3625bec2410f254 by nyalldawson

These are a visual guide, allowing designers to create logical groups
of algorithms relating to a single task ("eg 'Prepare data')

The title and color of the group boxes can be customized

**Comment by roya0045** [comment]
The Add Group Box is already present in https://github.com/qgis/QGIS-Documentation/blob/6c6b13a390e7d20278643fd6a4899fd0b212ebab/docs/user_manual/processing/modeler.rst , I think this can be closed. @DelazJ

**Comment by DelazJ** [comment]
Fixed in #6027
