### ISSUE TITLE
[FEATURE][processing] Add menu to the Model Designer "View" menu
allowing users to zoom direct to any group box present in the model

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5204]
Original commit: https://github.com/qgis/QGIS/commit/50b723ce7b55c58863f46ae1714167b9b935bcdf by nyalldawson

Allows for simplified navigation of complex models

**Comment by roya0045** [comment]
This is in.

**Comment by DelazJ** [comment]
Fixed in #6027
