### ISSUE TITLE
[FEATURE][processing] Port output parameter wrappers to new c++ API for modeler

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5206]
Original commit: https://github.com/qgis/QGIS/commit/d20a3bddc01f334b7fa31ec5417945d8c919e413 by nyalldawson

This allows a range of new possibilities, including:
- models with static outputs for child algorithms, e.g. always saving
a child algorithm's output to a geopackage or postgres layer
- models with expression based output values for child algorithms, e.g.
generating an automatic file name based on today's date and saving
outputs to that file

**Comment by roya0045** [comment]
@DelazJ When you have the time, could you add a modeler tag, a few issues would benefit from it. Thanks!

**Comment by roya0045** [comment]
@DelazJ nevermind.

**Comment by roya0045** [comment]
@DelazJ Is this a thing that needs to be documented? This is more of a backend changed, though it provide some new capabilities.
