### ISSUE TITLE
[FEATURE] Show a menu next to scale widget buttons, to allow setting
the widget directly to a scale from a print layout map

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5219]
Original commit: https://github.com/qgis/QGIS/commit/3094534b75714af2b6206e804faab722a31fa142 by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by roya0045** [comment]
@DelazJ I'm changing the label, as it can use layout maps, but it's done in the main app, the layout aspect is incidental.

**Comment by ioalexei** [comment]
If I've understood the change correctly it looks like this feature has been documented under [12.9.4. Visibility Scale Selector](https://docs.qgis.org/3.28/en/docs/user_manual/introduction/general_tools.html#visibility-scale-selector). 

Do you think that's enough detail or does it need a bit more explanation?
