### ISSUE TITLE
[FEATURE][layouts] New item type for marker symbols

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5230]
Original commit: https://github.com/qgis/QGIS/commit/632448c4475cc30b7b26eb8bded519a0a3002466 by nyalldawson

Allows marker symbols to be placed directly on layouts, eg.
for manually placing markers over a map item or for creation
of advanced custom legends

**Comment by havatv** [comment]
Covered by #5231.
