### ISSUE TITLE
[FEATURE] Add percentage size unit for Raster Image Marker and Raster fill layers symbology

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5242]
Original commit: https://github.com/qgis/QGIS/commit/0f1f43f77a012622968ece6a8ef2324beae98c9d by web-flow

This patch adds new percentage (percents of original image size) value of size units for Raster Image Marker and Raster fill, allowing the raster images to be scaled by a percentage of their original sizes

**Comment by DelazJ** [comment]
@beketata can you give details on what happens in the following screenshot, please? What is the percentage applied to the raster image? From what i understand in the PR, size is scaled based on the original width but displaying both values made me lost. Thanks
![image](https://user-images.githubusercontent.com/7983394/81390794-576b8f00-911c-11ea-91dd-ad90f0ce0c43.png)
Or is it a bug? I'm using https://github.com/qgis/QGIS/commit/0ada65b210

**Comment by beketata** [comment]
> can you give details on what happens in the following screenshot, please? What is the percentage applied to the raster image? From what i understand in the PR, size is scaled based on the original width but displaying both values made me lost. Thanks

Hi,
I couldn't reproduce such a case as on your screenshot.
In the latest master build when I open any raster image I've got the result similar to the next:
![1](https://user-images.githubusercontent.com/7413903/81658310-763e8e00-945a-11ea-84e1-c2be85bef99c.png)

**Comment by DelazJ** [comment]
I was playing with the different units, lock button and size to get that (on Ubuntu 18.04). I didn't try since my message but right now, this is what i get on another context, on Windows: the dimensions ratio is unlocked, but height is unavailable and the button state is on push, whatever unit I take. Something looks buggy there imho, but since when... I don't know.
![rasterimage](https://user-images.githubusercontent.com/7983394/81685503-5dcd7400-9458-11ea-93c7-3f92275c19a1.png)
Btw, could you give a look to #5471, whether it reflects what you changed? Thanks.

**Comment by beketata** [comment]
You are right.

Unfortunately, it's not a simple bug, but it's a wrong design.
The first issue is according to this design, the marker does not have two-dimensional size (x and y) in the source code, but only one “size”. Therefore, the “height” field is always gray, although the bitmap has a both dimensions of course.

By the right design the width and height text field should always be editable regardless of the "lock aspect ratio" switch, and its gray color is also misleading:

 ![3](https://user-images.githubusercontent.com/7413903/81800280-6d21ef80-9534-11ea-94c6-8d9733cc7233.png)
If the "lock aspect ratio" switch is locked, editing of any dimentsion should change another one in proportion to the aspect ratio of the image as follow:

![1](https://user-images.githubusercontent.com/7413903/81800103-2207dc80-9534-11ea-969a-10a0a01ea84e.png)

But if the lock is unlocked, you should have the ability to change any dimension independently of each other:

![2](https://user-images.githubusercontent.com/7413903/81800150-2e8c3500-9534-11ea-90e2-c1c1ecf37664.png)

The matter is complicated if the layer has different images with different proportions. What behavior should be in this case? And if the image path is defined by some expression for example?
