### ISSUE TITLE
[FEATURE][processing] New algorithm "Contour Polygons"

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5243]
Original commit: https://github.com/qgis/QGIS/commit/b73bd58cfb9a45a99629ee5dbcda232fa66b6ef9 by web-flow

With similar functionality to the existing GDAL contour algorithm, but exporting polygon representations of the contours

**Comment by rosaguilar** [comment]
Should this issue be closed? 
https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/gdal/rasterextraction.html

> Original commit: [qgis/QGIS@b73bd58](https://github.com/qgis/QGIS/commit/b73bd58cfb9a45a99629ee5dbcda232fa66b6ef9) by web-flow
> 
> With similar functionality to the existing GDAL contour algorithm, but exporting polygon representations of the contours

**Comment by DelazJ** [comment]
Good catch @rosaguilar. Thanks
Fixed in #6218
