### ISSUE TITLE
QGIS fails to export data of dynamic and cached web map services and ends up with exporting black images in particular case!! 

### ISSUE THREAD

**Issue by mmariamkhayyat** [qgis/QGIS-Documentation#5264]
QGIS fails to export data of dynamic and cached web map services and ends up with exporting black images in particular case!! 
As the QGIS has a tool to export the data of dynamic and cached web map services (esri), it is fails to do so in particular cases and ends up with the following error box and exporting black images in particular case!! 
The version of QGIS that has been used is 3.12.1, but also this issue appears in some older versions.

What might be the reason beyond that?!

![20f](https://user-images.githubusercontent.com/63535618/79064388-24ff7b00-7cb1-11ea-8e02-e0828994923b.png)
![18](https://user-images.githubusercontent.com/63535618/79064390-2a5cc580-7cb1-11ea-997f-7cc3f8099629.png)
![19](https://user-images.githubusercontent.com/63535618/79064392-3183d380-7cb1-11ea-910b-89cb7ed86c59.png)

**Comment by jamalnuman432** [comment]
I have tried QGIS Desktop 3.8.3 to download data from the web services below but fails
https://adaptor.geomolg.ps/adaptor/rest/services

I also started everything from scratch on my local machines but unfortunately fails either as shown in the screenshot below

![Clip_310](https://user-images.githubusercontent.com/63537453/79065153-bae9d480-7cb6-11ea-926c-cfcd07ab8e5f.jpg)

![Clip_311](https://user-images.githubusercontent.com/63537453/79065169-dc4ac080-7cb6-11ea-87c7-d62448a56606.jpg)

![Clip_312](https://user-images.githubusercontent.com/63537453/79065174-ee2c6380-7cb6-11ea-9ad1-18688c55088b.jpg)

**Comment by DelazJ** [comment]
Dear @mmariamkhayyat and @jamalnuman432 
This repository is meant to write and address [QGIS documentation](https://docs.qgis.org) issues. Problems related to the application itself should be reported in the [application bug tracker](https://GitHub.com/qgis/QGIS/issues) or, IMHO, in your case, you may want to ask in the [user mailing list ](http://qgis.org/en/site/forusers/support.html) for help and debug first.
I'm closing. Thanks for your understanding.
