### ISSUE TITLE
[FEATURE][processing] Allow copying/cut/paste of model components

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5275]
Original commit: https://github.com/qgis/QGIS/commit/47f96e246621660b0b941a0a6df9f1b5da33c7dd by nyalldawson

This commit allows users to copy and paste model components, both
within the same model and between different models

**Comment by roya0045** [comment]
This is in.

**Comment by DelazJ** [comment]
Fixed in #6027
