### ISSUE TITLE
[feature] add API to import/export ArcGIS MapServer and FeatureServer
connections. This is API-only change not visible for users.

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5289]
Original commit: https://github.com/qgis/QGIS/commit/99a930ca51a1758482b3abeb8c021dce6f301a34 by alexbruy

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment]
not to document then.
