### ISSUE TITLE
[feature] add vector tile page to the Datasource Manager

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5303]
Original commit: https://github.com/qgis/QGIS/commit/f786e5d75e4da74fb6ed8614d912b77510cb7086 by alexbruy

Unfortunately this naughty coder did not write a description... :-(

**Comment by lajunek** [comment]
@DelazJ @havatv @alexbruy How do the min max zoom levels in the connection dialog for Vector Tiles corrrespond with the zoom in QGIS? Can somebody give an explanation?

**Comment by lajunek** [comment]
@alexbruy do the min/max zoom levels correspond with the project defined scales that can be defined in the Project Properties?

**Comment by lajunek** [comment]
@alexbruy are there different min/max zoom levels in QGIS, depending on the CRS the Vector Tiles provide?

**Comment by alexbruy** [comment]
@lajunek, sorry I have no idea if there is a dependency between CRS and zoom levels. My guess will be that they are completely independent, e.g. you can have a layer with zoom levels from 2 to 10 and another layer with zoom levels 4-20.

**Comment by DelazJ** [comment]
@lajunek some info about the zoom levels https://wiki.openstreetmap.org/wiki/Zoom_levels
