### ISSUE TITLE
QgsRubberBand.setSvgIcon  it does't show how to change the size of the SVG QGIS3.10

### ISSUE THREAD

**Issue by xmaj2008** [qgis/QGIS-Documentation#5319]
## Description

I want to add a SVGpic to the QgsPointXY(123, 34.38) on a mapcanvas use the QgsRubberBand.setSvgIcon .the codes are as follows；
r = QgsRubberBand(self.mapCanvas,QgsWkbTypes.PointGeometry)
r.addPoint(QgsPointXY(123, 34.38), doUpdate=True, geometryIndex=0)
r.setSvgIcon("D:/Qgis/code/Demo3_9TreeDock/svg/tree.svg", QPoint(0, 0))
r.setIconSize(5)

But I can't change the size of the SVG shown on the mapcanvas even I change the Original size of the SVG.
I found that QgsRubberBand.setSvgIcon is in QGIS 3.10 3.12,but in 3.2 3.4  it disappeared.
I think it is very useful in QGIS  Secondary Development.
Hope to solve this problem.

Page URL:
https://qgis.org/pyqgis/3.10/gui/QgsRubberBand.html?highlight=rubber#qgis.gui.QgsRubberBand.setSvgIcon

**Comment by DelazJ** [comment]
> I want to add a SVGpic to the QgsPointXY(123, 34.38) on a mapcanvas use the QgsRubberBand.setSvgIcon .the codes are as follows；

Quoted from https://qgis.org/pyqgis/3.10/gui/QgsRubberBand.html#module-QgsRubberBand introduction: *The QgsRubberBand class provides a transparent overlay widget for tracking the mouse while drawing polylines or polygons*. Are you sure this is what you need?
Maybe could you find some convenient class to use at https://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/vector.html#appearance-symbology-of-vector-layers but for help, you better ask in QGIS mailing list  (see [support channels](http://qgis.org/en/site/forusers/support.html)). This place is to report issues found at https://docs.qgis.org

>  I found that QgsRubberBand.setSvgIcon is in QGIS 3.10 3.12,but in 3.2 3.4 it disappeared.

Normal! At the end of the description it's mentioned *New in version 3.10.*

**Comment by xmaj2008** [comment]
> > I want to add a SVGpic to the QgsPointXY(123, 34.38) on a mapcanvas use the 
> Normal! At the end of the description it's mentioned _New in version 3.10._
Thanks for your help!
I'm learning QGis.I want to add a SVG(such as a plane) to a fixed position on the base map ,next step I want to make it move follow a line.At the begining I add a .geojson which include a point on the mapcanvas,then I symbology it with a SVG pic.
Someone said you can use the QgsRubberBand.I succeeded add a SVG pic on the mapcanvas using QgsRubberBand.setSvgIcon,but Ican't change its size.

![207652719](https://user-images.githubusercontent.com/30265508/79731739-48679d00-8325-11ea-88cd-1b9923ad8bae.jpg)
The two little one are symbologied.
If its size can be changed ,I think its more convinent.
The version problem is I misunderstood.
Thanks again!

**Comment by havatv** [comment]
I don't think we can help you more here, @xmaj2008. If you need more help, try the QGIS mailing list, as suggested by @DelazJ, or stackexchange.
