### ISSUE TITLE
PyQGIS cookbook / intro: ways to use Python in QGIS

### ISSUE THREAD

**Issue by Houska1** [qgis/QGIS-Documentation#5323]
Congrats on the refactored and updated PyQGIS developer cookbook.

In the intro, lists 4 ways Python is used in QGIS Desktop (console, plugins, startup, custom applications). For completeness, I would suggest also listing the following, even if perhaps the cookbook itself doesn't cover them

- Processing
- Custom functions for expressions

**Comment by havatv** [comment]
Thanks for pointing this out, @Houska1. PR #5324 just includes a mention of processing algorithms and expression functions.

**Comment by Gustry** [comment]
FYI, I got these notes where we can have Python in QGIS:
* Console
* Script
* Processing script
* Processing model converted to Python
* Plugin
* Processing Provider
* Expressions
* Project macros
* Layer actions
* Form in Python
* Standalone application
* `startup.py` file

In this list, I think maybe actions are also a good one? t o add.
Maybe I can try to review other sections.
