### ISSUE TITLE
[FEATURE][layouts] Allow configuring legend patch shapes by
double-clicking on legend items

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5325]
Original commit: https://github.com/qgis/QGIS/commit/ddbcb1f4788f82f3885a0631cb91ebdcc9957d32 by nyalldawson

Allows users to set custom legend patch shapes for items by
entering a WKT string representing the patch geometry

**Comment by havatv** [comment]
#5326 covers this (and contains some documentation).
