### ISSUE TITLE
documentation not included in build

### ISSUE THREAD

**Issue by diethard2** [qgis/QGIS-Documentation#534]
There is some documentation written that is not included in the build of the documentation and therefore generates warnings. 

We have to decide to either include or remove (delete) this documentation.
I think the python documentation for example should be removed. It is an unfinished start and it is there for a while.

Documentation not included:
-training_manual/processing/geomorpho.rst
-training_manual/processing/r_intro.rst
-training_manual/python/index.rst
-training_manual/python/overview.rst
-user_manual/plugins/plugins_sql_anywhere.rst
-user_manual/processing_algs/qgis/vector_table_tools/refactorfields.rst

**Comment by yjacolin** [comment]
- [X] training_manual/processing/geomorpho.rst
- [ ] training_manual/processing/r_intro.rst
- [ ] training_manual/python/index.rst
- [ ] training_manual/python/overview.rst
- [ ] user_manual/plugins/plugins_sql_anywhere.rst
- [ ] user_manual/processing_algs/qgis/vector_table_tools/refactorfields.rst

**Comment by yjacolin** [comment]
We should remove training_manual/python/ chapter.

**Comment by yjacolin** [comment]
*  user_manual/plugins/plugins_sql_anywhere.rst has been removed
* training_manual/processing have been update by @ghtmtt 
* user_manual/processing_algs/qgis/vector_table_tools/refactorfields.rst is up to date.
