### ISSUE TITLE
[FEATURE][MESH] 1D mesh width/color varying (#35926)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5343]
Original commit: https://github.com/qgis/QGIS/commit/f8fae3cf39d86cca7719a8305c673e29750db24e by web-flow

Introduce a renderer for 1D mesh edges that can vary width over the line. The line can also have different color based on the actual dataset value on the line's point.

Co-authored-by: Peter Petrik <zilolv@gmail.com>

**Comment by DelazJ** [comment]
@vcloarec @PeterPetrik can you share a mesh 1D file to test in documentation, please? Thanks.

**Comment by PeterPetrik** [comment]
HI @DelazJ, some files can be found https://github.com/lutraconsulting/MDAL/tree/master/tests/data  e.g. /2dm/lines.2dm or /flo2d/channel/CADPTS.DAT for more complex one.

**Comment by DelazJ** [comment]
Hi @PeterPetrik Thanks.
Do you think it will be possible to add one or two to [our sample dataset](https://github.com/qgis/QGIS-Sample-Data)? Which license?

**Comment by PeterPetrik** [comment]
Sure, they are all MIT licence...
