### ISSUE TITLE
[FEATURE][layouts] Allow control over the horizontal spacing before
legend group/subgroup/symbols

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5351]
Original commit: https://github.com/qgis/QGIS/commit/36339c2c9ecce3f1d96580b7ba468d0781f4f14c by nyalldawson

Gives flexibility to allow "nesting" legend groups/subgroups/symbols
and much greater control over legend item placement

Sponsored by SLYR

**Comment by roya0045** [comment]
@DelazJ spacing section is not documented much and is quite self evident, I don't think this need much documentation.

**Comment by DelazJ** [comment]
I think it's worth a mention. This adds some improvement to legend good looking (I needed it myself and did not notice it until your message)
