### ISSUE TITLE
[needs-docs] remove Server Search tab from the WMS connections dialog
(fix #25660).

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5352]
Original commit: https://github.com/qgis/QGIS/commit/b8c3b0e71f11c53a29432d0556154435b0f3ca34 by nyalldawson

As used catalog does not receive updates for years and we already have
more feature rich search with MetaSearch core plugin.

**Comment by DelazJ** [comment]
Duplicate of #5353
