### ISSUE TITLE
Remove processing algorithms from pdf build

### ISSUE THREAD

**Issue by ghtmtt** [qgis/QGIS-Documentation#537]
The pdf manual is now more than 700 pages because the build includes the description of all processing algorithms.
IMHO it doesn't have sense to include them.

Is this the line of code we have to uncomment from build?
https://github.com/qgis/QGIS-Documentation/blob/master/source/conf.py#L71

@rduivenvoorde could you handle this?

**Comment by alexbruy** [comment]
Of course this is possible. Please look at README https://github.com/qgis/QGIS-Documentation/blob/master/readme.rst#partial--faster-building

**Comment by ghtmtt** [comment]
Yes I now that it is possible. But i think it is a good idea to remove processing algorithms from the pdf build of the website. If you create the pdf in the documentation web site, by default it includes all the processing algorithms.

**Comment by rduivenvoorde** [comment]
I have to see if we can do this, either by uncommenting this line in the conf.py,
or (I think easier)
during the pdf step (which is after the html build) rm the whole dir  (as for the next language this 'change' will be stashed/dropped and checked out anyway)...
have to test this, but it is/was on my todo list ...

**Comment by rduivenvoorde** [comment]
should be fixed now, please reopen if the algo part is still in the pdf

will do this also in master branch
