### ISSUE TITLE
Small formatting issue in list

### ISSUE THREAD

**Issue by alvaropp** [qgis/QGIS-Documentation#5392]
## Description

Hi, I've noticed a small formatting issue in a list in the "Gentle GIS Introduction".

<img width="716" alt="Screenshot 2020-05-04 09 35 59" src="https://user-images.githubusercontent.com/4785303/80949229-84056b00-8deb-11ea-8bac-e446c3f7a430.png">

I cannot reproduce it locally ( via `make html`).
<img width="706" alt="Screenshot 2020-05-04 09 36 12" src="https://user-images.githubusercontent.com/4785303/80949216-7f40b700-8deb-11ea-9c83-757cc0ea9876.png">

Page URL: [https://docs.qgis.org/3.10/en/docs/gentle_gis_introduction/introducing_gis.html](https://docs.qgis.org/3.10/en/docs/gentle_gis_introduction/introducing_gis.html)

**Comment by DelazJ** [comment]
This was fixed in https://github.com/qgis/QGIS-Documentation/pull/5358 but the 3.10 docs didn't rebuild... (for a while)
@rduivenvoorde, please ?

**Comment by rduivenvoorde** [comment]
@DelazJ building.. all languages, could take some time

**Comment by alvaropp** [comment]
It seems that the new docs have been published correctly, thanks!

**Comment by DelazJ** [comment]
Thanks @rduivenvoorde
