### ISSUE TITLE
Snap on mesh elements (#36171)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5404]
Original commit: https://github.com/qgis/QGIS/commit/0d9a15b7512df21839f75cadcf2de350c19c6acf by web-flow

[API] [FEATURE] Add a method in API to snap on mesh elements (vertex, edge, face)
The method returns the position of the snapped point on the closest mesh element :

**Comment by DelazJ** [comment]
Not sure there is anything to document here. I suggest we close.
