### ISSUE TITLE
[feature][expressions] New expression function "make_interval"

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5448]
Original commit: https://github.com/qgis/QGIS/commit/da042bb61dc7447b41b021838efe42d08b31cdd8 by nyalldawson

Allows direct construction of interval values from years/months/weeks/
days/hours/minutes/second values, without having to construct
a string representation of the interval first

**Comment by DelazJ** [comment]
fixed in #5811
