### ISSUE TITLE
Broken links in the Training Manual Foreword, License section

### ISSUE THREAD

**Issue by snowch** [qgis/QGIS-Documentation#546]
There are a few broken links in the License section of the Foreword:

https://github.com/qgis/QGIS-Documentation/blob/master/source/docs/training_manual/foreword/foreword.rst

The links are:

 - https://github.com/qgis/QGIS-Training-Manual 
 - https://github.com/qgis/QGIS-Training-Manual/blob/master/index.rst

**Comment by rduivenvoorde** [comment]
fixed/rephrased, see #552
