### ISSUE TITLE
[FEATURE][tracing curves] Trace tools generates curved geometries

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5504]
Original commit: https://github.com/qgis/QGIS/commit/350a49597ba34e49b0388cc1f0358c54c7cfe473 by olivierdalang

Unfortunately this naughty coder did not write a description... :-(

**Comment by roya0045** [comment]
@DelazJ I think this does not need to be documented. Users will assume that the trace tool properly replicate curved geometries.

**Comment by DelazJ** [comment]
Already fixed in #6291
