### ISSUE TITLE
[processing][feature][needs-docs] add algorithm for executing SQL queries against
registered SpatiaLite databases

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5509]
Original commit: https://github.com/qgis/QGIS/commit/319d34c1dd8cb3989a3e7fdea3f4e1e9c29a5088 by alexbruy

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment]
Covered by #5510
