### ISSUE TITLE
[feature][expression] base64 to and from functions

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5529]
Original commit: https://github.com/qgis/QGIS/commit/988ac20647f8ac600eefdf5083a8adea4e8865a9 by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment]
The referenced commit provides help for the functions, the functions were introduced in #5528.

**Comment by DelazJ** [comment]
fixed in #5811
