### ISSUE TITLE
[needs-docs][spatialite] Add datetime and date field types in the create new spatialite layer dialog

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5577]
Original commit: https://github.com/qgis/QGIS/commit/def348be2bd386cb6831184a4a3e5688550bb663 by nirvn

Unfortunately this naughty coder did not write a description... :-(

**Comment by roya0045** [comment]
Not sure if Data Loading is the best tag.

**Comment by DelazJ** [comment]
Maybe the "Data loading" label which refers to "opening data" chapter could be modified into "Managing data" whose eponym chapter covers Layer creation, layer opening and characteristics of their formats. I guess that once the writer is pointed to the managing data chapter, it should be obvious in which subchapter to add the info.
