### ISSUE TITLE
Document the spatial filtering of attribute table

### ISSUE THREAD

**Issue by pcav** [qgis/QGIS-Documentation#560]
Please better document this nice and somewhat hidden feature:

The workaround for the slow loading of a big attribute table (see 86d08b6c) is to set the initial mode for the attribute table to "only visible on map" in options. That will request only the features in the current canvas.
Note that this is different from what you can set in the attribute table itself. If set in options the attribute table will always be tied to canvas extent it was opened with - so "show all" within such a table will again only show the features in the initial canvas extent - "show only visible" will still have an effect if you zoom in.

Thanks a lot Juergen for clarifying.

**Comment by yjacolin** [comment]
Commit is here: https://github.com/qgis/QGIS/commit/86d08b6c39bad37e4c9b468f55c4c60981b60fa2

**Comment by DelazJ** [comment]
See also https://lists.osgeo.org/pipermail/qgis-developer/2015-June/038123.html
