### ISSUE TITLE
QGIS 3.12 - StreetSmart Plugin

### ISSUE THREAD

**Issue by Aarsr1** [qgis/QGIS-Documentation#5613]
Hallo,

Mijn collega van systeembeheer heeft vanmorgen de StreetSmart Plugin in QGIS versie 3.12 geïnstalleerd, echter krijg ik de Plugin nu niet te zien in QGIS.
Wij, de Werkorganisatie Langedijk en Heerhugowaard, werken met Citrix.
In de Street Smart documentatie kan ik, en mijn collega, niet terugvinden waar iets wordt weggeschreven voor de StreetSmart Plugin.
Dit zodat ik hier nu ook van gebruik zou kunnen maken in mijn Citrix-omgeving.
Dienen we nog iets te kopiëren?
Zo ja, waarvandaan? P:\hw\quantumgis3.12\apps\ ... ?

Ik hoor het graag. Alvast bedankt.

Met vriendelijke groet,
Rosann Aarsen

**Comment by havatv** [comment]
Hallo, @Aarsr1. Is it possible for you pose your question in English?

**Comment by havatv** [comment]
I guess that you are referring to the QGIS Plugin available on https://www.cyclomedia.com/en/street-smart.
I installed it in my plugin directory (on Ubuntu), but got an error message when I tried to enable it (```FileNotFoundError: [Errno 2] No such file or directory: '/usr/python.exe': '/usr/python.exe'```).

**Comment by havatv** [comment]
Anyway, this is not something related to QGIS documentation, so I suggest that you ask on the mailing list (https://www.qgis.org/en/site/getinvolved/mailinglists.html) or stackexchange.
