### ISSUE TITLE
Remove link to blogs with old API examples

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#563]
In http://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/intro.html, it's stated:
"There are some resources about programming with PyQGIS on QGIS blog(http://blog.qgis.org/). See QGIS tutorial ported to Python (http://blog.qgis.org/node/59.html) for some examples of simple 3rd party apps".
The two links are very very old (2011 and 2007) and probably show examples about the old API. 
I think they should be removed and replaced by blog showing examples up to date ( if someone knows link to such blog...)

**Comment by elpaso** [comment]
I'd suggest to add the examples directly into the cookbook, external references will eventually disappear or become obsolete.

**Comment by ThomasG77** [comment]
This issue can be closed. Now, there are no references to any URL from http://blog.qgis.org within all the cookbook (tried with grep...)

**Comment by DelazJ** [comment]
So let's close it.
Thanks
