### ISSUE TITLE
Make the TOC expandable in online current and testing documentations

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#564]
While selecting a title in QGIS 2.2 documentation, you get in the TOC the list of its section, very useful to directly move among sections.
But since 2.6, the TOC only shows chapters and since we have many sections in a chapter, when the one you are reading is not the one you were looking for, you have to go back to chapter level before choosing another section.
This makes the use of the online documentation very uncomfortable and very rude while reading Processing algorithms chapter.

At least, when clicking on chapter, the reader should have access to section. And I'm wondering if in the case of [Processing algorithms](http://docs.qgis.org/testing/en/docs/user_manual/processing_algs/index.html) in the manual, he shouldn't have access to the sub-section level once a section is selected....
Any idea?

**Comment by ghtmtt** [comment]
@DelazJ can we close this old issue?

**Comment by DelazJ** [comment]
no, it's old but i feel it's still valid

**Comment by havatv** [comment]
This seems to be OK in current documentation. If I go to https://docs.qgis.org/testing/en/docs/training_manual/index.html, the chapters are listed in the left "menu", and in the beginning of the "page", there are links to both chapters and sections.
Would you like to have the sections visible also in the left "menu"?

**Comment by DelazJ** [comment]
> Would you also like to have the sections visible also in the left "menu"?

Yes, that is the request. When you are in the middle of a page and wants to move to another section in the page, it's easier to switch from the left panel than move up to the embedded TOC and find the right target.

**Comment by DelazJ** [comment]
Fixed with the readthedocs theme
