### ISSUE TITLE
wrong list and procedure

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#565]
In [Bug Tracker] (http://docs.qgis.org/2.8/en/docs/user_manual/preamble/help_and_support.html#bugtracker), it's stated : "If you have found a bug and fixed it yourself, you can submit this patch also. Again, the lovely redmine ticketsystem at http://hub.qgis.org/wiki/quantum-gis/issues has this type as well. Check the Patch supplied checkbox and attach your patch before submitting your bug. One of the developers will review it and apply it to QGIS."

1/ the link should be http://hub.qgis.org/projects/quantum-gis/issues
2/ Should we recommend to supply patch as attached file instead of forking the repo and pulling a request which will be linked to the bug report?

**Comment by yjacolin** [comment]
A PR is more appropriate now that we are using github. Thanks!
