### ISSUE TITLE
Some errors in QGIS-Development page

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#566]
In [QGIS-Development](http://qgis.org/fr/site/getinvolved/development/index.html#qgis-development) page, I find the TOC weird:
- a problem with headers (about GRASS) : some subsections are shown like section (unless there are too many sections)
- there is a TOC shown at the right side but it doesn't correspond to the content of the page
- Is there the right place to put such informations about GRASS (too much technical)?  May be we should add this in the Documentation, after Processing features chapter (how to configure and "use" GRASS tools). C++ and Python plugins sections in QGIS-Development page just show links where to get more information. it should be same thing for GRASS I think.

**Comment by yjacolin** [comment]
What you named a TOC in the content is not a TOC, this is some links to another pages but this page seems to need some love as these links doesn't help the reader to understand the structure of the page.

About GRASS documentation, if it is for power user for the process plugin, you should add it somewhere else.

**Comment by DelazJ** [comment]
@yjacolin said
>About GRASS documentation, if it is for power user for the process plugin, you should add it somewhere else.

I'm not the writer and have no skills in GRASS so what seems to be for power user may not really be. :(
Whatever the headers of GRASS section needs indeed to be fixed and this page more easily readable.
