### ISSUE TITLE
In documentation, the bottom "fix me" link doesn't lead to the specific page in Transifex

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#567]
Clicking on "fix me" link at the bottom of QGIS 2.8 documentation leads in Transifex to a page with all the resources instead of just the page concerned by the text to fix (as it seems to work for traduction "fix me" link in QGIS-website)

**Comment by rduivenvoorde** [comment]
There are three things going on here:
1) english resources, do not have translations, so maybe we should not show the fixme link there... 
2) the pages which are NOT rst resources, (but actually templates from the template directory) all should point to the sphinx resource. Pointing to the root of the resources was the best I could offer...
3) while (for what I know) this stuff was working (at least for the website), there has been so much changes in Transifex recently, that it is not very clear if there is something broken there. Or that we do something that you are not supposed to do (creating your own deeplinks).

For 3) I create an issue on transifex: https://github.com/transifex/transifex/issues/342

If it is just not working we can off course remove this functionality

**Comment by DelazJ** [comment]
@rduivenvoorde it is stated in the readme of transifex repo
> Transifex used to be maintained as an open-source project on the side of Transifex.com. Since mid 2012, this repository is no longer actively maintained in favor of working aggressively in extending Transifex.com itself.

I'm afraid your issue report may not be (quickly?) seen. However, I wasn't able to find where to report this issue in their website.

**Comment by rduivenvoorde** [comment]
@DelazJ ouch, thanks for the tip! I was actually redirected to this issue-tracker via a link in transifex... Not so nice that they still point to this, indeed dead, tracker...

I'll  email the issue to support!
