### ISSUE TITLE
Interpolation Plugins

### ISSUE THREAD

**Issue by M-spec-dev** [qgis/QGIS-Documentation#5676]
I Have missing Interpolation Plugins in my QGIS 3.6
-->
Page URL:

**Comment by DelazJ** [comment]
Hi @M-spec-dev 
This is the QGIS official [documentation](https://docs.qgis.org) repository, hence not a place to report this kind of issue.

That said, I'm not aware of any interpolation *plugin* provided by QGIS. QGIS plugins are listed at https://docs.qgis.org/3.10/en/docs/user_manual/plugins/core_plugins/index.html You'll also find some interpolation algorithms in the Processing toolbox (from Processing menu).
Other than that, I'd suggest you ask in a [mailing list](http://qgis.org/en/site/forusers/support.html) and give more information about what that plugin is supposed to do.
I'm closing. Thanks.
