### ISSUE TITLE
QGIS 3.10 3D VIEW CRASH

### ISSUE THREAD

**Issue by PSalazarO** [qgis/QGIS-Documentation#5696]
Crash ID: af47473cd51daf6404da7089863af743c4df76c0

Stack Trace

QgsTilingScheme::tileToExtent qgstilingscheme.cpp:44
QgsDemHeightMapGenerator::render qgsdemterraintileloader_p.cpp:220
QgsDemTerrainTileLoader::QgsDemTerrainTileLoader qgsdemterraintileloader_p.cpp:79
QgsDemTerrainGenerator::createChunkLoader qgsdemterraingenerator.cpp:101
QgsChunkedEntity::startJob qgschunkedentity_p.cpp:383
QgsChunkedEntity::update qgschunkedentity_p.cpp:171
Qgs3DMapScene::updateScene qgs3dmapscene.cpp:255
Qgs3DMapScene::onCameraChanged qgs3dmapscene.cpp:239
QMetaObject::activate :
QgsCameraController::setViewFromTop qgscameracontroller.cpp:193
QgsCameraController::resetView qgscameracontroller.cpp:179
Qgs3DMapScene::viewZoomFull qgs3dmapscene.cpp:172
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1606
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.5-A Coru�a
QGIS code revision: 984615fe1e
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by DelazJ** [comment]
@PSalazarO This is the place to report issues with https://docs.qgis.org, not the issues with the software. You better fill your issue at https://github.com/qgis/QGIS, with details of what you were doing when it happened.
