### ISSUE TITLE
Inconsistence between dialog windows in training repository QGIS 3.10

### ISSUE THREAD

**Issue by simone100** [qgis/QGIS-Documentation#5727]
## Description

When I follow the training manual I find inconsistence with my qgis version. For example I have the version QGIS 3.10, but the training manual show screenshot of dialog that does not correspond to mine. 
For example: look at the pictures with two example that compare the manual and what I can see with my version QGIS 3.10!
![QGIS](https://user-images.githubusercontent.com/51158026/85024524-7bd47580-b176-11ea-86a7-645b7b7b4e3b.png)

Did I something wrong with the installation or the manual uses screenshot from other versions?

Page URL: https://docs.qgis.org/3.10/en/docs/training_manual/vector_classification/classification.html

**Comment by DelazJ** [comment]
Follow this one in the meantime https://docs.qgis.org/testing/en/docs/training_manual/vector_classification/classification.html (almost the same)
Changes were not ported to 3.10 branch (there were some subtleties to fix), yet

**Comment by DelazJ** [comment]
Fixed in #5526
