### ISSUE TITLE
QGIS 3.10, Missing Data in Training Manual Dataset.

### ISSUE THREAD

**Issue by larry64** [qgis/QGIS-Documentation#5742]
![Screenshot_SameLongErrorShot2-](https://user-images.githubusercontent.com/67182659/85195675-ec66c800-b317-11ea-9081-5ded4a8e5ebb.png)

**larry64:     QGIS 3.10, Missing Data in Training Manual Dataset.**
I am working through the Training Manual dataset using QGIS-Data-release_3.10 using Windows 10 OS and QGIS ver. 3.10.6. I could not complete the section Module 6.4.4. Follow Along: Open a Webpage Directly in QGIS. This is because each time I follow the instructions in this section of Module 6.4, I always receive a negative result at the finish: no webpage opens directly using QGIS. Resulting in a popup Python Error window (Screenshot file attached) and text shown below.
When I click-on the ‘Action’ toolbar button: ‘Run Feature Action, Wikipedia’. I receive the following popup Python Error notification,

 “An error occurred during execution of following code:
from qgis.PyQt.QtCore import QUrl; from qgis.PyQt.QtWebKit import QWebView;  myWV = QWebView(None); myWV.load(QUrl('https://wikipedia.org/wiki/Marloth Nature Reserve')); myWV.show()
Traceback (most recent call last):
  File "", line 1, in 
ImportError: cannot import name 'QWebView' from 'qgis.PyQt.QtWebKit' (C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\PyQt\QtWebKit.py)”

Another is, when performing Module 7.2. Lesson: Vector Analysis and opening the Geopackage file, training_data.gpkg for its following lessons. I have found no restaurants or schools layers in this geopackage file which are an essential part of Module 7.2.4. Follow Along: Start a Project and Get the Data, until the finish of Module 7.2.

Also, when starting Module 7.0. Network Analysis; Module 7.3.1. Follow Along: The Tools and the Data. There is no folder called Network_Analysis within the Training Manual dataset, at path; exercise_data/network_analysis/network.qgz and therefore no project file called network.qgz to continue with the QGIS 3.10 Training Manual.
Thank you, GITHUB Team.
larry64

**Comment by havatv** [comment]
Thanks for reporting, @larry64!

Could you test if this code (WebEngine variant) work for you (does not work for me)::

    from qgis.PyQt.QtCore import QUrl; from qgis.PyQt.QtWebEngineWidgets import QWebEngineView; myWV = QWebEngineView(None); myWV.load(QUrl('https://wikipedia.org/wiki/[%name%]')); myWV.show()

This code (WebKit variant) works for me ::

    from qgis.PyQt.QtCore import QUrl; from qgis.PyQt.QtWebKitWidgets import QWebView; myWV = QWebView(None); myWV.load(QUrl('https://wikipedia.org/wiki/[%name%]')); myWV.show()

**Comment by havatv** [comment]
Regarding data for the training manual.
There have been a number of updates to the  training data recently. Could you try to download

    https://github.com/qgis/QGIS-Training-Data/archive/release_3.10.zip

(restaurants and schools should be present, as well as network.qgz)

**Comment by larry64** [comment]
Thanks for your quick reply **havatv**.
I have tested the scripts that you sent me for Module 6.4.4. I received the following results:

1. Could you test if this code (WebEngine variant) work for you (does not work for me)::
from qgis.PyQt.QtCore import QUrl; from qgis.PyQt.QtWebEngineWidgets import QWebEngineView; myWV = QWebEngineView(None); myWV.load(QUrl('https://wikipedia.org/wiki/[%name%]')); myWV.show()

	Larry64.  **Doesn't work for me either !!**

2. This code (WebKit variant) works for me ::
from qgis.PyQt.QtCore import QUrl; from qgis.PyQt.QtWebKitWidgets import QWebView; myWV = QWebView(None); myWV.load(QUrl('https://wikipedia.org/wiki/[%name%]')); myWV.show()

	Larry64.  **YES. This works for me too!**

Thanks for working and reporting these changes. I have noticed that these script changes also have been made on the Documentation website at Module 6.4.4. for everybody. VERY GOOD.
Thanks again for giving me access to the updated QGIS-Training-Data-release_3.10.zip. I have opened the new ZIP file and all of the new data that you mentioned above is there.
