### ISSUE TITLE
Method QgsAttributeForm.disconnectButtonBox() does not work

### ISSUE THREAD

**Issue by edpop** [qgis/QGIS-Documentation#575]
Hello

I want to make a custom forms with python init module. A have a simple ui form without its own QbuttonBox (if it has, no matter).

    def formOpen(dialog,layer,feature):
        dialog.disconnectButtonBox()

        #or
        #buttonBox = dialog.findChild(QDialogButtonBox, "buttonBox")
        #buttonBox.accepted.disconnect(dialog.accept)
        #buttonBox.rejected.disconnect(dialog.resetValues)

After that, there is still dialog close. In the API http://qgis.org/api/2.8/qgsattributeform_8cpp_source.html there is no other connections with buttons.
I can't close this ButtonBox and create my own in the code, cause it breaks the logic of the other.

**Comment by edpop** [comment]
Found workaround:

    def formOpen(dialog,layer,feature):
        buttonBox = dialog.findChild(QDialogButtonBox, "buttonBox")
        buttonBox.blockSignals(True)

        bnOk = buttonBox.button(QDialogButtonBox.Ok)
        bnOk.clicked.connect(myMethod0)
        bnCancel = buttonBox.button(QDialogButtonBox.Cancel)
        bnOk.clicked.connect(myMethod1)

**Comment by SrNetoChan** [comment]
@edpop I don't think this is the right place for this kind of questions. First because this is an issue tracker, to report and track Bugs. Second, because this one is for QGIS Documentation only.

If you want to report an issue in QGIS Desktop or QGIS API, please use https://hub.qgis.org/issues instead.

**Comment by edpop** [comment]
Thank you, next time I'll do.
