### ISSUE TITLE
aggregates functions are badly described

### ISSUE THREAD

**Issue by tschmetzer** [qgis/QGIS-Documentation#5751]
## Description

The syntaxes of the aggregates functions are poorly described at:
https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/expression.html#aggregates-functions

I would expect something like this:

_aggregate(
  layer:='layer name or id',
  aggregate:='aggegate type',
  expression:='expression to aggregate',
  filter:='optional filter expression,
  concatenator:='optional string to use to join values',
  order_by:='optional expression to order the features'
  )_

(copied from:
https://courses.spatialthoughts.com/advanced-qgis.html#summary-aggregate-expressions )

**Comment by havatv** [comment]
Should be fixed with #5811.
