### ISSUE TITLE
Regular expressions: Required escape sequence is not mentioned

### ISSUE THREAD

**Issue by tschmetzer** [qgis/QGIS-Documentation#5760]
When using the RegEx operator ~ as well as regexp_* functions with user defined patterns the regex expression need to be escaped so that the statement will contain double backslashes. This is not reflected in the current documentation.

### Current text:
a ~ b: a matches the regular expression b
https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/expression.html#operators

### Suggested text is something like:
a ~ b: a matches the regular expression b. Special characters like the backslash character ('\') need to be escaped.

Example:
'123' ~ '\\d+' → 1

##
Please note that this text should also appear in the application software (see screenshots)

![regex1](https://user-images.githubusercontent.com/67278094/85698893-5b0ea180-b6db-11ea-8ff3-ec0e1f936ba0.png)
![regex2](https://user-images.githubusercontent.com/67278094/85698894-5ba73800-b6db-11ea-8747-8e9e13662b63.png)

**Comment by SrNetoChan** [comment]
Hi @tschmetzer,

In the first example, you mean double backslashes, right? I would add the example and add the explanation that is available on the regex argument in regexp_match, which already informs the user of that need.

Regarding other strange characters like ", isn't that the norm in regex anyway?

We can fix this, or, if you like, I can help you fix it yourself, what do you say? :-)

**Comment by tschmetzer** [comment]
Hello Alexandre, Thank you for confirming to include double backslashes along with examples. I personally am fine with my qgis expression. I just wanted to make aware there could be other cases where people might stumble over that are different to usual regex and that might be worth mentioning, too. Viele Grüße, Tobias Am 25.06.20, 12:34 schrieb Alexandre Neto <notifications@github.com>:

   
  Hi @tschmetzer, 
  In the first example, you mean double backslashes, right? I would add the example and add the explanation that is available on the regex argument in regexp_match, which already informs the user of that need. 
  Regarding other strange characters like ", isn't that the norm in regex anyway? 
  We can fix this, or, if you like, I can help you fix it yourself, what do you say? :-)
