### ISSUE TITLE
I don't find the datas for exercice_data/more_analysis ??

### ISSUE THREAD

**Issue by Bastien250** [qgis/QGIS-Documentation#5788]
Hello, 

I am working on the training manual but I don't find the datas for exercice_data/more_analysis  (page number 9.4.1) ?? 

I downloaded the folder exercice_data but inside there is not "more_analysis"

Is it posible to update the folder please ? 

Thanks

**Comment by havatv** [comment]
Thanks for reporting, @Bastien250.  This is a known issue.
The data would become available if the following PR was merged:

https://github.com/qgis/QGIS-Training-Data/pull/27

**Comment by Bastien250** [comment]
Hello, 

Thanks for your answer and your help

**Comment by havatv** [comment]
The data are now added to the master branch on https://github.com/qgis/QGIS-Training-Data.
