### ISSUE TITLE
[Feature] Add contextMenuAboutToShow to QgsMapCanvas 

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5842]
Original commit: https://github.com/qgis/QGIS/commit/fd6dcf3bf6c22acb48b57bae30123314d9a33176 by web-flow

Adds a contextMenuAboutToShow( QMenu *menu, QgsMapMouseEvent *event ) signal to QgsMapCanvas to allow plugins
a chance to add entries to the canvas context menu

Fixes #37559

**Comment by DelazJ** [comment]
This one should go somewhere in https://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/canvas.html but I have no idea how to introduce.
@jakimowb would you have a light code snippet to share?

**Comment by DelazJ** [comment]
Wonderful @jakimowb
