### ISSUE TITLE
Add checkbox to always show diagrams for a layer

### ISSUE THREAD

**Issue by yjacolin** [qgis/QGIS-Documentation#586]
https://github.com/qgis/QGIS/commit/d7eec444a2f193ecd9ae7fb0eba0c8a445c59809
Author: Nyall Dawson
Date:   Thu Apr 9 17:50:53 2015 +1000
    
    Unlike the global labeling setting this applies only to diagrams,
    and only for a single layer. Defaults to on. (fix #8706)

**Comment by yjacolin** [comment]
@nyalldawson do you mean the checkbox in the screenshot below ?
![screenshot2](https://cloud.githubusercontent.com/assets/660191/11154268/a4a5decc-8a3e-11e5-976d-ce5c7b367581.png)

**Comment by nyalldawson** [comment]
@yjacolin yes, that's it

**Comment by yjacolin** [comment]
Done with https://github.com/qgis/QGIS-Documentation/commit/934d725dbed508cbbbcd640f3a4fdeccdc450904
