### ISSUE TITLE
[feature][layouts] Allow setting per cell text format in manual text tables

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5866]
Original commit: https://github.com/qgis/QGIS/commit/18a36e46227b238d831d3b64f8b4f7f9151c6748 by nyalldawson

Individual cells (or selections of multiple cells) can have an preset
text format set, which overrides the default text format for those cells.

Sponsored by City of Canning

**Comment by lajunek** [comment]
@nyalldawson I found the "Configure format ..." option in the layout legend item properties. Is this the above described feature?
![grafik](https://user-images.githubusercontent.com/47246213/100539286-5a031280-322d-11eb-8934-cb3dd0bbb38b.png)
