### ISSUE TITLE
Trace tool not working

### ISSUE THREAD

**Issue by DrewFrance** [qgis/QGIS-Documentation#5891]
New version of QGIS 3.14.1 I believe, one project with multiple polygons all in same CRS. Trace tool NOT  tracing when on "all layers" mode. Checked issue in other projects - not an issue except for one project. Didn't have issue until downloaded and used new version Qgis. Will trace when on "active layer" mode. Very confused about why it refuses to trace, it seems to pause a bit when I click on second vertex or line. Refuses to trace on one project when on "all layers" mode. Thank you.

**Comment by ghtmtt** [comment]
This is the documentation repository, could you please open an issue on the bug tracker of the code respository? https://github.com/qgis/QGIS/issues

Thanks!
