### ISSUE TITLE
[feature][layouts] Expose option to clip maps to a shape or polygon item
in UI

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5937]
Original commit: https://github.com/qgis/QGIS/commit/ed2cca49c0195ec2de1c12d63218a9296c42a739 by nyalldawson

Allows users to clip a map item to a shape or polygon item from their layout,
allowing for non-rectangular maps in the layout

**Comment by lajunek** [comment]
@nyalldawson I suppose this feature was inserted into the print composer? Can you give a short step by step introduction how one can clip a map with an item? So far, I didn't find the functionalities. Thanks
