### ISSUE TITLE
Building QGIS from Source link can't access?

### ISSUE THREAD

**Issue by ohyeee** [qgis/QGIS-Documentation#5947]
https://htmlpreview.github.io/?https://raw.github.com/qgis/QGIS/master/doc/INSTALL.html can't access

**Comment by Gustry** [comment]
Where did you find this link?

It's a markdown file, not HTML:
https://github.com/qgis/QGIS/blob/master/INSTALL.md
so you don't need to use the https://htmlpreview.github.io/ website.

**Comment by havatv** [comment]
Thanks for reporting, @ohyeee. I found link (two places in the docs), and have updated the link in #5948.
