### ISSUE TITLE
Allow changing vector layer data source

### ISSUE THREAD

**Issue by yjacolin** [qgis/QGIS-Documentation#595]
https://github.com/qgis/QGIS/commit/e249bfee94220a822e5b602ff972cf57d2e26080
Author: Nathan Woodrow
Date:   Sun May 17 19:54:20 2015 +1000

**Comment by DelazJ** [comment]
@NathanW2 I'm unable to find where/in which circumstances this option is available. any help?

**Comment by andreasneumann** [comment]
I believe this only works from Python code - there is no UI to change the data source yet.

**Comment by m-kuhn** [comment]
Yes, it's an API only change.

**Comment by DelazJ** [comment]
Thanks! So it'd rather belongs to PyQGIS Cookbook, right?

**Comment by ThomasG77** [comment]
This change has been added since the beginning of the discussion in the PyQGIS Cookbook with [this commit ](https://github.com/qgis/QGIS-Documentation/commit/926629abcb8639e9afe2eeb854fc637689e5dd29#diff-27abc3b0021a6963ffc08c5e7123ce9cR158)

We can close I think.
