### ISSUE TITLE
add expressions at the symbollist level

### ISSUE THREAD

**Issue by yjacolin** [qgis/QGIS-Documentation#598]
https://github.com/qgis/QGIS/commit/1e46196937827d2a79f978b0ed67e97be9531c81
Author: vmora
Date:   Fri May 8 16:37:15 2015 +1000
    
    Size and Rotation can be defined by an expression for all symbols
    composing a marker. Width can be defined by an expression for all
    symbols composing a line.
    
    For markers, a legend is generated for varying sizes. This allows
    multivariate analysis legend in the case of classified/graduated colors.
    
    The offset is now set along with size to maintain the relative position
    of symbols composing a marker.
    
    An asistant, with preview, is accessible through the data defined button
    to help the user define the size expression. Three methods are
    available: Frannery, Area and Radius.
    
    Added a widget for use in categorized/classified symbology gui to set
    the expression if needed. The assistant is also available from it.

**Comment by DelazJ** [comment]
@vmora: 
>Added a widget for use in categorized/classified symbology gui to set
the expression if needed. The assistant is also available from it

What do you mean? where's the gui?

**Comment by vmora** [comment]
@DelazJ  The gui (assitant) is availble in the expression menu.

**Comment by DelazJ** [comment]
@vmora thank you. I thought there was another gui, especially for those types of renderer. Would you mind checking [this input](https://github.com/qgis/QGIS-Documentation/blob/master/source/docs/user_manual/working_with_vector/vector_properties.rst#proportional-symbol-and-multivariate-analysis) and let us know if it covers all the points of your implementation and reflects the use you were expecting, please? Thanks.

**Comment by vmora** [comment]
@DelazJ yes it does, except that I don't see the pictures/icons in the document.

Thanks a lot.

**Comment by DelazJ** [comment]
@vmora Yes, currently, our repo doesn't show images. It's in the roadmap :), maybe at the next hackfest.

**Comment by SrNetoChan** [comment]
@DelazJ @vmora I think all users manual screenshots are updated regarding this matter. See #865 . Is there something else we need to do before we close this issue?

**Comment by DelazJ** [comment]
@SrNetoChan I wanted to close it last day and reading the initial report I wonder if all is done and especially what does mean (and if it's worth any mention)
> The offset is now set along with size to maintain the relative position
of symbols composing a marker.

**Comment by SrNetoChan** [comment]
@DelazJ Maybe @vmora can help with that, but it sounds to me that this is not something that needs to be mentioned to the user, but rather something that fixed some previous bad behavior.

**Comment by DelazJ** [comment]
This is what I also understood but in the doubt...
