### ISSUE TITLE
QgsLogger: Barely understandable expression and examples missing

### ISSUE THREAD

**Issue by tschmetzer** [qgis/QGIS-Documentation#5995]
## Barely understandable expression
https://qgis.org/pyqgis/3.10/core/QgsLogger.html#qgis.core.QgsLogger

 debugLevel() → int

Reads the environment variable QGIS_DEBUG and converts it to int. **If** QGIS_DEBUG is **not set**, the function returns 1 if QGISDEBUG is defined and 0 **if not***

Suggestion:
Reads the environment variable QGIS_DEBUG and converts it to int. The function returns 1 if QGISDEBUG is defined and 0 if QGIS_DEBUG is not set.

## Examples for QgsLogger are missing
There are examples for QgsMessageLog but no examples for how to use the QgsLogger in 
https://docs.qgis.org/3.10/en/docs/pyqgis_developer_cookbook/communicating.html#logging

As I was unable to get the function to work I opened a but at https://github.com/qgis/QGIS/issues/38188

**Comment by DelazJ** [comment]
> Barely understandable expression
https://qgis.org/pyqgis/3.10/core/QgsLogger.html#qgis.core.QgsLogger

Pyqgis documentation has its own repository where related issues should be reported: https://github.com/qgis/pyqgis. But in your case, you better report (or better open a pull request) at https://github.com/qgis/QGIS where the source texts are. The pyqgis repo "only" has machinery to generate the website.
> Examples for QgsLogger are missing

There are unfortunately still a lot to write about in the docs. We'll be happy, once you figure out how it works, to integrate any examples for this. Thanks in advance.

**Comment by tschmetzer** [comment]
According to @m-kuhn in https://github.com/qgis/QGIS/issues/38188 QGIS needs to be built in debug mode in order to work.

How can this information be integrated into the docs?

**Comment by m-kuhn** [comment]
Hello,
I think this documentation should be in the API documentation, i.e. in here https://github.com/qgis/QGIS/blob/master/src/core/qgslogger.h

This is more the application documentation here.
