### ISSUE TITLE
Allow pasting of features in attribute table

### ISSUE THREAD

**Issue by yjacolin** [qgis/QGIS-Documentation#600]
https://github.com/qgis/QGIS/commit/499c102b57aa562f5d4c86a9960c05a43b1cce76
Merge: eaeea21 9b34202
Author: Nathan Woodrow
Date:   Wed May 20 20:46:10 2015 +1000

    Merge pull request #2047 from alexbruy/attrtable-paste

**Comment by yjacolin** [comment]
From @alexbruy  commit comment ```
Currently we have only "Copy" button in attribute table dialog. Sometimes, when working with attributes having ability to paste features into table is very handy. Of course one can paste features into layer by switching to main QGIS window but this is a bit inconvenient. This pull-request adds "Paste" button and shortcut to the attribute table dialog.
```
https://github.com/qgis/QGIS/pull/2047

**Comment by yjacolin** [comment]
@SrNetoChan there is two screenshot here: 
* attribut table to update (/static/user_manual/working_with_vector/vectorAttributeTable.png)
* add Past icon (|mActionPasteSelected|)

**Comment by SrNetoChan** [comment]
I have reopened this so I don't forget. I will close it as soon as the screenshots are created.

**Comment by SrNetoChan** [comment]
@yjacolin can you confirm me if the |mActionPasteSelected| icon was already taken care of? It seems all ok to me. Can I merge #906 and close this?
