### ISSUE TITLE
Data defined properties for font marker

### ISSUE THREAD

**Issue by yjacolin** [qgis/QGIS-Documentation#602]
https://github.com/qgis/QGIS/commit/1e3b820da4a7fcf189e2f3be4b3df7893af80296
Author: Nyall Dawson
Date:   Fri May 22 01:03:52 2015 +1000

**Comment by SrNetoChan** [comment]
@yjacolin Do you think we need to keep this one? In Users Manual, none of the markers have screenshots or even mention the data-defined properties. Or do you think we should add it? Maybe for html only?

**Comment by yjacolin** [comment]
I think it is important to explain somewhere that one can link a parameter to a data defined properties with some screenshot. Probably not specific to font marker or even marker. Something more generic. Does something like this already exist? if so, we can close the ticket, if not I will probabaly take care of it (for the text part).

**Comment by yjacolin** [comment]
Anyway, if anybody want to take care of this ticket, there is no problem :)

**Comment by SrNetoChan** [comment]
You are right. There no serious mention of how to use data-defined properties/override in the documentation. I believe this is something that should be added to the the vector properties and/or print composer sections.

**Comment by DelazJ** [comment]
@SrNetoChan about data defined override, there's http://docs.qgis.org/testing/en/docs/user_manual/print_composer/atlas_generation.html#data-defined-override-buttons (I think you wrote it :))
And I reserved a dedicated place of this feature at https://github.com/qgis/QGIS-Documentation/edit/master/source/docs/user_manual/working_with_vector/vector_properties.rst#L365. Maybe a **generic comment** on data-defined functionalities can be put there...

**Comment by SrNetoChan** [comment]
@DelazJ I no longer remember what I did in the past... must be the age. 

**Special tools** seem a nice place to put some information about data-defined properties usage. (Although I must say I'm not a huge fan of this section right at the beginning of the vector properties page.I think that for users it would be preferable to read about the more concrete and direct things first, and only then have some more info about special features.)

**Comment by DelazJ** [comment]
Feel free to move it to the place you think may better suit.
I'm neither fan of the word `special`, so if you have an idea...

**Comment by SrNetoChan** [comment]
I opened a new ticket for that: #921, so we can discuss it, and I will propose the change.

**Comment by yjacolin** [comment]
I agree with you.

**Comment by yjacolin** [comment]
removing Screenshot label as there is only need for icon, not more.
