### ISSUE TITLE
"[email protected]" instead of expression

### ISSUE THREAD

**Issue by StyXman** [qgis/QGIS-Documentation#6021]
## Description

The pages must be rendered with some product, or maybe it's the web server, but expressions in the "raster calculator"'s help (that I guess include the `@` symbol) are replaced by the string `"[email protected]"` and link to https://docs.qgis.org/cdn-cgi/l/email-protection . I had to read the doc's source code to figure out it was `"elevation@1"`.

Page URL: https://docs.qgis.org/3.10/en/docs/user_manual/working_with_raster/raster_analysis.html#examples and others

**Comment by DelazJ** [comment]
Probably, some local issue; Here's what I get here, using firefox, safari or Edge
![image](https://user-images.githubusercontent.com/7983394/90416676-12f47580-e0b3-11ea-8510-4ae8053db2e3.png)

**Comment by StyXman** [comment]
> The website from which you got to this page is protected by Cloudflare. Email addresses on that page have been hidden in order to keep them from being accessed by malicious bots. You must enable Javascript in your browser in order to decode the e-mail address.

That's it, it does that when I have JS disabled. Case solved. Sorry for the noise.
