### ISSUE TITLE
Duplicate documentation about QGis server installation

### ISSUE THREAD

**Issue by benoitdm-oslandia** [qgis/QGIS-Documentation#6031]
I am a bit confused about the QGis server installation parts found in the documentation: between the [user guide / ... / getting started](https://docs.qgis.org/testing/en/docs/server_manual/getting_started.html#installation-on-debian-based-systems) (on which I worked) and the [training/ ... / lesson 11](https://docs.qgis.org/testing/en/docs/training_manual/qgis_server/install.html). Both of them suggest installation/configuration methods which differ. 

The **getting started** documentation is, IMHO, too detailed for this kind of document and the **lesson 11** should focus on server wms configuration and tuning instead of a dedicated chapter on installation details. 

It may be a good solution to merge the both to provide a new document, properly referenced, in the server manual.

**Comment by DelazJ** [comment]
@benoitdm-oslandia any update on this?

**Comment by benoitdm-oslandia** [comment]
I'll check in the next days how we (Oslandia) will plan these changes.

Regards

**Comment by DelazJ** [comment]
@benoitdm-oslandia are there anything left to fix here, or could this be closed?

**Comment by benoitdm-oslandia** [comment]
No, it seems ok, I close. Thanks!
