### ISSUE TITLE
Lesson 6.1 0 Van der Grinten I CRS

### ISSUE THREAD

**Issue by jami3rez** [qgis/QGIS-Documentation#6043]
When trying to create the Custom CRS definition an error message is given when the given string is copied into the the Parameters box.

`+proj=vandg +lon_0=0 +x_0=0 +y_0=0 +R_A +a=6371000 +b=6371000 +units=m +no_defs`

I click Validate and the message given is - 

`This WKT projection definition is not valid: missing [`

I click Ok and the message given is -

`The definition if 'Van der Grinten I' is not valid`

I tried changing format to proj string and this doesn't work either.

Page URL: https://docs.qgis.org/3.10/en/docs/training_manual/vector_analysis/reproject_transform.html

**Comment by agiudiceandrea** [comment]
Hi @jami3rez, it seems there are two issue:
- the outdated training manual in which it is not stated that you need to select the Proj String format and there is an old screenshot of the Custom Coordinate Reference System Definition dialog window
- a bug in the Custom Coordinate Reference System Definition dialog window preventing a new definition from being inserted correctly

You can workaround the bug:

in the Custom Coordinate Reference System Definition dialog window you will see an empty item in the items list; select the empty item and then insert the name, the format ("Proj String") and the parameters; click OK and the custom definition will be correctly inserted in the list.
