### ISSUE TITLE
Add options under categorised renderer advanced menu

### ISSUE THREAD

**Issue by yjacolin** [qgis/QGIS-Documentation#605]
https://github.com/qgis/QGIS/commit/9031e9849f536bd5da7a83a1a47d8d8e9202582b
Author: Nyall Dawson
Date:   Sat May 23 00:34:34 2015 +1000

    Add options under categorised renderer advanced menu to
    set categories to symbols with a matching name from the style
    library or an XML style file.
    
    Thanks Lene for the great hackfest!

**Comment by yjacolin** [comment]
@nyalldawson any informations on how to do a symbol that can match the categories? I get this error message `No categories could be matched to symbols in library.` Thanks!

**Comment by nyalldawson** [comment]
@yjacolin Your symbol names must match the category name - so make sure you have symbols in your library with the the same name as a category in your renderer.
