### ISSUE TITLE
Wrong zip file location 

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#6059]
[Testing zip html download page ](https://docs.qgis.org/testing/zip/) shows outdated docs for 3.10 along with the testing one.
[3.10 zip html download page ](https://docs.qgis.org/3.10/zip/) shows more recent 3.10 docs along with an outdated testing doc.

It could be nice we removed the wrong docs from these URLs.
Assigning to you @rduivenvoorde . Thanks.

**Comment by rduivenvoorde** [comment]
Done, 

I do not know how this happens as the makefiles for both version in 'make all' do a springclean, so should not mix....

Let's keep an eye on this, so will not close this

**Comment by DelazJ** [comment]
OK. Thanks.

**Comment by DelazJ** [comment]
@rduivenvoorde this seems to work nicely, doesn't it? Close...?

**Comment by rduivenvoorde** [comment]
Yes, I think this was a 'byproduct' of the way I was building it. Thanks for cleaning up!
