### ISSUE TITLE
New statistical summary dock widget

### ISSUE THREAD

**Issue by yjacolin** [qgis/QGIS-Documentation#606]
https://github.com/qgis/QGIS/commit/e7b7549c29712f89c9ba56884ca748149c4c0778
Author: Nyall Dawson
Date:   Mon May 18 05:55:14 2015 +1000
    
    Can display summary statistics (eg mean, standard deviation, ...)
    for a field or expression from a vector layer.

**Comment by DelazJ** [comment]
@yjacolin How do you plan to fix this issue? Adding a text under http://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html#panels-and-toolbars section or elsewhere?
Afaik, There are many other panels that are not mentioned in Doc (Redo/Undo, Tile Scale, User Input). Wonder if the Overview and Log Messages panels aren't also in this situation.
What about a dedicated page of the Panels and Toolbars? All the panels will be described there unless they have a more suitable place (digitizing, Identify, GPS, Browser, Layer legend...) in which case we just introduce them and link to that page.

**Comment by DelazJ** [comment]
That said, I'm wonder if there'll be enough to fill a whole page

**Comment by yjacolin** [comment]
I didn't start on this yet. But I think there is several location where it can be useful to add some information. I need to think more about this but I have some problem to find free time in my planing these last monthes :)

**Comment by yjacolin** [comment]
> Adding a text under http://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html#panels-and-toolbars section or elsewhere?

done!

>There are many other panels that are not mentioned in Doc (Redo/Undo, Tile Scale, User Input). 
> Wonder if the Overview and Log Messages panels aren't also in this situation.

Both are already there. I just prepared the next step to include other panels.

> What about a dedicated page of the Panels and Toolbars? 

We can wait a little bit when we will have a lot of information about panel and toolbar we can split into another page.

> All the panels will be described there unless they have a more suitable place (digitizing, Identify, GPS, Browser, Layer legend...) in which case we just introduce them and link to that page.

We should describe panels and toolbar there and add link in another part when needed.

**Comment by yjacolin** [comment]
See #935 for other panels and toolbar.

**Comment by yjacolin** [comment]
Do we need a screenshot for this panel?
