### ISSUE TITLE
New geometry classes

### ISSUE THREAD

**Issue by yjacolin** [qgis/QGIS-Documentation#608]
https://github.com/qgis/QGIS/commit/68fe5f579157e81faa79fcea9aa251ae73638c2d
Author: Marco Hugentobler
Date:   Fri May 15 15:41:56 2015 +0200

**Comment by yjacolin** [comment]
need more information about this feature. Did you have a blog, presentation on which we can get more information.

**Comment by yjacolin** [comment]
https://github.com/qgis/QGIS/commit/b7a2a79de229e4cf2593c74fe2d0b3ba51791cd2
Merge: bb80c63 68fe5f5
Author: mhugent <marco.hugentobler@sourcepole.ch>
Date:   Mon May 25 10:03:42 2015 +0200

    Merge pull request #2055 from mhugent/geometry_mmsql_2_8
    
    [FEATURE]: New geometry classes (take 2)

**Comment by mhugent** [comment]
https://www.meci.co.kr/societyevent/FOSS4G2015/download/presentation/GBR%20B/6.%20S5-1/PT5-03_New%20QGIS%20functions%20for%20power%20users.pdf

**Comment by yjacolin** [comment]
Impacts mostly "editing" chapter: tools and geometries support (eg Support for SQL/MM curved geometries:
  * CircularString
  * CompoundCurve
  * CurvePolygon
  * MultiCurve
  * MultiSurface
* Z and M values)
