### ISSUE TITLE
WMS filter parameter

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#6082]
At https://docs.qgis.org/3.10/en/docs/user_manual/working_with_ogc/server/services.html#filter  or https://docs.qgis.org/testing/en/docs/server_manual/services.html#filter you can read

![Capture d’écran 2020-09-08 à 10 09 42](https://user-images.githubusercontent.com/7983394/92450269-80c82480-f1bb-11ea-9ec2-72f45f4279fb.png)

Questions:
1. Is the text in the first code block, the **error** message returned by QGIS? Or did we "skip" the actual message in the docs? Rather looks like some explanation.
1. Should the line `characters are 'AND','OR','IN','=','<','>=','>','>=','!=*,'(',')'` instead be `characters are 'AND','OR','IN','=','<','>=','>','>=','!=','(',')'`, replacing the * character with a simple quote?
1. What is the filter on layer1? whether the col1 value is not null?
1. the mandatory space is within the expression string, right? Not within the whole filter parameter string?

@pblottiere git blame says you might know ;).
Thanks for any input.

**Comment by pblottiere** [comment]
Hi @DelazJ,

> Is the text in the first code block, the error message returned by QGIS? Or did we "skip" the actual message in the docs? Rather looks like some explanation.

> Should the line characters are 'AND','OR','IN','=','<','>=','>','>=','!=*,'(',')' instead be characters are 'AND','OR','IN','=','<','>=','>','>=','!=','(',')', replacing the * character with a simple quote?

The error message evolved since I wrote this part of the documentation. The exact error message returned by QGIS Server (and displayed in the browser) is now:

```
<ServiceExceptionReport><ServiceException code="Security">The filter string XXXXXXXXX has been rejected because of security reasons. Note: Text strings have to be enclosed in single or double quotes. A space between each word / special character is mandatory. Allowed Keywords and special characters are  IS,NOT,NULL,AND,OR,IN,=,&lt;,>=,>,>=,!=,',',(,),DMETAPHONE,SOUNDEX. Not allowed are semicolons in the filter expression.</ServiceException></ServiceExceptionReport>
```

I'm taking a look for the remaining questions :).

**Comment by DelazJ** [comment]
Thanks @pblottiere #6087 takes care of the message update

**Comment by DelazJ** [comment]
The remaining question is what does mean `FILTER=mylayer1:"col1"` in
```
URL example:

http://localhost/qgisserver?
SERVICE=WMS
&REQUEST=GetMap
&LAYERS=mylayer1,mylayer2,mylayer3
&FILTER=mylayer1:"col1";mylayer1,mylayer2:"col2" = 'blabla'
&...
```
`In this example, the same filter (field col2 equals the string blabla) is applied to layers mylayer1 and mylayer2, while the filter on col1 is only applied to mylayer1.`

**Comment by DelazJ** [comment]
@pblottiere I think your ongoing work could consider this issue

**Comment by pblottiere** [comment]
Yes, I'll take a look :+1:
