### ISSUE TITLE
[FEATURE][vectortiles] Allow users to optionally specify the URL
for a default style to be applied to connections when they are
first loaded into QGIS

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#6084]
Original commit: https://github.com/qgis/QGIS/commit/dcf8728494622e3af59ebf4e0f1abfd6a392ffd0 by nyalldawson

When setting up a vector tile source connection, there's a new option
to enter a URL to a MapBox GL JSON style configuration. If one has
been entered, then that style will be applied whenever the layers
from the connection are added to QGIS.

Works also with Arcgis vectortileservice connections -- in this
case the URL overrides the default style configuration specified
in the server configuration.

**Comment by roya0045** [comment]
@DelazJ A Vector-Tile label would be good. ;)
