### ISSUE TITLE
[feature][vectortiles] Add checkbox for showing only visible rules
in the vector tiles labeling and renderer widgets

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#6085]
Original commit: https://github.com/qgis/QGIS/commit/92c3a88da4254b6bbf59a7bd0f2b869d7cb1ecf0 by nyalldawson

Makes it much easier to locate troublesome rules or work with
complex vector tile styling

**Comment by lajunek** [comment]
@nyalldawson Hi there. Do we find the checkbox in the vector Layer Properties?

**Comment by lajunek** [comment]
@nyalldawson is there a url where one can connect for free with a vector tile? Maybe this is possible on the openstreetmap page?

**Comment by lajunek** [comment]
@saberraz Hello Saber, my idea is to set up an OpenMapTiles server and describe the usage of the "Vector Tiles" connection. Another possibility is to use an existing Map Tiles server. Can you provide the address of such a server? Does Lutra provide one?

**Comment by nyalldawson** [comment]
> is there a url where one can connect for free with a vector tile? Maybe this is possible on the openstreetmap page?

I'm not personally aware of any. The ordinance survey openstack tiles are public, but I believe they may have some terms of use which would prevent advertising them as free for use. (They are also very slow and accordingly not a good showcase)

**Comment by nyalldawson** [comment]
> Hi there. Do we find the checkbox in the vector Layer Properties?

It's at the bottom of the layer styling panel

**Comment by saberraz** [comment]
hi @lajunek 

There are some Map Tile providers based on OpenStreetMap but you will need either an API key or their terms of service do not allow you to use the map tiles outside their application.

**Comment by DelazJ** [comment]
So without subscribing to something, there's no dataset/url the doc team can have access to in order to document features of this provider? Or did I misunderstand?

**Comment by lajunek** [comment]
@DelazJ yes, it seems to be.

**Comment by lajunek** [comment]
@DelazJ MapTiler connections via an URL are not for free.

**Comment by lajunek** [comment]
@DelazJ @havatv does somebody know where one can find this checkbox (and the name)?

**Comment by nyalldawson** [comment]
It's here:

![image](https://user-images.githubusercontent.com/1829991/95692842-1ef05400-0c6c-11eb-9a67-f811b8327255.png)

Down the bottom, just above the "Apply" button.

**Comment by nyalldawson** [comment]
(if you're looking for a sample server, try using the ArcGIS VectorTilesServer https://basemaps.arcgis.com/arcgis/rest/services/OpenStreetMap_v2/VectorTileServer . It's not freely usable, but it IS publicly accessible so is good for testing and screenshots)
