### ISSUE TITLE
Search widgets

### ISSUE THREAD

**Issue by yjacolin** [qgis/QGIS-Documentation#609]
https://github.com/qgis/QGIS/commit/95a740837faa4925982e68a6086840a768b5abe4
Merge: b5801af e015a7e
Author: Matthias Kuhn
Date:   Tue May 26 11:43:32 2015 +0200

    Merge pull request #2059 from carolinux/search-widgets
    
    Makes it easier to filter the attribute table if there are attribute domains attached

**Comment by yjacolin** [comment]
@carolinux: does your PR is only focuse on this part in the attributes table:
![osgeo_cod_manager1](https://cloud.githubusercontent.com/assets/660191/13380912/3fcc4cca-de4e-11e5-8089-ff907ece62f9.png)

Thanks.

**Comment by carolinux** [comment]
@yjacolin yes

**Comment by yjacolin** [comment]
ok thanks, there is no information about "attribute table" panel in the doc. Needs to take care a little bit of this :) will work on this, this sunday.

**Comment by yjacolin** [comment]
@SrNetoChan I need icon for |mActionForm| shorcut, see (in attribute table):

![osgeo_cod_manager1](https://cloud.githubusercontent.com/assets/660191/13724042/c6ae9d86-e878-11e5-9a22-663d04beb10d.png)

**Comment by SrNetoChan** [comment]
@yjacolin it's the left one, right?

**Comment by yjacolin** [comment]
yes!

**Comment by yjacolin** [comment]
just a question/information: there is two location where this action could be triggered: in the attribute table and in the "request" panel but the two icons are different, see:
![legende_gebaude1](https://cloud.githubusercontent.com/assets/660191/13744306/2baead7e-e9e7-11e5-88b3-3b5d460fa1b0.jpg)

**Comment by SrNetoChan** [comment]
I believe this is a bug. In source code the Icon I used was called mActionPropertyItem.png, but there was also a mActionPropertyItem.svg looking like the one in the identifier results panel. I think someone forgot to change the one in the attribute table. There is already a |mActionPropertyItem| with the new icon. @yjacolin, what do you think? Do we close my #890 Pull Request and open a bug report to change the Icon in the attribute table? and you would use the |mActionPropertyItem| for now?

**Comment by DelazJ** [comment]
They do not really do the same thing: one opens the form of a single feature while the other switches the whole attribute table into a form view

**Comment by yjacolin** [comment]
@SrNetoChan we should keep the doc consistent with the QGIS gui. So let's keep your PR.

@DelazJ in some way, user will click on this icon to show a form for a feature so for me it is the same action even if context change. Use can access to the form to change the attribut of the feature.

**Comment by SrNetoChan** [comment]
The icon used to be the same, so I would say it was. Should I open a ticket for replacing the icon anyway?

**Comment by yjacolin** [comment]
yes I think so!
