### ISSUE TITLE
Improve Server Services index

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#6090]
[Server Services](https://docs.qgis.org/testing/en/docs/server_manual/services.html) shows this index
![image](https://user-images.githubusercontent.com/7983394/92589759-551c6b80-f29b-11ea-8a8a-ae79a8acceec.png)

At the bottom:
1. The "Extra parameters supported by all request types" section list only:

   1. **MAP**, already described in each of the preceding services, although with unequal details; also note that WFS3 does not particularly recommend to expose it.
   1.  and **FILE_NAME**, also described in WMS and not supported by wfs3. Might be worth moving this one also to the other previous sections
1. Should REDLINING be part of the WMS section or is it something every service supports?
1. Move the "External WMS layers" section to WMS, same level as the requests or as part of the [LAYERS](https://docs.qgis.org/testing/en/docs/server_manual/services.html#layers) parameter ?

**Comment by DelazJ** [comment]
@pblottiere Based on discussion at https://github.com/qgis/QGIS-Documentation/pull/7154#discussion_r763845952 can I assign this to you

**Comment by pblottiere** [comment]
Yes :)

**Comment by DelazJ** [comment]
Fixed as can be seen at https://docs.qgis.org/3.22/en/docs/server_manual/services.html
