### ISSUE TITLE
Raster Alignment Tool

### ISSUE THREAD

**Issue by yjacolin** [qgis/QGIS-Documentation#610]
https://github.com/qgis/QGIS/commit/1409f08576751f02ff84bb6ec95c13dd16e3a786
Author: Martin Dobias
Date:   Fri Jun 12 14:12:21 2015 +0800
    
    This new tool in qgis_analysis library is able to take several rasters
    as input and to align them perfectly, that means:
    - reproject to the same CRS
    - resample to the same cell size and offset in the grid
    - clip to a region of interest
    - rescale values when required

**Comment by yjacolin** [comment]
@SrNetoChan two screenshots needed here:
![image](https://cloud.githubusercontent.com/assets/660191/15632113/6bec6340-2588-11e6-9059-3aaca778fca9.png)
and
![image](https://cloud.githubusercontent.com/assets/660191/15632117/8f6ace74-2588-11e6-8f30-d8b0c2d68c86.png)

**Comment by yjacolin** [comment]
@wonder-sk as a test user I think that a way to import several layer in one action would be great as I tested with more than 20 layers and it is quiet long :)

**Comment by SrNetoChan** [comment]
@yjacolin I will add new screenshots soon. Please do a pull request with this ones, let's merge it. Otherwise none of us will be able to merge anything without breaking Travis. Then assign the issue to me. Thx

**Comment by yjacolin** [comment]
Ok, thanks, I will keep the issue open and assign it to you.

**Comment by DelazJ** [comment]
@yjacolin why not just use the screenshots you added? Any problem with them?

**Comment by yjacolin** [comment]
Well, you are right, just though that these are not followed the guidelines :)

**Comment by DelazJ** [comment]
@yjacolin If they qre quick and dirty, we don't want them :)
I thought they were following the guidelines reason why

**Comment by yjacolin** [comment]
Well I always wondered why a Qt application doesn't show screenshots with KDE :) guidelines says to use Gnome (for diversity I guess).

**Comment by SrNetoChan** [comment]
@DelazJ @yjacolin some time ago in the mailing list it was decided that it would be better to always use the same system. At that time I offered for updating all screenshots, I asked if it would be ok to use ubuntu. That is how the guideline were set to ubuntu. I would be ok to change it to anything else. but keeping the consistency.
There might be Operation systems more favorable to this type of work. for instance, no rounded corners (I always cut then in ubuntu), buttons in the right corner, smaller menus and texts, etc... something that most of our users (windows?) would recognize (but not windows...:-P).

In this case, and during the creation of testing documentation, I would say that you could add the quick and dirty screenshots (this way I know what images you were looking for) and keep the issue open for reviewing the screenshots only (you could even remove the text label).

**Comment by yjacolin** [comment]
@SrNetoChan no problem from me, sorry it was a kind of french joke :)

**Comment by SrNetoChan** [comment]
Lol
