### ISSUE TITLE
8.4.24. Doesn't make sense

### ISSUE THREAD

**Issue by jami3rez** [qgis/QGIS-Documentation#6116]
https://docs.qgis.org/3.10/en/docs/training_manual/complete_analysis/analysis_exercise.html

The instruction is very abrupt.

`Build a query to select the four suitable areas closest to the university (selecting them using the id field)`

For me this does not work, the four points remain on the University and I am unable to complete what was a very long exercise.

**Comment by DelazJ** [comment]
> For me this does not work, the four points remain on the University.

At the end of https://docs.qgis.org/3.10/en/docs/training_manual/complete_analysis/analysis_exercise.html#find-the-locations-that-are-closest-to-the-university-of-cape-town, I can read
> 3. Open the attribute table of the `suitable_areas` layer
> 4. Build a query to select the four suitable areas closest to the university (selecting them using the id field)

So I'm afraid I don't get the four points you are referring to: `suitable_areas` is not a point layer. Did you manage to get to the point 7 of that section? and can you share the attribute table of that resulting point layer and the query you use?
Thanks

**Comment by havatv** [comment]
I belive this  exercise makes perfect sense, and the instructions look good to me.

**Comment by jami3rez** [comment]
Apologies, I think I mis-read this one, it was late! Thanks for the feedback!

**Comment by DelazJ** [comment]
@jami3rez so you could finally finish the exercise?

**Comment by jami3rez** [comment]
Yes, you were right the suitable_areas layer is not a point layer. The four points were taken from another layer that gave me four IDs (id_2) to cross-reference with those from the suitable_areas layer.

![qgis](https://user-images.githubusercontent.com/48032389/94859641-c24f9680-042c-11eb-827f-a4f9e1c56d71.PNG)

**Comment by DelazJ** [comment]
Thank you for the feedback.
