### ISSUE TITLE
[trainingmanual] Used sample file not correct? Western_Cape_UTM33S.shp

### ISSUE THREAD

**Issue by DiGro** [qgis/QGIS-Documentation#6146]
## Description
Whilst translating the documentation for the Training manual I noticed that the file Western_Cape_UTM33S.shp from the folder admin_boundaries just contains one (1) district, namely Belville.

The file is contained in the sample set for the Training manual: QGIS-Training-Data-master.zip

If I read the documentation correctly there should be more districts to populate the list in Query builder.

Full path of the file:  QGIS-Training-Data-master\exercise_data\more_analysis\admin_boundaries\Western_Cape_UTM33S.shp

Could someone please check if what I see is correct ?

[admin_boundaries.zip](https://github.com/qgis/QGIS-Documentation/files/5299537/admin_boundaries.zip)

Page URL: https://docs.qgis.org/3.10/nl/docs/training_manual/complete_analysis/analysis_exercise.html#find-the-correct-districts

**Comment by tgdbepe4** [comment]
I have the same problem. There are many remarks about this lack but no solution or correction is avilable until now. I hope someone has the complete file?

**Comment by DiGro** [comment]
I found a similar set at the site of RCMRD which is, as stated on their site, in the Public Domain
[http://geoportal.rcmrd.org/layers/?limit=100&offset=0&category__identifier__in=boundaries&title__icontains=South%20Africa%20Admin%20Boundaries%20level%20III](url)

Using this set the exercise can be finished

[south_africa_adm2.zip](https://github.com/qgis/QGIS-Documentation/files/5512301/south_africa_adm2.zip)

**Comment by havatv** [comment]
I fThe dataset location:
more_analysis/admin_boundaries/Western_Cape_UTM33S.shp

**Comment by tgdbepe4** [comment]
#havatv, no the file there has only one entry!

Regards

Peter

**Comment by tgdbepe4** [comment]
#DiGro Thanks for the zip file. Now I can complete the tutorial. Hope they will update the exercise data set!

**Comment by DiGro** [comment]
@havatv  Havard, the location is indeed that one.
However the file contains, just as Peter stated, just one unit (Bellville).

It isn't updated to the full set

@tgdbepe4  My pleasure. Glad to be of help

**Comment by DelazJ** [comment]
Thanks @DiGro for having found the original data. I updated the dataset with a subset of your data (keeping districts of the western cape instead of whole South africa).
> Hope they will update the exercise data set!

@tgdbepe4 there's no "they". QGIS is for everyone and everyone is more than welcome to report and/or help to fix issues they may encounter. Most of the docs maintenance is done by few QGIS users/fans on their free time, so it's not easy to catch every request on time.

**Comment by DiGro** [comment]
@DelazJ   Thanks, I think you have made a lot of (starting) users happy :-)

**Comment by tgdbepe4** [comment]
@DelazJ Sorry for my remark. It takes me many hours to identify the problem. The reason was that this problem was reported, resp. mentioned over many years (google search) and with always the recommendation to download and use the dataset from the tutorial site. But the dataset was never corrected. And I very appreciate all the free of time work which many people are doing for QGIS. Maybe I and other too have not figure out that right place to address such problems is here on githup. So thanks again for your assistance!

**Comment by tgdbepe4** [comment]
@DiGro  Was you able to perform:
8.4.7.1. Align the rasters
For our analysis we need the rasters to have the same CRS and they have to be aligned.
First we change the resolution of our rainfall data to 30 meters (pixel size):
    Right-click on the Rainfall_clipped layer and select Export► Save As… in the context menu.
    Set the Horizontal and Vertical resolution to 30 (meters).
    Save the file as Rainfall30.tif in rainfall/reprojected (File name)`
Then we align the DEM:
    Right-click on the DEM_clipped layer and select Export► Save As… in the context menu
    For CRS, choose WGS 84 / UTM zone 33S (EPSG code 32733)
    Set the Horizontal and Vertical resolution to 30 (meters)
    Under Extent, click on Calculate from Layer and choose rainfall30
    Save the file as DEM30.tif in DEM/reprojected (File name)

Sorry to all  I found no other way to reach you prsonally!
This is my problem:
    **Set the Horizontal and Vertical resolution to 30 (meters)**

**Comment by DiGro** [comment]
@tgdbepe4 

Peter,  no problem
Those settings are in the dialog Export as..
You have probably not yet opened the section Resolution (click the small triangle to open)
There you will  find the Horizontal and Vertical resolution

See screenshot:
![Peter_Export_Save as](https://user-images.githubusercontent.com/5002095/98840342-f7e19980-2446-11eb-9501-af8489205e3a.png)

**Comment by tgdbepe4** [comment]
But how to enter the value in (30) meter. Have to successful performed?

Von meinem iPhone gesendet

**Comment by DiGro** [comment]
@tgdbepe4
Simply click in the field and enter 30  (CRS EPSG:32733 is in meters).
I did complete the exercise

**Comment by DiGro** [comment]
Peter,

if you received this message you will have my e-mail now

__________
DiGro


     Op donderdag 12 november 2020 13:14:49 CET schreef Peter Berger <notifications@github.com>:  
 
 

But how to enter the value in (30) meter. Have to successful performed?

Von meinem iPhone gesendet
