### ISSUE TITLE
Show symbol as icon for attribute row

### ISSUE THREAD

**Issue by yjacolin** [qgis/QGIS-Documentation#615]
https://github.com/qgis/QGIS/commit/e3b2a2daf2a5368c8e5565cd83acc26e706e00c2
Author: Nathan Woodrow
Date:   Thu Jul 9 08:18:57 2015 +1000

**Comment by yjacolin** [comment]
https://github.com/qgis/QGIS/commit/bf6f62cd05fe22b939118c07f52c75837567faa8
Author: Nathan Woodrow <madmanwoo@gmail.com>
Date:   Sat Jul 11 18:21:42 2015 +1000

    Revert "[FEATURE] Show symbol as icon for attribute row"
    
    This reverts https://github.com/qgis/QGIS/commit/e3b2a2daf2a5368c8e5565cd83acc26e706e00c2.
    
    Revert until I fix the speed issues

**Comment by yjacolin** [comment]
Should not be documented as it still not be merged!

**Comment by DelazJ** [comment]
@yjacolin @NathanW2 what's the current status of this feature? Has it been merged or should this issue report be closed?

**Comment by NathanW2** [comment]
Hi this feature was reverted as it wasn't as good as I thought.  Can be
removed.

**Comment by DelazJ** [comment]
Thanks.
