### ISSUE TITLE
[needs-docs] Move Python Console settings for font colors and family
to new "Code Editor" tab in options dialog

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#6171]
Original commit: https://github.com/qgis/QGIS/commit/47236421af3f5af75cbd29b60b45209d9f79d3f4 by nyalldawson

These settings apply to more than just the Python console editors -
rather they apply to all code editors across QGIS (including expression
editors)

**Comment by DelazJ** [comment]
Duplicate of #6172
