### ISSUE TITLE
[FEATURE] [UI] OGR source select: add a dynamic layout to define open options

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#6175]
Original commit: https://github.com/qgis/QGIS/commit/46ce3085c36e151562dc1545b008b3c862adcb16 by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by lajunek** [comment]
@nyalldawson @DelazJ does the dynamic layout interact with the Data Source Manager? Is this a hidden functionality?

**Comment by nyalldawson** [comment]
@lajunek yes. A good example would be to select a shape file in the vector tab of data source manager and you should see a new table of options "magically" appear

**Comment by lajunek** [comment]
@nyalldawson thanks Nyall. Actually I'm pointing out the differences between "Add Vector Layer --> Create a New Database Connection --> Type: Oracle Spatial" and the other way "Add Oracle layer --> Create a New Oracle Connection" . From my point of view the second way provides the settings for setting up a new connection and the first way can be used when the oracle connection is already set up. The user may find this confusing... Do you agree with my explanation or did I miss something?

**Comment by nyalldawson** [comment]
@lajunek actually it's a bit more tricky then that, unfortunately. The first way ("Add Vector Layer -> Database -> New") creates a connection using the GDAL driver, whereas "Add Oracle Layer" adds a connection which uses the native QGIS Oracle data provider. Unless there's some very specific reason a user needs to use the GDAL driver, we should always direct them to using the native QGIS data provider.

It's somewhat unfortunate that we expose this double-up, but there is a number of sources like Oracle, Postgres, SQL Server, Spatialite where we have both full-featured native QGIS drivers and GDAL also has a generic driver...
