### ISSUE TITLE
Training Manual - Lesson 5.3: Forms - integer overflow and widget boxes in custom forms

### ISSUE THREAD

**Issue by Geogistn** [qgis/QGIS-Documentation#6177]
In lesson 5.3.5., the user is instructed to create a new GeoPackage layer and add two new fields, "age"  and "name". The training manual indicates that the type of both fields should be assigned  _Text Data_. If the user assigns the type for the "age" field as _Text Data_, an integer overflow will occur later when attempting to change the age of a new data point after adding in a custom form (as per the instructions in lessons 5.3.6., and 5.3.7.).

To prevent the overflow from occurring, the "age" field type should be assigned as _Whole Number (integer)_, instead of _Text Data_.

It should also be noted in the manual when naming the widget boxes "name" and "age" (while creating a custom form in 5.3.6.) the names must match **EXACTLY** the "name" and "age" fields of the point layer (fields were named when creating the new GeoPackage Layer in step 5.3.5.). Otherwise, when the user adds a new data point the name and age they input will not be assigned correctly, and thus the "name" and "age" fields of the data point will be _NULL_ in the attribute table.

Page URL: https://docs.qgis.org/3.10/en/docs/training_manual/create_vector_data/forms.html

**Comment by felixfeckler** [comment]
Adapted the names for the  QObjects, so that they are consistent with the geopackage field names.

Could not replicate the integer overflow, so did not change that part.

**Comment by DelazJ** [comment]
> Adapted the names for the QObjects, so that they are consistent with the geopackage field names.

Thanks @felixfeckler 
I find it weird to want to use a spinbox to store textual value and weird to store age as text. So if you are willing to do these fixes also (a screenshot fix would also be needed), it would be great. thanks

**Comment by felixfeckler** [comment]
Yeah thought the same when i made the changes, but wasn't sure if it is okay to modify the lessons.
But will fix it.

**Comment by felixfeckler** [comment]
As I changed the age to integer, the autogenerated form uses also a spinbox, so I guess there was some logic behind that. 
So I changed the age to integer and added 2 modified screenshots, but wont change the spinbox.
