### ISSUE TITLE
Error:    Index creation failed

### ISSUE THREAD

**Issue by ErimTaka** [qgis/QGIS-Documentation#6206]
Hi, I am new and I am developing a drainage network for a basin, I am using Saga for the creation of the drainage and I got the error of "index creation failed" when I finished processing the drainage, I don't know what to do because I have already done it, tried four times and I get the same error, post-error I get incomplete drain network.
If anyone could provide me with any solution, I will be delighted. 
![error 1](https://user-images.githubusercontent.com/73234120/96721453-c27aec00-1371-11eb-84cd-f77007e13c79.PNG)
![error](https://user-images.githubusercontent.com/73234120/96721458-c444af80-1371-11eb-9c9f-876a117b3a2d.PNG)

**Comment by DelazJ** [comment]
Hi @ErimTaka 
Please ask for help in qgis-user list (see [support channels](https://qgis.org/en/site/forusers/support.html)). You'll have more chances.
This repository is actually dedicated to issues related to the [documentation of the project](https://docs.qgis.org).
I'm closing. Thanks for understanding
