### ISSUE TITLE
[feature][gui] add "close all tabs" to QgsMessageLogViewer

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#6224]
Original commit: https://github.com/qgis/QGIS/commit/e248ffff53af6d823979d4ed87ba52d712f20ccc by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by felixfeckler** [comment]
I think this one needs no documentation, the other options are also not documented ("Close Tab" and "Close other Tabs") and i dont think they have to... 
Leaving the Ticket open, since im not 100% certain.

**Comment by roya0045** [comment]
I'd be inclined to agree.

**Comment by DelazJ** [comment]
Then let's agree 😄
