### ISSUE TITLE
User guide - Expressions - description for function type RELATION is missing

### ISSUE THREAD

**Issue by PitGraebel** [qgis/QGIS-Documentation#6231]
The chapter 14.2 "Expressions" describes functions listed in the expression editor. But unfortunatily there is no description for the function 'Relation', which is available if you have defined a relation in the project properties. 
Can someone please describe this or give me a tip where I can find information about this function?

Page URL: https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/expression.html#

**Comment by DelazJ** [comment]
@PitGraebel I don't know what exact function you are talking about (can't recall a function called "Relation"- mind sharing a screenshot?) but you have information on functions and variables at https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/functions_list.html (though mainly picked from the interface)

**Comment by PitGraebel** [comment]
@DelazJ Thanks for your fast reply!. The list of functions and the list of expressions are quite similar, but both lack a description of the "relation" function. You can see the function in the expression editor: 
german
![image](https://user-images.githubusercontent.com/73649813/97584278-26e41e00-19f8-11eb-8a81-c6e267d6099c.png)
english (https://docs.qgis.org/testing/en/_images/function_list.png)
![image](https://user-images.githubusercontent.com/73649813/97585177-21d39e80-19f9-11eb-99a9-d081fa7e0afc.png)

**Comment by DelazJ** [comment]
Can you expand the relations group and show the functions in, please? Would help to find them in code

**Comment by DelazJ** [comment]
OK. I found [the group](https://github.com/qgis/QGIS/blob/master/resources/function_help/json/Relations) and I think the screenshot I ask wouldn't help since these might be bound to your project.

**Comment by PitGraebel** [comment]
There are no functions, just the names of the defined relations. 
![image](https://user-images.githubusercontent.com/73649813/97585999-0917b880-19fa-11eb-9f46-4bc69de27462.png)

**Comment by DelazJ** [comment]
I'd say these might be handy to have, for use in eg the [relation_aggregate](https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/functions_list.html#relation-aggregate) function

**Comment by PitGraebel** [comment]
Ahh, ok. It's not a function it's a convenience feature. I understand ... 
Thanks a lot, nice to work with you!

**Comment by DelazJ** [comment]
You're welcome.
