### ISSUE TITLE
Effective Modern C++ book

### ISSUE THREAD

**Issue by miurahr** [qgis/QGIS-Documentation#6286]
## Description

On developer guide, coding standard guide, it recommend  bible books `More effective C++` and `Effective STL` by Scott Meyers. Unfortunately recent standard progress deprecated some description on that.

It would be better to add `Effective Modern C++` that support C++11 standard for recommendation list.
 
Page URL: https://docs.qgis.org/3.16/en/docs/developers_guide/codingstandards.html#book-recommendations

**Comment by DelazJ** [comment]
> It would be better to add Effective Modern C++ that support C++11 standard for recommendation list.

Is it not already in the list? the url points to https://www.oreilly.com/library/view/effective-modern-c/9781491908419/
![image](https://user-images.githubusercontent.com/7983394/99381996-24286a80-28cc-11eb-832b-0101f99cd2fd.png)

**Comment by miurahr** [comment]
Oh, exactly... sorry.

**Comment by DelazJ** [comment]
No problem. Thanks for trying to improve the situation.
