### ISSUE TITLE
[composer] Data defined style preset for composer maps

### ISSUE THREAD

**Issue by yjacolin** [qgis/QGIS-Documentation#629]
https://github.com/qgis/QGIS/commit/b87e5f7573752533561f943e2c8333f280aebb69
Author: Nyall Dawson
Date:   Wed Aug 19 20:42:04 2015 +1000
    
    Sponsored by City of Uster

**Comment by yjacolin** [comment]
I already added description about data-defined feature in the vector chapter but this is not linked to it, see [1]. I propose to move this part outside vector chapter to somewhere more generic, like http://docs.qgis.org/testing/en/docs/user_manual/introduction/general_tools.html.

@SrNetoChan , @DelazJ , @andremano thought?

[1] https://github.com/qgis/QGIS-Documentation/pull/1057/files

**Comment by andremano** [comment]
I agree. Though it is a very vector related thing it is also an important key characteristic of QGIS, and therefore should be highlighted in the general tools. Besides, under the 'Working with vector data' section I don't see an obvious place for it.

**Comment by yjacolin** [comment]
Not so much only related to vector layer as it also in composer! Thakns @andremano

**Comment by DelazJ** [comment]
Actualy, I'm not sure we should move it from there. If it's because the DataDefined... is used elsewhere than vector, then this argument is valid for other settings (blend mode, color wheel at least).
What about just using internal link between pages?

**Comment by andremano** [comment]
Internal link meaning it will be accessible from all the documentation sections where this is relevant? Then yes.

**Comment by yjacolin** [comment]
I think we should move general feature in the general chapter and make reference to them in other specific chapters. 

Readers won't understand if in composer reference send to vector chapter. If you are looking only for datadefined, etiher you are looking for general topic or to the specific chapter, so specific chapter should send the reader back to the general chapter. If you think that general chapter should be kept in specific chapter (like vector chapter for data-defined) I will argue that why don't we use composer chapter?

**Comment by DelazJ** [comment]
@yjacolin valid arguments. Let's move these shared options to a more generic place!

**Comment by yjacolin** [comment]
note for myself: add icon, See #1087
