### ISSUE TITLE
Support for relative paths in widgets

### ISSUE THREAD

**Issue by yjacolin** [qgis/QGIS-Documentation#635]
https://github.com/qgis/QGIS/commit/75df5f20c9d6ae40dd5b05f4da71defbab84d283
Author: Matthias Kuhn
Date:   Mon Sep 7 20:07:26 2015 +0200

    Is implemented for the following edit widget types:
    
     * File Name
     * Photo
     * Web View
    
    If the path which is selected with the file browser is located in the same
    directory as the .qgs project file or below, paths are converted to relative
    paths.
    This increases portability of a qgs project with multimedia
    information attached.

**Comment by yjacolin** [comment]
@m-kuhn by 'or below' you mean in a subdirectory?

**Comment by m-kuhn** [comment]
> @m-kuhn by 'or below' you mean in a subdirectory?

:+1: Exactly
