### ISSUE TITLE
postgres provider: allow copying tables from one schema to an other

### ISSUE THREAD

**Issue by yjacolin** [qgis/QGIS-Documentation#637]
https://github.com/qgis/QGIS/commit/fd2ad1329ae2238d64287fb527a7043bc5f73cf7
Author: Juergen E. Fischer
Date:   Fri Sep 11 13:38:18 2015 +0200

**Comment by DelazJ** [comment]
@jef-n is this about the drag-and-drop ability to copy tables within the browser panel? the DBManager? or something else (and any idea of an appropriate chapter)?
Thanks.

**Comment by jef-n** [comment]
the browser
