### ISSUE TITLE
HTML Size tied to DPI of layout

### ISSUE THREAD

**Issue by baswein** [qgis/QGIS-Documentation#6387]
## Description
Thanks for all of your amazing documentation. 
The size that HTML fonts are displayed (I only checked fonts) is dependent on the layout export resolution at the time the HTML frame was created. This is not documented anywhere that I could find. 
See this issue for more details:
https://github.com/qgis/QGIS/issues/37864
I have checked that this is the same behavior using link, source, and user style sheets. It also doesn't seem to matter if you use px, pt , or em. I did some tests and on my computer (QGIS 3.16 on Windows 10) 11pt font in a label will be about the same size as 11pt font when the layout export resolution is set to 272dpi. And  100pt font in a label will be about the same size as 100pt font when the layout export resolution is set to 275dpi.

I believe the documentation should say: 
The HTML scale is controlled by the layout export resolution at the time the HTML frame is created. HTML is displayed at approximately 100% when the layout export resolution is around 272dpi.

Page URL:
https://docs.qgis.org/3.16/en/docs/user_manual/print_composer/composer_items/composer_html_frame.html?highlight=html#figure-layout-html-ppt

**Comment by DelazJ** [comment]
> I have checked that this is the same behavior using link, source, and user style sheets. It also doesn't seem to matter if you use px, pt , or em. I did some tests and on my computer (QGIS 3.16 on Windows 10) 11pt font in a label will be about the same size as 11pt font when the layout export resolution is set to 272dpi. And 100pt font in a label will be about the same size as 100pt font when the layout export resolution is set to 275dpi.

Hi @baswein 
IMO, having to go through these calculations in order to scale your label is more like a hack (due to a misbehavior or a missing feature).
Now if you want to propose a pull-request (and I'd appreciate a dev feedback on its rightfulness), just hit the "Edit on github" button at the top of the documentation page and everything would be set up for your text. Thanks for contributing.
