### ISSUE TITLE
Add option to map unit scaling for limiting size in mm

### ISSUE THREAD

**Issue by yjacolin** [qgis/QGIS-Documentation#640]
https://github.com/qgis/QGIS/commit/586d59a43267c4d2af9783202aa6d3cd5694fd15
Author: Nyall Dawson
Date:   Thu Sep 17 20:35:27 2015 +1000
    
    Previously only the option to limit the scale range of the scaling
    was available. Now you can also choose to limit the corresponding
    rendered size in mm.

**Comment by DelazJ** [comment]
fixed in https://github.com/qgis/QGIS-Documentation/pull/722/commits/c27ad86ea08d691d2987ccb41fe33e05bfd27751
