### ISSUE TITLE
New API for labeling engine (QgsLabelingEngineV2)

### ISSUE THREAD

**Issue by yjacolin** [qgis/QGIS-Documentation#643]
https://github.com/qgis/QGIS/commit/1d0d0e06622563502fc24973256f427f9eb6ebc8
Author: Martin Dobias
Date:   Thu Sep 10 11:59:38 2015 +0800

```
The idea is to make the engine more flexible compared to QgsPalLabeling implementation:
- abstract dealing with text labels / diagrams from the engine itself
- allow multiple types of labels per layer
- support custom label providers (e.g. implemented by plugins)
- make the labeling engine independent from map rendering engine
- make it easier to auto-test the labeling engine and its components

This code has been funded by Tuscany Region (Italy) - SITA (CIG: 63526840AE) and commissioned to Gis3W s.a.s.
```

**Comment by SrNetoChan** [comment]
@yjacolin I this is probably something to the PyQGIS Cookbook and not actually the users manual. @wonder-sk, what do you think?

**Comment by yjacolin** [comment]
yes, probably!

**Comment by wonder-sk** [comment]
Correct - no need for user docs update here...

**Comment by ThomasG77** [comment]
Searching through the QGIS code repository (e.g [this search](https://github.com/qgis/QGIS/search?l=python&q=QgsLabelingEngineV2&utf8=%E2%9C%93)), QgsLabelingEngineV2 is not available in Python SIP bindings. No idea about the why.
Consequently, at the moment, there is no need for an update to the "PyQGIS Cookbook" as long as code does not change.

**Comment by ThomasG77** [comment]
@wonder-sk Can we close the issue or some work is planned for Python support?

**Comment by DelazJ** [comment]
Closing. Too old and I guess, a lot of things have changed meanwhile. And labeling is not part of the cookbook (yet) so if/when the time comes, better rely on a more recent code/class.

**Comment by harshnisar** [comment]
@DelazJ Apologies for re-initiating discussion here. You mention a lot of things have changed in the meanwhile. Related to this, is there a way to use ```RenderOutlineLabels``` in python bindings now? Or any other way to make render labels not as outline in python?

**Comment by DelazJ** [comment]
Hi @harshnisar no idea but maybe some answer at https://qgis.org/pyqgis/master/search.html?q=RenderOutlineLabels&check_keywords=yes&area=default#?
