### ISSUE TITLE
Mutually exclusive layer tree groups (only one child may be checked at a time)

### ISSUE THREAD

**Issue by yjacolin** [qgis/QGIS-Documentation#644]
https://github.com/qgis/QGIS/commit/50d4e720a78d3fd2396f9bfe6bba3f4a9ebe6d53
Author: Martin Dobias <wonder.sk@gmail.com>
Date:   Mon Sep 21 19:28:00 2015 +0800
    
    The feature can be toggled individually for groups - in layer tree view context menu.
    
    This code has been funded by Tuscany Region (Italy) - SITA (CIG: 63526840AE) and commissioned to Gis3W s.a.s.

**Comment by DelazJ** [comment]
I think this issue can be closed due to #674 although there's no screenshot. But I'm not sure we need screenshot for context menu.
