### ISSUE TITLE
Authentication configuration system with master password

### ISSUE THREAD

**Issue by yjacolin** [qgis/QGIS-Documentation#645]
https://github.com/qgis/QGIS/commit/e65aa99ae7b320790d38e04a1a2b5d6232003571
Author: Larry Shaffer
Date:   Mon Sep 21 04:43:15 2015 -0600
    
    - Main C++ core and gui classes and desktop app integration
    - Support for authentication method plugins
    - Does not contain any integration with service connections

**Comment by dakcarto** [comment]
Hi,

What is the release schedule for the 2.14 documentation?

I am swamped right now, but the [documentation associated with the original QEP](https://github.com/qgis/QGIS-Enhancement-Proposals/issues/35) is outdated and needs redone to fit the final implementation, and the added features not noted there. I can have a revamped version of the authentication system docs in April, possibly starting a little earlier on it.

**Comment by SrNetoChan** [comment]
@Dakcarto I was planning to start document this next week. Do you think I can start the QEP and try to figure out what have changed myself? You would only have to review it and make smaller changes.

**Comment by yjacolin** [comment]
@SrNetoChan , @dakcarto did you work on this part? I started #691 which need a reference to this part :)

I can add the reference to *general tools* chapter if you think this is the correct location. Thought?

**Comment by SrNetoChan** [comment]
@yjacolin I plan to work on this on the next Wednesday. @dakcarto already have most of the source created I will be just applying the documentation guidelines and making the Pull request. I think General Tools should be ok. Please create the reference and send me a link to where it is. Thanks.
