### ISSUE TITLE
Correction of the Expression for Picture Item's X in Trainning Manual Section 4.2.4

### ISSUE THREAD

**Issue by tswwe** [qgis/QGIS-Documentation#6452]
## Description

The expression for the picture item's X is ought to be correct to `@layout_pagewidth - @sw_layout_margin - 49.5`.
In current document, the expression is `@layout_pagewidth - @sw_layout_margin * 2 - 78`, which is not aligned with the third label created in previous Section 4.2.3, and is conflict with the north arrow created in following content(4.2.4.2). 

Page URL: https://docs.qgis.org/3.16/en/docs/training_manual/map_composer/dynamic_layout.html#moderate-fa-adding-pictures-to-the-dynamic-header

**Comment by DelazJ** [comment]
@tswwe Thanks for reporting. Could you provide the fix directly, please? Just hit the "Edit on Github" button at the top of the docs page and you should be able to correct the text. Thanks

**Comment by tswwe** [comment]
Sure, I have done that and created a pull request.
