### ISSUE TITLE
Rule-based labeling

### ISSUE THREAD

**Issue by yjacolin** [qgis/QGIS-Documentation#646]
https://github.com/qgis/QGIS/commit/1782d1a50592624089067b49951f36161b825fea
Author: Martin Dobias
Date:   Wed Sep 23 10:12:56 2015 +0800
    
    Work in progress
    
    This code has been funded by Tuscany Region (Italy) - SITA (CIG: 63526840AE) and commissioned to Gis3W s.a.s.

**Comment by DelazJ** [comment]
Can we considere this issue fixed by #674 ?

**Comment by yjacolin** [comment]
correct. I close it.
