### ISSUE TITLE
[composer] Add option to hide pages from view/export

### ISSUE THREAD

**Issue by yjacolin** [qgis/QGIS-Documentation#648]
https://github.com/qgis/QGIS/commit/2215d487124b0800b1ea8420a16f8ed05085128c
Author: Nyall Dawson
Date:   Mon Sep 7 07:55:40 2015 +1000
    
    Sponsored by NIWA

**Comment by DelazJ** [comment]
@nyalldawson what can be the use case of this option? Have a transparent background for exported files? Or is there any other usage we can explain to the user?
Thanks.

**Comment by yjacolin** [comment]
If my understanding is correct, this feature allow the user to hide a page when exporting a composition. That's mean you can add a draft page and not export it after all. Or just export a part of the composition.

**Comment by nyalldawson** [comment]
Sorry, missed the github notification for this originally. 

That feature has been designed to make it easy to hide the page BACKGROUND. Often composer is used to create non-print layouts, eg for inclusion in presentations or other documents, and it's desirable to export the composition using a totally transparent background. Previously you could do this by manually setting the page background symbol to no fill/no border, but this makes it much quicker.

The other use case was that often these non-print compositions are not bound by any physical size restrictions (eg the composition is just as big as required to fit all items), and in this case showing a meaningless page border is distracting and misleading. For this use case you can switch off the pages from view, and freely work on your composition without any regard to the final size. It's sometimes referred to as "infinite canvas" in other editing packages.

**Comment by yjacolin** [comment]
note to myself:
* update zoomToSelected subsitution string to update icon filename
