### ISSUE TITLE
Pull requests against release_3.16 branch do not trigger html or doctest checks

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#6501]
If you look at [release_3.16 actions](https://github.com/qgis/QGIS-Documentation/actions?query=event%3Apull_request+branch%3Arelease_3.16), the last [HTML](https://github.com/qgis/QGIS-Documentation/actions?query=event%3Apull_request+workflow%3A%22HTML+build%22+branch%3Arelease_3.16) and [doctest](https://github.com/qgis/QGIS-Documentation/actions?query=event%3Apull_request+branch%3Arelease_3.16+workflow%3A%22Doctest+build%22) checks are 3 weeks old; Only the backport test is run when you open a PR against 3.16 branch. 
These tests are however working when opening a PR against master or pushing changes to any branch (including release_3.16 branch). I can't see any difference in the code between the branches so may I assume something has changed in the settings (of the repo, the bot, default branch in github actions...)? Maybe the pull_request_target issue?

**Comment by DelazJ** [comment]
Reformulated: automated backport does not trigger tests on the generated pull request.
Based on discussion in dev list, I assume it's because we were missing the PAT (GH_TOKEN_BOT). Am I right, @m-kuhn? @3nids @elpaso can any of you extend its scope to the docs repo or create one, please? Thanks

**Comment by m-kuhn** [comment]
Correct, for reference https://github.com/m-kuhn/backport/pull/21

**Comment by m-kuhn** [comment]
Someone with admin rights on this repository will need to:

1. generate a new PAT for the qgis-bot
2. add a new secret on this repository https://github.com/qgis/QGIS-Documentation/settings/secrets/actions
3. adjust the workflow here https://github.com/qgis/QGIS-Documentation/blob/master/.github/workflows/backport.yml#L17

I don't have the required permissions on this repository to do so

**Comment by m-kuhn** [comment]
I do have the credentials to generate a PAT for qgis-bot, but lack admin rights here. I can jump in if I get the required permissions.

**Comment by Jean-Roc** [comment]
@DelazJ @m-kuhn  I have granted admin rights for this repo to your accounts

**Comment by DelazJ** [comment]
Thanks @Jean-Roc  and welcome @m-kuhn 👍

**Comment by m-kuhn** [comment]
Thanks, it's ready for a test drive

**Comment by DelazJ** [comment]
Working. Thanks.
