### ISSUE TITLE
Missing: argument labels for the providerLib parameter in the QgsVectorLayer class

### ISSUE THREAD

**Issue by josephburkhart** [qgis/QGIS-Documentation#6526]
Hi all,

I just noticed that in the `QgsVectorLayer` class description, the section that explains the options for `providerLib` is missing the arguments themselves. For example, the paragraph beginning with "Accesses data using the OGR drivers" should be labelled with `"ogr"`.

Page URL: https://qgis.org/pyqgis/3.16/core/QgsVectorLayer.html#qgis.core.QgsVectorLayer

Edit: if this is the wrong place to point this problem out, my apologies. I'm new to both QGIS and GitHub.

**Comment by DelazJ** [comment]
Hi @BotDoubt 
Thanks for reporting. The source of the page you point to is  https://github.com/qgis/QGIS/blob/master/python/core/auto_generated/vector/qgsvectorlayer.sip.in auto-generated based on https://github.com/qgis/QGIS/blob/master/src/core/vector/qgsvectorlayer.h (in case you'd like to give it a look). in the source files, these paragraphs are separated subsections with title to introduce every new provider, eg 
https://github.com/qgis/QGIS/blob/0c36f28295520a424659e152b97a86e87a236f06/python/core/auto_generated/vector/qgsvectorlayer.sip.in#L76
But they do not appear in the HTML

@gioman could you please move this issue to code repo please? There's nothing this repository could do with this. Thanks.
@3nids maybe you have an idea what would be wrong? I thought it was fixed but browsing recent pyqgis docs did not display the subsection title as such. Some (3.8) however display the subsection title as text.
And it could be nice we find a way to let people know that pyqgis sources (and issue report) belong to https://github.com/qgis/QGIS or https://github.com/qgis/pyqgis

**Comment by BotDoubt** [comment]
Hi @DelazJ 
Apologies for putting this in the wrong place, and thanks for the explanation! Very helpful for me.

**Comment by DelazJ** [comment]
No worries. The instruction is available nowhere.
Let's expect the report will be moved to the place where people who can fix it could read it.

**Comment by DelazJ** [comment]
@josephburkhart I'm closing this: One less report to count given that we can't fix it here. Feel free to reopen in qgis/QGIS repo. Thanks.
