### ISSUE TITLE
Images with mostly zero pixels are not processed correctly

### ISSUE THREAD

**Issue by inamurada** [qgis/QGIS-Documentation#6549]
## Description

The problem occurs when handling a Raster with 8192x8192 pixels.
The cell values are 1 for the radius of about 40 cells in the center of the image, and 0 for the rest (for masking).
When I load this file into QGIS, all the values are 0.
When the same file is imported into software other than QGIS, it is handled correctly (ArcGIS, Global mapper, Arcview).

I have changed the save format to ASCII, GRID, GEOTIFF, etc. and the same problem occurs when I load it.
Only tif output from ArcGIS loaded correctly in QGIS.

However, when I use this tif image to do some processing in QGIS (e.g. Raster calculator), it outputs an all-zero image.
This problem does not occur when the file size is small.

[data.zip](https://github.com/qgis/QGIS-Documentation/files/6046883/data.zip)

Page [URL:]()))

**Comment by DelazJ** [comment]
Hi @inamurada 
This is not a QGIS **documentation** issue. Please ask for help in the qgis user list and if confirmed it's a bug, report at https://github.com/qgis/QGIS/issues. Thanks.
