### ISSUE TITLE
creating layouts

### ISSUE THREAD

**Issue by sverbeeren** [qgis/QGIS-Documentation#6569]
Suddenly I am not able to create new layouts or duplicate layouts. If I click the buttom to do so, nothing happens. So I can only use old layouts and change them but this is not workable. How can I solve this problem?

**Comment by DelazJ** [comment]
Hi @sverbeeren 

Please try running an up to date QGIS version with [a clean profile](https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles) and if not solved report this in the [application issue tracker](https://github.com/qgis/QGIS/issues) with more details (QGIS version, OS, project files would be necessary...). 
This repository is dedicated to [QGIS documentation](https://docs.qgis.org) issues, hence I'm closing.
Thanks.
