### ISSUE TITLE
Sample project for qgis-server does not contain advertised URL

### ISSUE THREAD

**Issue by ar-siddiqui** [qgis/QGIS-Documentation#6603]
## Description

Page URL: https://docs.qgis.org/3.16/en/docs/server_manual/containerized_deployment.html

The sample QGIS project given on this page does not contain advertised URLs for WMS/WFS/WCS/WMTS and the documentation does not mention to add it. Without the advertised URLs qgis-server WMS/WFS/WCS/WMTS capabilities are broken. More details here: [https://gis.stackexchange.com/questions/390002/qgis-server-map-request-failed-error-host-not-found](https://gis.stackexchange.com/questions/390002/qgis-server-map-request-failed-error-host-not-found)

A line should be added under https://docs.qgis.org/3.16/en/docs/server_manual/containerized_deployment.html#first-run 

> If you want qgis-server to have WMS/WFS/WCS/WMTS capabilities, add advertised URLs under the Project Properties > QGIS Server tab.

**Comment by DelazJ** [comment]
@benoitdm-oslandia mind taking the project file update, please?
> A line should be added under ...

@ar-siddiqui maybe this is something you can help us fix? Hitting the "Edit on github" button at the top of the docs page will turn that page into edit mode and you can change and open a pull request. Thanks.

**Comment by ar-siddiqui** [comment]
I can do that, in that case, we don't need to update the project.

**Comment by benoitdm-oslandia** [comment]
@ar-siddiqui thank you for this update!
