### ISSUE TITLE
Docs for legend patches

### ISSUE THREAD

**Issue by tjukanovt** [qgis/QGIS-Documentation#6634]
## Description
Currently the legend patch functionality is missing completely from the documentation. There are a few open (automatically generated) issues on those, but main documentation is actually completely missing. Could be added as a new topic under [Legend items](https://docs.qgis.org/3.16/en/docs/user_manual/print_composer/composer_items/composer_legend.html?highlight=legend#legend-items)

## Open issues related to legend patches
https://github.com/qgis/QGIS-Documentation/issues/5330 (which might have this duplicate issue: https://github.com/qgis/QGIS-Documentation/issues/5329, see https://github.com/qgis/QGIS-Documentation/issues/5325)
https://github.com/qgis/QGIS-Documentation/issues/5326
https://github.com/qgis/QGIS-Documentation/issues/5364

These are the functionalities lacking documentation:
![image](https://user-images.githubusercontent.com/13899537/113693421-41bd6b80-96d7-11eb-89cc-444412d4b0cb.png)
![image](https://user-images.githubusercontent.com/13899537/113692245-04a4a980-96d6-11eb-883e-b830a7fd6707.png)

I will start working on a PR on this. Comments/input welcome.

**Comment by ioalexei** [comment]
It looks like this has been addressed somewhere between 3.16 and 3.28 - https://docs.qgis.org/3.28/en/docs/user_manual/print_composer/composer_items/composer_legend.html#customizing-legend-items. 

Can it be closed, or is more detail needed on how to use the shape/custom symbols?

**Comment by selmaVH1** [comment]
> It looks like this has been addressed somewhere between 3.16 and 3.28 - https://docs.qgis.org/3.28/en/docs/user_manual/print_composer/composer_items/composer_legend.html#customizing-legend-items.
> 
> Can it be closed, or is more detail needed on how to use the shape/custom symbols?

Hi @ioalexei Legend patches are also described [here](https://docs.qgis.org/testing/en/docs/user_manual/style_library/style_manager.html#creating-a-legend-patch-shape). I think this one can be closed, but I would like to have confirmation from @DelazJ.
