### ISSUE TITLE
[FEATURE] adding new features to QGIS will create issues in QGIS-Documentation

### ISSUE THREAD

**Issue by qgis-feature-tracker** [qgis/QGIS-Documentation#664]
Original commit: https://github.com/qgis/QGIS/commit/53ecc25151541020f19d15516df731f732f043eb by rduivenvoorde

A githook is implemented to create an issue automatically in QGIS-Documention repo whenever there is a commit with the word [FEATURE] in the message.

( this is also a test if it works :-) )

**Comment by timlinux** [comment]
@rduivenvoorde can you share the githook code? It would be nice to wire that up to the changelog too so it automatically creates an issue for all new FEATUREs added.

**Comment by SrNetoChan** [comment]
Don't Think this is a Open Issue for Documentation. Can we close it?

**Comment by yjacolin** [comment]
hehe yes :)

**Comment by DelazJ** [comment]
It's however worth knowing by (upcoming) developers so I moved it to https://github.com/qgis/QGIS-Website/issues/317
