### ISSUE TITLE
Issue with menu translation

### ISSUE THREAD

**Issue by MG977** [qgis/QGIS-Documentation#6672]
Hi. Googling to seek a solution to my issue, I come across this old bug report: https://issues.qgis.org/issues/20001
I have the same problem with both QGIS 3.18.1 & 3.18.2.
However, when localized in Italian (my system language), everything is fine. But when localized in English (my desired language), the menu "Vector" is empty and, after the "Help", I have a menu "Vettore" mixed up with Italian and English.
Any suggestion to fix it? Thanks.

**Comment by DelazJ** [comment]
Hi @MG977 
Go to menu Settings --> Options --> Processing and next to the "menus" entry, press the Reset to defaults" button. Restart QGIS.
Please note that this is the repository of the documentation and any issue you have with the application should be reported either in https://github.com/qgis/QGIS/issues or in our [mailing list](http://qgis.org/en/site/forusers/support.html) for seeking help.

**Comment by MG977** [comment]
Thank you.  That fixed the issue.
Sorry for posting in the wrong section.
