### ISSUE TITLE
How handling output extent and html in Processing?

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#668]
In [Writing new Processing algo](http://docs.qgis.org/2.18/en/docs/user_manual/processing/scripts.html), It would  be great to have more informations about what are and how to handle output html and output extent in handing data produced section, and more globally how to handle the hidden outputs (kind of use case?)

**Comment by ghtmtt** [comment]
@DelazJ @yjacolin the script section is really outdated. What about closing this issue?

**Comment by DelazJ** [comment]
I'm afraid that closing this issue would simply hide the issue to us and not solve any. There are two issues there, the outdated chapter and the missing features in the chapter. so my vote would be to keep it open, until it's solved (because written in an updated chapter, or becomes a deprecated feature)

**Comment by yjacolin** [comment]
Could we add a new info section, as for "testing" documentation to alert reader that "This part is outdated, however you can help us to improve it contributing to the documentation. See XXX for more information"?

**Comment by havatv** [comment]
This should be covered in current documentation. scripts.rst has been completely rewritten.
