### ISSUE TITLE
ow to install an previous version of QGIS Server on Windows 10?

### ISSUE THREAD

**Issue by franyam2006** [qgis/QGIS-Documentation#6685]
Good morning all,

A year ago, as part of a Lizmap project, I downloaded and installed version 3.10 of QGIS Server on Windows 10 . 
![qgis_server](https://user-images.githubusercontent.com/61616432/116489483-9bebbf80-a884-11eb-9d85-70944fc5180d.PNG)
whose executable file is osgeo4w-setup-x86_64.exe.

This year I took the same osgeo4w-setup-x86_64.exe executable file and ran it to install it. I see that the version has changed, it went from 3.10 to 3.16 (see attached file)

While this is the same file that I installed a year ago which had version 3.10. Now I am now looking to have installed the previous version which was 3.10 I can't do it anymore.
What to do ? Thank you in advance for your answers

**Comment by roya0045** [comment]
Please ask ok the user mailing list, this is not the right place for such enquiries.

**Comment by DelazJ** [comment]
I confirm, please ask for help in qgis-user list (see [support channels](http://qgis.org/en/site/forusers/support.html)).
This repository is actually dedicated to issues related to the documentation of QGIS project.
Closing. And thanks for your understanding.
