### ISSUE TITLE
Server plugin directory

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS-Documentation#6688]
## Description

Any special reason for the directory change from `/opt/qgis-server/plugins` -> `/var/www/qgis-server/plugins` in https://github.com/qgis/QGIS-Documentation/commit/00ba8a70302bea034fc2c15be0c8779423c7301a#diff-08497c66b7c67399ad4cc653b57c60efdfd648dd6b29639eb78d3aa9e07b7660R21 ?

There's some documentation around which mentions `/opt/qgis-server/plugins` as the server plugin directory, e.g
- https://github.com/3liz/qgis-wfsOutputExtension#installation
- https://www.itopen.it/qgis-server-python-plugins-ubuntu-setup/

If there's no speacial reason, maybe use `/opt/qgis-server/plugins` again for the docs?

Page URL:
https://docs.qgis.org/3.16/en/docs/server_manual/plugins.html#installation

**Comment by DelazJ** [comment]
ping @pcav as the author of the switch

**Comment by DelazJ** [comment]
Gentle ping @pcav or any server guru? I'd like to close/fix this kind of reports. Thanks

**Comment by Gustry** [comment]
I think the explanation on https://docs.qgis.org/3.22/en/docs/server_manual/plugins.html#location-of-plugins is ok now @pathmapper what do you think ?

It's mentioning the default location on debian and the environment variable.

**Comment by pathmapper** [comment]
Looks good, thanks @Gustry !
