### ISSUE TITLE
QGIS documentation and website translators list out of date

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#669]
http://qgis.org/en/site/getinvolved/governance/governance.html#community-resources states: "Find the list of documentation and website translators at: https://github.com/qgis/QGIS-Documentation"
IMHO, this list is out of date since we moved to transifex.
We should find a way to sync this list with transifex one, no? Desktop translators are listed in the app, it'd be nice to do such thing for Docs and website team, too.

**Comment by rduivenvoorde** [comment]
This should be possible via the transifex rest api.

The portoguese have some system in which the request the percentage of translations from transfifex and show it: http://www.qgis.pt/traducao.html

I think it we could also find out the names of the people in the team? Though I'm not sure if we can see the real names or som 'funny' nicknames...

**Comment by tudorbarascu** [comment]
In case we gather statistics, it would be nicer to put those statistics somewhere and just provide a link towards them. This way, we would get rid of the extra noise in readme commit + the statistics + contributors could be presented in a better way.

**Comment by DelazJ** [comment]
I added some comments in the [hackfest doc wiki](https://github.com/qgis/QGIS-Documentation/wiki/hackfest_Bonn_2016), to have it discussed at Bonn.
