### ISSUE TITLE
[FEATURE] show filename in layer name when importing multiple layers from a ogr datasource

### ISSUE THREAD

**Issue by jef-n** [qgis/QGIS-Documentation#670]
Original commit: qgis/QGIS@f99ccf0 by jef-n

show filename in layer name when importing multiple layers from a ogr datasource (implements [#13756](https://hub.qgis.org/issues/13756))

**Comment by raymondnijssen** [comment]
I don't think this "feature" needs documentation. This issue can be closed, right?

**Comment by yjacolin** [comment]
nope, but we can have a check that the documentation don't say anything different.

**Comment by yjacolin** [comment]
I think we can improve this section [1]:

* write the 'open files format XXX' in a more generic way. Specifically we have the section title realy different for each file format (loading mapinfo file vs ESRI Shapefiles)
* add a note about drag and drop files from browser, and how the layername are defined in this case
* "Vector layers crossing 180° longitude" should be move outside data format.

Though?

[1] http://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/supported_data.html
