### ISSUE TITLE
Status of https://qgis-docs.readthedocs.io

### ISSUE THREAD

**Issue by Gustry** [qgis/QGIS-Documentation#6734]
## Description

I have just used my search engine and it gave me an URL like :
https://qgis-docs.readthedocs.io/en/latest/docs/index.html

I saw the `latest` in the URL so I was OK and I continued reading the documentation.
A few minutes later, I have only noticed that I wasn't on docs.qgis.org but on qgis-docs.readthedocs.io.
Then after I have noticed the old QGIS Logo

In the footer :  
> Last updated on 09:47 Feb 17, 2016 

I'm not sure if one of us owns the readthedocs.io account but I think we should either update the content or remove it.
I would be in favor of removing, we have docs.qgis.org which works well, no ?

@rduivenvoorde Do you have any idea ?

**Comment by rduivenvoorde** [comment]
IN the early beginning of the rst builds someone set this up there, but because (in the beginning) we had site and docs in one, we needed some extra build steps (and some special theming at that time) that it did not work, and we start building ourselves.
Not sure who set it up. I would be ok to clean it up. Do we need/have the passwords?

**Comment by Gustry** [comment]
Ok, thanks for the explanation.

Can we know who was it ?

> Do we need/have the passwords?

I guess we need passwords. Otherwise it means everyone could delete our doc :)

**Comment by DelazJ** [comment]
> Can we know who was it ?

The readthedocs project might be able to tell us, if we contact them. No?

**Comment by tjukanovt** [comment]
I have sent a support request to readthedocs project and asked about the status/ownership of that project. I will report here when I get a response.

**Comment by DelazJ** [comment]
Thanks @tjukanovt

**Comment by tjukanovt** [comment]
Got a reply back and apparently the project is owned by @wonder-sk. Any thoughts Martin on this issue? Should we update it or remove it? I would suggest the latter as maintaining the docs in many places can quickly become difficult.

**Comment by DelazJ** [comment]
Thanks @tjukanovt. Glad that the owner is someone still around.
> Should we update it or remove it? I would suggest the latter as maintaining the docs in many places can quickly become difficult.

Agreed. A single entry point for docs sounds better to me

**Comment by Gustry** [comment]
Gentle ping @wonder-sk :)

**Comment by Gustry** [comment]
Similar request as before, I have noticed that Google is giving links pointing to https://qgis-documentation.readthedocs.io/

Does anyone in this ticket know about this other readthedocs.io project ?
It would be nice to remove it, so search engines can stop sending people on this old web page.

**Comment by DelazJ** [comment]
@wonder-sk Are you also owner of https://qgis-documentation.readthedocs.io/ 😄 ?
If not @tjukanovt someone particular to get in touch with in readthedocs team in order to know the actual owner of that site?
Thanks to you.

**Comment by DelazJ** [comment]
Shame on me. I did even not try to check the bottom  right menu.
Thanks @nicogodet

**Comment by DelazJ** [comment]
@capooti Could you please delete the https://qgis-documentation.readthedocs.io/ project to avoid it showing among search results? Thanks.

**Comment by capooti** [comment]
> @capooti Could you please delete the https://qgis-documentation.readthedocs.io/ project to avoid it showing among search results? Thanks.

just done! sorry if this caused issues

**Comment by Gustry** [comment]
Thanks @capooti !
