### ISSUE TITLE
Documentation of Geometry Validation panel missing

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS-Documentation#6740]
## Description

The documentation of the Geometry Validation panel is missing.

Page URL:
https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_gui.html#panels

**Comment by DelazJ** [comment]
@agiudiceandrea I checked master on Linux and Windows, as well as earlier versions, and I couldn't find any "Geometry validation" entry under View --> Panels

**Comment by agiudiceandrea** [comment]
It is available when the Geometry checks are set in the layer properties Digitizing settings window
![image](https://user-images.githubusercontent.com/16253859/122026735-ca890f80-cdca-11eb-999c-f0b8541f01bd.png)

![image](https://user-images.githubusercontent.com/16253859/122026634-b1805e80-cdca-11eb-983b-1fd739d1da8a.png)
