### ISSUE TITLE
documentation doesn't mention html rendering in logMessages-panel

### ISSUE THREAD

**Issue by koebi** [qgis/QGIS-Documentation#6745]
## Description
The Log Messages Panel apparently renders html
This is neither mentioned in the [pygis cookbok](https://docs.qgis.org/3.16/en/docs/pyqgis_developer_cookbook/communicating.html#qgsmessagelog), nor in the [user manual](https://docs.qgis.org/3.16/en/docs/user_manual/introduction/general_tools.html?highlight=message%20log#log-messages-panel) nor in the [QgsMessageLog-Documentation](https://qgis.org/pyqgis/master/core/QgsMessageLog.html).

The last place is where I'd hoped for this to be documented, since it just states `message` as being a string, not as being an html-string…

This became problematic when I tried to log python types (e.g. `<class 'str'>), as they disappeared for no apparent reason.

I am honestly a bit unsure on where to file this bug, so any pointers are greatly appreciated :)

**Comment by DelazJ** [comment]
@koebi If you think the API docs is incomplete then I'd suggest to report at https://github.com/qgis/QGIS/issues. It's where the necessary code needs to be filled.
Also, if you then think it's necessary to add to the docs, do not hesitate to propose a pull request. Thanks

**Comment by koebi** [comment]
Hey,
this took way too long, but I have reported the issue in qgis directly.
I'll close it here. Thanks for your help :))
