### ISSUE TITLE
[FEATURE] Expression compiler for SpatiaLite provider

### ISSUE THREAD

**Issue by qgis-feature-tracker** [qgis/QGIS-Documentation#676]
Original commit: https://github.com/qgis/QGIS/commit/35d0dd3211a799bee1eba2a7ed62d3fda3bc4e67 by nyalldawson

Unfortunately this lazy coder did not write a description... :-(

**Comment by yjacolin** [comment]
@nyalldawson is this something we should document? Same for #677, #675

**Comment by nyalldawson** [comment]
No - nothing user facing here!
