### ISSUE TITLE
[FEATURE]postgres provider: add support for timestamp types

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#678]
Original commit: https://github.com/qgis/QGIS/commit/f6e4e75cd6257a2fa6a59beb9892d7517bbbd39d by jef-n

Unfortunately this lazy coder did not write a description... :-(

**Comment by yjacolin** [comment]
There is no location to list the postgis support datatype in documentation. @DelazJ ok to close it?

**Comment by DelazJ** [comment]
@yjacolin not sure we'd close it. Let's keep it open and see how the doc can be improved to have it incorporated if it's an information that users should know.
What about the ["Supported Data"](http://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/supported_data.html#postgis-layers) chapter when tackling #1088?

**Comment by yjacolin** [comment]
Yes, my first try was in this chapter. But that's mean that we should know which data type are supported and which not. At tleast the main ones.

**Comment by DelazJ** [comment]
Let's keep it for after 2.14 doc release?

**Comment by yjacolin** [comment]
agreed
