### ISSUE TITLE
[FEATURE] Use rendered symbol size as obstacle for point feature labels

### ISSUE THREAD

**Issue by qgis-feature-tracker** [qgis/QGIS-Documentation#680]
Original commit: https://github.com/qgis/QGIS/commit/7d600bdaed8e9daba3805020bdbdb850f13e4ac4 by nyalldawson

Previously, only the point feature itself was treated as an obstacle
for label candidates. If a large or offset symbol was used for the
point, then labels were allowed to overlap this symbol without
incurring the obstacle cost.

Sponsored by City of Uster

**Comment by SrNetoChan** [comment]
@nyalldawson Does this have implications on the GUI or in the way users use labels? Just to know if we need to add something in Documentation or not.

**Comment by nyalldawson** [comment]
@srnetochan no documentation required - it's transparent for users
