### ISSUE TITLE
Missing docs for "Save vector features to file" processing algorithm

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS-Documentation#6820]
## Description

Missing docs for "Save vector features to file" (native:savefeatures) algorithm added to the "Vector general" processing group with PR https://github.com/qgis/QGIS/pull/37894

Page URL:
https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/vectorgeneral.html

**Comment by DelazJ** [comment]
Duplicate of #5892
