### ISSUE TITLE
Sample dataset not available when installing QGIS

### ISSUE THREAD

**Issue by genbroad** [qgis/QGIS-Documentation#6823]
I have installed QGIS twice and at no point either time was I given the option to download the sample dataset for the tutorial.

**Comment by jef-n** [comment]
fixed in ccbf42f90d254aebd11adf87096dfa88bd2ab9af

**Comment by rduivenvoorde** [comment]
Or if you mean the 'Training manual' if you say 'tutorial', see: 
https://docs.qgis.org/3.16/en/docs/training_manual/foreword/intro.html#data
for download places.

If you mean our 'Manual', it is like Juergen proposes: https://github.com/qgis/QGIS-Sample-Data/archive/master.zip
