### ISSUE TITLE
Inasafe 5.0.1 error using in Qgis 3.16.9

### ISSUE THREAD

**Issue by zyandysta** [qgis/QGIS-Documentation#6824]
## Report Details

**Crash ID**: [496f1a59d6ba28477edb0290d2f562f6c84f8403](https://github.com/qgis/QGIS/search?q=496f1a59d6ba28477edb0290d2f562f6c84f8403&type=Issues)

**Stack Trace**
<pre>
QgsField::QgsField qgsfield.cpp:54
QgsFields::at qgsfields.cpp:186
QgsMemoryProvider::changeAttributeValues qgsmemoryprovider.cpp:626
QgsVectorLayerEditBuffer::commitChanges qgsvectorlayereditbuffer.cpp:542
QgsVectorLayer::commitChanges qgsvectorlayer.cpp:3404
meth_QgsVectorLayer_commitChanges sip_corepart10.cpp:117856
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyFunction_FastCallDict :
PyException_SetTraceback :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyException_SetTraceback :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyException_SetTraceback :
PyEval_EvalFrameDefault :
PyEval_EvalCodeWithName :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.9-Hannover
QGIS code revision: 9f8d2f7942
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

**Comment by DelazJ** [comment]
@zyandysta This repository is dedicated to issues on the QGIS documentation (https://docs.qgis.org). For application issues, you need to go to https://github.com/qgis/QGIS/issues.
Closing...
