### ISSUE TITLE
Substitution page doesn't find link for some grass icons

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#686]
It seems that some icons are not available [here]:(http://docs.qgis.org/testing/en/docs/documentation_guidelines/substitutions.html#grass-integration).
@blazek since you are GRASS man and I think you've done the PR so you may already have all files  (seems they are deleted in 330f63f082e691eaf1586912e0c7a8c2271500ed)
I'm not enough good at git to fix it so if you or anyone else can do it....

**Comment by blazek** [comment]
The deleted icons are no more used in the plugin and may be deleted from substitutions.

**Comment by DelazJ** [comment]
Ok. Thanks for the clarification.

**Comment by DelazJ** [comment]
@rduivenvoorde @diethard2 
I'm planning to fix this issue by removing the rows from the grass table in [Substitutions.rst file](https://github.com/qgis/QGIS-Documentation/blob/master/source/docs/documentation_guidelines/substitutions.rst). Should I also delete the corresponding rows in conf.py file, e.g. [L895](https://github.com/qgis/QGIS-Documentation/blob/master/source/conf.py#L895) which is more available in QGIS?
I'm asking this because there are some rows in the conf file ( and in resources/en/docs/common folder) that link to icons that are no longer used in QGIS. Should they be kept or is it a good practice to "clean" them?

**Comment by diethard2** [comment]
It is better to replace substitutions. I mean remove and add new ones. Makes it easier to use the icons (substitutions) in training manuals. 
Coming weekend I have some time to  fix it. 

Groetjes,
Diethard

**Comment by rduivenvoorde** [comment]
@DelazJ @diethard2 @dassau  yes, please clean up the conf.py file from any not used substitution please: it slows down the build. 
I'm even in favour for NOT using the substitutions, UNLESS it is an icon which is used in more then 3 places. My arguments for this are:
-1- to be able to put the (english) images not in the resources folder anymore, but in the source tree, and giving relative paths directly to it: this will make github render the images, hopefully making it easier for people to edit the docs directly in Github. I'll have to adjust the  build scripts for this AND we have to edit the sources for it to work though...
-2- my feeling is that having this huge list of substitutions slows down the build

Regards,
Richard
