### ISSUE TITLE
Styling with QML files not explained

### ISSUE THREAD

**Issue by walthaas** [qgis/QGIS-Documentation#6902]
## Description
Paragraph 2.4.10 point 2. 

> Load the style file advanced_levels_demo.qml provided in exercise_data/styles.

The style manager does not allow import of *.qml files, only XML files.  What is the process for importing a qml file?

Page URL:
https://docs.qgis.org/testing/en/docs/training_manual/basic_map/symbology.html

**Comment by DelazJ** [comment]
This can be done through the  `Style --> Load Style...` combobox at the bottom of the `Layer Properties` dialog. Will be added to docs.
