### ISSUE TITLE
[FEATURE] Feature limit support for feature requests

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#692]
Original commit: https://github.com/qgis/QGIS/commit/edb16d0014dcc0f9017c0711554dfb7aa7a51bb9 by nyalldawson

Limits the maximum number of features returned by the iterator.
Some providers (postgres, spatialite, MS SQL) pass the limit on
to the provider to result in faster queries.

**Comment by yjacolin** [comment]
@nyalldawson how user can setup the limit?

**Comment by nyalldawson** [comment]
This is for PyQGIS use only. Do you want examples for the cookbook?

**Comment by yjacolin** [comment]
If you have any, yes!

**Comment by lucacasagrande** [comment]
I will work on this one.
