### ISSUE TITLE
[FEATURE] oracle provider: add Feature limit support for feature requests (followup edb16d0)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#693]
Original commit: https://github.com/qgis/QGIS/commit/5e4312b13c42d76ed2ba246a180d0aa08ff15b4c by jef-n

Unfortunately this lazy coder did not write a description... :-(

**Comment by yjacolin** [comment]
@jef-n Is it something user can set up in QGIS? Or only available for Python cookbook? Thanks.

**Comment by jef-n** [comment]
@yjacolin same as #692 - just for oracle

**Comment by yjacolin** [comment]
thanks!

**Comment by havatv** [comment]
#692 has been closed, and setLimit is documented in the cookbook.  Closing.
