### ISSUE TITLE
[FEATURE] oracle provider: initial expression compiler support

### ISSUE THREAD

**Issue by qgis-feature-tracker** [qgis/QGIS-Documentation#694]
Original commit: https://github.com/qgis/QGIS/commit/65ee1839a6198297b012d819965f988e8685a2ad by jef-n

Unfortunately this lazy coder did not write a description... :-(

**Comment by yjacolin** [comment]
@jef-n Does it mean that we can use expression with an oracle layer?

**Comment by jef-n** [comment]
@yjacolin same as #675 - just for oracle

**Comment by yjacolin** [comment]
Thanks!
