### ISSUE TITLE
Incorect reference to toolbar "Attributes" for "Annotations"

### ISSUE THREAD

**Issue by tomass** [qgis/QGIS-Documentation#6951]
## Description

Page URL:
https://docs.qgis.org/3.16/en/docs/user_manual/introduction/qgis_gui.html#menu-bar
Under section for menu Edit->Add Annotation->Text Annotation (as well as other three annotation options) in Toolbar column current value is "Attributes" (while reference correctly points to annotation tools).
![paveikslas](https://user-images.githubusercontent.com/969513/134780244-12e69a5f-e6c1-4a2e-85f9-6312c159cffa.png)

_Attribute_ toolbar does not have annotation tools:
![paveikslas](https://user-images.githubusercontent.com/969513/134780252-b83f179c-f878-4636-bc6f-3b1767a8e762.png)

_Annotation_ tools are in _Annotation_ toolbar:
![paveikslas](https://user-images.githubusercontent.com/969513/134780651-7f31af69-ba83-48b6-aa72-6ec33c129260.png)

**Comment by DelazJ** [comment]
@tomass The docs is correct since you are referring to a 3.16 URL. In that release, annotations are in the Attributes toolbar.
The Annotations toolbar is a new feature in 3.21 and the move already has a report at #6936. So I'm closing.
