### ISSUE TITLE
Add few example to expression functions

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#700]
It'd be nice to have few examples of expression for each group of functions in http://docs.qgis.org/2.8/en/docs/user_manual/working_with_vector/expression.html

**Comment by yjacolin** [comment]
Could we close this issue? Or delay it?

**Comment by DelazJ** [comment]
Moved it to 2.16. I still think that it could be nice to improve this chapter with examples. 2.16 comes with new functions that could be addressed here.

**Comment by yjacolin** [comment]
I would like to finalize 2.16 this week-end so I moved this ticket to 2.18 milestone. We will close it later after adding more example after the confirmation of my PR.

**Comment by DelazJ** [comment]
Should we close this one? the aim was to have some practical examples for each group and afaics, it's not yet the case
