### ISSUE TITLE
Snapping to the currently digitized feature - shortcut 

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS-Documentation#7028]
the keyboard shortcut is `Ctrl + a` and not` Alt + a`

https://www.qgis.org/it/site/forusers/visualchangelog314/index.html#feature-snapping-to-the-currently-digitized-feature

**Comment by DelazJ** [comment]
@pigreco is this an issue with the changelog (hence qgis-website repo) or the documentation? If the latter, can you better explain and point to the problematic section? If the former, you can also help fix it (link at the bottom of the page)

**Comment by pigreco** [comment]
It's a problem I encountered in the 3.14 changelog, I don't know if the same wrong shortcut is used in the documentation.

![image](https://user-images.githubusercontent.com/7631137/140566233-a6ec2d3b-80c3-4c5a-acbb-1113e58e2b4b.png)

the animated gif should also be redone where `Alt + A` is superimposed, the correct shortcut is `Ctrl + A`

https://github.com/qgis/QGIS-Website/pull/944

**Comment by DelazJ** [comment]
If you look at the shortcuts section at https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/editing_geometry_attributes.html#the-advanced-digitizing-panel it seems they both are meant to do the same thing. Weird but that is...

**Comment by pigreco** [comment]
@DelazJ 
header of this table is incorrect (at least in windows) as only `Shift +` works
![image](https://user-images.githubusercontent.com/7631137/140602954-cac9c189-dab6-42ed-a851-4c5dc5d7ee24.png)

**Comment by DelazJ** [comment]
@pigreco I can not confirm. I tested on macos with QGIS 3.22  as well as Windows 10 (3.23 83b92e97, 3.16.13 a8618a94) and I can confirm that both `Alt+/Cmd+` and `Alt+/Ctrl+` automatically push in the padlock icon and lock the value you enter.

**Comment by DelazJ** [comment]
Closing then?
