### ISSUE TITLE
Stream Digitize documentation

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS-Documentation#7044]
Originally mentioned here 
https://github.com/qgis/QGIS/issues/45942#issuecomment-963500214

Seems there is not a requirement to mention "The tolerance of the tool affects the spacing between each created vertex when the tool is used with Advanced digitizing enabled." but instead it should say something about setting the tolerance using the following option 

![image](https://user-images.githubusercontent.com/4627073/140808596-a7643841-c326-44fa-92ae-a6f12e1795ef.png)

https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/editing_geometry_attributes.html#straight-curve-and-stream-digitizing

**Comment by DelazJ** [comment]
@antoniolocandro thanks for reporting. Do you want to fix it? You are already on the tool, tested it and know how that option affects it. It will be way faster to fix than expecting someone will rexperiment what you went through and provide a fix one day. Just hit the "edit on github" button at the top or the bottom left menu of the doc page and you are ready. Thanks.

**Comment by antoniolocandro** [comment]
Ok gave it a try, I couldn't add a screenshot as I think Ubuntu is used for the official ones
