### ISSUE TITLE
[FEATURE] Add N:M relation editing possibilities

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#705]
Original commit: https://github.com/qgis/QGIS/commit/be01b7eec5ec08069b731af7aca62d2b03bfbc40 by m-kuhn

This adds the possibility to manage data on a normalized relational
database in N:M relations. On the relation editor in a form, the tools
to add, delete, link and unlink work (also) on the linking table if a
relation is visualized as N:M relation.

Configuration is done through the fields tab where on the relation a
second relation can be chosen (if there is a suitable relation in terms
of a second relation on the linking table).
# Limitations

QGIS is not a database management system.

It is based on assumptions about the underlying database system. In
particular it expects
- A `ON DELETE CASCADE` or similar measure on the second relation
- Does not take care of setting the primary key when adding features.
  Either users need to be instructed to set them manually or - if it's a
  database derived value - the layers need to be in transaction mode
  (currently only activatable through the API)

**Comment by yjacolin** [comment]
> the layers need to be in transaction mode (currently only activatable through the API)
@m-kuhn is it still true (for 2.14)?

**Comment by m-kuhn** [comment]
Nope,

In 2.14, Automatically create transaction groups needs to be enabled in
the application settings (data sources or so).

In 2.16 this has been moved to project properties.
