### ISSUE TITLE
[FEATURE] Directly set class symbol color from context menu in legend

### ISSUE THREAD

**Issue by qgis-feature-tracker** [qgis/QGIS-Documentation#708]
Original commit: https://github.com/qgis/QGIS/commit/2026fce135d379605b0d5b2777dd20ebbf852707 by nyalldawson

Shows a color wheel widget in the menu, which allows you to
interactively edit the color for a classes' symbol.

**Comment by yjacolin** [comment]
See #709 for another issue close to this one and #1146
