### ISSUE TITLE
[FEATURE] Add geometry generator symbols

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#710]
Original commit: https://github.com/qgis/QGIS/commit/17f9d554f8a4375ae06af40521ffa3a012eac331 by m-kuhn

Unfortunately this lazy coder did not write a description... :-(

**Comment by m-kuhn** [comment]
The lazy coder left some information here http://www.opengis.ch/2015/12/10/geometry-generator-symbology/

**Comment by SrNetoChan** [comment]
@DelazJ Let me know if you want screenshots for this one.

**Comment by DelazJ** [comment]
@SrNetoChan I'll close this issue with #1737 but I think screenshot of kind of renderings is needed and can be made in a global perspective, hence #1738

**Comment by SrNetoChan** [comment]
I will review #1737 ASAP and, when it's ready, let's merge it.

I will contribute to #1738 as soon as I can, but would like to tackle blockers issues first.

**Comment by DelazJ** [comment]
Fixed in #1737
