### ISSUE TITLE
[FEATURE][QGIS-Server] showFeatureCount in GetLegendGraphic

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#711]
Original commit: https://github.com/qgis/QGIS/commit/f27e6c27b55c3292da81bfd209d3e1156f73f529 by rldhont

Add non standard parameter 'ShowFeatureCount' to add feature count in the legend.

**Comment by tudorbarascu** [comment]
@rldhont I tried testing it before writing about it and I couldn't make it work (my fault probably).
Are you able to provide a ``GetLegendGraphic`` request that works for you? (if it's tied to an external server, it would be perfect).
I'm trying to fill in examples on how to do it in the documentation.
Thanks

**Comment by tudorbarascu** [comment]
@rldhont I tried testing it before writing about it and I couldn't make it work (my fault probably).
Are you able to provide a ``GetLegendGraphic`` request that works for you? (if it's tied to an external server, it would be perfect).
I'm trying to fill in examples on how to do it in the documentation.
Thanks

**Comment by rldhont** [comment]
Hi @tudorbarascu 

As explain in the qgis changelog http://www.qgis.org/en/site/forusers/visualchangelog214/index.html#feature-showfeaturecount-in-getlegendgraphic, this feature needs a fake X server to work like Xvfb.
An issue is opened http://hub.qgis.org/issues/14272 and a pull request has been made https://github.com/qgis/QGIS/pull/2780 but this will probably not fxed before 3.0.

Regards,

**Comment by yjacolin** [comment]
So I move the ticket to 3.0. Thanks @rldhont and @tudorbarascu
