### ISSUE TITLE
unclear license

### ISSUE THREAD

**Issue by Joeperdefloep** [qgis/QGIS-Documentation#7116]
## Description

The license for the documentation is rather unclear. I would expect there to be a license in either the github page, or some discussion of the license somewhere else. That is: What is the license for the entire collection, that is not in any of the chapters. For example the Server Manual does not have anything on the license.

Page URL: https://docs.qgis.org/3.16/en/docs/index.html

The bottom of the page says Copyright by the QGIS project. However, individual parts are licensed differently:
User manual: GNU documentation 1.3+ https://docs.qgis.org/3.16/en/docs/user_manual/preamble/preamble.html
Server manual: unclear? 
Training manual: Creative Commons 4.0 https://docs.qgis.org/3.16/en/docs/training_manual/foreword/foreword.html#license
Gentle introduction: GNU documentation 1.2+ https://docs.qgis.org/3.16/en/docs/gentle_gis_introduction/preamble.html

So what is the over-arching license? I would be willing to help/PR if there is some consensus!

**Comment by DelazJ** [comment]
@Joeperdefloep Can you raise this issue in the qgis-community list, please? It would get more audience than here. Thanks

**Comment by Joeperdefloep** [comment]
Thanks for your response! Hmm, I subscribed but didn't receive a confirmation and thus couldn't post it yet... Let's see how this goes

**Comment by anitagraser** [comment]
Thanks for raising this issue! I've taken the liberty to post the question of the Server manual to the mailing list https://lists.osgeo.org/pipermail/qgis-community-team/2021-December/005981.html

**Comment by anitagraser** [comment]
Implemented in https://github.com/qgis/QGIS-Documentation/pull/7338
