### ISSUE TITLE
About 30 algorithms descriptions missing in QGIS 3.16 docs

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS-Documentation#7132]
## Description

About 30 algorithms descriptions are missing in QGIS 3.16 user manual.

This leads to opening a missing user manual Web page or a page with missing information when the user clicks on the Help button in the algorithm dialog window in QGIS 3.16.

This was probably caused by some PR not backported to the LTR branch.

I volunteer to integrate the 3.16 user manual with the missing algorithms description already present in the master branch, if there is a chance (as I hope) they will be merged in the documentation.

Considering that QGIS 3.16 will be the last LTR available for Windows 7 users and for Ubuntu 18.04 bionic and Debian 10 buster users, among the others, it could be worth to have an as complete as possible user manual for this version.

Missing algorithm description in the user manual: 

1. Cartography (#7266)
    - [x] Export atlas layout as image
    - [x] Export atlas layout as PDF
    - [x] Export print layout as image
    - [x] Export print layout as PDF

1. Database (#7266)
    - [x] SpatiaLite execute SQL (registered DB)

1. File tools
    - [ ] Create directory

1. Layer tools
    - [ ] Filter layers by type

1. Mesh
    - [ ] TIN Mesh Creation

1. Modeler tools (#7266)
    - [x] Conditional branch
    - [x] Raise exception
    - [x] Raise warning
    - [x] Save log to file
    - [x] Set project variable

1. Raster analysis (#7266)
    - [x Equal to frequency
    - [x] Greater than frequency
    - [x] Highest position in raster stack
    - [x] Less than frequency
    - [x] Lowest position in raster stack

1. Vector general (#7266)
    - [x] Extract Shapefile encoding
    - [x] Save vector features to file
    - [x] Set layer encoding

1. Vector geometry (#7266)
    - [x] Convert to curved geometries

1. Vector selection
    - [ ] Filter by geometry type

1. Vector tiles (#7256)
    - [x] Write Vector Tiles (MBTiles)
    - [x] Write Vector Tiles (XYZ)

1. GDAL | Raster miscellaneous (#7266)
    - [x] Viewshed

There are also the following algorithms flagged as deprecated for which the description is missing:

Raster analysis | Zonal statistics (in place)
Raster tools | Set style for raster layer
Vector general | Set style for vector layer
Vector geometry | Rectangles, ovals, diamonds (variable)

**Comment by roya0045** [comment]
@agiudiceandrea some are already done and merged previously.

**Comment by DelazJ** [comment]
Closing as 3.16 is no longer maintained
