### ISSUE TITLE
Enable LR/LTR link to the QGIS documentation

### ISSUE THREAD

**Issue by ponceta** [qgis/QGIS-Documentation#7145]
## Description
Hey! It would be handy to have an **ltr** or **current** tag for the qgis doc version :

https://docs.qgis.org/3.16/fr/docs/user_manual/
->https://docs.qgis.org/ltr/fr/docs/user_manual/

AS

https://docs.qgis.org/3.22/fr/docs/user_manual/
->https://docs.qgis.org/latest/fr/docs/user_manual/

OR

https://docs.qgis.org/3.23/fr/docs/user_manual/
->https://docs.qgis.org/testing/fr/docs/user_manual/

Especially when refering in side projects directly to the LTR version / documentation and avoid any version number in the links provided (hard to maintain)

**Comment by DelazJ** [comment]
Aren't latest + testing enough to manage this? We document only LTRs.
Isn't 3.22 also ltr and current? Let's say we are in march 2022: what version would you expect ltr or current to open?

**Comment by ponceta** [comment]
My problem is that actual LTR is 3.16 and it is the actual version used in many public entities and cannot be referenced without setting its specific number via the current or lr/ltr keyworld.

In march 2022 we will have to switch to 3.22 which would be the new LR/LTR to be. Therefore all 3.16 links referencing QGIS docs would have to change.

I'm open to any mean that could enable to reference the LR/LTR without referencing its specific version number.

**Comment by DelazJ** [comment]
Unless i still misunderstand your case, wouldn't reverting `latest` redirection from 3.22 to 3.16 solve your issue? meaning that we get

|  | until Feb 2022 | from Feb 22 to Feb  23 | from Feb 23 to Feb 24 |
|---|----|---|----|
| latest | 3.16 | 3.22 | 3.28 |
| testing | >3.22 | >3.22 | >3.28 |

The releases keep their shortcut during and only during their official ltr life. We ignore them if inactive ltr.
Or do you really think a new entry is necessary (you can swap latest and current/ltr logic in the following table but that new entry would last for 4 months max.)?

|  | until Feb 2022 | Feb 22 - Oct 22 | Oct 22 - Feb  23 | Feb 23 - Oct 23 | Oct 23 - Feb 24 |
|---|----|---|----|---|---|
| latest | 3.16 | 3.22 | 3.22 |3.28 | 3.28|
| current | 3.22 | 3.22 | 3.28 | 3.28 | 3.34 |
| testing | >3.22 | >3.22 | >3.28| >3.28 | >3.34 |

**Comment by ponceta** [comment]
Reverting latest redirection from 3.22 to 3.16 would solve my issue. A new entry is not required.

**Comment by DelazJ** [comment]
Done. I'll let you confirm and close this request.

**Comment by ponceta** [comment]
That's great thank you!
