### ISSUE TITLE
[FEATURE][QGIS Server] STARTINDEX param in WFS GetFeature Request

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#724]
Original commit: https://github.com/qgis/QGIS/commit/30b3b6856a2204dcc7cea0f769cde6ac8278e823 by rldhont

STARTINDEX is standard in WFS 2.0, but it's an extension for WFS 1.0 implemented in QGIS Server.

STARTINDEX can be used to skip some features in the result set and in combination with MAXFEATURES provides for the ability to use WFS GetFeature to page through results. Note that STARTINDEX=0 means start with the first feature, skipping none.

**Comment by yjacolin** [comment]
@rldhont does MAXFEATURES also implemented in QGIS Server for WFS 2.0 and WFS 1.0?

**Comment by yjacolin** [comment]
And thanks for your great description, I really copy-pasting such description directly into the documentation.

**Comment by rldhont** [comment]
@yjacolin QGIS Server does not yet implement WFS 2.0 so it is to prepare it.

**Comment by yjacolin** [comment]
@rldhont thanks.
