### ISSUE TITLE
Training Manual's Chapter 6.1.3

### ISSUE THREAD

**Issue by rootsmusic** [qgis/QGIS-Documentation#7282]
I'm having trouble with step 9 in the Training Manual's Chapter 6.1.3 ("[Saving a Dataset to Another CRS](https://github.com/qgis/QGIS-Documentation/blob/master/docs/training_manual/vector_analysis/reproject_transform.rst#-follow-along-saving-a-dataset-to-another-crs)").  (In step 1, [training_data.gpkg](https://github.com/qgis/QGIS-Training-Data/blob/release_3.16/exercise_data/training_data.gpkg) can be downloaded as a single file.)

I'm using QGIS 3.16.15 For Windows.  My screenshot for step 9 is below.
![image](https://user-images.githubusercontent.com/22034168/149546999-35ba7ce7-07f4-4c74-8c1d-dad92b57d6c2.png)

Note the numbers under "Extent (current: layer)" exceed the Coordinate Reference System's extent, which is specified in the lower left box in [the screenshot for step 8](https://github.com/qgis/QGIS-Documentation/blob/master/docs/training_manual/vector_analysis/img/CRSselector.png).  So please add a step to convert the extent of building_reprojected.shp to be reprojected within its CRS extents.

**Comment by roya0045** [comment]
Does mapbox studio only accepts some projections and not others? 

The extent only filters the data that is to be exported.

**Comment by rootsmusic** [comment]
No @roya0045, but Mapbox Studio requires extents to be between -360 and 360.

**Comment by roya0045** [comment]
Ok so the answer is yes and they only want geographic coords. I'd suggest you familiarize yourself more with gis data, and the software you use. Though the extent parameter could be more detailed in the doc.

**Comment by rootsmusic** [comment]
@roya0045 Since I'm using the Training Manual to learn QGIS, please refer me to training or instructions on how to convert to geographic coordinates in QGIS.  Thanks.

**Comment by rootsmusic** [comment]
Ok @roya0045, I'm learning QGIS from its Training Manual.  In [the screenshot for step 8](https://github.com/qgis/QGIS-Documentation/blob/master/docs/training_manual/vector_analysis/img/CRSselector.png), isn't the lower left box specifying the CRS's range of extent (which are much less than the extent of buildings_reprojected.shp)?

**Comment by DelazJ** [comment]
> Note the numbers under "Extent (current: layer)" exceed the Coordinate Reference System's extent

> Shouldn't the extent of buildings_reprojected.shp be within its CRS's extent

At this moment in your GUI, buildings_reprojected.shp is not created yet, right? And the current layer is not buildings_reprojected.shp (but buildings) in a CRS different from 32734. Values you see are not the ones your output will necessarily be within.
> which is specified in the lower-left box of the screenshot for step 8

Whatever CRS you pick in this dialog, its extent is displayed in geographic coordinates. Probably for comparison convenience. It does not mean that those are the bounding values of the coordinates used by data in the CRS itself.
> So please add a step to convert the extent of building_reprojected.shp to be reprojected within its CRS extents.

If building_reprojected.shp is correctly reprojected in its CRS, then it's already within its CRS extents. Nothing to add.
What you are requesting is a step to convert the data to maybe epsg:4326 to satisfy your import to mapbox. But this is not relevant for the exercise, and the reprojection process is already taught so you might be able to handle that yourself.

**Comment by rootsmusic** [comment]
> What you are requesting is a step to convert the data to maybe epsg:4326 to satisfy your import to mapbox.

Yes @DelazJ, Mapbox Studio requires reprojecting to EPSG:3857.  After reprojecting, I'm adding the reprojected GeoJSON into QGIS and the layer info is below.
![image](https://user-images.githubusercontent.com/22034168/150405548-39e37a08-8816-402e-a82f-1f2dccfab5ba.png)

Since its extent is still unacceptable to Mapbox, I'll ask StackOverflow about how to convert extent in QGIS.  However, I'm unsure how to clearly phrase my question because I'm unfamiliar with extent.

Is my question about converting layer extent from northing/easting values to geographic coordinates?  Or is my question about converting layer units from meters to degrees?  Thanks!
