### ISSUE TITLE
QGIS 3.22 Regular Points - Chapter 14.4.2

### ISSUE THREAD

**Issue by eboelcke** [qgis/QGIS-Documentation#7288]
##The Regular Points plugin has been changed in version 3.22. 
Old version
![image](https://user-images.githubusercontent.com/45123660/149801812-1a008f67-d568-4563-ae9a-a7d2b18cb698.png)
New Version
![image](https://user-images.githubusercontent.com/45123660/149802129-8ef0435a-0fa6-466d-af71-e2027c1cb3b6.png)
Consequently, the text probably has to be changed as:

- Input extent: Calculate from Layer forest_stands_2012.shp
- Point spacing 80.00 meters
- Check Use Point spacing
- Output Layer systematic_plots.shp
- Output CRS : ESPG: 3067
Furthermore, the current Regular Points plugin is supposed to produce a point vector, but it produces a multipoint vector. This would have consequences when trying to save the info to a gpx file resulting in a format error of the type that multipoint layers are not accepted by the gpx format.

Page URL: https://docs.qgis.org/3.16/en/docs/training_manual/forestry/systematic_sampling.html

**Comment by DelazJ** [comment]
>  Consequently, the text probably has to be changed as:

@eboelcke Do you wanna give it a try? It "only" takes hitting the "Edit on Github" button at the top of the page (or in the left bottom menu) and edit the text in the page that opens and save in the branch github created for you. No worry for formatting issues, if any; we could handle them together afterwards.
If you need details of how-to, https://docs.qgis.org/testing/en/docs/documentation_guidelines/first_contribution.html#alternative-1-use-the-edit-on-github-shortcut
> Furthermore, the current Regular Points plugin is supposed to produce a point vector, but it produces a multipoint vector.

Sounds like a bug imho. What is your exact version of QGIS? 3.22.3?
