### ISSUE TITLE
PYQGIS documentation wordwrap/scroll elimination

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS-Documentation#7297]
Would be nice if a scroll was not needed to view the complete method definition. It would make it easier to work with

![image](https://user-images.githubusercontent.com/4627073/150423513-0da8d7ef-5e7a-490e-8352-58247c3fa8f5.png)

**Comment by DelazJ** [comment]
Belongs to pyqgis repo and duplicates qgis/pyqgis#36. See also https://github.com/qgis/QGIS/issues/43690.
