### ISSUE TITLE
Variable Distance Buffer should be removed from QGIS docs

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS-Documentation#7299]
### Feature description

If you go to the docs it mentions the existence of variable distance buffer 
https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/modelertools.html#variable-distance-buffer 

I open processing and it is not present as I guess the functionality is now present in the normal buffer algorithm, however the algorithm is still reachable using the Python console

![image](https://user-images.githubusercontent.com/4627073/150224403-3f3a4238-54de-4d61-bbd2-5e08b38e2b81.png)

![image](https://user-images.githubusercontent.com/4627073/150225152-8d1a64a8-08c7-4985-89bd-4c5234cf8892.png)

### Additional context

Probably would be a good idea to not have deprecated algorithms present at least in the documentation if it is confirmed it should no longer be used as this would make new people come to the docs and find the methods. Alternatively it might be the case it is not being exposed in processing and it should be a bug but I suspect it has been left out for a reason

**Comment by felixfeckler** [comment]
Do we have a method yet for marking algorithm as deprecated?

**Comment by nyalldawson** [comment]
@felixfeckler in documentation? Or in qgis itself?

**Comment by felixfeckler** [comment]
@nyalldawson meant in the documentation, but just saw DelazJ solution

**Comment by DelazJ** [comment]
> in documentation? Or in qgis itself?

@nyalldawson Do we have such thing in QGIS itself? Any way to find if there is any other deprecated algorithm we are still documenting/exposing? Having a way to visually display to users that the alg they just open is deprecated may help, doesn't it?
