### ISSUE TITLE
Add example with multi filtering on wfs, server side

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#7309]
We have examples explaining how people can filter different layers when calling a wms. Could be nice to have few for wfs also. On the topic, there was recently this request https://www.mail-archive.com/qgis-user@lists.osgeo.org/msg50029.html. I think such info needs to ne in thé docs.

**Comment by pblottiere** [comment]
(I noted your ping in my other PR, I'll take a look to this one asap)

**Comment by DelazJ** [comment]
Thanks @pblottiere
