### ISSUE TITLE
Training Manual Excercise 8.4 - Update instructions for aligning rasters

### ISSUE THREAD

**Issue by nkleinbaer** [qgis/QGIS-Documentation#7342]
## Description

In Training Manual Excercise 8.4 users are instructed to use the `export > save as` dialog to reproject, resample, and align two rasters. This results in resampling artifacts in the hillshade produced in a subsequent step (leading to confusion for some users following the tutorial, [for example this recent post in /r/qgis](https://www.reddit.com/r/QGIS/comments/sl9q7o/hillshade_from_90m_srtm_looks_fine_after/)). More generally, I would argue this is not best practice, as the export dialog does not give a choice of resampling method (defaulting to nearest neighbor): it would be better to demonstrate using the `Warp (Reproject)` tool instead.

Page URL: https://docs.qgis.org/3.16/en/docs/training_manual/complete_analysis/analysis_exercise.html#align-the-rasters

**Comment by roya0045** [comment]
Suggestions are good, but to have any changes in the documentation it's better to do it yourself and propose them with a PR instead of hoping one of the few contributors will have the free-time to do so in a way that you find adequate.

The path of the source file is https://github.com/qgis/QGIS-Documentation/blob/master/docs/training_manual/complete_analysis/analysis_exercise.rst

**Comment by nkleinbaer** [comment]
Thank for the feedback, @roya0045. That's exactly what I intended on doing, I just wasn't clear if I should open an issue first and then PR, or skip the issue and jump straight to the PR.

**Comment by roya0045** [comment]
> Thank for the feedback, @roya0045. That's exactly what I intended on doing, I just wasn't clear if I should open an issue first and then PR, or skip the issue and jump straight to the PR.

Thanks! I think it doesn't matter too much if it has an issue or not. Updating or improving things is valuable enough in itself.
