### ISSUE TITLE
[FEATURE] Allow definition of rendering order for renderers

### ISSUE THREAD

**Issue by qgis-feature-tracker** [qgis/QGIS-Documentation#736]
Original commit: https://github.com/qgis/QGIS/commit/73ba0e805ac720e245a5e4308a52e8bd19d11f03 by m-kuhn

This allows defining the order in which features are processed by
renderers.

**Comment by SrNetoChan** [comment]
@DelazJ Trying to finish this task. I realize that this appear scattered across the document figures. I think we could create a new figure to illustrate the layer rendering menu, and remove it (close it) in all other style renderer figures.

What do you think?

**Comment by DelazJ** [comment]
@SrNetoChan Do you mean that for each style screenshot (single, categorized...), we'll have the "Layer rendering" part collapsed (as done in http://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/vector_properties.html#figure-symbology-2)?
If i understood you well, then yes I do agree. And I think for standardization, we can also keep reduced the tab panel for all screenshots.

When I asked for a screenshot for this issue, I was thinking about the "Define order" dialog but I'm no more sure it's useful. A single figure of the Rendering menu as proposed can be enough for the whole [section](http://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/vector_properties.html#layer-rendering).

Ah, I also remarked that Heatmap style doesn't have screenshot. Should I open a ticket or will you take care of it?
Thanks

**Comment by SrNetoChan** [comment]
@DelazJ Yes, I meant that. Each style with the layers rendering collapsed, and an extra image just for that group options (including Define Order).

About the reducing the tab panel, I was thinking in keep the panel full size (icon + text) for the first figure on each tab, and only icon for the next images on the same tab.

I will had a figure for the heatmap no need to create a new issue I'm going to take care of that now.
