### ISSUE TITLE
Outputs of processing algorithms should honor default setting

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS-Documentation#7380]
### Feature description

It seems that in all processing algorithms the output is stated as a default 'temporary layer' , for instance check the buffer part
https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/vectorgeometry.html#buffer

Now in theory when an optional parameter is not provided the default value is to be used, or at least that is how it works for the other defaults. So if the output is not defined then temporary layers should be created automatically without the need of specifying that a temporary output is to be used.

### Additional context

Error raised
![image](https://user-images.githubusercontent.com/4627073/149844494-392f1dce-bc6f-401f-a1ea-0f2abd813409.png)

I added the default as per the documentation now no error shown and works ok
![image](https://user-images.githubusercontent.com/4627073/149844536-842008b4-ddc2-4f9a-b3f7-32c44df3c02b.png)

**Comment by DelazJ** [comment]
Hi @antoniolocandro 
Indeed, as @alexbruy pointed out, we mainly document algs based on the GUI.
There's a section explaining how things work from the console (https://docs.qgis.org/testing/en/docs/user_manual/processing/console.html#calling-algorithms-from-the-python-console - might need a bit of structure for readability) and you'd find that it's stated near the end of the section
> For output data objects, type the file path to be used to save it, just as it is done from the toolbox. If the output object is not specified, the result is saved to a temporary file (or skipped if it is an optional output).

This description was suggested by @nyalldawson  at https://github.com/qgis/QGIS-Documentation/pull/2797#discussion_r211427955. If I understand correctly: unless buffer output is an optional parameter, your first code should be fine. An issue in the code?

**Comment by antoniolocandro** [comment]
Ok, well the thing was that the OUTPUT is actually not an optional parameter from the console but in the GUI it is as the default is the TEMPORARY LAYER, for me the console should work the same if I do not specify anything then a TEMPORARY LAYER like defined in the GUI should be the result in this way the GUI and the console are aligned for the documentation, If this is not the case and I guess from the replies it isn't is there a statement letting people know that console requires explicit definition of the outputs?

**Comment by antoniolocandro** [comment]
Will close as this seems to be just my personal preference instead of something that may be beneficial for the wider community
