### ISSUE TITLE
QGIS 3.16 training data

### ISSUE THREAD

**Issue by Tengqgis** [qgis/QGIS-Documentation#7391]
## Description

Page URL:

**Comment by Tengqgis** [comment]
The exercise data is incomplete.  Please kindly help with the complete data set

**Comment by DelazJ** [comment]
@Tengqgis Can you be more specific on what is missing please?

**Comment by Tengqgis** [comment]
I don't have the shapefiles folder that are required for the basics of the
training manual. The folders in the zip folder were:
Forestry
Forms
Grass
More_analysis
Network analysis
Plugins
Postgis
Processing
an example qgis file
and a land use sqlite file

**Comment by DelazJ** [comment]
@Tengqgis have you solved this issue? I tried and could download everything.

**Comment by DelazJ** [comment]
No feedback. Closing.
