### ISSUE TITLE
OAuth2 requests documentation

### ISSUE THREAD

**Issue by molakos** [qgis/QGIS-Documentation#7422]
Docs version: 3.22
Installed QGIS version: 3.22

## Description
Hi there!

I've been trying to write a script to fetch some data from our own API which is secured with Auth0 (oauth2). In the documentation I found some guidlines how to achieve that, but that is outdated.

Page URL: [14.4 Adapt plugins to use Authentication infrastructure](https://docs.qgis.org/3.22/en/docs/pyqgis_developer_cookbook/authentication.html?highlight=authorization#id22)

The problem is that the suggested code for `NetworkAccessManager` ([link](https://github.com/rduivenvoorde/pdokservicesplugin/blob/master/networkaccessmanager.py)) is broken, due to a change in the core codebase which was delivered 4 years ago... ([read here about the issue](https://issues.qgis.org/issues/17384))

At this moment in time anyone who would like to make a request with oath2 authentication will face the same error:

```
plugins\pdokservicesplugin\networkaccessmanager.py", line 190, in request
QgsAuthManager.instance().updateNetworkRequest(req, self.authid)
AttributeError: type object 'QgsAuthManager' has no attribute 'instance'
```

I would kindly ask some more detailed documentation on how to write custom http requests which requires oauth2.

**Comment by DelazJ** [comment]
> The problem is that the suggested code for NetworkAccessManager ([link](https://github.com/rduivenvoorde/pdokservicesplugin/blob/master/networkaccessmanager.py)) is broken

@rduivenvoorde do you know what could be a replacement for this broken link?

**Comment by rduivenvoorde** [comment]
For what I see the link is ok, it is just that that code is not uptodate anymore with current code base...
So if you try in QGIS in the Python console:
```
QgsAuthManager.instance()
```
You indeed see that instance is not there anymore.
But reading the example code here: https://docs.qgis.org/3.22/en/docs/pyqgis_developer_cookbook/authentication.html?#init-the-manager-and-set-the-master-password

I says that you should use `QgsApplication.authManager()` instead, that is the endpoint to use (like in the docs):

```
authMgr = QgsApplication.authManager()
authMgr.authenticationDatabasePath()
```

**Comment by DelazJ** [comment]
> For what I see the link is ok, it is just that that code is not uptodate anymore with current code base...

Yes, indeed. A typo: Out of date **code**.
I barely understand half of these so, what do we do for the docs? remove the section referring to pdok?
If someone has a fix, it would be appreciated. Thanks

**Comment by rduivenvoorde** [comment]
@DelazJ there is actually no reference to pdok, that link points to one of my plugins in which I use an old boundless python script to easier do networking. @molakos pointed to docs about that, but for what I can see that should work. Else please add some code here which shows it is not.
Closing this as (for what I know it is not an issue in the docs (other then that there is no copy/paste code for oauth.

**Comment by molakos** [comment]
Hello, sorry for my late reaction. 

@DelazJ I agree with @rduivenvoorde that this is an issue on the docs rather the code of the mentioned scrip. Altough I think that the docs still should be updated in regards of the [14.4 Adapt plugins to use Authentication infrastructure](https://docs.qgis.org/3.22/en/docs/pyqgis_developer_cookbook/authentication.html?highlight=authorization#id22).

Honestly, I would remove that section entirelly. The ideal solution would be to write a new doc entry where you would paste some example code which will show how can one use authorized requests based on your configured auth settings.

Based on [this](https://github.com/QGIS-Contribution/QGIS-resourceSharing/blob/master/resource_sharing/network_manager.py) I wrote my network manager which fits my own needs (I have to fetch data from our own API with GET requests and then parse it as JSON). Please note, that this is my first time writing pyQgis code in my life so validation should be required on top of it. But I can state, that the code itself works.

If it is going to be any help in your docs, feel free to use it as an example.

```python
import json
import logging
import urllib

from qgis.core import QgsNetworkAccessManager, QgsProcessingException, QgsApplication
from qgis.PyQt.QtCore import QCoreApplication, QUrl
from qgis.PyQt.QtNetwork import QNetworkReply, QNetworkRequest

LOGGER = logging.getLogger("QGIS Resource Sharing")


class NetworkManager(object):
    """Class to get the content of a file with a given URL."""
    def __init__(self, url: str, auth_cfg: str = None):
        self._network_manager = QgsNetworkAccessManager.instance()
        self._auth_manager = QgsApplication.authManager()
        self._network_finished = False
        self._network_timeout = False
        self._url = url
        self._reply = None
        self._auth_cfg = auth_cfg
        self._content = None

        if auth_cfg:
            is_auth_configured = self._auth_cfg in self._auth_manager.configIds()
            if not is_auth_configured:
                raise QgsProcessingException('Authorization not configured!')

    @property
    def content(self):
        return self._content

    @property
    def network_finished(self):
        return self._network_finished

    @property
    def network_timeout(self):
        return self._network_timeout

    def fetch(self, params: dict, content_type: str):
        """Fetch the content (in the background).
        :return: (status, error message)
        :rtype: (boolean, string)
        """
        # Initialize some properties again
        self._content = None
        self._reply = None
        self._network_finished = False
        self._network_timeout = False

        encoded_params = urllib.parse.urlencode(params)
        url = f'{self._url}?{encoded_params}'

        request = QNetworkRequest(QUrl(url))
        request.setHeader(QNetworkRequest.ContentTypeHeader, content_type)

        request.setAttribute(
            QNetworkRequest.CacheLoadControlAttribute, QNetworkRequest.AlwaysNetwork
        )

        LOGGER.info("Update request with auth_cfg %s" % self._auth_cfg)
        updated, request = self._auth_manager.updateNetworkRequest(request, self._auth_cfg)

        self._reply = self._network_manager.get(request)
        self._reply.finished.connect(self.fetch_finished)
        self._network_manager.requestTimedOut.connect(self.request_timeout)

        while not self._reply.isFinished():
            # noinspection PyArgumentList
            QCoreApplication.processEvents()

        # Finished
        description = None
        if self._reply.error() != QNetworkReply.NoError:
            status = False
            description = self._reply.errorString()
        else:
            status = True
            content_raw = self._reply.readAll()
            self._content = json.loads(str(content_raw, "utf-8"))

        self._reply.deleteLater()

        return status, description

    def fetch_finished(self):
        """Called when fetching metadata has finished."""
        self._network_finished = True

    def request_timeout(self):
        """Called when a request timeout signal is emitted."""
        self._network_timeout = True
```
