### ISSUE TITLE
Wondering if nesting project is the correct term

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS-Documentation#7428]
From the documentation 
https://docs.qgis.org/3.22/en/docs/user_manual/introduction/general_tools.html#nesting-projects

However after trying the feature it seems that what it does is embedding the layer and not the project which may include different things like variables, layouts, etc. 

Should it be nesting or embedding layers from external projects a more appropriate term?

***Nesting layers from external projects***

**Comment by DelazJ** [comment]
Embedding might probably be better, the action label as well as the whole description use that word.

**Comment by antoniolocandro** [comment]
I agree, it will make it more comprehensible for readers

**Comment by PhilipAlbrecht** [comment]
Ok so we go for "Embedded Layers" i guess?
