### ISSUE TITLE
[FEATURE] Add color wheel and edit symbol shortcuts to style menu

### ISSUE THREAD

**Issue by qgis-feature-tracker** [qgis/QGIS-Documentation#744]
Original commit: https://github.com/qgis/QGIS/commit/974cc35759bc46a84c2d462fa0faf8cfbe079528 by nyalldawson

...for vector layers with single symbol renderer. This completes
earlier work where symbols from categorized/graduated/rule based
renderers can be quickly changed through the legend item context
menu.

**Comment by yjacolin** [comment]
Link to #706
