### ISSUE TITLE
Apply to join the list of Translators

### ISSUE THREAD

**Issue by xBcai** [qgis/QGIS-Documentation#7456]
At present, more than 3000 entries have been translated

Language: Chinese (Simplified)
Contributors: Xu Baocai

![IMG_20220401_123111](https://user-images.githubusercontent.com/66826351/161196773-b414f22a-0d18-4547-a702-be73e94f1ebf.jpg)
![IMG_20220401_123202](https://user-images.githubusercontent.com/66826351/161196793-f97c483b-1373-41f4-9dc5-da71d78a3fe5.jpg)

**Comment by DelazJ** [comment]
@xBcai can you open a pull request please? From the translator HTML page, expand the bottom left menu and click on "Edit on github": you should create a copy of the doc and be able to edit that page, as you want. If necessary, you can find more details in the documentation guidelines or ask here.

**Comment by xBcai** [comment]
ok
