### ISSUE TITLE
Missing Edit in place documentation

### ISSUE THREAD

**Issue by baswein** [qgis/QGIS-Documentation#7487]
## Description
The Edit in place checkbox and text is missing from these tools in the vector geometry section: Affine, Covert To Curved Geometries, Extract Specific Vertices, Extract Vertices, Force Right Hand Rule, Geodesic Line Split at antimeridian and, Split by max length. I first noticed that the Convert to Curve was missing and then double check them by looking at the tools that were available when I had edit in place selected with a point, line, and polygon layer. Some of them such as Extract Vertices I can't actually get to work because they require a line or polygon input but only work as edit in place on point geometries. But this is also true of some others such as Centroids that are already tagged as edit in place so maybe I'm missing something. 

I have made the changes and have a pull request ready but wasn't sure if it is best practice to add an issue first. If anyone has any guidance on that let me know. 

Thanks   

Page URL: https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/vectorgeometry.html

**Comment by DelazJ** [comment]
> I have made the changes and have a pull request ready but wasn't sure if it is best practice to add an issue first. If anyone has any guidance on that let me know.

Afaict there is no particular rule about opening a report before a PR. I'd say it depends on whether you think the issue might need some discussion before a PR could be finished. Otherwise IMHO explaining the rationale when opening the PR could be enough.
>  Some of them such as Extract Vertices I can't actually get to work because they require a line or polygon input but only work as edit in place on point geometries.

This is because the output has another geometry type and can't be pushed back to the input layer. "Edit in place" needs input and output layers to have the same geometry.

**Comment by DelazJ** [comment]
Do you thin we should add the supported geometry type next to the checkbox? e.g. `only with point layer`.

**Comment by baswein** [comment]
> > Some of them such as Extract Vertices I can't actually get to work because they require a line or polygon input but only work as edit in place on point geometries.
> 
> This is because the output has another geometry type and can't be pushed back to the input layer. "Edit in place" needs input and output layers to have the same geometry.

Yes - so for Centroids (which is currently tagged as edit in place) you can run it on a point layer in edit in place mode because it produces a point layer. But there is no functional use because the centroid of a point is the point. I can imagine that there might be the possibility of using the expression builder to get centroids of features on other layers and add them to the current layer but I can't figure out how to do that. 
Should we be documenting a useless function?    
**Update- Nevermind you can use it if you have a multipart point file it will give you the centroid of the parts.**
Extract Specific vertices will give you the parts you identify. 
Extract vertices will give you a feature for each part. 
Point on surface gives you the first vertex. 

>Do you thin we should add the supported geometry type next to the checkbox? e.g. (only with point layer).
Sounds good to me. I'll make those changes.

**Comment by baswein** [comment]
Ok- I updated it so they describe the geometry types they work with. Looking at my pull request it looks like it pulled in the edits I made last week as well and I can't figure out how to delete them. Sorry about that I think I wasn't using the branch correctly last week but am now.
