### ISSUE TITLE
Documentation Suggestion: Desktop shortcut documentation -> add the full list of default shortcuts for all systems

### ISSUE THREAD

**Issue by playmobilmeister** [qgis/QGIS-Documentation#7510]
I have been looking forever for a comprehensive list of all of the default keyboard shortcuts for all of the 3 major OS (Windows, Mac & Linux) inside the documentation for version 3.22 and outside of it, but I couldn't find anything official. I am aware that anyone using the software is able to export a list for her own system, as described [here](https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html#keyboard-shortcuts), but I am looking for shortcuts to other OS as well, not just the one that I am using currently. Am I missing something ?

**Comment by DelazJ** [comment]
No, there is no place with full list of the shortcuts in the docs.
Regarding OS specificities, afaict there's nothing else than replacing `Ctrl` with `Cmd` when switching to macos.

**Comment by DelazJ** [comment]
I'm not convinced this request needs to be addressed by the docs:
- you can export the list of shortcuts https://docs.qgis.org/3.22/en/docs/user_manual/introduction/qgis_configuration.html#keyboard-shortcuts (and adaptation to other OS particularities should be straight forward)
- there is a list of top functions in https://docs.qgis.org/3.22/en/docs/user_manual/introduction/qgis_gui.html with their default shortcuts
- it would mean a second list to maintain and keep up-to-date (there's no way to get notified in case of new/updated shortcuts)
- I feel like this has a really low audience...

I'd suggest we close this.
