### ISSUE TITLE
[FEATURE]: Zoom to feature with right-click in attribute table

### ISSUE THREAD

**Issue by qgis-feature-tracker** [qgis/QGIS-Documentation#752]
Original commit: https://github.com/qgis/QGIS/commit/f815ebc86bcaf073bb929924a511ab58ffd6cd8e by mhugent

Unfortunately this lazy coder did not write a description... :-(

**Comment by purplexed** [comment]
Merged to Master branch:
https://github.com/qgis/QGIS-Documentation/pull/827
