### ISSUE TITLE
Mac 地图合成时，报错Error:Proj:proj_create_from_database:cannot find proj.db

### ISSUE THREAD

**Issue by jlw526** [qgis/QGIS-Documentation#7533]
## Description
<img width="1004" alt="d08988258d959de26fe79c702748d7a" src="https://user-images.githubusercontent.com/46257960/165909124-5314ed72-9b16-4a11-8f1c-fa6dc6fbc4e8.png">

**Comment by roya0045** [comment]
Wrong place to ask and not enough info for a proper bug ticked. Raise the issue in the qgis repo or in the mailing services.
