### ISSUE TITLE
Working with relations

### ISSUE THREAD

**Issue by ponceta** [qgis/QGIS-Documentation#7558]
## Working with relations

Relations are essential for GIS analysis and data query.

Nowadays their documentation is burried in QGIS user manuel under the 
edit vector data
 - Working with the attribute table
 - - item 6 working with relations
 - - -  item 46 defining 1-n relation

https://docs.qgis.org/3.22/en/docs/user_manual/working_with_vector/attribute_table.html#id46

It would be good IMHO to raise it a bit higher (1 or 2 levels)

Section [15.2.6. Creating one or many to many relations](https://docs.qgis.org/3.22/en/docs/user_manual/working_with_vector/attribute_table.html#id42)

Could be either a full section 
16. Working with relations

or a main subsection of working with vector data

15.3 / 15.4 considering if we want to have it before or after 

Page URL:

https://docs.qgis.org/3.22/en/docs/user_manual/working_with_vector/attribute_table.html#creating-one-or-many-to-many-relations

**Comment by DelazJ** [comment]
@ponceta See also #6205. No opinion against. Feel free to propose a PR.
