### ISSUE TITLE
[FEATURE] Postgres provider PKI authentication (plus fixes #13841)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#756]
Original commit: https://github.com/qgis/QGIS/commit/5f3ca88a84766daceba57c89187ce942a964669f by dakcarto
Merge pull request #2674 from boundlessgeo/postgis-pki-pr

[FEATURE] Postgres provider PKI authentication (plus fixes #13841)

**Comment by SrNetoChan** [comment]
Can we merge this issue with #645? @dakcarto

**Comment by yjacolin** [comment]
This is a little bit different imho. Bu probably when writer will take care of the first, he can manage the second one.

**Comment by dakcarto** [comment]
@yjacolin and @SrNetoChan, yes #645 needs handled first, and this can be added to the Postgres connection docs, and linked back to auth system docs.
