### ISSUE TITLE
Training Manual Section 3.2.12

### ISSUE THREAD

**Issue by alexbruy** [qgis/QGIS-Documentation#761]
Ticket "moved" from QGIS redmine https://hub.qgis.org/issues/10587

It is impossible to follow the instructions in the manual. The whole section needs correcting and more detail. Don't assume expert knowledge of these programs.
0) On Page 42, provide the URL to the Inkscape website, so the program can be downloaded.
1) On page 44, there are no instructions on how colours of the created object are to be changed
a) assume that Fill has to be changed to "Pale grey-blue". To an expert graphics designer it may be obvious how to set this colour, so what is it's RGB value?
b) assume that Stroke Paint sets the colour of the border
c) assume that Stroke Style, the width needs to be changed to something, such as 0.4??
2) On Page 45, so where is the Line tool?
3) On page 46, instructions are inadequate.
a) I guess that in QGIS that another Symbol Layer needs to added?
b) And then change the symbol layer type to SVG fill?
c) And then click on the three dots button in the bottom RH corner, and then browse to the saved SVG file?
4) So what is supposed to happen next? no symbol is displayed.
5) Page 47 - yes, but how, an explanation would be nice.
6) Page 48 - I wish

**Comment by DelazJ** [comment]
This one wasn't easy :(

0-  Good point. Done
1- Though things are not really really precise in the doc, people are somehow adults so I assume they can figure out what a somehow pale grey blue looks like (there's a screenshot to show what might look their change). Adding to that the fact that user is free to choose the color he wants... --> No RGB is added in the PR nor a thickness value but few precision on what does each tab
2- Not mandatory but a screenshot could be useful. Improved meanwhile how to use it and add an info to find it.
3- Yes, almost guess well. So should all these basic steps be written? I didn't follow the Training manual but aren't some basis required (and supposed to be learned in previous lessons)? --> Actually this is taught in the two first sections of this lesson (how to change color and symbol structure)
4- added precision
5- The next screenshot shows the dialog for this
6- ... Me too
