### ISSUE TITLE
Add a ProjectReadFlags example for QgsProject.read method

### ISSUE THREAD

**Issue by roya0045** [qgis/QGIS-Documentation#7634]
## Description

I always forgot how to handle flags in python and the only example I could find was in this issue report https://github.com/qgis/QGIS/issues/41209

Having a similar example somewhere would be nice to showcase the use of flags and how to create them in python.

**Comment by DelazJ** [comment]
@roya0045 since you know what it is about, it could be nice if you provide the fix...!? Thanks.

**Comment by roya0045** [comment]
@DelazJ Yep I'll try to do it soon, I don't mind this ticket having it to be a reminder for myself. I would like to do more docs but time is limited.
