### ISSUE TITLE
Raster calculator output problem

### ISSUE THREAD

**Issue by farissetiawan6** [qgis/QGIS-Documentation#7638]
I have a problem processing the image. I have the image of the rgb drone. I cultivate to find out the vegetation index but the result is only half the size. can anyone help? thanks.
![1](https://user-images.githubusercontent.com/99633837/174212151-d05491e3-b61c-4f27-819f-ca37eb38b812.PNG)
input image
![2](https://user-images.githubusercontent.com/99633837/174212156-0137b443-1aad-4887-999b-b8fb590fd3b5.PNG)
output raster calculator

**Comment by DelazJ** [comment]
I'm afraid there is not enough information to get valuable help: what tool(s) you use, what settings, QGIS version...?
Anyway, the best place to ask for help is on the QGIS user mailing list (see [support channels](http://qgis.org/en/site/forusers/support.html)). This place is the repository to manage the documentation writing.
Thanks for your understanding. Closing...
