### ISSUE TITLE
Errors in the Processing model

### ISSUE THREAD

**Issue by alexbruy** [qgis/QGIS-Documentation#765]
Moved from QGIS redmine https://hub.qgis.org/issues/12903

Model https://github.com/qgis/QGIS-Documentation/blob/master/source/docs/training_manual/exercise_data/processing/iterative/hypso_slope.model
from training manual returns errors on several variables (min, max, etc.)

**Comment by DelazJ** [comment]
@alexbruy @pcav Is the model wrong or the data? Anything to do to fix this? Note that data are now in https://github.com/qgis/QGIS-Training-Data/tree/master/training_manual_data

**Comment by havatv** [comment]
In https://github.com/qgis/QGIS-Training-Data/blob/master/exercise_data/processing/iterative
there is no model with suffix ``model3``, only with suffix ``model``. I guess this means that the model has not been updated to work in QGIS 3 Processing.

**Comment by havatv** [comment]
@DelazJ, I tried https://github.com/qgis/QGIS-Training-Data/tree/master/training_manual_data ,
but that returned a 404 message.  I could only find the "exercise_data" referenced in my previous post.  Are there any other training datasets for QGIS 3?

**Comment by DelazJ** [comment]
https://github.com/qgis/QGIS-Training-Data/tree/v2.0/exercise_data

**Comment by havatv** [comment]
> https://github.com/qgis/QGIS-Training-Data/tree/v2.0/exercise_data

I have seen that one, but the "v2.0" made me think it was data for QGIS 2... :-)

**Comment by DelazJ** [comment]
no, that was v1.0 ;)
