### ISSUE TITLE
The training exercise data is incomplete. The landuse.sqlite database does not exist.

### ISSUE THREAD

**Issue by GeoWashingto** [qgis/QGIS-Documentation#7650]
## Description

Page URL:

**Comment by DelazJ** [comment]
@GeoWashingto A local issue. The file is in the [repository](https://github.com/qgis/QGIS-Training-Data). Try to download single file or the repo, or provide more information on your context (OS, browser, any error message,...)

**Comment by DelazJ** [comment]
File is there and still works. Closing.

**Comment by GeoWashingto** [comment]
Thank you! Per my previous email to you, I figured out what I was doing
wrong and was able to access the file. Have a good day.
*"*

**Comment by GeoWashingto** [comment]
Thank you for your prompt response. I am using Windows 10, QGIS 3.22, get
same error message whether I download using Firefox or Google Chrome. Am
new to QGIS, not a developer. Error message attached below.
