### ISSUE TITLE
missing image in vector_properties.rst

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS-Documentation#766]
@junek @dassau  I think you added this text in the docs:

https://github.com/qgis/QGIS-Documentation/blob/master/source/docs/user_manual/working_with_vector/vector_properties.rst

around line 205 (see the todo there)

but we get a build error because of the fact that symbol_data_defined_edit.png image is missing

Do you have this image maybe on your disk, and are able to add it. 
I changed the text temporarily (putting the wrong image there) to fix the warning.

Please change back to the right images

**Comment by dassau** [comment]
We need to create a new figure for that. Larissa and me haven't found symbol_data_defined_edit.png locally here - sorry.

**Comment by SrNetoChan** [comment]
I will, ASAP.

**Comment by SrNetoChan** [comment]
@dassau @junek Please confirm if the image at #771 is what you have imagined.
