### ISSUE TITLE
QGIS-Server Documentation General Issues

### ISSUE THREAD

**Issue by AID-PMBD** [qgis/QGIS-Documentation#7749]
First of all thank you for maintaining an open source software like qgis and maintaining an excessive documentation. However, it seems like the installation instructions for QGIS-Server on Ubuntu contains some outdated informartion and is lacking additional information. In the following a list of issues I have found so far.

# Issue 1 - Apache HTTP Server Virtual Host file content

Page URL: https://docs.qgis.org/3.22/en/docs/server_manual/getting_started.html#httpserver

When following the instructions and inserting the following line in the virtual host file the apache2 process is not restartable, I am not sure if the syntax is wrong or what's exactly the issue here but it simply doesn't work.

```
 # default QGIS project
  SetEnv QGIS_PROJECT_FILE /home/qgis/projects/world.qgs
```

# Issue 2 Xvfb Configuration with Apache

Page URL: https://docs.qgis.org/3.22/en/docs/server_manual/getting_started.html#with-apache

The following is stated in the "With Apache" section for the Xvfb:

**"**_Then you can configure the DISPLAY parameter._

_With Apache you just add to your FastCGI configuration (see above):_

_FcgidInitialEnv DISPLAY       ":99"_**"**

It is absolutely not clear where to set this configuration and since there are multiple sections above it is also unclear to which section this refers to. For example I tried to add this to the virtual host config file where it causes an error that crashes apache. It would be great if this could be further specified.

**Comment by DelazJ** [comment]
> Page URL: https://docs.qgis.org/3.22/en/docs/server_manual/getting_started.html#httpserver

>When following the instructions and inserting the following line in the virtual host file the apache2 process is not restartable, I am not sure if the syntax is wrong or what's exactly the issue here but it simply doesn't work.

>```
>  # default QGIS project
>  SetEnv QGIS_PROJECT_FILE /home/qgis/projects/world.qgs
> ```

@AID-PMBD What is your operating system? Linux? And have you copied the project file to that path as suggested at the end of the previous section https://docs.qgis.org/3.22/en/docs/server_manual/getting_started.html#installation-on-debian-based-systems?
> It is absolutely not clear where to set this configuration and since there are multiple sections above it is also unclear to which section this refers to. For example I tried to add this to the virtual host config file where it causes an error that crashes apache. It would be great if this could be further specified.

Indeed, it looks unclear. I _thought_ it referred to [fastcgi-wrappers](https://docs.qgis.org/3.22/en/docs/server_manual/getting_started.html#fastcgi-wrappers) but that is a nginx subsection so would probably not apply. Browsing [older docs](https://docs.qgis.org/3.10/en/docs/user_manual/working_with_ogc/server/getting_started.html#xvfb) reveals that it should be fcgid and not fastcgi, typo inserted while migrating the page to a dedicated server document. Fix at #7781
