### ISSUE TITLE
feature(postgres): Define session role for connection (Request in QGIS)

### ISSUE THREAD

**Issue by rldhont** [qgis/QGIS-Documentation#7780]
Request for documentation

[From pull request https://github.com/qgis/QGIS/pull/49440](https://github.com/qgis/QGIS/pull/49960)
Author: @rldhont
QGIS version: 3.28

feature(postgres): Define session role for connection
PR Description:

## Description

Be able to define a session role for postgres connection.

Documentation: https://www.postgresql.org/docs/current/sql-set-role.html

The `session_role` setting will be used to set the current user identifier
of the current SQL session to be `session_role`. Permissions checking for
SQL commands is carried out as though the named role were the one that had
logged in originally.

This is useful to automatically give the ownership of a new object (Table, View, Function) to
the `session_role` group and thus share ownership and associated rights with all members
of the `session_role` group.

The specified `session_role` must be a role that the current session user
is a member of. (If the session user is a superuser, any role can be selected.)

Funded by 3liz https://3liz.com/

**Comment by DelazJ** [comment]
@rldhont I just realize that you manually created this issue report, duplicated by #7820.
For reference, you don't need to do this, just add the "needs documentation" label to the code PR and it will be generated here.
