### ISSUE TITLE
Configuring the Processing Framework: missing "Override temporary output folder path" parameter description

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS-Documentation#7807]
## Description

The following parameter descriptions is missing:

- "Override temporary output folder path" https://github.com/qgis/QGIS/pull/33697

Page URL: https://docs.qgis.org/3.22/en/docs/user_manual/processing/configuration.html#configuring-the-processing-framework

**Comment by DelazJ** [comment]
@agiudiceandrea is this not what is pending for a review for more than 6 months at #7349 ?

**Comment by agiudiceandrea** [comment]
@DelazJ, oops... I apologise, I didn't found it. As I can see in the code, the description in the PR https://github.com/qgis/QGIS-Documentation/pull/7349 is correct.
I close this issue report.

**Comment by DelazJ** [comment]
@agiudiceandrea no problem; it thus counts as a review ;)
