### ISSUE TITLE
TM 3.3.3 Add details to avoid crashing QGIS with Fixed Interval classification

### ISSUE THREAD

**Issue by rnlbd** [qgis/QGIS-Documentation#7816]
## Description

Page URL: [Chapter 3.3.3](https://docs.qgis.org/3.22/en/docs/training_manual/vector_classification/classification.html#moderate-fa-ratio-classification)
While following the steps in chapter 3.3.3, using the latest version of QGIS (3.26.3 'Buenos Aires'), it crashed because the selected mode was by default "Fixed Interval", which can cause QGIS to crash (known issue, see [#49333](https://github.com/qgis/QGIS/issues/49333).)
An additional step to set the correct mode, "Equal count (quantile)", would avoid beginners like myself to have QGIS already crash on the 3d chapter of the training manual :)

**Comment by DelazJ** [comment]
> what to do in those situations when issue is related to the older versions?

Generally speaking, I'd say: we should close a report if it is about an issue occurring with the software. This is the QGIS docs repo, not QGIS repo.
But in this particular case, considering that the screenshot in the chapter shows the "Equal count" classification, we should add a step with that instruction. The text would be inline with the screenshot.
