### ISSUE TITLE
Desktop User Guide/Manual

### ISSUE THREAD

**Issue by AmelieMc** [qgis/QGIS-Documentation#7850]
I was following directions in the User Guide as a Newby.
I opened lakes.gml and did not get the window for Coordinate Systems as expected from 5.4 and 5.5. I got the screenshot below 

![lakes gml screenshot](https://user-images.githubusercontent.com/61313773/198898487-36e20224-f469-4f5f-b74b-1de401014ef7.jpg)

Page URL: https://docs.qgis.org/testing/en/docs/user_manual/introduction/getting_started.html#label-sampledata

**Comment by DelazJ** [comment]
Thanks @AmelieMc
