### ISSUE TITLE
3.22 build doctest is failing

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#7858]
Afaict, again, no related changes occurred in this repository. The doctest just started to fail. This time it is about:
> NameError: name 'start_qgis' is not defined

and 
> ModuleNotFoundError: No module named 'qgis'

**Comment by pedrocamargo** [comment]
I can confirm I am getting the same when running tests on CI for a plugin project

**Comment by nicogodet** [comment]
Could be related to https://github.com/qgis/QGIS/issues/50729 ?

**Comment by DelazJ** [comment]
Fixed in https://github.com/qgis/QGIS/commit/ca9acb7999b56d81fd261f491833b098461551a2
