### ISSUE TITLE
Hard to identify mentioned figures in the PDF manuals

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#788]
In the PDF version of the user manual (didn't check other docs), the figures are listed from the beginning and identified as Figure_chapternumber_positioninthechapter while they are somehow randomly named (would be nice to have rules about naming figures) in the Online doc. below is the same figure in both manuals 
- The PDF manual

![fig_addvector](https://cloud.githubusercontent.com/assets/7983394/12702780/7dd20bfe-c832-11e5-9491-b04cbd81b923.png)
- The online manual

![fig_addvector2](https://cloud.githubusercontent.com/assets/7983394/12702781/7dd44b9e-c832-11e5-96e0-94c6e2db6bd8.png)

As you can see, in the PDF manual, there's still a reference to `figure_vector_1` while no figure is named like this (`figure 12.1` instead). Clicking the hyperlink associated to`figure_vector_1` text still reaches the correct figure but you lose this link if you print the doc. If the reference to the figure is not that close to the figure (and that's really common in the PDF version for layout reasons), it becomes difficult to identify the mentioned figure and understand the manual.

Is it possible to substitute the reference to figure_vector_1 by Figure 12.1 in the text?

**Comment by havatv** [comment]
I suggest we try what was proposed in https://stackoverflow.com/a/37005964:

-------------------------------------------
In the latest versions of Sphinx (1.3+), numbering figures and referencing them from text got a bit easier as support for it is now built-in.
In your text, you can do something like:
```
.. _label:
.. figure:: images/figure.*

At :numref:`label` you can see...
```

The end result should be something like "At Fig 1.1 you can see...". This technique works both with the default HTML output and the LaTeX output.

In your conf.py file, make sure to set the flag numfig = True. There are also configuration options for the references' text format (numfig_format and numfig_secnum_depth).

References:

    http://www.sphinx-doc.org/en/stable/config.html#confval-numfig
    https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#cross-referencing-figures-by-figure-number
-------------------------------------------
Should be tested (and added to the documentation guidelines).

**Comment by havatv** [comment]
@DelazJ, in PR #5830 I have implemented my proposal and added a few :numref:s in the new Browser panel chapter. I did a make pdf, and it seems to work:
![image](https://user-images.githubusercontent.com/1598812/86544936-3e6c3800-bf2b-11ea-8fcd-63e17117d7e3.png)
The RST code for this is:

    The browser panel (:numref:`figure_browser_panel`) is organised

As you can see,

    :numref:`figure_browser_panel`

Is rendered as `Fig. 9.1`, so when we update :ref: to :numref: we must make sure that "figure" / "fig." / "Fig." are removed.

**Comment by DelazJ** [comment]
Humm, I'm not sure that is the proper fix. Already tested years ago with Alexandre. Checkout your html build and you'll notice that your images are getting numbered up to > fig. 500. Unlike Latex, Html by default counts your images from 1 to whatever, and this is quite ugly. Unless you number the chapter, which I'm fine with for training manual but not in User manual.

Actually the fix is already there and is instructed in the [guidelines](https://docs.qgis.org/testing/en/docs/documentation_guidelines/writing.html#figure); simply use :ref: role. This is already used in some places and I forgot to propagate it everywhere while fixing the old manual numbering system (I might have some branch somewhere I can resurrect if you want). :ref: shows the caption of the image. Maybe to be explicit, use "**figure :ref:\`figure_browser_panel\`**" which will render **figure The Browser panel** in html and pdf, and easily identifiable.

**Comment by havatv** [comment]
> Humm, I'm not sure that is the proper fix. Already tested years ago with Alexandre. Checkout your html build and you'll notice that your images are getting numbered up to > fig. 500. Unlike Latex, Html by default counts your images from 1 to whatever, and this is quite ugly. Unless you number the chapter, which I'm fine with for training manual but not in User manual.

I don't understand why high numbers for the figures could be a problem. And numbering the chapters in the user manual also sounds like an acceptable "solution" to me.

> Actually the fix is already there and is instructed in the [guidelines](https://docs.qgis.org/testing/en/docs/documentation_guidelines/writing.html#figure); simply use :ref: role. This is already used in some places and I forgot to propagate it everywhere while fixing the old manual numbering system (I might have some branch somewhere I can resurrect if you want). :ref: shows the caption of the image. Maybe to be explicit, use "**figure :ref:`figure_browser_panel`**" which will render **figure The Browser panel** in html and pdf, and easily identifiable.

I very much prefer numbers in the figure references - short, easy and unambiguous. I also think this is what the QGIS users will be accustomed to.

**Comment by SrNetoChan** [comment]
I don't have a very strong opinion about the way figures are referenced. I can't remember how numbered chapters look like, but this would be my order of preference:

1. Having numbered chapters, with numbered figures.

2. Having numbered figures even with very large numbers

3. Having non-numbered figures, which originate kinda ugly inline references (what we have now).

@DelazJ can you explain why you are against numbered chapters for the users manual?
