### ISSUE TITLE
QGIS SERVER

### ISSUE THREAD

**Issue by Accuracy-Global** [qgis/QGIS-Documentation#7902]
Hi team,

 we have already the QGIS Desktop version with windows and working on it! And now we are trying to install the **QGIS server version.**

Is the Qgis server and qgis desktop both are different? if yes how to install qgis server version can you please help me with link?

**Comment by DelazJ** [comment]
https://docs.qgis.org/testing/en/docs/server_manual/index.html
This repository is for docs managing. For questions, 
Please ask in qgis-user list or any other channel (see [support channels](http://qgis.org/en/site/forusers/support.html)).

**Comment by Accuracy-Global** [comment]
DO we have any Product support from QGIS we have requirements that need to discuss with QGIS support? If yes please help me!

**Comment by elpaso** [comment]
@Accuracy-Global you can contact any of the companies listed here: https://www.qgis.org/en/site/forusers/commercial_support.html
