### ISSUE TITLE
Standardize "Building with Docker" description between Documentation and Website repositories

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#791]
In the [Readme](https://github.com/qgis/QGIS-Documentation/blob/master/readme.rst#building-the-documentation-using-docker) file of QGIS-Documentation repo, the process described to build the doc with Docker is very different from the description in the [readme](https://github.com/qgis/QGIS-Website/blob/master/README.md#building-the-website-using-docker) of QGIS-Website repo.
Given that building with Make or Paver are almost the same, Is it normal to have these ones so different or is one of them just out of date?

**Comment by yjacolin** [comment]
Both are out of date but the best one is the one in QGIS-Documentation, @lucacasagrande is working on the QGIS-Documentation's one to adapt command line with an incorrect name.

**Comment by lucacasagrande** [comment]
The one in QGIS-Documentation should build only the PDF version (using qgis/sphinx_pdf) so probably we need a script also for the HTML version.

**Comment by yjacolin** [comment]
As far I remember we need to change manually the docker container to use in the script :) as by default cron should use the sphinx_pdf container.

**Comment by havatv** [comment]
> Both are out of date but the best one is the one in QGIS-Documentation, @lucacasagrande is working on the QGIS-Documentation's one to adapt command line with an incorrect name.

@yjacolin, can we close now?

**Comment by yjacolin** [comment]
I guess, I didn't work on this topic for years.
