### ISSUE TITLE
Update the documentation guidelines

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#793]
Considering the different improvements recently discussed in the mailing-list or applied to the repo, it might be nice to have them listed somewhere and be able to update the guidelines for newcomers. This is a first draft; some points below come from the difficulties I encounter when I began to contribute and that may be improved:
- [x] Keep using **`** character around GUI labels when mentioned and remove GUI label reference such as :guilabel:, :menuselection: 
  - [x] or meanwhile explain when to use each these tags
- [ ] better explain when special formatting can be used : bold, italic, ``, [ ].
- [ ] Show a complete and up to date list of available substitutions at http://docs.qgis.org/testing/en/docs/documentation_guidelines/substitutions.html. Might first require to:
  - [x] remove icon files not mentioned in the `conf.py` file
  - [x] clean the list of substitutions in `conf.py` file by removing all substitutions (and icons) not used in the docs --> reduce the list of substitutions to what's really needed and used
  - [x] reword substitutions name to be as shorter as possible (get rid if possible of all `mAction`, `mIcon` stuffs in the substitution)
- [x] indicate how to update the list of icons and substitution if needed:
  - [x] where to find the new icons (in QGIS repo: /images/themes/default?)
  - [x] need to add the substitution in conf.py file  before completing the list in the Guidelines Doc
- [x] what are the rules of naming figure, screenshot file..
- [x] first steps to deal with their git repo (inspired from https://github.com/yjacolin/QGIS-Documentation/wiki/howto_contribute_QGIS-Doc)

This is just a first draft. Can be reviewed according to what new changes are added. Comments are welcome.

**Comment by rduivenvoorde** [comment]
Hi, I'm pretty disappointed with what I have accomplished to be honest, and want to hear from @DelazJ @dassau @SrNetoChan if they really find that I should go further with this...
We get rid of the  :guilabel:, :menuselection:
We see the larger (non common/substitution) images in github
But I fail to get the inline ones replaced
So now there are rather 3 places for images: in resources (for substitutions), in images dir near rst and in the static/template dir (though not for docs..)
Anyway, are I should to this for all rst files? Now I can still revert the work...

**Comment by yjacolin** [comment]
@rduivenvoorde we can discuss this and have a look at the next hackfest?! Altogether we will be stronger to find a solution :)

**Comment by DelazJ** [comment]
@rduivenvoorde wrote (see #795 ):
>Sorry guys, I have been messing up recently with my quest to make stuff github editable.

>Feel free to roll back all my edits, or I will try to do it myself in near future.

>I think I only messed up the vector_properties.rst in working_with_vector. And the images directory in that dir. Which has had some newer screenshots after I added it... So these screenshots should go to the resource/en directory again...

>What is the preference? Should I dig up an old version of the vector_properties.rst (but then probably throwing away some work of others), or can we do something more clever here?
The images-directory should probably copied over de old images, so the newer ones will be in their original places, and the images directory is to be remove.

AFAICS, the main change in the rst file is the use of relative path for the images. So, IMO it'd be quicker to fix it by moving images to resources dir and make a Search/Replace in the file instead of digging up an old version (many changes have been done to this file meanwhile: 1abb786).
Or do you also mean that the removal of :guilabel: and :menuselection: should be reverted?
>So now there are rather 3 places for images: in resources (for substitutions), in images dir near rst and in the static/template dir (though not for docs..)

Wasn't that already the case: 3 dirs (a resources/en/common, resources/en/doc/chapter... and in static)? About your changes, I really like having the images in GitHub. I haven't followed nor understood all the technical requirements but what about moving the icons in resources/en/common into a folder in source dir (you then have a relative path accessible)?

**Comment by rduivenvoorde** [comment]
@DelazJ I reverted all my changes now. Brought back an old version of one rst file and copied the images back to resources (including the new ones from @SrNetoChan).

**Comment by SrNetoChan** [comment]
Sorry, missed the discussion before @rduivenvoorde revert his changes. What's the plan then? keep it until hackfest? or after 2.14 users manual release?

**Comment by rduivenvoorde** [comment]
Well, as said: I was trying something out, but was not happy with the result. 
We could do parts of it (like, only remove the :xxx: directives, or put only the dialog images (not the substition/inline ones) in a images dir per dir. But for the last part I would have to patch the multilingual build too and the other stuff would just be work... , I reverted all. Just too unhappy with results.
I think we should go with the 'old' system for 2.14 (and I hope this will be online before the hackfest)

**Comment by mezwor** [comment]
If we need more people to contribute this issue is very important. Please go ahead updating the guideline. It is not easy for newcomers to easily catch up with the topics for contribution.

**Comment by yjacolin** [comment]
@mezwor if something is not clear, could you list them in this ticket with `- [ ] ` as bullet point. We will find time to add more comment in the next hackfest.

**Comment by DelazJ** [comment]
@mezwor I'll try to address some of the points above but given that I am no more a newbie :), I'll surely need your help to better explain what is expected by a beginner. If there's anything you think should be clarified, feel free to say it and we'll try to formalize it. No wrong question, just ask. However note that there are points I can't explain yet. but others will help.
BTW, I'm still looking for someone to review https://github.com/qgis/QGIS-Website/pull/308 that explains first steps to report doc issues and help. sorry @yjacolin, another big PR.

**Comment by DelazJ** [comment]
@rduivenvoorde can you give a look to https://github.com/qgis/QGIS-Documentation/blob/master/source/docs/training_manual/processing/batch_conversion.rst and other pages in the processing folder? They render screenshots in github preview. How is that?

**Comment by yjacolin** [comment]
Because the pictures diredtory are located in the right place following the path in the rst file: img/picture.png, see https://github.com/qgis/QGIS-Documentation/tree/master/source/docs/training_manual/processing

**Comment by rduivenvoorde** [comment]
Yes, this is indeed working with relative paths in the sources. This was the 'experiment' I did some time ago. 
But the problem in using all 'relative paths' (which would be cool, because then we could let people write documents in Github, and in Github it would almost be 'what you see is what you get'...) are:
- inline images cannot be easily done that way
- common image replacement is not working

Biggest problem were the inline images... which are a pita in rst

BUT.... I found out that we could actually create a mixed combination of sources: 
Markdown for all content pages (with relative paths, and good inline images)
RST for the index-containing pages.

If I understand correct Sphinx can now use both, so the output for both html and pdf should still be possible... but... first let's release 2.14 :-)

**Comment by ghtmtt** [comment]
this seems outdated. image preview is fixed thanks to @SrNetoChan awesome script. Also the guidelines chapter seems updated for me. Reopen if necessary. :)

**Comment by DelazJ** [comment]
There are still issues about mismatched substitutions which i've been working on month ago (eg #2803) so i'm reopening

**Comment by yjacolin** [comment]
I think we should improve ourself to write correctly an issue description ;). The title is too large and so this ticket will never be closed. Almost 2 years to finalize this ticket, something going wrong.

Please keep ticket simple enough!

**Comment by DelazJ** [comment]
@yjacolin 
> The title is too large and so this ticket will never be closed.

Allow me to disagree with you. There are 10 older tickets in the repo (one of 4 years!!!); they may look simpler but it does not mean they get fixed before this one. I can bet ;)
This issue which may appear large gives a cap and is only about guidelines. It contains tasks that have been checked whenever the issue they cover was fixed (I should have linked commits, maybe). You can notice that there's only one remaining (i don't consider the format related one). Also, this is a backend improvement so not all contributors can give a hand and if there are no new contributors, there's no reason to prioritize guidelines writing when there are feature related issues that pile up (as usual, it's a matter of time, manpower and interest).
And, to reassure you, I've been working on this last issue until recently (check eg my July history).

> Please keep ticket simple enough!

Got it! Will try.

**Comment by DelazJ** [comment]
Seems most of the points that are worth documenting are fixed here, so I'm closing
