### ISSUE TITLE
Make the images translatable

### ISSUE THREAD

**Issue by BathoryPeter** [qgis/QGIS-Documentation#7954]
I'm planning to add some translated image (line and polygon label placements), but they will not shown with the current config. To follow the current directory structure of German images, we have to add the following config in conf.py:

```
figure_language_filename = '{path}{language}/{basename}{ext}'
```
([sphinx docs](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-figure_language_filename))

**Comment by DelazJ** [comment]
Oops, I'd have bet that translated images were already available in their docs. Seems they don't.
Feel free to adjust that. Thanks
I also found there still remain outdated German screenshots (e.g. authentication chapter,...) that we need to delete for a cleaner docs output.

**Comment by BathoryPeter** [comment]
Do I create a pull request? To which branch?

Screenshoting the software dialogs manually doesn't seems to be sustainable. Maybe in the future we will able to generate them automatically.

**Comment by DelazJ** [comment]
> Do I create a pull request? To which branch?

Yes, please. master. Everything goes first to our master branch
> Screenshoting the software dialogs manually doesn't seems to be sustainable. Maybe in the future we will able to generate them automatically.

There was an attempt some time ago by @3nids (see https://github.com/qgis/QGIS/blob/master/src/app/qgsappscreenshots.cpp or https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html#take-screenshots which can be run in the console as ```qgis --take-screenshots output_path```) but afair it did not work correctly.

**Comment by DelazJ** [comment]
@BathoryPeter Things are now in place to add your localized screenshots

**Comment by BathoryPeter** [comment]
I've just finished translating the corresponding file and hope to be able to add the pictures today evening.
