### ISSUE TITLE
Batch processing point to point

### ISSUE THREAD

**Issue by Kaushal333** [qgis/QGIS-Documentation#8047]
for example: I want to calculate distance from 500 different points to 500 different points in QGIS. In QGis they dont have special tool for this. They just have point to poin (single), point to layer and layer to point.
So I decided to use batch processing on point to point.
But the main problem is :
![image](https://user-images.githubusercontent.com/125223590/218425669-6f66e792-8404-4dce-9fc7-5d9160b82e8f.png)

![image](https://user-images.githubusercontent.com/125223590/218425640-9293f12f-8d4b-45fd-b611-8e9ee02dd19f.png)

(The instructions from https://gis.stackexchange.com/questions/441280/qgis-shortest-path-layer-to-layer)

But my question is bit different as I want to find from 500 different points to 500 different points , so in total just 500 paths.

MY PROBLEM
![image](https://user-images.githubusercontent.com/125223590/218425574-b77626c8-cbcc-4898-b64e-83f7ca615c99.png)

SO I decided to use "add value by expression" for both for start and end points but qgis starts filling the values from the rows where the start values end . FOr eg, for 4 origins to 4 destinations, when i use add by expression in start points, i fill 4 rows , 1-4 , and when i try to fill end points it starts filling from row 5 to row 8 instead of rows 1 to 4.

Note:
There are other ways to generate distant matrices from layer to layer so there will be for example 1000*1000 OD pairs instead of just 1000 OD pairs which i want so i want to use this method )
Regards
Kaushal

**Comment by DelazJ** [comment]
Hi @Kaushal333 
This repository is for [QGIS documentation](https://docs.qgis.org). For questions and help, please ask in qgis-user list (see [support channels](http://qgis.org/en/site/forusers/support.html)). If it is a feature request/bug report in the software, please instead report at https://github.com/qgis/QGIS/issues.
Thanks for understanding.
Closing.
