### ISSUE TITLE
Problem with PyQGIS cookbook

### ISSUE THREAD

**Issue by Marek-Zy** [qgis/QGIS-Documentation#8055]
Hi
Wanting to develop my skills, I started learning with the PyQGIS cookbook (for plugins and scripting).
Already in Introduction, I encountered a problem, chapter 1.3.1. The startup.py file, on my system the startup.py file does not exist. Works on debian 11 and QGIS 3.28. What replaces startup.py in this configuration?
I will be grateful for your help.

**Comment by nicogodet** [comment]
This file does not exist by default.

It can bu used if you want to execute python code on QGIS startup.
Here is an example (in french) of a use case of startup.py script : https://gitlab.com/Oslandia/qgis/profils_qgis_fr_2022

If you don't plan to execute python code on startup, you can simply skip this chapter.

**Comment by Marek-Zy** [comment]
Thank you very much for your answer, this was missing in the documentation.

**Comment by DelazJ** [comment]
https://docs.qgis.org/3.22/en/docs/pyqgis_developer_cookbook/intro.html#the-startup-py-file
> **If that file exists**, it is executed by the embedded Python interpreter.

Do you think we need more? In which case, if ever you have suggestion to make it clearer for people, it would be much appreciated
