### ISSUE TITLE
Remove SPIT plugin

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#806]
According to this [discussion](https://www.mail-archive.com/qgis-developer@lists.osgeo.org/msg30030.html), SPIT plugin is no longer in QGIS. So any mention should be removed:
- [X] from the user manual
- [ ] from the training manual

**Comment by EvanCarroll** [comment]
What replaced it? There is no talk in the discussion or suggestion of which 10 ways we should now go about doing this?

**Comment by DelazJ** [comment]
> SPIT is now removed from core. If there is anything missing in the current stuff that was in SPIT please open a ticket so it can be address in DB Manager.

For me, the message is clear. All SPIT stuffs are intended to be in DB Manager which you can activate from the Plugin Manager.
