### ISSUE TITLE
How to translate textual substitutions?

### ISSUE THREAD

**Issue by aroche** [qgis/QGIS-Documentation#8078]
## Description

Some substitutions in `substitutions.txt` are text replacements, such as |FA|, |LS|... As far as I know, those are not translated in documentation and results in mixed language sentences. Is there a way to translate them?

Example:
![image](https://user-images.githubusercontent.com/1985028/222097118-f6dfebca-035f-4fc4-95a6-c5115155e6df.png)

**Comment by DelazJ** [comment]
Some years ago, I looked for a way to get them translated but to no avail, and i guess i'm now used to these mixed strings and do not see them anymore.
It could be nice to check if there is an extension/parameter to do that now and if not, maybe should we consider replacing them with their actual text...

**Comment by misibacsi** [comment]
I opened now an issue on Github I hope they will solve this problem. 
It seems on Transifex some translations are 100% ready, but they are not used yet.
https://github.com/readthedocs/sphinx_rtd_theme/issues/1473

**Comment by DelazJ** [comment]
In #8916 I suggest we simply replace these substitutions with their actual text. Hence people can translate them.
