### ISSUE TITLE
Update the Metadata Tab

### ISSUE THREAD

**Issue by mezwor** [qgis/QGIS-Documentation#813]
Add LegendUrl and some description to the Metadata Tab section and also update the associated image

**Comment by mezwor** [comment]
I am going to add some description and update the image. Am learning to contribute and your comment is invaluable.

**Comment by yjacolin** [comment]
@mezwor just send a PR and I will review. We can close PR if you need more time or just update your branch and the PR will be updated.

**Comment by DelazJ** [comment]
@mezwor Can we considere this as done, due to #817 or are you planning any other change?
