### ISSUE TITLE
Open Error

### ISSUE THREAD

**Issue by XuBaocai** [qgis/QGIS-Documentation#8146]
The webpage cannot be opened after clicking the relevant link, as shown in the following figure:

https://docs.qgis.org/3.28/zh-Hans/docs/user_manual

![2023-03-29_094615](https://user-images.githubusercontent.com/66826351/228405678-bfa04926-b57a-4ec5-bcf8-e2b352421232.jpg)
![2023-03-29_094508](https://user-images.githubusercontent.com/66826351/228405697-b7d26113-e2b2-434d-9fa4-471b23d0208d.jpg)
![2023-03-29_094709](https://user-images.githubusercontent.com/66826351/228405714-1fb52d33-07e1-4b35-b1d5-c3441ac98e73.jpg)

**Comment by DelazJ** [comment]
We have to build zh-Hans as zh_Hans because sphinx doesn't like the '-', so files are stored in a zh_Hans folder while we were serving from an unavailable zh-Hans. And this time again, we forgot to symlink the two names. Should be fine now. Sorry for the inconvenience.
