### ISSUE TITLE
Missing layer CRS in Reprojecting Data Lesson

### ISSUE THREAD

**Issue by erinhuynh** [qgis/QGIS-Documentation#8177]
## Description

Vector layer exercise_data/world/RSA.shp has no CRS. Tthe documentation says the CRS should show up as "EPSG:3410" when hovering the mouse over the layer in the legend, but nothing shows up.

Page URL: https://docs.qgis.org/3.28/en/docs/training_manual/vector_analysis/reproject_transform.html#basic-fa-on-the-fly-reprojection

**Comment by DelazJ** [comment]
Thanks for reporting, @erinhuynh . Should be fixed now, data has been updated.
