### ISSUE TITLE
rsync script for pdf and zip's do not take language into account

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS-Documentation#8181]
Just found out by accident (building arabic here locally)) that the rsync step in the docker-world cleans up the full pdf and zips directory (every time...)... 
So I think.. we should update the script...

**Comment by rduivenvoorde** [comment]
Updated script, now the zip's should show up in an [LANGUAGE] directory too
Also updated the make_world, so it will rync per LANGUAGE
Have to see/check if it works...

**Comment by DelazJ** [comment]
@rduivenvoorde I see you reverted the changes. You did not get what you expected, I assume.
Do I understand that the idea would be to have a language folder in which we would have both PDF files and the zip one? 
```
E.g.:
/3.28
|--> de
      |--> PDF folder
            |--> German PDF files
      |--> German zip HTML file
```
Or would you have additional language folder for the (single) zip file? 
```
E.g.:
/3.28
|--> pdf
      |--> de
            |--> German PDF files
|--> zip
      |--> de
            |--> German zip HTML file
```
Looks like it was 2 (though my preference would go to 1). Or do I misunderstand (and should more carefully review your changes)?

**Comment by rduivenvoorde** [comment]
Hi @DelazJ yes, the second option was my plan, but it was a (too) quick fix, so apparently by rsyncing my (empty) output directory, all languages were removed... (there was not even an English site anymore).
So I reverted, and postponed to later :-)

But the actual issue is that (I think) rsync also tries to remove all files that are not there anymore at the source (with that removing ALL zip's ... that is why I tried to put the zip's in their language directory to make the rsync call more specific... but I failed... I put it on the TODO list :-)

**Comment by selmaVH1** [comment]
Hello @rduivenvoorde I'm not sure I understand everything in this discussion, but my question is: can we close this issue or we need to keep it as a reminder?

**Comment by rduivenvoorde** [comment]
@selmaVH1 I think it is fixed, maybe later?
I do see every language now seems to have it's own language dir:
https://docs.qgis.org/3.34/pdf/
So OK to close, I think?
