### ISSUE TITLE
Horizontal scrolling in Attribute table with shift + mouse scrollwheel does not work for MacBook

### ISSUE THREAD

**Issue by diethard2** [qgis/QGIS-Documentation#8186]
## Description
Please add note/warning in documentation on Shift + Scroll for Attribute Table

Actual behaviour
On my MacBook Pro, running MacOS Mojave, when I use the Shift + scrollwheel of my external mouse, the attribute table scrolls vertical instead of horizontally.

Expected behaviour
In the manual it is described that Shift + Scrollwheel would move the attribute table horizontally.

This seems to be a general problem described on stackexchange. 
https://apple.stackexchange.com/questions/392936/shift-scroll-doesnt-horizontally-scroll-with-any-external-mouse

Shift + moving 2-fingers up/down on the trackpad works however, moving 2-fingers to left/right works as well!

Page URL: https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/attribute_table.html?highlight=attribute%20table#id24

**Comment by DelazJ** [comment]
From what I understand in the link you provide, shift+ scroll wheel horizontally scrolls on macOS also if you change some Mos property (not clear either if this is a default tool/setting on the OS or not). TBH I'm not sure we need to add the trackpad behavior and, may I warmly suggest you to add the "fix" (if necessary) yourself, as a macOS user? Imho Not necessarily an easy fix for another OS user.
