### ISSUE TITLE
In Substitutions the icon definition for Elevation Profile is missing

### ISSUE THREAD

**Issue by diethard2** [qgis/QGIS-Documentation#8187]
## Description
In chapter 5.7 Substitutions for Print Layout we first need to add the **icon** for **Add Elevation Profile** before we can start to describe the widget.

Page URL: https://docs.qgis.org/testing/en/docs/documentation_guidelines/substitutions.html#print-layout

**Comment by DelazJ** [comment]
For information, https://docs.qgis.org/testing/en/docs/documentation_guidelines/substitutions.html#usage provides details on where to find the file to save as PNG for reuse. In this case, https://github.com/qgis/QGIS/blob/master/images/themes/default/mLayoutItemElevationProfile.svg (assumed based on the name, no QGIS around to check)
Also, the substitution icon addition is npt necessarily a pre-process; it can be done in the same PR targeting its functionality.

**Comment by diethard2** [comment]
Got it I will pick this up myself and first make sure to add this to substitutions. I need it for the next step ;-)

**Comment by diethard2** [comment]
icons are available now!
