### ISSUE TITLE
synchronise sample datasets

### ISSUE THREAD

**Issue by janneke-qgis** [qgis/QGIS-Documentation#8202]
There seem to be different locations where a sample data set is kept:

1) https://docs.qgis.org/testing/en/docs/documentation_guidelines/writing.html#managing-screenshots links to:
https://download.qgis.org/downloads/data/

2) https://docs.qgis.org/testing/en/docs/user_manual/introduction/getting_started.html#downloading-sample-data links to:
https://github.com/qgis/QGIS-Sample-Data/archive/master.zip

3) not seen (yet) in the documentation (I think):
https://github.com/qgis/QGIS-Sample-Data, when you do ‘code’ download zip you get:
https://github.com/qgis/QGIS-Sample-Data/archive/refs/heads/master.zip
This seems to be the latest (only based on dates, not sure if the data are actually different and if there’s a way to compare).

Which of these datasets is the latest/correct/authorised one? Should the documentation refer to one location, if so, which one? 
cheers,
Janneke

@rduivenvoorde @DelazJ

**Comment by DelazJ** [comment]
@janneke-qgis Am I wrong that 2 and 3 are the same? And 2 is the link that we should be using for writing the docs, and we should mention in managing screenshots section.
About link 1, this endpoint is (was?) also used to serve datasets with Windows standalone installers. I'd vote to kill it and rely on link 2 but I don't know the technical implications. Just as far as I'm concerned, I'd just kill it from the docs. 
Read also https://github.com/qgis/QGIS-Documentation/issues/1248

**Comment by DelazJ** [comment]
> And 2 is the link that we should be using for writing the docs, and we should mention in managing screenshots section.

Done in #8215

**Comment by DelazJ** [comment]
@janneke-qgis Do you see any remaining issues we need to address here?
