### ISSUE TITLE
when will a new translation will be visible online for the public if it is ready on Transifex?

### ISSUE THREAD

**Issue by misibacsi** [qgis/QGIS-Documentation#8228]
## Description
Question:
I wish to know when my translation will be visible online for the public?

What happened:
I translated some text into Hungarian 3 days ago on Transifex:
It is not complete. 
The translating was started by others sometime in the past, and this older translation is still visible.

Expected:
In the documentation there is a sentence, which states 

_"At the next build of the documentation (which occurs at least **once a day**)..."_

I tried to select v3.28 (default), "latest", "testing" text versions, and it looks that my translation is not visible in them. 

I expected that my translation will be visible after 24 hours after I finish the text.

I translated this part 3 days ago on Transifex (the older version of the translated text is visible):
Page URL: https://docs.qgis.org/3.28/hu/docs/documentation_guidelines/do_translations.html

**Comment by misibacsi** [comment]
Meanwhile my translation in the question was published after about 1,5 day.

I asked a Hungarian QGIS translator and he said that the file must be 100% complete, otherwise it won't be published. When I asked the question, the translation was not finished totally, so I finished on that day up to 100%. It is also missing from the documentation, that **"100% file completeness is required for publishing"**.

As I started to translate this piece of text, it was already partially translated. So I did not expect it must be finished 100%.

**Comment by DelazJ** [comment]
@misibacsi see #8234.
Note that the script for unfinished files is not working right now. I'm on it.

**Comment by misibacsi** [comment]
Meanwhile my translation in the question was published after about 1,5 day.

I asked a Hungarian QGIS translator and he said that the file must be 100% complete, otherwise it won't be published. When I asked the question, the translation was not finished totally, so I finished on that day up to 100%. It is also missing from the documentation, that **"100% file completeness is required for publishing"**.

As I started to translate this piece of text, it was already partially translated. So I did not expect it must be finished 100%.

> @misibacsi see #8234. Note that the script for unfinished files is not working right now. I'm on it.

1. Thanks in advance, this would be one good solution. 
2. The other solution would be if the documentation would contain this info _("The translation can be published after 24 hours if the translation is 100% complete")._

**Comment by DelazJ** [comment]
> The other solution would be if the documentation would contain this info ("The translation can be published after 24 hours if the translation is 100% complete").

Where would you see such information? In the do_translations chapter?
Note that it is not necessarily true; the build is at 3 pm afair so if you finished the translation at 2pm, it will be published.

**Comment by misibacsi** [comment]
Yes, the text is in here: ("4. Translation Guidelines")
https://docs.qgis.org/3.28/en/docs/documentation_guidelines/do_translations.html

It says: _"At the next build of the documentation (which occurs at least once a day), a script reuses the sentences to create translated output"_

If somebody has the knowledge when this happens, please give a more accurate guessing when (in this chapter). Please rephrase the sentence. There are many possibilities for expressing when the publishing process will start / happen:

1. probably within 24 hours
2. at 00:00 UTC it starts
3. at 12:00 at the next day (EST)
4. the timing can be any time between 12-36 hours
5. 2-3 days

In practice I waited about 1,5 day when the translation appeared, so I do not think that the "once a day" reflects this.

Yes, the "the next build expression covers all", but how can a translator know when the "next build" happens? The same question with other words.

**Comment by DelazJ** [comment]
> > Yes, the text is in here: ("4. Translation Guidelines")
https://docs.qgis.org/3.28/en/docs/documentation_guidelines/do_translations.html

> @misibacsi see https://github.com/qgis/QGIS-Documentation/pull/8234.

☝️Can you please suggest where/what/how you think the information could be put in the mentioned PR (or create a new PR)? We would be way more efficient than discussing here.
About the info: You can find build hour at the bottom of every page (3.28 is 8.00 UTC, and testing seems 7.00 pm). Sometimes there is a third maintained version (e.g. when 3.34 LTR is released in october, it needs its own build hour and I have no idea what it would be - _I think there are other things running on the server_). And I'm afraid nobody will track and update this time info, at each new LTR release leading potentially to wrong info, as illustrated by this [quite old top sentence](https://docs.qgis.org/3.28/en/docs/documentation_guidelines/index.html#documentation-guidelines)). 

> In practice I waited about 1,5 day when the translation appeared,

🤔 u sure? If so, it would be a bug in the build at that time but this is not the norm. There is a job on the server taking care of this **daily**.

**Comment by misibacsi** [comment]
Will you please add "**UTC**" after the time numbers? Like as you mentioned "8.00 UTC".
Without it there is an uncertainty about in what timezone it is shown.
