### ISSUE TITLE
Digitize this new (fictional) area

### ISSUE THREAD

**Issue by dlejay** [qgis/QGIS-Documentation#8253]
## Description

Page URL: https://docs.qgis.org/3.28/en/docs/training_manual/create_vector_data/topo_editing.html

What does “8. Digitise this new (fictional) area” mean ?

**Comment by DelazJ** [comment]
Closing?

**Comment by dlejay** [comment]
“8. Digitise this new (fictional) area” should be replaced with
“8. Digitise the new (fictional) area shown in red”
