### ISSUE TITLE
Adding a layer to a GeoPackage

### ISSUE THREAD

**Issue by dlejay** [qgis/QGIS-Documentation#8255]
## Description

When the tutorial says “When you choose to save a layer to an existing GeoPackage, QGIS will append that layer to the GeoPackage.”, what really happens on macOS is that it triggers a warning “vector_analysis.gpkg already exists. Do you want to replace it ?”.
In the end it does not replace but adds, but I think something is wrong here.

Page URL: https://docs.qgis.org/3.28/en/docs/training_manual/vector_analysis/basic_analysis.html

**Comment by DelazJ** [comment]
@dlejay Can you share a screenshot of what is shown to you when you try to add the layer to a gpkg?

**Comment by dlejay** [comment]
The warning message looks like this :
<img width="256" alt="Screenshot 2023-05-11 at 12 44 54" src="https://github.com/qgis/QGIS-Documentation/assets/39823850/bc48ad35-56d8-4c4d-9a13-682c6e8b818f">
but with “vector_analysis.gpkg” instead of “training_data.gpkg”.
