### ISSUE TITLE
Are all new features in 2.14 reported in the issues report?

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#826]
Looking for an issue report in QGIS Redmine, I found out this commit (https://github.com/qgis/QGIS/commit/3c33177910f2324c44613d6829ff1a1a94837658) which is a new feature in 2.14 but not automagically reported in the Doc issues list.
Note tha instead of [FEATURE], it's tagged [Feature], so I wonder if it's the only one we didn't notice or if there are others. And more important, if some scripts guru can retrieve all the missing ones.

**Comment by yjacolin** [comment]
something like git log --since=20/02/2015 --grep='Feature" could do the trick.

**Comment by yjacolin** [comment]
We need to check with the script developer to not be case sensitive.

**Comment by rduivenvoorde** [comment]
code is here:
https://github.com/qgis/QGIS-Sysadmin/blob/master/webhooks/github_feature_tracker.cgi
script runs on qgis server
will have a look at it later

**Comment by yjacolin** [comment]
https://github.com/qgis/QGIS-Sysadmin/blob/master/webhooks/github_feature_tracker.cgi#L423
Something like this could do the work?
`'[feature]' in msg.tower()`

**Comment by rduivenvoorde** [comment]
tower? is that Python? 
'[feature]' in msg.upper() would work I think
But have to do it both in github and on server, will have to take some time to do that

**Comment by yjacolin** [comment]
this is a typo, ie read lower() :)

PR ready to go on my side :)

**Comment by nyalldawson** [comment]
any chance you could also add another keyword? [needs-docs]?

**Comment by yjacolin** [comment]
Does the [feature] tags already means that we need docs? What could be the difference for you?

**Comment by rduivenvoorde** [comment]
@nyalldawson well, that actually IS what we mean when we do [FEATURE]? Or do you want to be able to add it to excisting features?
Happy to add that off course...
Is there some consensus on labels syntax? Would be good to have them all like uppercase and short (or lowercase and short...) What about [NEEDDOCS]

**Comment by nyalldawson** [comment]
I'm thinking for non-feature changes. Eg if a dialog is reworked. 

A good example is https://github.com/qgis/QGIS/commit/6453907cb69764816a82a3b3e97c204cbe48c750, https://github.com/qgis/QGIS/commit/ddbdcf8ab1196e859642b1083e43a1bcd2ae2e14,
and https://github.com/qgis/QGIS/commit/dfdcec89223d4167850c7ebbb0af1d65c21135f8

They aren't new features, but require documentation updates

**Comment by dassau** [comment]
Hi,

i think that the ManualTask Wiki page is uptodate. I used a "git log
--since=20/02/2015 --grep='FEATURE'" for that...

http://hub.qgis.org/wiki/17/ManualTasks#Updates-210-214-User-Guide

Otto

Am Mon, 15 Feb 2016 00:19:53 -0800
schrieb Jacolin <notifications@github.com>:

**Comment by rduivenvoorde** [comment]
Ok, good to use that list now to check, and fix/update script for future, because I think working with features is easier to chop the work in pieces, and keep working on docs while developing?

**Comment by DelazJ** [comment]
@dassau I cant' find the feature reported above (https://github.com/qgis/QGIS/commit/3c33177910f2324c44613d6829ff1a1a94837658) in the Wiki, meaning that not all features are there either.
@rduivenvoorde which list do u talk about: the Wiki or Github? if both list have been scripted using 'FEATURE' as argument, we should have the same list, no?
I personally prefer GitHub given that issue status is real-time updated (what's not the case for the wiki)

**Comment by rduivenvoorde** [comment]
@DelazJ I mean the list @dassau created with his grep. Indeed this should have the same list. But there have been some bumps in the beginning, and we could have missed some with the github issue script there.

I prefer github list too, but the grep list is very easy to create and be used to (double) check.

We can always miss something anyway, but if we do a 'needdocs'-like tag too, we can always fix that :-)

**Comment by DelazJ** [comment]
@rduivenvoorde:

> I prefer github list too, but the grep list is very easy to create and be used to (double) check.

So the wiki list needs update
>    We can always miss something anyway, but if we do a 'needdocs'-like tag too, we can always fix that :-)

+1

**Comment by yjacolin** [comment]
Close this issue as the answer's question is: yes.
