### ISSUE TITLE
Sample Session:  Tutorial should say HOW to close the Data Source Manager

### ISSUE THREAD

**Issue by jidanni** [qgis/QGIS-Documentation#8324]
This works fine on windows, but on linux it causes Qgis to get stuck and need to be killed:

On https://docs.qgis.org/3.28/en/docs/user_manual/introduction/getting_started.html the user reads:

> 5.3. Sample Session: Loading raster and vector layers
> Now that you have QGIS installed and a sample dataset available, we will demonstrate a first sample session. In this example, we will visualize a raster and a vector layer. We will use:
> 
> the landcover raster layer (qgis_sample_data/raster/landcover.img)
> 
> and the lakes vector layer (qgis_sample_data/gml/lakes.gml)
> 
> Where qgis_sample_data represents the path to the unzipped dataset.
> 
> Start QGIS as seen in Starting and stopping QGIS.
> 
> To load the files in QGIS:
> 
> Click on the dataSourceManager Open Data Source Manager icon. The Data Source Manager should open in Browser mode.
> 
> Browse to the folder qgis_sample_data/raster/
> 
> Select the ERDAS IMG file rasterLayer landcover.img and double-click it. The landcover layer is added in the background while the Data Source Manager window remains open.

This causes this screen to appear:

![20230606T170124](https://github.com/qgis/QGIS-Documentation/assets/1230959/8fdf6178-8ffc-4874-9e32-c8b2b3325357)
 
There is no way to click any X's to close any messages, nor to click anything to make the situation get better. Qgis must be killed via kill(1) linux command.

Also the error message in yellow is not copyable with the mouse.

Package: qgis                            
Version: 3.22.16+dfsg-1
Maintainer: Debian GIS Project <pkg-grass-devel@lists.alioth.debian.org>

**Comment by jidanni** [comment]
Normally ESC would close the Data Source Manager window, and X would close the orange warning. But both cannot be closed. Nor can we press the Details button of the orange warning.

**Comment by jidanni** [comment]
I conclude that it is too hard to figure out how to close the Data Source Manager window. And must use ^C from the shell.
By the way, I also saw:


```
$ <string>:1: DeprecationWarning: setapi() is deprecated
Warning 4: Failed to open /usr/share/qgis/resources/data/world_map.gpkg: Permission denied.
Warning 1: Non-conformant content for record 1 in column update_time, 2019-08-15T21:28:22Z, successfully parsed
```

**Comment by jidanni** [comment]
OK, now using
Package: qgis                            
Version: 1:3.30.3+99sid
Maintainer: QGIS developers <qgis-developer@lists.osgeo.org>

Things are much better.

The only unexpected thing is we had to download the .tif file for the coordinate system. The tutorial should mention that.

**Comment by jidanni** [comment]
Also the tutorial shows
![20230606T180516](https://github.com/qgis/QGIS-Documentation/assets/1230959/9b20ec4d-6cae-4666-aee8-ffd36646b665)
but we see
![20230606T180418](https://github.com/qgis/QGIS-Documentation/assets/1230959/d5af4dde-867b-4290-9519-ca14e40a2746)

**Comment by jidanni** [comment]
> To load the lakes data, browse to the folder qgis_sample_data/gml/, and drag and drop the dbSchema lakes.gml file over QGIS main dialog.

No. Dragging and dropping assumes a windowing system that not all users have the same type of...

But I found I could still double click a sub item.

**Comment by jidanni** [comment]
Anyway at this point the tutorial is much different than what I see.

**Comment by jidanni** [comment]
We also notice the program is scanning unrelated files on my file system though not asked to do so:

```
$ ERROR 4: ERROR parsing kml /home/jidanni/Downloads/planisphere_link.kml :This file does not fit the OGR model, there is no container element at the root.
ERROR 4: ERROR parsing kml /home/jidanni/Downloads/planisphere_link.kml :This file does not fit the OGR model, there is no container element at the root.
ERROR 4: ERROR parsing kml /home/jidanni/Downloads/planisphere_link.kml :This file does not fit the OGR model, there is no container element at the root.
ERROR 4: ERROR parsing kml /home/jidanni/Downloads/planisphere_link.kml :This file does not fit the OGR model, there is no container element at the root.
ERROR 4: ERROR parsing kml /home/jidanni/Downloads/planisphere_link.kml :This file does not fit the OGR model, there is no container element at the root.
ERROR 4: ERROR parsing kml /home/jidanni/Downloads/planisphere_link.kml :This file does not fit the OGR model, there is no container element at the root.
ERROR 4: ERROR parsing kml /home/jidanni/Downloads/planisphere_link.kml :This file does not fit the OGR model, there is no container element at the root.
ERROR 4: ERROR parsing kml /home/jidanni/Downloads/planisphere_link.kml :This file does not fit the OGR model, there is no container element at the root.
```

**Comment by jidanni** [comment]
Now the tutorial says
> Close the Data Source Manager window

which once again is impossible.

![20230606T183423](https://github.com/qgis/QGIS-Documentation/assets/1230959/5e302f37-ae98-4438-8968-a5e8cc2ce5e8)

Here is my .config/i3/config
```
workspace_layout tabbed
focus_on_window_activation focus
set $mod Mod1
bindsym $mod+Up focus left
bindsym $mod+Down focus right
bindsym $mod+VoidSymbol workspace prev
bindsym $mod+Tab workspace back_and_forth
font pango:monospace 16
bindsym $mod+1 workspace number 1: SU
bindsym $mod+2 workspace number 2: uxterm
bindsym $mod+3 workspace number 3: Emacs
bindsym $mod+4 workspace number 4: $BROWSER
bindsym $mod+6 workspace number 6: FF
bindsym $mod+7 workspace number 7: Gimp
assign [title="^SU$"] number "1: SU"
assign [title="^uxterm$"] number "2: uxterm"
assign [class="^Emacs$"] number "3: Emacs"
assign [class="FF"] number "6: FF"
assign [class="Gimp"] number "7: Gimp"
for_window [class="^Google-chrome-unstable$"] move to workspace number "4: $BROWSER"
for_window [class="^Firefox$"] move to workspace number "6: FF"
for_window [class="^Gimp$"] move to workspace number "7: Gimp"

bindsym $mod+Return exec i3-sensible-terminal
bar {
    separator_symbol "     "
    status_command i3status
    workspace_min_width 200
    colors {
        inactive_workspace #900000 #000000 #009000
    }
}
floating_maximum_size 1000 x 500

bindsym $mod+0 workspace number 0: QGIS
assign [class="QGIS3"] number "0: QGIS"
for_window [class="QGIS3"] move to workspace number "0: QGIS"
```

**Comment by jidanni** [comment]
Here we see other users passing tips about how to close it.

https://gis.stackexchange.com/questions/277193/how-can-qgis-3-data-source-manager-automatically-close-after-load-a-layer

Therefore please add an X button, just in case none of the tips work for some users.

**Comment by jidanni** [comment]
In http://www.suzannakrivulskaya.com/qgis.html we see a red button to push to close the Data Source Manager
window, but alas i3 doesn't provide it, so please provide a second method.

**Comment by jidanni** [comment]
Tutorial says
> a Data Source Manager tab, enabled pressing the dataSourceManager Open Data Source Manager button (Ctrl+L);

How about a second ^L being a toggle to close it?

**Comment by jidanni** [comment]
![20230606T190717](https://github.com/qgis/QGIS-Documentation/assets/1230959/4faec0f6-97ec-4154-afb3-3dae7cbd4e7e)
The more things I try, the more windows are produced with no way to close. At the top you see three.

**Comment by DelazJ** [comment]
@jidanni Here a copy of my Data source Manager with browser enabled. As you can notice there an X button. so the issue is with your system. ![image](https://github.com/qgis/QGIS-Documentation/assets/7983394/672bf80e-5127-4633-9ec7-c0196db9bb17)
Also if you switch to another tab, there is a Close button at the bottom.
Anyway, button missing in GUI is either issue with QGIS code (though I never missed this on macOS, ubuntu, debian, windows) or your operating system, and you should report to where is appropriate. Not something related to the docs repo afaict. Same for the multi windows issue.
> No. Dragging and dropping assumes a windowing system that not all users have the same type of...
But I found I could still double click a sub item.

Great. But if you read through, you'll notice that both methods are used; this to show people that both are possible. We shouldn't restrain information because of some "limited" environments, right?
> The only unexpected thing is we had to download the .tif file for the coordinate system. The tutorial should mention that. Yes, the Details message guides us through it.

Humm, maybe, maybe not; You don't need to download that file to achieve the steps to get started. Things are also fine without.

At this point, can you try to summarize what issues **related to the docs**, if any, still need to be addressed, please? Thanks.

**Comment by jidanni** [comment]
ESC will close this,
as long as I haven't opened any menus yet.
Once I have clicked on '/' here,
![20230607T070611](https://github.com/qgis/QGIS-Documentation/assets/1230959/c5a3476b-d47f-4b6a-82ff-7a999f6dd3c3)
not even [mod+Shift+q](https://i3wm.org/docs/4.0/userguide.html) will close it for me.

**Comment by jidanni** [comment]
https://github.com/signalapp/Signal-Desktop/issues/1750#issuecomment-345420239 and we note the buttons on the bottom of this gimp dialoge,
![20230607T073645](https://github.com/qgis/QGIS-Documentation/assets/1230959/91c57dda-16d2-4131-b0c0-477620620ec8)

**Comment by DelazJ** [comment]
Afaics every **documentation** issues you raised are now covered. Let's handle code issues on code repo.

**Comment by Blenux** [comment]
You just need to add this below to close the window.

# Kill focused window
$bs $mod+Shift+q kill
