### ISSUE TITLE
Training data repository link/download not able to be extracted.

### ISSUE THREAD

**Issue by flydesigncg** [qgis/QGIS-Documentation#8338]
I am trying to learn how to use QGIS however the Training data repository files are not allowing us to open them after being downloaded.

Here is the link: https://github.com/qgis/QGIS-Training-Data/archive/release_3.28.zip

**Comment by DelazJ** [comment]
Hi @flydesigncg 
I just downloaded and unzipped susccessfully the file you linked above. It is a zip file so you need to unzip it, e.g. with 7zip or whatever tool is provided by your system. Do you get a specific error message? Is the file correctly downloaded (should around 235Mo)?

**Comment by flydesigncg** [comment]
> Hi and thanks @DelazJ for your quick help here. I am getting this error message, screenshot here...
![Screenshot 2023-06-12 at 4 47 31 PM](https://github.com/qgis/QGIS-Documentation/assets/136295112/d4725732-00fc-43f9-b1e5-33795a874e25)
