### ISSUE TITLE
Cannot set the criterion in Rule-based Classification section 3.3.5

### ISSUE THREAD

**Issue by MyGIS** [qgis/QGIS-Documentation#8374]
## Description

3.3.5. hard Follow Along: Rule-based Classification

In page 101 of the documentation pdf, I cannot get the criterion to run:

"landuse" = 'residential' AND "name" <> 'Swellendam' (or "landuse" = 'residential' AND "name" != 'Swellendam').

Checking if it is correct.

Page URL: https://docs.qgis.org/3.28/en/docs/training_manual/vector_classification/classification.html

**Comment by DelazJ** [comment]
@MyGIS What do you mean by "I cannot get the criterion to run"? What happens? Also, do we agree that `"landuse" = 'residential' AND "name" <> 'Swellendam'` and `"landuse" = 'residential' AND "name" != 'Swellendam'` are two ways to write the same expression and not a single expression to copy paste as a whole? (as displayed in the screenshot just below)

**Comment by MyGIS** [comment]
Below is a screenshot.


![image](https://github.com/qgis/QGIS-Documentation/assets/5960438/837b6bd1-9a33-4c43-accd-d6397393b7ae)
