### ISSUE TITLE
 Fix project unit confusion (pt 2): add project distance unit setting

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#843]
Original commit: qgis/QGIS@ddbdcf8 by nyalldawson

Adds a new option in project properties to set the units used for
distance measurements. This setting defaults to the units set in
QGIS options, but can then be overridden for specific projects.

The setting is respected for length and perimeter calculations in:
- Attribute table field update bar
- Field calculator calculations
- Identify tool derived length and perimeter values
- Default unit shown in measure dialog

Also adds unit tests to ensure that length and perimeter calculated
by attribute table update bar, field calculator and identify tool
are consistent wrt ellipsoidal calculations and distance units.

**Comment by SrNetoChan** [comment]
@DelazJ #893 fixes this, right?

**Comment by DelazJ** [comment]
Yes it does!
