### ISSUE TITLE
Fix project unit confusion (pt 3): add area unit settings 

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#844]
Original commit: qgis/QGIS@dfdcec8 by nyalldawon

Adds a new option in both the QGIS setting and project properties to
set the units used for area measurements. Just like the distance
setting, this defaults to the units set in QGIS options, but can
then be overridden for specific projects.

The setting is respected for area calculations in:
- Attribute table field update bar
- Field calculator calculations
- Identify tool derived length and perimeter values

Also adds unit tests to ensure that area calculated by attribute table
update bar, field calculator and identify tool are consistent wrt
ellipsoidal calculations and area units

**Comment by SrNetoChan** [comment]
@DelazJ created a new screenshot for this in #893

**Comment by DelazJ** [comment]
Thanks
