### ISSUE TITLE
C-API Error

### ISSUE THREAD

**Issue by abdul1969** [qgis/QGIS-Documentation#8455]
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem .

**Comment by DelazJ** [comment]
Hi @abdul1969 
This repository is for [QGIS docs](https://docs.qgis.org), and nothing related with compiling with numpy. So please find the correct repository for your issue/software and report there.
Thanks for understanding.

**Comment by abdul1969** [comment]
Thank you for your prompt response and guidance.
