### ISSUE TITLE
offline documentation

### ISSUE THREAD

**Issue by mshubrick** [qgis/QGIS-Documentation#8485]
## Description
please provide downloadable documentation for when you or I or not able to have internet access.

thanks

Page URL:

**Comment by DelazJ** [comment]
@mshubrick The QGIS project provides downloadable PDF and HTML zipped file at https://docs.qgis.org/3.28/pdf and https://docs.qgis.org/3.28/zip. You can download the HTML version and add it as "documentation path" in QGIS settings ( https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html#system-settings). Are you looking for something else? In which case please provide sufficient details...
