### ISSUE TITLE
[FEATURE] Add km, yards and miles to distance unit options

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#850]
Original commit: https://github.com/qgis/QGIS/commit/b2235938e6023d033caa1446c4d863203603b1ae by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by nyalldawson** [comment]
Hey @qgis-feature-tracker - it's totally self explanatory! ;)

**Comment by yjacolin** [comment]
Should be changed in "Options" and "Project properties" for length and area.
