### ISSUE TITLE
training_data.gpkg not valid

### ISSUE THREAD

**Issue by bakkerdm** [qgis/QGIS-Documentation#8544]
I'm using the training data.gpkg file from the training manual but it returns as "Layer not valid." 
No layers are shown. 
Copying the file to the Desktop as suggested by a previous user was not successful.
I installed on two Mac's and both have the same issue. I'm using QGIS 3.28

**Comment by agiudiceandrea** [comment]
Hi @bakkerdm, I cannot replicate the issue on Windows. Where have you exactly downloaded the training_data.gpkg file from? What is its dimensions in bytes? What is its CRC32 or MD5 or SHA-1 or... checksum/hash value? How have you installed QGIS on you macOS system (from qgis.org installers, or condaforge or macports, or...)?

**Comment by bakkerdm** [comment]
Thank you for responding, Andrea.
The file training_data.gpkg was extracted from the QGIS-Training-Data-release_3.28 zip file. Find the file enclosed. I have installed QGIS on my MacOS.


Dr. Derk Bakker
Associate Professor
Chairman Environmental Sciences Department
Forman Christian College (A Chartered University)
Ferozepur Road, Lahore
Pakistan. 54600

Email: ***@***.***

**Comment by agiudiceandrea** [comment]
> The file training_data.gpkg was extracted from the QGIS-Training-Data-release_3.28 zip file. Find the file enclosed.

@bakkerdm, it is not possible to provide a file to GitHub via e-mail.

Please use the GitHub web interface of this issue report at https://github.com/qgis/QGIS-Documentation/issues/8544 to attach the file (extract the training_data.gpkg from QGIS-Training-Data-release_3.28 zip without opening it with QGIS, and then put it in a training_data.zip file, and then create a new comment in this issue report using the GitHub web interface at https://github.com/qgis/QGIS-Documentation/issues/8544, and then drag & drop such file in such new comment).

Please also provide the text contained in the QGIS Help menu -> About window (click in the table, Ctrl+A and then Ctrl+C. Finally paste here).

**Comment by bakkerdm** [comment]
[training_data.gpkg.zip](https://github.com/qgis/QGIS-Documentation/files/12789643/training_data.gpkg.zip)<!DOCTYPE 

QGIS version | 3.28.11-Firenze | QGIS code revision | d1af706d752
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 10.15
  |   |   |  
Active Python plugins
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

</body></html>QGIS version
3.28.11-Firenze
QGIS code revision
[d1af706d752](https://github.com/qgis/QGIS/commit/d1af706d752)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.11.5
OS version
macOS 10.15




Active Python plugins
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

**Comment by bakkerdm** [comment]
![image](https://github.com/qgis/QGIS-Documentation/assets/146663396/5c3945ee-89e2-4961-8736-a689286f782a)

Screenshot of the message in the Browser

**Comment by agiudiceandrea** [comment]
@bakkerdm, I've downloaded the release_3.28.zip file available at https://github.com/qgis/QGIS-Training-Data/archive/release_3.28.zip (it has a dimension of 235629568 byte and has a CRC32 checksum value of 4D7D2971). In such zip file I've found the file training_data.gpkg which has a dimension of 2134016 byte and a CRC32 checksum value of AF2DA745. Such training_data.gpkg file can be imported in QGIS on Windows without issues. You will find it attached here: [training_data.zip](https://github.com/qgis/QGIS-Documentation/files/12794139/training_data.zip)


The training_data.gpkg file contained in the training_data.gpkg.zip file provided by you has a CRC32 checksum value of 7E3CAE0F and it is an invalid gpkg file.

It looks like you may have had an issue downloading the release_3.28.zip file, so the file(s) contained in it are corrupted. Please try again to download the release_3.28.zip file and check that it has the correct dimension and CRC32 checksum value.

**Comment by bakkerdm** [comment]
Thank you so much. That worked very well.
Derk



Dr. Derk Bakker
Associate Professor
Chairman Environmental Sciences Department
Forman Christian College (A Chartered University)
Ferozepur Road, Lahore
Pakistan. 54600

Email: ***@***.***

**Comment by agiudiceandrea** [comment]
This issue report can be closed now.

**Comment by bakkerdm** [comment]
Issue has been resolved successfully
