### ISSUE TITLE
Illegibility in dark mode

### ISSUE THREAD

**Issue by Graziano8890** [qgis/QGIS-Documentation#8591]
/# Description

**In QGis ltr 3.28.11 desktop version with dark interface (windows10&11) inside the advanced digitizing panel the numbers have the same background's color (dark gray). The numbers turn out to be almost illegible.** 

Page URL:

**Comment by DelazJ** [comment]
@Graziano8890 This is a Desktop issue so please report it at https://github.com/qgis/QGIS/issues. This repository is only for [documentation](https://docs.qgis.org/testing) purposes
