### ISSUE TITLE
fTools plugin was removed from QGIS

### ISSUE THREAD

**Issue by alexbruy** [qgis/QGIS-Documentation#860]
fTools was replaced by Processing. "Vector" menu now opens corresponding Processing algs. More details in QEP https://github.com/qgis/QGIS-Enhancement-Proposals/issues/54. Feel free to ask if more information is needed.

**Comment by yjacolin** [comment]
Does it mean that we should take care to replace 'fTools' by 'Vector'? Features in these menu are different? It seems not. Am I wrong?

**Comment by alexbruy** [comment]
IMHO more correct replacement will be "Processing", as now Processing plugin used instead of fTools.

Depending on what do you mean by "features" answer will be "yes" or "no": dialogs are different now, but algorithms itself are the same.

**Comment by yjacolin** [comment]
See http://docs.qgis.org/testing/en/docs/user_manual/plugins/plugins_ftools.html chapter.
