### ISSUE TITLE
Icons and substitutions are wrongly placed inside tip or note insert

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#864]
In any tip or note insert where an icon is used, it's always placed at the beginning of the line instead of near the related command. Examples:
- above http://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/editing_geometry_attributes.html#zoom-to-feature
- http://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/editing_geometry_attributes.html#node-tool
- above http://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/vector_properties.html#rule-based-rendering
- ...

**Comment by SrNetoChan** [comment]
This happens in many places.
@DelazJ maybe is related to this?
http://docutils.sourceforge.net/FAQ.html#is-nested-inline-markup-possible

**Comment by DelazJ** [comment]
Yeah, it might be that. The fix is then upstream. Should I close the issue?

**Comment by SrNetoChan** [comment]
No. Let's keep it open. Maybe try to get a workaround or something. It looks bad.
