### ISSUE TITLE
Document usable values in reclassify raster tables

### ISSUE THREAD

**Issue by baswein** [qgis/QGIS-Documentation#8650]
## Description
Values that can be used in reclassify tables are not documented (that I can find). 
So far I have found in addition to numbers **-inf**, **inf**, and **nan** can also be used. Before I take a crack at putting this in the documentation are there others or is there a place that already lists valid inputs.  Thanks!

Page URL:
https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/rasteranalysis.html?highlight=reclassify#reclassify-by-table

**Comment by DelazJ** [comment]
@baswein No, there is no place the possible input values are listed.
