### ISSUE TITLE
Harmonization of NoData 

### ISSUE THREAD

**Issue by baswein** [qgis/QGIS-Documentation#8656]
## Description
The documentation uses many variations of NoData e.g. nodata, Nodata, NODATA, no data, no-data. 
It seems like NoData is generally the preferred designation on the internet. This frees the term  "no data" to be used when we actually want to refer to the lack of data not the designation NoData.  

Page URL:

**Comment by DelazJ** [comment]
I think part of these inconsistencies originates from QGIS interface itself. It might be good to have the spelling fixed there (also|first). Wanna investigate that @baswein ?

![IMG_20231126_131453](https://github.com/qgis/QGIS-Documentation/assets/7983394/b7dcb1fc-6ee6-4da8-a8aa-a669415aab6b)

**Comment by baswein** [comment]
Sure - I'll take a look. 

Here is my what I've found so far as a comparison from other tools: 

- Grass documentation uses NULL rather than NoData
- GDAL documentation uses nodata
- Saga varies on the tool: No-Data or NoData
- OTB uses NoData
- Whitebox uses NoData
- Esri uses NoData

Here is some screen shots from QGIS showing the inconsitancy in the program. 
![image](https://github.com/qgis/QGIS-Documentation/assets/15817745/9de65f69-88e9-4374-8bbe-866b07dd2672)
![image](https://github.com/qgis/QGIS-Documentation/assets/15817745/74372ed4-f9f6-4589-823c-f76a6b0e44ee)

Personally I prefer NoData as it (to my eyes) clearly marks it as a designation similar to the all caps NULL.

**Comment by baswein** [comment]
Should I try to get feedback from the wider QGIS dev community? On the one hand it seems like a nitpicky thing. On the other I'm sure people have definite preferences. I have found with my students consistent language and spelling is helpful for them when they are learning concepts.
