### ISSUE TITLE
14.3.2 Georereferencer applied distortedly

### ISSUE THREAD

**Issue by yutaro-shimizu** [qgis/QGIS-Documentation#8715]
I am following the tutorial posted on [14.3.2. basic Try Yourself Georeference the Green Pixels Image](https://docs.qgis.org/3.28/en/docs/training_manual/forestry/stands_digitizing.html#basic-ty-georeference-the-green-pixels-image), but the `rautjarvi_green_georef` layer seems misaligned from the original map. Has anyone else run into the error and how did you solve it?

https://github.com/qgis/QGIS-Documentation/assets/68834841/65225e02-1336-458c-944f-1b9651f4181f

This is how I configured the georeference of the green pixel layer:
![スクリーンショット 2023-12-18 152524](https://github.com/qgis/QGIS-Documentation/assets/68834841/01c6a028-15d3-4b68-a6cb-3d630ddb5458)

All the GCP points are identical to those in the tutorial documentation and the CRS projection is set to `KKJ / Finland zone 2`.

**Comment by yutaro-shimizu** [comment]
![image](https://github.com/qgis/QGIS-Documentation/assets/68834841/ecbb759c-2af3-48f4-8b7f-e7c641b4e101)

I was able to identify the problem. It has to do with exporting the extracted green borders in the GIMP software. When extracting the green borders, the image dimension resizes along the x-axis by 500 pixels. Thus, the GCP points do not land on the same points as in the original `rautjarvi_map.tif` map. 

My tentative solution is to readjust the Source X coordinate in the GCP table manually. But I wonder if there's a way in GIMP to retain the original image size when exporting the file, so the user can still use the same `rautjarvi_map.tif.points`.

I would appreciate an extra clarification about this in the training manual. I'd be happy to contribute, but since this is my first contribution to any open source project, do you have an instruction on whether I'm encouraged to edit the manual, and if so how?

**Comment by selmaVH1** [comment]
Hello @yutaro-shimizu thank you for expressing your interest in contributing to the QGIS Training Manual. Here are the [documentation guidelines](https://docs.qgis.org/testing/en/docs/documentation_guidelines/index.html), where you can find instructions for updating QGIS documentation. 
Currently, I'm unable to provide an answer to your question about image size in GIMP, but I will try to figure it out.

**Comment by DelazJ** [comment]
@yutaro-shimizu Afaics you are supposed to copy paste the selected green elements in the same `rautjarvi_map.tif` file, not as a new file (see point 4.4 at https://docs.qgis.org/3.28/en/docs/training_manual/forestry/stands_digitizing.html#basic-fa-extracting-the-forest-stands-borders). I think that would make the export reuse the same extent by default. You may probably need to uncheck "save layers" checkbox in the export options...
PS: I'm not a GIMP expert and didn't replay the training manual. Just trying to find what is different from your process and the docs.
