### ISSUE TITLE
[FEATURE] Add setting for default attribute dialog view

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#875]
Original commit: https://github.com/qgis/QGIS/commit/f98b4ef635694b817e2f097b88ae70fc026d5f1b by nyalldawson

Options for table view, form view and remember last view

**Comment by DelazJ** [comment]
@yjacolin Sorry, I just remark you self-assigned this issue. Hope you didn't work on it yet.

**Comment by yjacolin** [comment]
no problem, I won't have time before next hackfest.
