### ISSUE TITLE
[FEATURE] Add a menu entry to zoom to a layer's scale range

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#878]
Original commit: https://github.com/qgis/QGIS/commit/556b621ad6b6daf943325296d74f6a4bc2842ea0 by pvalsecc

Unfortunately this naughty coder did not write a description... :-(

**Comment by nyalldawson** [comment]
Also see #885 - the menu entry was renamed

**Comment by SrNetoChan** [comment]
Is it ok to close #885 to clear the issues list a bit? The issue will be addressed at the same time as this one, so no need to have it open.

**Comment by yjacolin** [comment]
:+1:

**Comment by yjacolin** [comment]
Take care that layer should have set a Layer Scale Visibility to see the entry in the contextual menu.
