### ISSUE TITLE
[NEEDS-DOCS] Reword "zoom to layer scale" to "zoom to visible scale"

### ISSUE THREAD

**Issue by qgis-feature-tracker** [qgis/QGIS-Documentation#885]
Original commit: https://github.com/qgis/QGIS/commit/23cd2fcb4f41295fc44e24d5aad878a0c375d08b by nyalldawson

...makes it clearer what this does, as the original wording could be
confused with zooming to the layer's native scale/resolution

**Comment by SrNetoChan** [comment]
This will be addressed with #878, closing.
