### ISSUE TITLE
The description of the "Edit" menu is not up to date

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS-Documentation#8853]
## Description

The PR https://github.com/qgis/QGIS/pull/46687 (https://github.com/qgis/QGIS-Documentation/issues/7366 - https://github.com/qgis/QGIS-Documentation/pull/7724) removed various sub-menus and items from the "Edit" menu since QGIS 3.26, anyway such items are listed in the user guide as still part of the "Edit" menu.

https://github.com/qgis/QGIS/pull/46687/files#diff-7ed5bdfb153b1620af72f740d8879928a6de308849cc8e043785c64d3d727b23

- "Add Circle" sub-menu and contained items
- "Add Ellipse" sub-menu and contained items
- "Add Rectangle" sub-menu and contained items
- "Add Regular Polygon" sub-menu and contained items
- "Add Circular String" item
- "Add Circular String by Radius" item

See https://lists.osgeo.org/pipermail/qgis-developer/2024-February/066487.html.

Page URL: https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_gui.html#edit

**Comment by DelazJ** [comment]
Yep, I saw that. Do you think the removal was deliberate and necessary? Not avoidable?

**Comment by agiudiceandrea** [comment]
I don't know. We need to ask to @3nids.

**Comment by agiudiceandrea** [comment]
@DelazJ , this is fixed now. Isn't it?

**Comment by DelazJ** [comment]
Fixed in 3.28 as it is EOL and it wouldn't change anyway. So let's align docs and GUI.
For 3.34+, I'm waiting for @3nids feedback in order to know whether to proceed. The removal of these menu items appear nowhere in the discussion, so was it deliberate and/or necessary?
