### ISSUE TITLE
Consider different icons for Basic/Intermediate/Advanced in training manual

### ISSUE THREAD

**Issue by ioalexei** [qgis/QGIS-Documentation#8879]
## Description
I think the icons used to show which parts of the training manual are basic/intermediate/advanced are a bit confusing. 

To me, the icons suggest how far you are through the process (beginning, middle, end) rather than difficulty. 

I wonder if it would be more immediately comprehensible to use a star/circle rating - e.g. ★☆☆ /  ★★☆ / ★★★ or ⦿○○ / ⦿⦿○ / ⦿⦿⦿ ?

The icons are explained on the Introduction page ([1.2](https://docs.qgis.org/3.28/en/docs/training_manual/foreword/intro.html#tiered-course-objectives) but it's likely that a lot of people will go straight to the tutorial pages without reading the introduction, or arrive at them directly from a search. 

Alternatively, perhaps the current icons could be amended so that there is some other indication that they refer to a difficulty level - e.g. a text label or hover text that can show up?

**Comment by DelazJ** [comment]
> Worth a try. Just replace in substitution.txt, .. |basic| replace:: ★☆☆ and so on and you could be able to check if better.

While we can't show text during hovering of an image, this is possible with text. So I followed this approach in  #8916 and would appreciate your feedback @ioalexei.
