### ISSUE TITLE
Fonts (label) on map not clear when printing in pdf version

### ISSUE THREAD

**Issue by mmanafff** [qgis/QGIS-Documentation#8970]
Hi, 

Why does my map labels are not clear when printing especially when I export in PDF form? I have to export my map in high resolution (eg: 700pdi) to get a proper labelled map. Sometimes the PDF version looks okay on desktop but the fonts arent clear when I print it. Is there any settings that could help it to work in pdf version pls?

Thanks!!

**Comment by DelazJ** [comment]
Hi @mmanafff 
This repository is actually dedicated to [QGIS documentation](https://docs.qgis.org).
For help on desktop, please ask in qgis-user list (see [support channels](https://qgis.org/en/site/forusers/support.html)). You would need to provide some more details on your context (e.g. if you are using data from remote services, screenshot,...)
