### ISSUE TITLE
wrong version warning for qgis.core.QgsVectorLayer.fieldConfigurationFlags

### ISSUE THREAD

**Issue by pers-ephone** [qgis/QGIS-Documentation#8996]
## Description
This part of the documentation states _New in version 3.16._ but the [qgis.core.Qgis.FieldConfigurationFlag](https://qgis.org/pyqgis/master/core/Qgis.html#qgis.core.Qgis.FieldConfigurationFlag) it returns is _New in version 3.34._

the version warning should be _New in version 3.34._

Page URL: https://qgis.org/pyqgis/master/core/QgsVectorLayer.html#qgis.core.QgsVectorLayer.fieldConfigurationFlags

**Comment by selmaVH1** [comment]
Hello @pers-ephone, thank you for the information. However, this change is part of the [QGIS Python API documentation](https://qgis.org/pyqgis/master/index.html). Please, open an issue in this [bug tracker](https://github.com/qgis/pyqgis/issues).
