### ISSUE TITLE
@rownum variable not working in lesson 14.5

### ISSUE THREAD

**Issue by davidgilbertson** [qgis/QGIS-Documentation#9112]
## Description

Page URL: https://docs.qgis.org/3.34/en/docs/training_manual/forestry/systematic_sampling.html

This page refers to a variable `@rownum` which doesn't exist in the current QGIS version. There's now a `@row_number` variable but that appears to not work (in the preview, it is always `1`) and when I actually create the field, it doesn't populate at all.
![image](https://github.com/qgis/QGIS-Documentation/assets/4443482/47c86ab3-2f51-4482-abfa-3714c81e80ea)

![image](https://github.com/qgis/QGIS-Documentation/assets/4443482/a68a32c8-4195-4dae-8f50-dd57c5cd54c1)

**Comment by DelazJ** [comment]
@davidgilbertson Indeed, it should be @row_number (see #9113)
I tested the expression with another layer and it worked as expected. It however fails (I got Null values and not 'P_') when I also checked the "create virtual field" as you did in your screenshot. Mind unchecking that option, set appropriate field length and retry?

**Comment by davidgilbertson** [comment]
Yep, that works, thanks!
