### ISSUE TITLE
Portuguese (I think) is sprinkled through english documentation.

### ISSUE THREAD

**Issue by takezo39** [qgis/QGIS-Documentation#9128]
## Description

Portuguese (I think) is sprinkled through english documentation. For example, in the contents section (but also whole paragraphs elsewhere):

> ...  
> [One to many (1-N) relations](https://docs.qgis.org/3.34/pt_BR/docs/user_manual/working_with_vector/joins_relations.html#one-to-many-1-n-relations)
> 
> [Layers and keys](https://docs.qgis.org/3.34/pt_BR/docs/user_manual/working_with_vector/joins_relations.html#layers-and-keys)
> 
> [Definindo relações 1-N](https://docs.qgis.org/3.34/pt_BR/docs/user_manual/working_with_vector/joins_relations.html#defining-1-n-relations)
> 
> [Formulários para relações 1-N](https://docs.qgis.org/3.34/pt_BR/docs/user_manual/working_with_vector/joins_relations.html#forms-for-1-n-relations)
> 
> ...
> 

Page URL: https://docs.qgis.org/3.34/pt_BR/docs/user_manual/working_with_vector/joins_relations.html

**Comment by DelazJ** [comment]
@takezo39 Actually your link points to the (brazilian) portuguese version of the docs (see pt_BR in the URL). The languages are mixed because their translators not yet finished translating the docs, hence the English (source) strings.
