### ISSUE TITLE
[FEATURE] Parameterized svg support for composer svg images

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#913]
Original commit: https://github.com/qgis/QGIS/commit/0cdfca7d9b48951b6a3b80e6278a9046633246db by nyalldawson

This makes it possible to change SVG fill/outline color and outline
width when using parameterised SVG files such as those included
with QGIS (fix #10542)

(cherry-picked from ed3cb120087414906fd409049081950137116e1a)

**Comment by yjacolin** [comment]
@DelazJ are you sur this is for QGIS 2.14? cc @nyalldawson

**Comment by DelazJ** [comment]
@yjacolin yes
@nyalldawson cherry-picked it so unless there's an [issue](https://lists.osgeo.org/pipermail/qgis-developer/2016-March/042010.html), it should be available in 2.14.1

**Comment by yjacolin** [comment]
indeed, so I closed #913 ticket which is for 2.16 release.

**Comment by yjacolin** [comment]
@nyalldawson what is a parameterised SVG file?

**Comment by yjacolin** [comment]
See #704

**Comment by nyalldawson** [comment]
Here's a good explanation:

https://blog.sourcepole.ch/2011/06/30/svg-symbols-in-qgis-with-modifiable-colors

**Comment by yjacolin** [comment]
thank @nyalldawson I added it in the doc.
