### ISSUE TITLE
Export Save Feature as

### ISSUE THREAD

**Issue by KostasPrountzos** [qgis/QGIS-Documentation#9134]
## Description

In most cases (for me at least) when i export a layer and save it i want to remove the original temporary layer. why not have a toggle button in save window to remove the original layer after exporting it so we save clicks and annoyance ?

**Comment by selmaVH1** [comment]
Hello @KostasPrountzos this repository is only for documentation purpose, for feature request open issue [here ](https://github.com/qgis/QGIS/issues).
