### ISSUE TITLE
Problemi di visualizzazione geometrie

### ISSUE THREAD

**Issue by RG9700** [qgis/QGIS-Documentation#9135]
buongiorno,
durante lo zoom in scompaiono alcune geometrie (poligoni) dal progetto e conseguentemente le "Informazioni Elemento" non dà risultati.
Grazie, anticipatamente

**Comment by selmaVH1** [comment]
Hello @RG9700 please use English for communication. While we can translate your comment, this repository is intended to be in English. Anyway, as I understand the problem, you have geometry errors. You can perform [validity check](https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/vectorgeometry.html#check-validity) to identify errors in your geometry and that use the [fix geometries](https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/vectorgeometry.html#qgisfixgeometries).
