### ISSUE TITLE
Not Finding EPSG:2964 while setting CRS to work on Albers Equal Area for Alaska dataset

### ISSUE THREAD

**Issue by Amulya-Iyyapu** [qgis/QGIS-Documentation#9144]
I want to work on Alaska dataset as guided by the QGIS manual that is provided in the portal for which I am providing the link - https://docs.qgis.org/testing/en/docs/user_manual/introduction/getting_started.html In the sample session part i.e., 5.3 section that you'll find after opening the link mentioned above, there's a step to set the CRS since the data to be worked with (Alaska dataset) is in Albers Equal Area. But as I followed that step and opened the project properties and typed 2964 in the filter section, I'm not finding the corresponding predefined coordinate system which as mentioned in the guide should be NAD27/Alaska Albers with EPSG:2964. Is there anything that I have missed to enable that option or what should I do now? Please help!

Page URL: https://docs.qgis.org/testing/en/docs/user_manual/introduction/getting_started.html

**Comment by selmaVH1** [comment]
Hello @Amulya-Iyyapu,

Did you click the arrow next to the "Projected" to expand the menu with projections?
![image](https://github.com/qgis/QGIS-Documentation/assets/138306509/8fa5608a-2edb-4ef1-a8d6-7d81538676ec)
If that doesn't work, you can also find it manually. Go to Projected -> Albers Equal Area -> NAD27/Alaska Albers.
