### ISSUE TITLE
Requirement for LICENSE file when updating plugin is not documented

### ISSUE THREAD

**Issue by burkmarr** [qgis/QGIS-Documentation#9192]
It appears that there is a new requirement when updating a plugin that it must contain a license file with the name LICENSE with no file extension. It is not clear from the error message that a license filed called, for example license.txt, will not suffice. This is not documented in https://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/plugins/plugins.html. This problem has also been reported recently on Stackexchange (https://gis.stackexchange.com/questions/484049/cannot-find-license-in-the-plugin-package-error-when-updating-qgis-plugin/).

Page URL: https://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/plugins/plugins.html

**Comment by DelazJ** [comment]
Indeed it is about uploading to our plugins repo, but IMHO it could be nice to advise people earlier, at the beginning, to add a license file, along with other elements mentioned at https://docs.qgis.org/3.34/en/docs/pyqgis_developer_cookbook/plugins/plugins.html#set-up-plugin-file-structure
