### ISSUE TITLE
Special Tools Section in Vector Properties seem displaced

### ISSUE THREAD

**Issue by SrNetoChan** [qgis/QGIS-Documentation#921]
I think that the Special Tools section in the Vector properties dialog is not in the best position / order regarding the rest of the text. Like it is, users will start by reading some generic concepts/settings that make little or no sense if the user doesn't know (yet) what the Vector Properties Dialog contains.

Also, as suggested by @DelazJ the section name could be other.

https://github.com/qgis/QGIS-Documentation/edit/master/source/docs/user_manual/working_with_vector/vector_properties.rst#L21

**Comment by yjacolin** [comment]
We need probably think more about documentation on the next hackfest. I mean about the structure, what we can put inside, etc..

**Comment by SrNetoChan** [comment]
@yjacolin what do we do about this?

**Comment by yjacolin** [comment]
we need to:
* move the special tools at the end of the chapter
* find a  better name

I think that we should close this ticket as the same time than my PR.

So we need to find a name for the section! Proposition: Other tools. My PR has been updated following my comments.

**Comment by SrNetoChan** [comment]
Are they tools? or options or maybe settings?

I agree with the use of 'Other'

**Comment by SrNetoChan** [comment]
@DelazJ @rduivenvoorde ? Any opinion on this?

**Comment by DelazJ** [comment]
I would call them settings indeed:

* `Other common settings` (with the idea they are available from many parts in vector layer dialogs)
* `Other Special settings` or `Other particular settings`
* `Other Advanced settings` or `Other Advanced options`
* ...

**Comment by SrNetoChan** [comment]
I would say simply 'Other Settings'
