### ISSUE TITLE
Creating empty polygone causes minidump error.

### ISSUE THREAD

**Issue by aetor** [qgis/QGIS-Documentation#924]
In Qgis 2.14.0 (Essen) When I add a polygon in a shape without putting a character in the tabel, I get a MINIDUMP error and Qgis closes!  In 2.12, in the same file, I can do this without any problem. Also when I add one character in the tabel, it is no problem, only when the polygon is empty.

**Comment by DelazJ** [comment]
Hi,
This issue report is for [QGIS documentation](http://www.qgis.org/en/docs/index.html) (is something wrongly stated in the doc? A missing information?...)
If you want to report an issue on QGIS application itself, you should use the [QGIS issue tracking](http://hub.qgis.org/projects/quantum-gis/issues) following these [advices](http://qgis.org/en/site/getinvolved/development/bugreporting.html#bugs-features-and-issues)
