### ISSUE TITLE
Issue with Training Manual Exercise 14.6.9 - Atlas tool will only generate one-page PDF instead of multi-page

### ISSUE THREAD

**Issue by mgmark** [qgis/QGIS-Documentation#929]
When working through Lesson No. 14.6.9 (Follow Along: Printing the Maps) of the Forestry Application module of the QGIS 2.8 Training Manual, I noticed that QGIS 2.14 will only create a one-page PDF of the first map of the map series in the exercise and will not create a multi-page PDF atlas even though I have the 'Single file export when possible' box checked on under the 'Atlas generation' tab in the Print Composer.

Has anyone else encountered this issue while doing this exercise?  Since the Training Manual is for QGIS 2.8, could this be a compatibility issue in relation to using QGIS 2.14? 

On a side note, I am running QGIS 2.14 on Windows 7 Professional, SP1 with a 64-bit Operating System.

**Comment by DelazJ** [comment]
@mgmark Thanks for the report and sorry for the delay. 
Have you finally got this work? Actually there should not be compatibility issue for the atlas tool between the two releases (2.8 vs 2.14) so, as far as fields are well filled, things should work well.

**Comment by DelazJ** [comment]
Going through the manual instructions (all seems ok)  and the issue report, I wonder if the map item property "Controlled by atlas" was checked. If unchecked, I think the described behavior is normal. 
Atlas tool seems to behave normally so I'm closing this.
