### ISSUE TITLE
Outdated PDF files of documentation

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS-Documentation#9346]
## Description

For example for 3.34, the files date is 2024-03-03 https://docs.qgis.org/3.34/pdf/en/

https://docs.qgis.org/3.34/pdf/en/QGIS-3.34-DesktopUserGuide-en.pdf
![image](https://github.com/user-attachments/assets/c9f1f5a7-9456-4ff5-ba76-b900cb92c4f1)

https://docs.qgis.org/3.34/en/docs/user_manual/index.html
![image](https://github.com/user-attachments/assets/50db2a85-9298-4738-83fa-c268a72687e5)

**Comment by DelazJ** [comment]
There were some warnings due to redirected files at the end of the HTML build that made the pdf build not starting. Removed and restarted the build and afaict all is fine now
![image](https://github.com/user-attachments/assets/a51dfa4a-7d1b-49bd-9239-d63e14d712f6)
