### ISSUE TITLE
Add missing description of panels and toolbar

### ISSUE THREAD

**Issue by yjacolin** [qgis/QGIS-Documentation#935]
Adding a text under http://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html#panels-and-toolbars section + link from another part toward this chapter.

**Comment by DelazJ** [comment]
@yjacolin Is this still valid? What kind of text is (was) expected? Panels and toolbars are now mentioned in [QGIS GUI](http://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_gui.html#panels-and-toolbars) and [General Tools](http://docs.qgis.org/testing/en/docs/user_manual/introduction/general_tools.html#panels)

**Comment by yjacolin** [comment]
I think it is now ok as far I an see.
