### ISSUE TITLE
The last image on the 6.4.3. topic does not match the steps

### ISSUE THREAD

**Issue by EstherAraujo** [qgis/QGIS-Documentation#9368]
According to the guide, at the point of Image 1, the table shown in image 2 is not what results of a distance matrix calculation, it would be something closer to the Image 3, showing the the distance between the 3 input points to 2 of its neighbours. In order to get to the table shown in Image 2, there would be an advanced filter or even the extraction of data from the table of image 3 and its process through an SQL query.

Page URL:
Image 1:
![image](https://github.com/user-attachments/assets/85e31040-1355-4805-9ee2-32018bead14a)
Image2: 
![image](https://github.com/user-attachments/assets/7e2b42d2-b798-4f85-95f6-e065cd8e0081)
Image 3: 
![image](https://github.com/user-attachments/assets/21454c42-e8fc-4f80-9ed9-2386ee45c84d)

**Comment by DelazJ** [comment]
Hi @EstherAraujo 
I think that you didn't select the same "output matrix" option as in the image. You might have kept `Linear` instead of changing  to `Summary distance`.

_PS: please provide the page URL the next time. It makes checking easier. Thanks_
