### ISSUE TITLE
[Feature] Save readonly mode of vector layers in project

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#937]
Original commit: https://github.com/qgis/QGIS/commit/1c59eff12dfe0aa8824cf0e89535864c48ef1041 by m-kuhn

Unfortunately this naughty coder did not write a description... :-(

**Comment by m-kuhn** [comment]
In the project properties there is now a new column to control the readonly mode of layers. If checked, the layer will appear to the user as readonly, regardless of the dataprovider's capabilities.

**Comment by m-kuhn** [comment]
Screenshot here: https://github.com/qgis/QGIS/pull/2938#issuecomment-200422755

**Comment by yjacolin** [comment]
waiting for the PR #1320 been merged

**Comment by yjacolin** [comment]
waiting for the PR #1340 been merged
