### ISSUE TITLE
[feature] Allow using multiple columns in attribute forms

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#944]
Original commit: https://github.com/qgis/QGIS/commit/faf6b2654cf4887e093f4beb4cd6121fa78b4151 by m-kuhn

When using the drag and drop designer, a user can specify over how many
columns the fields should be distributed.

A double click on an existing group will allow adapting the value.

**Comment by m-kuhn** [comment]
for reference https://github.com/qgis/QGIS/pull/2962
