### ISSUE TITLE
[FEATURE][console] Improvements to find functionality

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#968]
Original commit: https://github.com/qgis/QGIS/commit/99210ecfd713f4380125c4ccfa0908142c8ee3a9 by nyalldawson
- add key shortcut to open find widget, set focus to find text input
  automatically (uses default shortcut for DE, eg usually Ctrl+F)
- add key shortcuts for find next/previous (using default DE
  shortcut, eg Ctrl+G/Shift+Ctrl+G)
- automatically find first match when typing in find box
- set initial find string to selection when opening find
- pressing Escape closes the find bar

**Comment by yjacolin** [comment]
@nyalldawson some questions: 
* what DE means?
* where or which console do you talk about in the title of your commit?

Ctrl+F works on several location (canvas on current layer, attribute table). Thanks.

**Comment by DelazJ** [comment]
Do not know what DE means but the PR is about the Editor panel in the Python Console.
I'm though unable to get result using Ctrl+G/Ctrl+Shift+G

> Ctrl+F works on several location (canvas on current layer, attribute table)

Not sure it's related to this PR and neither if this is the right place but some bug(?) reports below: trying a Ctrl+F with a layer opened (or selected) opens the Query Builder dialog:

* and the Search bar isn't opened in the Python Console
* the dialog opened is the one used in Layer Properties > General tab, to filter the layer. Applying the dialog "removes" from the layer the not returned features --> Ctrl+F filters the provider layer; it doesn't find features. 
Wouldn't that confuse users, given that in attribute table Ctrl + F switch to a dialog that really finds features, up to the user to select or filter (only in the current attribute table, not from the provider) ?

I also think that using the same icon for select/filter in attribute table vs "Filter Legend by map content" in layer panel is really confusing.

**Comment by yjacolin** [comment]
Thanks @DelazJ I successfuly made the ctrl+F working.

For the other remarks, please fill a bug report :)

**Comment by yjacolin** [comment]
DE could stand for Development Editor.

**Comment by DelazJ** [comment]
@yjacolin Yeah will check later if a report is not filled. I was just wondering whether there's something I did the wrong way and that @nyalldawson could let me know before any report. :)

**Comment by yjacolin** [comment]
DE stands for Desktop Environment.

**Comment by yjacolin** [comment]
@SrNetoChan I need screenshot here :)

**Comment by SrNetoChan** [comment]
@yjacolin  just an image of the console? or do you have anything in mind?

**Comment by SrNetoChan** [comment]
@yjacolin Screenshots added, let me know if you want me to do any change.
