### ISSUE TITLE
[FEATURE] Compilation support for unary - operation

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#969]
Original commit: https://github.com/qgis/QGIS/commit/0672abbaed506d96ffa5f3a6d3e51109e442ec5b by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by yjacolin** [comment]
@nyalldawson If I understand well, Expression now support unary expression? Like ```("field1" == 'something')? $perimeter: $length```, right?

**Comment by nyalldawson** [comment]
Nothing important for users here - feel free to close this.

**Comment by yjacolin** [comment]
ok thanks.
