### ISSUE TITLE
[FEATURE][styles] Add new style dock for interactive styling

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#976]
Original commit: https://github.com/qgis/QGIS/commit/831e7cd23633bf16a54b8175b35c76154ac1284f by NathanW2

Unfortunately this naughty coder did not write a description... :-(

**Comment by yjacolin** [comment]
Please, take care #1017 and #1018 as it is in the same area and feature.

**Comment by DelazJ** [comment]
Miss screenshot
