### ISSUE TITLE
Reorganise and/or update screenshots in vector labeling section

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#981]
The three screenshots in the [Label menu section](http://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/vector_properties.html#labels-menu) of vector properties chapter could be more related to the text: imho they should actually show smart labeling options that can be performed using placement or rendering options. They could be updated to really show what is labeled : map canvas might show cleanly labeled features ( [figure-labels-3](http://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/vector_properties.html#figure-labels-3) ), maybe using advanced options in other tabs or how labels rendering or placement can be fine tuned.

**Comment by SrNetoChan** [comment]
What do you think, if instead of showing the placement dialog, we create a mosaic of all the different positions with a reference geometry? I could do one for each geometry type.

**Comment by DelazJ** [comment]
I do not really see how you want to sketch it (we should avoid it being cluttered) but something that shows QGIS potential sounds better to me than just showing a dialog options (easily accessible to any user).

**Comment by SrNetoChan** [comment]
I will created an example asap

**Comment by SrNetoChan** [comment]
@DelazJ  something like this:

![line_placement](https://cloud.githubusercontent.com/assets/3607161/16749433/0e545092-47c2-11e6-901a-a6999ca9b1c5.png)

**Comment by DelazJ** [comment]
Nice! Let's do it that way!
