### ISSUE TITLE
Remove local content TOC from the PDF manuals

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#988]
Adding a TOC at the top of long pages in the documentation surely improves  the navigation. But these TOCs are also added in the PDF version of the doc, disturbing chapter's reading and increasing uselessly the number of pages.

**Comment by rduivenvoorde** [comment]
@DelazJ 

For some content we use the ".. only:: html" directive

http://stackoverflow.com/questions/2215518/conditional-output-in-sphinx-documentation

see

https://github.com/qgis/QGIS-Documentation/edit/master/source/docs/user_manual/working_with_vector/supported_data.rst line 27

Not sure if this works for a TOC though...

**Comment by DelazJ** [comment]
not sure if your second link is the right one but no worries I'm aware of this tip used especially to display figure title.
I can give it a try if someone helps me build docs with Paver on W10 (already done it successfully on W8) - see http://osgeo-org.1560.x6.nabble.com/Unable-to-build-QGIS-Website-with-Paver-td5262145.html

**Comment by yjacolin** [comment]
See #1138. I will make a PR for this.

**Comment by DelazJ** [comment]
@yjacolin does the solution keep the TOC in GitHub preview? This is an handy feature.

**Comment by yjacolin** [comment]
No, but do we want to have the same feature as the built html documentation? There is a lot of tag not well supported in github.

See https://github.com/yjacolin/QGIS-Documentation/blob/showTOCinHTML/source/docs/user_manual/working_with_vector/attribute_table.rst

**Comment by DelazJ** [comment]
In the past, there was a discussion about how to have gitHub preview preview to be as close as possible to html rendering to ease the process and attract new writers (no longer need to build doc). see http://osgeo-org.1560.x6.nabble.com/Qgis-community-team-Doc-writing-simpler-writing-and-styling-td5242930.html

This led to http://osgeo-org.1560.x6.nabble.com/Qgis-community-team-Doc-images-and-github-td5246998.html on which @rduivenvoorde worked that time before reverting.
I do personally find the TOC in the preview handy given that it helps to visualize the structure of the doc. Isn't there a way to keep it: a tag to add to html or a tag that exludes only pdf?
Whatever, I think that keeping the statu quo and thus the TOC in the PDF is worst than anything. So ok with that if not possible/

**Comment by yjacolin** [comment]
I looked for a tag to not export to PDF or another way, but can't find any. I am not against get 'preview to be as close as possible to html rendering' but quiet hard this time ;)

I wait a litlle bit and will merge it.

**Comment by DelazJ** [comment]
fixed in #1152
