### ISSUE TITLE
Show effects "in action" in the Draw effects section

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#994]
In http://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/vector_properties.html#draw-effects, we have exposed some screenshots.

1. some screenshots are almost the same in their options (Inner glow vs Outer Glow, Inner Shadow vs Drop Shadow). We should either get rid of the duplicate ~~and move the description of the effect near the remaining screenshot (done in #987)~~ or, see 2
2. It could be nice to set options of some of them so that reader can easily figure out how nice and funny things he can do with these options ( increase values, combine some effects...)

**Comment by SrNetoChan** [comment]
I will be showing the each type of effects always combined with source, so users can better see what it does. I will also exagerate some of the efects to make them more visible.

**Comment by DelazJ** [comment]
Good idea and thanks for taking this in charge @SrNetoChan

**Comment by SrNetoChan** [comment]
I'm at the halfway, I will have my all near by in case I have doubts.

**Comment by DelazJ** [comment]
Enjoy, dude!

**Comment by SrNetoChan** [comment]
@DelazJ please have a look.
