### ISSUE TITLE
[FEATURE] Make labeling map tools work with rule-based labeling

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#996]
Original commit: https://github.com/qgis/QGIS/commit/1a3e648e17c8e10a018bd97c91c31825705d693d by wonder-sk

(until now they worked just with simple labeling)

**Comment by yjacolin** [comment]
Nothing to do here as the documentation didn't tell that tools was not possible with rules-bases labeling. See http://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/vector_properties.html#using-data-defined-override-for-labeling
