### ISSUE TITLE
[FEATURE] add setting to control centroid fill point rendering
on all parts or a single part of multi-features (fixes #9199)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#998]
Original commit: https://github.com/qgis/QGIS/commit/fef8c1fef2ad60bf6f858b2253e57c463f40659e by nirvn

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment]
fixed in #1737
